### ISSUE TITLE
Fl_Tree: Line style "Solid"

### ISSUE THREAD

**Issue by michaelbaeuerle** [fltk/fltk#1008]
**Describe the bug**
I got a report from a macOS user that the Fl_Tree widget displays the connector lines incorrectly when the style is set to "Solid". 

**To Reproduce**
1. Run the FLTK test program "tree" on macOS with Cocoa and select connector style "Solid".
2. Error: The lines are drawn through the triangles that are used to open/close branches.

**Expected behavior**
The lines should be shorter (not drawn throught the triangles).

**Screenshots**
<img width="1157" alt="2024-06-29_fltk_tree" src="https://github.com/fltk/fltk/assets/81162390/370397ca-6c25-434f-a3a9-a0045588d3af">

**FLTK Version**
Some FLTK 1.4 snapshot (exact commit is unknown).

**Operating System / Platform:**
macOS (exact version is unkown).

**Additional context**
I have no macOS machine, maybe one of the developers can reproduce this behaviour.
Seems to be a Cocoa issue. With X11 it works as expected.

**Comment by erco77** [comment]
Can confirm, and just to be clear we're talking about this little line segment:
![image](https://github.com/fltk/fltk/assets/6484779/08f6cdc0-f599-449c-b37d-f1dd9aaef3b0)
Will follow up with a fix.

**Comment by erco77** [comment]
Should be fixed in 6776f89.

**Comment by erco77** [comment]
Closing this -- Michael, if you have any trouble, please re-open with new details.
