### ISSUE TITLE
Linux profiler shows fltk app spending more time in floor() than drawing pixels?

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#1015]
While using the linux profiler perf(1) to investigate a slowness problem in the Fl_Tree test program (when a lot of items, over 20k, are being scrolled -- issue #1014), I noticed the profiler reports 40% of the program's execution time is spent calling Fl_Scalable_Graphics_Driver::floor(), which seemed unusual.

This is more cpu time than spent in the graphics drawing code.
_Not sure if this is a distortion, perhaps due to how X11 drawing is done by the server, and not the client process, so functions like fl_rectf() and fl_point() may show very little actual cpu use._

Perhaps there's room for investigating optimization (e.g. skipping scale calculations if no scale is set) AFAIK on my system the FLTK scale is unset (default 1.0) and there's no window manager pixel scaling set.

Replication:

1. Using **fltk 1.4.x** current on **Linux (Ubuntu 20.04)** with X11 window manager, built FLTK this way:
```
    mkdir build-debug
    cd build-debug
    cmake -D CMAKE_BUILD_TYPE=Debug -D FLTK_BACKEND_WAYLAND=OFF ..
    make -j 4
```
2. Ran the bin/test/tree program in the profiler, e.g. `sudo perf record bin/test/tree`
3. Clicked on the '333' item
4. Clicked on "Add 20,000" button
5. Drag the scroller up and down over the 20k items about 10 times back and forth
6. Quit the program
7. Analyze the performance report, e.g. `perf report`
8. Use up/down arrow keys, and hit Enter twice to drill down into the function.. results:
    ![image](https://github.com/user-attachments/assets/652fc9ca-c91f-4220-b1d8-67109d1c9033)

    Hitting "Enter" twice on that first item to view the assembly for the floor() function shows the most expensive mul/add/cvt assembly operations in red:
    ![image](https://github.com/user-attachments/assets/c4ba8f37-c210-4241-ad2a-b46eff65e02b)

**Comment by erco77** [comment]
To elaborate: certainly /something/ has to take up most of the time when a program executes, I'm just surprised it's a floating point conversion function, and by a very large factor compared to the rest of the app.

**Comment by ManoloFLTK** [comment]
Go Wayland! 😊

**Comment by xuyun018** [comment]
I tested it on Ubuntu and the speed is good, but on Windows (Win2003, Win7, Win10), the speed is very slow.

**Comment by erco77** [comment]
Question: Does setting "Line style: Solid" speed things up?

_I don't currently have a windows machine available to me, but when I do I'll check._

**Comment by xuyun018** [comment]
> Question: Does setting "Line style: Solid" speed things up?
> 
> _I don't currently have a windows machine available to me, but when I do I'll check._

No, all default, If the item level >= 3, the speed is very very slow.

**Comment by ManoloFLTK** [comment]
What I see running tree under Windows11 for arm64 (in a VM on MacBook pro):
-with `Line style:Dotted`, about 1 sec to reply to "Add 20,000", and about 1 sec to reply to each click in the scrollbar; scrolling up and down over all tree nodes is essentially impossible;
-with `Line style:Solid`, apparently instantaneous for both operations; up and down scrolling is smooth.

**Comment by erco77** [comment]
@ManoloFLTK Ya, that's what I thought. I've pretty much ruled out Fl_Tree itself doing anything weird on changes in depth, other than drawing more of the dotted connection lines. And on my linux machine I did also see slightly faster response when Solid lines are used.

For dotted lines, I use `fl_point()` inside a small for() loop to draw the dotted connection lines (instead of `fl_line_style()` and `fl_line()`) so that for sure all dots draw only in odd pixel positions to ensure they all line up nicely when they connect. It works well, and I didn't think fl_point() would ever be cpu-expensive.

**Is it possible during the recent 1.4.x retooling, is it possible `fl_point()` might be a lot slower than it used to be?**

If fl_point() can't be optimized, I could maybe rewrite it to use solid light-gray lines to get a similar effect to the dotted lines, and make a note in the docs, but perhaps it would be worth investigating if there's a way to optimize `fl_point()`?

Regarding @xuyun018 's reply, he may not have understood my question due to a language misinterpretation (he replied in Chinese once). He may have thought I was asking if he was using Solid lines, and he said no, he only used the default. I don't think he realized I was asking him to /change/ the setting to Solid.

I now have access to a windows machine, so I'll try to do some tests, but I'll probably get the same result as @ManoloFLTK.

**Comment by erco77** [comment]
OK, yeah, can confirm changing `Line style:` to `Solid` gives very fast response, so for sure it's the default `Dotted` setting that's causing the slowness.

FWIW this is how I draw the dotted lines; `x,y1,y2` are all ints:
```
      y1 |= 1;                          // force alignment w/dot pattern
      y2 |= 1;                          // force alignment w/dot pattern
      fl_color(prefs.connectorcolor());
      for ( int yy=y1; yy<=y2; yy+=2 ) {
        fl_point(x, yy);
      }
```

@xuyun018 please try _changing_ the `Line style` to `Solid` in the test/tree program, and it should run quickly. You can change this in your own programs too. We'll investigate why the default `Dotted` setting is slow.

**Comment by erco77** [comment]
BTW, all these comments about Fl_Tree 20,000 items will need to be moved over to issue #1014.
_(The issue we're in right now, issue #1015, is a different but related issue on fltk profiling)_

**Comment by erco77** [comment]
In the original issue #1014 `in example "tree", button "Add 20,000", very slow` I summarized the above results.

So please continue all future discussion about Fl_Tree slowness in _that_ issue (not this one).

**Comment by ManoloFLTK** [comment]
@erco77 Could you, please, repeat the profiling measurement detailed above after the fix for long dotted lines (0291b48)? That would be to understand whether there's still an issue to be considered here.

**Comment by erco77** [comment]
I'll check, but I was satisfied with the floor() result from `perf report` because I'm thinking for those long 40,000 pixel long lines the bug was drawing mostly offscreen, the internals was calling `floor()` many many times per-point to find the post-scale x,y position, only to find the position off-screen.

**Comment by erco77** [comment]
Here's the current, post bug fix results for X11 (no wayland/no cairo) which predictably shows the `draw()` function being the highest cpu use:

![image](https://github.com/user-attachments/assets/8ca3f2f6-5f75-4f89-8c40-85d16649c461)

I imagine whatever cpu use is done by the actual drawing of graphics won't be shown because that's handled by the X server (Xorg).

So I'm going to close this out as "solved" because `floor()` was being rightfully flagged but only because of the Fl_Tree bug, and nothing about the internals.

I'm not sure how to do performance testing on Windows (the OP's situation), but I imagine Visual Studio has the ability to do this through the IDE somehow.

Profiling on Windows MIGHT be worth exploring if `SetPixel()` is perhaps more efficient than `fl_rectf()`. And if it is, it might even be worth pursuing if those optimizations (links I cited) might provide even better performance, since we primarily prize the "Fast" part of Fast/Light in F.L.T.K.

Perhaps such optimizations can be saved for post 1.4.0 release.

**Comment by erco77** [comment]
Interestingly, changing `Fl_Tree_Item_Array::total()` to be `inline` didn't change the performance report much:

![image](https://github.com/user-attachments/assets/aa626edf-9ee9-44a6-9057-926432bf366f)

The percentage use and position in the report are more or less the same, which tells me things must be pretty efficient now.

Since exercising the program is an interactive process (adding the 20k items and then scrolling up and down through them), it's not precisely repeatable, so the numbers will vary a bit between each report generation even when nothing is changed, but the percentages and positions remain mostly the same despite the attempt at `inline` optimization to remove function call overhead.

So it seems to not matter here, but _perhaps_ I should convert most of the Fl_Tree related simple "return a value" methods into being `inline`. Not sure; I know inline can cause trouble if, down the road, one wants to add more complexity to the methods and convert them to regular functions, as that affects ABI.

Certain methods will probably /never/ be made more complex, so those should probably be made `inline`. I figure if we decide to do that, we should perhaps do it across the board to /all/ widgets in a single pass, as a single commit.

I think what I'll do is close _this_ issue, and open a new RFE requesting an optimization pass at pre-1.4.0 release, since this is a good opportunity to break ABI.

Holding this from close to see what @ManoloFLTK and/or @Albrecht-S have to say..

**Comment by ManoloFLTK** [comment]
@erco77 Many thanks for these new performance results. This issue is good to close in my mind.

**Comment by erco77** [comment]
Great, thanks for the confirm.

**Comment by Albrecht-S** [comment]
I'm fine with the results and conclusions. Thanks for all the work on it to @erco77 and @ManoloFLTK for checking and commenting.

Greg, I suggest that you as the author take a closer look at `Fl_Tree` and `Fl_Table` etc. regarding inline methods, rather than - or before - opening another issue requesting to make more methods inline, just for practicability.

**_Rationale:_** I imagine looking at **all widgets** to make **_some methods_** inline would be tedious and maybe not worth the effort unless we know about any performance issues. Apart from that I believe that you can deal with "your" code quickly because you know which methods could be useful to make `inline`. I agree that only simple methods that are not supposed to become more complex should be made inline.

**Comment by Albrecht-S** [comment]
@erco77 I assigned you for reference only.
