### ISSUE TITLE
"Drawing Things In FLTK" docs: FL_SOLID shows confusing info

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#1016]
The "Drawing Things In FLTK" docs for FL_SOLID shows a weird dot pattern instead of a solid line:
![image](https://github.com/user-attachments/assets/0134e682-f7be-462e-b6fa-1801a7600323)

Investigating a correct fix.

**Comment by erco77** [comment]
Employed unicode line drawing, which improved the **HTML docs**:

![image](https://github.com/user-attachments/assets/b28bb73c-1dd2-49d2-8329-e04320cec29f)

..however unicode _is not well handled_ in the **pdf docs**, e.g.

![image](https://github.com/user-attachments/assets/637a3109-a769-476c-9e1b-ab77c27d0a8d)

I have to assume PDF generation not handling unicode is a bug in the doxygen/pdf generator, so closing this as "solved", despite that issue.

**Comment by Albrecht-S** [comment]
@erco77 FWIW, some thoughts:
1. doxygen supports `\htmlonly` and `\latexonly`, hence we could split the generation for both
2. if necessary we could use an image for the PDF version - or for both versions
3. this image could be created (a) from the HTML docs or (b) with a test/demo program that shows real drawings, similar to `test/line_style` but with all styles at the same time

Just my 2 ct.

**Comment by erco77** [comment]
Ya, I was thinking of drawing a diagram for all of the items, so that we can include info about the caps settings, but I was trying to keep the immediate changes simple. Was surprised PDF had trouble with unicode. I noticed severe problems with my diagrams in the Fl_Terminal docs that use unicode box drawing; all the unicode stuff is blanked out.

**Comment by erco77** [comment]
Reopening to investigate making an illustrated (drawn) diagram that includes showing the cap styles.

**Comment by erco77** [comment]
I'm not familiar with the different linestyles, so I need to write a small test program to exercise these options  so I can make screenshots for the diagram.

I don't see a unittest or demo program that covers this. Seems like all the line styles should be represented in the unittests, perhaps under a new category "Lines styles"?

In doing research for how to write this, I'm noticing our `fl_line_style()` docs don't even refer to the enum list of line styles (e.g. FL_SOLID, FL_DASH, etc).  Seems the enum is anonymous, so can't be referenced by name, so in e64e708 I've added an `\anchor` for the enum so it can be referenced.

**Comment by erco77** [comment]
Attaching [linestyle.cxx test program](https://github.com/user-attachments/files/16321864/linestyle.cxx.txt) which exercises the different line style types which I should be able to use to create the illustration image:
![image](https://github.com/user-attachments/assets/729c1c8f-92b0-4c0e-ba32-8b3ab9274285)

**Comment by erco77** [comment]
OK, committed 7f998ba which uses an image to replace the unicode box drawing "ascii art". In the docs, the results are html (left) and pdf (right):

![image](https://github.com/user-attachments/assets/e8a5c134-719d-40e6-ad5e-e4d566d40422)

**Comment by erco77** [comment]
Closing this, unless there's any problems..

**Comment by erco77** [comment]
Hmm, reopening: I'm noticing that when I view the enum docs, it just shows it as an anonymous name, which is kinda confusing as it's not clear what the enum is actually for.

![image](https://github.com/user-attachments/assets/50807e1d-f17e-4eb9-99f0-a18cabe81433)

Would it break anything to give the enum an actual name? Not sure what to call it because it's in the global name space, but maybe Fl_Line_Style or some such would be good. This way the docs are clear on what the enum is for.

Since this is 1.4.0, we could perhaps give names to all the anonymous enums so they're all documented properly. Just a thought.

**Comment by Albrecht-S** [comment]
> If we want to add this test program to the unittests as a new test item, someone open a new issue and I can probably address it.

@erco77 Greg, FYI, I worked on your test program and restructured it a bit so I could replicate an image similar to your screenshot above. The main reason was that I believe we should have the source code of all programs used to create images/screenshots for our documentation. I'm going to commit this shortly, together with some more documentation updates. I'm definitely **not** working on integration into unittests - although it might be useful.

Screenshot (Linux/Cairo/Wayland):
![fl_line_style](https://github.com/user-attachments/assets/6b1f7b06-17c5-4738-b9a3-dad5bf9715dd)

I hope you don't mind that it looks a little different than yours. I'll push the source code together with the documentation updates ASAP. It looks good both in HTML and PDF docs.

Regarding the enum names:
- I don't know if it could break anything if we added the names (I don't think so) but I agree that it's good to do it in 1.4.0 if there are more anonymous enums
- please wait a moment until I pushed my commit and then pull it, otherwise you might encounter conflicts.

**Comment by erco77** [comment]
Yes, I forgot to commit my 12cm changes for the PDF yesterday and was gonna commit them this morning but I got pulled into an afternoon with family, and when I got back you'd already fixed that, so great!

I see you committed the program I used to generate the docs as test/line_style_docs.cxx and added the table graphics I'd hand drawn in, so that's great too. Might be handy to check for regressions.

I also noticed this morning a left over bit of `fl_line_style()` ascii art that wasn't working, and replaced that too in dc95cd5 which I think should finish this issue, so re-closing.

**Comment by Albrecht-S** [comment]
> I also noticed this morning a left over bit of fl_line_style() ascii art that wasn't working, and replaced that too in dc95cd55c0513539c11ab1180219ab2cbcd802e1 ...

@erco77 I had noticed this too but I didn't know how to describe this in proper English, hence I left it open yesterday. Your wording looks good, now I understand all these details too. ;-)

I think it's time to update the online docs on the FLTK server again. Will do this soon...

**Comment by Albrecht-S** [comment]
> I see you committed the program I used to generate the docs as test/line_style_docs.cxx and added the table graphics I'd hand drawn in, so that's great too.

I first didn't know how to add the table graphics but I wanted to use `Fl_Grid` to simplify the layout which worked fine. Finally I noticed that I could use the background (box) color of `Fl_Grid` to "shine through" (in the margins and gaps) which made it really easy to colorize the frames around the boxes. Nice feature.

**Comment by erco77** [comment]
@Albrecht-S : It would make a lot of sense to move your very cool `test/line_style.cxx` demo into unittests.

I can probably do this; add a new unit test and remove the test program from the cmake files; I've created new unittests before, and I'm guessing I can remove the test program by looking into the commit that created it.

If that sounds good to you, I'll make a new issue so it can be tracked to completion.

**Comment by erco77** [comment]
> It would make a lot of sense to move your very cool test/line_style.cxx demo..

Oh, `line_style` isn't new, it's _really_ old.. weird I've never noticed it!
Perhaps let's leave it then. The new line_style_docs.cxx should perhaps stay as it is, or maybe we can create something like the unittests app to round up all the docs apps into one with a browser selector, so we don't have to generate so many test executables.

**Comment by Albrecht-S** [comment]
Yes, we can (and IMHO should) leave all this as-is for now.

In 1.5 we might want to structure all the test and demo programs better, e.g. by adding a `games` folder and maybe a `CMake` option to build the games or not.

The same could be done with a `screenshots` directory where all the programs used to create screenshots can be combined - again with a CMake option to build them or not.

I also wouldn't mind if we moved the original `test/line_style.cxx` into the `unittests` demo which could also use its own folder. Note that `test/line_style.cxx` predates `test/unittests.cxx` (2000 vs. 2004). I can't believer that the latter is already 20 years old.

Etc etc...

PS: such ideas would likely have a good place in GitHub Discussions under one of the `Development` or `Ideas` categories.
