### ISSUE TITLE
Fl_Tile::size_range seems to ignore maxw and maxh arguments

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#1025]
**Describe the bug**
Fl_Tile seems to get a new method `size_range` which has 2 overloads and accepts 5 params, the last two being optional for max width and max height.
Trying to set these seems to be ignored by the Fl_Tile however.

**To Reproduce**
Build the following program:
```c++
#include <FL/Enumerations.H>
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tile.H>

int main(int argc, char **argv) {
  auto *win = new Fl_Double_Window(600, 400);
  auto *tile = new Fl_Tile(0, 0, 600, 400);
  auto *b1 = new Fl_Box(0, 0, 200, 400, "B1");
  b1->box(FL_DOWN_BOX);
  tile->size_range(b1, 200, 400, 200);
  auto *b2 = new Fl_Box(200, 0, 200, 400, "B2");
  b2->box(FL_DOWN_BOX);
  auto *b3 = new Fl_Box(400, 0, 200, 400, "B3");
  b3->box(FL_DOWN_BOX);
  tile->end();
  win->end();
  win->resizable(tile);
  win->size_range(300, 100);
  win->show(argc, argv);
  return Fl::run();
}
```

After the window launches, you'll have 3 boxes. The first box cannot be made smaller, however it can be enlarged (which doesn't respect the size_range limit).

**Expected behavior**
The first box should be fixed (i.e can't be dragged).

**Screenshots**
N/A

**FLTK Version**
 - Version:1.4
 - If from Git, branch: master

**FLTK Configure / Build Options**
 - cmake -Bbin -G"Ninja" -DCMAKE_BUILD_TYPE=Debug && cmake --build bin

**Operating System / Platform:**
Windows 11 x86_64 running WSL2

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by MoAlyousef** [comment]
I checked the source code implementing Fl_Tile::size_range and it seems this is known at the moment. 

Should I close this issue?

**Comment by ManoloFLTK** [comment]
Apparently, these parameters are reserved for future use. They are documented as "currently ignored". I suggest this issue should be closed.

**Comment by MoAlyousef** [comment]
Thank you
