### ISSUE TITLE
FLTK-1.4: Some Tests crash

### ISSUE THREAD

**Issue by Micha-2021** [fltk/fltk#1029]
**Describe the bug**
Test-programs  "buttons" and "checkers" crash

Message:
libdecor-gtk-WARNING: Failed to initialize GTK
memory access error

**To Reproduce**
Simply run them

**Expected behavior**
Should terminate correctly

**FLTK Version**
 - Version: [e.g. 1.4.0]
 - Downloaded and self-built from: [e.g. Git, Snapshot and version, or tarball/zip]
 - If from Git, branch: [e.g. master, branch-1.3]

**FLTK Configure / Build Options**
Build with provieded options, there were no changes.

**Operating System / Platform:**
 - OS: Linux: Ubuntu 24.04

**Linux/Unix Runtime, if applicable:**
 - X11

No problems with Linux:Manjaro

**Comment by ManoloFLTK** [comment]
I just ran here `buttons` and `checkers` under Ubuntu 24.04 and the "Gnome on Xorg" desktop. No problem found.

Could you, please, double check, that all Linux packages required to build FLTK listed in section 2 of file README.Unix.txt are present on your system. If the crash continues, it would be useful to re-build FLTK in debug mode, run `buttons` under the gdb, and type command `bt` after the crash to get the backtrace at the crashpoint. Please, post this backtrace here. Post also you file `build/FL/fl_config.h`.

**Comment by ManoloFLTK** [comment]
@Micha-2021 It might be also useful to post here your file `build/CMakeCache.txt`.

**Comment by Micha-2021** [comment]
[CMakeCache.txt](https://github.com/user-attachments/files/16451449/CMakeCache.txt)
[fl_config.h.txt](https://github.com/user-attachments/files/16451459/fl_config.h.txt)

**Calllist before: libdecor-gtk-WARNING: Failed to initialize GTK**
libdecor_plugin_new(struct libdecor * context) (/home/gildemeister/Dokumente/fltk/libdecor/src/plugins/gtk/libdecor-gtk.c:2959)
fl_libdecor_new(struct wl_display * wl_display, const struct libdecor_interface * iface) (/home/gildemeister/Dokumente/fltk/libdecor/build/fl_libdecor.c:129)
Fl_Wayland_Window_Driver::makeWindow(class Fl_Wayland_Window_Driver * this) (/home/gildemeister/Dokumente/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:1431)
Fl_Wayland_Window_Driver::show(class Fl_Wayland_Window_Driver * this) (/home/gildemeister/Dokumente/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:427)
Fl_Window::show(class Fl_Window * this) (/home/gildemeister/Dokumente/fltk/src/Fl_Window.cxx:556)
Fl_Window::show(class Fl_Window * this, int argc, char ** argv) (/home/gildemeister/Dokumente/fltk/src/Fl_arg.cxx:330)
main(int argc, char ** argv) (/home/gildemeister/Dokumente/fltk/test/button.cxx:50)

**Calllist after segentation fault**
fl_libdecor_decorate(struct libdecor * context, struct wl_surface * wl_surface, const struct libdecor_frame_interface * iface, void * user_data) (/home/gildemeister/Dokumente/fltk/libdecor/src/libdecor.c:589)
Fl_Wayland_Window_Driver::makeWindow(class Fl_Wayland_Window_Driver * this) (/home/gildemeister/Dokumente/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:1433)
Fl_Wayland_Window_Driver::show(class Fl_Wayland_Window_Driver * this) (/home/gildemeister/Dokumente/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:427)
Fl_Window::show(class Fl_Window * this) (/home/gildemeister/Dokumente/fltk/src/Fl_Window.cxx:556)
Fl_Window::show(class Fl_Window * this, int argc, char ** argv) (/home/gildemeister/Dokumente/fltk/src/Fl_arg.cxx:330)
main(int argc, char ** argv) (/home/gildemeister/Dokumente/fltk/test/button.cxx:50)

Program received signal SIGSEGV, Segmentation fault.
0x0000555555640053 in fl_libdecor_decorate (context=0x555555739820, wl_surface=0x555555739770, iface=0x5555556b2248 <libdecor_frame_iface>, user_data=0x555555739700) at /home/gildemeister/Dokumente/fltk/libdecor/build/../src/libdecor.c:589
589		frame = plugin->priv->iface->frame_new(plugin);

**Comment by erco77** [comment]
OP, check to make sure you don't have a conflicting install of FLTK installed on your machine in /usr/include.

See if you have a `/usr/include/FL` directory, and if so, rename it away and rebuild FLTK cleanly, to ensure your build isn't picking up the wrong include files, as that can cause all kinds of weird crashing/memory problems.

**Comment by MoAlyousef** [comment]
This might be relevant:
https://gitlab.freedesktop.org/libdecor/libdecor/-/issues/65

How are you launching the built programs. It appears that the vscode terminal might set the GDK_BACKEND env variable to x11. Can you try launching with GDK_BACKEND=wayland ./path/to/buttons

**Comment by Micha-2021** [comment]
There was a /usr/include/FL indeed.
I removed it and rebuild fltk cleanly.
No improvement.

**Comment by ManoloFLTK** [comment]
Your backtraces show that you run these FLTK programs as Wayland clients (not as X11 clients as you wrote). That's very good, but you should be aware of that. Then, please check that all packages required listed in section 3.1 of file `README.Wayland.txt` are present on your system. I also strongly recommend you to install packages `libdecor-0-dev` and `libdecor-0-plugin-1-gtk`. Then, delete completely your build directory and relaunch cmake and make.

**Comment by Micha-2021** [comment]
I agree. If you start button outside VS Code, there are no problems.
Thanks for help.
