### ISSUE TITLE
CMake: Building FLTK with X11 Support

### ISSUE THREAD

**Issue by Micha-2021** [fltk/fltk#1037]
**Bug description**
Building FLTK-1.4 out of the box results in the following error message of CMake:
[cmake] CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[cmake] Please set them or make sure they are set and tested correctly in the CMake files:
[cmake] /home/gildemeister/Dokumente/fltk/src/OPENGL_INCLUDE_DIR
[cmake]    used as include directory in directory /home/gildemeister/Dokumente/fltk/src
[cmake] 
[cmake] CMake Error in src/CMakeLists.txt:
[cmake]   Target "fltk_gl" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/gildemeister/Dokumente/fltk/src/OPENGL_INCLUDE_DIR-NOTFOUND"
[cmake] 
[cmake]   which is prefixed in the source directory.

Please look at the configuration summary of CMake
[tm.txt](https://github.com/user-attachments/files/16513037/tm.txt)

**options.cmake**
The problem seems to be in options.cmake

...
**_if(FLTK_BACKEND_X11)_**
       set(OPENGL_FOUND TRUE)		**# very optimistic**
       find_library(OPENGL_LIB GL)		**# Not found**
	get_filename_component(PATH_TO_GLLIB ${OPENGL_LIB} DIRECTORY)
	find_library(GLU_LIB GLU)		# Not found
	get_filename_component(PATH_TO_GLULIB ${GLU_LIB} DIRECTORY)
	# FIXME: we should find a better way to resolve this issue:
	# with GL, must use XQuartz libX11 else "Insufficient GL support"
	set(OPENGL_LIBRARIES -L${PATH_TO_GLULIB} -L${PATH_TO_GLLIB} -lX11 -lGLU -lGL)
	find_path(OPENGL_INCLUDE_DIR NAMES GL/gl.h OpenGL/gl.h HINTS 
			${X11_INCLUDE_DIR}) **# Not found**
	unset(HAVE_GL_GLU_H CACHE)
	find_file(HAVE_GL_GLU_H GL/glu.h PATHS ${X11_INCLUDE_DIR})
**_else()_**
...

**Solution**
Make the NOT-FOUND libraries required

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version:1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: [e.g. master, branch-1.3]

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Out of the box -> no changes

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: Fedora
 - OS Version: 40

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

**Comment by Albrecht-S** [comment]
Thanks for the report, but this is a duplicate of issue #1001 which will be fixed soon. Please follow the development of issue #1001.

**Comment by Albrecht-S** [comment]
@Micha-2021 Please check if 60330a6d6f0cb396e694bf9353b4f116bd4b7213 fixes the issue for you. Please see https://github.com/fltk/fltk/issues/1001#issuecomment-2275773899 for details.

**Comment by Albrecht-S** [comment]
Reopened: I'm no longer sure that this is really a duplicate. It looks like the OP doesn't have all required libs installed and that the FLTK CMake process doesn't diagnose this well.

@Micha-2021 Please upgrade your FLTK installation to the latest Git `master`, at least to 60330a6d6f0cb396e694bf9353b4f116bd4b7213. Then try to rebuild and report if anything changed. If it doesn't build w/o errors please
- check if all required libs (dev packages) are installed, as mentioned in README.Unix.txt chapter 2.2
- post the entire CMake configure log from a clean build folder so we can see all messages

Thanks and sorry for the confusion (closing and reopening).

**Comment by ManoloFLTK** [comment]
I confirm that FLTK at current top of source code builds and runs OK under Fedora 40, both with the `Gnome` and the `Gnome or Xorg` desktops.

**Comment by Albrecht-S** [comment]
@Micha-2021 Please report what you found out with the latest FLTK version (see my request above). Otherwise this issue will be closed in a few days.

**Comment by Micha-2021** [comment]
This issue has nothing to do with other issues published here.

It describes the bad implementation in options.cmake, if X11 is used. See if (FLTK_BACKEND_X11)... in my first post.

2. line: set(OPENGL_FOUND TRUE) Not searched, but set to true
3. line: find_library(OPENGL_LIB GL) So what happend if the library is not found.
A better solution would be:
find_library(OPENGL_LIB GL REQUIRED) (See my solution point in my first post: Make the NOT-FOUND libraries required)
CMake would emit the message
CMake Error at options.cmake:640 (FIND_LIBRARY):
[cmake]   Could not find OPENGL_LIB using the following names: GL
So the user knows what is going wrong
CMake stops here.

Same with find_library(GLU_LIB GLU).

Similar problems with
find_path(OPENGL_INCLUDE_DIR NAMES GL/gl.h OpenGL/gl.h HINTS ${X11_INCLUDE_DIR})
and
find_file(HAVE_GL_GLU_H GL/glu.h PATHS ${X11_INCLUDE_DIR})
What happens if not found.

Everything is better then the std-message of CMake, see my first post.
May be someone can correct this and raise the FLTK build on a higher level.

I can't do that because of my limited time and knowledge of CMake.

So for me this issue is closed.

**Comment by Albrecht-S** [comment]
@Micha-2021 Many thanks for your comments. Improving the OpenGL and related stuff in our CMake files is on my to-do list, although with low priority. I agree that better diagnosis of missing dev files (headers) would be better and I'll try to do this independent of this issue.

I'm leaving this issue closed but I'll either open a new issue for improving our CMake procedure or add this to the other open CMake issues. Thank you.

**Comment by Albrecht-S** [comment]
PS: I hope you got your build working after installing the required `-dev` packages.

**Comment by Albrecht-S** [comment]
FTR, I added this issue to my list of "CMake fixes" (issue 655).
