### ISSUE TITLE
macOS: CMake cache inconsistency detected

### ISSUE THREAD

**Issue by bsdooby** [fltk/fltk#1046]
**Describe the bug**

When doing a CMake build of FLTK (head, from source) on macOS Sonoma (**macOS, 14.6, 23G80, arm64 AND x86_64)** , 
and try to reconfigure the cache w/ `ccmake .`, I get the following error (on all other platforms this is not an issue):

```
 FLTK configure: CMake cache inconsistency detected
 CMake Error at CMake/resources.cmake:78 (message):
   Please rebuild FLTK in a clean CMake build directory
 Call Stack (most recent call first):
   CMakeLists.txt:73 (include)

 Configuring incomplete, errors occurred!
```

**To Reproduce**

`/opt/local/bin/cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=14`

do some reconfiguration of the cache: e.g. change the build type to `Debug`

and try to reconfigure...

**Expected behavior**

No inconsistency should be produced, and the reconfiguration and the subsequent build should proceed

**FLTK Version**

commit `f151ecb87b8ecfca4bfcd352ff7590edf425666a`

**FLTK Configure / Build Options**

see above

**Operating System / Platform:**

see above; **CMake version 3.29.5**, **AppleClang 15.0.0.15000309**

**Comment by Albrecht-S** [comment]
Thanks for the report. This should not happen, I'll look into it.

**Comment by Albrecht-S** [comment]
This should be fixed by 9e35b0216f384f815284d6e8ee4ee9fcce3af01a.

@bsdooby Please test and confirm.

**Comment by bsdooby** [comment]
Hi,

Thank you for your quick response; I can confirm that the fix works
(tested on an old MacBook Pro, 17", macOS Sonoma (OCLP), max. OpenGL 3.0,
w/ latest AppleClang).

Cheers

**Comment by Albrecht-S** [comment]
@bsdooby Thanks for confirmation, closing now.
