### ISSUE TITLE
macOS: Undefined symbols ... `in libfltk.a[176](Fl_Native_File_Chooser_MAC.mm.o)`

### ISSUE THREAD

**Issue by bsdooby** [fltk/fltk#1047]
**Describe the bug**

When the (implicit) FLTK platform specific file chooser (context menu?) is used, the linking step produces the following error.
On all other platforms this is not an issue. **Older FLTK 1.4 version(s) (from 2022/23)**  on macOS (arm64, x86_64), using the exact 
same setup and the same application-specific source code **are linking just fine**.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UTType", referenced from:
       in libfltk.a[176](Fl_Native_File_Chooser_MAC.mm.o)
```

**To Reproduce**

source code on request

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 -B build`
`cmake --build build --clean-first -j`

**Expected behavior**

No undef. symbols, build/linking steps should proceed and produce a binary

**FLTK Version**

1.4.0; head; `f151ecb87b8ecfca4bfcd352ff7590edf425666a`

**FLTK Configure / Build Options**

**Operating System / Platform:**
 - OS: macOS, Sonoma, 14.6, 23G80
 - CPU: arm64 (or X86_64)
 -  AppleClang 15.0.0.15000309
 - CMake 3.29.5/3.30.2 (installed from MacPorts/binary from CMake.org)

**Comment by ManoloFLTK** [comment]
I don't succeed in reproducing this issue.
I successfully build under macOS 14.6 FLTK test apps, including native-filechooser, with CMake both with the make and the Xcode generators. I also successfully build native-filechooser using the fltk-config shell file that CMake produces.

I believe the key issue is that the link command you use includes 
`-weak_framework UniformTypeIdentifiers`
Can you report here the full link command you use?

**Comment by bsdooby** [comment]
Building FLTK and its demo apps works, and this is not the issue (CMake's
cache can also be modified now,
after the fix provided by Albrecht for Issue #1046:
https://github.com/fltk/fltk/commit/9e35b0216f384f815284d6e8ee4ee9fcce3af01a
)

This is the (common) call (which is identical for all our demo projects) if
using `cmake --build build --clean-first -j`

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
 -ggdb3 -O0 -Wall -Wextra -Wpedantic -Wnon-virtual-dtor -Wshadow
-Wconversion -Wsign-conversion -Wno-write-strings -Wno-deprecated-volatile
-ggdb3 -O0 -Wall -Wextra -Wpedantic -Wnon-virtual-dtor -Wshadow
-Wconversion -Wsign-conversion -Wno-write-strings -Wno-deprecated-volatile
-O3 -DNDEBUG -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk
-mmacosx-version-min=14.5 -Wl,-search_paths_first
-Wl,-headerpad_max_install_names
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/__/_COMMON/src/UtilFLTKInclude.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/__/_COMMON/src/UtilCPP.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/__/_COMMON/src/TrackBall.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/__/_COMMON/src/UtilOpenGL.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/__/_COMMON/src/UtilFLTK.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/src/CmdHandler.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/src/Geom.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/src/Graphics.cpp.o"
"CMakeFiles/CPP-13_D.02_RandomPlot.dir/src/RandomPlot.cpp.o" -o
/Users/username/workspaces/bfh/cis-compiler-test-suite/CPP-13_D.02_RandomPlot/bin/Release/CPP-13_D.02_RandomPlot
 -framework OpenGL -framework OpenGL
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/FLTK/lib/mac/x86_64/Release/libfltk.a
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/FLTK/lib/mac/x86_64/Release/libfltk_forms.a
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/FLTK/lib/mac/x86_64/Release/libfltk_gl.a
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/FLTK/lib/mac/x86_64/Release/libfltk_z.a
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/FLTK/lib/mac/x86_64/Release/libfltk_images.a
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/FLTK/lib/mac/x86_64/Release/libfltk_png.a
/Users/username/workspaces/bfh/cis-compiler-test-suite/_LIBS/GLEW/lib/mac/x86_64/Release/libGLEW.a
-framework Cocoa

```
What irritates me is the fact that our old FLKT libs (downloaded somewhere
around August 2023) are working with that project?

Adding to the above build/link command `-weak_framework
UniformTypeIdentifiers` does seem to help (contrary to what you suggest)?

**Comment by ManoloFLTK** [comment]
> What irritates me is the fact that our old FLKT libs (downloaded somewhere
around August 2023) are working with that project?

Removing a warning of deprecated API in macOS had obliged to render FLTK dependent on one more framework `UniformTypeIdentifiers`. Linking this framework with `-weak_framework
UniformTypeIdentifiers` rather than with `-framework
UniformTypeIdentifiers` allows to produce executables that can run both old and recent macOS versions without change.

> Adding to the above build/link command `-weak_framework
UniformTypeIdentifiers` does seem to help (contrary to what you suggest)?

Does it help?  My suggestion is that it should fix the link error.

How is the link command shown above generated? Is it by cmake applied to your project followed by make (your  posts don't make clear if cmake is used to build FLTK, your project, or both) ? If used for your project, do you use the relatively new "modern CMake" approach as explained in README.CMake.txt? A link command without `-weak_framework
UniformTypeIdentifiers` nor `-framework
UniformTypeIdentifiers` will fail for sure.

**Comment by bsdooby** [comment]
see inline comments

On Sat, Aug 24, 2024 at 8:52 AM ManoloFLTK ***@***.***> wrote:

> What irritates me is the fact that our old FLKT libs (downloaded somewhere
> around August 2023) are working with that project?
>
> Removing a warning of deprecated API in macOS had obliged to render FLTK
> dependent on one more framework UniformTypeIdentifiers. Linking this
> framework with -weak_framework UniformTypeIdentifiers rather than with -framework
> UniformTypeIdentifiers allows to produce executables that can run both
> old and recent macOS versions without change.
>
* Ah, I see. Thank you for the explanation (is it only me or is developing
on macOS becoming a real challenge?)

> Adding to the above build/link command -weak_framework
> UniformTypeIdentifiers does seem to help (contrary to what you suggest)?
>
> Does it help? My suggestion is that it should fix the link error.
>
* Yes, adding manually -weak_framework UniformTypeIdentifiers does help,
and it resolves our issue!

> How is the link command shown above generated? Is it by cmake applied to
> your project followed by make (your posts don't make clear if cmake is used
> to build FLTK, your project, or both) ? If used for your project, do you
> use the relatively new "modern CMake" approach as explained in
> README.CMake.txt? A link command without -weak_framework
> UniformTypeIdentifiers nor -framework UniformTypeIdentifiers will fail
> for sure.
>
* We built FLTK using CMake, and the link command (see above) for our
project is generated by CMake also (relying on the platform default
toolchain AppleClang): cmake -B build -DCMAKE_BUILD_TYPE=<...> -D...,
followed by cmake --build build --clean-first -j
* I quickly read the README.CMake.txt, but could not find anything "out of
the common"; maybe using the Xcode generator silently adds the
-weak_framework flag?

**Comment by bsdooby** [comment]
What is the "best" approach to adding -weak_framework UniformTypeIdentifiers
to the project? I just added an Apple-specific section that sets a variable
(not ideal IMHO) :/

**Comment by ManoloFLTK** [comment]
Please, make sure you follow instructions of section 3.4 of file README.CMake.txt when you construct your project's `CMakeLists.txt `file. Here, I have checked that I successfully build a client program using the native file chooser under macOS 14 with this CMakeLists.txt file:
```
cmake_minimum_required(VERSION 3.15)

project(native)

# optional (see below):
set(FLTK_DIR "/Users/XXX/Documents/fltk/fltk-git/build" CACHE FILEPATH "FLTK build directory")

find_package(FLTK CONFIG REQUIRED)

add_executable       (native WIN32 MACOSX_BUNDLE native-filechooser.cxx)
target_link_libraries(native PRIVATE fltk::fltk)
```
With this, no need to fiddle with an Apple-scpecific section of your CMake files; using modern CMake should automatically include `-weak_framework UniformTypeIdentifiers`in the link command of your FLTK client app.

**Comment by bsdooby** [comment]
Thank you for your suggestions and tips. I try to follow these instructions.
I guess you can close the ticket.

**Comment by ManoloFLTK** [comment]
@bsdooby  Closing. You can re-open if you still stumble on this error.
