### ISSUE TITLE
fluid: "Image Spacing" field label in properties editor is truncated

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#1050]
The "Image Spacing" field in fluid's widget properties editor under the Style tab is too long for the screen and is being truncated. Resizing the window doesn't help.

![image](https://github.com/user-attachments/assets/c30a9d78-684d-4450-a46b-128835cffd5c)

Platform: Linux
Fltk: 1.4.x-current

**Comment by MatthiasWM** [comment]
Ah, thanks. It's fine on macOS. I'll fix it.

**Comment by MatthiasWM** [comment]
Ok, so the title is now `"Image Margin:"`, and we have two additional fields the allow for a horizontal and vertical offset between the label and the widget.

**Comment by erco77** [comment]
Ah, thanks!

Yeah, I was curious how you were gonna fix that, either by making the font smaller or moving everything around. Looks like you found a shorter name for the field, and combined a few values into one; nice!

I see "Label Margin:" now, which looks like it came from commit ec05f78d98:

![image](https://github.com/user-attachments/assets/78d3b936-7d53-4905-a2a4-0afeed65c39f)
