### ISSUE TITLE
CMake: Investigate to replace check_function_exists() with check_symbol_exists()

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#1053]
The discussion of issue #1049 showed that it might be better to replace `check_function_exists()` with `check_symbol_exists()` because the former has some issues which are documented in CMake docs:
> Note:
> Prefer using [CheckSymbolExists](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html) instead of this module, for the following reasons: ...

For details see the docs:
https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html

The transition from `check_function_exists()` to `check_symbol_exists()` looks pretty straightforward but there may be some difficulties.
1. `check_symbol_exists()` requires an additional parameter: one or more include files as a CMake list
2. we need to find the correct header file(s) for each function
3. it is possible that we need to specify one or more libraries to link with
4. Points 2 and 3 may be platform specific (different headers or libs)
5. As of today there are 13 occurrences of `check_function_exists()` in our code.

**FLTK Version**
 - Version: 1.4.0 (Git)
 - Branch: `master`
 - Commit: 9568d5bb737eb468e87fd43f21404e2def101e30

**Operating System / Platform:**
All platforms, thorough tests required.

**Additional context**
Currently no issues are known but it would be good to change and test all occurrences.

I'm asking for help, volunteers would be very much appreciated because I'm too busy with other FLTK stuff. Volunteers should drop a note here and assign this issue to themselves. TIA.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thank you very much. What compiler suite did you use on Windows 11?
- [ ] classic MinGW (32-bit)
- [ ] MSYS/MinGW-64
- [ ] Visual Studio (which version?)
(you can check the check boxes above)

I'll try your patch and I can provide more tests:
- Debian 12 (Bookworm)
- Debian 12 - MinGW cross compiler
- Windows 10 (all build types mentioned above)

**Comment by ManoloFLTK** [comment]
I've checked relevant boxes above.

**Comment by Albrecht-S** [comment]
OK, patch tested and looks good. Platforms tested:

- Windows 10:
  - Visual Studio 2019
  - classic MinGW (32-bit)
  - MSYS/MinGW-w64 (64-bit)
- Debian 12 / Bookworm:
  - Linux/Unix (gcc)
  - MinGW cross compiler

I found a minor issue (diff in `config.h`) in VS-2019 where the old version didn't find `vsnprintf()` (`HAVE_VSNPRINTF`) and `snprintf()` (`HAVE_SNPRINTF`) but I verified that the new version is correct on my system.

@ManoloFLTK Thanks for your patch. Please feel free to commit and push it, or let me know if you want me to do it.
