### ISSUE TITLE
FLUID: easy resize of main window with subwindows.

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1055]
**Is your feature request related to a problem? Please describe.**
I am using fluid for the main UI of my application.  I designed it to be as small as possible, but now due to some menus, it needs to grow in size.  Changing min size does not scale it up.  Live Scaling does not seem to work either.  Also, I have some subwindows which would need scaling.

**I am using FLTK**
1.4 master

**Describe the solution you'd like**
I would like setting the min range in the UI to automatically resize the window and all attached subwindows.

**Describe alternatives you've considered**
None.

**Comment by MatthiasWM** [comment]
Thanks, that is a nice idea. I am sure I can write that.

Maybe holding a modifier key while resizing the window would be an easy UX to implement this (unless that interferes with desktop modifier key use)?

**Comment by ggarra13** [comment]
Personally, I would prefer typing numbers if possible, as I often find fluid messes up its undo queue when doing UI changes.

**Comment by MatthiasWM** [comment]
If you have repeatable situations where the Undo queue is messed up, please let me know so I can fix it. Thanks.

**Comment by MatthiasWM** [comment]
Ok, I implemented that as a checkbox menu item "Synchronized Resize" in the "Layout" menu. While the box is checked, all windows and groups interactively resize their children. If unchecked, groups and windows can be resized without changing the layout of their children. Please let me know if this works well for you.

Also added "undo" for window resizing.

**Comment by ggarra13** [comment]
It does not respect the groups' resizable off behavior, making them all scale.

**Comment by ggarra13** [comment]
It does not take the values of min size in Window behavior to have it scale with numbers.

**Comment by ggarra13** [comment]
Here's a complex .fl file for you to have it test the behavior.

[mrv2.fl.txt](https://github.com/user-attachments/files/16828036/mrv2.fl.txt)

**Comment by MatthiasWM** [comment]
Thank, I will look at those issues.

**Comment by MatthiasWM** [comment]
> It does not take the values of min size in Window behavior to have it scale with numbers.

Yes, this is on purpose. I believe that a more common workflow is resizing the window to a useful size, and the setting or overriding size_range. If FLUID would clip size changes to size_range, you'd have to unset size_range before resizing a window and the set it again.

But of course I am always open to user opinions ;-) .

**Comment by ggarra13** [comment]
> I tested your example code. There, both widget classes, `TimelineClass` and `PixelToolBarClass` are set to resizable.

Sorry.  I should have been more clear.  The issue was not with the widget classes but with the TopBar's groups (Gain, Exposure, Gamma, etc).  Those seemed to resize vertically when they shouldn't.

**Comment by ggarra13** [comment]
I see what the problem might be.  The Fl_Flex class for the main group was defined as Fl_Pack and overridden with a C++ class Fl_Flex as it was created before fluid supported Fl_Flex.  Changing it to Fl_Flex with emacs made the whole UI useless, as fluid takes the Fl_Flex and arranges all the groups vertically at the same size.
Is there an easy way to change the Fl_Pack to Fl_Flex without messing the UI?
