### ISSUE TITLE
FLUID: Grouping is broken, new Group is created at wrong location

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#1056]
**Describe the bug**
Select a few widgets and "Group" them. The resulting group is created too far up in the hierarchy

**Expected behavior**
The new group should replace the first (last?) selected widget

**FLTK Version**
1.4.master

**Comment by ggarra13** [comment]
Yep!  That's what I meant by fluid being broken.

**Comment by MatthiasWM** [comment]
FLUID: Fixes grouping and ungrouping, #1056

- grouping a bunch of widgets will now create the new
  group in the expected place
- also add grouping and ungrouping of menu items
- ungrouping now also works with only a few items 
  selected instead all items, moving the selection before
  the group
