### ISSUE TITLE
Wayland: menus in menubar have incorrect vertical offset if window is fullscreen

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#1061]
**Describe the bug**
Menus in menubar have incorrect vertical offset if window is fullscreen. They are shifted down by the height of the (now invisible) decoration. This may also apply to borderless windows (untested).

**To Reproduce**
In `test/menubar` comment out the size_range() line and add `window.resizable(G_tty); window.fullscreen();`, then open a menu in the menubar.

**Expected behavior**
Menus should be aligned with menubar.

**Screenshots**
[Grabación de pantalla desde 2024-09-04 05-54-03.webm](https://github.com/user-attachments/assets/941a1a6c-cea9-40ee-930a-4d0bb3f56a4f)

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4 master

**Operating System / Platform:**
 - Ubuntu 24.04 LTS

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
I believe that's a bug in Mutter, gnome's Wayland compositor. The compositor decides the location of popup windows such as menu windows according to so-called "constraints", and Mutter forgets that when a window is fullscreen, what was the screen top bar is a space where it's allowed to place windows. KWin, the compositor of KDE/Plasma, doesn't have this bug.

**Comment by ManoloFLTK** [comment]
Weston, another Wayland compositor, also doesn't have this bug.

**Comment by ManoloFLTK** [comment]
For me, the fix is  not to be searched in  FLTK.

**Comment by ggarra13** [comment]
@ManoloFLTK Can you report the bug upstream to Mutter, so it does not get lost?  You probably know better than myself what exactly is the issue.

**Comment by ManoloFLTK** [comment]
I don't intend to report this to Mutter.

**Comment by vanvugt** [comment]
It's already reported in https://gitlab.gnome.org/GNOME/mutter/-/issues/3652

**Comment by erco77** [comment]
@Vanvugt Yes: it seems @ggarra13 (here in this thread) is the same person who reported it on the gnome page (Gonzalo). Glad to see it's been reported!
