### ISSUE TITLE
FLTK's Fl_PDF_File_Surface device draws images without floating coordinates

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1062]
**Describe the bug**
Images drawn with fl_draw_image() or image->draw(X, Y) seem like they are drawn with integer coordinates, leading to pixelation.

**To Reproduce**
Here's two attached .pdfs.  One created by FLTK's Fl_PDF_File_Surface and one created with my previous LibHPDF code.  

[fltk.pdf](https://github.com/user-attachments/files/16912630/fltk.pdf)
[hpdf.pdf](https://github.com/user-attachments/files/16912631/hpdf.pdf)

The original data is the same.  LibHPDF handles automatic floating point scaling of the images.  Fl_PDF_Surface seems like it is using just integer math to layout the pixel of the images. 

**Expected behavior**
The images should be scaled with floating point.  This could be a feature request to have a fl_draw_image() function that uses floating point bilinear or bicubic scaling when saving to a PDF.

**Screenshots**

**FLTK Version**
Please complete the following information and delete non-applicable lines:
- 1.4 master

**Operating System / Platform:**
- OS: Linux

**Additional context**

**Comment by ManoloFLTK** [comment]
File hpdf.pdf is 11 MB whereas file fltk.pdf is 0.5 MB. I suspect the former contains pixel-rich images drawn to small rectangles whereas the latter has been drawn first copying pixel-rich images to small sized images and then drawing the resulting pixel-poor images to pdf.

To clarify this question, it's necessary to see the source code that produces fltk.pdf.

The way to draw pixel-rich images to potentially small areas while keeping all their pixel content is to refrain from calling Fl_Image::copy() and instead call Fl_Image::scale() to set the drawing size of the image and then Fl_Image::draw() to draw the pixel-rich image to a - large or small - area determined by the image's drawing size.

Attached files pixel-rich.pdf and pixel-poor.pdf contain a full-size and a shrink-before-draw versions of the same image drawn to approximately the same areas. The latter shows pixelation when zoomed in. The former has been produced by class Fl_PDF_File_Surface with Fl_Image::draw() called after Fl_Image::scale() was used.

[pixel-rich.pdf](https://github.com/user-attachments/files/16915149/pixel-rich.pdf)
[pixel-poor.pdf](https://github.com/user-attachments/files/16915115/pixel-poor.pdf)

**Comment by ManoloFLTK** [comment]
Function `fl_draw_image()` in essence cannot draw pixel-rich images to small areas because the pixel size of its arguments determines the size of the drawing area in drawing units. It's recommended very generally to avoid this function when drawing units and pixels of the output product don't match. That's what happens with HighDPI displays, PDF files, and PostScript printers.

**Comment by ggarra13** [comment]
@ManoloFLTK Thanks!!!  image.scale() was the trick I was looking for.  You might want to add a reference to it in image.copy() to clarify the difference.
