### ISSUE TITLE
CMake fails in CMakeLists.txt line 44 of unknown version of FLTK

### ISSUE THREAD

**Issue by ThothK** [fltk/fltk#1064]
Hello,

When I execute make several errors are generated

SurfaceGo3: FLTK_20221107: mkdir build
SurfaceGo3: FLTK_20221107: cd build
SurfaceGo3: build: cmake ..
This repeats a few times:
CMake Error at /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:192 (configure_file):
  Operation not permitted
Call Stack (most recent call first):
  CMakeLists.txt:44 (project)

Added both in the pastebin
https://pastebin.com/tYu48ndL

SurfaceGo3: build: make
make: *** No targets specified and no makefile found.  Stop.

**Expected behavior**
FLTK Libraries in the lib directory.

**Operating System / Platform:**
Debian 12

Thank you

**Comment by MatthiasWM** [comment]
**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: [e.g. 1.4.0]
 - Installed as package from: [e.g. Debian 11.4 Bullseye]
 - Downloaded and self-built from: [e.g. Git, Snapshot and version, or tarball/zip]
 - If from Git, branch: [e.g. master, branch-1.3]
 - If from Git, commit: [e.g. 7d58e2385452]

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed
by using CMake GUI tools (if any).
 - ./configure --enable-cairo ...
 - cmake -G"..." -DCMAKE_BUILD_TYPE=Debug ...

**Comment by ThothK** [comment]
Hello Matthias,

Thank you for responding.

I attempted to git clone the repository. I believe the master branch
SurfaceGo3: build: git clone https://github.com/fltk/fltk.git
This failed with:
error: chmod on /SG3Data/Source/FLTK_Git/fltk/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'

I downloaded the zip archive and unzipped it.
many failures:
chmod (directory attributes) error: Operation not permitted
inflating: fltk-master/.clang-format  fchmod (file attributes) error: Operation not permitted
inflating: fltk-master/ANNOUNCEMENT  fchmod (file attributes) error: Operation not permitted
...

I created a build directory, changed to it, and called cmake from within that directory. 
The errors are as stated in my original issue.

CMake version is:
SurfaceGo3: build: cmake --version
cmake version 3.25.1

**Comment by ThothK** [comment]
Hello Erco77,

Is /SG3Data/Source a directory tree provided by a remote file server? 
No, it is not.
The directory is on an exFAT disk which does not support chmod or chown level access control.

SurfaceGo3: Source: fltk-config --version
1.3.8
SurfaceGo3: ~: cmake --version
cmake version 3.25.1

Running CMake from within a different directory resulted in the expected build artifacts in build/bin and build/lib.

However, I believe the problem is still present.
After moving a fresh copy of the repository to /Source/FLTK_Git, creating a build directory, changing to it, and running cmake results in:

SurfaceGo3: build: cmake ..
CMake Error at /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:192 (configure_file):
  Operation not permitted
Call Stack (most recent call first):
  CMakeLists.txt:39 (project)

-- The C compiler identification is GNU 12.2.0
CMake Error at /usr/share/cmake-3.25/Modules/CMakeDetermineCCompiler.cmake:226 (configure_file):
  Operation not permitted
Call Stack (most recent call first):
  CMakeLists.txt:39 (project)

and results in the generation of
-- Configuring incomplete, errors occurred!
See also "/Source/FLTK_Git/build/CMakeFiles/CMakeOutput.log".
See also "/Source/FLTK_Git/build/CMakeFiles/CMakeError.log".

The two log files should be the same as what I linked to at pastebin.

**Comment by erco77** [comment]
I'd wait to see if Albrecht can reply on this, as he's our cmake expert.

But I'm thinking you'll continue to have problems if you continue to try to use git/cmake/make on an exFAT file system, which is basically an old DOS disk format, and is very limited, usually only used as a fallback for removable storage devices on windows machines, because of problems specific to NTFS, or some such. I don't think those problems exist for linux file systems like ext3/ext4, etc.

> The two log files should be the same as what I linked to at pastebin.

The paste bin logs are hard to interpret due to all the noise about the exFAT issues, and it's hard to tell how all those errors are impacting the build results.

You wrote:

> Running CMake from within a different directory resulted in the expected build artifacts in build/bin and build/lib.

I take that to mean "it worked" when you moved off exFAT? If so, unless I'm missing something, it sounds like that's the solution, and exFAT is the issue here.

But you also wrote:

> However, I believe the problem is still present.
> After moving a fresh copy of the repository to /Source/FLTK_Git, creating a build directory, changing to it,
> and running cmake results in [errors snipped]

Well yes, exFAT seems to be the issue, right? If you go back to using cmake on the exFAT file system, you're likely to encounter the same issues. Pretty sure _all_ the build tools expect a unix file system (not just git).

I'll let others answer, as I might be missing something.

**Comment by Albrecht-S** [comment]
> I'd wait to see if Albrecht can reply on this, as he's our cmake expert.

@erco77 I can't contribute much more than what you wrote already. I strongly suspect that building on an exFAT (or any FAT like) file system with CMake on Linux (or maybe even on Windows) is not supported, but this would be a question to ask the CMake guys (see more below).

From the first few lines of the posted build log:
```
SurfaceGo3: FLTK_20221107: mkdir build
SurfaceGo3: FLTK_20221107: cd build
SurfaceGo3: build: cmake ..
CMake Error at /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:192 (configure_file):
  Operation not permitted
Call Stack (most recent call first):
  CMakeLists.txt:44 (project)
```
 
This indicates clearly that the CMake `project()` call fails which must be one of the very first CMake commands in every CMake project. **This is not FLTK specific.** I assume that you could create a very short CMakeLists.txt file consisting only of the `project(..)` line and it would fail in the same way.

> I take that to mean "it worked" when you moved off exFAT? If so, unless I'm missing something, it sounds like that's the solution, and exFAT is the issue here.

Yes, that's my assumption too, unless we misunderstood the statements of the OP (i.e. if the build folder is not on an exFAT system).

@ThothK You should be able to build FLTK or any other CMake project (if that project is written correctly) with the **_source folder_** on any filesystem, even read-only ones, if you locate the **_build folder_** on a supported, writable, filesystem. Usually your home folder should be on a Linux compatible filesystem, i.e. you could locate the build folder below your home directory and you should be fine, for instance:
```
cd $HOME  # or just `cd`
cmake -B fltk-build -S /path/to/fltk-source
cd fltk-build
make [-jN]
```

Please close this issue if this solves your problem.

**Comment by ThothK** [comment]
Hello Albrecht-S,

Thank you for answering.

I am going to go with this not being an FLTK specific issue. However, I recently spent a considerable amount of time implementing a CMake build system with all of the files on an exFAT drive. I experienced no issues with this. 

The B and S switches are new to me and using them I did not experience the errors above.

Thanks
