### ISSUE TITLE
fl_read_image() missing right and bottom pixel line

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#1066]
**Describe the bug**
`fl_read_image()` does not capture the right and the bottom image line of a window.

**To Reproduce**
Use the attached test program, which displays the result of fl_read_image() in a magnified window:
[read_image_missing.cxx.txt](https://github.com/user-attachments/files/16946411/read_image_missing.cxx.txt)

**Expected behavior**
The blue rectangle should be contained completely in the image captured by fl_read_image().

**Screenshots**
This is a magnified version of a screenshot taken from the program:
![grafik](https://github.com/user-attachments/assets/e0d6c24e-dccc-42bc-b8f2-20391b5c80b5)

This is the magnified fl_read_image() output of this program:
![grafik](https://github.com/user-attachments/assets/3d89bb41-9f8a-434d-93b9-9b668d9199a2)

As can be seen the blue rectangle is not complete.

**FLTK Version**
Version: 1.4 git master

**Operating System / Platform:**
Ubuntu 20.04

**Linux/Unix Runtime**
 - Wayland
 - X11
 
**Additional context**
With FLTK 1.3 this is correct.

**Comment by ManoloFLTK** [comment]
@wcout The issue should be fixed with the commit mentioned above. Please, close issue if you confirm.

**Comment by MatthiasWM** [comment]
Thanks!
