### ISSUE TITLE
Wayland random crash on exit

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1073]
**Describe the bug**
When exiting my application, I sometimes get a Wayland crash.

**To Reproduce**

**Expected behavior**
No crash.

**FLTK Version**
1.4.0 master

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Additional context**
Attached stack trace on crash on exit:
[stack_trace_on_exit.txt](https://github.com/user-attachments/files/16989903/stack_trace_on_exit.txt)

**Comment by ManoloFLTK** [comment]
Could you detail in what context does your program call function exit()?

**Comment by ggarra13** [comment]
I am closing the issue as it seemed related to the startup pointer de-reference crash from issue #1072.
