### ISSUE TITLE
1 BUG in windows, and 1 bug in Ubuntu.

### ISSUE THREAD

**Issue by xuyun018** [fltk/fltk#1075]
FLTK version: 20240920

BUG 1:
In the Windows system, double clicking on the title bar maximizes the window, causing the Tabs page to switch from "TestPage11" to "TestPage12". This situation does not occur in Ubuntu.

![2024-09-23-19-00-17](https://github.com/user-attachments/assets/72d624dc-ead5-481a-be9e-12f186e94b87)

BUG 2:
The Chinese display is incorrect, the title bar is displayed correctly, but using the function fl_draw displays garbled text.
Ubuntu:
![linux bad](https://github.com/user-attachments/assets/7db3537d-bc93-419a-8bd8-8cce13841c6c)
Windows:
![windows ok](https://github.com/user-attachments/assets/78f87680-d713-41a7-aa0a-5a8e9e1b85af)

Source code:
[fltk_20240923.zip](https://github.com/user-attachments/files/17096734/fltk_20240923.zip)

**Comment by ManoloFLTK** [comment]
About what you call the Ubuntu bug:

The recommendation to work easily with non-ASCII characters is to install package `libpango1.0-dev` in your Ubuntu system and to build FLTK with the Pango option, running cmake -with `-DFLTK_USE_PANGO=1`
Once this is done, all UTF-8 character strings, including CJK, right-to-left scripts, hindu, etc…, are rendered correctly by function `fl_draw()`. Also, it's not necessary to translate constant strings like this `"\xe5\xae\xbd\xe6\x9d\xbe\x00"`, you can type the 2 chinese characters directly in the source code.

**Comment by ManoloFLTK** [comment]
> The title bar display is correct, but using the function 'fl_draw' displays garbled text. 

It displays garbage because you have not turned on the FLTK_USE_PANGO option when building the FLTK library. Function fl_draw() will produce correct text with this option is turned On. For this option to be usable you MUST have package `libpango1.0-dev` installed in your system.

> Can the same process be applied?

The same as what?

**Comment by erco77** [comment]
The title bar isn't drawn by FLTK, it's drawn by different software (the window manager), so its font abilities may be different from FLTK's. For FLTK to draw correctly, do what manolo said to be sure FLTK can properly render CJK..

**Comment by erco77** [comment]
The tab changing problem does seem like a bug in fltk where the mouse button release event on the second click on the titlebar is leaking into FLTK, causing the tab that is under the mouse after the resize to be selected.

**Comment by ManoloFLTK** [comment]
The "bug in windows" should be fixed with commit mentioned above.
@xuyun018 Please, close issue if you confirm both reported problems are fixed.
