### ISSUE TITLE
FLUID: undo + save may screw up .fl files

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1078]
**Describe the bug**
FLUID is currently buggy either with undo or with saving, as it will re-arrange the #include lines, sometimes sending them to the bottom or middle of the .fl file, leading to symbols not being found on compile. 

**To Reproduce**
I still don't know *exactly* what causes it.  It seems a combination of adding an include, undoing and saving.

**Expected behavior**
Not screw up the .fl file.

**FLTK Version**
 - 1.4 master

**Comment by MatthiasWM** [comment]
Thanks for the report. If you could find a way to reproduce this, it would be very helpful. I _did_ change some ordering code recently, fixing another bug, so this may very well be related.

**Comment by MatthiasWM** [comment]
Could you please check if f285712 fixes the issue? Thanks.

**Comment by MatthiasWM** [comment]
FLUID was a quick hack and small app that has grown into something much much bigger over the years. I try to modernize things over time. One issue to refactor is the use of global variables. `force_parent` was such global variable that had an influence on positioning children when pasting from a file. 

When importing type nodes form a file (merge, paste, duplicate), the location of the first inserted node depends on the current node and its type, and the node to insert. You can't make an Fl_Menu_Item a child of Fl_Window, for example. That code needed some work to make paste and duplicate run correctly (e7f1247552fbb9d056d4c68eb51564a504df3161). 

When I fixed that, I saw that the global variable `Fl_Type::current` is misused in the file reader as the current insert position. I was able to fix that partially by adding an `anchor` parameter in some places, but did not fix this all the way. As a result, when reading a file, and that file would change `Fl_Type::current`, all further positioning would be off. 

I did see that when I wrote the code, so I updated `Fl_Type::current` after every widget I read (https://github.com/fltk/fltk/blob/5c6ec56b33d9eb5a9261eb72128d86f8e6ff5305/fluid/file.cxx#L412). Or so I thought. The old version of this line https://github.com/fltk/fltk/blob/5c6ec56b33d9eb5a9261eb72128d86f8e6ff5305/fluid/file.cxx#L387 called continue, skipping the code that I added.

So new on my list to refactor is the use of `goto` and `continue` in `Fd_Project_Reader::read_children` besides the elimination of `Fl_Type::current`.

**Comment by Albrecht-S** [comment]
@MatthiasWM Your explanation sounds interesting, but I think @ggarra13 wanted to know what **operation** triggered the bug, and very likely also which constellation in an input (.fl) file was needed to reproduce the bad behavior. If you could tell a way to trigger the issue in the old code Gonzalo might be able to reproduce it with his own .fl file. Or something like that.

**Comment by MatthiasWM** [comment]
LOL, yes, I guess I was tired. The bug happens when a file is read, and a node in that file is marked as selected. All widgets after the selected one will be loaded in reverse order until a widget is loaded that can have children, which resets Fl_Type::current, so the remainder of the file is read correctly. Unless there is another selection.

Yes, this may have messed up some .fl files over he last two week. Apologies for that and the adventures of beta software.

**Comment by Albrecht-S** [comment]
@ggarra13 Can you confirm that your issue is fixed with the new information posted above? TIA.

Note that this is **currently** the last issue in our [release milestone](https://github.com/fltk/fltk/milestone/1) (although there may be other issues that need fixes before the release). But anyway, it would be great if we could close this issue.

**Comment by ggarra13** [comment]
I'll do a test this afternoon and let you know either this evening or tomorrow.

**Comment by ggarra13** [comment]
Seems to work fine in all the manual tests I did.  You may close the issue.

**Comment by MatthiasWM** [comment]
Thanks for verifying
