### ISSUE TITLE
Commit 6e5f3f7ecb3cc0039e113a5e3b2409ba0f7e7cea breakes build because configure does not detect that cairo is missing (Linux)

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#1087]
Compiling drivers/Xlib/Fl_Xlib_Graphics_Driver_font_xft.cxx...
In file included from drivers/Xlib/Fl_Xlib_Graphics_Driver_font_xft.cxx:21:
drivers/Xlib/../Cairo/Fl_Cairo_Graphics_Driver.H:25:10: fatal error:
cairo/cairo.h: No such file or directory
     25 | #include <cairo/cairo.h>

**FLTK Configure / Build Options**
./configure

**Operating System / Platform:**
Xubuntu 24.04

**Linux/Unix Runtime, if applicable:**
X11

**Comment by ManoloFLTK** [comment]
@gnuwimp Please, close issue if you confirm it's fixed with the commit mentioned above.
