### ISSUE TITLE
FLUID: Live Resize Preview of Grid Widget Causes Segfault.

### ISSUE THREAD

**Issue by 4ffy** [fltk/fltk#1092]
**Describe the bug**
Attempting to view the live resize preview of a Grid widget or a group with a Grid descendant in FLUID causes the program to crash with a segmentation fault.

**To Reproduce**

1. Use the following FLUID file (can't attach) or start a new project and add a Class→Function→Window→Grid hierarchy with default options.
2. Click on the Grid to bring up its properties window.
3. Click on the "Live Resize" button.
4. Segfault.

```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {.h}
code_name {.cxx}
class UserInterface {open
} {
  Function {make_window()} {open
  } {
    Fl_Window {} {open
      xywh {1057 749 480 320} type Double visible
    } {
      Fl_Grid {} {open selected
        xywh {25 25 240 160}
        dimensions {3 3}
      } {}
    }
  }
}
```

**Expected behavior**
No segfault. A working preview.

**FLTK Version**
 - Version: 1.4.0rc1
 - Downloaded and self-built from: tarball

**FLTK Configure / Build Options**
```shell
cmake -DCMAKE_BUILD_TYPE=Debug -DFLTK_BUILD_TEST=OFF -B build
cmake --build build
```

**Operating System / Platform:**
Arch Linux

**Additional context**
No other widget has issues. I tried debugging the program to see where the segfault happens, but it seems that I don't get the necessary debug symbols even with build type set to debug. I don't know what to do about that.

```
Thread 1 "fluid" received signal SIGSEGV, Segmentation fault.
0x00005555557e7470 in typeinfo for Fl_Help_View ()
```

**Comment by MatthiasWM** [comment]
Ok, looking at this right now. It crashes in `Fl_Widget_Type::propagate_live_mode(Fl_Group* grp)` tying to call the virtual function `copy_properties()`. The vtable of the object seems to have been corrupted. I will continue my research.

**Comment by MatthiasWM** [comment]
@4ffy : I added the missing code for live resizing of Flex and Grid widgets. My short test seems fine. Could you please verify that the new code works for you as well. Thanks.

**Comment by 4ffy** [comment]
That seems to work for me. I am no longer getting any crashes.
