### ISSUE TITLE
[Bug] Windows: fullscreen doesn't always pick the correct display

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1097]
**Describe the bug**

`Fl_Window::fullscreen()` sometimes full-screens the window on the wrong display on Windows.

**To Reproduce**

1. Run test/fullscreen.exe
2. Move the window "at least past the halfway point" towards a second display (To be clear, I mean past the midway point of a single display, on the side facing towards another display. I do NOT mean placing the window halfway between two displays. The window remains completely on one display at all times.)
3. Click the FullScreen button (the window should fullscreen on the correct display at first)
4. Click the FullScreen button again to exit fullscreen
5. Click the FullScreen button again to enter fullscreen a second time
6. See that the window is suddenly fullscreen on the wrong display

Note: Every time the window is manually repositioned even a little bit, the next FullScreen press will use the correct display again exactly once (like Step 3 above).

Note: If the window is NOT past the halfway mark on its display, then repeatedly entering fullscreen will continue to use the correct display (this is shown at the end of the video).

**Expected behavior**

The display used for fullscreen should always correspond to the display that the window is clearly on.

**Video**

https://github.com/user-attachments/assets/6fa94ce4-93d0-4f90-afa0-ffb227276b1b

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: release-1.4.0rc2

**FLTK Configure / Build Options**
 - Default CMake build in VS 2022

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Additional context**

I haven't yet tested this exact bug on Linux or Mac, but will test soon and report back.

Update: The bug does not happen on Linux/X11.
Update 2: No issues found on Mac either.

**Comment by Albrecht-S** [comment]
@dannye Thanks for testing 1.4.0rc2 and for the report.

Assigning this to @ManoloFLTK ...

**Comment by ManoloFLTK** [comment]
@Albrecht-S  I deassign this from myself because I don't have easily access to a Windows system with multiple displays.

**Comment by MatthiasWM** [comment]
I may have a chance to look at his on the weekend. Not sure if my VM supports multiple monitor though.

**Comment by ManoloFLTK** [comment]
@dannye This should be fixed with the commit mentioned above. Please, close issue if you confirm.

**Comment by dannye** [comment]
Yes, works great now. Thank you very much.

I just found another kind of fullscreen bug on Mac, which I will write up shortly. (But the tl;dr of it is: Use the green fullscreen button to go fullscreen, then use the "FullScreen" button to un-fullscreen. The window is not always returned to the expected size or position, ie the size/position that it would be returned to if you had used the green button for both fullscreen and un-fullscreen.)

**Comment by MatthiasWM** [comment]
Thank you, @ManoloFLTK
