### ISSUE TITLE
[Bug] Mac: Mixing native fullscreen button with Fl_Window::fullscreen() has side effects

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1098]
**Describe the bug**

If a window is full-screened with the native fullscreen button in the window title bar (the green circle) and then un-fullscreened with `Fl_Window::fullscreen()`, it may be restored to the wrong position, or at the wrong size, or other side effects.

**To Reproduce**

1. Run test/fullscreen
2. Move and resize the window somewhere new
3. Click on the green fullscreen button to fullscreen
4. Click on the FullScreen button to un-fullscreen [1]
5. See the window begins the "un-fullscreen animation" as expected, but "snaps" to the wrong position and the wrong size right at the very end of the animation.

[1] I _felt_ like I was getting better "luck" at triggering the bug if I held the mouse button down on the FullScreen button for about a full second before letting go, but that was probably a placebo. I figured I'd mention it anyway.

**Expected behavior**

The effect of `Fl_Window::fullscreen()` should be the same as clicking the green circle in this case.

**Video**

https://github.com/user-attachments/assets/2de5ca40-2a9b-4870-b5b7-70f64bd153e5

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: release-1.4.0rc2

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Debug`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: macOS 14.6.1
 - Processor if relevant: M3

**Comment by dannye** [comment]
There are a few more scenarios that lead to bugs, but they are more debatably the result of invalid steps from a malformed test program rather than an FLTK bug (whereas I would say the OP above is definitely normal user behavior).

Extra Case 1:

 1. Run test/fullscreen
 2. Press the FullScreen button to fullscreen
 3. Press the Border button (this might be the "invalid" step; why would you try to remove a border from a fullscreened window?)
 4. See the program has crashed

Extra Case 2:

 1. Run test/fullscreen
 2. Press the Border button to remove the border
 3. Press the FullScreen button to fullscreen
 4. Press the Border button (this might be the "invalid" step; why would you try to add back a border to a fullscreened window?)
 5. Press the FullScreen button to exit fullscreen (notice the border is missing despite being enabled in the previous step)
 6. Press the Border button twice ("off" then "on") to re-enable the border
 7. Notice that the green button has suddenly become a "maximize" button and not a "fullscreen" button!

**Comment by ManoloFLTK** [comment]
@dannye The commit mentioned above should fix the issue. Problems when fiddling with the window border while the window is fullscreen persist. I believe this is less improtant because modifying the border of a (borderless) fullscreen window doesn't make much sense. I will look at these later. Please, close issue if you agree it's fixed.

**Comment by dannye** [comment]
Absolutely 👍 It's working great now. Thanks so much as always.

**Comment by dannye** [comment]
@ManoloFLTK Thanks, that looks like it works well to me.

There are a few even more minor bugs with regard to toggling the border while the window is maximized.

(If the border is OFF, then the window is maximized, then the border is toggled ON, then the main window area overlaps with the border.)

(And if the border is ON, then the window is maximized, then the border is toggled OFF, then the window is un-maximized, then the window is sent to a seemingly random X,Y position (sometimes totally vanished off the screen).)

**Comment by dannye** [comment]
Oh, just saw your update. That fix looks good too, thanks.

I found one more sequence of events that fails (sorry):

 1. Run test/fullscreen
 2. Click Border to turn the border off
 3. Click Maximize
 4. Click FullScreen
 5. Click Maximize
 6. Click FullScreen
 7. Window is vanished

**Comment by dannye** [comment]
Steps 3 through 6 can also be "inverted" (FullScreen, Maximize, FullScreen, Maximize) and the window still vanishes.
