### ISSUE TITLE
[Bug] Mac: Fl_Window::fullscreen() doesn't work for unfocused tabbed window

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1101]
**Describe the bug**

If a window is part of a window tab group and that window is not the active tab, then `Fl_Window::fullscreen()` on that window doesn't work as expected (ie, doesn't do the same thing as pressing the green circle button on that window group).

This invocation of `Fl_Window::fullscreen()` could come from the sys menubar, a global keyboard shortcut, or some other source. But regardless of the source, it is still a sensible action even if the window tab is not the _active_ tab, since the window still has the green fullscreen button which is fully functional.

**To Reproduce**

```diff
diff --git a/test/fullscreen.cxx b/test/fullscreen.cxx
index 65c25036a..1e838506e 100644
--- a/test/fullscreen.cxx
+++ b/test/fullscreen.cxx
@@ -57,6 +57,7 @@
 #include <FL/math.h>
 #include <FL/fl_ask.H>
 #include <FL/Fl_Browser.H>
+#include <FL/Fl_Sys_Menu_Bar.H>
 #include <stdio.h>
 
 #if HAVE_GL
@@ -133,6 +134,19 @@ fullscreen_window::fullscreen_window(int W, int H, const char *t) : Fl_Single_Wi
 
 }
 
+void fullscreen_menu_cb(Fl_Widget *w, void *p) {
+  Fl_Menu_ *menu = (Fl_Menu_ *)w;
+  Fl_Window *win = (Fl_Window *)p;
+  const Fl_Menu_Item *mi = menu->mvalue();
+  if (mi->value()) {
+    win->fullscreen();
+  } else {
+    win->fullscreen_off();
+  }
+}
+
+Fl_Sys_Menu_Bar *pMenubar = nullptr;
+
 void after_resize(void *data) {
   Fl::remove_check(after_resize, data);
   fullscreen_window *win = (fullscreen_window*)data;
@@ -142,6 +156,11 @@ void after_resize(void *data) {
   if (win->fullscreen_active()) win->b3->set();
   else win->b3->clear();
   win->b3->redraw();
+  Fl_Menu_Item *mi = (Fl_Menu_Item *)pMenubar->find_item(fullscreen_menu_cb);
+  if (!!mi->value() != !!win->fullscreen_active()) {
+    mi->value(win->fullscreen_active());
+    pMenubar->update();
+  }
 }
 
 void fullscreen_window::resize(int x, int y, int w, int h) {
@@ -321,6 +340,17 @@ int main(int argc, char **argv) {
 
   window.begin();
 
+  Fl_Menu_Item menutable[] = {
+    {"View", 0, 0, 0, FL_SUBMENU},
+    {"Fullscreen", FL_COMMAND+FL_SHIFT+'f', fullscreen_menu_cb, &window, FL_MENU_TOGGLE},
+    {},
+    {}
+  };
+
+  Fl_Sys_Menu_Bar menubar(0, 0, 0, 0);
+  menubar.copy(menutable);
+  pMenubar = &menubar;
+
   int y = window.h()-30*NUMB-105;
   Fl_Hor_Slider slider(50,y,window.w()-60,30,"Sides:");
   slider.align(FL_ALIGN_LEFT);
@@ -372,5 +402,10 @@ int main(int argc, char **argv) {
   window.end();
   window.show(argc,argv);
 
+  Fl_Single_Window second_window(100, 100, 200, 200, "Second Window");
+  second_window.size_range(200, 200);
+  second_window.end();
+  second_window.show();
+
   return Fl::run();
 }
```

Scenario 1: (window is NOT fullscreen to begin with)
1. Apply the above patch to test/fullscreen.cxx
2. Build like normal and run test/fullscreen
3. Select "Window -> Merge All Windows" to create a window tab group
4. Switch to the "Second Window" tab
5. Select "View -> Fullscreen" (notice that the window does not become fullscreen)
6. Switch back to the first window tab (the "main" window)
7. See that the FullScreen light button is lit, indicating that the `FULLSCREEN` flag of the window's `flags_` is set, despite the window not being fullscreen

Scenario 2: (window is fullscreen to begin with)
1. Apply the above patch to test/fullscreen.cxx
2. Build like normal and run test/fullscreen
3. Select "Window -> Merge All Windows" to create a window tab group
4. Select "View -> Fullscreen" to make the window group fullscreen
5. Switch to the "Second Window" tab
6. Select "View -> Fullscreen" to un-fullscreen
7. Notice that the window has un-fullscreened, but has not returned to the main desktop (the window is floating in the "void" (not sure what to call it) and the user must use the 4-finger gesture to return to their desktop)

**Expected behavior**

Even if a tabbed window is not the active tab, `Fl_Window::fullscreen()` should still have the same effect as clicking the green fullscreen circle button for that window.

**Videos**

Scenario 1: (window is NOT fullscreen to begin with)

https://github.com/user-attachments/assets/679d4989-1d0b-472c-bb2b-4a9f80751698

Scenario 2: (window is fullscreen to begin with)

https://github.com/user-attachments/assets/ce72a11f-414b-4b36-bfe8-953c2c8bdb60

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 7ce5b74

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Debug`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: macOS 14.6.1
 - Processor if relevant: M3

**Additional context**

I've known about this bug for a long time from my own program, but it's really a pretty minor bug and required more effort to reproduce in a test program than most other bugs so I procrastinated on it until now. And now that most other fullscreen-related bugs are fixed, this might be one of the only ones left.

**Comment by ManoloFLTK** [comment]
@dannye At this point in time, I can propose you to slightly change the way your "Fullscreen" menu item is programmed. Don't have it apply to always the same window independently of whether it's focussed or not focussed; make it instead apply to the currently focussed window.
That would mean changing your `fullscreen_menu_cb` function as follows:
```
void fullscreen_menu_cb(Fl_Widget *w, void *p) {
  Fl_Menu_ *menu = (Fl_Menu_ *)w;
  //Fl_Window *win = (Fl_Window *)p;  // <-- old version
  Fl_Window *win = Fl::first_window(); // <-- new version
 …
```
With this, the programmed fullscreen/un-fullscreen command does the same as clicking the green button.

I'm not sure it's possible to do with the public API of macOS exactly what you ask for.

**Comment by dannye** [comment]
Hm, the problem with that solution is that the "Fullscreen" menubar option will start toggling the wrong window (the "Second Window") if the "Move Tab To New Window" option is used on the "main" window.

The intention of the fullscreen menubar checkmark is to strictly track the state of the main window.

**Comment by dannye** [comment]
I could at least ignore the fullscreen request if the first_window() is not the expected window. That would be an OK compromise I think.

**Comment by ManoloFLTK** [comment]
> I could at least ignore the fullscreen request if the first_window() is not the expected window. 

Sorry, I don't understand what you mean with that sentence. What is "the expected window"?

My main point is that if function `fullscreen_menu_cb()` targets the active tab's window rather than a fixed window, the net result is that everything occurs as if clicking the green button, and everything is correct as you pointed out. Noticeably, the fullscreen menubar checkmark does strictly track the state of the main window.

**Comment by dannye** [comment]
> > I could at least ignore the fullscreen request if the first_window() is not the expected window.
> 
> Sorry, I don't understand what you mean with that sentence. What is "the expected window"?

The main window. (The only one expected to be controlled by the fullscreen shortcut.)

> My main point is that if function `fullscreen_menu_cb()` targets the active tab's window rather than a fixed window, the net result is that everything occurs as if clicking the green button, and everything is correct as you pointed out.

That is only true while the windows are merged into a single window group.

When the windows are separated, then targeting the "active" window is not the desired behavior. (This would require that I update the checkmark status in the menubar every time the window focus changes, which is of course possible, but a big deviation from how this works on all other platforms, where the menubar is _inside_ the main window and only controls the main window.)

> Noticeably, the fullscreen menubar checkmark does strictly track the state of the main window.

Now I'm confused. What do you mean by this? This is not true under the plan to always use the first_window().

e.g. If neither the main window nor the secondary window are fullscreen (and the menubar checkmark is unchecked) and the secondary window has focus (and they're not grouped), then triggering the fullscreen shortcut will cause the secondary window to be fullscreen and it will check the checkmark in the menu; making the checkmark desynced from the state of the main window (ie, fail to strictly track the main window).

**Comment by ManoloFLTK** [comment]
@dannye The commit mentioned above should fix this issue.

**Comment by dannye** [comment]
Thank you, issue is totally fixed for me.
