### ISSUE TITLE
 Fl_Tile Resizes Incorrect Child (not the resizable one) When Fl_Window is Maximized

### ISSUE THREAD

**Issue by erinacio** [fltk/fltk#1102]
**Describe the bug**

When a `Fl_Tile` is marked as the resizable child of a `Fl_Window` and the window is maximized, the right-most child of the `Fl_Tile` is resized instead of the resizable child.

**To Reproduce**

Use example code in `Fl_Tile` documentation.

```cpp
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Window.H>

int main(int argc, char *argv[]) {
    Fl_Window win(400, 300, "My App");

    Fl_Tile tile(0, 0, 400, 300);

    Fl_Box left_tool_box(0, 0, 100, 300, "Tools");
    left_tool_box.box(FL_DOWN_BOX);
    tile.size_range(&left_tool_box, 50, 50);

    Fl_Box document(100, 0, 200, 300, "Document");
    document.box(FL_DOWN_BOX);
    tile.size_range(&document, 100, 50);

    Fl_Box right_tool_box(300, 0, 100, 300, "More\nTools");
    right_tool_box.box(FL_DOWN_BOX);
    tile.size_range(&right_tool_box, 50, 50);

    tile.end();
    tile.resizable(document);

    win.end();
    win.resizable(tile);
    win.show(argc, argv);
    win.size_range(200, 50);
    return Fl::run();
}
```

1. Compile and run the above code.
2. Maximize the window.
3. `right_tool_box` is resized instead of `document`.

**Expected behavior**

Should always resize the resizable child.

**Screenshots**

https://github.com/user-attachments/assets/315bf22e-05c7-484b-b5ad-6f7ee0aa65c8

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from: Git (CMake FetchContent)
 - If from Git, branch: release-1.4.0rc2 (307148222) and master (3c03aecc3)

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed
by using CMake GUI tools (if any).

```cmake
include(FetchContent)

set(FLTK_BUILD_FLTK_OPTIONS OFF)
set(FLTK_BUILD_FLUID OFF)
set(FLTK_BUILD_FORMS OFF)
set(FLTK_BUILD_GL OFF)
set(FLTK_OPTION_STD ON)

FetchContent_Declare(fltk
        GIT_REPOSITORY https://github.com/fltk/fltk.git
        GIT_TAG release-1.4.0rc2)
FetchContent_MakeAvailable(fltk)
```

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: Linux
 - OS Version: Arch Linux rolling
 - DE: KDE Plasma 6.2.2, KDE Frameworks 6.7.0, Wayland session

**Linux/Unix Runtime, if applicable:**
 - Wayland
 - X11 (through XWayland)

**Comment by Albrecht-S** [comment]
@erinacio Thanks for the report, bug confirmed.

@MatthiasWM Do you have an idea how to fix this?

PS: I set low priority because this is a border case that should not delay release FLTK 1.4.0 - although it would be "nice to have" a solution...

**Comment by ManoloFLTK** [comment]
@MatthiasWM I've looked a little into this issue and found that this change to function `Fl_Tile::request_shrink_l()` at line 191 of file `src/Fl_Tile.cxx` fixes the problem. 

Replace
`         if (may_l < new_l) {`
by
`         if (new_l < ri->r()-min_w) {`

I'm not sure though this is the correct fix for lack of complete understanding of the complex tile resizing algorithm.

**Comment by MatthiasWM** [comment]
Thanks for looking at this. The bug seems to be around Fl_Tile.cxx:611 where it resizes the "resizable" before it resizes the entire tile. I will try to fix it ASAP. Simply changing the lines is not enough.

**Comment by MatthiasWM** [comment]
This should fixed in the last Commit. The problem was, that the original code was tested for smaller changes in size only, and the bug would appear if the bottom right corner of the resizable widget would be positioned outside of the current Fl_Tile. This is now fixed by first enlarging the width and/or height as needed, the adjusting the resizable, and the reducing width and/or height as need. 

@erinacio Please let me know if this fixes the bug, and if so, Close the Issue. Thanks!

**Comment by erinacio** [comment]
> This should fixed in the last Commit. The problem was, that the original code was tested for smaller changes in size only, and the bug would appear if the bottom right corner of the resizable widget would be positioned outside of the current Fl_Tile. This is now fixed by first enlarging the width and/or height as needed, the adjusting the resizable, and the reducing width and/or height as need.
> 
> @erinacio Please let me know if this fixes the bug, and if so, Close the Issue. Thanks!

I tried the latest master commit and cannot reproduce this issue any more. Should be fixed so close it. Many thanks to the rapid fix.
