### ISSUE TITLE
[Bug] X11: Window border cannot be re-enabled

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1107]
**Describe the bug**

After a window border has been turned off, it cannot be turned back on. This happens on X11 only.

**To Reproduce**

1. Run test/fullscreen
2. Click the Border button to turn the border off
3. Click the Border button again
4. See that the border has not been restored

**Expected behavior**

Toggling the window border should work as expected.

**Video**

https://github.com/user-attachments/assets/14430c1c-5ffc-47b4-b129-940a1ab94381

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8752701

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Release -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0 -D FLTK_OPTION_CAIRO_WINDOW=1`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

I see the same bug on the latest branch-1.3, so this is not a new regression.

I did a quick pass through all the test+example programs on Linux/Mac/Windows and will make a quick report for the few minor bugs I found.
All the bugs are on X11. I didn't spot any new issues on Mac or Windows. This bug is 1 of 5.

**Comment by ManoloFLTK** [comment]
No such bug here with Ubuntu 24.04 in X11 mode corresponding to gnome-shell version 46.0

**Comment by ManoloFLTK** [comment]
No such bug here with Ubuntu 22.04 in X11 mode corresponding to gnome-shell version 42.9

What is "Peppermint OS 10" ?

**Comment by ManoloFLTK** [comment]
No such bug here with Debian 11 "Bull's eye" in X11 mode corresponding to gnome-shell version 3.38.6

**Comment by ManoloFLTK** [comment]
OK. I can reproduce the issue with an xfce session under Ubuntu.

This is a known issue documented in member function `Fl_Window::border(int)`which reads
> With some X window managers, this does not work after show() has been called.

xfce is one of these window managers that require to hide, then turn border on, and then show the window for the operation to be successful.

I don't think FLTK can do anything about that.

**Comment by dannye** [comment]
Okay, not a problem. Thanks for checking!

> What is "Peppermint OS 10" ?

Peppermint is a derivative of Ubuntu.
(The latest version of Peppermint is now based on Debian, but I'm still using the final release of Peppermint that was based on Ubuntu.)

> This is a known issue documented in member function `Fl_Window::border(int)`which reads
> 
> > With some X window managers, this does not work after show() has been called.

My apologies for not noticing this.
