### ISSUE TITLE
[Bug] X11: test/windowfocus doesn't work as described

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1108]
**Describe the bug**

test/windowfocus says "Type something to pop the subwindow up. The focus should stay on the input, and you should be able to continue typing." but this doesn't seem to work on X11. It works for the first keystroke (the one that initially creates the second window) but every subsequent keystroke gives focus to the second window and prevents typing into the input.

**To Reproduce**

1. Run test/windowfocus
2. Type 2 or more characters into the input box
4. See that full focus is given to the second window and you cannot type into the input.

**Expected behavior**

As the program claims, you should be able to continue typing. This works correctly on Windows and Mac.

**Video**

https://github.com/user-attachments/assets/cdf14ed7-d125-4970-a72b-1585a9f7056f

You can't clearly tell that I'm typing on my keyboard, but I am, and the characters are not being received by the input.

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8752701

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Release -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0 -D FLTK_OPTION_CAIRO_WINDOW=1`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

I see the same bug on the latest branch-1.3, so this is not a new regression.

I did a quick pass through all the test+example programs on Linux/Mac/Windows and will make a quick report for the few minor bugs I found.
All the bugs are on X11. I didn't spot any new issues on Mac or Windows. This bug is 2 of 5.

**Comment by ManoloFLTK** [comment]
No such bug here under Debian 11 in X11 mode, the oldest Linux config I have at hand.

**Comment by Albrecht-S** [comment]
Neither here on Debian 12, Wayland/XWayland mode.

@dannye Is it possible that you set `point-to-focus` [1] (rather than `click-to-focus`) on your system? If yes, please check that the mouse (pointer) doesn't hover over the second window.

[1] or a similar name, I don't know exactly how to call it.

**Comment by ManoloFLTK** [comment]
I have also checked that there's no bug with windowfocus under Ubuntu 24.04 and an xfce session. It might be an issue of Pepermint 10 repaired in more recent versions.

**Comment by dannye** [comment]
> @dannye Is it possible that you set `point-to-focus` [1] (rather than `click-to-focus`) on your system? If yes, please check that the mouse (pointer) doesn't hover over the second window.

No, nothing like that enabled on my system.

> I have also checked that there's no bug with windowfocus under Ubuntu 24.04 and an xfce session. It might be an issue of Pepermint 10 repaired in more recent versions.

Okay, I don't mind this being closed at all. This issue is not personally important to me, I just wanted to report what I found during testing. Thanks again for taking a look. Feel free to close.
