### ISSUE TITLE
[Bug] X11: test/checkers drawing artifacts when window is scaled

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1109]
**Describe the bug**

test/checkers has strange drawing artifacts when clicking and dragging the mouse around the window while the window is scaled up or down.

**To Reproduce**

1. Run test/checkers
2. Scale the window up or down
3. Click and hold the mouse button and drag around the window
5. See the artifacts that scribble around the window

**Expected behavior**

The window should continue to be drawn correctly even while the window is scaled up or down.

**Video**

https://github.com/user-attachments/assets/5e42acf0-c9ac-46e7-af2c-714794b3bb28

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8752701

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Release -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0 -D FLTK_OPTION_CAIRO_WINDOW=1`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

I did a quick pass through all the test+example programs on Linux/Mac/Windows and will make a quick report for the few minor bugs I found.
All the bugs are on X11. I didn't spot any new issues on Mac or Windows. This bug is 3 of 5.

**Comment by ManoloFLTK** [comment]
@dannye Please, close issue if you confirm the commit mentioned above does fix it.

**Comment by dannye** [comment]
Yes, fixed!
