### ISSUE TITLE
[Bug] X11: test/gl_overlay stale overlay rendering

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1111]
**Describe the bug**

test/gl_overlay doesn't correctly redraw when using the "Overlay" slider. Using the "Sides" slider always fixes the issues by doing a full redraw. This only happens on X11.

**To Reproduce**

1. Run test/gl_overlay
2. Use the "Overlay" slider to change/redraw the overlay
4. See that the different overlays "stack" and draw on top of each other

**Expected behavior**

Redrawing the overlay should replace the old overlay, not draw on top of it.

**Video**

https://github.com/user-attachments/assets/a05e7797-cec3-4390-97cb-c0f31d670372

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8752701

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Release -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0 -D FLTK_OPTION_CAIRO_WINDOW=1`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

I see the same bug on the latest branch-1.3, so this is not a new regression.

I did a quick pass through all the test+example programs on Linux/Mac/Windows and will make a quick report for the few minor bugs I found.
All the bugs are on X11. I didn't spot any new issues on Mac or Windows. This bug is 5 of 5.

**Comment by ManoloFLTK** [comment]
@dannye Please, close issue if you see it fixed with commit above.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Fixed for me, thanks very much.

**Comment by dannye** [comment]
Yes, same here, looks good!
