### ISSUE TITLE
[Bug] X11: fl_draw_image() with horizontal flip reads out of bounds

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1112]
**Describe the bug**

If the `D` parameter to `fl_draw_image()` is negative (to indicate a horizontal flip), ALL the pixels sampled from the image are off by 1 row, and the bottom row of pixels are sampled "out of bounds".

(This might mean out of bounds of the whole buffer, therefore reading garbage data, or it might mean reading the row of the image that is below the intended "X/Y/W/H", which is how I originally observed the bug.)

As far as I can tell, vertical flipping does not suffer from the same issue.
(If the image is vertically flipped, it looks correct. If it is both horizontally and vertically flipped, the row of garbage pixels is moved from the bottom to the top.)

This is a new bug in 1.4.0 and definitely was NOT an issue in 1.3. This bug does not happen on Windows or Mac.

**To Reproduce**

1. Run test/unittests
2. Go to "Drawing Images"
3. Uncheck the "IMG" checkbox
4. Check the "FLIPH" checkbox
5. See the row of garbage pixels at the bottom of each image

**Expected behavior**

When the image is flipped horizontally, the "Y offset" of the drawn image should not be changed (compared to when not flipped).

**Screenshots**

![image](https://github.com/user-attachments/assets/1b35c122-df17-49c6-874d-9a14a97c94fb)

![image](https://github.com/user-attachments/assets/31563772-f6d3-488f-86f6-4322bedd3ad3)

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8752701

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Release -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0 -D FLTK_OPTION_CAIRO_WINDOW=1`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

This is THE bug I was hunting that lead me to test all the sample programs on Linux.

I discovered this bug while porting a few FLTK 1.3.7 apps (that use a lot of image drawing/flipping) to 1.4.0 for a friend and only saw this issue on Linux. I went through all the test programs in the hopes of finding a demo of the bug to avoid needing to write my own repro. I almost gave up!

https://github.com/Rangi42/tilemap-studio/pull/87
https://github.com/Rangi42/polished-map/pull/87

**Comment by dannye** [comment]
I think there are more related-but-different bugs in fl_draw_image regarding off-by-one sample coordinates, which don't require flipping.

Taking a small region of the image buffer (say, 8x8 pixels) and stretching it over a large area of the screen often results in "strips" of pixels from _outside_ the 8x8 region of the image being drawn to the screen:

![image](https://github.com/user-attachments/assets/bc6db2c7-f240-4558-b56b-b3d2a1fdb94a)

This also only happens on X11 and also is new to 1.4.0.

(As far as I can tell, the image is always drawn to the exactly correct X/Y/W/H region of the screen. It's just the sampling coordinates of the image buffer that's the problem.)

**Comment by dannye** [comment]
And to be totally clear, the exact same scenario in FLTK 1.3.7 looks like this:

![image](https://github.com/user-attachments/assets/03f8d811-6e17-424b-bd04-0a93a3092f44)

**Comment by dannye** [comment]
Yes, thank you, the first issue is fixed.

For the second issue, I'll come back and open a separate issue if I can create a minimal repro.

**Comment by MatthiasWM** [comment]
@ManoloFLTK Thanks for all the fixes. What a run ;-) . @dannye Thanks for checking and reporting.
