### ISSUE TITLE
Very minor high DPI rounding issue with fl_rect

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1113]
**Describe the bug**

This is based on part of the discussion in #1089.

When `fl_rect()` is used to draw a rectangle with a thickness of 2 on macOS, the top-left X/Y of the rectangle are 1 greater than expected. This puts the rectangle 1 pixel down and 1 pixel to the right from where it is expected, in terms of screen pixels, not application coordinates. (Meaning that the rectangle is only a small fraction of a pixel off in terms of application coordinates.)

This creates issues with boxes "poking out from behind" of other boxes when many partially overlapping boxes/lines are drawn at once in a UI that really relies heavily on pixel-perfect placement.

There's no issue with the W/H of the rectangle.

**To Reproduce**

demo.cxx:

```cpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Box.H>
#include <FL/fl_draw.H>

class CanvasA : public Fl_Widget {
public:
	CanvasA(int x, int y, int w, int h, char *l=nullptr) : Fl_Widget(x, y, w, h, l) {}

	void draw() {
		int cx = x() + w()/2, cy = y() + h()/2;
		Fl_Rect rect(cx - w()/8, cy - h()/8, w()/8 * 2, h()/8 * 2);

		fl_rectf(x(), y(), w(), h(), fl_lighter(FL_GRAY));

		fl_color(fl_darker(FL_GRAY));
		fl_xyline(x(), rect.y()          + 0, x()+w());
		fl_xyline(x(), rect.y()          + 1, x()+w());
		fl_xyline(x(), rect.y()+rect.h() - 2, x()+w());
		fl_xyline(x(), rect.y()+rect.h() - 1, x()+w());

		fl_yxline(rect.x()          + 0, y(), y()+h());
		fl_yxline(rect.x()          + 1, y(), y()+h());
		fl_yxline(rect.x()+rect.w() - 2, y(), y()+h());
		fl_yxline(rect.x()+rect.w() - 1, y(), y()+h());

		// Draw two nested rectangles.
		fl_rect(rect.x(),     rect.y(),     rect.w(),     rect.h(),     FL_RED);
		fl_rect(rect.x() + 1, rect.y() + 1, rect.w() - 2, rect.h() - 2, FL_RED);
	}
};

class CanvasB : public Fl_Widget {
public:
	CanvasB(int x, int y, int w, int h, char *l=nullptr) : Fl_Widget(x, y, w, h, l) {}

	void draw() {
		int cx = x() + w()/2, cy = y() + h()/2;
		Fl_Rect rect(cx - w()/8, cy - h()/8, w()/8 * 2, h()/8 * 2);

		fl_rectf(x(), y(), w(), h(), fl_lighter(FL_GRAY));

		fl_color(fl_darker(FL_GRAY));
		fl_xyline(x(), rect.y()          + 0, x()+w());
		fl_xyline(x(), rect.y()          + 1, x()+w());
		fl_xyline(x(), rect.y()+rect.h() - 2, x()+w());
		fl_xyline(x(), rect.y()+rect.h() - 1, x()+w());

		fl_yxline(rect.x()          + 0, y(), y()+h());
		fl_yxline(rect.x()          + 1, y(), y()+h());
		fl_yxline(rect.x()+rect.w() - 2, y(), y()+h());
		fl_yxline(rect.x()+rect.w() - 1, y(), y()+h());

		// Draw a rectangle with a thickness of 2.
		fl_line_style(FL_SOLID, 2);
		fl_rect(rect.x() + 1, rect.y() + 1, rect.w() - 1, rect.h() - 1, FL_RED);
		fl_line_style(FL_SOLID);
	}
};

int main(int argc, char **argv) {
	Fl_Window *window  = new Fl_Window(200, 200, 600, 400);
	Fl_Tabs   *tabs    = new Fl_Tabs  ( 20,  20, 560, 360);
	Fl_Group  *tab1    = new Fl_Group ( 20,  50, 560, 330, "Nested Rect");
	CanvasA   *canvasA = new CanvasA  ( 30,  60, 540, 290);
	Fl_Box    *box1    = new Fl_Box   ( 30, 350, 540,  30, "The red rectangle should perfectly overlap with the gray lines on all platforms.");
	tab1->end();
	Fl_Group  *tab2    = new Fl_Group ( 20,  50, 560, 330, "Thick Rect");
	CanvasB   *canvasB = new CanvasB  ( 30,  60, 540, 290);
	Fl_Box    *box2    = new Fl_Box   ( 30, 350, 540,  30, "The red rectangle should perfectly overlap with the gray lines, but does not on Mac.");
	tab2->end();
	window->end();
	window->resizable(tabs);
	window->show(argc, argv);
	return Fl::run();
}
```

1. Build the above demo.cxx with: `fltk-config --compile demo.cxx` and run.
2. Observe that the first tab shows 2 nested 1-pixel-thick rectangles which overlap perfectly with the background lines drawn behind them.
3. Observe that the rectangle always remains perfectly overlapped even when resizing and/or rescaling the window.
4. Observe that the second tab shows a 2-pixel-thick rectangle which does not quite perfectly overlap with the background lines.
5. Observe that the amount of rounding error remains exactly the same when resizing and/or rescaling the window.

**Expected behavior**

If possible, it would be ideal if the 2-pixel-thick rectangle was drawn at the exact same X/Y coordinates as the 1-pixel-thick rectangle (as is the case on Windows and Linux).

**Screenshots**

<img width="712" alt="Screenshot 2024-11-07 at 9 52 47 PM" src="https://github.com/user-attachments/assets/ac4213c7-72a4-487f-9877-e597e28c66df">

<img width="712" alt="Screenshot 2024-11-07 at 9 53 40 PM" src="https://github.com/user-attachments/assets/24cb993e-0b0c-41b3-968c-8594a22db2ea">

![image](https://github.com/user-attachments/assets/d9f783b2-fc2a-4d0e-b655-44e5a6d563c4)

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8f987ce

**FLTK Configure / Build Options**
 - `cmake -D CMAKE_BUILD_TYPE=Release`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: macOS 14.6.1
 - Processor if relevant: M3

**Additional context**

I am fairly confident this will be my last report for 1.4.0. Sorry for all the pestering and thank you sincerely for everything.

**Comment by dannye** [comment]
The more I think about it, maybe this isn't really describing a bug at all and I should instead look at this as a request for a new kind of draw function, one which draws a band between:
```
fl_rect(rect.x(), rect.y(), rect.w(), rect.h(), FL_RED);
```

and:
```
fl_rect(rect.x() + 1, rect.y() + 1, rect.w() - 2, rect.h() - 2, FL_RED);
```

I totally get how minor this is, please ignore for as long as you like.

**Comment by ManoloFLTK** [comment]
@dannye This should be fixed with commit above. Please, close issue if you agree.

**Comment by dannye** [comment]
Thank you!

> Regarding the question of drawing a band between 2 rectangles: I would believe this can be achieved with 4 fl_rectf() calls.

A filled rect is not viable for all my use-cases. But it's a non-issue since you've fixed it. Thank again.

**Comment by dannye** [comment]
> Regarding the question of drawing a band between 2 rectangles: I would believe this can be achieved with 4 fl_rectf() calls.

Wow, I completely misinterpreted this originally. My mind was stuck on "nested rectangles" still. Oops.

You're absolutely right that 4 fl_rectf() calls for drawing each edge of the rect band is massively better than what I was doing previously.

This approach is extremely (totally) robust to the rounding errors that `fl_line_style(FL_SOLID, 2);` suffers from on Windows at scales >100%.

This is what I settled on (where `t` is thickness):

```cpp
void rect_band(int x, int y, int w, int h, int t, Fl_Color c) {
	fl_color(c);
	fl_push_clip(x, y, w, h);
	fl_rectf(x, y, w, t);
	fl_rectf(x, y+h-t, w, t);
	fl_rectf(x, y, t, h);
	fl_rectf(x+w-t, y, t, h);
	fl_pop_clip();
}
```

Thanks.
