### ISSUE TITLE
Fl_Help_View::find() looks inside tags

### ISSUE THREAD

**Issue by jafcobend** [fltk/fltk#1119]
I have found that in my scenarios Fl_Help_View fails to to indicate its found text and in many cases seems to do nothing. I'm not at the bottom of this yet. But I found a mishandling of `bp` and `bs` in the search routine. The short of it is that it is searching the content inside of tags. I propose this patch

```
--- a/src/Fl_Help_View.cxx
+++ b/src/Fl_Help_View.cxx
@@ -1235,12 +1235,12 @@ Fl_Help_View::find(const char *s,               // I - String to find
       // multi byte string in (*sp)...
       // For instance: "&euro;" == 0x20ac -> 0xe2 0x82 0xac (UTF-8: 3 bytes).
       // Hint: use fl_utf8encode() [see below]
-
-      if (tolower(*sp) == tolower(c)) sp ++;
-      else {
+      if (tolower(*sp) == tolower(c)) {
+        if(sp==s) bs = bp;
+        sp ++;
+      } else if(sp!=s) {
         // No match, so reset to start of search...
        sp = s;
-       bs ++;
        bp = bs;
       }
     }
```

If nothing else the original code wastes a lot of time rechecking the same things and will skip characters. I'm using the relationship of `sp` to `s` to determine when a possible match starts and when it fails to be a match.

M$ is getting heavy handed like g00g and like g00g will likely lock me out of my account. I'm not sure how much longer I'll be able to use this last avenue of communication with your project. So hopefully this patch helps. I'm committed to using FLTK for the foreseeable future and will continue to fix things in my copy, even if I can't share those fixes directly.

**Comment by ManoloFLTK** [comment]
@jafcobend Could you, please, post here a short example of HTML content that triggers the problem in Fl_Help_View ? TIA.

**Comment by jafcobend** [comment]
Not particularly. My HTML content is of a good size. But its easy enough to watch what's happening. Assuming ASCII test HTML inject a `putchar(c);` at line 1127 (current master). Load the ASCII test HTML into an Fl_Help_Dialog from a test applet. Run the code from an X terminal and use the find. You'll see quite clearly that the search back-tracks into the tags **and** the entities. The only reason this does not lead to a frequently noticed failure is because tag & entity text seldom mimic the content text. Unless... of course, the content text is of a programming nature. ;-) And the whole block fixation frequently hides the failure. I'm still working on making "find" work as expected.

Hmm... that back-tracking might be an issue with UTF-8 as well, backing up into the middle of a multi-byte character... If I used something other than ASCII I might be concerned.

**Comment by Albrecht-S** [comment]
@jafcobend Thank you for this report. This is something we should check but I assume that this can't be fixed easily, i.e. not in 1.4.0 - and maybe not in the 1.4.x series at all (note that 1.5.0 development will be started shortly after the release of 1.4.0 or 1.4.1).

`Fl_Help_View` is really old and has not been updated for a long time except for some bug fixes and IIRC one small extension. As you can see in the comment above [line 1127](https://github.com/fltk/fltk/blob/53bedf1d34f7f3c56aaa2edadc92f74b73fe6982/src/Fl_Help_View.cxx#L1127) which you mentioned in your comment, it is known that this widget is not UTF-8 aware in many parts because it was written before FLTK used UTF-8 at all.

It is also noteworthy that this widget supports only a very old HTML standard, and this will very likely not be changed.

Not respecting HTML tags in the `find()` method seems to be a new (yet unknown) issue. This should be investigated.

**Comment by jafcobend** [comment]
It looks like M$ ate my last post. In brief: I gave you the fix for the search inside tags. Put the "putchar()" and my patch in and you'll see it stops all the erroneous back and forth. As for UTF-8 I won't rewrite all the reasoning but in general find() will still work with UTF-8 since a byte-by-byte equality comparison still works on it.

Use the patch or not. Your choice.

**Comment by Albrecht-S** [comment]
@jafcobend wrote:
> Use the patch or not. Your choice.

Sure, thanks for the patch. We will evaluate it and apply if it fixes the issue and doesn't break anything else. The latter is probably more work to do, and I (personally) can't afford the time before the upcoming release.

What I wanted to say, in a nutshell: we'll certainly check your patch, but this will very likely not be done before the release of 1.4.0 (unless someone else finds the time to do it). Thanks for your contribution anyway, all bug fixes and patches are appreciated.

**Comment by MatthiasWM** [comment]
Thanks of the original patch. I had a hard time replicating the issue, but nevertheless found bugs in the code. I also implemented the test for Unicode HTML Entities.

**Comment by jafcobend** [comment]
Merry Christmas to me! I'll have to try out the patch. Thanks!
