### ISSUE TITLE
Fl_Output bad redraw on mouse selection

### ISSUE THREAD

**Issue by stgatilov** [fltk/fltk#112]
I have a weird problem with behavior of default Fl_Output widget in FLTK 1.3.5. Both on Windows 10 and on Ubuntu Linux.
It looks as if the text and selection rectangle is redrawn without clearing whatever was there first.
Here is short video: https://www.youtube.com/watch?v=PqCDV6QztOk

I have tried to find some simple workaround like calling redraw on "changed" callback or do FL_DAMAGE_ALL damage, but it has no effect. Since Fl_Input works properly (and very differently), I tried to see the difference in the source code, but could not understand how input and output widgets are distinguished there.

I would be happy if someone can suggest a workaround.

**P.S.** This FLTK-based app is a new installer for TheDarkMod game.
I can give full sources or Windows/Linux executable if it would help.

**Comment by erco77** [comment]
What's the box() type set to for the Fl_Output widget? If it's a FL_XXXX_FRAME, that's probably the problem, change it to FL_XXXX_BOX instead, as it likely needs a background to redraw correctly.

**Comment by stgatilov** [comment]
It is FL_THIN_DOWN_FRAME. Changing it to FL_THIN_UP_BOX fixes the problem.
So it is my fault: I selected wrong box type without understanding the difference.

Problem solved. Thank you!
