### ISSUE TITLE
Windows and X11: Rounding issues with Fl_RGB_Image::draw()

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1120]
**Describe the bug**

This is a follow-up to the second issue mentioned in #1112.

In FLTK 1.4 on X11 (both with and without Cairo), `Fl_RGB_Image::draw(int, int, int, int, int, int)` sometimes draws pixels from the source image that are outside the region specified by the arguments. This problem did not occur in 1.3.

**To Reproduce**

```cpp
#include <FL/Fl.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Button.H>

#include <cassert>
#include <random>

#define TILE_WIDTH 8
#define GRID_WIDTH 50
#define MIN_SCALE 1
#define MAX_SCALE 10

int png_num_columns = 1;
int png_num_rows = 1;
int png_num_tiles = 1;
int scale = 5;
int tiles[GRID_WIDTH * GRID_WIDTH] = { 0 };

Fl_RGB_Image *original = nullptr;
Fl_RGB_Image *zoomed = nullptr;

class Canvas : public Fl_Widget {
public:
    Canvas(int x, int y, int w, int h, char *l=nullptr) : Fl_Widget(x, y, w, h, l) {}

    void draw() {
        for (int i = 0; i < GRID_WIDTH * GRID_WIDTH; ++i) {
            zoomed->draw(
                x() + (i % GRID_WIDTH) * TILE_WIDTH * scale,
                y() + (i / GRID_WIDTH) * TILE_WIDTH * scale,
                TILE_WIDTH * scale, TILE_WIDTH * scale,
                (tiles[i] % png_num_columns) * TILE_WIDTH * scale,
                (tiles[i] / png_num_columns) * TILE_WIDTH * scale
            );
        }
    }
};

Fl_Window *window = nullptr;
Canvas *canvas = nullptr;

void slider_cb(Fl_Widget *w, void *d) {
    scale = (int)((Fl_Slider*)w)->value();
    if (zoomed) delete zoomed;
    zoomed = (Fl_RGB_Image *)original->copy(original->w() * scale, original->h() * scale);
    ((Fl_Box*)d)->image(zoomed);
    canvas->size(TILE_WIDTH * GRID_WIDTH * scale, TILE_WIDTH * GRID_WIDTH * scale);
    window->redraw();
}

void randomize_cb(Fl_Widget *w, void *d) {
    for (int i = 0; i < GRID_WIDTH * GRID_WIDTH; ++i) {
        tiles[i] = rand() % png_num_tiles;
    }
    window->redraw();
}

int main(int argc, char **argv) {
    original = new Fl_PNG_Image("tiles.png");
    assert(original->w() % TILE_WIDTH == 0);
    assert(original->h() % TILE_WIDTH == 0);
    png_num_columns = original->w() / TILE_WIDTH;
    png_num_rows    = original->h() / TILE_WIDTH;
    png_num_tiles = png_num_columns * png_num_rows;

    window             = new Fl_Window(200, 200, 800, 600);
    Fl_Group  *group   = new Fl_Group (  0,   0, 800, 280);
    Fl_Box    *box1    = new Fl_Box   ( 20,   0, 100,  40, "Original:");
    Fl_Scroll *scroll1 = new Fl_Scroll( 20,  40, 150, 150);
    Fl_Box    *box2    = new Fl_Box   ( 20,  40, original->w(), original->h());
    scroll1->end();
    Fl_Slider *slider  = new Fl_Slider( 20, 220, 100,  20, "Zoom:");
    Fl_Button *button  = new Fl_Button( 20, 260, 100,  20, "Randomize");
    Fl_Box    *box3    = new Fl_Box   (220,   0, 100,  40, "Zoomed:");
    Fl_Scroll *scroll2 = new Fl_Scroll(220,  40, 240, 240);
    Fl_Box    *box4    = new Fl_Box   (220,  40, original->w() * MAX_SCALE, original->h() * MAX_SCALE);
    group->end();
    Fl_Box    *box5    = new Fl_Box   ( 20, 280, 100,  40, "Random Tiles:");
    Fl_Scroll *scroll3 = new Fl_Scroll( 20, 320, 760, 260);
    canvas             = new Canvas   ( 20, 320,   0,   0);
    window->end();

    window->resizable(scroll3);
    group->resizable(nullptr);
    box1->align(FL_ALIGN_INSIDE | FL_ALIGN_BOTTOM_LEFT);
    box2->align(FL_ALIGN_INSIDE | FL_ALIGN_TOP_LEFT);
    box2->image(original);
    slider->type(FL_HORIZONTAL);
    slider->align(FL_ALIGN_TOP_LEFT);
    slider->range(MIN_SCALE, MAX_SCALE);
    slider->step(1);
    slider->value(scale);
    slider->callback(slider_cb, box4);
    button->callback(randomize_cb);
    box3->align(FL_ALIGN_INSIDE | FL_ALIGN_BOTTOM_LEFT);
    box4->align(FL_ALIGN_INSIDE | FL_ALIGN_TOP_LEFT);
    box5->align(FL_ALIGN_INSIDE | FL_ALIGN_BOTTOM_LEFT);

    slider_cb(slider, box4);
    randomize_cb(nullptr, nullptr);

    window->show(argc, argv);
    return Fl::run();
}
```

Compile with: `fltk-config --use-images --compile demo.cxx`

You can use any NxM png as long as its dimensions are a multiple of 8. Name the png "tiles.png" and place it in the same directory as demo.cxx.

This is the png that was used for the screenshots:

![tiles](https://github.com/user-attachments/assets/cb035014-bba6-4475-9c67-30b565fa0f9c)

1. Compile the above demo.cxx and run.
2. See that many of the individually-drawn tiles in the bottom region of the window sometimes have stray strips of pixels that come from the source image, but from outside the specified area.

**Expected behavior**

The exact specified region of the image is what should be drawn to the screen. Extra strips of pixels from immediately outside the region should not be drawn.

**Screenshots**

![image](https://github.com/user-attachments/assets/f7a4778d-3a61-4498-8f45-747844f746cf)

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: dc2c533

**FLTK Configure / Build Options**

Tested with both:
 - `cmake -D CMAKE_BUILD_TYPE=Release`
 - `cmake -D CMAKE_BUILD_TYPE=Release -D FLTK_GRAPHICS_CAIRO=1 -D FLTK_BACKEND_WAYLAND=0`

**Operating System / Platform:**
 - OS: Peppermint OS
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

The exact same demo.cxx compiled with FLTK 1.3 does not show the issue:

![image](https://github.com/user-attachments/assets/652633f3-cf53-47b9-8c35-71997cea2b4f)

The same demo.cxx also does not show the issue on Windows or Mac when compiled with FLTK 1.4.

**Comment by dannye** [comment]
Actually the issue does happen on Windows too, even though I didn't notice this issue originally when updating a 1.3.7 app to 1.4.0.

![image](https://github.com/user-attachments/assets/0b546e82-078f-47cb-b1fe-2aa69957ea94)

**Comment by dannye** [comment]
There are really faint lines between draws on macOS, but this behavior is identical between 1.3.9 and 1.4.0:

<img width="912" alt="image" src="https://github.com/user-attachments/assets/bf1a1c3e-1dcb-4221-a231-4ea3fb17c606">

Not a major problem.

**Comment by dannye** [comment]
This turned out to be caused by, for example, `this->floor(XP)` and `this->floor(YP)` in this line:

https://github.com/fltk/fltk/blob/dc2c53333cf598d3b7fd5d183da671671dff2896/src/drivers/GDI/Fl_GDI_Graphics_Driver_image.cxx#L626

`XP` and `YP` are sometimes negative because of `XP -= cx; YP -= cy;` and `Fl_Scalable_Graphics_Driver::floor` would round in the wrong direction for negative inputs.

**Comment by ManoloFLTK** [comment]
@dannye I came to the same conclusion and fixed it with the commit mentioned above.

**Comment by dannye** [comment]
Thanks. I think there is one more case of bad rounding somewhere. I am still debugging..
