### ISSUE TITLE
Make Fl_Browser_'s bbox and, more important, find_item public.

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1121]
**Is your feature request related to a problem? Please describe.**
Fl_Browser_'s bbox() and find_item() are protected member functions of Fl_Browser_.  While for C++ this presents no issue, it is a problem for pyFLTK, as swig will only expose public functions of a class.
The functions are needed to implement a draggable browser as seen in Greg Ercolano's cheat-page:
https://www.seriss.com/people/erco/fltk/#Fl_Browser_DND_Reorder

**I am using FLTK**
 - 1.4.0-rc2

**Describe the solution you'd like**
Make those two functions public.

**Describe alternatives you've considered**
None.

**Comment by ManoloFLTK** [comment]
Isn't this more a problem in pyFLTK (or swig, whatever that is)?

**Comment by ggarra13** [comment]
No.  Actually, it did not work.  The problem happens with any language wrapper (swig, pybind11, etc)  that tries to expose Fl_Browser et. al. methods (public ones are fine of course).  But Fl_Browser, as it derives from Fl_Browser_ has a lot of useful methods protected.
The exposing of the methods, happens like:

```
void* wrap_Fl_Browser_find_item(Fl_Browser* self, int idx)
{
       return $self->find_item(idx);   // this fails as find_item is protected in Fl_Browser_.
}
```

I personally think this is an error in the design of FLTK as it was not properly tested with language bindings.

**Comment by ggarra13** [comment]
I added  a new widget to pyFLTK's more open source code, through a cmake patch.   Somewhat ugly, but it works.
