### ISSUE TITLE
Keyboard shortcut (alt + letter) does not work in input widget (Windows)

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#1122]
**To Reproduce**
```

#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/fl_ask.H>

void hello(Fl_Widget *, void *) {
    fl_message("Hello World");
}

void quit(Fl_Widget*, void*) {
    exit(0);
}

int main(int argc, char ** argv) {
    Fl_Window* window = new Fl_Window(300, 130);
    Fl_Button* b1 = new Fl_Button(10, 10, 280, 30, "&Hello");
    Fl_Button* b2 = new Fl_Button(10, 50, 280, 30, "E&xit");
    Fl_Input* i1 = new Fl_Input(10, 90, 280, 30);

    b1->callback(hello, 0);
    b2->callback(quit, 0);
    i1->take_focus();

    window->end();
    window->show(argc, argv);

    return Fl::run();
}

```

It was commit ae55a42c "`Quick fix for Windows Ctrl character handling - cont'd`" that was responsible.
Same Swedish keyboard now as for the other bug reports I have made about altgr issues.

**Comment by Albrecht-S** [comment]
Thanks! Bug confirmed. Unfortunately this bug blocks release 1.4.0.

@ManoloFLTK? Any idea?

**Comment by Albrecht-S** [comment]
The bug can also be seen in the unmodified `test/input` demo program:

1. Click on any button to give the button focus, then type `Alt-s` or `Alt-m`: focus is given to `Secret` or `Multiline` input fields, respectively (OK).
2. When focus is in one of the input fields: either 's' or 'm' is inserted, focus is not transferred (FAIL).

Note: if `Alt-s` is typed more than once, `s` is inserted and this is logged in the included terminal widget:
```
Callback for &Secret: 's'
Callback for &Secret: 'ss'
Callback for &Secret: 'sss'
Callback for &Secret: 'ssss'
 ```

This is NOT intended and NOT done e.g. on Linux.

**Comment by ManoloFLTK** [comment]
That should be fixed with the commit above.

**Comment by gnuwimp** [comment]
Yes it's working now som I'm closing this issue.

**Comment by Albrecht-S** [comment]
Thanks, Manolo for fixing this!
