### ISSUE TITLE
[Bug] Rounding issues with Fl_RGB_Image::draw() + window scaling

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1128]
**Describe the bug**

Like #1120 but with window scaling added.
When the window is scaled up _or_ down, `Fl_RGB_Image::draw(int, int, int, int, int, int)` sometimes draws pixels from the source image that are outside the region specified by the arguments.

**To Reproduce**

Use the same demo program from #1120 (not re-pasted here just to save screen space).

1. Compile the demo.cxx and run.
2. Scale the window up or down with Ctrl-/+ (or use a display that is set to a non-default scaling factor).
3. See that many of the individually-drawn tiles in the bottom region of the window sometimes have stray strips of pixels that come from the source image, but from outside the specified area.

**Expected behavior**

The exact specified region of the image is what should be drawn to the screen. Extra strips of pixels from immediately outside the region should not be drawn.

**Video**

https://github.com/user-attachments/assets/6f112f71-e02d-4baa-93af-4961aa9a481d

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 114fb66

**FLTK Configure / Build Options**
 - Default VS CMake options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11
 - Processor if relevant: Intel

**Additional context**

I believe the same issue happens on X11, but I will confirm one more time after submitting this.

**Comment by dannye** [comment]
This is a modified version of the demo program from #1124:

```cpp
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_Copy_Surface.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Radio_Round_Button.h>

#include <cassert>
#include <random>

#define TILE_WIDTH 8
#define GRID_WIDTH 50

int png_num_columns = 1;
int png_num_rows = 1;
int png_num_tiles = 1;
int tiles[GRID_WIDTH * GRID_WIDTH] = { 0 };

Fl_RGB_Image *original = nullptr;
Fl_Window *window = nullptr;

bool use_fl_draw_image = false;

void draw_tiles(int X=0, int Y=0) {
    for (int i = 0; i < GRID_WIDTH * GRID_WIDTH; ++i) {
        if (!use_fl_draw_image) {
            original->draw(
                X + (i % GRID_WIDTH) * TILE_WIDTH,
                Y + (i / GRID_WIDTH) * TILE_WIDTH,
                TILE_WIDTH, TILE_WIDTH,
                (tiles[i] % png_num_columns) * TILE_WIDTH,
                (tiles[i] / png_num_columns) * TILE_WIDTH
            );
        }
        else {
            fl_draw_image(
                &original->array[
                    (tiles[i] / png_num_columns) * TILE_WIDTH * (original->w() * original->d()) +
                    (tiles[i] % png_num_columns) * TILE_WIDTH * original->d()
                ],
                X + (i % GRID_WIDTH) * TILE_WIDTH,
                Y + (i / GRID_WIDTH) * TILE_WIDTH,
                TILE_WIDTH, TILE_WIDTH,
                original->d(),
                original->w() * original->d()
            );
        }
    }
}

class Canvas : public Fl_Widget {
public:
    Canvas(int x, int y, int w, int h, char *l=nullptr) : Fl_Widget(x, y, w, h, l) {}

    void draw() {
        draw_tiles(x(), y());
    }
};

void copy_cb(Fl_Widget *w, void *d) {
    float scale = fl_override_scale();
    Fl_Copy_Surface *surface = new Fl_Copy_Surface(TILE_WIDTH * GRID_WIDTH, TILE_WIDTH * GRID_WIDTH);
    surface->set_current();
    draw_tiles();
    delete surface;
    Fl_Display_Device::display_device()->set_current();
    fl_restore_scale(scale);
}

void randomize_cb(Fl_Widget *w, void *d) {
    for (int i = 0; i < GRID_WIDTH * GRID_WIDTH; ++i) {
        tiles[i] = rand() % png_num_tiles;
    }
    window->redraw();
}

void use_image_draw_cb(Fl_Widget *w, void *d) {
    use_fl_draw_image = false;
    window->redraw();
}

void use_fl_draw_image_cb(Fl_Widget *w, void *d) {
    use_fl_draw_image = true;
    window->redraw();
}

int main(int argc, char **argv) {
    original = new Fl_PNG_Image("tiles.png");
    assert(original->w() != 0 && original->w() % TILE_WIDTH == 0);
    assert(original->h() != 0 && original->h() % TILE_WIDTH == 0);
    png_num_columns = original->w() / TILE_WIDTH;
    png_num_rows    = original->h() / TILE_WIDTH;
    png_num_tiles = png_num_columns * png_num_rows;

    window                         = new Fl_Window            (200, 200, 600, 800);
    Fl_Box                *box1    = new Fl_Box               ( 20,   0, 100,  40, "Original:");
    Fl_Box                *box2    = new Fl_Box               ( 20,  40, original->w(), original->h());
    Fl_Button             *button1 = new Fl_Button            (300,  40, 150,  20, "Copy to Clipboard");
    Fl_Button             *button2 = new Fl_Button            (300,  80, 150,  20, "Randomize");
    Fl_Radio_Round_Button *radio1  = new Fl_Radio_Round_Button(300, 120, 150,  20, "Use image->draw()");
    Fl_Radio_Round_Button *radio2  = new Fl_Radio_Round_Button(300, 160, 150,  20, "Use fl_draw_image()");
    Fl_Box                *box3    = new Fl_Box               ( 20, 280, 100,  40, "Random Tiles:");
    Canvas                *canvas  = new Canvas               ( 20, 320, TILE_WIDTH * GRID_WIDTH, TILE_WIDTH * GRID_WIDTH);
    window->end();

    window->resizable(nullptr);
    box1->align(FL_ALIGN_INSIDE | FL_ALIGN_BOTTOM_LEFT);
    box2->align(FL_ALIGN_INSIDE | FL_ALIGN_TOP_LEFT);
    box2->image(original);
    button1->callback(copy_cb);
    button2->callback(randomize_cb);
    radio1->setonly();
    radio1->callback(use_image_draw_cb);
    radio2->callback(use_fl_draw_image_cb);
    box3->align(FL_ALIGN_INSIDE | FL_ALIGN_BOTTOM_LEFT);

    randomize_cb(nullptr, nullptr);

    window->show(argc, argv);
    return Fl::run();
}
```

It includes an option to switch between using `image->draw()` or `fl_draw_image()` for drawing the grid of random times (both drawing to the window and drawing to the clipboard).

It shows that the rounding problems at non-default scales reported in this issue only happen with `image->draw()`.
`fl_draw_image()` always produces the correct result even at 110% scale:

https://github.com/user-attachments/assets/ba3e0bb1-0ae2-4af7-b112-168f4f59a5cf

Additionally, it also shows that `image->draw()` is also _significantly_ slower than `fl_draw_image()`.
See in the video above how long it takes for the grid to repaint when "Use image->draw()" is selected versus how quickly it repaints when "Use fl_draw_image()" is selected.

**Comment by dannye** [comment]
In addition to being slower, `image->draw()` also uses much, _much_ more heap memory when drawing to a Fl_Copy_Surface compared to `fl_draw_image()`:

https://github.com/user-attachments/assets/6a50dff9-522c-4eb4-8f89-1a249acedd54

See in the video how `fl_draw_image()` only uses ~4 MB of memory in total to draw the whole grid of random tiles to the clipboard in almost an instant.
But `image->draw()` takes a whole 905 MB (!) to draw the exact same pixels to the clipboard and takes a full second to do so.

Given that any `image->draw()` call can be purely transformed into an equivalent `fl_draw_image()` call (as done in this program's `draw_tiles()` function), I'm curious what the need for the distinction between them is.

**Comment by dannye** [comment]
> **Additional context**
> 
> I believe the same issue happens on X11, but I will confirm one more time after submitting this.

The rounding issues with window scaling described in the OP do happen on X11 as well.

The performance issues discussed in the follow-up comments do NOT happen on X11.

**Comment by ManoloFLTK** [comment]
The issue on X11, X11+Cairo and Windows should be fixed with commit mentioned above.
I didn't look at what happens when copying to clipboard under Windows.

**Comment by dannye** [comment]
Thanks! I confirmed the issue is fixed (just confirmed on Windows so far).

I can organize the performance questions more cleanly in a new issue a little later, so that it can be looked at whenever time allows (no rush) and so that this issue can be closed. Thanks again.

**Comment by ManoloFLTK** [comment]
@dannye  Here is what I believe happens when copying the image to the clipboard under Windows.

The doc of class `Fl_Copy_Surface` states, for its Windows platform:
> The graphical data are copied to the clipboard in two formats: 1) as an 'enhanced metafile'; 2) as a color bitmap. 

This, I would believe, entails that the clipboard memorizes the series of operations performed to it and plays these operations back when the clipboard content is pasted somewhere else, possibly outside FLTK.

In the case of the example app considered here, this amounts to memorize the tiles.png image several hundred times and explains why that is so costly in memory. My advice would be to write the `copy_cb()` function differently: first, construct the full image piece by piece in an auxiliary `Fl_Image_Surface` object; second, copy the resulting image to the clipboard. Here is what the code could be:
```
void copy_cb(Fl_Widget *w, void *d) {
  Fl_Image_Surface *surface = new Fl_Image_Surface(TILE_WIDTH * GRID_WIDTH, TILE_WIDTH * GRID_WIDTH);
  Fl_Surface_Device::push_current(surface);
  draw_tiles();
  Fl_Surface_Device::pop_current();
  Fl_RGB_Image *rgb = surface->image();
  delete surface;
  Fl_Copy_Surface *copy = new Fl_Copy_Surface(TILE_WIDTH * GRID_WIDTH, TILE_WIDTH * GRID_WIDTH);
  Fl_Surface_Device::push_current(copy);
  rgb->draw(0, 0);
  delete rgb;
  Fl_Surface_Device::pop_current();
  delete copy;
}
```
I don't know how to get the detailed memory footprint you show in your screen videos. I would bet that alternative version of `copy_cb()` would have a much smaller memory footprint.

**Comment by dannye** [comment]
> I would bet that alternative version of `copy_cb()` would have a much smaller memory footprint.

You are absolutely right. Thank you very much for looking into this and for the helpful explanation.
