### ISSUE TITLE
Fullscreen regression between release-1.4.0rc2 and release-1.4.0rc3 on macOS

### ISSUE THREAD

**Issue by geuzaine** [fltk/fltk#1129]
Fullscreen stopped working in our Gmsh app on macOS between release-1.4.0rc2 and release-1.4.0rc3. The FLTK test/fullscreen.cxx still works though, so it might be an edge use-case. In Gmsh fullscreen is not handled through a callback of the window, but on a separate window that we maintain explicitly for fullscreen use.

I did not have time to dig deeper into it, but there seem to have been some changes in fullscreen handling in that development timeframe, so it's probably related to one of these changes...

Tested on macOS 15.0.

**Comment by Albrecht-S** [comment]
Note: FLTK 1.4.0 has been released today. Please investigate further and provide a short example application (full code) that shows the issue if it persists.

**Comment by geuzaine** [comment]
@ManoloFLTK The culprit seems to be commit 5e91ecf: `nswin = [[nswin tabGroup] selectedWindow];` can result in `nswin` to be nullptr, which indeed happens in Gmsh. I've tested this quick-and-dirty fix, which solves the issue:
```
diff --git a/src/Fl_cocoa.mm b/src/Fl_cocoa.mm
index ae40df446..d5f7eab94 100644
--- a/src/Fl_cocoa.mm
+++ b/src/Fl_cocoa.mm
@@ -3284,7 +3284,8 @@ - (void)draggingSession:(NSDraggingSession *)session
 #  if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_7
     NSWindow *nswin = fl_xid(pWindow);
 #    if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_13
-       if (fl_mac_os_version >= 101300) nswin = [[nswin tabGroup] selectedWindow];
+       if (fl_mac_os_version >= 101300 && [[nswin tabGroup] selectedWindow] != nullptr)
+         nswin = [[nswin tabGroup] selectedWindow];
 #    endif
     [nswin toggleFullScreen:nil];
 #  endif
@@ -3375,7 +3376,8 @@ static void restore_window_title_and_icon(Fl_Window *pWindow, NSImage *icon) {
 #  if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_7
     NSWindow *nswin = fl_xid(pWindow);
 #    if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_13
-       if (fl_mac_os_version >= 101300) nswin = [[nswin tabGroup] selectedWindow];
+       if (fl_mac_os_version >= 101300 && [[nswin tabGroup] selectedWindow] != nullptr)
+         nswin = [[nswin tabGroup] selectedWindow];
 #    endif
     [nswin toggleFullScreen:nil];
 #  endif
```

**Comment by geuzaine** [comment]
Confirmed fixed
