### ISSUE TITLE
can't view an optimized png file

### ISSUE THREAD

**Issue by Freddan-67** [fltk/fltk#1136]
**Describe the bug**
FL version 1.3.8, raspberry pi, 
GNU C 12.2.0 (or clang 14.0.6)
Opening an unoptimized png image should work fine
Opening an optimized png image should work fine

**To Reproduce**
Steps to reproduce the behaviour:
run the program with the unoptimized image (see attachment)
works fine
optimize the image with optipng (see attachment)
optipng img/fltk-logo.png
run again
crash at (in gdb)
0xb6f09584 in Fl_Xlib_Graphics_Driver::draw(Fl_RGB_Image*, int, int, int, int, int, int) () from /lib/arm-linux-gnueabihf/libfltk.so.1.3
(gdb) bt
#0  0xb6f09584 in Fl_Xlib_Graphics_Driver::draw(Fl_RGB_Image*, int, int, int, int, int, int) () from /lib/arm-linux-gnueabihf/libfltk.so.1.3
#1  0x004009bc in main (argc=1, argv=0xfffffffff258) at hello_world_fltk.cpp:26
(gdb) p *bg
$2 = {<Fl_RGB_Image> = {<Fl_Image> = {_vptr.Fl_Image = 0xfffff7e2f808 <vtable for Fl_PNG_Image+16>, static ERR_NO_IMAGE = -1,
      static ERR_FILE_ACCESS = -2, static ERR_FORMAT = -3, w_ = 691, h_ = 256, d_ = 3, ld_ = 0, count_ = 1, data_ = 0xaaaaaaad3da8,
      static RGB_scaling_ = FL_RGB_SCALING_NEAREST}, static max_size_ = 18446744073709551615,
    array = 0xfffff712e01 .......

Code: modified the example hello_world_fltk to add a background image with the logo from fltk site
see source file below

compile with additional fltk_images library, see makefile below
g++ -Wall -g -ggdb -fPIC  -o hello_world_fltk hello_world_fltk.cpp -lfltk -lfltk_images

**Expected behavior**
works even with optimized png.
![fltk-logo optpng](https://github.com/user-attachments/assets/e6fb6dae-c7f7-4308-b94a-5b3a7ca5d770)
![fltk-logo](https://github.com/user-attachments/assets/c9b3dce3-be66-4859-9a21-5f33095f5707)

**Screenshots**

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.3.8
 - Installed as package from: [Raspberry pi  bookworm] arm
 - Same with ubuntu 20.04 (1.3.8) aarch64 as package
 - Same with armbian/ubuntu 22.04.5 (1.3.8) arm as package
 - Same with armbian/ubuntu 24.04 trunk (1.3.8)  aarch64 as package
 - Same with ubuntu 24.04.1 x86_64 as package

**FLTK Configure / Build Options**
N/A

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: [Linux]
 - OS Version: [Ubuntu 20.04 arm, Debian 12 arm, Ubuntu 22.04 arm. Ubuntu 24.04 x86_64] (all)
 - Processor if relevant [not relevant]

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Additional context**
Please note that I have optimized ~300 images with optipng. This is the only image I have detected a crash with. Probably because it is so few colour bit planes or that the alpha channel is optimized away.
Source code (sorry couldn't add a c++ file as attachment) 
```C++
// https://github.com/gammasoft71/Examples_FLTK
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Image.H>
#include <FL/Fl_PNG_Image.H>
#include <unistd.h>

#define MARGIN  20
#define IWIDTH 691
#define IHEIGHT 256
#define WIDTH (IWIDTH+MARGIN*2)
#define HEIGHT (IHEIGHT+MARGIN*4)

const char img_file[] = "img/fltk-logo.png";
Fl_PNG_Image *bg; // for debugging
auto main(int argc, char *argv[]) -> int {
  char name[30];
  gethostname(name,sizeof(name));
  char hello[100];
  sprintf(hello,"Hello World, FLTK from {%s}",name);
  auto window = Fl_Window {WIDTH, HEIGHT,hello};
  bg = new Fl_PNG_Image(img_file);
  Fl_Box box = Fl_Box {MARGIN, MARGIN, IWIDTH, IHEIGHT+2*MARGIN, hello};
  bg->draw(MARGIN,MARGIN,IWIDTH,IHEIGHT);
  box.box(FL_UP_BOX);
  box.labelfont(FL_BOLD);
  box.labelsize(25);
  box.labeltype(FL_NORMAL_LABEL);
  box.align(FL_ALIGN_INSIDE|FL_ALIGN_CENTER|FL_ALIGN_CLIP);
  box.image(bg);
  window.show(argc, argv);
  return Fl::run();
}
```

Makefile (sorry couldn't add a makefile as attachment)
```
ALL=hello_world_fltk
CXX=g++
CXXFLAGS=-Wall -g -ggdb -fPIC
LIBS=-lfltk -lfltk_images
ALL:$(ALL)

%: %.cpp
        $(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)
```

EDIT: modified markdown for C++ source and Makefile

**Comment by ManoloFLTK** [comment]
I tried here to read with FLTK the optimized FLTK logo png file. No problem.

In contrast, this line of your source code is a source of error
```
 bg->draw(MARGIN,MARGIN,IWIDTH,IHEIGHT);
```
I would recommend you remove this statement and try again.

I attach the 2 .png files used:

![fltk-opti](https://github.com/user-attachments/assets/79061365-90fe-4c05-8898-dcdbdf908d91)
![fltk-logo](https://github.com/user-attachments/assets/35fe02fc-f89a-4eb6-97f7-e03eb53529f3)

**Comment by Freddan-67** [comment]
Thank you very much, I can agree that your proposed change solved the problem
It was apparently a PBKAC on my side.
