### ISSUE TITLE
Add Fl_Text_Display::top_line_number()

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1153]
**Is your feature request related to a problem? Please describe.**
Fl_Text_Display keeps the top displayed line number in a protected variable, but this should be made accessible in a public function.  This is the displayed line number which is different from the insert_position.  For example:

int Fl_Text_Display::top_line_number() or top_displayed_line_number().

**I am using FLTK**
 - 1.4.0-release-1

**Describe the solution you'd like**
Add a public function to access the currently mTopLineNumHint protected variable.

**Describe alternatives you've considered**
I've created my own widget to expose the function for pyFLTK.  It works, but this should be added to FLTK itself.

**Comment by Albrecht-S** [comment]
> to access the currently mTopLineNumHint protected variable

@ggarra13 Actually there are two similar variables: `mTopLineNum` and `mTopLineNumHint`. Are you sure that `mTopLineNumHint` is the variable you want to be exposed, or should it be `mTopLineNum`?

@MatthiasWM This should be doable even in 1.4.1 or a later release but I can't tell why the mentioned variable is protected and how reliable it would be to expose it - and I wouldn't want to spend time on investigating. Maybe you, Matthias, can help?

**Comment by Albrecht-S** [comment]
FTR: while looking around I found in `fluid/CodeEditor.h`:
```
  /// access to protected member get_absolute_top_line_number()
  int top_line() { return get_absolute_top_line_number(); }

  /// access to protected member mTopLineNum
  int scroll_row() { return mTopLineNum; }

  /// access to protected member mHorizOffset
  int scroll_col() { return mHorizOffset; }
```

Note: This is just a hint that **_some of these variables_** may be useful in user software and I'm not suggesting to use any of these names, maybe other names could be more appropriate.

**Comment by ggarra13** [comment]
@Albrecht-S I think you are right.  It is mTopLineNum the one I want.  Thanks!

**Comment by MatthiasWM** [comment]
Ok, I moved the FLUID hack to the Fl_Text_Display header file. The scroll... naming makes sense IMHO because the returned values mirror the `Fl_Text_Display::scroll(int, int)` call.
