### ISSUE TITLE
Hang/Infinite loop on submenu with all inactive/invisible items

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1158]
**Describe the bug**

If a menubar contains only inactive and invisible items, and the mouse is pressed on the menubar and then the left or right arrow key is pressed, FLTK gets stuck in an infinite loop in `forward()` or `backward()`.

**To Reproduce**

Apply this patch to test/menubar.cxx to make all the top-level items inactive or invisible:

```diff
diff --git a/test/menubar.cxx b/test/menubar.cxx
index a5ccfc234..1c0f5a898 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -67,7 +67,7 @@ Fl_Menu_Item hugemenu[100];
 
 Fl_Menu_Item menutable[] = {
   {"foo",0,0,0,FL_MENU_INACTIVE},
-  {"&File",0,0,0,FL_SUBMENU},
+  {"&File",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"&Open",   FL_ALT+'o', 0, 0, FL_MENU_INACTIVE},
     {"&Close",  0,      0},
     {"&Quit",   FL_ALT+'q', quit_cb, 0, FL_MENU_DIVIDER},
@@ -108,7 +108,7 @@ Fl_Menu_Item menutable[] = {
       {"after submenu"},
       {0},
     {0},
-  {"&Edit",FL_F+2,0,0,FL_SUBMENU},
+  {"&Edit",FL_F+2,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"Undo",        FL_ALT+'z',  0},
     {"Redo",        FL_ALT+'r',  0, 0, FL_MENU_DIVIDER},
     {"Cut",         FL_ALT+'x',  0},
@@ -120,7 +120,7 @@ Fl_Menu_Item menutable[] = {
     {"Preferences", 0,           0},
     {"Size",        0,           0},
     {0},
-  {"&Checkbox",FL_F+3,0,0,FL_SUBMENU},
+  {"&Checkbox",FL_F+3,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"&Alpha",  FL_F+2, 0, (void *)1, FL_MENU_TOGGLE},
     {"&Beta",   0,      0, (void *)2, FL_MENU_TOGGLE},
     {"&Gamma",  0,      0, (void *)3, FL_MENU_TOGGLE},
@@ -133,7 +133,7 @@ Fl_Menu_Item menutable[] = {
     {"00",      0,      0, (void *)1, FL_MENU_TOGGLE},
     {"000",     0,      0, (void *)1, FL_MENU_TOGGLE},
     {0},
-  {"&Radio",0,0,0,FL_SUBMENU},
+  {"&Radio",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"&Alpha",  0,      0, (void *)1, FL_MENU_RADIO},
     {"&Beta",   0,      0, (void *)2, FL_MENU_RADIO},
     {"&Gamma",  0,      0, (void *)3, FL_MENU_RADIO},
@@ -146,7 +146,7 @@ Fl_Menu_Item menutable[] = {
     {"00",      0,      0, (void *)1, FL_MENU_RADIO},
     {"000",     0,      0, (void *)1, FL_MENU_RADIO},
     {0},
-  {"&Font",0,0,0,FL_SUBMENU /*, 0, FL_BOLD, 20*/},
+  {"&Font",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE /*, 0, FL_BOLD, 20*/},
     {"Normal",  0, 0, 0, 0, 0, 0, 14},
     {"Bold",    0, 0, 0, 0, 0, FL_BOLD, 14},
     {"Italic",  0, 0, 0, 0, 0, FL_ITALIC, 14},
@@ -157,7 +157,7 @@ Fl_Menu_Item menutable[] = {
     {"Shadow",  0, 0, 0, 0, (uchar)FL_SHADOW_LABEL},
     {"@->",     0, 0, 0, 0, (uchar)FL_SYMBOL_LABEL},
     {0},
-  {"&International",0,0,0,FL_SUBMENU},
+  {"&International",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"Sharp Ess",0x0000df},
     {"A Umlaut",0x0000c4},
     {"a Umlaut",0x0000e4},
@@ -169,7 +169,7 @@ Fl_Menu_Item menutable[] = {
     {"Hangul character Sios &\xe3\x85\x85"},
     {"Hangul character Cieuc", 0x003148},
     {0},
-  {"E&mpty",0,0,0,FL_SUBMENU},
+  {"E&mpty",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {0},
   {"&Inactive", 0,      0, 0, FL_MENU_INACTIVE|FL_SUBMENU},
     {"A very long menu item"},
@@ -179,8 +179,8 @@ Fl_Menu_Item menutable[] = {
     {"A very long menu item"},
     {"A very long menu item"},
     {0},
-  {"&Huge", 0, 0, (void*)hugemenu, FL_SUBMENU_POINTER},
-  {"button",FL_F+4, 0, 0, FL_MENU_TOGGLE},
+  {"&Huge", 0, 0, (void*)hugemenu, FL_SUBMENU_POINTER|FL_MENU_INACTIVE},
+  {"button",FL_F+4, 0, 0, FL_MENU_TOGGLE|FL_MENU_INACTIVE},
   {0}
 };
```

1. Apply the above patch and run test/menubar
2. Click on the menubar
3. Press Left or Right
4. See that FLTK has hung

**Expected behavior**

Nothing should happen when left or right is pressed on a menubar of inactive items.

Arguably, a menubar with all inactive/invisible items shouldn't even take focus when pressed with the mouse. But that can be left alone for now.

**Video**

https://github.com/user-attachments/assets/fedcbfa6-355b-4b25-b554-e28881f85ffd

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5ff42dd

**FLTK Configure / Build Options**
 - Default CMake options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Additional context**

I'll include a simple fix with #1157.

**Comment by dannye** [comment]
This bug is actually not as rare or as contrived as it is in the OP.

This bug also happens when pressing right arrow to enter an ACTIVE submenu that contains only inactive items:

```diff
diff --git a/test/menubar.cxx b/test/menubar.cxx
index a5ccfc234..52bc09224 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -98,14 +98,14 @@ Fl_Menu_Item menutable[] = {
     {"shortcut",FL_ALT+FL_CTRL+FL_F+1},
     {"shortcut",FL_ALT+FL_SHIFT+FL_CTRL+FL_F+1, 0,0, FL_MENU_DIVIDER},
     {"&Submenus", FL_ALT+'S',   0, (void*)"Submenu1", FL_SUBMENU},
-      {"A very long menu item"},
-      {"&submenu",FL_CTRL+'S',  0, (void*)"submenu2", FL_SUBMENU},
+      {"A very long menu item", 0, 0, 0, FL_MENU_INACTIVE},
+      {"&submenu",FL_CTRL+'S',  0, (void*)"submenu2", FL_SUBMENU | FL_MENU_INACTIVE},
         {"item 1"},
         {"item 2"},
         {"item 3"},
         {"item 4"},
         {0},
-      {"after submenu"},
+      {"after submenu", 0, 0, 0, FL_MENU_INACTIVE},
       {0},
     {0},
   {"&Edit",FL_F+2,0,0,FL_SUBMENU},
```

https://github.com/user-attachments/assets/daee4b01-c4be-4005-a118-bc977950d5c7

The program hangs as soon as I press the right arrow key while hovering over the submenu item.

This started happening sometime between e5693ef and 634ce80, because that's when my editor starting being susceptible to this bug:

https://github.com/user-attachments/assets/14eebe18-86d6-4472-840b-e8dbf8b64ff7

**Comment by Albrecht-S** [comment]
> This started happening sometime between e5693efb75f8ab50362256c630421e71291cfb46 and 634ce805e5de4663fc9efdb288ed5b726af96005, ...

FWIW, there are six commits that deal with `Fl_Menu*` header or source files:
```
$ git lp e5693efb75f8..634ce805e5de -- FL/Fl_Menu*.H src/Fl_Menu*.cxx
ec05f78d98d8 2024-08-27 15:13:32 +0200 Matthias Melcher   - Adding horiizonatl and vertical label margin
cfc54a3b190d 2024-08-14 01:52:37 +0200 Matthias Melcher   - Adding Fl_Widget::label_image_spacing() (#1039)
46dd1b33ccb1 2024-08-04 11:53:35 +0200 dannye             - Fix testing of multi-label alt shortcuts (#974)
b692cc55dabb 2024-06-27 07:45:45 +0200 ManoloFLTK         - Navigation in menubar: wrap around when using arrow past end or start of menubar.
fe4c94b4dc5d 2024-06-25 13:23:49 +0200 ManoloFLTK         - Navigation in menubar: wrap around when using arrow past end or start of menubar.
c1a950e25fec 2024-06-24 16:18:56 +0200 ManoloFLTK         - Navigation in menubar: wrap around when using arrow past end or start of menubar.
```
... where `git lp` is a special alias defined by me. I removed one more commit (done by me) from the list because it only changed whitespace. I'm not going to investigate further, leaving this to others...

HTH

**Comment by ManoloFLTK** [comment]
@dannye The various issues mentioned here should be fixed with commit 5af4108.

**Comment by dannye** [comment]
Again, my proposed pull request resolved this issue *and more*. Was it really not worth having a discussion on that PR?

**Comment by ManoloFLTK** [comment]
@dannye I had not seen a PR was referenced above. Please avoid to submit both an issue and a PR that fixes the issue. Choose either one or the other. This in the interest of preventing duplication of efforts.

**Comment by dannye** [comment]
> Please avoid to submit both an issue and a PR that fixes the issue.

Okay, but I rather like the "bug report template" format, and sometimes while writing the bug report I don't yet know how simple the fix will be or if I will be capable of fixing it myself.

As soon as I associate a pull request with an issue report in GitHub, a link to the pull request is added to the issue page in at least 3 different spots (the very top, the right, and the bottom of the page).

But if I ever do this again in the future, I will clearly announce it in a comment on the issue too to avoid confusion. Sorry about that.
