### ISSUE TITLE
Mouse hover+Enter key selects inactive menu items

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1159]
**Describe the bug**

Hovering over an inactive menu item and pressing Enter picks the item and invokes its callback.

I have no idea how I've never noticed this in over two years.

This means that marking a menu item as FL_MENU_INACTIVE is merely a suggestion to the user.

**To Reproduce**

1. Run test/menubar
2. Click on any menubar item (even an inactive one!)
3. Hover over an inactive menu item (in the menubar or in a submenu)
4. Press Enter
5. See that the menu item was picked and its callback was invoked

**Expected behavior**

Pressing Enter while hovering over an inactive menu item should do nothing.

**Video**

https://github.com/user-attachments/assets/680399de-0d8d-41e7-b9e0-dd4d78724650

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5ff42dd

**FLTK Configure / Build Options**
 - Default CMake options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Additional context**

As you could expect, this can be very destructive for applications that assume inactive menu items will never be picked.

Here's an amusing example from my editor where a whole song can be deleted _while it's playing_, which is absolutely not supposed to be possible.

https://github.com/user-attachments/assets/e74e9f8e-791f-4d33-b17e-2f8369808f17

Many of my menu item callbacks have safeguards that return early if conditions don't make sense, but not all of them do. In some cases, the program crashes.

**Comment by ManoloFLTK** [comment]
@dannye Please close issue if you see it fixed with commit mentioned above.

**Comment by dannye** [comment]
Okay, but my proposed pull request already solved this issue plus more..

**Comment by dannye** [comment]
Commit 80c94eb makes an undesirable change which is that the Enter key no longer dismisses a menu while no menu item is picked.

The correct solution is in PR #1160.

**Comment by MatthiasWM** [comment]
Thanks for the suggested patch @dannye , and thanks for the pushed code, @ManoloFLTK . I took both solutions into consideration and needed up adding a "return 1" instead of 0 because the keyboard event should not be resent to other windows IMHO. Please let me know if this fixes your case, and if there are additional considerations.

I am going on to #1160 and I will apply the remaining changes if the fix the issue.

Lastly, I did some formatting on the incredible 'if' statement right above the feed code ;-) .

**Comment by dannye** [comment]
Sounds good. The last change in #1160 is more subjective, so feel free to use it, or not.

**Comment by MatthiasWM** [comment]
I am not sure why GitHub decided to separate Issues and Pull Requests. The functionalities are quite similar. It's possible to change an Issue into a PR with the GitHub command line app: `hub pull-request -i <issue number>`.

IMHO it's important to set Assignees and only fix bugs after assigning oneself. This would in theory work for the Issue/PR problem as well by assigning oneself in both forms. It's unfortunate if two developers spend time on the same issue, an even worse if we have to decide which patch to use (and which to throw away... ;-) ).

**Comment by dannye** [comment]
> IMHO it's important to set Assignees and only fix bugs after assigning oneself.

I agree but I can't make myself an assignee :-)

**Comment by Albrecht-S** [comment]
I agree with @MatthiasWM's comment above which is directed to FLTK devs (only those with write access can assign someone).

@dannye wrote:
> I agree but I can't make myself an assignee

That's true but you can - as you wrote elsewhere - drop an explicit note on the issue
- when you work on it (if e.g. no developer was assigned after some time)
- when you are ready and open a PR regarding that issue.

Note: I followed the discussion and noticed wordings like _"this PR would have fixed issue N **and more**..."_. I'm aware that sometimes things are related, particularly when you're intensely testing menu related issues (as you obviously did, thanks for that!) but it's hard to manage multiple issues and related PR's together.

Ideally there would be only one PR for one issue and not one PR for multiple issues. Emphasis on **_ideally_**. If it can't be avoided, please add notes so the devs are aware of this situation. Thanks.

**Comment by dannye** [comment]
Sorry for the tension I caused today and thank you, all three of you, for all your help and consideration. I'll avoid these problematic situations in the future.

**Comment by MatthiasWM** [comment]
Thanks for putting the effort in to make PRs. I am sure we will get tasks synchronized.
