### ISSUE TITLE
fluid 1.4.0 generates trailing whitespace

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#1161]
**Description**
fluid 1.4.0 generates trailing whitespace for an empty line within a comment in `fluid/codeview_panel.fl`.

**To Reproduce**
```
$ cd fluid
$ ./fluid -c codeview_panel.fl
$ git diff --check
fluid/codeview_panel.cxx:35: trailing whitespace.
+ 
```

```diff
$ git diff
diff --git a/fluid/codeview_panel.cxx b/fluid/codeview_panel.cxx
index f9496b7ba..0cd81f4c5 100644
--- a/fluid/codeview_panel.cxx
+++ b/fluid/codeview_panel.cxx
@@ -32,7 +32,7 @@ extern void reveal_in_browser(Fl_Type *t);
 /**
  Update the header and source code highlighting depending on the
  currently selected object
-
+ 
  The Code View system offers an immediate preview of the code
  files that will be generated by FLUID. It also marks the code
  generated for the last selected item in the header and the source
```

**Expected behavior**
Fluid should not output trailing whitespace.

**FLTK Version**
 - Version: 1.4.0, git master (fe8177ea2ce409702882cf40f9e9dbc435dd3d84)

**Operating System / Platform:**
irrelevant

**Additional context**
- I noticed the issue when I updated all fluid files in preparation of release 1.4.1
- this is the only issue, no other fluid files are concerned
- trailing whitespace can potentially be rejected by Git (not in our config though).

**Comment by Albrecht-S** [comment]
This is a minor bug but it should IMHO be fixed anyway. I set label "Regression" but I couldn't run it with fluid 1.3.10 and didn't check (git bisect?) older 1.4.x versions.

Probably an issue for @MatthiasWM but I didn't assign it.

**Comment by MatthiasWM** [comment]
I am surprised that this is a regression. The old code was never able to not output indent spaces on empty lines. Maybe an external editor fixed that at a previous commit. Anyway, master should have that fixed.

**Comment by Albrecht-S** [comment]
> I am surprised that this is a regression.

@MatthiasWM : I'm pretty sure that there was a time in FLTK 1.4 development where fluid didn't generate trailing whitespace with any of our `.fl` files in the FLTK repo. I can't tell however if we had such a case that **would** have generated trailing spaces. This can't be verified w/o bisecting the Git repo but that would be wasted time.

Thanks for your commit (ead9078bc3a1bfc2a80bef4bfda2ff2fed7e5b4f), I confirm that it fixes the issue.

Closing now.
