### ISSUE TITLE
Fl_Check_Button text draw blurry

### ISSUE THREAD

**Issue by tanxn5** [fltk/fltk#1165]
Mouse down on a Fl_Check_Button and drag around, the label draw again without BG erase. 
It make the label looks blurry.

**Comment by dannye** [comment]
Related discussion: #1130

**Comment by Albrecht-S** [comment]
Yes, this is indeed a known issue and can hopefully be fixed in the future. A full fix will likely be implemented in FLTK 1.5.0, the next minor release. Since it is only a minor drawing issue its priority is `Low`.

**Comment by MatthiasWM** [comment]
See 34b5fe9e92a560d0507838c3dc1c6c3fd19648f9.

**Comment by tanxn5** [comment]
> @tanxn5 Thanks for your report. In the future please use the [bug report template](https://github.com/fltk/fltk/issues/new/choose) (click "Get started" right of "Bug report") and fill in the information about your FLTK version and platform. Thanks in advance.
> 
> Please confirm that the latest fix in commit [34b5fe9](https://github.com/fltk/fltk/commit/34b5fe9e92a560d0507838c3dc1c6c3fd19648f9) fixes the issue for you. This is currently only available in Git (master) but will be in the next release 1.4.1 as well.
> 
> If yes, please close the issue.

Thanks. Ill see to it.
