### ISSUE TITLE
Window can be moved while menu is open

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1166]
**Describe the bug**

This is very minor because it is so harmless and circumstantial.

On Windows, if a pulldown menu, popup menu, or menubar is open and Alt+Tab is used to switch windows (and switch back) the main window can be dragged around by its title bar, detaching it from its menu.

**To Reproduce**

1. Run test/menubar
2. Open a pulldown menu, popup menu, or menubar
3. Press Alt+Tab to switch to another window
4. Press Alt+Tab again to switch back to the menubar program (Edit: this step actually isn't necessary)
5. See that the window can be dragged around by the title bar and the menu will not be dismissed or moved

**Expected behavior**

The menu should be dismissed when the mouse is pressed on the title bar (like what happens when Alt+Tab isn't used).

Or maybe the menu should be dismissed as soon as Alt+Tab is pressed (like when using the mouse to switch to a different window).

**Video**

https://github.com/user-attachments/assets/1d55b0b6-e63e-43f0-bbe3-6226207df86c

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 34b5fe9

**FLTK Configure / Build Options**
 - Default VS CMake options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Additional context**

While in this state, the window cannot be minimized/maximized/closed using the buttons in the top-right of the titlebar, and cannot be resized by using the edges of the window. But the window can be maximized by dragging the window against the top edge of the display. (Edit: This may depend on Windows version or other factors. On my Windows 10 PC I noticed that the window _can_ be resized in all the usual ways.)

I couldn't reproduce this on Mac or X11.

**Comment by ManoloFLTK** [comment]
@dannye Please, close issue if you see it fixed with commit mentioned above.

**Comment by dannye** [comment]
Thanks @ManoloFLTK, this is a good improvement.

The menu still sticks around for as long as the window is being dragged and only closes once the window is finally dropped:

https://github.com/user-attachments/assets/3ca20881-a68a-40f5-8c49-9bea08da2b37

If you're aware of and okay with this compromise then feel free to close the issue.

Thanks again!

**Comment by ManoloFLTK** [comment]
It should be better with 86eaf0f.

**Comment by dannye** [comment]
Yes! Thank you very much!

**Comment by Albrecht-S** [comment]
@ManoloFLTK @dannye Are you sure that this is the latest and working fix?

**I'm in the release process of FLTK 1.4.1** and would really like to get a stable fix into it!

Are you both confident that 86eaf0f90577cec8f56f29eaca41d75468f56ffb is the final fix?

**Comment by ManoloFLTK** [comment]
For me, that's the final fix.

**Comment by dannye** [comment]
Yes, all good, thank you.
