### ISSUE TITLE
memcmp out of bounds in Fl_Quartz_Graphics_Driver_font.cxx

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#117]
In the skip() function of Fl_Quartz_Graphics_Driver_font.cxx (OS X) a comparison is made with potentially out of bounds strings.  The solution is to compare the strlen before hand.  Find patch attached.
[memcmp-fix.zip](https://github.com/fltk/fltk/files/4973032/memcmp-fix.zip)

**Comment by erco77** [comment]
What's in the patch, for those browsing:
```
index c528f2721..8a3d9b416 100644
--- a/src/drivers/Quartz/Fl_Quartz_Graphics_Driver_font.cxx
+++ b/src/drivers/Quartz/Fl_Quartz_Graphics_Driver_font.cxx
@@ -620,13 +620,20 @@ void Fl_Quartz_Graphics_Driver::ADD_SUFFIX(draw, _CoreText)(const char *str, int
 
 static char *skip(char *p, int& derived)
 {
-  if (memcmp(p, "-BoldItalic", 11) == 0) { p += 11; derived = 3; }
-  else if (memcmp(p, "-BoldOblique", 12) == 0) { p += 12; derived = 3; }
-  else if (memcmp(p, "-Bold", 5) == 0) {p += 5; derived = 1; }
-  else if (memcmp(p, "-Italic", 7) == 0) {p += 7; derived = 2; }
-  else if (memcmp(p, "-Oblique", 8) == 0) {p += 8; derived = 2; }
-  else if (memcmp(p, "-Regular", 8) == 0) {p += 8; }
-  else if (memcmp(p, "-Roman", 6) == 0) {p += 6; }
+  if (strlen(p) >= 11 &&
+      memcmp(p, "-BoldItalic", 11) == 0) { p += 11; derived = 3; }
+  else if (strlen(p) >= 12 &&
+           memcmp(p, "-BoldOblique", 12) == 0) { p += 12; derived = 3; }
+  else if (strlen(p) >= 5 &&
+           memcmp(p, "-Bold", 5) == 0) {p += 5; derived = 1; }
+  else if (strlen(p) >= 7 &&
+           memcmp(p, "-Italic", 7) == 0) {p += 7; derived = 2; }
+  else if (strlen(p) >= 8 &&
+           memcmp(p, "-Oblique", 8) == 0) {p += 8; derived = 2; }
+  else if (strlen(p) >= 8 &&
+           memcmp(p, "-Regular", 8) == 0) {p += 8; }
+  else if (strlen(p) >= 6 &&
+           memcmp(p, "-Roman", 6) == 0) {p += 6; }
   return p;
 }
 

```

**Comment by erco77** [comment]
Is there a reason not to use `strncmp()` here?  e.g. `strncmp(p, "-BoldItalic", 11) == 0 ) ..`
Or are these not null terminated strings?

**Comment by ggarra13** [comment]
On 28/7/20 23:10, erco77 wrote:
>
> Is there a reason not to use |strncmp()| here? e.g. |strncmp(p, 
> "-BoldItalic", 11) == 0 ) ..|
> Or are these not null terminated strings?
>
p is not null terminated and that's why you can get an out of bounds 
read access.

--

Gonzalo Garramuño

**Comment by ggarra13** [comment]
On 28/7/20 23:10, erco77 wrote:
>
> Is there a reason not to use |strncmp()| here? e.g. |strncmp(p, 
> "-BoldItalic", 11) == 0 ) ..|
> Or are these not null terminated strings?
>
Never mind me.  strncmp should be fine.

-- 
Gonzalo Garramuño

**Comment by ggarra13** [comment]
Here's the modified patch:

index c528f2721..ae0a6731a 100644
--- a/src/drivers/Quartz/Fl_Quartz_Graphics_Driver_font.cxx
+++ b/src/drivers/Quartz/Fl_Quartz_Graphics_Driver_font.cxx
@@ -620,13 +620,13 @@ void Fl_Quartz_Graphics_Driver::ADD_SUFFIX(draw, _CoreText)(const char *str, int
 
 static char *skip(char *p, int& derived)
 {
-  if (memcmp(p, "-BoldItalic", 11) == 0) { p += 11; derived = 3; }
-  else if (memcmp(p, "-BoldOblique", 12) == 0) { p += 12; derived = 3; }
-  else if (memcmp(p, "-Bold", 5) == 0) {p += 5; derived = 1; }
-  else if (memcmp(p, "-Italic", 7) == 0) {p += 7; derived = 2; }
-  else if (memcmp(p, "-Oblique", 8) == 0) {p += 8; derived = 2; }
-  else if (memcmp(p, "-Regular", 8) == 0) {p += 8; }
-  else if (memcmp(p, "-Roman", 6) == 0) {p += 6; }
+  if (strncmp(p, "-BoldItalic", 11) == 0) { p += 11; derived = 3; }
+  else if (strncmp(p, "-BoldOblique", 12) == 0) { p += 12; derived = 3; }
+  else if (strncmp(p, "-Bold", 5) == 0) {p += 5; derived = 1; }
+  else if (strncmp(p, "-Italic", 7) == 0) {p += 7; derived = 2; }
+  else if (strncmp(p, "-Oblique", 8) == 0) {p += 8; derived = 2; }
+  else if (strncmp(p, "-Regular", 8) == 0) {p += 8; }
+  else if (strncmp(p, "-Roman", 6) == 0) {p += 6; }
   return p;
 }

**Comment by ggarra13** [comment]
[0001-Changed-memcmp-for-strncmp.zip](https://github.com/fltk/fltk/files/4995089/0001-Changed-memcmp-for-strncmp.zip)

**Comment by erco77** [comment]
@ManoloFLTK just checking if this sounds OK, I can apply if you're busy.
Wasn't sure why memcmp() was being used, as perhaps maybe there was a reason to avoid strncmp().

**Comment by ManoloFLTK** [comment]
@Greg: please go ahead and apply if OK. I always forget to use strncmp and use memcmp instead
without no good reason.

**Comment by erco77** [comment]
Thanks Manolo, closed.
(Added a short descriptive comment header to skip(), feel free to make adjustments)
