### ISSUE TITLE
Xlib: Drawing SVG images in scaled mode without XRender has drawing artefacts (invalid reads)

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#119]
When drawing SVG-images in a scaled mode (FLTK_SCALING_FACTOR > 1.0) there are drawing artefacts at the bottom line of the images.  This is due to out of bounds reads of the source image (Valgrind reports these correctly).

The  method `void Fl_Xlib_Graphics_Driver::draw_fixed(Fl_RGB_Image *img, int X, int Y, int W, int H, int cx, int cy)` adapts W and H for scaling by calling `cache_size()`, which return somewhat bigger values. Then this W and H are passed to the `alpha_blend`function, which iterates over W and H to read the source data. As the source has less data than WxH there are invalid reads.

To reproduce compile FLTK **without** XRender support (e..g. set X_RENDER = 0 in `config.h`) and set a scaling factor with the envirioment variable FLTK_SCALING_FACTOR e.g. `export FLTK_SCALING_FACTOR=1.28`), then use the `pixmap_browser` demo program to load SVG images.

**Comment by Albrecht-S** [comment]
Thanks for the bug report, the analysis which sounds sensible, and the test description.

I think this is one for @ManoloFLTK

**Comment by ManoloFLTK** [comment]
That should be fixed now in the git repository.
Thanks for the report.
@wcout: Please, close if you confirm the fix.

**Comment by wcout** [comment]
I can confirm, that this fix solves the drawing artifacts and seems to have no other side effects.
Thank you very much for the quick response.
