### ISSUE TITLE
SSE/AVX support

### ISSUE THREAD

**Issue by shlyakpavel** [fltk/fltk#12]
Hello. I've been working around the project for a while and it's really nice.
However, I didn't find out if it has explicit support for modern vector instructions like Intel AVX or arm NEON. I am not sure if it helps to improve rendering speed, but I would really appreciate if you provide some estimations:
1. Does FLTK need it at all?
2. What is the actual state of supporting it?
3. Could such extentions be merged into master if proper built flags are provided with PR?
4. What parts of FLTK are "bottle necks" in terms of performance? Any estimations of the possible benefit of optimizing it?
I am really eager to find a proper project for optimizing with AVX as it is a part of task I have in my university :) Any ideas are appreciated. Have a nice day!

**Comment by fab672000** [comment]
I think it would be an unfortunate  mix a concerns to use avx (or any streaming other simd) technology in FLTK.

This kind of acceleration makes total sense in heavily dependent on DSP calculations applications such as video real-time filters, audio DSP virtual realtime effects, compression, encryption ...
3D rendering heavy loads are typically  dealt with GPU's today not really much with CPU's.

FLTK is mostly dealing with providing portable user interfaces that don't need much CPU power at all, so I would not think of a solid use case for FLTK to start implementing this kind of library.

**Comment by Albrecht-S** [comment]
@shlyakpavel If you have questions regarding the development of the FLTK library (and if this question is not yet answered sufficiently by Fabien) please ask such questions in our discussion group for developers:
[fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev).
