### ISSUE TITLE
Building fltk via vcpkg on Windows not working

### ISSUE THREAD

**Issue by jlfilion** [fltk/fltk#120]
Hello,

I'm using fltk 1.3.5-2, x64 Windows, on Windows 10. I can't get past the cmake setup.

I'm trying to use the fltk library in both Windows and Linux. I don't seem to be having problems in Linux, but Windows has been impossible for me. I'm trying to use vcpkg and cmake. I installed the fltk for x64-windows package using "vcpkg.exe install fltk:x64-windows" and it seemed to install fine. It tells me what to enter for cmake, but when I enter that, I just get the following errors: 

CMake Error at C:/Users/jfilion/vcpkg/installed/x64-windows/share/fltk/FLTK-Targets.cmake:93 (message):
  The imported target "fltk_SHARED" references the file

     "C:/Users/jfilion/vcpkg/installed/x64-windows/debug/lib/fltk_SHAREDd.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/Users/jfilion/vcpkg/installed/x64-windows/share/fltk/FLTK-Targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/Users/jfilion/vcpkg/installed/x64-windows/share/fltk/FLTKConfig.cmake:21 (include)
  C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake:441 (_find_package)
  myapp/CMakeLists.txt:28 (find_package)

I reported this on a vcpkg forum and got a response. I then got an email saying they fixed the problem and closed it out. But I've updated everything in vcpkg and I'm still having the problem. I'm using vcpkg for quite a few other libraries with no problems. I can't figure out what I'm doing wrong with this one. Is there some other step in all of this that I'm missing?

Thanks for any help you can provide.
Joe

**Comment by Albrecht-S** [comment]
I'm sorry to say that we can't answer questions about 3rd party tools (`vcpkg`). I'm trying to provide some more info but I'm afraid we can't help.

1. There is no **official** `fltk 1.3.5-2`. Our latest release is `1.3.5`. We don't know what this `fltk 1.3.5-2` is and where you got it from. If it's a patched version in any way, please ask the person or group that provided it.

2. The error message you posted seems to indicate that you were using a Windows **Debug** build, hence the 'd' suffix in `fltk_SHAREDd.lib`. This is the default in a Visual Studio **Debug** build on Windows. Maybe the `vcpkg` install renames this file.

3. FLTK's CMake support in version 1.3.5 is not yet complete (beta stadium) and may have issues. You can't rely on it 100% yet. We're working on improvements in the future version 1.4.0.

That all said: we can't help. Last but not least: this is not our forum for user questions. Standard reply follows:

> This is the wrong place to ask questions about building or running programs built with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

Please note that you will likely **NOT** get answers about how to use `vcpkg` in `fltk.general`, although it is possible if other users are also using `vcpkg` and can help you with your problem.

**Comment by jlfilion** [comment]
Thank you for your prompt reply and please accept my apologies for
submitting to the incorrect forum. I wasn't aware that Microsoft was
accepting library submissions for vcpkg from anyone other than the library
owners, so I assumed it came from you. It's actually a bit scary if anyone
can submit libraries to them other than the official authors.

I will likely try to hunt down the true author of the vcpkg submission and
I may post on the general forum as you suggested. I'll look forward to your
completion of the CMake support.

Thanks again,
Joe

**Comment by Albrecht-S** [comment]
No apologies necessary. Thanks for your understanding. If you find out who the author is and how it was uploaded to the vcpkg system we'd appreciate a note in fltk.general. TIA.

**Comment by jlfilion** [comment]
For reference on this issue: https://github.com/microsoft/vcpkg/issues/12291

They were very helpful.

**Comment by Albrecht-S** [comment]
Thank you very much for your feedback.

I found vcpkg meanwhile, but your issue and its solution is very interesting. My impression (w/o actual testing) is that vcpkg would download the original tarball but patch it as "they" need it. I'll look into it further...
