### ISSUE TITLE
During #116, noticed Fl_Check_Browser needs some whitespace fixups

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#121]
Albrecht agreed, [see this issue 116 comment](https://github.com/fltk/fltk/pull/116#discussion_r458522494)

Suggestion was to use clang-format, but I decided to take a manual shot at it anyway, and noticed a few oddball things (like ';' at the end of C style comments) that I'm not sure clang would fix, and one small code mod `if (p==0)` vs `if (!p)` that I think improves readability, and a few other non-code things to improve readability.

Patch attached here, too lazy to create a fork and all that.
[Fl_Check_Browser--whitespace-patch.txt](https://github.com/fltk/fltk/files/5012528/Fl_Check_Browser--whitespace-patch.txt)

**Comment by Albrecht-S** [comment]
I believe there's nothing wrong with your patch `Fl_Check_Browser--whitespace-patch.txt` but I used `clang-format` to verify anyway.

I pushed the results to my fork in [branch fix-Fl_Check_Browser--whitespace](https://github.com/Albrecht-S/fltk/tree/fix-Fl_Check_Browser--whitespace). The diffs are
- positions of some comments
- spaces around operators
- one `if(` w/o space -> `if (`
- single line `if (...) statement` split into two lines

Details can be [viewed here](https://github.com/fltk/fltk/commit/499ce97a205191f6994d73d82b956d98c8cd44e7).

I can imagine to combine both patches but to leave out some `clang-format` changes we don't like. Feel free to comment my commit in my fork (if that's allowed) or drop another comment here.

**Comment by Albrecht-S** [comment]
@erco77 Greg, I modified your patch and my additions so I think we can both agree with the whitespace changes. Please review my PR #132 . TIA.

If you agree with the result we can merge PR #132 and this will automatically close this issue.
