### ISSUE TITLE
RFE: After build, a message describing where built libs + executables located

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#124]
Due to how cmake now places builds in different places than the source code dirs, it would be good if after running 'make'
the generated Makefile could tell us the path where constructed libs and executables were saved (fluid, test apps). e.g.

    make -j 4
    [..build messages..]
    --- COMPLETED:
        FLTK libs are located in c:\temp\fltk\build-mingw\lib
        FLTK fltk-config, fluid, and test executables located in c:\temp\fltk\build-mingw\bin

**Comment by Albrecht-S** [comment]
I don't think that it would be a good idea to do this after every build, but I can imagine to add such info to CMake's **configure** pass so you can see it after you execute `cmake`. Note that after changing anything related to the CMake configuration, CMake will execute its configure and generate procedure again before the actual build process when you execute `make` or `ninja` or build the VS project files.

**Comment by Albrecht-S** [comment]
I propose to write something like the following text at the end of the CMake configure phase:
```
-- Configuration Summary --

-- The following OPTIONAL packages have been found:

 * Doxygen
 * LATEX
 * ZLIB

-- FLTK Libraries   will be written to /git/fltk/master/build/cairo/lib
-- Shared libraries will not be built (set OPTION_BUILD_SHARED_LIBS=ON to build)
-- Test programs    will be written to /git/fltk/master/build/cairo/bin/test
-- Example programs will be written to /git/fltk/master/build/cairo/bin/examples

-- End of Configuration Summary --

-- Configuring done
-- Generating done
-- Build files have been written to: /git/fltk/master/build/cairo
```
Notes:
- `autoconf/configure` outputs the summary at the end of the configure phase, and so does CMake (shown above)
- this can be extended to show more configuration options (Xft, pango, ...) like with `autoconf/configure`

**Comment by Albrecht-S** [comment]
OK, I think this is done. Closing now...
