### ISSUE TITLE
android 中文显示乱码

### ISSUE THREAD

**Issue by sunyikeji** [fltk/fltk#126]
new Fl_Check_Button(150,90,160,30,"123汉字按钮456");

![image](https://user-images.githubusercontent.com/65880215/90118050-47ea8a80-dd8a-11ea-8fb0-01764ebecf14.png)

**Comment by Albrecht-S** [comment]
You need to use a proper font or build FLTK with pango to use non-latin scripts, if that's what you wanted to ask.

**Note:** This is the wrong place to ask questions about building or running programs built with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by erco77** [comment]
I wonder if pango is an option on android.. Matt might have to weigh in on this.

For those who might be wondering, the subject of this thread: "android 中文显示乱码"
translates to "android Chinese display garbled".

**Comment by Albrecht-S** [comment]
> I wonder if pango is an option on android.. Matt might have to weigh in on this.

IIRC the current Android port renders fonts using a single-header truetype font renderer [(src/drivers/Android/stb_truetype.h)](https://github.com/nothings/stb/blob/master/stb_truetype.h).

> ... it might be an actual 'issue' if pango isn't an option.

It's still a usage question - you need a proper (truetype) font to render Chinese text.
