### ISSUE TITLE
Documentation bug: leading frontslash and Fl_Menu::add

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#137]
The docs for Fl_Menu mention:

The "/" character is ignored if it appears as the first character of the label string, e.g. "/File/Quit".

This is incorrect. What will happen is the menu hierarchy implicit in the string will be ignored, and a top level menu of the form "/File/Quit" will be added.

The docs should say something more along the line that a leading backslash is contra-indicated when adding to a menu.

The code is "likely" to be correct as the logic applies for other consumers. Please see the 
[Google Groups thread](https://groups.google.com/d/msgid/fltkgeneral/3e970217-4f22-1861-30f9-ddc048ec072f%40seriss.com?utm_medium=email&utm_source=footer) for full details and samples.

**Comment by erco77** [comment]
Fixed in 67347dd, removed the errant line from the docs.

**Comment by fire-eggs** [comment]
Thanks [for some reason I consistently mix up "slash" and "backslash" - sorry for that!]
