### ISSUE TITLE
RFE: [1.4.x] add a method Fl_Text_Display::sbuffer() to access the mStyleBuffer

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#138]
We already have buffer() to access the text buffer, but there's never been a way to access the style buffer.

This is a problem I run into constantly, most recently debugging changes to fluid for the CodeEditor, with no way
to access the style buffer in static callbacks for debugging purposes to compare the text + style buffers.
Suggesting the simple addition of (including doxygen docs):
```
--- a/FL/Fl_Text_Display.H
+++ b/FL/Fl_Text_Display.H
@@ -171,6 +171,13 @@ public:
    \see Fl_Text_Display::buffer(Fl_Text_Buffer& buf)
    */
   Fl_Text_Buffer* buffer() const { return mBuffer; }
+  /**
+   Gets the current style buffer associated with the text widget.
+   Multiple text widgets can be associated with the same style buffer.
+   \return current style buffer
+   \see Fl_Text_Display::highlight_data()
+   */
+  Fl_Text_Buffer* sbuffer() const { return mStyleBuffer; }

   void redisplay_range(int start, int end);
   void scroll(int topLineNum, int horizOffset);
```

**Comment by Albrecht-S** [comment]
+1, but call it style_buffer(). sbuffer() is (IMHO) too terse, nobody can remember what this means.

**Comment by erco77** [comment]
Done; tested, checked doxygen docs, committed, closed.
Added a 'See also' from highlight_data() back to the new method as well.
