### ISSUE TITLE
[Regression] Fl::screen_count() returns an incorrect number of screens

### ISSUE THREAD

**Issue by sandeep-datta** [fltk/fltk#140]
Fl::screen_count() returns an incorrect count on a machine with two monitors in FLTK v1.3.5 but it works correctly when the application (tigervnc's vncviewer) is statically linked with FLTK v1.3.4-2.

Here is some additional information which may help you reproduce this issue on your end...

### Platform
Manjaro Linux v20.1 (Mikah) x64
KDE Plasma v5

### Compiler
gcc (GCC) 10.2.0

### Display adapter
NVIDIA

**Comment by ManoloFLTK** [comment]
The source code behind Fl::screen_count() for the X11 platform did not change since 18 july 2017, that is before 
the releases of FLTK 1.3.4-2 (17 sept 2017) and 1.3.5 (3 march 2019).

Is it possible that you compare runs that differ in terms of X extensions (e.g., Xinerama, Xrandr)?

**Comment by sandeep-datta** [comment]
No, it's the same run. Did not restart my machine or even logout.

**Comment by ManoloFLTK** [comment]
OK. The word "run" was not well chosen. The question is whether the X extensions (e.g., Xinerama, Xrandr)
expected by the 2 versions of the FLTK library you compare are the same. The anwser is in the config.h
files used when these libraries were built.

**Comment by sandeep-datta** [comment]
I see. I think this explains it. The non working version comes from the Manjaro repo while the working version was compiled from source.
