### ISSUE TITLE
Row / Column based layout development

### ISSUE THREAD

**Issue by osen** [fltk/fltk#144]
Hi there,

I notice that Fltk doesn't really focus on using rows and columns to lay out interfaces. And yet this functionality would be very simple to implement as a Fl_Row, Fl_Col classes extending Fl_Group. I have put together an initial prototype (some minor testing on Win32, OpenBSD and with some of the different "themes").

[fltk_rowcol.zip](https://github.com/fltk/fltk/files/5286698/fltk_rowcol.zip)

Normally I would simply stick to the "native" way suggested by the toolkit (in this case FLUID, etc). However one big benefit to the row / column approach is that it seems to be the lowest common denominator of most toolkits (when it comes to a resizing strategy) giving us a good way of porting to and from the different UI systems with minimal change of design.

Let me know what you think. If you like the idea but don't have any time for maintenance or further integration of it, I am happy to invest some time on it since I will be using Fltk for a few internal projects for the next few months at the very least.

**Comment by engelsman** [comment]
I think you would be better re-posting this to the fltk.general google groups forum where more people will see it.
You might need to provide more information about what it is you are trying to do, what you think the programming interface will be, etc.

The github issues makes more sense if you have a pull request to review.

**Comment by osen** [comment]
Ah, OK that is a fair point. I followed a link about features from the FLTK website but can now clearly see there is indeed a forum.

I will move my noise to there then ;)
