### ISSUE TITLE
MacOS 10.15: NSOpenPanel modal issue

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#145]
Hello!
Running this code works on linux and windows, however it fails to return the filename on macos 10.15:
```cpp
#include <stdio.h>
#include <FL/platform.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Native_File_Chooser.H>

int main() {
  fl_open_display();
  auto chooser = new Fl_Native_File_Chooser();
  chooser->show();
  printf("filename: %s\n", chooser->filename());
}
```
It also gives a warning:
```
WARNING: <NSOpenPanel: 0x7fd13541bf80> running implicitly; please run panels using NSSavePanel rather than NSApplication.
```
This issue from xamarin appears similar:
https://github.com/xamarin/xamarin-macios/issues/6474

**Comment by ManoloFLTK** [comment]
I see that too. The problem occurs when there's no other open FLTK window.
It should now be fixed in the git repository (1e73216).
@MoAlyousef : Can you confirm, please?

**Comment by MoAlyousef** [comment]
Hello Manolo
Thanks for your efforts. The panel opens and disappears right away. Some printf debugging shows runModal giving an NSModalResponseStop signal (-1000).

**Comment by ManoloFLTK** [comment]
That's unexpected. Here, under macOS 10.15.7, the small test program you gave above runs well
with the last code from git.

**Comment by MoAlyousef** [comment]
Strange. I'm also running macOS 10.15.7. 
The warning is gone however.

**Comment by ManoloFLTK** [comment]
Since   chooser->show();   runs well here, I'm afraid I don't see what more I could do.

**Comment by MoAlyousef** [comment]
I'm able to keep it alive using this:
```cpp
      while (![_panel URL]) { 
        retval = [_panel runModal];
        if (retval == NSModalResponseCancel) break;
      }
```
However I get a flicker in the beginning

**Comment by ManoloFLTK** [comment]
That is very unexpected because method  runModal of NSSavePanel shows the panel
and runs an event loop until the panel window is closed. The caller is not expected to run a loop!

**Comment by MoAlyousef** [comment]
I agree. All documentation out there suggests that runModal suffices.
It could be a problem in my old and slow macbook air!

**Comment by ManoloFLTK** [comment]
I have now tried to run the small app as an unbundled macOS executable.
In that setup, the panel opens and disappears right away.
Do you also run it unbundled?
If yes, is there a reason for that? MacOS apps are normally bundles.

I also see that if the app opens a window (fl_message("hello");) and closes it
and then opens the file dialog, the unbundled app runs OK.
The problem is thus to open the file dialog in an unbundled app without any other FLTK window opened before.
I'm afraid if I craft something to support that, it will be invalidated soon by a
macOS update, because it's a very unstandard situation.

**Comment by MoAlyousef** [comment]
Hmm that's quite interesting. No it wasn't bundled. I was reproducing an issue in the Rust wrapper.
I'll keep that in mind. 
No need to craft anything non-standard in that case.
Thank you for all your effort.

**Comment by MoAlyousef** [comment]
I'll close this issue now.
