### ISSUE TITLE
Improper handling utf8

### ISSUE THREAD

**Issue by mingodad** [fltk/fltk#154]
Hello !
While trying to compile https://github.com/McNeight/Fl_Scintilla I found that FLTK is not handling utf8 correctly, to see the problem execute `test/editor` and try to paste `//函数名` and we get only bordered rectangles.
Cheers !

**Comment by Albrecht-S** [comment]
Hi @mingodad, thanks for your report, but this is not the case.

There are two options to render such (Chinese?) characters correctly:
1. enable Pango when compiling FLTK (possible in FLTK 1.4, not available in 1.3.x)
2. use a font that supports these characters directly (both FLTK 1.3/1.4)

FTR: I just pasted your entire message into test/editor (FLTK 1.4, built with pango support), and it works fine.

**Comment by Albrecht-S** [comment]
PS: If you have further questions...

This is the wrong place to ask questions about building or running programs built with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
