### ISSUE TITLE
test/cube doesn't resize symmetrically in 1.4.x

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#157]
When the test/cube application is resized to be larger, the left + right open GL windows no longer size symmetrically the way they use to, only the left GL window is getting resized on width, the right one remains the original application size.

Attaching screenshot showing the current resize behavior where right GL window's width stays a fixed width, which seems very wrong:

![cube](https://user-images.githubusercontent.com/6484779/99130586-9c89e580-25c5-11eb-99ce-24df6fd48497.jpg)

**Comment by erco77** [comment]
Attaching a v1 patch suggestion which keeps the cube views the same size, and uses variables to make the widget sizes/positions interdependent, so as to be easily calculated.
[cube-v1.patch.txt](https://github.com/fltk/fltk/files/5539736/cube-v1.patch.txt)

Resulting image on resize:
![cube-with-v1-patch](https://user-images.githubusercontent.com/6484779/99130292-cd1d4f80-25c4-11eb-9761-e91b5eb05709.jpg)

I'm using patches for now, because that whole git forking business makes me nervous and crazy, messes up my ability to wrap up fixes up quickly.

Anyway, hoping the patch is an obvious improvement.
Changed the menu bar a bit too, to be more.. normal?

**Comment by Albrecht-S** [comment]
Attached file [issue-157_cube-v2.patch](https://github.com/fltk/fltk/files/5539985/issue-157_cube-v2.patch.txt) fixes whitespace (tabs -> spaces and alignment) issues. Nothing else changed WRT `issue-157_cube-v1.patch`.

I'm not sure if I like the extra alignment after `begin()` which increases the indent substantially in parts. If we'd keep it, then an additional indent level in lines 192-193 would be appropriate. I don't think that this extra indent would be doable with automated code formatting (try e.g. `clang-format -i test/cube.cxx`) but I "could live with it".

Other than that, tested and works fine. Thanks.

**Comment by erco77** [comment]
Would it be any better if I added {}'s for the begin/end indents?

I also wanted to do another pass to see if I can keep the width of the widget area constant, while still staying centered; might need to add another group to pull that off.

**Comment by Albrecht-S** [comment]
> Would it be any better if I added {}'s for the begin/end indents?

Hmm, personally I don't think so. But it would make automatic code formatting with clang-format (or any other tool) work (with an extra indent level).

**Comment by erco77** [comment]
OK, took your v2 patch as a starting point, added some braces for begin/end, fixed weird bracing in an if/else and weird indent in a switch(), and added an asciiart diagram of the layout to document the macros, creating this [cube-v3.patch.txt](https://github.com/fltk/fltk/files/5540188/cube-v3.patch.txt)  that I hope is suitable.

Yeah, I was logged in as root when I created the v1 patch, so it didn't have my FLTK editor features enabled (folding tabs, 2 space indent, etc).

I did try to keep the widget area width constant, but I think this is one of those situations the fltk resizing can't handle, keeping a middle widget centered while the widgets left and right change size. Perhaps I'm missing something, but I think "centering" widgets during resize has always been a missing ability, without controlling things with a resize() overload.

**Comment by erco77** [comment]
Here's a [cube-v4.patch.txt](https://github.com/fltk/fltk/files/5540353/cube-v4.patch.txt) that maintains the width of the center widgets using custom resize(), which is nice looking. Created an 'application' class, and put all those globals inside of it, making the code arguably cleaner.

I did try using methods instead of macros, but in the end macros seemed more practical. I do wish we had a way to do this with FLTK's own resizing behavior though.. If it can be done, it escapes me.

I did change the Fl_Window -> Fl_Double_Window because it makes a big difference for me in terms of flicker for the widgets. Albrecht, I think you mentioned in a separate conversation earlier today that cube's code changed from Window -> Double then back again.. I don't see this reflected in the git logs, so I don't think I'm undoing a previous fix by doing this.

**Comment by erco77** [comment]
OK, after a [long thread over on fltk.general](https://groups.google.com/g/fltkgeneral/c/JngpHfAMcUI/m/J_gkkB9FBQAJ) where I asked about using FLTK's own resizable() techniques for managing the resize behavior this widget needs, Albrecht came up with a great solution which I've fitted into the attached [cube-v5-patch.txt](https://github.com/fltk/fltk/files/5586492/cube-v5-patch.txt) which sure seems like the direction to go for this demo, as I didn't like switching this demo to using a custom resize() (as shown in the v4 patch).
Will probably go with this once I test it on a few platforms.

**Comment by Albrecht-S** [comment]
@erco77 Thanks for your patch. I tested it and it worked well with one minor issue: the margins were resized together with the boxes. I tried to fix this and adjusted the layout to be more like my own proposal in the above mentioned thread:
- keep both the left cube and the middle button group in one container (lt_grp)
- make the cubes the resizable() widgets in their respective groups
The left resizer is no longer necessary with these mods and the margins keep their widths constant.

I created PR #166 to be able to view the diffs easily ([direct link to my modifications](https://github.com/Albrecht-S/fltk/commit/9e6bb5bd731be4a99e701224fbfa62542d5914a0)).

What do you think?

**Comment by erco77** [comment]
Yep, turned your fork into [alb-pr157.patch.txt](https://github.com/fltk/fltk/files/5591515/alb-pr157.patch.txt) and applied to my code, looks good to me -- simplified and better resizing behavior of the margins.
Since there's a PR now, I guess you'll have to commit it to close it. (I'm staying away from the PR process for now; the resync process is just too confusing for me, and too easy to screw up the main repo)

**Comment by Albrecht-S** [comment]
I just updated (squashed) my branch, edited the commit message, and force-pushed it to my fork.
Last chance to review if you like.

If you want me to "push the button" (merge #166) please let me know. I linked PR #166 to this issue (see top/right: "Linked pull requests), hence merging PR #166 will also close this issue.

**Comment by erco77** [comment]
Sounds good, go ahead -- if it needs any tweaks we can always fine tune with further commits after.

**Comment by Albrecht-S** [comment]
Done. And, FTR, closed automatically.
