### ISSUE TITLE
Xlib w/o XCursor doesn't allow hiding cursor, instead crashes

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#160]
I'd like to open an issue for [STR 3424](https://www.fltk.org/str.php?L3424), because I consider it an error instead of an undocumented side effect.

Without having installed the `libxcursor-dev` package when configuring FLTK an application is no longer able to hide the mouse cursor. Worse, it crashes when trying to set `FL_CURSOR_NONE` as a window's default cursor (you can see this by e.g. adding the line `window->default_cursor(FL_CURSOR_NONE)` to the `hello.cxx `test program **after** `window->show()`). The reason is explained in the STR.

I'm attaching a version of the patch contained in the STR updated for current FLTK 1.4:
[pixmap_cursor.txt](https://github.com/fltk/fltk/files/5572638/pixmap_cursor.txt)

**Comment by ManoloFLTK** [comment]
Thanks for this patch. I propose this slightly modified patch to fix the issue:
[none_cursor.patch.txt](https://github.com/fltk/fltk/files/5575042/none_cursor.patch.txt)

@wcout: please, report if you confirm the issue can be closed.

**Comment by wcout** [comment]
Yes, perfect. Thanks for fixing.
