### ISSUE TITLE
About use ttf file.

### ISSUE THREAD

**Issue by DaMoXin** [fltk/fltk#173]
Can you tell me if there is a function in the fltk library like"QFontDatabase::addApplicationFontFromData(fontFile)" in QT library  that uses a third font or local ttf file. If so, please write an example below. Thank you.

**Comment by Albrecht-S** [comment]
There is (IIRC) currently no function to load a font from a .ttf file in FLTK. That said:

This is the wrong place to ask questions about building or running programs built with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages (if any) in text form (copy and paste preferred). TIA.
