### ISSUE TITLE
Easily break Fl_Tree::insert

### ISSUE THREAD

**Issue by mjm2017** [fltk/fltk#18]
Fl_Tree::insert doesn't check the pos if it is not out of scope ... You can pass any number to the function and for sure it will crashes since it will point to a position that doesn't exist 
Use this code to break the Fl_Tree

/** sample code modified*/
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
/*
int main(int argc, char **argv) {
  Fl_Window *window = new Fl_Window(340,180);
  Fl_Box *box = new Fl_Box(20,40,300,100,"Hello, World!");
  box->box(FL_UP_BOX);
  box->labelfont(FL_BOLD+FL_ITALIC);
  box->labelsize(36);
  box->labeltype(FL_SHADOW_LABEL);
  window->end();
  window->show(argc, argv);
  return Fl::run();
}*/

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tree.H>
int main(int argc, char *argv[]) {
	Fl_Double_Window *win = new Fl_Double_Window(250, 400, "Simple Tree");
	win->begin();
	{
		// Create the tree
		Fl_Tree *tree = new Fl_Tree(10, 10, win->w() - 20, win->h() - 20);
		tree->showroot(0);

		// Add some items
		tree->add("Aaa/000");
		tree->add("Aaa/111");
		tree->add("Aaa/222");
		tree->add("Aaa/333");
		tree->add("Aaa/444");
		tree->add("Aaa/555");

		tree->add("Bbb/000");
		tree->add("Bbb/111");
		tree->add("Bbb/222");
		tree->add("Bbb/333");
		tree->add("Bbb/444");
		tree->add("Bbb/555");

		// Let's use Fl_Tree::insert() to put an item between Aaa/333 and Aaa/444
		{
			Fl_Tree_Item *item_Aaa = tree->find_item("Aaa");        // get the parent /Aaa item
  /*			if (item_Aaa) tree->insert(item_Aaa, "New item",8);   // insert into index #4     Uncomment this to find the bug. You cannot give the function position 8 since it doesn't exist - Mariwan Jalal*/
		}

		// Let's use Fl_Tree::insert_above() to put an item between Bbb/333 and Bbb/444
		{
			Fl_Tree_Item *item_444 = tree->find_item("Bbb/444");    // get item Bbb/444
			if (item_444) tree->insert_above(item_444, "New item");// insert above it
		}
	}
	win->end();
	win->resizable(win);
	win->show(argc, argv);
	return(Fl::run());
}

**Comment by Albrecht-S** [comment]
Thanks for the report. This issue is now fixed in git commit 2c5ba944582a8101cd3fd7445814a2e50b4701bd.

The chosen solution was to be benign and insert the item at the beginning or the end of the child items, respectively. If this is not appropriate in any program users can check the range themselves.

Close #18.
