### ISSUE TITLE
Fl_Screen_Driver.H non-const functions should be const

### ISSUE THREAD

**Issue by markjolesen** [fltk/fltk#181]
functions returning a value should be const like the way they are in Fl_Widget.

For example,

virtual int x() { return 0; }

Should be

viritual int x() const ...

**Comment by Albrecht-S** [comment]
Done. Thanks for the report. See commit f94ed7116c2943c105faebb14798e2ac33bb37cd.

**Comment by bodomartin** [comment]
Hi,

sorry, but this commit 

f94ed7116c2943c105faebb14798e2ac33bb37cd

breaks desktop scaling for me - works for the commit before that. (over ssh remote but that should not matter?)

**Comment by Albrecht-S** [comment]
@bodomartin: Yes, you're right, thanks for the report and sorry for the inconveniencies. See also #239.

I'm working on a fix, to be committed and pushed soon...

**Comment by Albrecht-S** [comment]
OK, this should be fixed now. Hopefully. All feedback would be appreciated.

**Comment by Albrecht-S** [comment]
@markjolesen (OP): Please note that I had to revert the changes to make `x()`, `y()`, `w()`, and `h()` `const`. This didn't work with the internal driver logic (virtual methods) that call platform specific driver methods which can't be `const`. But I made some of the other `Fl_Screen_Driver` methods `const` as requested.

**Comment by Albrecht-S** [comment]
As noted in https://github.com/fltk/fltk/issues/239#issuecomment-864169260 by @bodomartin this issue is fixed and can be closed.
