### ISSUE TITLE
Fl_Gl_Window_Driver unusable thru the public api

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#184]
Hi
Should Fl_Gl_Window_Driver be accessible through the public api?
Fl_Gl_Window has a public method which returns a Fl_Gl_Window_Driver pointer, however the type is incomplete because it's only a forward declaration.

```cpp
#include <FL/Fl_Gl_Window.H>
#include <FL/Fl.H>

int main() {
	Fl_Gl_Window win(400, 300);
	win.end();
	win.show();
	win.gl_driver()->GetProcAddress("glDrawArrays");
	return Fl::run();
}
```
Results in this compilation error:
```
main.cpp:8:17: error: invalid use of incomplete type ‘class Fl_Gl_Window_Driver’
    8 |  win.gl_driver()->GetProcAddress("glDrawArrays");
      |                 ^~
In file included from main.cpp:1:
/usr/local/include/FL/Fl_Gl_Window.H:26:7: note: forward declaration of ‘class Fl_Gl_Window_Driver’
   26 | class Fl_Gl_Window_Driver;
      |       ^~~~~~~~~~~~~~~~~~~
```

**Comment by Albrecht-S** [comment]
> Should Fl_Gl_Window_Driver be accessible through the public api?

No, all the driver stuff should not be public. Thanks for reporting this.

> Fl_Gl_Window has a public method which returns a Fl_Gl_Window_Driver pointer, however the type is incomplete because it's only a forward declaration.

The forward declaration is intentional but the method should be private.
Fixed in 246291fe51734f9be73f457a7c4da00f2413a3dd.
