### ISSUE TITLE
Request for 3d charts and more extensive 2d charts (e.g., radial plots)

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#19]
It is very hard to find anything out there for 3d or more extensive 2d FLTK charts that is not also GPL or Python-ish (e.g., matplotlib). It would be tremendous if FLTK could be improved in this area, especially for use in scientific / engineering applications. I do understand that the "Light" in FLTK may be challenged by such changes, but perhaps a compromise could be implemented. Anyway, I just wanted to say I am learnng FLTK and I really like it, but I am someone who needs good chart support for my applications. I do really appreciate the Fl_Chart class, but could the FLTK development team put some of these improvements into the 1.4.x roadmap?

**Comment by Albrecht-S** [comment]
Thanks for your request, we're always open for contributions like new widgets. If you have suggestions, please feel free to contribute patches or a PR.

It would be useful to discuss new features in our mailing list [fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev) first to see if there is someone that can help. You can also ask in [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral) if anybody can offer such widgets - sometimes other users can help.

**Comment by Albrecht-S** [comment]
I'm sorry to say that this feature request can not be done by our team.
If you're still interested please ask in our mailing lists as suggested above.

Closing this issue now.
