### ISSUE TITLE
Consider removing or renaming VERSION file

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#191]
Hello

Android and Emscripten’s clang toolchain on Windows mistake fltk’s VERSION file for libcxx c++20 “version” header and would try to include it internally (because of Window’s non case-sensitive filesystem. 
I haven’t tried to use clang that is bundled with msvc but it could potentially have the same issue.

**Comment by Albrecht-S** [comment]
Thanks for the report. I can probably rename this file, it's just a build and maintenance support file.

I assume:
- it is found when you build your application (not the FLTK lib itself) and
- it is found only if you build your application directly against the FKTK build directory
- it is **not** found if you build your app _after installing FLTK_ into an arbitrary (not necessarily system default) location and building against this directory.

Can you confirm all or any of these assumptions? Which ones?

Other questions for my better understanding of the issue:
- what build system are you using (CMake, configure/make, ...)?
- if CMake: directly in the source tree (not recommended!) or out of source, i.e. in a separate build directory?

**Comment by lobsterlooks** [comment]
The truth. Continue.

**Comment by MoAlyousef** [comment]
It's when using CMake, in both cases invoking a CMake toolchain file, and having FLTK built with the application/library I'm building. Also just trying to build FLTK as a library before installing it. So options 1, 2 and 3 are true.
Example usage:
```
$ git clone --depth 1 https://github.com/fltk/fltk
$ cd fltk
$ cmake -Bbin -S. -DFLTK_BUILD_TEST=OFF -DCMAKE_TOOLCHAIN_FILE=D:\Android\Sdk\ndk\21.1.6352462\build\cmake\android.toolchain.cmake
```
Would fail.

Also using Android Studio:
- Create a native C++ app, accept defaults.
- Navigate to the Android generated CMakeLists
-  Git clone and git submodule add fltk in the same directory.
- Replace contents of CMakeLists with:
```
cmake_minimum_required(VERSION 3.10)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")
set(FLTK_BUILD_TEST OFF CACHE BOOL " " FORCE)
add_subdirectory(fltk)
add_library(native-lib SHARED native-lib.cpp)
target_include_directories(native-lib PRIVATE fltk ${CMAKE_BINARY_DIR}/fltk)
target_link_libraries(native-lib PRIVATE fltk fltk_images fltk_jpeg fltk_z fltk_png)
target_link_libraries(native-lib PUBLIC log android)
```
- Replace native-lib.cpp code with any FLTK code.
- Run the build (invokes gradle which calls cmake).

**Comment by Albrecht-S** [comment]
Okay, thanks for the quick confirmation and the build details.
I'll rename the offending file.

**Comment by MoAlyousef** [comment]
Thank you. Simply changing the extension works as well.

**Comment by Albrecht-S** [comment]
I did both: rename to another file _name_ and _extension_.

**Comment by MoAlyousef** [comment]
Thank you
