### ISSUE TITLE
1.4.x:focus box drawing incorrectly on OSX (e.g. 10.10.15) at scales >100%

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#192]
When scaling an fltk 1.4.x app on the Mac to values above 100%, the dotted lines for focus boxes break up into distracting patterns.
For example, in the buttons program:
![focusbox-problems](https://user-images.githubusercontent.com/6484779/108448678-0a722880-7217-11eb-8b91-191b91d31106.jpg)

**Comment by Albrecht-S** [comment]
I tried this on my brand new MacBook Air (M1) but I can't confirm this. Looks much better here. From which zoom factors are your three images?

**Comment by erco77** [comment]
Regarding which zoom factors: Using Cloverleaf(+), /every/ step up from normal size gives these artifacts.. It only looks right again when I get to 200%.

I used 'configure --enable-localzlib --enable-localjpeg --enable-localpng & make', building 1.4.x current on 10.10.15.

Ran the same binaries on a few other machines available to me:
    
- Mac mini (Late 2014) running Yosemite (10.10.5) on 27" screen: same artifacts
- MacBook Air (11" Early 2014) running Mojave (10.14.6): same artifacts
- MacBook Air (13" Retina 2019) running Big Sur (11.2.1): same artifacts
- MacBook Pro (15" Early 2011) running Lion (10.7.5): _segfaults_ (*)

(*) The Lion 10.7.5 machine won't run binaries generated by 10.10.15, so I cloned fltk-1.4.x from github and built locally. That ran the binaries, but gave the same focus box artifacts when scaled up.

So I can't actually find a machine that /doesn't/ show those artifacts.

**Comment by erco77** [comment]
Same results using cmake, e.g:

    mkdir build
    cd build
    cmake -D OPTION_USE_SYSTEM_LIBJPEG=Off -D OPTION_USE_SYSTEM_ZLIB=Off -D OPTION_USE_SYSTEM_LIBPNG=Off ..
    make -j 4
    open bin/test/buttons.app

BTW, I don't seem to have a system that can build FLTK unless I turn off the default that tries to use the system image libs. For me it always craps out building the PNG lib (an error about the ZLIB stuff being the wrong version), so I always have been disabling /all/ the system image libs. Perhaps this should be the default on OSX, just so a simple default build works?

**Comment by Albrecht-S** [comment]
Greg, which kinds of displays and resolutions do your systems have? The older ones certainly don't have Retina displays. For my "Built-in Retina Display" I can choose four different resolutions which don't show an exact resolution in display preferences but (original text) "Looks like ..." 1024x640, 1280x800, 1440x900 (Default) and 1680x1050. I tested the last two resolutions and the first screenshot is from 1440x900 (Default) at 170% zoom. It's not absolutely "perfect" and the other zoom factors and screen resolutions look similar but not identical (minor differences in dot sizes.
<img width="297" alt="buttons_zoom_170" src="https://user-images.githubusercontent.com/26235500/108609787-b27f2180-73d0-11eb-96dd-f0da300a8017.png">
I can see similar effects at zoom 80% though (at 1680x1050 resolution):
![buttons_zoom_80](https://user-images.githubusercontent.com/26235500/108609980-3d145080-73d2-11eb-9f48-c531ae5a493f.png)
Note: the 2nd image was zoomed in Gimp, hence it appears larger than the 170% image.

Looks like something for @ManoloFLTK.

test/fullscreen shows the resolutions as given in preferences by "Looks like ...".

**Comment by Albrecht-S** [comment]
Regarding the built-in image libs: I think Manolo changed the default in CMake builds for png and jpeg to built-in on macOS (e.g. OPTION_USE_SYSTEM_LIBJPEG "use system libjpeg" OFF) but left zlib ON (i.e. system) which I found this way on my macOS CMake build. It seemed to work but I switched zlib to OFF manually as well for consistency. I can't tell what the defaults for configure/make are.

> Perhaps this should be the default on OSX, just so a simple default build works?

I think this depends on our bundled library versions and the existing header files on the system. It's a well-known problem that not all combinations work well - and under Linux we have another issue that (IIRC) is required and linked to the system Xft shared lib which makes it impossible to use our bundled libpng, or something like that...

One of my next points on my to-do-list is to update the bundled libs but I can't tell if this makes a difference (very likely it will).

For users it would probably be the best to switch either **all** bundled libs ON or **all** libs OFF for consistency and likely the best results.

**Comment by erco77** [comment]
> Which kinds of displays and resolutions do your systems have?

The macbooks are all set to the "default resolution" for the built in displays; I've appended resolution info below to each machine.
I also added a 5th mac:

- Mac mini (Late 2014) running Yosemite (10.10.5) on 27" LG screen: same artifacts -- 3840 x 2160
- Mac mini (Late 2014) running High Sierra (10.13.6) on a Cintiq 22HD: same artifacts -- 1920 x 1080
- MacBook Air (11" Early 2014) running Mojave (10.14.6): same artifacts -- 1366 x 768
- MacBook Air (13" Retina 2019) running Big Sur (11.2.1): same artifacts -- 2560 x 1600 Retina
- MacBook Pro (15" Early 2011) running Lion (10.7.5): segfaults (*)/same artifacts w/local build -- 1440 x 900

**Comment by ManoloFLTK** [comment]
@Greg: I can't reproduce here what you show and have a hard time understanding how a continuous
line can arise from this code:
  line_style(FL_DOT);
  rect(x, y, w, h);
  line_style(FL_SOLID);

I get dotted lines scaled to a fractional factor in which some dots or some intervals are twice longer
than others. As Albrecht reports, scaling factors < 1 produce somewhat irregular patterns.
I'll try to make these dots more even as I did for GDI+ recently.

I confirm the default building option is the same with configure and CMake and uses bundled JPEG and PNG
libs and the system's zlib. But this shouldn't be related to focus box drawing.

I recommend to use the Pixie app to explore in detail such drawing patterns.

**Comment by Albrecht-S** [comment]
@erco77 Greg, I noticed that Manolo committed a fix for this issue (842cbf0, see above). Can you please test if this fixes it for you?

**Comment by erco77** [comment]
@Manolo, thanks, your recent commit seems to have solved the artifacts.

When I scale to sizes larger than 100%, it draws with a dotted line that is still one pixel thin (doesn't get thicker, and dotted pattern doesn't get larger), but perhaps that's intentional and OK. Certainly looks much better now.

Here's a [screen capture video](http://seriss.com/people/erco/tmp/focusbox-manolo-fix.webm) showing the 'buttons' app during scaling.

I couldn't find "Pixie" for Xcode 7, but Apple's built in interactive screen zoom with picture-in-picture using ⌘⌥(8) seemed to work just fine (with smoothing turned off), as shown in the second half of this video.

**Comment by ManoloFLTK** [comment]
The dotted line becomes 2-pixel wide at 200% and 3-pixel wide at 300%.

Please, close the issue if you consider it's solved.

**Comment by erco77** [comment]
Great, thanks so much -- closing!
