### ISSUE TITLE
Extending selected text with keyboard in Fl_Text_Editor

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#196]
When you select text in the buffer and then try to extend it with the shift and keyboard it selects the wrong text range.

Example:
run "editor editor.cxx"
press ctrl + f and enter "https"
then press shift + right and it selects all text from pos 0 until "https:"

It might have something to do with Fl_Text_Display::dragPos which is not set when you select text with the Fl_Text_Buffer::select().
Anyway I have no idea how to fix it.

**Comment by MatthiasWM** [comment]
I can replicate that. I will fix that hopefully this week.

**Comment by Albrecht-S** [comment]
Maybe this is related to #412?

**Comment by MatthiasWM** [comment]
Selecting text after the "find" action does not seem to set the cursor position correctly. I am traveling RN, but I will look at that tonight.

**Comment by MatthiasWM** [comment]
Ok, so this is more complicated than I thought. Programmatically selecting text (Editor->Find, for example), does not set dragPos, which is the base for changing the selection with shifted arrow keys. Not sure how to solve this as dragPos/mCursorPos shadow the buffer()->selection(), which should probably not be part of the buffer anyway.

This will get complicated!

**Comment by MatthiasWM** [comment]
Some more details. We have two places where we store the text selection. The first selection is associated with the text buffer, and the second one is associated with the text display. The buffer selection is the visible one, but the display selection is used for shifted movements and for drag'n'drop. 

If the buffer selection is created by mouse or cursor movements, both selections coincide. But if the buffer selection isdone programatically (e.g. by using "test/Editor->Find"), the display and buffer selections diverge. We *show* the buffer selection, but we *use* the display selection.

This gets even more complex when we have multiple displays using the same buffer... .

Spontaneously, I would remove the buffer selection altogether, but that interferes with existing software. Making buffer selection change all associated displays is feasible, but the buffer does not know which displays are connected, and keeping back pointers is dangerous if a display is deleted without unlinking the buffer.

So, um, I am open for suggestions.

**Comment by erco77** [comment]
Heh, you sure seem attracted to the tough problems; fluid menus, and now the text editor X^D
All that you need to complete your migraine is to start probing around in the HTML viewer code.

I'm not looking at the code, but from what I remember, I'm going to guess that if a text buffer is shared by both an editor and a display, the idea would be any edits in the Fl_Text_Editor would be displayed by the associated Fl_Text_Display too.

Given that, a (perhaps naive) design expectation would be all text selection would ONLY be in the text buffer that is simply shared/inherited by the Editor and Display classes. Any change in the buffer's text selection would simply be reflected in both display and editor.

But perhaps there's messy reasons why the concept is reflected in display, though I can't think why e.g. keyboard navigation of selection couldn't just manipulate the buffer, and we do away with whatever's duplicated in display.
All I can think of is having display have its own selection allows keyboard nav of selection not affecting any editor selections, though not sure why that should be important.

**Comment by MatthiasWM** [comment]
OK, so I think I fixed this in #550. I keep the previous behaviour intact, but I am now catching some unexpected cases, fixing coordinates as the user would expect them to be. This is a compromise between keeping the API while still catching edge cases.

Hah, Greg, I don't think I will touch the HTML code. That's just *too much*. The rest is fun though. Some of the code is my own crime anyway. When I added UTF-8 support to the text editor many years ago, it took me days to figure out, how it worked. I am glad that I still remember a lot of that.

**Comment by MatthiasWM** [comment]
Thanks for the suggestions, Greg. Hoping that the patch will fix this.

**Comment by Albrecht-S** [comment]
OK, the issue is closed, thanks to @MatthiasWM, but anyway:

@erco77 @MatthiasWM FWIW: you can open a new view in `test/editor` (Menu: `File`/`New View` or `Alt+V`) for testing. This is like a typical "split editor windows" function in other text editors. You can even scroll one view to the end of the file, select text, and drag it to another view at another place in the file. The (one) selection is always reflected in all views and - as expected - deleting or modifying text in one view is reflected in all views (it's only one `Fl_Text_Buffer`).
