### ISSUE TITLE
Read Access Violation in FL_Browser in x64 (Windows)

### ISSUE THREAD

**Issue by chipnetics** [fltk/fltk#197]
Long time FLTK user; who has always used 32-bit library with no issues.  I successfully compiled ftlk.lib version 1.3.5 with x64 flags in Visual Studio 2017 and have been using the library in my 64-bit software (a GUI that collects API data). However after hours of program execution (1 to 10 hours), inevitably, Fl_Browser::item_height (Fl_Browser.cxx line 409) will eventually throw an exception for a Read Access Violation (a system level exception, not a C++ exception). It appears to be a piece of code that checks if the FL_Browser items has an icon and if so, adjusts the height max to accommodate icon height .  I don't use any icons in my software in FL_Browser.

I checked some previous versions of FLTK and this function has been unchanged for a long time, so I'm pretty sure this is a 64 bit compilation issue - and probably not specifically related to the icon existing or not.  I'm not all too sure where to begin looking; I've left all the preprocessor definitions as WIN32 as it mentions on the FLTK homepage they are valid for both 32 and 64-bit builds. Also I've set flag /MACHINE:X64. 

As this is a system level exception I can't really put a try/catch in the FLTK source code in this area, so looking to find a root cause - my suspicion is a build issue.  Any advice/help is greatly appreciated! Thanks.

**Comment by erco77** [comment]
On 3/3/21 7:36 AM, Jeffrey Paranich wrote:
>
> Long time FLTK user; who has always used 32-bit library with no issues. I successfully compiled ftlk.lib version 1.3.5 with x64 flags in Visual 
> Studio 2017 and have been using the library in my 64-bit software (a GUI that collects API data). However after hours of program execution (1 to 10 
> hours), inevitably, Fl_Browser::item_height (Fl_Browser.cxx line 409) will eventually throw an exception for a Read Access Violation (a system level 
> exception, not a C++ exception).
>
> I checked some previous versions of FLTK and this function has been unchanged for a long time, so I'm pretty sure this is a 64 bit compilation 
> issue. I'm not all too sure where to begin looking; I've left all the preprocessor definitions as WIN32 as it mentions on the FLTK homepage they are 
> valid for both 32 and 64-bit builds. Also I've set flag /MACHINE:X64.
>
> As this is a system level exception I can't really put a try/catch in the FLTK source code in this area, so looking to find a root cause - my 
> suspicion is a build issue. Any advice/help is greatly appreciated! Thanks.
>

     Usually when I encounter issues like this, it's usually because either #include files were
     pulled in from a different version of FLTK than linked (or dynamically loaded), or not all
     parts of the application were rebuilt (old OBJ files).

     It might not be related at all to 32bit vs. 64bit, but just two different 64bit builds
     that are incompatible with each other, for whatever reason (such as changing the ABI
     flags but not rebuilding all of FLTK)

     First make sure your #include's for FLTK are coming from the same directory as the
     FLTK libs you're linking against (dynamic or static), and do a 'make clean; make' on
     both FLTK and your own project.

     Often when one gets problems like this, and adding printf() statements to the code
     magically "fixes" it, it's because the act of adding a print statement touches the source
     code file and causes it to be rebuilt, and /that's/ what fixes the problem.

**Comment by Albrecht-S** [comment]
I can only second everything @erco77 said and may add that another reason of such sporadic issues can be *any* stale pointer, double free, access after free (delete) or something like that, be it in FLTK or in user code. If the OP was on Linux (but he's on Windows) I'd suggest using valgrind which can reveal issues that never do any harm - only after a runtime of 10 hours or so (by accident).

@chipnetics If you have any memory checker available I strongly recommend to use such tools to find any issues. If you find something in FLTK, please report; if you find something in your user code, please report as well and close this issue. If it's an option for you: I suggest to build your program on Linux and run it with `valgrind` to see if `valgrind` reports any issues. That's pretty easy **if** you can run your program on Linux.

@erco77 wrote:
> Often when one gets problems like this, and adding printf() statements to the code magically "fixes" it, it's because the act of adding a print statement touches the source code file and causes it to be rebuilt, and /that's/ what fixes the problem.

Another reason why adding a `printf()` statement can change things: the memory layout of your app changes slightly and dereferencing a stale pointer suddenly doesn't do any harm. Also, newer systems have options to randomize load addresses which can make compiling an entirely unrelated module and **linking the program** change its behavior WRT dangling or stale pointers.

**Comment by chipnetics** [comment]
Thanks guys, I just recompiled everything from scratch and will see if the issue clears up; and report back.

It did dawn on me however; would it not be proper for the offending piece:

 if (l->icon && (l->icon->h()+2)>hmax) 

to be re-written as

 if (l->icon->h()+2)>hmax && l->icon ) ?

I seem to recall most compilers will generate assembly from right to left, so technically it tries to check the icon height before testing if an icon exists.  I noticed in other parts of FL_Browser, icon is always checked first before trying to access its elements.... just a thought.

**Comment by Albrecht-S** [comment]
> Update: Okay looks like can disregard - ...

Yep, that code as written is standard. The C and hence also C++ standards guarantee that such expressions are evaluated left to right **and** that the evaluation is terminated if a condition of an `&&` expression is false.

**Comment by chipnetics** [comment]
Okay after running for ~18 hours with no crash, I believe the complete recompile has fixed the issue.  I blew out all the .PDB files, and extra stuff Visual Studio litters all over the place as well, before compiling.  

I think another key element was I re-compiled with the flag /LARGEADDRESSAWARE:NO (previously was YES, which I read some articles that this is bound to cause sporadic issues in both 32 and 64-bit compilations, and really is a band-aid fix for 32 bit use cases only, and of course superfluous when you've already set /MACHINE:X64).  I think this issue can be closed.  Thanks for all the help!

**Comment by Albrecht-S** [comment]
Thanks for confirmation and closing the issue. Glad we could help.
