### ISSUE TITLE
build static and shared libs, properly named, side-by-side

### ISSUE THREAD

**Issue by dvzrv** [fltk/fltk#20]
I'm currently building 1.3.5 for Arch Linux and usually we require the shared libraries to be build (and not so much the static ones).
I've now achieved both by extensively renaming things within a bunch of the `CMakeLists.txt`s, achieving an outcome with both static libs and shared libs installed with proper names (i.e. without the `_SHARED` postfix). Some of the macros were a little too eager to rename things ;-)

Would you be interested in a pull request for that?

**Comment by Albrecht-S** [comment]
Yes, please.

**Comment by Albrecht-S** [comment]
This issue has been fixed, see PR #21 (b8318480f515c9ca0e7257ca7ca4c73c56a4a080).
