### ISSUE TITLE
How to plot sine wave and other function in single graph using FLTK

### ISSUE THREAD

**Issue by hiteshkhanna31** [fltk/fltk#202]
I am trying to plot sine wave and other functions in one graph using FLTK library but i did not find any sample code in the examples which can help me get started.

Appreciate any help on this issue.

**Comment by erco77** [comment]
See examples/howto-draw-an-x.cxx in fltk 1.4.x as a simple example of how to draw lines.

In the future please use the [fltk.general google group](https://groups.google.com/u/1/g/fltkgeneral) for all questions, so everyone can benefit from the question/answers. The github issues page is only for reporting bugs.
