### ISSUE TITLE
Gtk-CRITICAL messages from native file chooser

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#209]
**O/S:** Linux Mint 20 MATE
**FLTK:** github 1.4.x snapshot dated 20210326

Relevant source: Fl_Native_File_Chooser_GTK.cxx

I'm using the unmodified, out-of-the-box native-filechooser test program. I can get these two errors the first time the native file chooser is shown (whether "pick a dir" or "pick a file"):

```
(native-filechooser:1866294): Gtk-CRITICAL **: 13:50:08.037: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(native-filechooser:1866294): Gtk-CRITICAL **: 13:50:08.037: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
```

**How to reproduce:**

1. Run native-filechooser program.
2. Invoke "pick a dir" or "pick a file".
3. Notice in the file chooser that Preview is NOT checked.
4. Check the "Preview" box.
5. Close the file chooser.
6. Close the program.
7. Run native-filechooser program.
8. Invoke "pick a dir" or "pick a file".

At this point, as long as "Preview" is _checked_, the Gtk-CRITICAL messages will appear the first time the native file chooser is invoked. _Un-checking_ "Preview" and re-running the program, the messages do not appear.

**Comment by Albrecht-S** [comment]
Thanks for the report, I can confirm the behavior as described. However I don't see any misbehavior although the message says "Gtk-CRITICAL ...". Did you notice any wrong behavior?

That said, I have no idea where to look for further insights (except debugging step by step).

Maybe @ManoloFLTK can help?

**Comment by fire-eggs** [comment]
I didn't see any incorrect behavior. 

Great, you got me rubber ducking and actually figured out the problem!

The problem is touching the state of the state of the `plus_button` and `minus_button` controls in
`update_preview_cb` too early. I.e. they don't exist when first touched.

I've confirmed this by trying Solution 1 below.

The crux of the problem is the two controls haven't been created at the time this 'set sensitive' function is called.

In `Fl_GTK_Native_File_Chooser_Driver::fl_gtk_chooser_wrapper()`, in the 
`if (Fl_Image::register_images_done) {` block, the "preview" widget is created first, followed by the `plus_button` and `minus_button` widgets.

This line:
```
    fl_gtk_toggle_button_set_active((GtkToggleButton *)preview_button, want_preview);
```
initializes `preview_button` to ON in this scenario. As the `preview_cb` has been hooked in the previous line, `update_preview_cb` is called and attempts to touch the not-yet-created controls!

Solution 1: [verified to work]
Swap the lines which initialize the preview toggle and hook up the callback.

Solution 2:
Move the six lines which create the plus/minus buttons before the creation of the preview_button

**Comment by fire-eggs** [comment]
Here's the relevant code:
[Sorry I screwed up my nl command, the blank lines didn't get numbered correctly].
```
   655	    GtkWidget *preview_button = fl_gtk_check_button_new_with_label(Fl_File_Chooser::preview_label);
   656	    fl_g_signal_connect_data(preview_button, "toggled", G_CALLBACK(preview_cb),    gtkw_ptr, NULL, (GConnectFlags) 0);
   657	    fl_gtk_toggle_button_set_active((GtkToggleButton *)preview_button, want_preview);
   658	    fl_gtk_table_attach_defaults(table, preview_button, 0, 1, 0, 1);
       
   659	    plus_button = fl_gtk_button_new_with_label("<--->");
   660	    fl_g_signal_connect_data(plus_button, "clicked", G_CALLBACK(plus_cb), preview, NULL, (GConnectFlags) 0);
   661	    fl_gtk_table_attach_defaults(table, plus_button, 1,2, 0, 1);
   662	    minus_button = fl_gtk_button_new_with_label(">---<");
   663	    fl_g_signal_connect_data(minus_button, "clicked", G_CALLBACK(minus_cb), preview, NULL, (GConnectFlags) 0);
   664	    fl_gtk_table_attach_defaults(table, minus_button, 2,3, 0, 1);
```

Solution 1: Swap lines 656 and 657
Solution 2: Move lines 659-664 to before line 655

**Comment by Albrecht-S** [comment]
Thanks for testing and the suggested solutions.

FTR: This code has meanwhile been moved to another file; it's now in `src/Fl_Native_File_Chooser_GTK.cxx` in lines 741-744 and 746-751, respectively.

Adjusted line numbers (not tested, not verified):
Solution 1: Swap lines 742 and 743
Solution 2: Move lines 746-751 to before line 741

**Comment by Albrecht-S** [comment]
I decided to use solution 1. Solution 2 would also suppress the warning but solution 1 was less code changes.
Thanks again. Issue closed.
