### ISSUE TITLE
Fl::event_x() & event_y() doesn't take into account embedded window's coords with Mouse wheel events

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#210]
Hello

Sorry for the weakly descriptive title.
Given the following program:
```cpp
#include <FL/Enumerations.H>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
// #include <FL/Fl_Group.H>

struct Embed : public Fl_Window {
  Embed(int x, int y, int w, int h, const char *title = 0)
      : Fl_Window(x, y, w, h, title) {}

  int handle(int e) {
    switch (e) {
    case FL_PUSH:
      printf("%d, %d\n", Fl::event_x(), Fl::event_y());
      fflush(stdout);
      break;
    case FL_MOUSEWHEEL:
      printf("%d, %d\n", Fl::event_x(), Fl::event_y());
      fflush(stdout);
      break;
    }
    return Fl_Window::handle(e);
  }
};

int main() {
  Fl_Window win(100, 100, 400, 300);
  Embed embed(0, 0, 400, 300);
  win.end();
  win.show();
  win.redraw();
  return Fl::run();
}
```
For an embedded (child) window, the values retrieved from Fl::event_x() and Fl::event_y() differ depending on the event. If we change Embed to derive from Fl_Group, then the values are correct. Also the values of Fl::event_x_root() and Fl::event_y_root() are correct in all cases.

Edit: forgot to mention that this is Windows specific, linux works fine.

**Comment by Albrecht-S** [comment]
OK, I'm working on this issue. I can confirm that it is a bug and I've found a "quick fix" which needs some more testing and verification so it doesn't break anything else.

Issue #87 (`FL_LEAVE` events) appears to be related, i.e. likely the "same" internal issue - I'm still testing...

**Comment by Albrecht-S** [comment]
BTW, thanks to @MoAlyousef for the good test program. It's very helpful and I've extended a little bit it to suit my needs.

**Comment by Albrecht-S** [comment]
FTR: please don't hold your breath, give me one or two more days to report progress. It looks like this issue needs some more testing. There are some tricky special cases...

**Comment by Albrecht-S** [comment]
This issue should be fixed now with commit e3e8fe494d71a0ab1869fd4fcd275366373b464d.

Tests, feedback of all kinds welcome. TIA.

**Comment by Albrecht-S** [comment]
FTR and for clarification: I'm posting the extended test/demo program I used for testing `FL_MOUSEWHEEL` events on all three major platforms: [issue-210.cxx](https://github.com/fltk/fltk/files/6755024/issue-210.cxx.txt). Screenshot:
![issue-210](https://user-images.githubusercontent.com/26235500/124286443-3f8c7100-db4f-11eb-9db3-046d04f51367.png)
In this screenshot the mouse is positioned at (50, 50), centered inside the red square.

A typical sequence of events looks like this:
```
( 1) App::   (  50,   50) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
( 2) App::   (  50,   50) FL_MOUSEWHEEL issue-210(  44,   44), topwin(  44,   44)
( 3) Embed:: ( -50,  -50) FL_MOUSEWHEEL subwindow( 100,  100), topwin(  44,   44)
( 4) App::   (  50,   50) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
( 5) App::   ( 150,  150) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
( 6) Embed:: (  50,   50) FL_PUSH       subwindow( 100,  100), topwin(  44,   44)
( 7) App::   ( 150,  150) FL_MOUSEWHEEL issue-210(  44,   44), topwin(  44,   44)
( 8) Embed:: (  50,   50) FL_MOUSEWHEEL subwindow( 100,  100), topwin(  44,   44)
( 9) App::   ( 150,  150) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
(10) Embed:: (  50,   50) FL_PUSH       subwindow( 100,  100), topwin(  44,   44)
(11) App::   ( 104,  104) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
(12) Embed:: (   4,    4) FL_PUSH       subwindow( 100,  100), topwin(  44,   44)
(13) App::   ( 104,  104) FL_MOUSEWHEEL issue-210(  44,   44), topwin(  44,   44)
(14) Embed:: (   4,    4) FL_MOUSEWHEEL subwindow( 100,  100), topwin(  44,   44)
(15) App::   ( 104,  104) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
(16) Embed:: (   4,    4) FL_PUSH       subwindow( 100,  100), topwin(  44,   44)
(17) App::   (  90,   90) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
(18) App::   (  90,   90) FL_MOUSEWHEEL issue-210(  44,   44), topwin(  44,   44)
(19) Embed:: ( -10,  -10) FL_MOUSEWHEEL subwindow( 100,  100), topwin(  44,   44)
(20) App::   (  90,   90) FL_PUSH       issue-210(  44,   44), topwin(  44,   44)
(21) App::   ( 320,  320) FL_MOUSEWHEEL issue-210(  44,   44), topwin(  44,   44)
(22) Embed:: ( 220,  220) FL_MOUSEWHEEL subwindow( 100,  100), topwin(  44,   44)
```
Relevant events are logged by both the main window (App::) and the subwindow (Embed::). The leading numbers `(nn)` were added for comments only:

1. `FL_PUSH` inside the red square (50,50)
2. `FL_MOUSEWHEEL` at the same position, logged by the main window
3. `FL_MOUSEWHEEL` at the same position, logged by the subwindow
4. `FL_PUSH` at the red square (50,50) again

(5-16) similar actions

(17-20) `FL_PUSH` + `FL_MOUSEWHEEL` left of and above the subwindow.

(3, 19, 21, 22) Note that `FL_MOUSEWHEEL` coordinates outside the subwindow may be negative or greater than the subwindow size (200 x 200).

**Comment by Albrecht-S** [comment]
I tested with this demo program on all major supported platforms (Windows, Linux, macOS). On Windows I used VS 2019 and MinGW-w64 (MSYS2). All test results looked as expected.

**Comment by MoAlyousef** [comment]
Thanks I’ll try again in a few hours.

**Comment by MoAlyousef** [comment]
Thanks @Albrecht-S . I can confirm it works. I'll close this issue now.

**Comment by Albrecht-S** [comment]
Reopening, see bug report _"Mouse wheel event coordinates for unselected windows are off ..."_ (fltk-rs/fltk-rs#760) and particularly this [comment](https://github.com/fltk-rs/fltk-rs/issues/760#issuecomment-873410667).

This report is specific to macOS (AFAICT).

I'm not sure if we can fix this though (in case we don't get the mouse/pointer coordinates on macOS).

**Comment by eadf** [comment]
I know next to nothing about objective c, but from what I can tell from the documentation you can setup an tracking rectangle over the entire window and listen for [mouseExited](https://developer.apple.com/documentation/appkit/nsresponder/1527561-mouseexited) and [mouseEntered](https://developer.apple.com/documentation/appkit/nsresponder/1529306-mouseentered) in cocoaMouseHandler.

**Comment by Albrecht-S** [comment]
Thanks for the hint and the links, I'll check this.

**Comment by Albrecht-S** [comment]
FTR: there's some work going on to send FL_ENTER/FL_MOVE/FL_LEAVE events when the mouse is moved over "inactive" windows. The proposed patch in issue #411 appears to use the proposed `NSTrackingArea` and `NSMouseEntered` / `NSMouseExited`.

I'm referencing issue #411 here to make sure that **this issue** (210) will be checked when/if the solution is implemented and this issue (210) can hopefully be resolved and closed as well.

**Comment by Albrecht-S** [comment]
My tests with the demo program [issue-210.cxx](https://github.com/fltk/fltk/files/6755024/issue-210.cxx.txt) indicate that this issue is now (since commit aa955812f988a4c0ffa3a43e9a5ba7a20a0e1f92) fixed for macOS as well.

@MoAlyousef @eadf Can you please test and confirm that the issue is fixed now?

**Comment by MoAlyousef** [comment]
Thanks again. I’ll close the issue here.
