### ISSUE TITLE
cmake build installs files include/FL/Makefile.in and include/FL/README.Xcode

### ISSUE THREAD

**Issue by yurivict** [fltk/fltk#212]
These files don't look like they belong there.

Version 1.3.5

**Comment by Albrecht-S** [comment]
Thanks for the report, I'll check this. ISTR that the entire FL/ folder gets installed which was probably correct in earlier versions. The additional files you mention should not be installed.

Please note also that FLTK 1.3.5 is pretty old now and FLTK 1.4 is the current development. FLTK 1.3.6 will be released soon but I'm not sure if a fix for this issue will make it into 1.3.6.

**Comment by Albrecht-S** [comment]
Fixed in `master` (1.4) and `branch-1.3` (1.3.6).
