### ISSUE TITLE
Could you please drop the suffix "_SHARED" from shared library names?

### ISSUE THREAD

**Issue by yurivict** [fltk/fltk#214]
For example, you install:
```
lib/libfltk.a
lib/libfltk_SHARED.so
lib/libfltk_SHARED.so.1.3
lib/libfltk_SHARED.so.1.3.5
lib/libfltk_forms.a
lib/libfltk_forms_SHARED.so
lib/libfltk_forms_SHARED.so.1.3
lib/libfltk_forms_SHARED.so.1.3.5
lib/libfltk_gl.a
lib/libfltk_gl_SHARED.so
lib/libfltk_gl_SHARED.so.1.3
lib/libfltk_gl_SHARED.so.1.3.5
lib/libfltk_images.a
lib/libfltk_images_SHARED.so
lib/libfltk_images_SHARED.so.1.3
lib/libfltk_images_SHARED.so.1.3.5
```

Many projects build and install both static and shared libraries with the same name without a problem. This is a convention to share names in shared and static libs. For example:
```
libboost_stacktrace_basic.a
libboost_stacktrace_basic.so
libboost_stacktrace_basic.so.1
libboost_stacktrace_basic.so.1.72
```
```
libgthread-2.0.a
libgthread-2.0.so
libgthread-2.0.so.0
libgthread-2.0.so.0.6600.7
```

**Comment by Albrecht-S** [comment]
This is already done in current development (git `master`) and in `branch-1.3` which will be released very soon as FLTK version 1.3.6.

You can pull the latest Git (branch-1.3) to test this. If you don't have or use git you can always pull a zip file from GitHub. If you set the CMake cache variable `OPTION_BUILD_SHARED_LIBS` you'll get both lib types side by side as shown in your report.
