### ISSUE TITLE
[Documentation] 'char text[256]' missing from the text editor example and incomplete documentation in general?

### ISSUE THREAD

**Issue by Godnyx** [fltk/fltk#219]
In the [chapter 6](https://www.fltk.org/doc-1.3/fltk.pdf#chapter.6) of the official documentation, the variable that is called `title` that is a char array seems to be missing. I found out about that when I reached to [6.8.4](https://www.fltk.org/doc-1.3/fltk.pdf#subsection.6.8.4) when it implements the `set_title()` function and I realized that the `title` variable doesn't exist. With some research I was able to find the same example [here](https://www.fltk.org/doc-2.0/html/editor.html) but now this variable is presented. Unless I'm missing something, I hope I helped!

**EDIT:** Now that I'm finishing the example, I now see that I have a couple of errors for function that have not being implemented like `undo_cb` `paste_cb` etc. and I also have an error in the `changed_cb` function in the line when we use `set_title(w)` and the error massage is: `'Fl_Window` is an inaccessible base of 'EditorWindow'` and I have no idea what does that mean.

**Comment by Albrecht-S** [comment]
Thank you for reporting your findings. And yes, [this is a known issue](https://github.com/fltk/fltk/issues/189), the test/editor.cxx demo code has evolved since the docs with this example were written, but the docs have not been changed.

I committed a fix anyway, but if you find more issues related to this example (test/editor) please add comments to issue #189. Thanks.

All comments are welcome.

**Comment by Albrecht-S** [comment]
> Now that I'm finishing the example, I now see that I have a couple of errors for function that have not being implemented like undo_cb paste_cb etc. and I also have an error in the changed_cb function in the line when we use set_title(w) and the error massage is: 'Fl_Window is an inaccessible base of 'EditorWindow'` and I have no idea what does that mean.

I see that you closed the issue meanwhile, but anyway, to answer your question (not really).

I don't have the code in question before me and can't answer this directly. I'd like to refer you to the source code test/editor.cxx in the FLTK source distribution. If you have questions like these, please ask in our "forum" [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral).
