### ISSUE TITLE
Table will flash when I click.

### ISSUE THREAD

**Issue by blackbeaf** [fltk/fltk#220]
Environment: Windows 10 x64 ,  VS2019 , 
code:  fltk\test\table.cxx

Some items of the table will "flash" when I click. How to fix this?

![fltk](https://user-images.githubusercontent.com/25684578/114827682-98275a00-9dfb-11eb-8608-7fe1f37fa5fd.gif)

**Comment by Albrecht-S** [comment]
I don't know why `test/table.cxx` uses an `Fl_Window`, but if you replace `Fl_Window` with `Fl_Double_Window` the flashing should be gone. That said, ...

This is the wrong place to ask questions about building or running programs with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by blackbeaf** [comment]
Thanks for your reply! I got it.

**Comment by erco77** [comment]
Albrecht, FWIW I /think/ if we create a CONTRIBUTING.md file, the github issue page will show a small indicator/link to the file if you're visiting the issues page for the first few times. Some info here: https://github.blog/2012-09-17-contributing-guidelines/

**Comment by Albrecht-S** [comment]
Yes. I know. It's on my todo list, but I didn't yet find the time to even get started, reading docs, testing it (maybe in one of my own repos, etc.). If you like to do it, feel free. ;-)
Otherwise I may have more time after 1.3.6 is out...
