### ISSUE TITLE
Feature request: support arcan display server?

### ISSUE THREAD

**Issue by jackghg** [fltk/fltk#225]
I hope that fltk will focus on arcan rather than wayland in the future.

**Comment by Albrecht-S** [comment]
Why? Please elaborate.

**Comment by jackghg** [comment]
because wayland is garbage and arcan look like the new-gen X that linux need.

**Comment by Albrecht-S** [comment]
Points taken, although that's not what I meant with "elaborate". Saying that wayland is "garbage" is not an argument.

Since we're not planning to support wayland or any other display server in the near future I'm closing this now.

**Comment by jackghg** [comment]
I'm also going to use X for some more years but im worried for the future... ok thanks for reading

**Comment by erco77** [comment]
I think FLTK devs are likely going to wait until an obvious winner of the battle against X becomes firmly established. Many attempts have been made to replace X only to flounder and fail. I'm glad we didn't waste developer time on those.
When something both establishes and has a stable API, at that point we'd likely start on a dedicated backend driver for the new tech making it an option, leaving X support be the default until it's painfully obvious the new driver is stable and error free.

**Comment by jackghg** [comment]
Yeah, right.

**Comment by jackghg** [comment]
...perhaps make the display server a plugin ? like qt does. so the display server becomes modular...

**Comment by Albrecht-S** [comment]
FTR: there are currently efforts going on to implement Wayland support in FLTK. There's no official (releaseable) support available yet.

Anyway, closing this issue now as announced before.

**Comment by Albrecht-S** [comment]
FTR: Wayland support has been added in commit 3718effc431f5622a23c55b254153efdfe4e72c4 and will be in release 1.4.0

**Comment by MatthiasWM** [comment]
Looking at Arcane, it seems to be much closed to SDL than Wayland or any X11 window manager with SDL running on anything from Desktop over Mobile Phones all the way to game consoles. It has all the features that Arcane has, as far as I was able to compare, and SDL is very mature, being used in hundreds of projects. 

Maybe I am missing something?

**Comment by jackghg** [comment]
Ok, I hope that the thing is modular now.
