### ISSUE TITLE
Examples are not installed (but their man pages are)

### ISSUE THREAD

**Issue by dvzrv** [fltk/fltk#23]
The blocks, checkers and sudoku examples are being built automatically using the cmake setup, their man pages are installed using `make install`, but not the applications themselves, neither their XDG and icon integration.

**Comment by Albrecht-S** [comment]
Thanks for the report. All test (example) programs in the test/ folder are always built intentionally unless you deactivate the corresponding CMake option. At some time in the past we decided not to install test/demo programs, but I'm not sure if we should consider to at least install these three mentioned programs.

The fact that the man pages are installed but not the programs is obviously a bug, thanks for the heads-up.

**Comment by Albrecht-S** [comment]
Since we decided not to install the test and game programs in the past I removed the installation of their man pages as well for consistency.
