### ISSUE TITLE
Building FLTK 1.3.6 in Mac failed

### ISSUE THREAD

**Issue by gfisys** [fltk/fltk#236]
Hello,

I'm trying to build fltk 1.3.6 in my Mac.
First I configured fltk to create multi architecture binaries using:

`./configure --with-archflags="-arch i386 -arch x86_64 -arch arm64"`

Then started the build using 

`make`

The build failed with this message:

fl_draw_pixmap.cxx:217:3: error: unknown type name 'U32'
   U32 *q = (U32*)out;
fl_draw_pixmap.cxx:217:13: error: use of undeclared identifier 'U32'
   U32 *q = (U32*)out;
fl_draw_pixmap.cxx:217:17: error: expected expression
   U32 *q = (U32*)out;

3 errors generated.
make[1]: *** [fl_draw_pixmap.o] Error 1
make: *** [all] Error 1

However, if I did not configure for multi architecture binary the build was completed without any errors.
Anybody know what should be done to get a successful build for multi architecture binary?

Thanks,
Henry

**Comment by erco77** [comment]
Just guessing: Try leaving the "-arch i386" out.
I mean, i386.. on a mac?

**Comment by gfisys** [comment]
Thanks for the swift response. 
You're right, I was copying the example from the read me text without even thinking!

So I removed the i386 from the configuration, the build error is now gone, but the build ended with this error message instead:

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fluid] Error 1
make: *** [all] Error 1

Is this something to worry about?
All 6 lib binaries libfltk_forms.a,  libfltk_gl.a,  libfltk_images.a,  libfltk_jpeg.a,  libfltk_png.a, and  libfltk.a were generated.

**Comment by erco77** [comment]
Assuming you're now using `./configure --with-archflags="-arch x86_64 -arch arm64`, be sure to do a `make clean; make` after.

If that's not it, I'm not sure what the problem is, as that runs to completion and results in generating "fat" dual architecture executables, e.g.
```
$ file test/tree.app/Contents/MacOS/tree 
test/tree.app/Contents/MacOS/tree: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
test/tree.app/Contents/MacOS/tree (for architecture x86_64):	Mach-O 64-bit executable x86_64
test/tree.app/Contents/MacOS/tree (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by gfisys** [comment]
`clean make` prior to `make` worked.

Thanks so much!
