### ISSUE TITLE
Dynamic scaling broken in current revision?

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#239]
Scaling with keys CTRL+/- behaves very strange (Ubuntu 20.04):
+ shows 90% but size of window increases. - shows 110% but size decreases.

**Comment by Albrecht-S** [comment]
Yes, indeed. Thanks for the report. This is a regression introduced by the latest commit f94ed7116. I'm looking into it...

**Comment by Albrecht-S** [comment]
OK, this should be fixed now. Hopefully. All feedback would be appreciated.

**Comment by bodomartin** [comment]
the latest commit fixes the issue for me. Many thanks for the almost instant reply & fix

**Comment by Albrecht-S** [comment]
Thanks for the quick feedback as well. 

My reaction was so quick because I was already working on it, and regressions are always taken seriously.

I'm closing this issue now again.
