### ISSUE TITLE
How to build fltk on Dev-C++

### ISSUE THREAD

**Issue by Howld** [fltk/fltk#24]
I don't know how to build it on Dev-C++. And I searched forums found there is a way to download devpack from fltk.net, but the site address is wrong. Could you help me to solve this problem?

**Comment by Albrecht-S** [comment]
The official FLTK website is [fltk.org](https://www.fltk.org) (not `.net`). We do not officially support building with Dev-C++, i.e. we don't provide build files or specific help, although some FLTK users may be able to help you.

We recommend to use MinGW and/or MSYS for Windows or to use CMake to generate build files (IDE's) of your choice (including Visual Studio).

If you have further questions, please ask in our mailing list (Google Groups) at
https://groups.google.com/forum/#!forum/fltkgeneral
