### ISSUE TITLE
fl_wait missing on Mac

### ISSUE THREAD

**Issue by incanus** [fltk/fltk#246]
I'm new to the project, but trying to link against it for another piece of software that I'm trying out. It turns out that there is no `fl_wait()` in `src/Fl_cocoa.mm`. I'm curious if this is known, intentional, and/or relatively trivially fixed as I'd be willing to try to contribute it. I searched through the mailing lists, commit history & issues/PRs here, and I've not turned up any relatively quick answers. 

Looking at latest version - 1.3.6.

**Comment by erco77** [comment]
Hmm, perhaps you want Fl::wait() instead of fl_wait()?

**Comment by incanus** [comment]
I apologize — of course, immediately after I dug into this and posted about, I discovered this fixed in the code trunk though not yet distributed in the project source tarballs. Indeed this has been taken care of in this way.
