### ISSUE TITLE
Add a flexible row/column container widget

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#255]
We've often been asked to add a container widget to allow simple row and column resizing.

I'd like to evaluate [Fl_Flex](https://github.com/osen/FL_Flex) for inclusion in FLTK. Fl_Flex supports two types of containers: row and column containers. Both types can be combined, i.e. nested to create a layout.

Other options, even rewriting from scratch, may be considered as well.

If anybody finds similar widgets as candidates for inclusion in FLTK, please add a comment with more information and a link.

**Comment by grammoboy2** [comment]
Qt in Supercollider.
https://youtu.be/Ww2QbWwWln0?t=1509

(Juce for Csound)
https://cabbageaudio.com/docs/groupbox/

Tk seems to be proud (one of the best if you've to believe them) on it's grid (not pack) system:
https://tkdocs.com/tutorial/grid.html

**Comment by gvnnz** [comment]
> Qt in Supercollider.
> https://youtu.be/Ww2QbWwWln0?t=1509
> 
> (Juce for Csound)
> https://cabbageaudio.com/docs/groupbox/
> 
> Tk seems to be proud (one of the best if you've to believe them) on it's grid (not pack) system:
> https://tkdocs.com/tutorial/grid.html

And also JUCE's Flexbox class: https://docs.juce.com/master/classFlexBox.html

**Comment by Albrecht-S** [comment]
Thanks to all who posted comments and those who will do this later. I'm now collecting and evaluating information, please be assured that all comments and pointers are much appreciated, even if I will not comment each of them (or only with a thumbs-up).

I need some time to evaluate everything and I'll post a summary when done. TIA.

**Comment by Albrecht-S** [comment]
Status update: A new layout / container widget [Fl_Flow](https://github.com/osen/Fl_Flow) has been announced in [fltk.general](https://groups.google.com/g/fltkgeneral/c/rFQ-1dNBb8o) and is under investigation for inclusion. It supports a very flexible layout, i.e. it is neither a "simple" row/column nor a grid container. See the description and tutorial on its [GitHub page](https://github.com/osen/Fl_Flow#readme).

**Comment by Albrecht-S** [comment]
The new container widget Fl_Grid will be added in FLTK 1.4.0 (see #256).
This can also be used for a single row or column. I'm leaving this issue open for later decisions.

**Comment by Albrecht-S** [comment]
FTR: Meanwhile I investigated usage of Fl_Flex and decided to include it as a light weight layout widget.

[Fl_Flex](https://github.com/osen/FL_Flex) will be included in FLTK 1.4.0 (as well as [Fl_Grid](https://github.com/fltk/fltk/issues/256)).

**Comment by Albrecht-S** [comment]
The new `Fl_Flex` widget has been committed to the FLTK master branch in commit f37aca15e9786a7192e36ea4b0295ab4dc12819f. For a short description of the changes please see the commit log (link above).

The [full documentation of Fl_Flex](https://fltk.gitlab.io/fltk/classFl__Flex.html) can be found on our GitLab mirror.

I believe that `Fl_Flex` is feature complete for the upcoming `FLTK 1.4.0` release. There may still be minor updates but AFAICT there are no more required features. However, suggestions will be considered if they are small enough to implement quickly.

**Comment by erco77** [comment]
Cool! Long needed widget.

I looked at the docs, could use:

- a "Description"
- small example code snippet
- screenshot of the example

Perhaps what's the in the constructor docs would suffice to populate the Description, or a combo of that and the opening comment for this issue.

Hate to chime this in this late, but I couldn't remember what "Fl_Flex" was by its name. If we're happy with the name, that's fine.. but maybe "Fl_Row_Column" be more inviting and self descriptive?

**Comment by Albrecht-S** [comment]
@erco77 Hi Greg, thanks for your comments.

I also thought about a description which would be (IIRC) positioned in the `\file` section of the source file. But it was too late to do, I really wanted to get it done (after hours of work, particularly with the docs which I wrote from scratch). I'll update the docs after more feedback or when time permits.

Screenshots and a code snippet should certainly be added, I agree. Thanks.

I personally believe that Fl_Flex is a good name and it that we should keep a short name. IIRC the original author Karsten (@osen) wrote somewhere that it was inspired by the html/css 'flex' layout. The other new widget I'm working on is, as you may know, Fl_Grid which can be compared to the html/css 'grid' layout. Hence I believe we're consistent and people will certainly learn what it is good for.

Another documentation addition on my to-do list is in the documentation chapter ["How Does Resizing Work?"](https://fltk.gitlab.io/fltk/resize.html). There should be a (kinda) tutorial on how to use `Fl_Flex` and - when ready - `Fl_Grid` so users can learn how to use these widgets.

And as a start:

![flex_demo](https://user-images.githubusercontent.com/26235500/182192338-2dc75557-c80c-4fc7-8edf-8ca565387157.png)

Note that I colorized the nested Fl_Flex widgets differently for testing.

**Comment by ManoloFLTK** [comment]
Is the deprecated member function in the all new FLTK widget 
[Fl_Flex::isSetSize()](https://fltk.gitlab.io/fltk/classFl__Flex.html#aadf4968560145c417fd6c7ae07b6579d) really wanted ?

**Comment by Albrecht-S** [comment]
Actually there are two deprecated inline methods in the header only (`setSize()` and `isSetSize()`) which I implemented for backwards compatibility with the original Fl_Flex widget. This ensures that the original test and demo programs can be compiled w/o changes - except for changing the `#include` statement. I hope that users can port their old programs using Fl_Flex w/o issues.

Since these are small inline methods they should not generate code if not used by the program. I also surrounded these two methods with `#if (1)` and `#endif` so I could disable these methods for testing to be sure they are not used in the new code including demo programs.

That said, yes, they were added intentionally although this is a new widget in the FLTK core, but we can easily disable the compilation or make it optional.

@ManoloFLTK Thanks you for your comment.

**Comment by MoAlyousef** [comment]
Hi
Thanks for including Fl_Flex. I think several methods (remove, clear) should be overridden to remove the Fl_Widget pointer from the set_size_ list. 
Not doing so would mess up subsequent additions of widgets after removing others.

**Comment by Albrecht-S** [comment]
Hi @MoAlyousef, thank you very much for your comment. I'm aware of this problem and I'm going to add a solution shortly. In my current implementation stale widget pointers in the array don't do any harm - unless you delete a widget and subsequently create another one that gets allocated at the **exact same address**. This is not hypothetical, it really happened in one of my tests.

This will be fixed in a future update.

**Comment by Albrecht-S** [comment]
@MoAlyousef Please wait a moment before you integrate this version in fltk-rs. I'm planning to change the API before the final release. Right now I'm going to implement different margins on all four sides (optional, if requested) which will need another API.

Generally the API will only be stable when FLTK 1.4.0 will be released, notwithstanding later ABI compatible additions.

**Comment by MoAlyousef** [comment]
Thanks @Albrecht-S  for the heads up

**Comment by Albrecht-S** [comment]
Progress report: commit 713d276b1c0786da3390e4e78dc9de7bd31a8b62 updates some methods, adds support of different margins on all sides and improves the documentation.

From my point of view `Fl_Flex` is now final, i.e. its API can be considered **_almost_** stable for the release of FLTK 1.4.0. However, suggestions for improvements would still be appreciated.

@erco77 Documentation: description, example and screenshot of a **very simple** layout are now in the [docs on our GitLab mirror](https://fltk.gitlab.io/fltk/classFl__Flex.html#details). I just added an improved version of the source code to our examples: [examples/howto-flex-simple.cxx](https://github.com/fltk/fltk/blob/e6c2503453ed6ff253b2574211edaeb936b51965/examples/howto-flex-simple.cxx).

@MoAlyousef The new `margin()` API is in place but - as mentioned above - changes are still possible. Test reports would be very much appreciated. The new feature to check for deleted widgets is not yet implemented, I'm still considering two different approaches which will need some more time. My goal is to implement a solution suitable for other widgets (groups, containers) as well and the new `Fl_Grid` widget is one of these containers that needs it.

**Comment by MoAlyousef** [comment]
Hi @Albrecht-S 
It seems with the latest commits, removing widgets works.

**Comment by Albrecht-S** [comment]
@MoAlyousef Yes, thanks for the feedback. I worked together with @MatthiasWM on the final solution (we decided to use his proposal) and this is now in Git.

**Comment by Albrecht-S** [comment]
FYI: We've been discussing recently to change the API of some methods, e.g. `set_size()` and `margin()` / `margins()` and related methods for more consistency and clarity. Hence my "warning" above still holds: the API is not yet final, please expect minor changes to come.

**Comment by Albrecht-S** [comment]
FTR: there's now real work in progress to rename some existing methods. If you are interested, please see PR #594.

Short info (incomplete):
- rename method names `margins(…)` (plural) to `margin(…)` (singular form)
- rename method names set_size(…) to fixed(…) (better compliance with FLTK style)
- potential change(s) in fluid file syntax (may break existing .fl files)

I hope that I can finish `Fl_Flex` soon. I'll give a summary of the changes when they are committed/pushed to the repo.

**Comment by Albrecht-S** [comment]
FYI: PR #594 has been merged. This changes some method names as announced above. There are no semantic changes, you can just edit your source files to replace the method **_names_**. Sorry for the inconvenience for beta testers.

For details please see commit 44a2547394a3b4f8b0177c2f33aa8ed47a2c1051.

Note: this commit may affect existing (**pre-release**) fluid (`.fl`) files: you may want to edit and replace `"set_size_tuples"` with `"fixed_size_tuples"`. This syntax change was chosen to be compatible with the method names (`set_size()` renamed to `fixed()`).

I'm pretty confident that the API is now final. It should only be extended in the future (no more method name changes). However, as said before, it's only final when FLTK 1.4.0 is released.

All test results would be appreciated. Thank you in advance.

**Comment by Albrecht-S** [comment]
I'm glad to say that there haven't been any changes since Dec 15, 2022 (44a2547394a3b4f8b0177c2f33aa8ed47a2c1051), and there are currently no further plans to change anything in the interface of `Fl_Flex` [(link to documentation)](https://www.fltk.org/doc-1.4/classFl__Flex.html).

I'm closing this issue now, it's all done. Thanks to all who tested and commented.
