### ISSUE TITLE
Fix for chdir compiler warning

### ISSUE THREAD

**Issue by zcream** [fltk/fltk#257]
I changed fl_utf8.h to 
```
#ifdef WIN32

#  if !0 && !defined(__CYGWIN__)

//#    undef chdir
//#    define chdir _chdir
```

This prevents compiler warnings in Visual Studio.

: warning C4996: '_chdir': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _chdir

The rest of the code builds fine.

**Comment by Albrecht-S** [comment]
Note: the label "wontfix" is meant for FLTK 1.3 exclusively.

FTR: there are a lot of other similar, known warnings, even in FLTK 1.4.0. As I wrote, these warnings are benign and will maybe be fixed slowly if someone finds the time to do it.

Related issue: #109

**Comment by zcream** [comment]
You are correct, its from the 1.3 branch. I had used 1.4 earlier and do not recollect these warnings.
