### ISSUE TITLE
Question: Can I keep GUI program running after Fl::run() returned?

### ISSUE THREAD

**Issue by Lucy2003** [fltk/fltk#265]
Hi,

I'm trying to build a GUI program with FLTK 1.3.5 and Go 1.16.3.
I have generated a project by FLUID,and added some interface functions so that I can static link them with CGO and use them in Go.

**The question is that,I have no idea about how FLTK manage memory of widgets and windows,so that I'm not sure whether I should delete all widgets or not when the Fl::run() returned.**

I can't find any method like `Fl::end()` in the document,and the document suggested that the program should return after Fl::run() returned.If I don't follow the document,will it cause memory leak?

Thanks.

**Comment by Albrecht-S** [comment]
Hi Lucy, we're using GitHub issues only for error reports and feature requests.

A short answer is that you don't need to return immediately after Fl::run() and that you don't need to care about memory leaks if you return after some time and don't work with FLTK in a continuous loop, i.e. opening and closing different windows with their widgets. User support is available in our Google group and/or mailing list. If you need more help, please see the information below. Thank you.

This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.

Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by Lucy2003** [comment]
Sorry for that,thanks.
