### ISSUE TITLE
macOS OpenGL + tooltips

### ISSUE THREAD

**Issue by geuzaine** [fltk/fltk#27]
Hi @ManoloFLTK,

The current master (38cf195727822fc873c6b08374b04504e7e362ab) behaves in a weird way on macOS when tooltips are drawn on top of OpenGL windows. To reproduce, apply the following one-liner to test/cube.cxx:

```
--- a/test/cube.cxx
+++ b/test/cube.cxx
@@ -148,6 +148,7 @@ void makeform(const char *name) {
   if (Fl::cfg_gfx_opengl) { // try to overlay a button onto an OpenGL window
     cube->begin();
     Fl_Button *test = new Fl_Button(35, 105, 100, 30, "Test");
+    test->tooltip("Test tooltip");
     test->box(FL_ROUND_UP_BOX);
     cube->end();
   }
```

Hovering several times over the button has the tooltip moving around the screen.

**Comment by ManoloFLTK** [comment]
That should be now repaired in the git repository.

**Comment by geuzaine** [comment]
Verified as fixed. Thanks!
