### ISSUE TITLE
Documentation inaccuracy regarding Fl_Image::count()

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#272]
The documentation for Fl_Image::data() here:
https://github.com/fltk/fltk/blob/9e0f140f0a50688d36928feb51b0719f94c7db53/FL/Fl_Image.H#L162

states that count() can be used to retrieve the length of data which is not correct. 

That said, maybe adding a convenience method to get the length of the data would be helpful.

**Comment by Albrecht-S** [comment]
Thanks for the report, but ...

The wording is admittedly confusing, but it really says "the size of the `data array`". This means the number of components of the array pointed to by array().

That data array is (AFAICT) not really (well) documented. It has different contents depending on the type of image but I can't tell what this contents is off the top of my head. See documentation of count():
> The count() method returns the number of data values associated with the image.
> The value will be 0 for images with no associated data, 1 for bitmap and color images, and greater than 2 for pixmap images.

That said, inaccuracy might be the wrong word but I agree that the documentation could (should) be improved.

**Comment by Albrecht-S** [comment]
I tried to improve the docs of count() and data(). Note that there are some undocumented details - the only documented construction of the data() array is for Fl_RGB_Image and derived classes.

You can view the updated [docs at our GitLab mirror](https://fltk.gitlab.io/fltk/classFl__Image.html) but you may need to update your browser cache. The docs on fltk.org will be updated later.

Does this help? Can we close this issue?

**Comment by MoAlyousef** [comment]
Yes it’s less ambiguous now. Closing the issue.
