### ISSUE TITLE
Error when trying to compile an FLTK program

### ISSUE THREAD

**Issue by rempas** [fltk/fltk#273]
I've downloaded and built FLTK from master under Manjaro Linux after running the following command to configure: `./configure --disable-gl`. I then run `make` and then `make install` and everything was successful. Now I'm reading thought the FLTK documentation and in the [basics](https://fltk.gitlab.io/fltk/basics.html) section, I'm trying to use the given commands to compile my program and I'm getting the following error message:

```
/usr/bin/ld: /usr/local/lib/libfltk.a(Fl_X11_Window_Driver.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Unless I'm doing something wrong. The exact command used is: ``gcc `fltk-config --cxxflags` -I/usr/local/include test.cpp -L/usr/local/lib -lfltk -lXext -lX11 -lm``. Any ideas?

**Comment by Albrecht-S** [comment]
Hi @rempas, thanks for your report. This error message means that you need to add `-ldl` to your commandline (symbol `dlsym` is missing). Depending on the options you used to build FLTK and your system configuration there may be even more required commandline flags. IIRC the requirement to add `-ldl` has been added later than the time when the docs were written but I believe all Linux builds need this nowadays. I'll add this to the docs. The recommended way to find the required flags is to use `fltk-config` as described in the same chapter.

That said, this is not the place to ask questions on how to build or use FLTK. If you have further questions, please follow the advice below. Thanks. Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
> Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by Albrecht-S** [comment]
FTR: I updated the relevant docs in commit c3857517b01c5085a385f8750038d7a069be64a7.

The new docs can be viewed [online on our GitLab mirror](https://fltk.gitlab.io/fltk/basics.html#basics_standard_compiler), the docs on fltk.org will be updated later.
