### ISSUE TITLE
Fl::run returns immediately when Fl_Window is wrapped in a PIMPL class

### ISSUE THREAD

**Issue by Neur1n** [fltk/fltk#275]
I apologize that I don't know how to descript it in short, so let's begin with a working example:

```cpp
#include <FL/Fl.H>
#inlucde <FL/Fl_Window.H>

class App
{
public:
  App(int w, int h, const char *title)
  {
    this->m_win = new Fl_window(w, h, title);
    this->m_win->show();
  }

  ~App()
  {
    if (this->m_win)
    {
      delete this->m_win;
      this->m_win = nullptr;
    }
  }
private:
  Fl_Window *m_win;
};

int main()
{
  App app(400, 300, "APP");
  return Fl::run();
}
```

The above snippet works properly and show an empty window when it runs, but when I turned it into PIMPL (see below), the window flashes and `main` returns 0 almost immediately:

In `app.h` file:

```cpp
class AppImpl;

class App
{
public:
  App(int w, int h, const char *title);
  ~App();
private:
  AppImpl *m_impl;
};
```

In `app.cpp` file:

```cpp
#include "app.h"

class AppImpl
{
public:
  AppImpl(int w, int h, const char *title)
  {
    this->m_win = new Fl_window(w, h, title);
    this->m_win->show();
  }

  ~AppImpl()
  {
    if (this->m_win)
    {
      delete this->m_win;
      this->m_win = nullptr;
    }
  }

private:
    Fl_Window *m_win;
};
```

In `main.cpp` file:

```cpp
#include "app.h"

int main()
{
  App app(400, 300, "APP");
  return Fl::run();
}
```

Therefore the problem is, how to make the PIMPL code work? I've read the multithreading part of the documentation, but I'm not sure if my code is related.

Any help is much appreciated.

**Comment by engelsman** [comment]
The problem is that in the second version, your App constructor doesn't create/new an AppImpl and therefore no Fl_Window is created and shown either, so Fl::run() will simply return straight away.

Please note that this github issues page is for discussing identified problems with the FLTK library itself.
To discuss problems in user code, please post your question to the fltk.general mailing list / newsgroup, where you should also mention which version of FLTK you are using, and on which platform, as that might be relevant.

**Comment by Albrecht-S** [comment]
Hi @Neur1n, although this is not the right/best place to ask this kind of user questions I was curious enough to complete your code and run it. I'll post my results in a follow-up message.

That said, following is the "standard reply" to user questions, please follow the advice if you have further questions:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
> Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by Albrecht-S** [comment]
@Neur1n One more note: your code was incomplete (missing headers, constructors, destructors) and there were some typos. I wonder how this code could compile. If you ask further questions in fltk.general, please try to post complete, compileable code so we can better help you.

I converted your files so I could compile the entire program with `fltk-config --compile main.cpp`:
```cpp
// file: main.cpp
#include "app.h"

int main() {
  App app(400, 300, "APP");
  return Fl::run();
}
```
```cpp
// file: app.h
#include <FL/Fl_Window.H>

class AppImpl {
public:
  AppImpl(int w, int h, const char *title) {
    this->m_win = new Fl_Window(w, h, title);
    this->m_win->show();
  }
  ~AppImpl() {
    if (this->m_win) {
      delete this->m_win;
      this->m_win = nullptr;
    }
  }
private:
  Fl_Window *m_win;
};

class App {
public:
  App(int w, int h, const char *title) { m_impl = new AppImpl(w, h, title); }
  ~App(){};

private:
  AppImpl *m_impl;
};
```
Hope this helps.

**Comment by Neur1n** [comment]
My apologies. I did missed the implementation part of `App` in my descriptions. It is weird that this minimal example works but my actual code (although they are almost identical) does not.

Thanks for your time.

**Comment by Neur1n** [comment]
I get it. I compiled a shared library based on static-linked FLTK library, to which my actual `App` class linked to. Then this issue happened. Thanks for your help.
