### ISSUE TITLE
Setting width of display area of slider value

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#285]
Referring to stackoverflow question "[FLTK Setting width of display area of slider value](https://stackoverflow.com/questions/65052741/fltk-setting-width-of-display-area-of-slider-value)":

We should consider making the value display size of sliders changeable by the user so they can use larger numbers or larger fonts.

Citation from the question: _"I was wondering how to change the width of the area responsible for showing the current value of a Fl_Hor_Value_Slider. The thing is, I want to be able to select a year (that's 4 digits) and the space on the side of the slider is not enough to display the year number correctly."_

**Comment by MatthiasWM** [comment]
All value sliders in 1.4 have the method `value_width(int)` that does exactly that. Are there other widgets that need to be fixed, because:
 @Albrecht-S _This is not only true for Fl_Hor_Value_Slider but also for several other slider types and even some more widgets._

**Comment by Albrecht-S** [comment]
The method `value_width()` has been added in FLTK 1.4.0 in commit 191aeefc4a4161cb132065625a5e5eacb567688a based on [STR 3222](https://www.fltk.org/str.php?L3222) in Nov. 2022 (later than this issue was created). Hence (the main part of) this issue is resolved and it can probably be closed.

@MatthiasWM My point "... and some more widgets" was off the top of my head and should be interpreted that there are some other widgets with hardcoded values, sizes, or colors for some aspects. Since I don't know which ones there are two options: you can either search for such hardcoded properties that users can't change, or ... we close this issue and wait for other reports. I wouldn't mind if you closed it as "fixed".
