### ISSUE TITLE
Fullscreen windows should not be cascaded

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#286]
There is a bug in the macOS window creation that misplaces windows if they are shown whilst in fullscreen mode. This bug has probably been around for ages, we just haven't noticed it until know as our other windows were previously all dialogs (which don't trigger the cascading offset for some reason).

I've confirmed that this fixes the issue:

```diff
diff --git a/src/Fl_cocoa.mm b/src/Fl_cocoa.mm
index be07b09fb..341d91a3c 100644
--- a/src/Fl_cocoa.mm
+++ b/src/Fl_cocoa.mm
@@ -3299,7 +3299,7 @@ void Fl_X::make(Fl_Window* w)
     [cw setLevel:winlevel];
     
     q_set_window_title(cw, w->label(), w->iconlabel());
-    if (!w->force_position()) {
+    if (!w->force_position() && !w->fullscreen_active()) {
       if (w->modal()) {
         [cw center];
       } else if (w->non_modal()) {
```

**Comment by ManoloFLTK** [comment]
@CendioOssman: please, close the issue if you confirm the 1.3 branch is now fixed.

**Comment by Albrecht-S** [comment]
> We have people building things themselves, e.g. via homebrew. So we would prefer actual releases that we can tell people to use.

@CendioOssman I'm now planning a new release (1.3.8) during the next about four weeks. You can help with your test results to make this happen as early as possible. Please report any open issues you might need for TigerVNC.

**Comment by williamsjoblom** [comment]
@Albrecht-S As far as I know, #286, #287, and #288 along with a backport of b6b1fcc is sufficient for TigerVNC, but maybe @CendioOssman has further thoughts?

**Comment by Albrecht-S** [comment]
@williamsjoblom Thanks for your comments. The three mentioned issues are either already closed or waiting for confirmation.

The potential backport of b6b1fcce4103 is something @ManoloFLTK needs to take a look at. For me the code looks similar (but different) and I can't tell if the same patch can be applied w/o further changes. Manolo?

**Comment by CendioOssman** [comment]
> @Albrecht-S As far as I know, #286, #287, and #288 along with a backport of [b6b1fcc](https://github.com/fltk/fltk/commit/b6b1fcce4103f6a401571e9050f4482d38d3a6c9) is sufficient for TigerVNC, but maybe @CendioOssman has further thoughts?

Nothing further from me. Those issue are ready to be closed then.

**Comment by Albrecht-S** [comment]
Thanks for confirmation.

I'm not sure if we still need backporting of b6b1fcce4103 though as @williamsjoblom mentioned above. Waiting for @ManoloFLTK to chime in ...

**Comment by ManoloFLTK** [comment]
I will also backport b6b1fcc from master to branch 1.3 to allow building with non Apple compiler.
