### ISSUE TITLE
Printing without and with GTK II

### ISSUE THREAD

**Issue by szukw000** [fltk/fltk#290]
@Albrecht-S,

The code I used was from test/device.cxx . I removed the whole contents of
  /usr/local/fltk14/

winfried
[print-non-gtk-error.txt.zip](https://github.com/fltk/fltk/files/7533259/print-non-gtk-error.txt.zip)

**Comment by Albrecht-S** [comment]
@szukw000 Please don't open new issues for additional information. You can add comments to the original issue instead. I'm copying your reply to the original issue and I'm closing this one now.

See https://github.com/fltk/fltk/issues/289
