### ISSUE TITLE
failed to build with pango library

### ISSUE THREAD

**Issue by ikey4u** [fltk/fltk#291]
The original issue is posted on [fltk-rs project](https://github.com/MoAlyousef/cfltk/issues/207), and i just copy it here for convinient.

In centos 6 with devtoolset-6 installed which contains gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3), the following command will not compile

```
cargo build --example spreadsheet --verbose
```

and the error is

```
gmake: warning: -jN forced in submake: disabling jobserver mode.
  /root/dev/fltk-rs/fltk-sys/cfltk/fltk/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx: In function ‘void draw_image_cb(void*, int, int, int, uchar*)’:
  /root/dev/fltk-rs/fltk-sys/cfltk/fltk/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx:58:26: error: invalid operands of types ‘uchar* {aka unsigned char*}’ and ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ to binary ‘operator+’
       buf += abs(cb_data->D);
                            ^
  /root/dev/fltk-rs/fltk-sys/cfltk/fltk/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx:58:26: error:   in evaluation of ‘operator+=(uchar* {aka unsigned char*}, __gnu_cxx::__enable_if<true, double>::__type {aka double})’
  /root/dev/fltk-rs/fltk-sys/cfltk/fltk/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx: In member function ‘virtual void Fl_Cairo_Graphics_Driver::draw_image_mono(const uchar*, int, int, int, int, int, int)’:
  /root/dev/fltk-rs/fltk-sys/cfltk/fltk/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx:539:28: error: invalid operands of types ‘const uchar* {aka const unsigned char*}’ and ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ to binary ‘operator+’
     if (D<0) data += iw*abs(D);
                              ^
  /root/dev/fltk-rs/fltk-sys/cfltk/fltk/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx:539:28: error:   in evaluation of ‘operator+=(const uchar* {aka const unsigned char*}, __gnu_cxx::__enable_if<true, double>::__type {aka double})’
  gmake[2]: *** [fltk/src/CMakeFiles/fltk.dir/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx.o] Error 1
  gmake[1]: *** [fltk/src/CMakeFiles/fltk.dir/all] Error 2
  gmake: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2
```
It seems that `abs` function does not work properly, see stackoverflow [here](https://stackoverflow.com/questions/8226705/g-abs-on-a-short-int-appears-to-turn-it-into-a-double/8227799). By simply convert `abs(xx)` to `int(abs(xx))`, the problem is gone. Should we make a patch to `Fl_Cairo_Graphics_Driver.cxx`?

**Comment by Albrecht-S** [comment]
Thanks for the report. I'll look into it and try to fix it. No need to make a patch, thanks. Thank you also for the stackoverflow link.
...
Done. Commit d96c980d29c3caecadca49af62def57e86d7eed9 should fix the issue. Please report if this works for you and/or close the issue. Thanks.

Note: as the commit message says I also included two missing header files. This alone might have fixed the issue but I applied another fix by introducing a local variable similar to another fix in the postscript driver.

**Comment by ikey4u** [comment]
> Thanks for the report. I'll look into it and try to fix it. No need to make a patch, thanks. Thank you also for the stackoverflow link. ... Done. Commit [d96c980](https://github.com/fltk/fltk/commit/d96c980d29c3caecadca49af62def57e86d7eed9) should fix the issue. Please report if this works for you and/or close the issue. Thanks.
> 
> Note: as the commit message says I also included two missing header files. This alone might have fixed the issue but I applied another fix by introducing a local variable similar to another fix in the postscript driver.

Confirmed, this issue is fixed, thank you.

**Comment by Albrecht-S** [comment]
@ikey4u Thanks for confirmation. I'm closing this issue now.
