### ISSUE TITLE
DOS windows pop open/closed during Visual Studio builds

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#293]
This is probably caused by VS build invoking 'fluid' to generate .cxx/.h from .fl. It seems fluid is built as /subsystem:windows for both debug and release modes.

If we really need fluid to be a /subsystem:windows app, then perhaps we should generate two executables for fluid on windows platforms:

- **fluid.exe** - linked with /subsystem:windows
- **fluid-cmd.exe** - linked with /subsystem:console

..and then invoke fluid-cmd.exe (instead of fluid) in the VS build scripts.

Perhaps too, for command line use operations like fluid -c:

- fluid.exe should output errors to an fl_alert() dialog
- fluid-cmd.exe should output errors to stderr

Currently, my tests show that on Windows with fluid built using VS, a command like: `fluid -c somefile.fl` does not show an error message at all e.g. if `somefile.fl` does not exist, which is bad. And if I rename away e.g. test/tabs.fl and rebuild FLTK in VS, while it does detect a non-zero exit return from fluid, there's no indication as to what the problem is (file not found, permission denied, etc)

**Comment by Albrecht-S** [comment]
Related issue: #224 which covers (amongst others) building a second `fluid-cmd.exe` for windows which will hopefully solve this issue as well.

**Comment by Albrecht-S** [comment]
@erco77 A patch has been posted to issue #224, please test and confirm that it fixes this issue.

**Comment by Albrecht-S** [comment]
This issue is fixed (commit 228d04d0e0d6e968c59bcab606e609eb1103f917).
