### ISSUE TITLE
Compiler warnings with msys2 (current) + fltk-1.4.x current

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#296]
Basically the PNG lib and Fl_Table threw some warnings:
[fltk-build-errors-msys2-current.txt](https://github.com/fltk/fltk/files/7598714/fltk-build-errors-msys2-current.txt)

I started with a fresh install of msys2 from today using these instructions:

        1) I followed steps 1 through 7 on this page: https://www.msys2.org/

        2) Not sure why, but 'git' was not part of the 'base-devel' install in step 7 above,
           so I had to install it with: pacman -S git

        3) Cloned fltk, cd'ed into the directory and ran 'make':

                git clone https://github.com/fltk/fltk.git fltk-1.4.x.git
                cd fltk-1.4.x.git
                make

This automatically ran autogen, ran configured, and then started building FLTK.

Built OK, 2 warnings no errors.

I'm looking into the Fl_Table related warnings.

**Comment by erco77** [comment]
Hmm, I've checked the Fl_Table_Row related warnings, both in source and with valgrind and debugging messages added, and I'm not seeing a problem. The size is never 0 when arr[] is set.

It would /seem/ the warnings are not taking into account the behavior of size(int) which enlarges the array, unless I'm missing something subtle in the warning. But I'd think the compiler is smarter than that, so I feel like I'm missing something.

There's a conversion from int -> uint which is a possible concern, but not really; going out of range of a positive signed int is beyond the range of what a table could realistically handle anyway. The only thing I see is I should probably document that the argument to size() must be 0 or larger. Negative values would be bad. Same for row() and col() methinks. I can handle that.

But I'm not seeing the problem with Fl_Table* warnings.. hmm.

**Comment by erco77** [comment]
Seems a range check solves the Fl_Table_Row related warning, so committed as e97fd17.

**Comment by Albrecht-S** [comment]
Well, that's "funny". I rebuilt everything from scratch (latest git) and I don't see "your" warnings. I can see another (maybe) bogus warning in my build though. Wondering what's going on.

Some details:
```
$ gcc --version
gcc.exe (Rev5, Built by MSYS2 project) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
...
$ ./configure --enable-localpng --enable-localzlib --enable-localpng
configure: loading site script /etc/config.site
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
...
       Graphics: GDI+
Image Libraries: JPEG=Builtin
                 PNG=Builtin
                 ZLIB=Builtin
    Large Files: YES
         OpenGL: YES
        Threads: YES
...
$ make -j4
...
(no errors or warnings in png, jpeg, and zlib and elsewhere unless shown here)
...
Compiling drivers/GDI/Fl_GDI_Graphics_Driver_color.cxx...
In member function 'virtual void Fl_PostScript_Graphics_Driver::color(unsigned char, unsigned char, unsigned char)',
    inlined from 'virtual void Fl_PostScript_Graphics_Driver::color(Fl_Color)' at drivers/PostScript/Fl_PostScript.cxx:203:8:
drivers/PostScript/Fl_PostScript.cxx:1049:7: warning: writing 2 bytes into a region of size 1 [-Wstringop-overflow=]
 1049 |   cr_ = r; cg_ = g; cb_ = b;
      |   ~~~~^~~
In file included from drivers/PostScript/Fl_PostScript.cxx:23:
drivers/PostScript/Fl_PostScript_Graphics_Driver.H: In member function 'virtual void Fl_PostScript_Graphics_Driver::color(Fl_Color)':
drivers/PostScript/Fl_PostScript_Graphics_Driver.H:128:17: note: at offset 0 to object 'Fl_PostScript_Graphics_Driver::cr_' with size 1 declared here
  128 |   unsigned char cr_,cg_,cb_;
      |                 ^~~
Compiling drivers/GDI/Fl_GDI_Graphics_Driver_font.cxx...
...
```
Other than that the build was successful.

It's even weirder! A subsequent build completed w/o any warnings:
```
$ LDFLAGS='-static-libgcc -static-libstdc++' ./configure --enable-localpng --enable-localzlib --enable-localpng --enable-debug
...
$ make -j3
...
```
The only issue I could see (and this is something I encountered regularly) is that the build seems to hang when building/linking some of the test programs. This seems to be kinda random but often CubeView seems to be involved. Restarting the build after ctrl/c runs to completion.

Side note: the build with LDFLAGS above creates portable `.exe` files that can be executed w/o MinGW/MSYS dependencies, for instance by clicking on the exe file in the Windows explorer.

**Comment by Albrecht-S** [comment]
Regarding my previous message: except setting the LDFLAGS (which I suppose doesn't have any effect on the warnings) I noticed that I configured the 2nd build with `--enable-debug` which obviously **DOES** make a difference. Still puzzled...

**Comment by erco77** [comment]
@Albrecht: Note this is with latest msys2 (see subject), which is version 11.2.x of g++.

**Comment by Albrecht-S** [comment]
OK, that may explain the differences. I used my current msys2 because I didn't want to upgrade for the test. As you can see above this was gcc 10.3.0.

**Comment by erco77** [comment]
You can (I think) rename away c:\msys64 and reinstall, then (maybe) switch back and forth by just renaming the directory. (Possibly environment variables differ slightly, I have no idea.. I guess you could test)

I don't do anything serious work with mingw/msys myself; all work I send out is built in VS.

**Comment by erco77** [comment]
Regarding the hangs during build, I haven't seen those, but I do build on a local drive. I've seen problems sometimes doing builds on network drives, and I think you noticed sometimes virus checkers cause trouble too.

**Comment by erco77** [comment]
Regarding the png warning: seems legit.
Can be solved easily enough by changing line of png/png.c (755):
```
-     char number_buf[5];
+     char number_buf[5] = "";
```
I know we're reluctant to fix the external lib code, but it sure seems like a fix they should accept.

**Comment by Albrecht-S** [comment]
@erco I checked the [libpng website](http://libpng.org/pub/png/libpng.html) (still at 1.6.37) and the [sourceforge git repository](https://sourceforge.net/p/libpng/code/ci/libpng16/tree/png.c) and couldn't find a change yet.

Please feel free to fix it if you flag it with a "FLTK" comment. In this case I suggest to use the issue number as documented in `README.bundled-libs.txt`:
```diff
-      char number_buf[5]; /* enough for a four-digit year */
+      char number_buf[5] = ""; /* enough for a four-digit year */ /* FLTK Issue #296 */
```

Whenever we need to upgrade libpng again we should notice the change and be able to apply the patch.

I'm leaving this to you because you can test and I'm too busy with other stuff. Would you also like to propose a patch upstream?

**Comment by Albrecht-S** [comment]
> Regarding the hangs during build, I haven't seen those, but I do build on a local drive.

Same here, although this is in a Virtualbox VM. I'm not up-to-date with the MSYS tools on my bare metal windows 10.

> I've seen problems sometimes doing builds on network drives, and I think you noticed sometimes virus checkers cause trouble too.

Yes, virus checkers, long story... I tried to **exclude** the FLTK build dirs from the MS virus checker but although it's registered and displayed it doesn't affect anything, the virus checker still runs at high CPU level during the build. In this special build case I disabled the entire virus checking (which reduced the CPU load) but it still hung. :-(

I'm also using the MSYS tools exclusively for FLTK development, hence I can live with such sporadic hangs (I can continue the build). Maybe these are gone after I upgrade the MSYS tools???

**Comment by erco77** [comment]
RE: upstream patch - libpng appears to be mailing list oriented to report bugs.. just curious if you're already on their mailing list?

If not I'll join (bleh, another mail folder) and report it.

**Comment by erco77** [comment]
RE: virus checker, you perhaps disabled only the disk scan. I'm not sure if there's a way to exclude the realtime checks or not (which I assume intercept open/close to do a check on a recently closed file, or perhaps even read/write ops). It's possible they don't support the latter, due to the realtime aspect, but I'm not sure.

**Comment by erco77** [comment]
RE: continued hangs - how strange that you still get a hang. I wonder if it's a virtual box thing? It's hard to trace stuff like hangs on Windows without strace. There used to be an strace for early versions of windows from sysinternals. I used to use it often. I think Microsoft took over sysinternals (the company) and continues those tools' development. I think they integrated the strace tool into a GUI tool (it used to be CLI) where you can still attach to e.g. a hung process and trace the NT system calls, which can sometimes help you identify the cause of the hang.

**Comment by erco77** [comment]
Actually, msys has an strace, so you might give it a try on your hung process. It's just like the linux one where you can either invoke a command under strace, or use strace to attach to a pid.. I figure the latter might work for you. 'strace -p <PID>'. Check the usage flags via `strace --help`, as there doesn't appear to be a man page.

**Comment by Albrecht-S** [comment]
> RE: upstream patch - libpng appears to be mailing list oriented...

I'm not on their mailing list. Would you please ... ?

> RE: virus checker, you perhaps disabled only the disk scan.

They don't say that explicitly, but maybe this is it. The only thing I could find that says to "exclude folder" is where I entered the "exclusion" (Virus & threat protection settings / Manage settings / Exclusions). If this is not for realtime checks, well, then OK. I'm also disabling the entire realtime checks during builds if I want to speed the build up.

RE: hangs. Don't bother, I can live with it or maybe an upgrade of MSYS2 will help. Or not. And yes, Sysinternals has been taken over by MS and they continue to provide the tools, at least that's what I experienced a few years ago. I'm no longer interested in Windows tools - unless I need them for FLTK development. ;-)

RE: strace: thanks, I'll give it a try if I really need. Typing ctrl/c and recalling the make command is usually faster.

**Comment by erco77** [comment]
Committed - since all warnings are solved, closing this.
However, I'll follow up here when I've reported the patch upstream.

**Comment by erco77** [comment]
Hmm, reopening because:

1. I'm not not completely convinced the libpng warning is legit. Looking at their code, I *think* the operation is safe, because their append code uses a position index that starts at 0, and only looks for null termination in the source string, not the dest. So the "fix" I committed just silences a possibly benign error. Investigating before I report upstream, as I want to be sure if there's security implications or not. Apparently reporting security issues for libpng can be done thru private email, without joining a mailing list. Just google for 'libpng reporting bugs' to find it, e.g.
```
If you wish to privately report a security issue (vulnerability)
in libpng, please report it by email to:
    png-mng-security at lists.osuosl.org
where it will be seen by a small group of long-time libpng
contributors. You don't need to subscribe (in fact you probably
won't be allowed to subscribe) to that list.
```

2. I see there's some other warnings I didn't catch from the build of test/icon.cxx, another potential buffer uninitialized issue. (attached)  [icon-warnings.txt](https://github.com/fltk/fltk/files/7604818/icon-warnings.txt)

**Comment by erco77** [comment]
Confirmed the png related compiler warning is a red herring (false lead). Attached test code [test-pngsafecat.c.txt](https://github.com/fltk/fltk/files/7604861/test-pngsafecat.c.txt) shows the destination buffer can be garbage and still work just fine, since indexing is used. Only the src buffer must be NULL terminated.

I suppose I should report this upstream anyway, not as a security issue, but to silence over zealous compiler warnings, as it's possible compilers of the future will simply report uninitialized buffers.

Question: Is it possible libpng builds with fewer warning flags than we build it with? If so they may never even see the warning even with the same build environment. I'll be sure to cover that we use libpng bundled with our own code.

I'll look into the test/icon.cxx warnings next.

**Comment by Albrecht-S** [comment]
> ... to silence over zealous compiler warnings ...

ISTR that we had similar warnings already. I believe the compiler **might** issue a warning even if the given argument is a pure output parameter - just because the compiler doesn't know it better because it can't "look into the function code". That said, it seems to be easier to initialize all variables that are used as parameters to function calls later. Just to be sure and silence such (formally) unnecessary warnings.

Just my 2 ct, I won't dig deeper into this, personally.

**Comment by Albrecht-S** [comment]
> I'll look into the test/icon.cxx warnings next.

And so did I. buffer is definitely used uninitialized to create an Fl_RGB_Image with undefined pixel data. Then `icon.color_average(c, 0.0);` overwrites the undefined pixels with the value of `c` (by "averaging" 100% c, 0% original data). Not nice.

I can see two solutions:
1. what happens if you move the declaration of buffer above choice_cb? This would init it with zeroes. The code would work but still be weird.
2. instead of using color_average() we could init `buffer[]` with appropriate values which would be 32 \* 32 \* (255, 0, 0) or (0, 255, 0) or (0, 0, 255), respectively.

The code would likely be longer but free of warnings and clear. Using color_average() is cool but hard to understand.

**Comment by erco77** [comment]
I have to put this on hold; today is the Thanksgiving holiday, but will dig into it later.

**Comment by Albrecht-S** [comment]
FWIW, after thinking about it, I'd suggest to use the simple solution 1 above (KISS) by either moving the buffer into the global space or making it static as a local variable (I'd prefer the latter). In both cases the buffer should be initialized with zeroes (IIRC), otherwise an initializer like `{ 0 }` would do it (untested). This would be well-defined and using `color_average()` as in the existing code would be an informative example as well.

**Comment by erco77** [comment]
RE icon.cxx:

Just adding 'static' in front of the uchar buffer declaration has the same effect as solution 1, and prevents a "global", so going with that.

I found the icon demo a bit confusing; I've opened a separate issue #297 with a few RFE's.

**Comment by Albrecht-S** [comment]
@erco Is this now all fixed (I think so), can we close this issue?

**Comment by erco77** [comment]
Need to send that email upstream. I sent you a private email about what I was sending them, and holding for your response on that. (Sent it about a week ago or so?) If you have time pls respond to that.

**Comment by Albrecht-S** [comment]
@erco77 Greg, I think you sent the mail to the PNG team and we could close this issue since all warnings are fixed. If they update their code we will notice this when we upgrade to the next PNG version.

Can we close this issue?

**Comment by erco77** [comment]
Hadn't actually sent it yet, so was holding it open till I did.
Was procrastinating about whether to use the security email address or not.
Just sent it now, so closing.
