### ISSUE TITLE
X11 image drawing performance degredation with recent commit

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#301]
With one of my applications, which relies primarily on drawing lots of images, I notice a severe performance degradation with latest Github-FLTK version. 

I tracked down the causing change to be:

[ X11+XRender platform: more accurate drawing of RGB images when GUI is scaled.](https://github.com/fltk/fltk/commit/2f506407327762ce30b4d895c856baa7f681d9bc)

Strange: My application is running unscaled (Fl::screen_scale()=1.0) and uses XRender (HAVE_XRENDER 1).

**Comment by wcout** [comment]
Some more digging ... this change seems to fix it:

````diff
diff --git a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
index 92ee52548..209c18dcd 100644
--- a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
+++ b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
@@ -772,11 +772,10 @@ void Fl_Xlib_Graphics_Driver::draw_rgb(Fl_RGB_Image *rgb, int XP, int YP, int WP
   if (!*Fl_Graphics_Driver::id(rgb)) {
     cache(rgb);
   }
-  float s = scale();
-  int Xs = Fl_Scalable_Graphics_Driver::floor(XP - cx, s);
-  int Wfull = Fl_Scalable_Graphics_Driver::floor(XP - cx + rgb->w(), s) - Xs  ;
-  int Ys = Fl_Scalable_Graphics_Driver::floor(YP - cy, s);
-  int Hfull = Fl_Scalable_Graphics_Driver::floor(YP - cy + rgb->h(), s) - Ys;
+  int Xs = floor(XP - cx);
+  int Wfull = floor(XP - cx + rgb->w()) - Xs  ;
+  int Ys = floor(YP - cy);
+  int Hfull = floor(YP - cy + rgb->h()) - Ys;
   if (Wfull == 0 || Hfull == 0) return;
   bool need_clip = (cx || cy || WP < rgb->w() || HP < rgb->h());
   if (need_clip) push_clip(XP, YP, WP, HP);

````

Must have something to do with `Fl_Scalable_Graphics_Driver::floor(int x, float s)` being a static method, which seems to be not inlined by the compiler (or whatever), leading to some costly calls? Strange...

**Comment by Albrecht-S** [comment]
@ManoloFLTK ?

**Comment by wcout** [comment]
Please don't invest your time in this ... though I see definitely this effect, there seem to  be some other accidental combination of things involved, that lead to the slowdown...
I have now compared the assembly code of the suspected instructions and it is (almost) identical!
I think I will close this one (and reopen only when 100% certain). Sorry for the noise!

**Comment by wcout** [comment]
It is so strange! The "real life" evidence shows consistently that this change makes the lag disappear from my application and re-appear if undone, but the "theory" shows, that this change has no effect on FLTK's code. Leaves me puzzled.
Closing for now...
