### ISSUE TITLE
Timer issue on macOS

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#306]
This was [reported in fltk.coredev](https://groups.google.com/g/fltkcoredev/c/J001Qmol9_Y):

Thread: "Rare crash on repeat_timeout on macOS"
Date:   Tue, 7 Dec 2021 13:10:54 -0300

My reply:

On 12/7/21 11:22 PM Albrecht Schlosser wrote:

Hmm, OK, this observation rang a bell somewhere in my brain (faint memory).
I believe there are two issues, one in the FLTK code and one likely in your
program, that "work together":

(1) the code in FLTK is (IMHO) incorrect, your added check works around
    this particular issue. I have this on my todo list and I'll probably
    file an issue so this won't be forgotten.

(2) the code in your program *might* call Fl::repeat_timeout() outside a
    timer callback which causes the 'current_timer' variable to be null.
    You can work around it in your program if you check that you call
    Fl::repeat_timeout() only in a timer callback that was triggered
    for this particular timer you want to repeat. Otherwise you must
    call Fl::add_timeout().

The (false) assumption in FLTK on macOS that the user code calls
Fl::repeat_timeout() *only* in the timer callback of the same timer
it wants to *repeat* is the culprit (IIRC). This is in platform specific
code only on macOS and should be fixed because the timer code on other 
platforms works differently.

**Comment by Albrecht-S** [comment]
Note to myself: the Fl::add_timeout() and related methods should be unified on all platforms with more common code and less platform specific code. The bug reported here results from a false assumption and different behavior on macOS than on other platforms.

**Comment by ggarra13** [comment]
Note that in my case I am not calling repeat_timeout from other place.  It Is being called from the same timeout.

**Comment by Albrecht-S** [comment]
Thanks for the clarification. Repeating my reply from fltk.general for later reference:

OK, this may be a different issue than I thought. Looking at your report, your "fix" is:
```
  if ( current_timer->timer == nullptr ) {
      return;
  }
```

If this does no longer crash then `current_timer` itself can't be `NULL` (otherwise it would still crash) but that was the case I had in mind.

The case that `(current_timer != nullptr)` but `(current_timer->timer == nullptr)` would definitely be different.

**Comment by Albrecht-S** [comment]
@ggarra13 Gonzalo, can you "archive" the source code of the program that exhibits this issue so you can test it again after a potential fix? If the error is not reproducible with a small test case this would be a valuable help.

**Comment by ggarra13** [comment]
> El 7 dic. 2021, a las 20:28, Albrecht Schlosser ***@***.***> escribió:
> 
> 
> @ggarra13 Gonzalo, can you "archive" the source code of the program that exhibits this issue so you can test it again after a potential fix? If the error is not reproducible with a small test case this would be a valuable help.
> 

The source code is already archived in branch v6.0.2 of mrViewer on both GitHub and sourceforge.  Compiling it from scratch is another issue as it has many dependencies. 

—
Gonzalo Garramuno
***@***.***

**Comment by Albrecht-S** [comment]
> Compiling it from scratch is another issue as it has many dependencies.

I didn't say that I wanted to build and test it, I'd rather ask you to test again when we have something to test, but hopefully with the same (i.e. archived) software version. I hope you don't mind and will assist. TIA.

**Comment by ggarra13** [comment]
El 7/12/21 a las 21:57, Albrecht Schlosser escribió:
>
>     Compiling it from scratch is another issue as it has many
>     dependencies.
>
> I didn't say that I wanted to build and test it, I'd rather ask you to 
> test again when we have something to test, but hopefully with the same 
> (i.e. archived) software version. I hope you don't mind and will 
> assist. TIA.
>
Sure.  As I mentioned in the other thread, I found the cause of the 
crash.  However if you later want to unify timeouts on all platforms, I 
can certainly use my program as testbed.
>

**Comment by ManoloFLTK** [comment]
@ggarra13 reports in fltk.coredev "Rare crash on repeat_timeout on macOS" that the
error was in the app, not in the FLTK library.

@Albrecht-S: Could you, please, reconsider your making of this issue a milestone
for FLTK 1.4.
