### ISSUE TITLE
Obnoxious compiler warnings about unused parameters in FLTK 1.4

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#307]
First, my build platform: CentOS Linux 6 with g++ 5.1 on Xeon-based workstation. (yes I know, old stuff)

I realize this is likely not a high priority for FLTK maintainers, but whenever I build my application code that includes certain FLTK 1.4 `.H` files, I see obnoxious warnings about unused parameters emanating from those `.H` files. Yes I can turn off these warnings with the suitable compiler flag (e.g., `-Wunused-parameter`), but then I don't have useful information about my own code's possible deficiencies.

FYI the way I deal with unused parameters or variables in my own code is the old-timey brute force approach: just insert the empty statement `(void)var-name;` somewhere in the appropriate method etc. This is benign even if later the parameter or variable actually does get used. I also do not think it affects run-time performance (maybe the compiler optimizes it out?), although I have never actually bothered to verify that simplistic assumption.

Please see if you can do something about these warnings.

Here are some of the offenders as recorded in the latest build of my app code:

- fltk/latest/include/FL/Fl_Image.H:78:33: warning: unused parameter ‘width’
- fltk/latest/include/FL/Fl_Image.H:78:45: warning: unused parameter ‘height’
- fltk/latest/include/FL/Fl_Graphics_Driver.H:376:64: warning: unused parameter ‘fnum’
- fltk/latest/include/FL/Fl_Image_Surface.H:106:45: warning: unused parameter ‘high_res’

Thank you.

**Comment by Albrecht-S** [comment]
Thanks for the report, you are right that "unused parameter" warnings don't have high priority for developers.

But I do also agree that it would be good to eliminate such warnings at least from user visible code (header files), i.e. we might want to "clean" at least those. A quick minimal test with `-Wunused-parameter' exhibits a relatively small number of files (6) and issues (35):
```
FL/Fl_File_Input.H:90:37: warning: unused parameter ‘c’ [-Wunused-parameter]
FL/Fl_File_Input.H: In member function ‘void Fl_File_Input::errorcolor(Fl_Color)’:
FL/Fl_Graphics_Driver.H:376:64: warning: unused parameter ‘fnum’ [-Wunused-parameter]
FL/Fl_Graphics_Driver.H: In member function ‘virtual PangoFontDescription* Fl_Graphics_Driver::pango_font_description(Fl_Font)’:
FL/Fl_Image.H:78:33: warning: unused parameter ‘width’ [-Wunused-parameter]
FL/Fl_Image.H:78:45: warning: unused parameter ‘height’ [-Wunused-parameter]
FL/Fl_Image.H: In member function ‘virtual void Fl_Image::cache_size_(int&, int&)’:
FL/Fl_Image_Surface.H:106:45: warning: unused parameter ‘high_res’ [-Wunused-parameter]
FL/Fl_Image_Surface.H: In constructor ‘Fl_Image_Surface_Driver::Fl_Image_Surface_Driver(int, int, int, Fl_Offscreen)’:
FL/Fl_Native_File_Chooser.H:190:37: warning: unused parameter ‘val’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:192:25: warning: unused parameter ‘t’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:194:28: warning: unused parameter ‘o’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:198:36: warning: unused parameter ‘i’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:199:38: warning: unused parameter ‘val’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:201:34: warning: unused parameter ‘t’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:204:35: warning: unused parameter ‘f’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:206:33: warning: unused parameter ‘i’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H:208:39: warning: unused parameter ‘f’ [-Wunused-parameter]
FL/Fl_Native_File_Chooser.H: In constructor ‘Fl_Native_File_Chooser_Driver::Fl_Native_File_Chooser_Driver(int)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual const char* Fl_Native_File_Chooser_Driver::filename(int) const’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::directory(const char*)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::filter(const char*)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::filter_value(int)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::options(int)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::preset_file(const char*)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::title(const char*)’:
FL/Fl_Native_File_Chooser.H: In member function ‘virtual void Fl_Native_File_Chooser_Driver::type(int)’:
FL/Fl_Table.H:385:39: warning: unused parameter ‘context’ [-Wunused-parameter]
FL/Fl_Table.H:385:52: warning: unused parameter ‘R’ [-Wunused-parameter]
FL/Fl_Table.H:385:61: warning: unused parameter ‘C’ [-Wunused-parameter]
FL/Fl_Table.H:386:30: warning: unused parameter ‘X’ [-Wunused-parameter]
FL/Fl_Table.H:386:39: warning: unused parameter ‘Y’ [-Wunused-parameter]
FL/Fl_Table.H:386:48: warning: unused parameter ‘W’ [-Wunused-parameter]
FL/Fl_Table.H:386:57: warning: unused parameter ‘H’ [-Wunused-parameter]
FL/Fl_Table.H: In member function ‘virtual void Fl_Table::draw_cell(Fl_Table::TableContext, int, int, int, int, int, int)’:
```
This seems to be doable but I can't tell if this list is complete.

However, this doesn't mean that this will be done soon.

**Comment by pdhahn** [comment]
Sure it makes complete sense that the priority is low, especially in light of the fact 1.4 is bleeding edge (I `git pull` the FLTK repo and rebuild at least nightly). I just wanted to get the issue onto the radar, so to speak. I do pay attention to things like this actually just because FLTK 1.4 is bleeding edge and I am of course therefore concerned about regressions. Note I am committed to 1.4 thanks to features, even though it is not yet formally stable (still hoping like many others it becomes so sooner than later!).

BTW, even though the list within the FLTK realm is relatively small, the frustration for me is that some of them show up over and over because the same header files are being imported into a significant number of my source files.

Anyway, in the meantime, I can implement some sort of `grep -v` in my make files to filter them out of the build logs.

**Comment by Albrecht-S** [comment]
> BTW, even though the list within the FLTK realm is relatively small, the frustration for me is that some of them show up over and over because the same header files are being imported into a significant number of my source files.

Yep, I've seen this as well, thus I used `grep` and `sort -u` to filter by filename. I can fully understand that this is a pain in your build environment.

I added this issue (although low priority) to the release milestone because I believe it's not much work to fix it.

**Comment by ManoloFLTK** [comment]
@pdhahn : please `git pull `the lastest FLTK source code and report if these warnings have all disappeared.

**Comment by pdhahn** [comment]
Yes, all fixed now. Thanks!

**Comment by Albrecht-S** [comment]
@pdhahn Great, thanks for feedback!

And thanks to @ManoloFLTK for fixing the warnings, of course.
