### ISSUE TITLE
RFE: change Fl_Scroll::fix_scrollbar_order() from private -> protected

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#308]
Classes deriving from `Fl_Scroll` need access to `fix_scrollbar_order()` to properly determine child widget size/placement based on scrollbar visibility, and that can only be done properly if the scrollbars are first in proper order.

`Fl_Scroll::recalc_scrollbars()` (protected) doesn't work properly unless the scrollbar order is correct, so unless the subclass can first fix the scrollbar order, it can't properly make use of this function.

An example case is the `test/pack` example, which would _like_ to make sure as children are added in such a way they are the full width of the inner area of the `Fl_Scroll`, which depends on whether the vertical scrollbar is visible.

The subclass can't trivially check a scrollbar's `visible()` flag, as their visibility isn't _actually_ calculated until the next `draw()`, too late for the subclass to properly predict widget placement. To do this properly, the subclass has to:

- Call `fix_scrollbar_order();`
- Call `ScrollInfo si; recalc_scrollbars(si);`
- Check `si.vneeded` to see if the vertical scrollbar will be visible
- Resize its children accordingly

Also, the subclass can't properly walk its own children with `child()` immediately after a new child has been `add()`ed unless `fix_scrollbar_order()` has been called: `Fl_Scroll::add()` does not readjust the scrollbar order, so newly added widgets can end up  _below_ the scrollbars in the `child()` array, and out of order.

Either this change, or a way for a subclass to force a recalc of scrollbar visibility and a `fix_scrollbar_order()` implied with that, without waiting for the next `draw()`.

**Comment by erco77** [comment]
This is a trivial fix, but looking for input before making the change, in case there's some reason not to change this method from private -> protected.

**Comment by Albrecht-S** [comment]
I don't see any reason not to make this method protected. Maybe there are more methods that are private and should be protected as well but I don't know. I'd appreciate if you could check this as well (at least for the most obvious methods that can be used in subclasses).

+1 on the proposed change.

**Comment by Albrecht-S** [comment]
Slightly OT but may be relevant: For some reasons we can't make `Fl_Group::add()` virtual which is a pity and precludes knowing when a widget has been added to a (derived) class as this might be useful for `Fl_Scroll` to check its scrollbars.

FLTK 1.4.0 will soon get a new mechanism (method) that will enable any class based on `Fl_Group` to detect when widgets are added or deleted. The details are not yet all that clear but it's a WIP because any kind of layout manager needs to know this.

`Fl_Grid` is one example that will utilize this new method. ;-)

**Comment by Albrecht-S** [comment]
> Classes deriving from Fl_Scrollbar need access ...

in the first message should probably read "... deriving from `Fl_Scroll` ..."

**Comment by erco77** [comment]
Fixed and closed.
