### ISSUE TITLE
Make test/checkers HighDPI friendly

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#31]
The piece images used by the test/checkers app are 62x62 pixels by size
and are drawn at 62x62 FLTK drawing units. While that's optimal for 96 DPI
displays, HighDPI systems are such that there is more than 1 pixel per
FLTK drawing unit. Larger piece images are necessary to have pieces optimally
drawn on HighDPI displays.

For example, on a macintosh with retina display, the checkers pieces are currently drawn
by blocks of 4 identically colored pixels.

If it was possible to construct twice larger images (that is, 124x124 instead of the present
62x62 for each piece image), that extra line in the source code would be enough
to get well-drawn pieces on HighDPI displays:
for (int i = 0; i < which; i++) png[i]->scale(png[i]->data_w()/2, png[i]->data_h()/2);
after line #880 of file test/checkers.cxx . That source code change would be
equally effective under X11, Windows and macOS.

That would also show the use of the new
Fl_Image::scale(int, int)
member function to improve support of HighDPI displays.

**Comment by MatthiasWM** [comment]
Hmm, this is a bit of work to make it run correctly, but probably worth it at some point. It could also be a nice example on how to use FLuid to add binary data from a .png file and then load it at runtime.

**Comment by MatthiasWM** [comment]
Wow, that was easy. Didn't know about Fl_Image::scale(int, int). Maybe whoever has the vector graphics could create better .png files? No need to create the .h files. Fluid takes care of that now.

**Comment by erco77** [comment]
Source wasn't vector; drawn with pixels in GIMP.
However one could scale the pieces up; gradients won't suffer from a 2x scale I don't think.
It just took a bit of effort to get it where it is now, I didn't feel like taking it further. But feel free; the source .xcf file is in test/pixmaps/checkers-pieces.xcf

**Comment by ManoloFLTK** [comment]
Support of HighDPI displays in FLTK 1.4 is achieved, for images, by 3 new member functions
Fl_Image::data_w() and data_h(), and Fl_Image::scale().

Class Fl_Image now contains two (width, height) pairs for each image :
1) Fl_Image::data_w() and data_h() give the image dimensions in pixels and are unmutable;
2) Fl_Image::w() and h() give the image drawing size in FLTK units.
They initially equal Fl_Image::data_w() and data_h().
Function Fl_Image::scale() allows to set the drawing size independently from
the raw data size.

When an image is drawn, an OS function is used to map the raw image pixels to the
display pixels present in the image area. Under X11, the XRender extension does that.

The intent is to keep its full pixel size to any image, and to set its drawing size independently,
so that all image pixels are available to fill the drawing area, even on a HighDPI display, 
a pdf file, or a laser printer.

**Comment by Albrecht-S** [comment]
> Source wasn't vector; drawn with pixels in GIMP.
However one could scale the pieces up; gradients won't suffer from a 2x scale I don't think.

@erco77 @ManoloFLTK FWIW, I tried to scale the (Gimp) image up by a factor of 2 in Gimp (which is essentially 2 x 2 = 4), but the images look blurry. I don't think that this would be a good solution although it would be fine, I think, if we had the images, as @ManoloFLTK suggested, in the larger size and could scale them down for normal displays.

Are there any better ideas to create or scale the images in / to the higher resolution?

**Comment by ManoloFLTK** [comment]
No better idea on my side.

**Comment by MatthiasWM** [comment]
Done: 84c0b7495b0859cce8b79fc6e4ceee19bc4f2f35

**Comment by ManoloFLTK** [comment]
@MatthiasWM Beautiful now on a retina display. Many thanks.

**Comment by Albrecht-S** [comment]
@MatthiasWM I wonder what exactly you did to make it more HiDPI friendly. I noticed that the images are a tiny bit smaller (112x112 rather than 124x124) but the actual (net) checker size is the same. They look "sharper" though.

I also noticed the nice new (slower) animation effect.

This is just for my own curiosity: how did you do this? And wouldn't we "need" twice the resolution to make it really HiDPI (Retina) friendly? Did I miss anything?

@erco77 @MatthiasWM Greg created the original images in `gimp` and we still have the original gimp image file `test/pixmaps/checkers-pieces.xcf`. Since this file is no longer adequate, should we remove it from the repo? I would say +1 to remove it.

**Comment by ManoloFLTK** [comment]
> This is just for my own curiosity:  wouldn't we "need" twice the resolution to make it really HiDPI (Retina) friendly? 

Consider line #877 of checkers.cxx
    `png[i]->scale(png[i]->data_w()/2, png[i]->data_h()/2);`
With it, the drawing size of each image is half its data size. The net result is 
perfectly sharp piece images on a retina display.

**Comment by Albrecht-S** [comment]
> Consider line #877 of checkers.cxx
png[i]->scale(png[i]->data_w()/2, png[i]->data_h()/2);

Oh, yes, I see, thanks, @ManoloFLTK. I missed the fact that we already had twice the size (the checkers are in reality only about 56x56). So I think the only relevant change was sharpening the existing images?

**Comment by MatthiasWM** [comment]
Just sharpening is not enough. The original image was doubled in size and blurred. The best solution is to vectorise the graphics, so they can be scaled arbitrarily. The rendered PNG is a little bit smaller because I had the shadow reduced in size to avoid some clipping artefacts. The shadow uses the alpha channel of the PNG.

But I can't take all the credit 😄. I always wanted to try out Fiverr and this was the perfectly defined job to do it. I think it worked out just fine.

@Albrecht-S The timer is not very smart. It uses Fl::wait() instead of the more correct timeout callback.

**Comment by Albrecht-S** [comment]
OK, so you paid for the job at https://www.fiverr.com ?

> The timer is not very smart. It uses Fl::wait() instead of the more correct timeout callback.

I saw this and I also got the impression that it worked a little different on my Mac and on Linux but I didn't pay too much attention to the differences.

**Remaining question** @erco77 (the author of the Gimp image) and @MatthiasWM (the person who changed the png's): shall we remove the Gimp image from the repo? I think it's no longer useful.

**Comment by MatthiasWM** [comment]
> OK, so you paid for the job at https://www.fiverr.com ?

Yes, but I made sure to make known that this is part of an OpenSource projects. Plus it wasn't expensive at all compared to the time I would have had to invest to draw this. 

> > The timer is not very smart. It uses Fl::wait() instead of the more correct timeout callback.
> 
> I saw this and I also got the impression that it worked a little different on my Mac and on Linux but I didn't pay too much attention to the differences.

Yes, it's different because other events may interrupt Fl::wait() sooner than the given time. I should probably fix that.

> **Remaining question** @erco77 (the author of the Gimp image) and @MatthiasWM (the person who changed the png's): shall we remove the Gimp image from the repo? I think it's no longer useful.

I think it makes sense to remove it. I would add the vector data, but it's 600kBytes times four files.

**Comment by erco77** [comment]
Yes, remove the gimp image if it's no longer the source for future work.
I'm guessing a vector image is a better source, so please include that instead.

**Comment by Albrecht-S** [comment]
Old image file removed in commit 8e42f772f54603f6341de629987b2d1ed1d9d0e8 as requested.

**Comment by Albrecht-S** [comment]
> Yes, it's different because other events may interrupt Fl::wait() sooner than the given time. I should probably fix that.

This would be a perfect case for the new cross-platform Fl_Timeout handling (although it should work now already, of course).

**Comment by Albrecht-S** [comment]
600 kBytes x 4 images is not very much but if it's considered too much you could upload it here and, provided that GitHub exists for some more time, we'd have them saved.

OTOH, Greg and I could put them on the FLTK server in a folder we'd have yet to specify (do we have an STR for this?) and then we'd have the files under our own control outside the repository.

**Comment by MatthiasWM** [comment]
Created and add my own pieces which I herewith put under the FLTK license.

**Comment by MatthiasWM** [comment]
Also added vector data for even higher DPI screen in the future.

**Comment by ManoloFLTK** [comment]
Are these vector data in SVG format? If so, checkers could read the vectorial files and adapt
automatically to any DPI.

**Comment by Albrecht-S** [comment]
Great, thanks for these new checker pieces, they're looking clear and pretty well.

However, if I had a wish free I'd wish that all the "shadow" and "light" effects point at the same direction. This was already an issue with the old checkers from Greg but maybe it's easier to change in your version?

If you look at the black checker the "light" seems to come from the NW side if you look at the outer part of the piece. However, the shadow in the inner part looks as if the light is in the NO corner. This makes the visual impression "wrong".

![black_checker](https://user-images.githubusercontent.com/26235500/151581656-5922b0a5-98eb-449a-9feb-a963ec551ea1.png)

My suggestion would be to make the "light" always be in the NW corner which is, IIRC, the "natural" view we are mostly used to, and thus the inner "shadow" should be on the NW side of the inner part as well. This would mean to turn the inner part by 45° counter-clockwise. The same would apply to the white checker.

But if it's too difficult, never mind, forget what I said. ;-)

**Comment by Albrecht-S** [comment]
@MatthiasWM :1st_place_medal: :+1: Awesome, thank you very much for commit 303e8de48397909751b32b0754257192f89ef7b0.

**Comment by MatthiasWM** [comment]
Changed the shading. 

Yes, it's an SVG. Nano SVG does not support the blurring of the shadow or the layers to generate all four pieces from on file.

**Comment by erco77** [comment]
Don't know if it's worth it, since it's "just a checkers game", but here's a fun thought:

If you really wanted to render the SVGs for full image scaling, then the shadow could be rendered as a PNG, and the detailed piece over that as an SVG.

Scaling the PNG should be fine, since all it would have is shadow information in its alpha channel, and therefore wouldn't suffer from scaling artifacts.
