### ISSUE TITLE
Fluid: new option for declaration

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#317]
We need an option for the first declaration(s) in a design to go in front of the `"#include <FL/Fl.H>"` that Fluid always generates in the header.

**Comment by Albrecht-S** [comment]
FWIW, here's a short test case for reference:
```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {.h}
code_name {.cxx}
decl {\#define FLTK_HAVE_CAIRO 1} {
  comment {Example for Cairo or something else.
Must be before \#include <FL/Fl.H>} public local
}

decl {\#include <my_config.h>} {
  comment {User defined config header before \#include <FL/Fl.H>} public global
}

decl {\#include <FL/Fl_Box.H>} {
  comment {normal header inclusion} public global
}
```

**Comment by MatthiasWM** [comment]
I solved this differently: projects now have the option "avoid early include of FL.H". This will simply not emit the "#include <FL/Fl.H>" at the beginning of the header, so that other declarations can be write first. However, if the first FLTK widget is written, "#include <FL/Fl.H>" is emitted right before the include statement for that particular widget.

See #363.

**Comment by Albrecht-S** [comment]
My test case above does not include `<FL/Fl.H>` (if I activate the new option) although it includes `<FL/Fl_Box.H>` which seems to be a border case because it's included implicitly and not by a widget declaration.

How should this be handled?

**Comment by MatthiasWM** [comment]
If you include something explicitly, you need to also include explicitly all its dependencies. However, if you include an Fl_Box widget in your design, Fluid will include both Fl.H and Fl_Box.H in the correct order. See fluid/about_panel.fl

**Comment by Albrecht-S** [comment]
OK, that's plausible.

**Comment by MatthiasWM** [comment]
Thanks. The default setting remains as it was anyway. I don't want to disturb existing projects. I am trying to implement CI/CD for Einstein and I can see how tiny changes break everything.
