### ISSUE TITLE
Enable more g++ warning flags

### ISSUE THREAD

**Issue by psyomn** [fltk/fltk#32]
I was wondering if it would be appreciated if there was an effort to add some warning flags (eg: `-Wswitch-enum`, and more).

I'm willing to do some work to resolve some of these flags; let me know!

**Comment by Albrecht-S** [comment]
Thanks for the offer.

I don't think though that we need to "support" any specific warning flags in our build environment. Users can always _add their own flags_ when building FLTK with both build systems supported by us (autoconf/make and CMake), for instance by setting environment variables CXXFLAGS, LDFLAGS, etc.

Am I missing anything, are there other reasons I didn't see?

**Comment by psyomn** [comment]
Nope, thanks for the reply! This answers my question.

**Comment by erco77** [comment]
Just want to check on the goal of the request, to make sure we aren't missing out on something.

Was the goal to just allow end users to influence build flags, and this is served by specifying e.g. CXXFLAGS?

Or is it to add specific new compiler warning flags that we should be using to ensure future FLTK development doesn't trip on code problems these new flags would prevent, but are flags that -Wall does not currently support? And if so, is the OP offering to provide some kind of mechanism that only enables such flags if the compile time g++ compiler environment supports them, and are not already enabled by -Wall?

If the latter, that might be interesting, though I would imagine our existing use of -Wall would cover this.. not sure.

Certainly I can say that when we used to compile on SGIs, the SGI compiler would catch many problems that gnu did not, and I imagine now that we also support clang, it similarly catches other problems gnu doesn't, and having such features /is/ useful.

Anyway, just checking if we're not missing something that might be good to add..

**Comment by psyomn** [comment]
> Or is it to add specific new compiler warning flags that we should be using to ensure future FLTK development doesn't trip on code problems these new flags would prevent, but are flags that -Wall does not currently support? 

This was my original concern, but also wanted to give myself a "good first issue" so I could start learning the `fltk` code base. I figured that enabling a flag like `-Wold-style-cast`, or other small (perhaps benign) flags like this, could create a small task to get familiar with the code base.

**Comment by erco77** [comment]
If you'd like to familiarize yourself with the code base, feel free to try fixing bugs in the bug list: https://www.fltk.org/str.php
Some are pretty challenging, but some might be easy.

**Comment by Albrecht-S** [comment]
> I figured that enabling a flag like -Wold-style-cast, or other small (perhaps benign) flags like this, could create a small task to get familiar with the code base.

@psyomn - Regarding the flag mentioned above: please note that we're using old style casts intentionally. Our code base is targeted at pretty old compilers, hence we don't use more modern C++ features.

Before you familiarize yourself with the FLTK code base you might want to take a look at our [Configuration Management Plan](https://www.fltk.org/cmp.php), particularly at the chapter [General Coding style](https://www.fltk.org/cmp.php#CODING_STANDARDS).

**Comment by psyomn** [comment]
Thanks!
