### ISSUE TITLE
Disabling IM disables Greek and Cyrillic layouts on macOS

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#325]
If you call `Fl::disable_im()` on macOS then you disable not just layouts that use input methods, but all non-Latin layouts. This means that layouts such as Greek and Russian also get disabled, which is not what is desired.

The reason for this is because this was the easiest way to disable input methods on macOS, and it is also what other software such as Firefox and Chrome do for things like password fields. That doesn't make it correct though.

Downstream bug reports:

https://github.com/TigerVNC/tigervnc/issues/1396
https://www.cendio.com/bugzilla/show_bug.cgi?id=5272

The latter has a patch for the issue, but isn't fully tested.

**Comment by ManoloFLTK** [comment]
@CendioOssman : Thanks for the proposed fix. It's now committed to the git repo for the main branch which will soon become FLTK 1.4. Can you confirm it's OK for you?

**Comment by CendioOssman** [comment]
I'm afraid we're a bit too swamped right now. But I figured it was still worthwhile to mention we had a suggestion for this in case some one else has time for testing. :)

**Comment by ManoloFLTK** [comment]
The fix is now also committed to branch 1.3
