### ISSUE TITLE
Feature suggestion: functions to read BMP and GIF images from array

### ISSUE THREAD

**Issue by usrshare** [fltk/fltk#33]
While the constructors for `Fl_JPEG_Image` and `Fl_PNG_Image` helpfully allow the developer to load the image data from an array, there is no similar functionality for `Fl_GIF_Image` and `Fl_BMP_Image`.

This functionality would be useful in cases where, for example, the image you want to load is actually part of an archive that's dealt with by a third-party library like libzip, or an even simpler case of the image being compiled into a constant array in the program's source code.

**Comment by Albrecht-S** [comment]
Thanks for this proposal, we'll look into it when time permits.

**Comment by MatthiasWM** [comment]
Implemented.
