### ISSUE TITLE
Fluid: compiler warnings

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#340]
```
Compiling Fl_Type.cxx...
Fl_Type.cxx: In member function ‘void Fl_Type::add(Fl_Type*, Strategy)’:
Fl_Type.cxx:402:12: warning: unused variable ‘a’ [-Wunused-variable]
  402 |   Fl_Type *a = p;
      |            ^
Fl_Type.cxx: In member function ‘void Fl_Type::insert(Fl_Type*)’:
Fl_Type.cxx:436:12: warning: unused variable ‘a’ [-Wunused-variable]
  436 |   Fl_Type *a = prev;
      |            ^
```

I could have fixed this myself by just removing the offending statements but the comments above these statements made me hesitate. Is there anything missing or what do the comments mean?
```
  // run the p tree a last time to make sure the widget_browser updates correctly
  Fl_Type *a = p;
```

@MatthiasWM Can you please take a look?

**Comment by MatthiasWM** [comment]
Thanks, those were leftovers from previous code that was replaced by one short function call. I have to find a way to tell CMake to be much more strict with warnings in Xcode!
