### ISSUE TITLE
Fluid: separate system settings (global and user) to another program

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#349]
Fluid is a developer tool and the menu
- Edit
- .. Global FLTK Settings

should be accessible to users and system admins w/o having to use such a developer tool.

AFAICT we added these global and user system preferences to fluid because we needed a quick solution for all the new `Fl::option()` settings.

I propose to add a new tool that users can use to set their own preferences and system admins can use to set the system preferences (maybe only once at installation time).

I propose the name "`flups`" for "`FL`TK `U`ser `P`reference`s`" but I'm asking for opinions and better proposals.

- Shall we add such a tool?
- Which name should that tool have?
- Does anybody know of conflicts with other (Unix/Linux) tool names if we used `flups` or any other proposal?

**Comment by MatthiasWM** [comment]
- + 1 👍 on adding that tool
 - other name option is Floss (FLTK operational system settings), Flux (FLTK User eXperience is probably taken)

**Comment by ManoloFLTK** [comment]
+1 to separate the control of FLTK options from fluid.
This tool would control what the API calls  [Fl::Option](https://fltk.gitlab.io/fltk/classFl.html#a43e6e0bbbc03cad134d928d4edd48d1d). Its name should be based on "option",
possibly `floptions`.

**Comment by MatthiasWM** [comment]
I have made a PR #560 for this.

**Comment by MatthiasWM** [comment]
About to close #560

**Comment by erco77** [comment]
Late to the party, yeah +1 for floptions and not flups.

We have to keep in mind that executables like fltk-config, fluid, etc. are going to be part of the linux distributions appearing in their bin directories, and therefore in all user's PATH when installed, so we want to play nice with the rest of the world's executable names.

**Comment by MatthiasWM** [comment]
2 minutes after the merge ;-) . Anyway, it's `fltk-options` by majority vote.

**Comment by erco77** [comment]
Oh, well that's good too!
