### ISSUE TITLE
Windows Y location not updating

### ISSUE THREAD

**Issue by mdblack98** [fltk/fltk#354]
Using github checkout as of 20211222
Windows 11 Y location when monitor is above the other does not record the correct Y location.
X location when monitors are side-by-side works...but not Y when in vertical orientation.  When in vertical (non-extended) neither X nor Y are updated.

**Comment by Albrecht-S** [comment]
Thanks for the report.

You wrote "Windows 11". Can you compare thist with Windows 10, does it work with Windows 10 in this monitor configuration?

What do you mean with "vertical (non-extended)", and what means "neither X nor Y are updated"? Please explain what you are doing and what you see.

What does the demo program test/fullscreen show when you start it?

**Comment by mdblack98** [comment]
Can't compare with Windows 10 right now but was running the same monitor config then and I'm quite sure it did not have the problem.
It's an application called FlRig from herehttp://www.w1hkj.com/alpha/flrig/

It does, of course, save it's screen location on exiting the program.  When FLRig is on the other monitor the X/Y locations saved do not change.
I think the problem is due to the fact that I have Monitor#1 on the top and Monitor#2 on the bottom so the Y coordinates go negative.
Both screens are 2560x1440
So fullscreen on the bottom monitor shows this
And on the upper monitor shows this

Mike
 

    On Wednesday, December 22, 2021, 04:01:21 PM CST, Albrecht Schlosser ***@***.***> wrote:  
 
 


Thanks for the report.

You wrote "Windows 11". Can you compare thist with Windows 10, does it work with Windows 10 in this monitor configuration?

What do you mean with "vertical (non-extended)", and what means "neither X nor Y are updated"? Please explain what you are doing and what you see.

What does the demo program test/fullscreen show when you start it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mdblack98** [comment]
I added a screenshot to the github issue.
Mike

 

    On Wednesday, December 22, 2021, 05:35:23 PM CST, Michael Black ***@***.***> wrote:  
 
 

Can't compare with Windows 10 right now but was running the same monitor config then and I'm quite sure it did not have the problem.
It's an application called FlRig from herehttp://www.w1hkj.com/alpha/flrig/

It does, of course, save it's screen location on exiting the program.  When FLRig is on the other monitor the X/Y locations saved do not change.
I think the problem is due to the fact that I have Monitor#1 on the top and Monitor#2 on the bottom so the Y coordinates go negative.
Both screens are 2560x1440
So fullscreen on the bottom monitor shows this
And on the upper monitor shows this

Mike
 

 On Wednesday, December 22, 2021, 04:01:21 PM CST, Albrecht Schlosser ***@***.***> wrote: 
 
 


Thanks for the report.

You wrote "Windows 11". Can you compare thist with Windows 10, does it work with Windows 10 in this monitor configuration?

What do you mean with "vertical (non-extended)", and what means "neither X nor Y are updated"? Please explain what you are doing and what you see.

What does the demo program test/fullscreen show when you start it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Albrecht-S** [comment]
@mdblack98 Can you please compile and run the attached program [screen.cxx](https://github.com/fltk/fltk/files/7766152/screen.cxx.txt) and report what you see?

If you have problems compiling it under Win11 you can copy its content into one of the demo programs, e.g. `hello.cxx` and build the FLTK library or only that program.

- Please run the program, move it across your screens, and watch the displayed message. If you see anything suspicious, please click the "Copy" button and paste the text here.

- When you press the "Quit" button you'll see a message with the current main window coordinates. Is this message correct?

If this program works as expected the failure must be somewhere else (not in FLTK), otherwise we can investigate further.

Example output on my (Linux) system with only one monitor:
```
Window at (  412,   347)
on screen 0

number of screens = 1
screen 0: (    0,     0,  1920,  1080)
```

PS: the screenshot you posted looks correct according to your description of your setup. I there anything wrong with it?

**Comment by mdblack98** [comment]
So my monitors are like this:12And I have 2 as my main monitor
When the program is on monitor 1 it shows negative numbesr for the y axis.Same thing happens to the x axis when monitors are side-by-side1 2 -- and 2 is the main monitorOn monitor 1 we get negative x numbers


I assume negative coordinates are causing the problem.
Mike
 

    On Wednesday, December 22, 2021, 07:59:30 PM CST, Albrecht Schlosser ***@***.***> wrote:  
 
 


@mdblack98 Can you please compile and run the attached program screen.cxx and report what you see?

If you have problems compiling it under Win11 you can copy its content into one of the demo programs, e.g. hello.cxx and build the FLTK library or only that program.
   
   -    
Please run the program, move it across your screens, and watch the displayed message. If you see anything suspicious, please click the "Copy" button and paste the text here.

   -    
When you press the "Quit" button you'll see a message with the current main window coordinates. Is this message correct?


If this program works as expected the failure must be somewhere else (not in FLTK), otherwise we can investigate further.

Example output on my (Linux) system with only one monitor:
Window at (  412,   347)
on screen 0

number of screens = 1
screen 0: (    0,     0,  1920,  1080)

PS: the screenshot you posted looks correct according to your description of your setup. I there anything wrong with it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mdblack98** [comment]
I found the problem in the FLRig code -- it was checking for X/Y to be > 0.
Thanks for the help.
