### ISSUE TITLE
Fl_Text_Display proposal: set background colors for each line

### ISSUE THREAD

**Issue by ZJUGKC** [fltk/fltk#355]
A proposal: add a function which can set background colors for each line and render them in Fl_Text_Display. So the effect of code difference like GITHUB commits can be implemented.

**Comment by MatthiasWM** [comment]
This should be possible. I have some spare time after the 28th and should be able to implement this, as I also have a use for this feature in Fluid. But of course, if anyone else feels like implementing this: please assign it to yourself ;-)

**Comment by Albrecht-S** [comment]
Related STR's:
- [STR 2838](https://www.fltk.org/str.php?L2838): Add Colors to FL_Text_Display (+ underscore + strikethru)
- [STR 3453](https://www.fltk.org/str.php?L3453): Fl_Text_Display: Highlight current line (Patch)
- [STR 3277](https://www.fltk.org/str.php?L3277): Fl_Text_Display virtual method

Some of these STR's include patches but these are probably outdated.

**Comment by MatthiasWM** [comment]
The changes in #378 add the option to set the background color for style. This is a bit different from setting on a per line base, but seems to be more universal without requiring a completely new data structure.

STR 2838: implementing strike through, underscore, and undersquiggle would also be pretty easy.

STR 3453: highlighting the cursor line can easily be done with the secondary selection

STR 3277: this is pretty much what I implemented. We can still make Fl_Text_Display::draw_string() virtual. Any opinions on that?

**Comment by Albrecht-S** [comment]
> STR 3277... make Fl_Text_Display::draw_string() virtual. Any opinions on that?

The original question in STR 3277, comment 1 and 2 was: make the method virtual **or** add a background color feature. Since the latter is done I think that we don't need the virtual method.

I would tend to close this issue (label "wontfix") together with STR 3277 ("resolved"). Setting the line background color as suggested here would conflict with the per-character setting implemented now and would need (as said) a complete new data structure. But the most important point seems to be the conflict with per-character setting.

**Comment by Albrecht-S** [comment]
> STR 3453: highlighting the cursor line can easily be done with the secondary selection

@MatthiasWM What does this mean? Should the user do this, or would it be done somehow internally? I just don't understand what you mean with "can easily be done".

The patch given in STR 3453 looks pretty straight-forward and not too complicated. The only issue I saw looking at it was that some public methods would take `bool` arguments. We should stay with `int` for compatibility. The patch might be outdated though but I think it could be used unless _"can easily be done"_ means that there is a better way?

**Comment by Albrecht-S** [comment]
> STR 2838: implementing strike through, underscore, and undersquiggle would also be pretty easy.

@MatthiasWM I believe "strike through" and "underscore" (as requested) are interesting features. I wouldn't make it too complicated and add "undersquiggle".

This should be doable without yet another drawing pass. `Fl_Text_Display` is sometimes slow anyway so we shouldn't make it even slower if possible.

**Comment by MatthiasWM** [comment]
> > STR 3453: highlighting the cursor line can easily be done with the secondary selection
> 
> @MatthiasWM What does this mean? Should the user do this, or would it be done somehow internally? 

Fl_Text_Buffer has not only a `selection` range but also a `highlight` range: https://www.fltk.org/doc-1.4/classFl__Text__Buffer.html#ab53392af0a3ba98312f230dd40ed5fb9 and a `secondary_selection`. So changing the background of a single line that contains the cursor, as suggested in the STR, can easily be achieved by the user by adding this (pseudo)code to the text change callback:
```
myBuffer->highlight(myBuffer->line_start(crsrPos),  myBuffer->line_end(crsrPos));
```

**Comment by Albrecht-S** [comment]
> changing the background of a single line that contains the cursor, as suggested in the STR, can easily be achieved by the user by adding this (pseudo)code to the text change callback

Two questions:

1. Wouldn't that be a little too complicated?
2. What if the text is not changed but the cursor is moved? "text change callback" doesn't sound like this covers cursor movement.

I believe users would be asking for a simple function to be switched on and off by a call to an `Fl_Text_Display` method like activating line numbering and wrap mode. Setting the "_cursor line highlight (background) color_" would also be useful and acceptable. But setting a highlight range like proposed above appears over-complicated.

But what am I saying? You are the `Fl_Text_Display` expert. ;-)

**Comment by erco77** [comment]
+1 for undersquiggle in Fl_Text_Editor, if it's not too hard to add.

There's a few times where I'd have wanted to use it.

Certainly its evolved from being used for just highlighting misspelled words, and is now often used in IDE contexts to highlight syntactical errors, when the editor is smart enough to detect such things. Just be sure to allow its color to be set, and respond properly to highlighting.

**Comment by Albrecht-S** [comment]
> +1 for undersquiggle in Fl_Text_Editor, if it's not too hard to add.

I'm fine with this if it's really requested (and this is a real request). So ...

+1 from me as well.

**Comment by MatthiasWM** [comment]
Current pull request now features underline, strike through, and red and blue dotted underlines.

**Comment by MatthiasWM** [comment]
@ZJUGKC thanks for the request. I implemented background colors on a pre-style base instead. I believe that this is more versatile, and it also fixes two other STRs. Most of what line highlighting would do can also be implemented with this feature. The fix also adds underlining and strike through.
