### ISSUE TITLE
Release 1.3.8 is missing a git tag

### ISSUE THREAD

**Issue by OPNA2608** [fltk/fltk#357]
FLTK 1.3.8 was released a month ago: https://www.fltk.org/articles.php?L1782

However, unlike with previous releases, no git tag was created for it.

![Bildschirmfoto von 2021-12-23 13-14-19](https://user-images.githubusercontent.com/23431373/147239224-a30a0cd1-595f-4cc0-93f7-67207ce1a1f2.png)

**Comment by Albrecht-S** [comment]
Thanks, I created the tag but forgot to push it. Done now.
