### ISSUE TITLE
RFE for Fl_Input_Choice: ability to customize Fl_Input vs. Fl_Menu_Button positions and sizes via subclassing

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#361]
Currently `Fl_Input_Choice` doesn't support swapping the input and menubutton's positions, and doesn't make it easy to even derive a subclass because the methods used for resizing (`inp_{xywh}()` and `menu_{xywh}()`) are private and non-virtual.

Suggest making these methods virtual so they can be overridden by a subclass to redefine positioning behavior.

And also, a new convenience method to swap the positions, e.g. `input_align(FL_ALIGN_LEFT|RIGHT)`, as that would be the most common reason to want to redefine positioning.

**Comment by erco77** [comment]
Attaching [issue_361_v1.patch.txt](https://github.com/fltk/fltk/files/7830396/issue_361_v1.patch.txt) which does what's suggested above.

Here's a [newchoice.cxx.txt](https://github.com/fltk/fltk/files/7830420/newchoice.cxx.txt)  that creates two instances of `Fl_Input_Choice`; one with the input field left aligned (default), one right aligned. That can be dropped into the `./examples `directory and easily built+run with `make newchoice && ./newchoice`

The resulting screenshot being:
![issue_361_screenshot](https://user-images.githubusercontent.com/6484779/148585175-bc857051-9589-4a96-8740-25b764cf4f89.png)

**Comment by Albrecht-S** [comment]
Hmm, I think the original question in [fltk.general](https://groups.google.com/g/fltkgeneral/c/itgqHHUuCZI/m/KW3gcLkuBAAJ) (thread "Fl_Input_Choice dropdown bellow text") was about changing the location where the dropdown appears rather than swapping the input field and dropdown button positions.

The OP asked: _"The Fl_Input_Choice shows the dropdown on the right, is it possible to show it at the left with the right side aligned with the right of the dropdown button?"_

Although the questions appears to be somewhat ambiguous I think what the OP wanted to achieve is something like the following ASCII graphics:

Current behavior:
```
+------------+---+
| one        | v |
+------------+---+
             +---------+
             | one     |
             | two     |
             | three   |
             +---------+
```

Requested behavior:
```
+------------+---+
| one        | v |
+------------+---+
       +---------+
       | one     |
       | two     |
       | three   |
       +---------+
```

This layout was taken from `test/input_choice.cxx`.

**Comment by Albrecht-S** [comment]
Your patch and screenshot above appeared while I was writing the comment above. This could certainly be another useful option - although I would think the dropdown button should always be on the rigt side of the input widget.

**Comment by MatthiasWM** [comment]
> On 7. Jan 2022, at 18:54, Albrecht Schlosser ***@***.***> wrote:
> 
> 
> Hmm, I think the original question in fltk.general (thread "Fl_Input_Choice dropdown bellow text") was about changing the location where the dropdown appears rather than swapping the input field and dropdown button positions.

Yes, that's ho I understood it too.

> 
> 
> Current behavior:
> 
> +------------+---+
> | one        | v |
> +------------+---+
>              +---------+
>              | one     |
>              | two     |
>              | three   |
>              +---------+
> 
> Requested behavior:
> 
> +------------+---+
> | one        | v |
> +------------+---+
>        +---------+
>        | one     |
>        | two     |
>        | three   |
>        +---------+
> 
> This layout was taken from test/input_choice.cxx.

I would like to suggest this, no need to move the arrow-down button to the left as described here:
https://github.com/fltk/fltk/issues/361#issuecomment-1007605539


> +------------+---+
> | one        | v |
> +------------+---+
> +----------------+
> | one            |
> | two            |
> | three          |
> +----------------+

**Comment by erco77** [comment]
Ah, OK, guess I misread the OP's intention. We can forget my patch then, as I'm not sure I could see why anyone would actually want that, looking at the results.

Perhaps tho, at least making the internal `inp_xywh()` and `menu_xywh()` methods virtual and protected might be a good idea just to allow control over those from a subclass.

**Comment by MatthiasWM** [comment]
> On 7. Jan 2022, at 19:07, erco77 ***@***.***> wrote:

> Perhaps tho, at least making the internal inp_xywh() and menu_xywh() methods virtual and protected might be a good idea just to allow control over those from a subclass.

I see no harm in that. ABI is changing though.

 - Matthias

**Comment by erco77** [comment]
What the OP is requesting, then, I think would be a modification to Fl_Menu_Button.

I seem to recall when I implemented Fl_Input_Choice all those years ago, before I was an FLTK dev, that the OP's described behavior would have been what I wanted, but the Fl_Menu_Button didn't work that way, and not being a dev, I had no control over that.

Not sure if I'm the right person to make such changes to `Fl_Menu_Button`, as I'm not very familiar with the FLTK menu internals at that low a level.

**Comment by erco77** [comment]
@MatthiasWM regarding ABI changes, right, though we're in a good position to break ABI with 1.4.

Of course we also have a way to make ABI breaking mods in maintenance releases using the FL_ABI_VERSION stuff, which we don't need for 1.4.0, but worked well in the 1.3.x maintenance series, where the user could optionally enable ABI breaking features.

**Comment by Albrecht-S** [comment]
While I'm looking at the old and new behavior described by me above I wonder whether the suggested part in "Requested behavior" should not be the default behavior anyway. I looks more like the "natural" appearance one would expect and I believe we could change this as a "bug fix" (maybe nobody except the OP would notice the change).

> Perhaps tho, at least making the internal inp_xywh() and menu_xywh() methods virtual and protected might be a good idea just to allow control over those from a subclass.

:+1: on this enhancement.

@MatthiasWM : ABI changes are OK right now before 1.4 gets released, hence I suggest to do this quickly.

> Not sure if I'm the right person to make such changes to Fl_Menu_Button, as I'm not very familiar with the FLTK menu internals at that low a level.

@erco77 If you don't feel comfortable with changing this, then I believe we all agree that your patch regarding the virtual methods would be fine and you could commit that part.

I'm not sure how exactly changing the popup position would be done, but maybe @MatthiasWM has an idea (Matthias, I believe you know that code better than Greg and me?).

**Comment by Albrecht-S** [comment]
> ... make ABI breaking mods in maintenance releases using the FL_ABI_VERSION stuff, which we don't need for 1.4.0, ...

Correct, but this will be kept in place so we can make ABI breaking changes in 1.4.1 and later. ;-)

**Comment by Albrecht-S** [comment]
OK, summing the discussions up, I believe we could:

- change the title of this issue to "RFE for Fl_Input_Choice: ability to **~swap+~** customize Fl_Input vs. Fl_Menu_Button positions **and sizes**
- open a new issue regarding the request in fltk.general
- commit Greg's patch, modified w/o the alignment stuff
- close this issue when done

**Comment by erco77** [comment]
I just looked at Fl_Menu_Button's code -- it's pretty simple, so I'll at least take a shot at it I guess.. all were talking about I think is just changing the x,y position for the appearance of the menu, and to right align it would mean determining the menu's width, which if that's not too hard, might be easy.
Where it could get complicated as you say, if the menu has to move due to proximity to the screen edges. I'm not even sure if there's further implications for that in the context of a multi-screen environment.

**Comment by erco77** [comment]
@Albrecht-S OK, just seeing your comment.
Sure, I can change the title and just apply my revised patch, and we can make the menubutton change a separate issue.

**Comment by erco77** [comment]
First I want to make sure I can create a subclass in user code and see if I can redefine the positioning, to make sure this works as expected.

**Comment by MatthiasWM** [comment]
> On 7. Jan 2022, at 19:15, Albrecht Schlosser ***@***.***> wrote:
> 
> I'm not sure how exactly changing the popup position would be done, but maybe @MatthiasWM has an idea (Matthias, I believe you know that code better than Greg and me?).

Should be easy. Fl_Choice does it already. But I'll be happy to look at a Pullrequest or patch ;-)

**Comment by erco77** [comment]
Hmm, in testing the virtual methods, I ran into the apparently [well known problem of calling virtuals in a constructor](https://stackoverflow.com/questions/962132/calling-virtual-functions-inside-constructors), where in C++ apparently the subclass's methods can NOT called from the base class's ctor. Something about the vtable not being initialized yet or some such.

And in the case of Fl_Input_Choice, the base class _does_ call these methods, so the subclass implementations aren't called, causing the default behavior to appear unless the widget is resized.

The apparently easy solution is to simply call resize() in the _subclass's_ constructor, which triggers the subclass implementations, as the vtable is by then valid (or something). So that'd have to be a warning note to folks subclassing. I guess I'll include example code in the Fl_Input_Choice docs.

**Comment by erco77** [comment]
I'll create the separate issue, assign to myself, and see if I can figure it out.
If not, I'll unassign it and leave it open.

**Comment by MatthiasWM** [comment]
> On 7. Jan 2022, at 20:04, erco77 ***@***.***> wrote:
> 
> 
> Hmm, in testing the virtual methods, I ran into the apparently well known problem of calling virtuals in a constructor, where in C++ apparently the subclass's methods can NOT called from the base class's ctor. Something about the vtable not being initialized yet or some such.

Well, you can't call a virtual function of a derived class from within the constructor of the base class because the constructor of the derived class has not yet been called. 

But you can call the function either from the constructor of the derived class, or you can explicitly call a virtual function of the same or a super class.

You can PM me the code if you like.

 - Matthias

**Comment by erco77** [comment]
@MatthiasWM right, hence the call to resize() in the subclass ctor which triggers the new methods.

So here's the new patch proposal, 
[issue_361_v2.patch.txt](https://github.com/fltk/fltk/files/7832106/issue_361_v2.patch.txt)
, to address changing the inp_xywh / menu_xywh methods from `private/inline` to `protected/virtual`. The patch includes doxygen docs for the methods, as well as a subclassing example that demonstrates (for example) swapping the button and input fields.

One can then copy/paste the doxygen example and build a working program that demonstrates the swap. If that looks good I'll commit + close.

**Comment by Albrecht-S** [comment]
:+1: +1 Patch looks good and works well (tested under Linux, including example code).

`<nitpicking>` Copyright year (2022) should be adjusted in both files. `</nitpicking>`

**Comment by erco77** [comment]
I didn't apply the copyright fix because aren't copyright tweaks done as one big commit before a release?

**Comment by Albrecht-S** [comment]
> ... aren't copyright tweaks done as one big commit before a release?

IIRC there was never a rule to do this and in the recent past we changed the copyright with each file update. Doing so would always reflect the last year of a change.

Since Git tracks all changes doing bulk copyright updates for /all/ files would unnecessarily show a change without any functional changes which I personally would like to avoid, hence the copyright (year) change with every change.

This could (should?) be discussed and eventually documented in the CMP...
