### ISSUE TITLE
Fl_Table constructor does not end with `Fl_Group::end();`

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#364]
```Fl_Table.cxx:191:  table->begin();               // leave with fltk children getting added to the scroll```

The Fl_Table constructor ends in auto-adding further widgets as children. This is formally correct because Fl_Table is derived from Fl_Group, but IMHO it is unexpected behaviour. By default, Fl_Table is not used as a Group, but by adding Text Strings.

I would expect that further widgets either show up on the same level as Table, or they would appear inside the table, filling the cells one-by-one. 

RFC is:
1: behaviour one, calls this->end();
2: behaviour two: change what happened when adding children
3: don't change anything to keep compatibility

**Comment by erco77** [comment]
This is by design; Fl_Table can be used as a container; see test/table-as-container

**Comment by Albrecht-S** [comment]
Since Fl_Table is an Fl_Group it should behave like Fl_Group. You can always call `table->end()` if you want to change it in a user program. Changing this behavior would have potential to break user programs.

I vote for option 3 unless there are really, really compelling reasons to change this.

**Comment by erco77** [comment]
I should add, one doesn't really use Fl_Table by "adding text strings" either.

When Fl_Table isn't being used as a widget container, it's the "view" and "controller" part of a [Model/View/Controller](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) design. The user handles the "model", e.g. strings or images, or whatever data is supposed to be displayed in the table. This allows Fl_Table to be unconcerned with the amount of data the user has (memory management, etc) or how to efficiently store large amounts of data -- the user controls all that.

Fl_Table handles keeping track of where the table cells are (xywh of each cell) in the context of scrolling and row/col resizing, and tells the user where and when to draw each cell's content ("view"), and manages keyboard/mouse interaction for scrolling, cell clicks, interactive row/col resizing ("controller"), and the user is told where and when to draw each cell given a `row, col, and xywh` for the content.

So `Fl_Table` can be used two ways; as an MVC, or as a widget container. There might be other ways to use it too that I'm not aware of. One clever use involves a mixture of the two, using it as an MVC, and then when someone clicks on a cell, a widget appears there to let the user type in a new value, then makes it disappear after the user hits enter. The `test/table-spreadsheet-with-keyboard-nav` is a good example of that.

So for the RFC, my two cents: we have to be careful what we change; Fl_Table supports a lot of modes, and users have built existing apps around these different designs.

**Comment by MatthiasWM** [comment]
Hi Erco, didn't mean to oversimplify the widget. I know that you put a lot of work in to make the table be able to handle huge data sets ;-) . We'll leave it as it is. I'll check if Fluid behaves well, because it's not under Group widgets... .

**Comment by erco77** [comment]
@MatthiasWM No problem -- I know Fl_Table is kinda confusing at first to everyone.
Model/View is a powerful optimizing technique, but is often not what people expect.
