### ISSUE TITLE
Fluid sometimes doesn't remove widgets in groups from display

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#367]
While playing with fluid I noticed that fluid didn't remove a button from the display when I deleted the button. This small .fl file can be used as a reproducer:
```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {.h}
code_name {.cxx}
Function {make_window()} {open
} {
  Fl_Window {} {
    label {Button in Group} open selected
    xywh {737 117 300 220} type Double resizable
    code0 {w->resizable(g);} visible
  } {
    Fl_Group g {
      label group open
      xywh {25 35 260 85} box THIN_UP_FRAME resizable
    } {
      Fl_Button {} {
        label {button in group}
        xywh {50 50 210 45}
      }
    }
    Fl_Button {} {
      label {button in window}
      xywh {55 140 210 50} down_box DOWN_BOX color 142
    }
  }
}
```

1. Select "button in window", delete it, and it is immediately removed from the display.
2. Select "button in group", delete it, and it stays on the display.

The obvious difference is that the group has a "frame" border type (`THIN_UP_FRAME`) and I know that this behavior would be the same "in real life" but I'm wondering if fluid couldn't do it better.

I also tried `FL_NO_BOX` and noticed that the button disappeared immediately, hence I suspect there must be something more complex going on. The display is redrawn when you resize the window (as expected), hence users would be able to refresh the display manually as a workaround.

I wouldn't say this is definitely a bug, but it's unexpected and at least confusing.

**Comment by MatthiasWM** [comment]
I changed widget deletion to use Fl::delete_widget() and added a redraw for the enclosing window. Unless no background at all is set anywhere, this should work.

**Comment by Albrecht-S** [comment]
I suggest not to use `Fl::delete_widget()`. This has been introduced to work around some bugs in FLTK (I know that you know which ones) and I consider `Fl::delete_widget()` obsolete - we should IMHO deprecate it in FLTK 1.4. Therefore we should not use it in FLTK code anymore.

**Comment by Albrecht-S** [comment]
Did you commit and push already? I don't see a commit yet.

**Comment by MatthiasWM** [comment]
Sorry, yes, that was on my fork. I just pushed the changes upstream.

**Comment by Albrecht-S** [comment]
Pulled, tested, works. Thanks.
