### ISSUE TITLE
Add wayland support

### ISSUE THREAD

**Issue by ImUrX** [fltk/fltk#380]
I didn't find any tracking issue for this so thought I could make one, is there any ongoing visible progress on this?

only thing i found about is [this comment](https://github.com/fltk/fltk/issues/225#issuecomment-872113076)

**Comment by Albrecht-S** [comment]
A Wayland port is work in progress and will likely be included in 1.4.0.

Discussion about library development takes place in our "forum" (aka mailing list, Google Groups) [fltk.coredev](https://groups.google.com/g/fltkcoredev).

See thread "Please vote: add a Wayland platform to FLTK":
https://groups.google.com/g/fltkcoredev/c/V9UdH2ZZyzg

**Comment by Albrecht-S** [comment]
FTR: see also [STR 3371](https://www.fltk.org/str.php?L3371): "Wayland Display Server Protocol support"

**Comment by Albrecht-S** [comment]
Wayland support has been added in commit 3718effc431f5622a23c55b254153efdfe4e72c4 and will be in release 1.4.0

**Comment by MatthiasWM** [comment]
Congratulations on that intense work!
