### ISSUE TITLE
[RFE] End user copy to clipboard from fl_message

### ISSUE THREAD

**Issue by ramcdona** [fltk/fltk#388]
Is it possible to enable the end-user to copy the text from a fl_message to the OS clipboard?

I'm not interested in making the fl_message work with drag-n-drop events or an application specific clipboard.  When I use a fl_message to display an error message to my users, I'd like for them to be able to copy/paste that message into an email for error reporting (and other use cases).

My wish is that this would be a simple behavior flag to turn on/off.  I suspect it will involve inheriting a custom fl_message_copyable and implementing an event handler with some magic sauce...  I have no experience with the system clipboard through FLTK, so I'm not sure where to start here.

**Comment by Albrecht-S** [comment]
Thanks for the suggestion.

I'm working on the implementation of ctrl-c (macOS: command-c) to copy the message text to the clipboard which would be always active (but users would need to know about it because it's a "hidden" feature.

Offering a "copy" button on demand -- by setting a "copy button" flag before calling fl_message() -- would be another option but much more work.

**Comment by Albrecht-S** [comment]
Fixed in commit f6c2531b5b4d939352dccd9f8295f4471d7e1c4c.

@ramcdona Please confirm that the above commit works for you. I'd like to leave it as is and not add an extra button as [discussed in fltk.general](https://groups.google.com/g/fltkgeneral/c/lXKOo8Jx75U).

**Comment by erco77** [comment]
Just to note: I'm pretty sure this same feature (^C in dialog boxes copying msg to the clipboard) has been a long standing hidden feature in MS windows dialogs. I remember learning about it very early on (perhaps as far back as Win NT?), and was one of the few times while using MS windows I thought "Wow, that's actually a really nice feature"

**Comment by ramcdona** [comment]
I haven't had a chance to pull this down and build with it yet (will try to later today).  But it should work for me.

**Comment by Albrecht-S** [comment]
I'm closing this issue now.

@ramcdona Feedback would still be appreciated. Thanks.

**Comment by ramcdona** [comment]
Was able to test today on MacOS.  Works great.  Thanks much!

**Comment by Albrecht-S** [comment]
Thanks, done.
