### ISSUE TITLE
Location of the FLTK include files

### ISSUE THREAD

**Issue by MrExplode** [fltk/fltk#389]
I'm trying to build FLTK for Windows and noticed that the README.CMake.txt isn't really up to date. the output artifacts aren't at the stated paths, and even though I found the .lib files I can't seem to find the include files anywhere. Where are they being placed?

**Comment by Albrecht-S** [comment]
There are several different build systems on Windows, for instance Visual Studio, MinGW, MSYS2, ...

Please specify what you are using and in what points README.CMake.txt is outdated so we can fix it (if it's wrong).

Thanks. That said, if this is a bug report, then this is the correct place and you can help us improve the documentation. If this is a question how to build FLTK, then please see below.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by MrExplode** [comment]
I'm building with Visual Studio 2022.
Well looking at it now I figured out where are the things. Realized that other than the vs7 everything is ok in the readme.
