### ISSUE TITLE
please update FLTK website UI

### ISSUE THREAD

**Issue by ejamshidiasl** [fltk/fltk#39]
Hello
please update FLTK website UI

**Comment by erco77** [comment]
Can you be more specific -- is there a broken link, info out of date, if so where?

**Comment by ejamshidiasl** [comment]
no
my mean is that update UI. like modern websites

**Comment by ejamshidiasl** [comment]
now website has old style
change style

**Comment by Thecarisma** [comment]
I think there has been a vote on this and people vote the website to stay that way. I also vote in support for a new modern website because fltk is a very great framework and the current website does not portray enough. 

If you have enough free time we can collaborate to create a modern website for fltk. If it ok it will be applied to the website and still keep the current UI under a legace url.

To me the only advantage of this current website UI is the speed that all.

**Comment by ejamshidiasl** [comment]
> fltk is a very great framework and the current website does not portray enough
YES it is
fltk is really nice and i love it
i am working on simple , fast and beautiful(material design) website for fltk and i will send url to you tomorrow and when it complete i will send source to you

**Comment by ejamshidiasl** [comment]
[https://imgur.com/iXELJ7i](url)
it is home page
is it good?

**Comment by erco77** [comment]
Looks nice to me in a general layout way.

I don't think we want to drop the logo though, but could modernize for color or tweak in small ways but keep that same logo design.

And fitting news + list of latest user supplied links back into the main page should be something to keep, so user's new contributions get exposure.

I think I have a pure css menubar lying around somewhere that handles pulldown menus without needing jquery and other heavy 3rd party stuff.

All the website code is PHP, so it'd be a bit of work to refit, but perhaps refitting one page at a time would keep it easy.

Thing is I don't have a lot of time these days; too many projects not FLTK related, so I just have time to keep an eye on the mailing list and fix problems that come up. But in a slow way either me or Albrecht might be able to find some time to work on this.

If you feel in the mood to present a full site layout, feel free and we can try to help guide you. Then when we have something working, let a few people eval the new way to look at the site, work the bugs out, then go for a release. That's how we usually do stuff.

**Comment by ejamshidiasl** [comment]
ok i change until you like it
