### ISSUE TITLE
Loading PNG_IMAGe failed

### ISSUE THREAD

**Issue by Jomme5** [fltk/fltk#4]
$ fltk-config --ldflags --compile hallo_test.cxx

```
g++ -I. -I./png -I./zlib -I./jpeg -mwindows -DWIN32 -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -o 'hallo_test' 'hallo_test.cxx' -static ./lib/libfltk.a -lole32 -lws2_32 -lcomctl32 -luuid
D:\Tmp\ccw4NMb9.o:hallo_test.cxx:(.text+0xe8): undefined reference to `Fl_PNG_Image::Fl_PNG_Image(char const*)'
collect2.exe: error: ld returned 1 exit status

```
What do I have to change in the fltk-config?

**Comment by Jomme5** [comment]
--libs --use-images

**Comment by Albrecht-S** [comment]
I'm glad you found the solution yourself.

In case someone else is reading this and for future questions I'd like to add that this (GitHub Issues) is not the correct place to ask for FLTK user help. Please use our mailing list (Google Groups) fltk.general:

**https://groups.google.com/forum/#!forum/fltkgeneral**

Thanks.
