### ISSUE TITLE
How to edit source

### ISSUE THREAD

**Issue by ejamshidiasl** [fltk/fltk#40]
Hello
i want to edit simple thing in source code for learning source

i want to change check-button tick sign to other shape. how to do this?

**Comment by Albrecht-S** [comment]
This is not the proper and not the best place to ask such questions. FLTK issues should be used to report bugs of the library and/or to propose enhancements.

That said, you'd likely get quicker and more answers if you ask in our FLTK mailling list (Google Groups) [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). You need to register to post and you can use its web interface or use it as a mailing list with your mail account.

**Comment by ejamshidiasl** [comment]
Ok
is it possible to just answer this time here?
i made account in fltk.genral
