### ISSUE TITLE
Wayland: Fl::get_key(c) for lower case letters different behaviour from X11

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#404]
Running the following program under X11:

```cxx
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
int main() {
	Fl_Window win(100,100);
	win.show();
	while ( 1 )  {
		Fl::wait(0.01);
		int c = Fl::event_key();
		if ( Fl::get_key('a') )
			printf("key 'a' pressed\n");
		if ( Fl::get_key('A') )
			printf("key 'A' pressed\n");
		if ( Fl::get_key('1') )
			printf("key '1' pressed\n");
	}
}
```
When pressing 'a' it shows two events at once, one for 'a' and for 'A'.

Running the same program under Wayland, it will never report 'a', but only 'A'.

**Comment by erco77** [comment]
On 3/8/22 09:36, wcout wrote:

> Running the following program under X11:
>
> #include  <FL/Fl.H>
> #include  <FL/Fl_Window.H>
> int  main() {
> 	Fl_Windowwin(100,100);
> 	win.show();
> 	while  (1  )  {
> 		Fl::wait(0.01);
> 		int  c =Fl::event_key();
> 		if  (Fl::get_key('a') )
> 			printf("key 'a' pressed\n");
> 		if  (Fl::get_key('A') )
> 			printf("key 'A' pressed\n");
> 		if  (Fl::get_key('1') )
> 			printf("key '1' pressed\n");
> 	}
> }
>
> When pressing 'a' it shows two events at once, one for 'a' and for 'A'.
> Running the same program under Wayland, it will never report 'a', but only 'A'.
>
     Pretty sure get_key() and the related event_key() method (referenced as a "See also")
     only return _unshifted_ values; according to the event_key() docs:

        /Keys are identified by the //unshifted//values. FLTK defines a set of symbols that should work on most modern machines for every key on the
        keyboard [..]/

     So I'm guessing doing tests with /_shifted_/ values is undefined (e.g. get_key('A')).

     If you want to detect keys, use these functions.
     If you want to detect "text", where e.g. shift and utf8 characters and such are applied,
     use Fl::event_text() and Fl::event_length().

**Comment by wcout** [comment]
Yes, this works now like under X11.
Thank you very much.

**Comment by wcout** [comment]
Seems this does not work any more with current Github version. Some regression?
System: Ubuntu 20.04.

**Comment by ManoloFLTK** [comment]
I see no problem with the current source code for Fl::get_key().

**Comment by wcout** [comment]
Did you try the program posted in the initial report? I double checked now, made a clean rebuild of FLTK and I still see a different behavior of the Wayland backend (program compiled as `keys`).

NOTE: press key 'a' after program start:

````
export FLTK_BACKEND=x11 
./keys 
key 'a' pressed
key 'A' pressed
key 'a' pressed
key 'A' pressed
...

export FLTK_BACKEND=wayland
./keys 
key 'A' pressed
key 'A' pressed
key 'A' pressed
key 'A' pressed
...
````

The lower case 'a' is never reported.
I see this under Ubuntu 20.04 and also Ubuntu 22.04.

SIDENOTE: Under Ubuntu 22.04 I also get an error with this program from libdecor:
````
Caught error (1): minimum size (128,100) must be smaller than maximum size (100,100)
````
This is because of the window size 100/100. I do net get this error with the x11 backend though!
I had to change it to 200/200 to make it work.

**Comment by wcout** [comment]
Confirming, it is fixed. Thank you.
