### ISSUE TITLE
New build failure when using OPTION_USE_PANGO on Linux

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#405]
Hello

The last commit no longer builds FLTK on Linux when specifying the OPTION_USE_PANGO cmake feature due to ODR violation.
```
/usr/bin/ld: lib/libfltk.a(Fl_Cairo_Graphics_Driver.cxx.o):(.data.rel.local+0x900): multiple definition of `fl_fonts'; lib/libfltk.a(Fl_Xlib_Graphics_Driver_font_xft.cxx.o):(.data.rel.local+0x900): first defined here
collect2: error: ld returned 1 exit status
```

To repro:
```
git clone https://github.com/fltk/fltk --depth=1
cd fltk
cmake -GNinja -Bbin -DOPTION_USE_PANGO=ON
cmake --build bin
```

**Comment by Albrecht-S** [comment]
Thanks for the report, I confirm that commit f97fbffa7b927829236e792df8ef6416c6aeed4f (_"Move all font stuff to Fl_Cairo_Graphics_Driver from Fl_Wayland_Graphics_Driver"_) breaks the build.

@ManoloFLTK Can you please check this?
