### ISSUE TITLE
Can you add UI auto scaling with resolution?

### ISSUE THREAD

**Issue by Spatzendame** [fltk/fltk#407]
Hi, many games don't scale the UI which result in a very small UI when playing in modern 4K or even higher resolutions that makes everything unreadable small. I know that it's possible to built in an auto scale function that automatically scales the UI up with the resolution. This would be a major improvement.

**Comment by ManoloFLTK** [comment]
That is indeed built in the next version of the FLTK library, 1.4.0, which is expected to be released soon. It can be downloaded and used even before its official release.
