### ISSUE TITLE
How to build FLTK.dll from source with Visual Studio 2022?

### ISSUE THREAD

**Issue by Spatzendame** [fltk/fltk#409]
Hi, I did everything described in the README.CMake file and I got successfully built the FLTK.sln using the command prompt.
But when I open it with Visual Studio I have only x64 solutions available, so I selected "create new" and converted everything to Win32. Then I wanted to build the FLTK.dll but in the end I got many link errors "GDIplus".

Can someone please explain to me step by step what I have to configure before building the solution?

I want to update the fltk.dll from the game "Amnesia: The Dark Descent" which is from 2010 so can I even replace the old fltk.dll with a new from version 1.4.0 ?

I got successfully built FLTK 1.3.8 by opening the "ide" folder which has a vs2010 solution and the game works with it. But even here I got warnings during the build process and I don't know whether everything is correct inside.

Or please can you pre-build an official fltk.dll when the stable version of FLTK 1.4.0 is released?
For you developers it should be done in 2 minutes I think and everyone would be happy to have an easier life.

Thank you.

**Comment by Albrecht-S** [comment]
Hi Spatzendame, you can't replace a FLTK 1.3.8 DLL with a 1.4.0 DLL because they would be binary incompatible. If you got FLTK 1.3.8 to work with the game there should be no need to change this. Is there anything wrong with the game using the 1.3.8 DLL?

That said, this is not the right place to ask questions about building and using FLTK, please see the following standard reply:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
