### ISSUE TITLE
Top level Fl_Window event delivery on macOS

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#411]
I observed inconsistent event delivery (particularly FL_MOVE, FL_ENTER, FL_LEAVE) in top level windows on macOS. This issue is a follow-up to issue #408.

1. Top level windows under macOS don't send FL_ENTER and FL_LEAVE events when the mouse enters or leaves the window.
2. FL_MOVE events are delivered to the window that has the focus which is significantly different than on other platforms. This may be caused by point 1.
3. On other platforms (notably Linux) FL_ENTER events are created when the mouse enters the window area, then FL_MOVE events are generated until the mouse leaves the window again and FL_LEAVE is sent. This happens independent of the window focus.
4. Maybe all windows (Fl_Window, Fl_Double_Window, Fl_Gl_Window) generate FL_ENTER, FL_MOVE, and FL_LEAVE events under macOS only when the focus is transferred to the window by clicking into the window or on its titlebar, i.e. when the window is activated and stop sending FL_MOVE events only when another window gets the focus.

I created two test programs that `printf()` events sent to the window handle() methods:

(a) a top level Fl_Gl_Window:

[opengl_simple.cxx.txt](https://github.com/fltk/fltk/files/8256997/opengl_simple.cxx.txt)

(b) an Fl_Gl_Window embedded in another Fl_Window or Fl_Double_Window:

[opengl_embedded.cxx.txt](https://github.com/fltk/fltk/files/8256998/opengl_embedded.cxx.txt)

Different event output should be obvious regarding the main window and the subwindow. However, WRT FL_ENTER and FL_LEAVE there is maybe no difference between the two program but, as said before, this is significantly different than on Linux (and likely Windows, which needs to be tested).

**Comment by Albrecht-S** [comment]
@ManoloFLTK Please take a look at the output and compare this with the output on Linux and/or Windows. I'm not sure how important it would be to fix this but it's definitely a platform compatibility issue. Thanks.

**Comment by ManoloFLTK** [comment]
@Albrecht-S : is this specific of Fl_Gl_Window's or also occurs with Fl_Window's ?

**Comment by Albrecht-S** [comment]
@ManoloFLTK I first thought it's only Fl_Gl_Windows, but as the second demo program seems to indicate, it's also with Fl_Window's. A simple test is to have one or more of the test programs launched from one or more terminal sessions.

- Under macOS only the window with the focus gets events (seen in its related terminal), no matter where the mouse is on the screen.
- Under Linux (X11) the window under the mouse gets events, even if any other window has the focus.
- I'm not sure what Windows does, but IMHO the Linux behavior is correct.
- Wayland not tested yet.

**Comment by ManoloFLTK** [comment]
I've looked first at issue 1. above (FL_ENTER and FL_LEAVE events don't get sent).

It appears the **macOS** FLTK implementation doesn't contain code to send them.

It also appears  FL_EVENT don't get sent **under Windows** when the mouse enters a single-windowed app. FL_LEAVE events do get sent.

Thus, we can consider the X11 implementation to be an outlier,
or that the FL_ENTER (and FL_LEAVE to some extent) event to be platform-specific.

I've superficially looked at the macOS doc about "enter" events. The system doesn't send them by default to a window as opposed to click or key events.  But it's possible to associate a window with an additional "tracking" object,  to set this object's tracked area to the window area, and get macOS to send "enter" events when the mouse enters a window.

**Comment by ManoloFLTK** [comment]
FL_ENTER and FL_LEAVE events get sent when the mouse enters or leaves a window under the **Wayland** platform. That happens whether or not this window has focus.

**Comment by ManoloFLTK** [comment]
Those missed FL_ENTER events concern only Fl_Window widgets. Other widgets
do receive their FL_ENTER and FL_LEAVE events when appropriate on all platforms.

**Comment by ManoloFLTK** [comment]
Attached patch has FL_ENTER and FL_LEAVE events sent to FL_Window widgets on macOS when the mouse enter or leaves a window, independently from the focus.

There's a small difference with the X11 platform: enter, leave and move events are sent also when the app is inactive, whereas on X11 only move events are sent to Fl_Window's.

[FL_ENTER-macOS.patch.txt](https://github.com/fltk/fltk/files/8287207/FL_ENTER-macOS.patch.txt)

**Comment by Albrecht-S** [comment]
@ManoloFLTK I mentioned this issue (411) in #210 because I believe that #210 might be fixed as soon as we get FL_ENTER/MOVE/LEAVE events on "inactive" windows which is the subject of this issue.

**Comment by ManoloFLTK** [comment]
I believe the macOS platform behaves as the X11 platform after commit aa95581.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Yes, I agree. Thanks for implementing this.
