### ISSUE TITLE
Selecting text with keyboard in Fl_Text_Editor stops working sometimes

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#412]
If you select text with mouse and then move/drag that text to another position, then selecting text with keyboard stops working. And you have to select some text with the mouse to get it working again.

It might be because of dragType is set to DRAG_START_DND and not turned off again after moving text.

Tested on Ubuntu 21.10 with FLTK from 2022-03-15.

**Comment by MatthiasWM** [comment]
Not happening on macOS. I will try to replicate this on Ubuntu when I have access to a machine.

**Comment by Albrecht-S** [comment]
Testing to add some observations, I'm not trying to fix anything.

1. I confirm the issue on Linux (Mint, based on Ubuntu) with **X11** backend
2. I confirm the issue on Linux (Mint, based on Ubuntu) with **Wayland** backend
3. I also confirm that the issue doesn't exist on **macOS** with default config (**Quartz**?)
4. However, I can replicate it on **macOS** with `./configure --enable-x11` (**X11** backend, running with XQuartz)
5. The problem doesn't exist on Windows AFAICT (cross-compiled on Linux with `wine`, not tested on a native Windows box)

My test scenario:
- launch `test/editor test.txt`
- select text with mouse **OR** keyboard (`Shift` + `cursor keys`)
- drag the selected text to another place
- press `Shift` + `cursor keys` as before: doesn't work on some platforms (see above)

The OP @gnuwimp wrote:
> ... you have to select some text with the mouse to get it working again.

In my tests it's been enough to click with the mouse anywhere in the editor to position the cursor to a new place.

HTH

**Comment by MatthiasWM** [comment]
I think that resetting the drag state to none in ::handle FL_DRAG after the Fl::dnd() call should do the trick. Cocoa seems to send FL_RELEASE after the dnd which resets the state, X11 does not.

**Comment by Albrecht-S** [comment]
> Cocoa seems to send FL_RELEASE after the dnd which resets the state, X11 does not.

If that's true, then one of the platforms needs to be fixed, independent of this particular issue. Events should be as close as possible on all platforms (compared to other platforms). Note that I don't know which one is correct, i.e. sending FL_RELEASE or not.

But at least this explains the difference.

**Comment by ManoloFLTK** [comment]
The issue should be fixed in the Wayland backend with commit d215dde.

**Comment by MatthiasWM** [comment]
Thanks Manolo!
