### ISSUE TITLE
src/drivers/Xlib/Fl_Xlib_Graphics_Driver_font_xft.cxx has a libasan error (memcmp read on unitialized memory)

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#416]
The function:

static int font_name_process(const char *name, char &face)

in src/drivers/Xlib/Fl_Xlib_Graphics_Driver_font_xft.cxx

has an issue reading (memcmp) from unitialized memory if the font name being compared is too short (like Sans).  
Find the attached patch to fix the issue.

[fonts_attrs.patch.txt](https://github.com/fltk/fltk/files/8311252/fonts_attrs.patch.txt)

**Comment by ManoloFLTK** [comment]
Thanks for the patch.
