### ISSUE TITLE
How to find Zlib installation when generating project files with CMake

### ISSUE THREAD

**Issue by DragonOsman** [fltk/fltk#42]
I have Zlib installed in my C drive root.  When I try to use CMake to generate project files for FLTK, it can't find Zlib.  How do I specify the library name and path?  I've tried this: `cmake -G "Visual Studio 16 2019" -A x64 -Thost=x64 .. -DCMAKE_INSTALL_PREFIX="C:/Program Files/FLTK" -DCMAKE_BUILD_TYPE=Release -DZLIB_INCLUDE_DIR=C:/zlib/include -DZLIB_LIBRARY=C:/zlib/lib` (I see I won't have to specify the install prefix, so when I run it again I won't include that) and I get a warning saying that the unknown manually-specified option `ZLIB_LIBRARY` wasn't used.  What's the correct way to specify the library path (and name, which in my case is zlibstatic.lib (if I use zlib.lib, it'll try to use zlib.dll as well and that's bad as it'll cause linker errors due to symbols being seen in more than one place))?  Thanks in advance.

Edit: Note: I didn't install the LLVM toolchain extension since it only seems to work if VS2017 is also installed.  On the extension's installation page it says that VS2019 users may want to look at [this](https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/) instead.  I'm using the built-in LLVM toolchain that VS2019 comes with instead of the extension.  CMake must be trying to find the extension.  I need to know how, if at all, I can get it to use the built-in LLVM toolchain instead.

**Comment by Albrecht-S** [comment]
Note that this is not the best place to ask (user) questions on how to build the library or user applications. You may get quicker and more results if you ask such questions in our mailing list (aka forum) [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral).

That said, here are the relevant parts of my CMakeCache.txt **from a Linux build**. Maybe this can help you to find out how to set up your cmake build:
```
OPTION_USE_SYSTEM_ZLIB:BOOL=ON
ZLIB_INCLUDE_DIR:PATH=/usr/include
ZLIB_LIBRARY_DEBUG:FILEPATH=ZLIB_LIBRARY_DEBUG-NOTFOUND
ZLIB_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libz.so
```
i.e. in my case `ZLIB_LIBRARY_RELEASE` points at the (shared) library file. YMMV.

Do you really need a specific ZLIB to build with? FLTK comes with a bundled ZLIB which will be used if the system library is not found or you specify `OPTION_USE_SYSTEM_ZLIB:BOOL=OFF` explicitly.

Regarding `-DCMAKE_INSTALL_PREFIX="C:/Program Files/FLTK"`: It is generally a bad idea to specify paths with included spaces for CMake builds. Although it is generally possible it may lead to unexpected problems.

**Comment by DragonOsman** [comment]
I added quotes, so the spaces should be okay here.  And apparently that's the default location where FLTK is installed on Windows machines anyway.  

So on the CMake command line, I have to specify `-DZLIB_LIBRARY_RELEASE`?

**Comment by Albrecht-S** [comment]
> So on the CMake command line, I have to specify -DZLIB_LIBRARY_RELEASE?

See `cmake --help-module FindZLIB`:

> A user may set ``ZLIB_ROOT`` to a zlib installation root to tell this module where to look.

FLTK uses FindZLIB, hence you'd likely need `-DZLIB_ROOT="path-to-zlib"` but I'm not sure.

**Comment by Albrecht-S** [comment]
I assume this issue is resolved. Can we close it?

**Comment by Albrecht-S** [comment]
No reply ... closing now.
