### ISSUE TITLE
Fl_OpenGL_Graphics_Driver should be GUI scaling aware under Windows

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#421]
The issue occurs with Windows and is visible with test/cube.
Run test/cube under Windows.
String "FLTK over GL" is visible in a yellow rectangle.
Scale the GUI typing ctrl-+    ===>  the text in the yellow rectangle disappears.
Scale back typing ctrl-0   ===>  the text reappears.

**Comment by ManoloFLTK** [comment]
This may be a side effect of using a VM to run Windows.

**Comment by MatthiasWM** [comment]
Hmm, it works correctly on MacOS. Do you want me to recheck on a native Windows machine?

**Comment by ManoloFLTK** [comment]
Yes, please.

**Comment by Albrecht-S** [comment]
I can confirm the issue, but I'm currently also working in a Windows (Virtualbox) VM and I can't test on a "real" Windows box right now and in the near future.

**Comment by ManoloFLTK** [comment]
Just to clarify a detail hidden deep inside the text drawing code to a GL window :
Some VMs have limited suport of OpenGL so that the texture-based approach of text drawing is not
possible. In that case, another code path is used to draw OpenGL text.
It's possible therefore the problem is only in that fallback code, not in what runs on a native Windows box.

**Comment by Albrecht-S** [comment]
FTR: I found out that the cube demo works fine with ctrl/+/-/0 on a native Windows 10 box.

> Some VMs have limited support of OpenGL so that the texture-based approach of text drawing is not possible. In that case, another code path is used to draw OpenGL text. It's possible therefore the problem is only in that fallback code, not in what runs on a native Windows box.

@ManoloFLTK My observation seems to support your suspicion. Does this help?

**Comment by MatthiasWM** [comment]
FWIW, I saw the issues originally, but I upgraded Parallels and VisualStudio to run under Windows 11 for ARM on my M1 MacBook Pro, and now the cube demo runs and scales just fine. I compiled as an ARM executable and as Intel in emulation, and both versions are fine.

**Comment by ManoloFLTK** [comment]
I propose to close this issue because it seems limited to some VM configurations emulating Windows.
