### ISSUE TITLE
cmake -DOPTION_USE_GL=OFF causes link errors in test units

### ISSUE THREAD

**Issue by markjolesen** [fltk/fltk#422]
because GL was turned off the test units using GL can not link

ld: error: undefined symbol: vtable for Fl_Gl_Window
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(PointTest::PointTest(int, int, int, int))
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(RectTest::RectTest(int, int, int, int))
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(CircleTest::CircleTest(int, int, int, int))
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)

ld: error: undefined symbol: Fl_Gl_Window::init()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(PointTest::PointTest(int, int, int, int))
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(RectTest::RectTest(int, int, int, int))
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(CircleTest::CircleTest(int, int, int, int))

ld: error: undefined symbol: Fl_Gl_Window::~Fl_Gl_Window()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(PointTest::PointTest(int, int, int, int))
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(GLTestWin::~GLTestWin())
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced 4 more times

ld: error: undefined symbol: Fl_Gl_Window::draw_begin()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(GLTestWin::draw())
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(GLRectTest::draw())
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(GLCircleTest::draw())

ld: error: undefined symbol: Fl_Gl_Window::draw_end()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(GLTestWin::draw())
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(GLRectTest::draw())
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(GLCircleTest::draw())

ld: error: undefined symbol: Fl_Gl_Window::handle(int)
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(vtable for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(vtable for GLCircleTest)

ld: error: undefined symbol: Fl_Gl_Window::resize(int, int, int, int)
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(vtable for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(vtable for GLCircleTest)

ld: error: undefined symbol: Fl_Gl_Window::show()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(vtable for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(vtable for GLCircleTest)

ld: error: undefined symbol: Fl_Gl_Window::hide()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(vtable for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(vtable for GLCircleTest)

ld: error: undefined symbol: Fl_Gl_Window::flush()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(vtable for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(vtable for GLCircleTest)

ld: error: undefined symbol: Fl_Gl_Window::draw_overlay()
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(vtable for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(vtable for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(vtable for GLCircleTest)

ld: error: undefined symbol: typeinfo for Fl_Gl_Window
>>> referenced by unittest_points.cxx
>>>               CMakeFiles/unittests.dir/unittest_points.cxx.o:(typeinfo for GLTestWin)
>>> referenced by unittest_fast_shapes.cxx
>>>               CMakeFiles/unittests.dir/unittest_fast_shapes.cxx.o:(typeinfo for GLRectTest)
>>> referenced by unittest_circles.cxx
>>>               CMakeFiles/unittests.dir/unittest_circles.cxx.o:(typeinfo for GLCircleTest)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (test/CMakeFiles/unittests.dir/build.make:300 'bin/test/unittests')
*** Error 2 in . (CMakeFiles/Makefile2:489 'test/CMakeFiles/unittests.dir/all')
*** Error 2 in /home/markjolesen/tmp/fltk/build (Makefile:136 'all': make -s -f CMakeFiles/Makefile2 all)

**Comment by Albrecht-S** [comment]
I can't confirm this on my system, everything works with the latest Git checkout (master) on Linux with the commandline given in the subject. The unittests demo program works but the GL parts are not shown in the demo, as expected.

To ensure that there are no other effects in your build, please run your build commands in a fresh checkout or at least a fresh build directory.

If the issue persists, please tell us on which system/platform you are experiencing this issue and the exact (i.e. complete) CMake commandline you're using so we can test.

**Comment by Albrecht-S** [comment]
I forgot to mention: please use the latest Git version of branch 'master' and provide the Git hash in your report (if there are still issues). I used Git commit df4503ea2ce2fd8727cf77f7d8d071897bb13445 for my tests.

**Comment by markjolesen** [comment]
I think the problem was I overridden config.h and had
#define HAVE_GL 1

**Comment by Albrecht-S** [comment]
> the problem was I overridden config.h and had
#define HAVE_GL 1

Yep, that would explain it. Closing the issue now.
