### ISSUE TITLE
Can (a variant of) Fl_Box_Draw_F take the boxtype or userinfo as a parameter?

### ISSUE THREAD

**Issue by pwiecz** [fltk/fltk#423]
I'm writing a foreign language (Go) binding to Fltk and cannot find a way to specify more than one custom boxtype.
Fl::set_boxtype take a pointer to a "C/C++" function used for drawing the boxes, and the function does not know what kind of the box it's supposed to draw.
In my Go code I cannot create a new C function for custom boxtype, so I have to have one function that somehow knows which Go function to invoke for which boxtype. Unfortunately Fl_Box_Draw_F right now does not have this information.

If I'm not missing somethig, I'd need a new callback type and new Fl::set_boxtype function to be able to create a proper binding.

Thanks.

**Comment by pwiecz** [comment]
Thanks! I'll post where appropriate. :)

**Comment by Albrecht-S** [comment]
A few short words to your project (I took a very quick look at it and I'm not a Go user). I do not recommend to provide compiled libraries with your project. FLTK is using C++ and its binary interface (ABI) can heavily depend on the compiler and tools used to build the library, particularly on Windows where you have Visual Studio and several other incompatible compiler/build suites.
