### ISSUE TITLE
macOS: "configure --enable-cairoext" flips display upside down

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#426]
System: macOS 12.2.1 "Monterey" with Homebrew.
Git master, commit b4bbc53c5e7f17395b1d5330598565b60f71e543
```
make distclean; autoconf; ./configure --enable-cairoext; make -j7
```
Running for instance `test/unittests` looks OK when the program starts but as soon as you click on one of the items in the side bar most of the screen flips upside down. Other programs are also affected, "interesting" example: test/buttons. test/hello is not affected.
Screenshot of test/unittests after clicking:

![unittests](https://user-images.githubusercontent.com/26235500/162326892-95f7bc37-ba33-4729-aadf-ff60c2982d94.png)

The following patch works around the issue but this is very likely not a proper fix:
[patch.txt](https://github.com/fltk/fltk/files/8447102/patch.txt)

I tried to look into it but I can't find out what's going on. There are similar occurrences of such code, always wrapped in `# if defined(FLTK_HAVE_CAIROEXT)` ... `#endif`, hence it happens only if "extended Cairo support" is enabled.

I'm aware that FLTK inverts the macOS coordinate system but I need help from a macOS expert.

@ManoloFLTK Do you have an idea how to fix this correctly?

**Comment by Albrecht-S** [comment]
FTR: the same issue exists when built with CMake.

**Comment by ManoloFLTK** [comment]
@Albrecht-S : do you see this fixed as I do ?

**Comment by Albrecht-S** [comment]
Yes, I do. Thank you very much, I would never have been able to fix it with this macOS specific code. I hope I'll find some time in the future to improve my macOS skills.
