### ISSUE TITLE
Feature suggestion: read on-screen pixel

### ISSUE THREAD

**Issue by daniel-starke** [fltk/fltk#43]
There exists the fl_point() function to draw a pixel but no function to read a pixel value back. However, such function would make it possible to create alpha-blended drawing functions. Hence, this feature suggestion.

**Comment by Albrecht-S** [comment]
Well, it's not exactly the function you're suggesting, but we have a more general function to read pixels from the screen called [fl_read_image()](https://www.fltk.org/doc-1.3/group__fl__drawings.html#ga0cdc05d3f7689e1c6b8a26fd0bd97233) .
The following code (note: untested) should do what you want:
```
unsigned char pixel[3];
fl_read_image(pixel, X, Y, 1, 1, 0);
```
This would fill pixel[] with R, G, B components of pixel (X, Y) of "the current window or off-screen buffer" according to the docs. Does this work for you?

I'm pretty sure we also have "alpha-blended drawing functions" but this part would need more info about what you want to achieve.

If you need more help please ask questions about FLTK usage in our forum / mailing list / Google Group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Thanks.

**Comment by daniel-starke** [comment]
Thank you. fl_read_image() was exactly what I needed. I was looking for a fl_point() counterpart and did not imagine finding it as fl_draw_image() counterpart, though.
