### ISSUE TITLE
Menus have white corners when background is dark and scheme is gtk+ or plastic on macOS

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#435]
The menus under macOS only show white corners even when the background color is dark under gtk+ or plastic schemes.  Find attached a simple demo program to compile with fltk-config --compile.

[white_corners.zip](https://github.com/fltk/fltk/files/8547677/white_corners.zip)

**Comment by ggarra13** [comment]
I am attaching a patch for gtk+ that fixes the problem on macOS (which has white backgrounds by default, while Linux and WIN32 have black backgrounds).  I still have to see plastic and gleam
[gtk_white_corners.txt](https://github.com/fltk/fltk/files/8548817/gtk_white_corners.txt)
.

**Comment by ggarra13** [comment]
Here's the fix for plastic, too
[plastic_white_corners.txt](https://github.com/fltk/fltk/files/8548833/plastic_white_corners.txt)
.

**Comment by ggarra13** [comment]
And here's the fix for gleam (we fill a rectangle, instead of drawing lines).
[gleam_white_corners.txt](https://github.com/fltk/fltk/files/8548860/gleam_white_corners.txt)

**Comment by ManoloFLTK** [comment]
@ggarra13 : This should now be fixed using the code you proposed at PR #507 with commit 3ba0904. Please, close this issue if you confirm it's fixed. Thanks for your input.

N.B. A typo in the description of commit 3ba0904 makes it refer erroneously to an unrelated issue instead of this issue.
