### ISSUE TITLE
Wayland: Textdrawing different from Xft version

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#438]
Wayland textdrawing is different from Xft textdrawing.

Compare the output from the Xft-version and the Wayland-version:

![xft-wayland_textdraw](https://user-images.githubusercontent.com/9895976/165547980-8e40ff38-882e-4be2-87c7-c4d20222feea.png)

- Text is smaller under Wayland
- The y Position is not correct (the red line marks the y value for fl_draw(text,..), which is the font baseline for Xft.

I used this program for above screens:

[textdrawpos.cxx.gz](https://github.com/fltk/fltk/files/8573156/textdrawpos.cxx.gz)

**Note:** This may be related to Cairo being used for drawing. Xft+Pango does not have the problem (except a minor discrepancy in y position)

**Comment by ManoloFLTK** [comment]
@wcout : is it OK now ?

**Comment by wcout** [comment]
The size seems ok now.
But as for the baseline, if that's really a matter of subtracting some fraction of size,  I would rather use a value of 9 or 10 (currently 21). At least in my environment this works out better.

Divisor 21 (current):
![divisor_21](https://user-images.githubusercontent.com/9895976/166090676-5a30bef5-663c-4b2e-8abe-cbab103b05d4.png)

Divisor 9:
![divisor_9](https://user-images.githubusercontent.com/9895976/166090693-2fea7364-e1e5-4e74-9726-56bc9bc1960a.png)

Here my modified test program (resizing changes font size):
[textdrawpos.cxx.gz](https://github.com/fltk/fltk/files/8596092/textdrawpos.cxx.gz)

**Comment by ManoloFLTK** [comment]
I use program test/fonts to explore this issue. It allows to set font and font size at will.
I temporarily modify the FLTK lib to make visible the baseline of text, adding this

```
int ix=x+.5, iy=y+.5, iw=width(str,n);
color(FL_GREEN);
cairo_set_line_width(cairo_, 0.25);
xyline(ix, iy, ix + iw);
color(FL_BLACK);
```
at the end of function `Fl_Cairo_Graphics_Driver::draw(const char* str, int n, float x, float y)` in file `src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx` . Setting the fraction of size to 9 or 10 doesn't appear a good choice.

**Comment by ManoloFLTK** [comment]
@wcout : please, report about what you get now.

**Comment by wcout** [comment]
That is pretty good now, at least with my test program.
But in a "real life" program it seems to not work out, if Fl::set_font(FL_HELVETICA,..) is involved.
Investigating..

**Comment by ManoloFLTK** [comment]
Previous repairs had bad effects on the editor demo program in which underscores became hidden.
The last commit intends to find a tradeoff.

**Comment by wcout** [comment]
> Previous repairs had bad effects on the editor demo program in which underscores became hidden.
The last commit intends to find a tradeoff.

I can not confirm this change fixing the underscore issue with editor. The underscore in editor is not visible in my environment with latest commit.

But the baseline positioning is now much worse again - nearly as it was initially:

![default_xft_wayland](https://user-images.githubusercontent.com/9895976/166191741-d69abffa-4d0f-4042-a987-d699627bed8c.png)

Additionally when using set_font() with a monospace font the baseline is even below the "_" :

![set_font_xft_wayland](https://user-images.githubusercontent.com/9895976/166191831-165dc1e1-6352-4b45-b026-6e97a6da36a4.png)
(created with 'textdrawpos -s')

The Xft version is always ok.

Here my current test program:
[textdrawpos.cxx.gz](https://github.com/fltk/fltk/files/8601103/textdrawpos.cxx.gz)

**Comment by ManoloFLTK** [comment]
@wcout : please, report about what you get now. Should be good.

**Comment by wcout** [comment]
Right, this is perfect now!
Thanks for all your effort.
