### ISSUE TITLE
Imprecise argument type for fl_color(int)?

### ISSUE THREAD

**Issue by deliciouslytyped** [fltk/fltk#439]
Since Fl_Color is typedef-ed as an unsigned int, shouldnt fl_color(int c) here https://github.com/fltk/fltk/blame/c975ec6dca1f1f48404d82643f2f250faee6c1bd/FL/fl_draw.H#L41 take an unsigned int argument?

**Comment by Albrecht-S** [comment]
Thanks for the report, but the answer is "no". Note that your link refers to an ancient commit (September 2008), but anyway, the code is still similar [today](https://github.com/fltk/fltk/blob/5341f0e45ead688a0bef59d2a6a30afcd02fadf1/FL/fl_draw.H#L53):
```c++
/** for back compatibility - use fl_color(Fl_Color c) instead */
inline void fl_color(int c) {
  fl_color((Fl_Color)c);
}
```
As you can see this is an overloaded inline method that is only left for backwards compatibility. The [code above these lines](https://github.com/fltk/fltk/blob/5341f0e45ead688a0bef59d2a6a30afcd02fadf1/FL/fl_draw.H#L50) shows the method that uses an `Fl_Color` argument and, for completeness, there are even more `fl_color(...)` methods with different arguments.
