### ISSUE TITLE
Persian/Arabic text

### ISSUE THREAD

**Issue by ejamshidiasl** [fltk/fltk#442]
Hello
is it possible to use Persian/Arabic text in fltk? how?

fltk version: 1.3.8
os: windows
compiler: vs2022

for example: "سلام" (hello) shows "????"

**Comment by Albrecht-S** [comment]
I assume "os: windows" means recent versions, i.e. win10 or win11. On such windows versions this should work if you have a font with these characters installed. To test this, please build FLTK as usual, run the test/editor program and cut-and-paste your text above into the editor window. Does it show the text correctly?

That said, this is not the right place to ask such user questions. Please see below on how to proceed.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS) and its version, the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by ejamshidiasl** [comment]
adding u8 before string solved my problem. thanks

for example `widget.label(u8"سلام");`
