### ISSUE TITLE
Wayland fl_rectf() regression

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#447]
Commit https://github.com/fltk/fltk/commit/a118732f7c10da03196ebd9207007686163114f4 produced a regression. The fl_rectf rectangle is drawn to big:

````cxx
#include <FL/Fl_Window.H>
#include <FL/Fl.H>
#include <FL/fl_draw.H>

class Window : public Fl_Window {
public:
	Window(int w_, int h_, const char *l_ = 0) : Fl_Window(w_, h_, l_) {}
	void draw()	{
		Fl_Window::draw();
		int X = w() / 4;
		int Y = h() / 4;
		int W = w() / 2;
		int H = h() / 2;
		fl_color(FL_BLACK);
		fl_rect( X - 1, Y - 1, W + 2, H + 2 );
		fl_color(FL_YELLOW);
		fl_rectf( X, Y, W, H );
	}
};

int main(int argc, char *argv[]) {
	Window win( 500, 300 );
	win.resizable(win);
	win.show();
	return Fl::run();
}
````
![rectf_wayland](https://user-images.githubusercontent.com/9895976/170637119-b53ffc57-231e-4b5e-ab69-39baf71738c3.png)

**Comment by Albrecht-S** [comment]
Commit a118732f7c10da03196ebd9207007686163114f4 is about Cairo drawing...

@wcout When do you see this issue, using Wayland or ...? I'm not seeing it with stock FLTK on Linux/X11 and I can't confirm the issue on Linux/Wayland either (using current master).

After testing it appears to me that this issue has been fixed in commit b78035624. Can you confirm, or is there anything I'm missing?

**Comment by wcout** [comment]
It was on Wayland only (like mentioned in the title).
But it is gone now with commit https://github.com/fltk/fltk/commit/b78035624d5135f27b9742249652f124411f90a9, as you assumed. The question is, if that was a coincidence (two effects that neutralize each other) or the second is actual the fix for first too.

[Offtopic: It seens that the dotted focus rectangles on the buttons are now a little "ragged" with some scales (e.g. 133, 170%)]

**Comment by Albrecht-S** [comment]
> The question is, if that was a coincidence (two effects that neutralize each other) or the second is actual the fix for first too.

This question (if really relevant?) could probably be answered by @ManoloFLTK.

> ... the dotted focus rectangles on the buttons are now a little "ragged" with some scales ...

@wcout Can you provide a screenshot? Is this also only on Wayland, or do you see this on Linux as well?

@ManoloFLTK, what do you think about the focus rectangle question above? Is there anything we can do?

**Comment by ManoloFLTK** [comment]
Should be good now. Can the OP confirm, please ?

**Comment by ManoloFLTK** [comment]
> The question is, if that was a coincidence (two effects that neutralize each other) or the second is actual the fix for first too.

The first commit was not a good solution. The second one is the good one. It removes changes form the first commit.

**Comment by wcout** [comment]
All good now. Thanks for clarification.
