### ISSUE TITLE
Symbol file not found exception in release build

### ISSUE THREAD

**Issue by demberto** [fltk/fltk#448]
FLTK 1.3.8 (vcpkg - x64-windows-static)
MSVC 2022 17.2.1 64-bit
Windows 10 21H2

CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.8)
project (Prj)
find_package (FLTK CONFIG REQUIRED)
add_executable (${PROJECT_NAME} WIN32 "main.cpp")
set_property (TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 17)
target_link_libraries (${PROJECT_NAME} PRIVATE fltk)
```

CMakePresets.json (almost entirely the default generated by MSVC):
```json
{
  "version": 3,
  "configurePresets": [
    {
      "name": "windows-base",
      "hidden": true,
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/out/build/${presetName}",
      "installDir": "${sourceDir}/out/install/${presetName}",
      "cacheVariables": {
        "CMAKE_C_COMPILER": "cl.exe",
        "CMAKE_CXX_COMPILER": "cl.exe",
        "CMAKE_TOOLCHAIN_FILE": "C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake"
      },
      "condition": {
        "type": "equals",
        "lhs": "${hostSystemName}",
        "rhs": "Windows"
      }
    },
    {
      "name": "x64-debug",
      "displayName": "x64 Debug",
      "inherits": "windows-base",
      "architecture": {
        "value": "x64",
        "strategy": "external"
      },
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug"
      }
    },
    {
      "name": "x64-release",
      "displayName": "x64 Release",
      "inherits": "x64-debug",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release"
      }
    },
    {
      "name": "x86-debug",
      "displayName": "x86 Debug",
      "inherits": "windows-base",
      "architecture": {
        "value": "x86",
        "strategy": "external"
      },
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug"
      }
    },
    {
      "name": "x86-release",
      "displayName": "x86 Release",
      "inherits": "x86-debug",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release"
      }
    }
  ]
}
```

Already tried **Clean All** option in MSVC and manually deleting *out/* folder.

**Comment by Albrecht-S** [comment]
Sorry, we can't help here with building your application, and particularly not with vcpkg. GitHub issues for FLTK is reserved to issues with the library itself, please see below for more info.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
