### ISSUE TITLE
Fl_Tree doesn't spawn FL_TREE_REASON_RESELECTED

### ISSUE THREAD

**Issue by lionkor** [fltk/fltk#45]
I built from source, everything else works fine. Not sure what other info I can give here - the event just never arrives at the handler, the others (SELECT & DESELECT for example) work fine.

**Comment by lionkor** [comment]
The fix is to set FL_TREE_SELECTABLE_ALWAYS - this should be explicitly mentioned in the corresponding documentation (about handling events).

**Comment by erco77** [comment]
Docs for FL_TREE_SELECTABLE_ALWAYS modified in commit a624d9b.
