### ISSUE TITLE
Fl::get_font_name failure on OS-X

### ISSUE THREAD

**Issue by w1hkj** [fltk/fltk#452]
One of my Mac users reported a corrupt OX-X font caused a segmentation fault in this method prior to commenting out the OS-X system calls:

// turn a stored font name into a pretty name:
const char* Fl::get_font_name(Fl_Font fnum, int* ap) {
  if (!fl_fonts) fl_fonts = Fl_X::calc_fl_fonts();
  Fl_Fontdesc *f = fl_fonts + fnum;
  if (!f->fontname[0]) {
/*
#if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
    if (fl_mac_os_version >= Fl_X::CoreText_threshold) {
      CFStringRef cfname = CFStringCreateWithCString(NULL, f->name, kCFStringEncodingUTF8);
      CTFontRef ctfont = CTFontCreateWithName(cfname, 0, NULL);
      CFRelease(cfname);
      cfname = CTFontCopyFullName(ctfont);
      CFRelease(ctfont);
      CFStringGetCString(cfname, f->fontname, ENDOFBUFFER, kCFStringEncodingUTF8);
      CFRelease(cfname);
      }
    else 
#endif
*/
    strlcpy(f->fontname, f->name, ENDOFBUFFER);
    const char* p = f->name;
    if (!p || !*p) {if (ap) *ap = 0; return "";}
    int type = 0;
    if (strstr(f->name, "Bold")) type |= FL_BOLD;
    if (strstr(f->name, "Italic") || strstr(f->name, "Oblique")) type |= FL_ITALIC;
    f->fontname[ENDOFBUFFER] = (char)type;
  }
  if (ap) *ap = f->fontname[ENDOFBUFFER];
  return f->fontname;
}

David

**Comment by w1hkj** [comment]
I should have included the stack trace:

Caught signal 11
Aborting fldigi due to a fatal error.
Please report this to:   [fldigi-devel@sourceforge.net](mailto:fldigi-devel@sourceforge.net)
or file a bug report at: https://fedorahosted.org/fldigi/newticket

****** Stack trace:
0   fldigi                              0x000000010fd676e5 _Z13handle_signali + 21
1   libsystem_platform.dylib            0x00007ff80a923dfd _sigtramp + 29
2   libFontParser.dylib                 0x00007ff81355c5c9 _ZNSt3__110__function6__funcIZNK10TnameTable7GetNameEttttE3$_2NS_9allocatorIS3_EEFvRK17sfntNameRecord_BEimPbEEclES8_OiOmOS9_ + 347
3   fldigi                              0x000000010ff4fbb9 _ZN2Fl13get_font_nameEiPi + 229
4   fldigi                              0x000000010fc1e3c8 _ZN12Font_BrowserC2EiiiiPKc + 1432
5   fldigi                              0x000000010fb97d75 _Z15ConfigureDialogv + 69
6   fldigi                              0x000000010fb97d15 _Z12createConfigv + 21
7   fldigi                              0x000000010fc0056b _Z27create_fl_digi_main_primaryv + 49515
8   fldigi                              0x000000010fc06359 _Z19create_fl_digi_mainiPPc + 25
9   fldigi                              0x000000010fcf3e9c main + 9548
10  dyld                                0x0000000111b6151e start + 462

**Comment by w1hkj** [comment]
Error occurred on MacOS 12.4, I7 processor:

Runtime information:
  system         : Darwin iMac-East.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

**Comment by ManoloFLTK** [comment]
That issue should be fixed now in the git repo (master and branch-1.3).
@w1hjk : please close teh issue if you agree it's fixed.

**Comment by w1hkj** [comment]
Thank you Manolo.
