### ISSUE TITLE
Problems in Fl_Text_Buffer & Fl_Text_Display

### ISSUE THREAD

**Issue by ZJUGKC** [fltk/fltk#456]
In Fl_Text_Buffer.cxx, line 70-76,

```
static char *undobuffer;
static int undobufferlength;
static Fl_Text_Buffer *undowidget;
static int undoat;              // points after insertion
static int undocut;             // number of characters deleted there
static int undoinsert;          // number of characters inserted
static int undoyankcut;         // length of valid contents of buffer, even if undocut=0
```

These global variables are used for implementing Undo/Redo. But they will cause unexcepted results if I create several Fl_Text_Buffer objects in my application. They should be data members of Fl_Text_Buffer.

Furthermore,  I take a proposal for implementing complete Undo/Redo function. We can use two arrays/lists to describe undo-list and redo-list. `can_undo`, `can_redo` and `redo` methods should be added to `Fl_Text_Buffer` and `Fl_Text_Editor`. If these works are complex, I will give up this proposal.

In Fl_Text_Display, line 81-84,

```
static int scroll_direction = 0;
static int scroll_amount = 0;
static int scroll_y = 0;
static int scroll_x = 0;
```

These global variables may cause unexcepted results when I create many Fl_Text_Display objects and show them in a window like tiles.

**Comment by Albrecht-S** [comment]
Thanks for reporting this. You're absolutely right, global (static) variables are bad, particularly for such things like reusable widgets.

**Comment by ZJUGKC** [comment]
The same problem appears in Fl_Input_.cxx, line 725-731.

**Comment by Albrecht-S** [comment]
Thanks for the heads-up.

**Comment by MatthiasWM** [comment]
> In Fl_Text_Display, line 81-84,
> 
> ```
> static int scroll_direction = 0;
> static int scroll_amount = 0;
> static int scroll_y = 0;
> static int scroll_x = 0;
> ```

I agree with the other observations about the undo. The code above however I think is ok. It's only used if text is selected and the mouse button is held down while the pointer is dragged beyond the edge of the widget. Since we only support a single mouse pointer, I don't see how two widgets may use these variables at the same time. 

Please let me know if you observed differently, and how to repeat that.
