### ISSUE TITLE
Fl_Preferences must not read or write a file if the file path could not be constructed correctly

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#46]
Fl_Preferences relies on a few system calls to construct the path to the file that will hold the preference data. If any of those calls fail (for example, $HOME on Linux is not set), the the entire operation must fail and no file must be read or written.

**Comment by MatthiasWM** [comment]
Fixed and tested on macOS, Linux, and MSWindows

**Comment by Albrecht-S** [comment]
It appears to me that these changes would change some of the directories where FLTK stored the preference files in 1.3.x and early 1.4.0 development versions.

If this is true, do we need to document this? Maybe tell users how to migrate their preferences files to the new locations? Anything else?

**Comment by MatthiasWM** [comment]
It should not change the original directories. When generating a preferences filename fails, it will return 0, which generates internal preferences that only last during the lifetime of the app (not perfect, because two preference files may get mixed, may need to change that).

Also, a static buffer for filenames is only allocated if it is actually needed to avoid blocking 2k of RAM at launch time.

On Windows, RegQueryValue() is now checked if it failed, and if it did, no filename is created. Originally, the filename would be C:/FLTK/... which is a bad idea!

On Linux, we still query $HOME first, but if that is not set, or the directory does not exist, we try getpwuid(getuid(), and if that also fails, we return 0.

On MacOS, I decided to use NSHomeDirectory() instead of $HOME. I will change that to what the Linux version does, to first check $HOME and then fall back to NSHomeDirectory(). Again, I return 0 if all fails.

**Comment by Albrecht-S** [comment]
> On Windows, RegQueryValue() is now checked if it failed, and if it did, no filename is created. Originally, the filename would be C:/FLTK/... which is a bad idea!

Yep, I agree (that **WAS** a bad idea) but **this is how it was in the past**. Hence users may have built there preferences files in `C:/FLTK/...` and may lose their old preferences if they don't move them to the new location. Or am I missing anything?

My concern: The same would maybe if you _**changed**_ the storage locations on other OS's (but again, it's hard to understand what would happen from reading the diffs).

Sorry, I couldn't test this, I just saw the changes in the commits, hence my questions.

**Comment by MatthiasWM** [comment]
Phew, well, I guess. The original code read:

```
        DWORD type;
        filename[0] = 0;
        err = RegQueryValueExW( key, L"AppData", 0L, &type,		        
                                (BYTE*)filename, &nn );
         if ( ( err != ERROR_SUCCESS ) && ( type == REG_SZ ) ) {
          filename[0] = 0;
         }
         if (filename[0]==0)
           path = "C:/FLTK/";

```
RegQueryValueExW() can fail if the user has no home directory, which would be on a server as a task started by a web server, for example. Writing to C:/FLTK/ was simply false and caused this bug report to begin with. 

But I leave that up to you. If you prefer, I'll reverse the changes for all platforms.

**Comment by Albrecht-S** [comment]
No, no, I'm all for cleaning this up! I don't see a problem if we **know** about the changes and can document for users what they need to do to keep their existing preferences. That's all, IMHO.

We're going to make a big change (1.3.x to 1.4.0) which is in our definition an ABI breaking change. Some cleanups (like this one: where to store prefs) should be done rather now than later. The only point is that we need to document it if it changes things for users (and devs who worked with 1.4 already).

Thanks for your efforts to improve this!
