### ISSUE TITLE
Multiple cursors in one Fl_Text_Editor instance

### ISSUE THREAD

**Issue by VinnyVicious** [fltk/fltk#460]
Following the trend started by Sublime and adopted by editor widgets like CodeMirror, it would be nice to be able to manage multiple cursors in a single Fl_Text_Editor instance. If you ctrl + click, it creates a new cursor that responds to input.

Examples:
https://codemirror.net/
https://ace.c9.io/build/kitchen-sink.html

**Comment by Albrecht-S** [comment]
Note: "wontfix" label added for clarification.
