### ISSUE TITLE
Multisample antialiasing  doesn't work on fltk opengl

### ISSUE THREAD

**Issue by ar37-rs** [fltk/fltk#483]
I have the same issue as: https://www.fltk.org/newsgroups.php?s1097+gfltk.opengl+v1101
is there any workaround for that? thank you

**Comment by Albrecht-S** [comment]
Sorry, in order to keep our issues maintainable, such user questions are not accepted here. Please see below for instructions where to ask for help. Thank you for your understanding.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
