### ISSUE TITLE
[Wayland, libdecor] Segfault of "tree" demo

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#485]
I can't figure out the exact order of actions reproducing the segfault but it happens after spending some time playing with controls and "Test Suggestions" dialog of `tree` demo program.

Build options: `-DCMAKE_BUILD_TYPE=Debug -DOPTION_USE_WAYLAND=1`
Compiler: `gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)`

It happens on the latest master and default libdecor shipped with FLTK. I have recorded 2 videos proofs :)

https://user-images.githubusercontent.com/6562863/186394511-b46b3ae6-27b3-43e3-bbb7-4436e779869c.mp4

https://user-images.githubusercontent.com/6562863/186393832-835b543f-bcf1-440e-b14e-9945cdfa9321.mp4

Here are the cordeumps (failures in different places inside libdecor's `pointer_motion`):

[tree_coredumps.zip](https://github.com/fltk/fltk/files/9415236/tree_coredumps.zip)

```
#0  0x00000000004c8576 in update_local_cursor (seat=0x2348ed0) at /fltk/libdecor/build/../src/plugins/gtk/libdecor-gtk.c:1994
#1  0x00000000004c89a7 in pointer_motion (data=0x2348ed0, wl_pointer=0x24623f0, time=35034967, surface_x=259544, surface_y=12640)
    at /fltk/libdecor/build/../src/plugins/gtk/libdecor-gtk.c:2122
#2  0x00007ff661831c04 in ffi_call_unix64 () from /lib64/libffi.so.6
#3  0x00007ff661831108 in ffi_call () from /lib64/libffi.so.6
#4  0x00007ff662f9fde0 in wl_closure_invoke.constprop () from /lib64/libwayland-client.so.0
#5  0x00007ff662fa0553 in dispatch_event.isra () from /lib64/libwayland-client.so.0
#6  0x00007ff662fa074c in wl_display_dispatch_queue_pending () from /lib64/libwayland-client.so.0
#7  0x00000000004e2ae0 in fd_callback (fd=3, display=0x2232d40) at /fltk/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:1073
#8  0x00000000004e60e2 in Fl_Unix_System_Driver::poll_or_select (this=0xe151a) at /fltk/src/drivers/Unix/Fl_Unix_System_Driver.cxx:821
#9  0x00000000004e64b0 in Fl_Unix_System_Driver::ready (this=0x222dab0) at /fltk/src/drivers/Unix/Fl_Unix_System_Driver.cxx:862
#10 0x000000000045749b in Fl::wait (time_to_wait=1e+20) at /fltk/src/Fl.cxx:482
#11 0x00000000004574bf in Fl::run () at /fltk/src/Fl.cxx:502
#12 0x0000000000455c65 in main (argc=1, argv=0x7ffcb96a64b8) at /fltk/build/test/tree.cxx:2091
```

I guess that it's a libdecor 's GTK plugin issue, but I'm not sure. Maybe you will understand the root cause more quickly, If it's not a fltk issue I will forward this upstream.
Thank you.

**Comment by Albrecht-S** [comment]
**_OT:_** @polter-rnd Sorry, I can't contribute anything useful here, but I'm interested in the screen recording tool you're using. Can you tell us which tool it is (link?) and if it's free (FOSS) or commercial? Thank you.

**Comment by polter-rnd** [comment]
It's [Kooha](https://github.com/SeaDve/Kooha), GPL3.0. I'm using it's FlatPak build: [io.github.seadve.Kooha](https://flathub.org/apps/details/io.github.seadve.Kooha)

**Comment by Albrecht-S** [comment]
Thanks!

**Comment by ManoloFLTK** [comment]
@polter-rnd : could you, please, report whether the last state of the code in the repo does fix this issue?

**Comment by polter-rnd** [comment]
I'm unable to reproduce it with the latest commits, so closing it, thank you! Will reopen if it will happen again
