### ISSUE TITLE
X11: demo resize after Ctrl+/- wrong

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#491]
This is like #419 for X11.

Seems the cure is the same:

A line like
```cxx
if (Fl_Window::is_a_rescale()) size_range();
```
in `Fl_x.cxx` method `Fl_X11_Window_Driver::resize(int x, int y, int w, int h)`

**Comment by Albrecht-S** [comment]
Thanks, fixed in commit 746135f0aef6e7f45824c22d1a54ac5ab134c1a1.
