### ISSUE TITLE
Wayland: scaling of large menus out of sync

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#493]
Test case:
- run test/menubar
- select 'Huge' menu
- move cursor/mouse up and down.

This works sufficiently well at scaling 100% but fails e.g. at scaling factor 80% but also other scaling factors.

The following screenshot with visible mouse cursor and "Huge" menu was created after moving the cursor down until the menu moves all the way up. After that the highlighted menu item is no longer under the cursor but there are also other misbehaviors. The FLTK scaling factor was at 80%. System was Debian Bullseye in a Virtualbox VM.

![menubar_80](https://user-images.githubusercontent.com/26235500/188213429-5bb788f5-5171-4820-b77b-1bf971e18b9e.png)

@ManoloFLTK This issue is present in current Git (76858fc040052ec50a52d).

**Comment by ManoloFLTK** [comment]
@Albrecht-S : can you confirm it's fixed in the git repo?

**Comment by Albrecht-S** [comment]
Yep, it's fixed. Thank you for the quick fix.
