### ISSUE TITLE
Wayland: Fl_Gl_Window subwindows draw outside their main window

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#494]
@ManoloFLTK The "Fast Shapes" test of `test/unittests` "leaks" its subwindows outside of the main window. The upper unittests instance is, as the title says, running under X11 (FLTK_BACKEND=x11) and works as expected (subwindows are clipped), the 2nd instance (below) was executed under Wayland.
![unittests](https://user-images.githubusercontent.com/26235500/188311723-ebe22dc9-15d2-4ec8-9f50-5150b840b722.png)

- System: Linux Mint 20
- User session: Gnome/Wayland
- FLTK version: Git commit 57e0cdec084f2f080ad55486a255d8ba026bc42f

**Comment by ManoloFLTK** [comment]
The same occurs under macOS :
![macOS](https://user-images.githubusercontent.com/41016272/188381194-d523d5f7-5614-45dc-97cc-052e171d9ce0.jpg)

A widget is allowed to leak outside its enclosing group unless group->clip_children(1) forbids it. Is it certain subwindows must be forbidden from leaking outside their enclosing window ?

**Comment by Albrecht-S** [comment]
> Is it certain subwindows must be forbidden from leaking outside their enclosing window ?

I believe yes, this should always be true but I didn't find it clearly documented anywhere.

- AFAICT Windows and Linux (X11) do this by default, i.e. the windowing system does it for us so we don't need to care in FLTK ourselves.
- I didn't know that macOS would leak GL subwindows. Does it leak "normal" subwindows as well if they are too large?
- I was really surprised to see this under Wayland.

I thought this was documented but the only hint I could find quickly in the docs says something about subwindows and clipping. However, I don't think it applies directly to the situation given here. Anyway, this is what [the docs](https://www.fltk.org/doc-1.4/subclassing.html#subclassing_fl_window) say:

> **_Making a subclass of Fl_Window_**
>
> _You may want your widget to be a subclass of [Fl_Window](https://www.fltk.org/doc-1.4/classFl__Window.html), [Fl_Double_Window](https://www.fltk.org/doc-1.4/classFl__Double__Window.html), or [Fl_Gl_Window](https://www.fltk.org/doc-1.4/classFl__Gl__Window.html). This can be useful if your widget wants to occupy an entire window, and **can also be used to take advantage of system-provided clipping**, or to work with a library that expects a system window ID to indicate where to draw._

(Emphasis in **bold text** added by me)

Generally I would say that **nothing** should ever leak out of any (main) system window. This includes IMHO all kinds of subwindows.

**Comment by ManoloFLTK** [comment]
> I didn't know that macOS would leak GL subwindows. Does it leak "normal" subwindows as well if they are too large?

No, non GL subwindows don't leak under macOS because there's code to prevent it, but this code isn't effective with GL subwindows.

**Comment by ManoloFLTK** [comment]
Commit 13e05f4 fixes this issue for the macOS platform, but not for Wayland.
The documentation of class Fl_Gl_Window now states that the behaviour of sub GL windows that leak outside their parent window is undefined and possibly platform-dependent.

An imperfect solution was found for Wayland, that cannot be committed because it would require any sub GL window to have the FL_ALPHA flag on; that would break source code compatibility with previous FLTK versions.

This issue will be closed. The cross platform solution is for client applications to avoid the creation of leaking sub GL windows.

**Comment by Albrecht-S** [comment]
Thanks.
