### ISSUE TITLE
doxygen docs fltk logo update

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#506]
Currently the doxygen docs use an artifact-ridden yellow "fltk" logo in `documentation/src/FL200.png` that looks like this:

![before](https://user-images.githubusercontent.com/6484779/191955696-cec7f7fb-a9f5-4157-9af0-744fffdd9104.jpg)

Would like to suggest changing the logo to be more like the one on the website's main page for consistency, e.g.

![after](https://user-images.githubusercontent.com/6484779/191955979-1168eb42-dc76-4647-877f-4ed190709861.jpg)

The replacement I'm suggesting being:
![FL200](https://user-images.githubusercontent.com/6484779/191954301-4c2f2d19-105c-437a-9cc2-259de8a79da3.png)

**Comment by erco77** [comment]
Looking for feedback before I make this change.

**Comment by Albrecht-S** [comment]
:+1:

**Comment by ManoloFLTK** [comment]
Yes. It's good to make the doc and the web site more consistent.

@erco77 : do you have any comment about issue #505 which reports a compatibility problem between the present source code to create the HTML doc and recent versions of Doxygen ?

**Comment by erco77** [comment]
I'll make the change.

Regarding issue #505, I did sniff around on the doxygen issues and found some issues related to "mainpage", but not sure if it's the same thing.

**Comment by erco77** [comment]
Fixed in commit 0fd10e9fd, closing.
