### ISSUE TITLE
Cairo drawing: fl_circle() not drawn

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#511]
Sorry, another one: with FLTK Cairo `fl_circle()` is not drawn, when it is not within a shape sequence.
But in this case I think that is simply because a `cairo_stroke()` is missing.

````cxx
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/fl_draw.H>

//-------------------------------------------------------------------------------
class Appl : public Fl_Double_Window
//-------------------------------------------------------------------------------
{
typedef Fl_Double_Window Inherited;
public:
	Appl( int argc_ = 0, const char *argv_[] = 0 ) :
		Inherited( 200, 200, "fl_circle")
	{
		show();
	}
private:
	void draw()
	{
		fl_rectf(0, 0, w(), h(), FL_WHITE);

		fl_color( FL_BLUE );
		fl_circle( w() / 2, h() / 2, w() / 2 - 1); // not drawn + all sub-sequent drawing() maybe wrong
	}
};

//-------------------------------------------------------------------------------
int main( int argc_, const char *argv_[] )
//-------------------------------------------------------------------------------
{
	Appl app( argc_, argv_ );
	app.wait_for_expose();
	return Fl::run();
}
````

**Comment by ManoloFLTK** [comment]
I'm afraid fl_circle() is part of the "drawing complex shapes" API and requires to be preceded by fl_begin_loop() and followed by fl_end_loop() or fl_begin/end_polygon().

**Comment by wcout** [comment]
Well, that has just always worked for me (at least under X11), using it for ages. Is this platform specific?
I have now had a look at the docs: https://fltk.gitlab.io/fltk/group__fl__drawings.html#gac4540eaf7b5f23944cf332fc8f81f57e
It states that `fl_circle()` can be used if it is the "only thing" in the path, whatever this means.
Looking at the code for Xlib it seems for me that provision has been taken for this.

With this change it does also work under Cairo for me:
```diff
diff --git a/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx b/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
index 4421bd610..f51b8fbd7 100644
--- a/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
+++ b/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
@@ -455,6 +455,7 @@ void Fl_Cairo_Graphics_Driver::circle(double x, double y, double r){
     concat();
     cairo_arc(cairo_, x, y, r, 0, 2*M_PI);
     reconcat();
+    cairo_stroke(cairo_);
     cairo_restore(cairo_);
   } else {
     cairo_arc(cairo_, x, y, r, 0, 2*M_PI);
```

**Comment by ManoloFLTK** [comment]
The "path" refered to in the doc by " the only thing in the path" is produced by fl_begin_loop() / fl_end_loop() or fl_begin_polygon() / fl_end_polygon() .

The thing is, fl_circle() will produce a circle with
```
fl_begin_loop();
fl_circle(x, y, r);
fl_end_loop();
```
and a disk with
```
fl_begin_polygon();
fl_circle(x, y, r);
fl_end_polygon();
```
So, it makes sense to require that fl_circle() not be used by itself.

**Comment by ManoloFLTK** [comment]
OK. I see there's support for lone fl_circle() calls in all graphics drivers (unsure with Fl_OpenGL_Graphics_Driver), so it's undocumented but it works. I've committed the corresponding fix in the Cairo driver. Please close the issue if you agree it's fixed.

**Comment by wcout** [comment]
If it is implemented an working, would it not be good to reflect this in the documentation somehow?
A quick search "in the web"I found some occurrences, where code is written/adviced that way e.g.

https://stackoverflow.com/questions/70371915/fltk-clearing-a-graph-when-drawing-another
https://cpp.hotexamples.com/examples/-/-/fl_circle/cpp-fl_circle-function-examples.html
Used in e.g.
https://github.com/3dem/relion/blob/master/src/displayer.cpp

**Comment by ManoloFLTK** [comment]
@Albrecht-S , @imaclmaca : that seems to be a historical thing in FLTK. Should function fl_circle() be officially documented as a member of both the simple and complex drawing APIs?

**Comment by ManoloFLTK** [comment]
The additional documentation of fl_circle() has been added.
