### ISSUE TITLE
Cairo drawing: arc different to X11

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#512]
arc demo comparison X11/Cairo:

![arc_x11_cairo](https://user-images.githubusercontent.com/9895976/194869145-2ebe78a6-3109-4dc2-bed8-d96acd4717f5.png)

**Comment by ManoloFLTK** [comment]
@wcout: This should be fixed now in the git repo. Please, close if you confirm.

**Comment by wcout** [comment]
Re-Open, because I noticed a regression with this commit.
Filled Fl_Dial is not drawn correctly (with Cairo) as seen in the 'valuators' demo:
![fill_dial_regression](https://user-images.githubusercontent.com/9895976/198813041-0bd4f9b0-a8bb-4310-b96b-bf5f1e9d0c37.png)
(It was ok before this commit)

**Comment by ManoloFLTK** [comment]
That should be OK with commit 31ec6f6.

**Comment by wcout** [comment]
Confirmed.
