### ISSUE TITLE
Fl::awake() and Fl::add_timeout()

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#524]
As discussed in fltk.general, thread ["Fl::awake and Fl::add_timeout"](https://groups.google.com/g/fltkgeneral/c/g6g9aWLSANs/m/HXGFipuqAwAJ) the following statements must be **verified** and **documented**:

1. All forms of `Fl::awake()` can be called in the main FLTK thread (e.g. in a timeout callback) and/or in worker threads.
2. All forms of `Fl::awake()` can be called w/o wrapping the call in `Fl::lock()` and `Fl::unlock()`.
3. Since FLTK 1.4.0 `Fl::add_timeout()` and friends can be called in worker threads if and only if they are wrapped in `Fl::lock()` and `Fl::unlock()`.
4. Also: (3) is not allowed in earlier FLTK versions up to the latest 1.3.x versions (see e.g. FLTK 1.3 documentation in chapter ["Advanced FLTK", section "FLTK multithreaded Constraints"](https://www.fltk.org/doc-1.3/advanced.html#advanced_multithreading_caveats)). Current text is: _"Don't start or cancel timers from a worker thread"_. This (1.3.x) text is still the same in 1.4 docs as of today and must be modified and clarified in the latter.

If any point above turns out to be wrong, then this must be documented as well.

**Comment by ManoloFLTK** [comment]
I have verified that statements 1., 2. and 3. above are correct for all platforms, and have changed the documentation accordingly (which takes care of point 4. also).

I have noticed that 1. is correct but requires the initial Fl::lock() call used to initialize thread support. The doc is now explicit about this requirement.

I believe the commit mentionned above fixes the issue. @Albrecht-S Please, close issue if you agree.

I've been using this toy program to create situations 1. 2. and 3. by switching at lines 5-9 preprocessor variables USE_CHILD, USE_TIMEOUT and USE_AWAKECB between values 0 and 1 : 
```
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

#define USE_CHILD 0
#if USE_CHILD
#  define USE_TIMEOUT 0
#endif
#define USE_AWAKECB 0

void awake_cb(void *data) {
  fprintf(stderr,"awake_cb data=%p\n", data);
}
void timeout_cb(void *data) {
  fprintf(stderr,"timeout_cb data=%p\n", data);
}


#if USE_CHILD
#ifndef _WIN32
#  define HAVE_PTHREAD_H 1
#endif
#include <test/threads.h>

extern "C" void* child_func(void* p)
{
  fprintf(stderr,"child starts\n");
#if USE_TIMEOUT
  Fl::lock();
  fprintf(stderr,"add timeout\n");
  Fl::add_timeout(1, timeout_cb, p);
  Fl::unlock();
#else // !USE_TIMEOUT
#  if USE_AWAKECB
    Fl::awake(awake_cb, p);
#  else
    Fl::awake( p);
#  endif
#endif // USE_TIMEOUT
  return NULL;
}
#endif // USE_CHILD

int main(int argc, char **argv) {
  Fl::lock();
  Fl_Window *window = new Fl_Window(340, 180);
  fprintf(stderr,"window=%p\n",window);
  Fl_Box *box = new Fl_Box(20, 40, 300, 100, "Hello, World!");
  box->box(FL_UP_BOX);
  box->labelfont(FL_BOLD + FL_ITALIC);
  box->labelsize(36);
  box->labeltype(FL_SHADOW_LABEL);
  window->end();
  window->show(argc, argv);
  
#if USE_CHILD
  Fl_Thread child_thread;
  fl_create_thread(child_thread, child_func, window);
#else // !USE_CHILD
#  if USE_AWAKECB
    Fl::awake(awake_cb, window);
#  else
    Fl::awake( window);
#  endif
#endif // USE_CHILD
  while (Fl::first_window()) {
    Fl::wait(1000);
    void *message = Fl::thread_message();
    if (message)
      fprintf(stderr, "received thread message=%p\n",message);
  }
  return 0;
}
```

**Comment by Albrecht-S** [comment]
@manoThanks for taking this, for the test program, and for updating the docs.

I agree that this issue is fixed and I'm closing it now.
