### ISSUE TITLE
AFAIK, there is no standard way to cancel a DnD operation .

### ISSUE THREAD

**Issue by mroe1** [fltk/fltk#525]
**Is your feature request related to a problem? Please describe.**
Although no such method officially existed, it was common for x11 to abort a DnD simply by calling Fl::pushed(0); .
Apparently this doesn't work with Wayland .
No wonder, but we need a way to achieve that somehow.

**I am using FLTK**
1.4.0

**Describe the solution you'd like**
Possibly a new standard method like cancel_dnd() for all platforms. 

**Describe alternatives you've considered**
Finding a reasonable and permanent Wayland-specific solution to canceling a DnD.
As a last resort, we'd be poking around in the 'FLTK Wayland System Driver' somehow individually.

**Additional context**

**Comment by mroe1** [comment]
1.) Right , from within the program.
In our case we cancel the DnD when leaving the own app area/window because we can not set a own specific content type.
Our data are wrapped in a own container.
The dragged content in FLTK can be only plain/text or image and could wrongly inserted elsewhere.

2.) This was the solution for x11 only.
Unfortunately, I can't find the discussion anymore. Will add the source if I can find it again.

3.) It is about doing it from within the program. 1.)

**Comment by Albrecht-S** [comment]
Thanks for answering the questions. It's all clear now.

> Our data are wrapped in an own container. The dragged content in FLTK can be only plain/text or image ...

Okay, this opens another question, not directly related to this problem. Would it help if you could set a specific content type (free text, your own responsibility). This would (if implemented in FLTK) replace the offered types so other applications would not accept the drag and thus you could also drag to another window of your own application - which would then have to request (also a new FLTK feature) and accept your specific data type. It's just a thought, not an offer that we could do quickly or at all.

**Comment by mroe1** [comment]
Yes ,  a specific content type would be also a solution. Canceling the DnD in our case was even a workaround to prevent dropping the [text] payload somewhere else. 

Just to mention , 
Win api has  QueryContinueDrag function to handle such.

**Comment by ManoloFLTK** [comment]
@mroe1 Commit eb679f9 should make FLTK's Wayland platform behave as its X11 platform accepting a call to Fl::pushed(0); as "unofficial" way to cancel a DnD operation. Can you confirm? That is not a platform-independent solution, but should correspond to your initial need.

**Comment by mroe1** [comment]
@ManoloFLTK Confirmed it works. Thanks for the implementation.

**Comment by mroe1** [comment]
@ManoloFLTK 
Oh. Excuse me. It is actually _not_ working with the Wayland flavor for me. Was obviously still x11 backend in first tests.
Calling Fl::pushed(0) within FL_DND_LEAVE . Ubuntu 20.04/22.04, Fedora.

**Comment by ManoloFLTK** [comment]
@mroe1  I added `Fl::pushed(0);` to the `FL_DND_LEAVE` section of  program `examples/howto-drag-and-drop.cxx`, and it works here with Wayland. So, I need an example program of what you do that doesn't work with Wayland.

**Comment by mroe1** [comment]
@ManoloFLTK 
Have tested it with 'examples/howto-drag-and-drop.cxx' as you describe. 
- Added Fl::pushed(0) in LEAVE_DnD  of receiver.
- Started a drag from Sender and move through the receiver window to trigger the  Dnd_leave event there .

x11 :     cancel Dnd  is working , drag is canceled as expected( e.g. unable to drop when move back to the receiver)
But there is another strange side effect now :
If the drag goes through another open window(e.g. editor , this app closes suddenly.(This is only with the example , not with e.g. our app) 

Wayland:  drag is not canceled , the drag is still active and can be drop-ed everywhere. 

.................
Unfortunately, can not find something what is possibly messed up on my side.
Will try to debug what happens on to some point .

**Comment by ManoloFLTK** [comment]
Here is the 1-line change I applied :
```
diff --git a/examples/howto-drag-and-drop.cxx b/examples/howto-drag-and-drop.cxx
index 856838d..7b9fce7 100644
--- a/examples/howto-drag-and-drop.cxx
+++ b/examples/howto-drag-and-drop.cxx
@@ -116,6 +116,7 @@ public:
         fprintf(stderr, "FL_DND_LEAVE\n");
         dnd_inside = 0;         // status: mouse is outside, don't accept drop
         ret = 1;                // return(1) anyway..
+Fl::pushed(0);
         break;
     }
     return(ret);

```
Then, under Wayland, if I drag from sender to receiver, string "It works!" is dropped and shown in a popup window.
If I drag through and continue out of the receiver and then back in, nothing is dropped.
I don't see dragging through a neighbor editor window causing any problem.

Apart from suggesting there could be a mixture of diverse commits, I've no idea to explain what you see.

**Comment by ManoloFLTK** [comment]
A possibility: if you use
#if !FLTK_USE_X11
  Fl::pushed(0);
#endif   
expecting this code to run under the Wayland platform, that's wrong, because the Wayland platform's code is hybrid to support both Wayland and X11 and to select only at run-time which one is used.

What should be done is
#if FLTK_USE_X11
  Fl::pushed(0);
#endif   
and this code will run under both legs of the hybrid Wayland/X11 libfltk.

**Comment by mroe1** [comment]
@ManoloFLTK
Well, have to admit i testing in  VM's.
Also X-Wayland is involved if x11.
What i can tell so far at this point , the 'cancel of DnD' with Wayland works so far that the Drag is not accepted in the receiver anymore after the canceling happened after leave.
The content ("It works!'") is also deleted ,but i'am still able to let drop "empty" into an other open [e.g Editor or Filebrowser] window.

**Comment by ManoloFLTK** [comment]
Yes, after `Fl::pushed(0);` has run, receiver FLTK widgets or other clients receive an empty string ("") when the mouse button is released. Isn't that what you wanted to achieve, that the private dragged data be made invisible to other potential receivers ?

**Comment by mroe1** [comment]
<Isn't that what you wanted to achieve, that the private dragged data be made invisible to other potential receivers ?>

Thats one part to avoid . But also not dropping content somewhere else by accident.There is still plain/text offered to the extern recievers which they mostly allow.
In the x11 variant Fl::pushed(0) leads to fully cancel the DnD operation.

**Comment by ManoloFLTK** [comment]
Consider the modified `howto-drag-and-drop` program and run it.
Drag from sender to an external receiver, say a terminal window, and drop: "It works" is dropped.
Drag from sender through receiver and continue to the terminal window and drop: nothing is dropped.

Repeat the same operations under X11: the same effects happen.

Thus, I don't see what other part should be avoided.

**Comment by mroe1** [comment]
Don't want to split hairs.But here is one example.
On Ubuntu , File explorer is a  candidate that absolutely wants doing something with it.

**Comment by ManoloFLTK** [comment]
I've looked at dragging from howto-drag-and-drop and dropping to Ubuntu's "Files" app.

Under Wayland, both howto-drag-and-drop and Ubuntu's "Text Editor" do the same: a text file called "Dropped Text.txt" is created and contains the dragged text. If the dragging goes in and out of howto-drag-and-drop's receiver target widget, the dragged text becomes "" and thus the text file is created empty.

Under X11, "Text Editor" does the same as what howto-drag-and-drop does under Wayland, that is, the "Dropped Text.txt" file is created by the receiving "Files" app.
[This runs "Text Editor" under X11: `WAYLAND_DISPLAY=NONE gnome-text-editor&` ]

Overall, I see howto-drag-and-drop under Wayland doing the same as a native gnome app, and hiding the private dragged text to any potential receiver app once the dragging cursor has been in and out from the receiver widget.

**Comment by ManoloFLTK** [comment]
With commit 38536d8, the drag-n-drop operation should be terminated after exiting from the target widget, so the "Files" application should not create an empty "Dropped Text.txt" file.

**Comment by ManoloFLTK** [comment]
@mroe1  It should be better with commit 9c793a3

**Comment by Albrecht-S** [comment]
@ManoloFLTK @mroe1 This seems to be fixed, can this issue be closed?

**Comment by mroe1** [comment]
yes , works very well, can happily closed.

**Comment by Albrecht-S** [comment]
@mroe1 Thanks for confirmation. Closing the issue now.
