### ISSUE TITLE
Wayland - modifier keys have no effect with mouse actions

### ISSUE THREAD

**Issue by mroe1** [fltk/fltk#534]
**Describe the bug**
modifier keys (e.g Shift,ctrl,alt) have no effect with mouse actions with Wayland.
In our app that is also buggy because  Fl::event_state()  gives zero or bogus values.

**To Reproduce**
you can see it in test/file_chooser

- run file_chooser 
- select 'multi' and hit 'open file-browser'
- try to select a bunch of files by SHIFT+MouseClick first to last
  or more then one files with CTRL+MouseClick

**Expected behavior**
modifier keys can have effect with mouse actions

**FLTK Version**
 - 1.4.0
 - Downloaded and self-built from: Git master

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - Linux
 - Ubuntu 20.04,

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Additional context**

**Comment by ManoloFLTK** [comment]
@mroe1   Good catch. That should be fixed with commit 402b08c. Please, close issue if you confirm.
