### ISSUE TITLE
FLTK-1.3.8 error when building in Visual Studio

### ISSUE THREAD

**Issue by mech-man7** [fltk/fltk#535]
When I build fltk 1.3.8 in Visual Studio I get these two errors: 
1) "syntax error: 'constant'" in line 6651 in file winnt.h
2) "unexpected token(s) preceeding ';'" in the same file and line
Am I doing something wrong here? I followed the readme file for MSWindows and the build stops with these errors. Thanks in advance if anyone can offer any help.

**Comment by Albrecht-S** [comment]
There is no file named `winnt.h` in our FLTK distribution, i.e. there is either something wrong with your setup (Visual Studio) or you are maybe doing something wrong. However, without more info we can't help, and this is the wrong place to ask for help. Please see below for instructions where you should ask your question.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

That said, I'm closing this issue with label "no user support", please ask in fltk.general. Thanks for your understanding.
