### ISSUE TITLE
Cairo: Scaled images draw with wrong size

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#537]
The right and bottom pixel line (or top/left?) is missing.

Demo program: 
[image_draw_size.cxx.txt](https://github.com/fltk/fltk/files/9994511/image_draw_size.cxx.txt)

Result X11 (should be):
![image_draw_size_x11](https://user-images.githubusercontent.com/9895976/201465200-a3dbf7b4-efd0-4fa1-b6a8-f727056f1410.png)

Result Cairo (wrong):
![image_draw_size_cairo](https://user-images.githubusercontent.com/9895976/201465222-c3e8223c-aa5a-49a6-a356-95030cca69b0.png)

**Comment by ManoloFLTK** [comment]
This is not a final response, but just a recommendation, to start with.

In that case, it's useful to set to 1 the `high_res` parameter of the [Fl_Image_Surface 
constructor](https://fltk.gitlab.io/fltk/classFl__Image__Surface.html#a48b726fdd17920f263c80b776f175b70)
which fixes the test program given here. The benefit is that there will be as many pixels in the offscreen image as in the display area where it will be drawn, avoiding the blur effect that occurs when images are enlarged while drawn.

**Comment by wcout** [comment]
@ManoloFLTK After much experimenting I'd like you to look over a change in the cairo driver, that with my limited tests (with tiled images, unitests, my test program from above,..) does not display any of the problems so far:

[cairo_image_draw.diff.txt](https://github.com/fltk/fltk/files/10003712/cairo_image_draw.diff.txt)

It also implements a way of regarding the scaling mode set with `Fl_RGB_Image::scaling_algorithmn()`.

I changed `test/tile.cxx` in order to able to test it with all image types:

[tiled_image_from_arg.diff.txt](https://github.com/fltk/fltk/files/10003738/tiled_image_from_arg.diff.txt)

**Comment by wcout** [comment]
Hm, so the change is essentially the `double(img->data_w()) > Ws`check?

With my test now with `tiled_image <file> -b` I never see the bilinear filter applied.
Can you please explain your reasoning?

**Comment by ManoloFLTK** [comment]
My reasoning is
1) with your test program image_draw_size.cxx modified to use FL_RGB_SCALING_BILINEAR, the output is better (not blurred) with CAIRO_FILTER_FAST than with CAIRO_FILTER_GOOD.
2) using pixmap_browser which uses FL_RGB_SCALING_BILINEAR  to read and display images that have more pixels than contained in the area where they are drawn shows that CAIRO_FILTER_GOOD gives a much better result than CAIRO_FILTER_FAST.

Overall, the outcome is to use CAIRO_FILTER_GOOD when FLTK uses FL_RGB_SCALING_BILINEAR and when the image is drawn shrinked, but not when it's drawn enlarged.

I may have missed something.

**Comment by wcout** [comment]
Ok, I see your intention now.
But I don't agree for these reasons:
1. My test program is a special case with only straight lines, it is evident that it can not be enlarged by a bilinear filter without blurring. All other cases, when the image contains realistic content I see improvement also when enlarging with the bilinear (good) filter.
2. I would not want FLTK to decide not to use of a filter that is explicitly set by the application on its own reasoning. That's why the filter is settable and the application should select it by its own criteria.

**Comment by ManoloFLTK** [comment]
@wcout The issue should be fixed with commit 167a326. Many thanks for finding the solution. Please close issue if you agree.

**Comment by wcout** [comment]
Hi @ManoloFLTK !
I was still fiddling around with this, because I tried to check all the different image types (bitmap, pixmap,...).

On the way I encountered a problem with  `XBM` images, demonstrated with the following program:
````cxx
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_XBM_Image.H>
#include <FL/Fl_Box.H>
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <cstdlib>
#include <cassert>
#include <config.h>

static const char TITLE[] =
#ifdef FLTK_USE_CAIRO
	"Cairo"
#else
	"X11"
#endif
;

class TestWin : public Fl_Double_Window {
public:
	TestWin() : Fl_Double_Window(100, 100, TITLE),
		_image(new Fl_XBM_Image("test.xbm"))
	{
		if (_image && _image->w() && _image->h())
		{
			size(_image->w()*2, _image->h());
			_canvas = new Fl_Box(_image->w(), 0, _image->w(), _image->h());
			_canvas->image(_image);
			show();
		}
	}
	void draw() {
		Fl_Double_Window::draw();
		fl_rectf(0, 0, _image->w(), _image->h(), FL_YELLOW);
		_image->draw( 0, 0 );
	}
private:
	Fl_Image *_image;
	Fl_Box *_canvas;
};

int main() {
	TestWin win;
	return Fl::run();
}

```` 

It results in this output (Note: I used `test/pixmaps/sorceress.xbm` as `test.xbm`)
![xbm_test](https://user-images.githubusercontent.com/9895976/202379220-3960477b-d2c7-482d-a956-e3cf7cd4d72c.png)

So when drawn with `image->draw()` (left side) it does draw nothing, whereas when used as widget image (right side) it shows correctly.

This is with Cairo  **and** with X11!

And it brings me to the next thing: In the Cairo version, when I change the `draw_cached_pattern` method to **not** use the `if  img->d() >= 1)` lines (I changed them to `if img->d() >= 0` to disable them) then the left image is displayed correctly!
So I wonder what these lines are useful for. I could not find an image type so far, that does not display correctly if they are not used.

**Comment by ManoloFLTK** [comment]
The left half of the window remains yellow because Fl_Bitmap images are special in that they are drawn **using the current color.** Thus, your code
```
    fl_rectf(0, 0, _image->w(), _image->h(), FL_YELLOW);
    _image->draw( 0, 0 );
```
draws a yellow bitmap on a yellow background, producing just yellow !
You need to set the desired color before calling draw on the Fl_Bitmap, e.g. :
```
    fl_rectf(0, 0, _image->w(), _image->h(), FL_YELLOW);
    fl_color(FL_BLUE);
    _image->draw( 0, 0 );
```
and then both Cairo and X11 (and macOS too) work OK.

**Comment by wcout** [comment]
One last thing.
As the Cairo driver handles all images types with the same code, also the non RGB image types get the RGB scaling filter applied (which is normally thought for Fl_RGB_Image's only). This is different from X11, because there bitmaps and pixmaps are rendered separately from RGB images.
But as Cairo's default filter is CAIRO_FILTER_GOOD anyway, it makes no difference. And I don't think it's worth to mimic the X11 behaviour and explicitly render bitmaps and pixmaps with CAIRO_FILTER_FAST. 
What's your opinion?

**Comment by ManoloFLTK** [comment]
I've no competence/knowledge whatsoever about image filters. I can just observe results on displays. I notice that the Fl_Pixmap image of program test/device is much better with CAIRO_FILTER_GOOD than with CAIRO_FILTER_FAST when enlarged to 133% or shrunk to 67%. Overall, the current status of image drawing with FLTK's Cairo graphics driver, with your help, seems good to my eyes.

**Comment by wcout** [comment]
> Overall, the current status of image drawing with FLTK's Cairo graphics driver seems good to my eyes.

That is also my observation. Thank you for implementing.

**Comment by ManoloFLTK** [comment]
Reopening this because the fix destroys various things in test/mandelbrot :
- the scene is often solid black when the app looses focus
- the selection rectangle is not properly deleted when scaling has a fractional value
