### ISSUE TITLE
FLTK build error under linux/wayland

### ISSUE THREAD

**Issue by ZJUGKC** [fltk/fltk#538]
When I build FLTK 1.4.0 (master, the latest commit, 8d636d9) under linux/wayland, an error is raised.

I use ubuntu server 22.04 (libwayland-dev package has been installed),
and input the following commands:

```
cmake <fltk-src-path> -DCMAKE_BUILD_TYPE=Debug -DOPTION_USE_WAYLAND=ON -DOPTION_WAYLAND_ONLY=ON -G "Unix Makefiles"
make
```

See error: 

![error](https://user-images.githubusercontent.com/5561846/201466929-ec0f9a66-22a5-4571-89cf-b7c9ef626c0f.png)

If I remove `-DOPTION_WAYLAND_ONLY=ON`, above error is also raised.

**Comment by ManoloFLTK** [comment]
You're probably missing package "wayland-protocols" (see section 4.1 of README.Wayland.txt)

Please, note that -DOPTION_WAYLAND_ONLY=1 is mostly meant for very special cross compiling situations where the target system lacks libX11, which is not true of Ubuntu.

**Comment by ZJUGKC** [comment]
Thank you very much. Now I can build FLTK 1.4.0 under linux/wayland after installing the proposed packages in `README.Wayland.txt` manually. There are some other problems raised, but they are not suitable for discussion in this issue.

Now I close this issue.
