### ISSUE TITLE
[Cairo]: Arrows have a "gap"

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#561]
Since commit ecc47d0cc3e1784e17ac94829202f2bdbd38a682 arrows under Cairo driver drawing have a small vertical gap.

E.g. seen with the `symbols` demo:
![cairo_arrow_gap](https://user-images.githubusercontent.com/9895976/204309894-201642f0-8c37-441a-99c6-85355e1441a5.png)

**Comment by Albrecht-S** [comment]
Thanks for the report. I don't have time to look into it right now, but are you sure that the mentioned commit is really the cause?

I wonder how the given commit would change symbol drawing (although these symbols are "arrows"). Symbol drawing is implemented in `src/fl_symbols.cxx` which has not been changed by this commit.

Please make sure that your build is clean and complete (e.g. `make distclean; autoconf; make -jN`) - or use CMake which is more reliable than the dependencies used in configure/make builds.

If you can still see these diffs, please report your exact build steps and configuration so we can try to reproduce this.

**Comment by wcout** [comment]
You are right of course, it has nothing to do with this commit (I *did* check with the previous commit , but didn't reconfigure, and it created a pure X11 build, as the default has changed during this period, which I didn't realize). Sorry for the mistake.
So this seems to be there for a long time with the Cairo driver.
It can be observed better with `unitests`, section "Symbol Text".

**Comment by Albrecht-S** [comment]
Thanks for clarification. If it has to do with the Cairo driver this is very likely something for @ManoloFLTK. Manolo?

**Comment by ManoloFLTK** [comment]
That should be fixed now.

**Comment by ManoloFLTK** [comment]
Unfortunately, the proposed fix breaks drawing of rotated arrows under X11.
More work needed…

**Comment by ManoloFLTK** [comment]
I believe arrow drawing is now fixed with commit 00884f2.
@wcout Please, close issue if you confirm.

**Comment by wcout** [comment]
Confirming. Tested with X11 and Cairo.
