### ISSUE TITLE
FYI - fluid command line option '-o .cpp' not working in latest 1.4

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#562]
I have an application makefile rule that creates `.h` and `.cpp` files from a source FLUID `.fl` file. Of course, the default is for fluid to create a `.cxx` file but I want a `.cpp` extension, so I have been using the `-o .cpp` command line option to achieve that (for a long time). That is not working now in the latest 1.4. I checked the latest FLTK doco and the `-o` option is not there, so I am faced with a small mystery. I have not researched which commit introduced the issue though.

Naturally, the simple workaround for me is to modify my makefile to rename the generated `.cxx` file to have the `.cpp` extension, so I am entering this issue just FYI.

**Comment by MatthiasWM** [comment]
Thanks for letting us know. I made some changes around the FLUID command line interpreter. I'll check this probably tomorrow and fix the issue. Note that you can also change the extension in Project Settings. I will verify both of these options and fix them accordingly.

**Comment by MatthiasWM** [comment]
Ok, I found the bug. It's should be fixed in the next 24h. Thanks again for letting us know quickly.

**Comment by MatthiasWM** [comment]
This is fixed in 8f9728d511f45c98bc505cdd4f0f8bdbc99dd1a2 .
