### ISSUE TITLE
FLTK 1.4 unit test "complex shapes": OpenGL versions not all drawing correctly

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#567]
Certain of the complex shapes on the OpenGL side of this unit test do not draw correctly as compared to their "native" counterparts. The boundaries are OK, but for certain ones, the fill is not. For example, the shape on the far right side of line 2a, and the middle shape on line 3a.

Please see the attached screenshot.

![FLTK_unittests_complexshapes](https://user-images.githubusercontent.com/18319324/205058514-58b78155-e84f-46cf-b7ff-7b86a4ae2603.png)

**Comment by MatthiasWM** [comment]
Yes, thanks you. That is pretty much the reason fro writing this test. I remembered that OpenGL does not do complex polygons, but I have two different approaches that could fix this, and this app is for verification.

**Comment by pdhahn** [comment]
Works perfectly on my system now after the fix. FYI I really like this feature - thanks!

**Comment by MatthiasWM** [comment]
Thanks. I am happy to hear that you like it. I hope to see some new UI implementations popping up soon. :-)
