### ISSUE TITLE
Text positioning different in 1.4.x vs 1.3.x (new pango default +1 pixel on x and y)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#568]
**Describe the bug**
When pulling 1.4.x into my applications, I noticed all the text on buttons and menus seemed off-center by +1 on x and y, vs. my 1.3.4-2 builds which seem normal. It's noticeable in my app because I use small buttons with the text inside, so text alignment issues are easy to see.

~~I also see this issue comparing 1.3.4-2 and 1.3.x current git, so the change happened somewhere after 1.3.4-2.~~

**To Reproduce**
Run the test/radio demo and compare. **Here's an animation comparing the radio demo in 1.3.4-2 vs. 1.4.x:**
![fltk-text-anim](https://user-images.githubusercontent.com/6484779/205161223-33cae018-dccd-4fd3-9162-eb59881dfa9c.gif)

1. Build 1.3.x with default 'configure/make', run test/radio
2. Build 1.4.x with default 'configure/make', run test/radio
3. Compare screenshots of the two, noting text positioning offset

Hopefully the above animation shows the issue clearly. You can see how the "radio 1/2/3/4" text is now touching the group border box, whereas before it didn't. It seems ALL text is offset by +1 on x/y.

**FLTK Version**
 - Version: 1.4.x and 1.3.x current (as compared to 1.3.4-2)

**FLTK Configure / Build Options**
Default configure/make.

**Operating System / Platform:**
This is on Linux Ubuntu 20.04.05 with default gnome window manager.

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by erco77** [comment]
OK, narrowed it down a little.
I focused on 1.3.x, and the problem cropped up AFTER the 1.3.8 release.
Which is to say I don't see the problem in 1.3.7 or 1.3.8 tar files, it's only in the current git for 1.3.x and 1.4.x.

**Comment by erco77** [comment]
Thought it would be good to compare the unittests -> rendering text screens:
![fltk-unittests-text](https://user-images.githubusercontent.com/6484779/205167038-be2eadd2-d4da-42e0-91d6-c7f69a96f837.gif)
Definitely something going on there.

**Comment by wcout** [comment]
I think you are seeing here the difference between `Xft` vs. `Pango` text drawing.
Look into `config.h` for the `USE_PANGO` define.
There was a change of Make defaults recently (0ba051994a5b6a928db90a439461a37386e4d8e1), so the default configure/make uses Cairo/Pango for drawing if the Wayland libraries are present on your system.

**Comment by erco77** [comment]
Having trouble turning pango off to test; `./configure --disable-pango` or `cmake -D OPTION_USE_PANGO=Off`, the log still shows pango being 'yes':
```
$ cmake -D OPTION_USE_PANGO=Off ..
                      \__________ THIS SHOULD TURN IT OFF BUT..
-- Looking for png.h
-- Looking for png.h - found

-- Configuration Summary for FLTK 1.4.0 generated by CMake 3.16.3 --

-- The following OPTIONAL packages have been found:

 * Doxygen
 * LATEX
 * JPEG
 * ZLIB
 * PNG

-- Static libraries will be built in /usr/local/src/fltk-1.3.x-git/build/lib
-- Shared libraries will not be built (set OPTION_BUILD_SHARED_LIBS=ON to build)
-- FLUID will be built in /usr/local/src/fltk-1.3.x-git/build/bin/fluid
-- Test programs    will be built in /usr/local/src/fltk-1.3.x-git/build/bin/test
-- Example programs will not be built (set FLTK_BUILD_EXAMPLES=ON to build)
-- Image Libraries: JPEG = System
--                  PNG  = System
--                  ZLIB = System
-- Use Wayland:             Yes (when available at run-time)
-- All drawing uses Cairo:  Yes
-- Use Pango:               Yes                    <-- HEY!!!
-- Fl_Cairo_Window support: No

-- End of Configuration Summary --

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/fltk-1.3.x-git/build
```
Looking in config.h, I see `#define USE_PANGO 1`. I get similar results with `./configure --disable-pango`.

Sure seems like something is off though, as I'd have to refactor a fair bit of code to get things lined up again.

**Comment by wcout** [comment]
Use `./configure --disable-wayland`

**Comment by erco77** [comment]
OK, looks like I had to disable cairo too, e.g. `cmake -D OPTION_USE_PANGO=Off -D OPTION_USE_CAIRO=No ..`

(I did try disabling wayland, but that didn't affect it -- seems to be if cairo is on, pango will be too)

And yes, turning that off seems to make the issue go away.. thanks!
Still not sure if that isn't something to be corrected though -- leaving this open for now.

The machine I'm working on now is X only, not wayland. I do have other wayland machines, not this one.
(which is to say Xorg is in the process table, and wayland is not) cmake is apparently detecting the presence of wayland dev libraries though, which are, for whatever reason, on this machine.

**Comment by wcout** [comment]
Interesting playground...  I put in some printf's into `unittest_text.cxx` and used other texts. Though in most cases the dimensions are quite near, some combinations of characters produce quite different widths (e.g. "ioio..."). Also, though some dimesions are *reported* similar, the screen output is not similar e.g. with the first test "AWX..."), the red measure box entends considerably beyond the text on the right side.

X11
````
fl_measure(AWXAWXAWXAWXAWXAWX): 432x36
fl_text_extents(AWXAWXAWXAWXAWXAWX): 433x22 (-1/-22)
fl_measure(#####): 125x36
fl_text_extents(#####): 123x22 (1/-22)
fl_measure(WWWWWWWWWW): 300x36
fl_text_extents(WWWWWWWWWW): 300x22 (0/-22)
fl_measure(ioioioioio): 130x36
fl_text_extents(ioioioioio): 128x23 (2/-23)
fl_measure(________): 120x36
fl_text_extents(________): 122x3 (-1/4)
````
Wayland:
````
fl_measure(AWXAWXAWXAWXAWXAWX): 432x36
fl_text_extents(AWXAWXAWXAWXAWXAWX): 420x22 (0/-21)
fl_measure(#####): 130x36
fl_text_extents(#####): 126x22 (2/-21)
fl_measure(WWWWWWWWWW): 300x36
fl_text_extents(WWWWWWWWWW): 299x22 (1/-21)
fl_measure(ioioioioio): 140x36
fl_text_extents(ioioioioio): 137x23 (2/-22)
fl_measure(________): 120x36
fl_text_extents(________): 122x3 (-1/4)

````

**Comment by ManoloFLTK** [comment]
Several factors are at work here.

1) Switching from xft to Pango+Cairo for text drawing slightly changes font widths, font names, line heights, and possibly text positionning. I will see if text positionning can be improved.

2) The Wayland platform uses Pango+Cairo for text, without any other option. It's been decided the X11 leg of the hybrid Wayland/X11 platform would also use Pango for text. Consequently, the X11 leg of the hybrid Wayland/X11 **is not always the same as** the X11 platform: first draws text with Pango+Cairo -- second with xft or optionally with Pango. This decision can be reversed, if needed.
This explains why --disable-wayland or cmake -DOPTION_USE_WAYLAND=Off is needed to get rid of Pango for text. Under X11, it's possible to turn Pango on or off.

3) It's been decided the hybrid Wayland/X11 platform would be the default configuration obtained when building FLTK, considering that such library can decide at run-time to run either under X11 or Wayland.
Thus, unless running "configure --disable-wayland" or "cmake -DOPTION_USE_WAYLAND=Off", the build procedure checks whether the software packages (e.g., libwayland-dev) are present on the system. If they are, it produces a hybrid Wayland/X11 libfltk. If they are not, it produces a "traditional" X11-based libfltk. Item 2) above makes clear that the hybrid library always draws text with Pango. Greg's system most probably has all software packages required to produce the hybrid library, even if Greg doesn't run the Wayland-enabled desktop. Greg obtains a hybrid Wayland/X11 libfltk which draws text with Pango but runs FLTK apps as X11 clients.

4) Kerning changes the space between characters in a string. Typical cases are "fi"  and "AW" where kerning reduces the offset between these 2 pairs of characters. The result is that the lengths of string "AWXAWXAWXAWXAWXAWX" with and without kerning differ conspicuously.
Kerning is absent in xft and Windows GDI.
Kerning is turned off by FLTK in macOS platform.
Kerning applies in Pango. Despite much efforts, I didn't find how to turn it off. Any hint about how to do that is much welcome. 
FLTK computes string widths (fl_measure()) by adding precomputed, single-character widths. That is necessary for width computation to be quick as required when Fl_Text_Editor holds a large text with line wrapping.
fl_text_extents() does not add up single-character widths but considers the whole string with its kerning, if any.
This explains the differences reported by wcout above.

**Comment by erco77** [comment]
So here's a comparison of 1.3.x (with all defaults) vs. 1.4.x with pango/wayland/cairo disabled, and small changes aside, they behave exactly the same from a text rendering point of view:
![fltk-1 3 x-vs-1 4 x-no-pango](https://user-images.githubusercontent.com/6484779/205312845-642967e2-67f9-4a73-8886-af1922ade430.gif)

I'll repair my previous comments, as I think the two versions to compare are FLTK 1.4.x with and without pango, and I'll re-edit the title accordingly so the info in this bug is more accurate.

**Comment by erco77** [comment]
OK, so I guess this is normal when switching renderers.
Now that I look at the above, it seems like with pango on vs. off, it isn't just that _all_ text is off by +1 on x/y, which was my concern, as that'd be an obvious fix.

But it does _maybe_ seem like text closer to the top left doesn't offset as much as it does the further away.
The first "radio comparison" animation seems to show the text for the top/left button barely moves, but as you move progressively downward, the text offset is more and more noticeable. Similarly, I think, for the x axis.

**Comment by ManoloFLTK** [comment]
> But it does _maybe_ seem like text closer to the top left doesn't offset as much as it does the further away. The first "radio comparison" animation seems to show the text for the top/left button barely moves, but as you move progressively downward, the text offset is more and more noticeable. Similarly, I think, for the x axis.

I attach the output of the test/radio demo app where each Pango-drawn text is accompanied by a short horizontal red line starting at the string's (x,y) position.
This is obtained adding this
`int c=fl_color();fl_color(FL_RED);fl_xyline(x,y,x+10);fl_color(c);`
at the end of function
`void Fl_Cairo_Graphics_Driver::draw(const char* str, int n, float x, float y) `
in file `src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx` .

I don't perceive there a drift between text and red line along growing x or y coordinates.


![PangoOffset](https://user-images.githubusercontent.com/41016272/205330894-df8c089c-a927-4fcb-97dd-c7c130c9d182.jpg)

**Comment by ManoloFLTK** [comment]
@erco77 The last commit (e5c3cae) is expected to fix the +1 offset reported when drawing text with Pango and is included in the red line experiment above.

**Comment by wcout** [comment]
@ManoloFLTK There is also significant difference in the line heights between Xft and Cairo+Pango, which can be observed with the leftside menu of the unittest "video" from the second comment here.
Interestingly I found that the Xft+Pango version (`--disable-wayland --enable-pango`) does have the **same** line heights as the pure Xft version.
So I guess it could be done under Cairo+Pango too?

**Comment by erco77** [comment]
Thanks Manolo, you're awesome as always!

**That seems to have fixed it**; I pulled the latest 1.4.x and here's the comparison of unittests between my old 1.4.x "pango off" screenshot, and building with your new fix with pango et al turned on (basically default cmake/make).
This is much better!
![pangofix](https://user-images.githubusercontent.com/6484779/205336263-f39d0f64-0aae-44e9-8851-4c012c348c6c.gif)

Two things I notice in the animation, perhaps unrelated: 

- the selected text in the unittest browser ("Rendering text"), the descender on the "g" seems to be drawing off the bottom of the blue background rectangle.
- the focus box (dotted line) seems.. different? disabled?

I'm guessing the focus box is unrelated, but perhaps the text inside the selection box being "one down" is related?

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks for the attempt to fix positioning, but I believe the fix made it better in x direction and worse in y direction, as compared to the x11 rendering which we seem to use as the basis. I'm uploading three screenshots:

1. original X11 version (standard):

![radio-x11](https://user-images.githubusercontent.com/26235500/205347327-96cb5925-08ce-461d-954f-116654d5df15.png)

2. previous Wayland version:

![radio-wayland](https://user-images.githubusercontent.com/26235500/205347382-166c4a44-ea3c-473a-9f82-d48d7ee29bea.png)

3. new Wayland version (git e5c3caeb6b3824eb933cbb3acc57365d9b2ed6d4):

![radio-wayland-2](https://user-images.githubusercontent.com/26235500/205347456-6b95bf93-655b-4d24-ab6d-1aa510044e0a.png)

If you open these three images in three different browser tabs (by clicking on them) and scale these tabs as you like (e.g.  200%) and then click on them in order (below) you'll see:

From 1 to 2 (original comparison posted by Greg, now with my screenshots): the text seems to "move" right and down, as observed.

From 2 to 3 (old Wayland -> new Wayland): text moves "back" to the left (good) but **even more downwards** (bad).

From 3 to 1 (new Wayland -> X11): text moves back to the left and upwards.

From 1 to 3 (X11 to new Wayland): text moves downwards significantly (stays correct in x direction).

Note that some "movement" is caused by centering, i.e. you should always look at the middle of the text when comparing x direction.

Conclusion: the fix in x direction appears to be correct but the attempted fix in y direction should perhaps be in the opposite direction (?)

@ManoloFLTK I didn't try to "fix" this, just providing the data (images). Looking forward to your comment.

PS: I'm using FLTK's "-title" commandline argument to set the window title which can be very helpful for such comparisons.

PPS: My Wayland build was configured with the Cairo plugin.

**Comment by ManoloFLTK** [comment]
> @ManoloFLTK There is also significant difference in the line heights between Xft and Cairo+Pango, which can be observed with the leftside menu of the unittest "video" from the second comment here. Interestingly I found that the Xft+Pango version (`--disable-wayland --enable-pango`) does have the **same** line heights as the pure Xft version. So I guess it could be done under Cairo+Pango too?

No. The font difference is not caused by Pango but by Cairo vs xft. So,  Xft+Pango uses the same font and therefore line heights as xft, whereas Pango+Cairo uses Cairo fonts that produce some differences in line heights.

**Comment by erco77** [comment]
Here's a [text grid program](https://github.com/fltk/fltk/files/10144814/grid-src.zip) showing manolo's recent fix, comparing pango on+off. The text is drawn using fl_text(s,x,y), no use of alignment or the font measuring stuff:
![wordgrid-pango-on-off](https://user-images.githubusercontent.com/6484779/205401863-c55b61f2-dedc-4aed-a5d1-d3c6a9abfda5.gif)


Looks very acceptable to me as far as text placement is concerned. The kerning differs a tiny bit, but perhaps that's to be expected. It's the vertical and horizontal position of the first letter of each word moving around that was my primary concern initially.

I'll try to follow up with something else, as I need to catch up on the thread on fltk.coredev.

**Comment by erco77** [comment]
..and here's the same grid program compiled against pango/no pango before manolo's fix, just to show the x/y offset thing. Seems much better!
![wordgrid-pango-on-off-pre-fix](https://user-images.githubusercontent.com/6484779/205402571-ca0f9db8-e753-4d01-9bbf-7066dc737432.gif)

**Comment by ManoloFLTK** [comment]
@erco77 Focus box drawing is repaired. The problem was that dotted line + antialiasing fused the whole thing into a continuous line.

**Comment by ManoloFLTK** [comment]
@Albrecht-S I attach what I get under Debian sid with Wayland inside my virtual machine on a retina display. I see labels nicely positioned both horizontally and vertically.

![RadioDebianWayland](https://user-images.githubusercontent.com/41016272/205427527-15f87312-9ab8-49a6-962d-9449b11d2112.jpg)

**Comment by wcout** [comment]
I can confirm all sides ;)
- Under Ubuntu 20.04 @ManoloFLTK's  fix makes the y direction of the radio buttons of `radio.cxx` even worse, as @Albrecht-S mentions
- Under Ubuntu 22.04 the fix looks correct, just as Manolo shows in the above screenshot
- @erco77's  `grid.cxx`  looks correct under Ubuntu 20.04 - I see the same animation as Erco posted when comparing with Xft (Erco states he is using 20.04).

Can this be a Pango issue (a change between the versions*)? But why does it show only with the radio buttons?

Would be interesting to know, what @erco77 sees with the `radio` demo..

*)
Pango version Ubuntu 20.04: `1.44-7-2ubuntu4`
Pango version Ubuntu 22.04: `1.50-6+ds-2`

**Comment by erco77** [comment]
So going a little deeper, the radio widget issues are I think related to the fact the label for that is drawn with FL_ALIGN_XXX flags that affect x,y positioning of text drawing, which looks at things like `fl_descent()` and `fl_height()`, and in my experiments those functions return different values between pango vs no pango. specifically:
```
    pango off:  fl_descent()=4  fl_height()=17
    pango on:   fl_descent()=3  fl_height()=18
```

Suffice it to say I went down the rabbit hole, and came up with that being the cause of the +2 y offset for the radio labels.
Read on for more details, **but I think focusing on why those are different will lead to the final fix.**
___

To figure this out, I made a small [myradio.zip](https://github.com/fltk/fltk/files/10147629/myradio.zip) test program that just creates an instead of an Fl_Round_Button similar to the test/radio demo. Then I added some printf()s to the src/fl_draw.cxx and src/fl_labeltype.cxx code to see what the x,y values are for the text. With just the one widget, that widget's label text is the only text being drawn, so it's easy to see the x,y text coordinates for just that widget.

I found the x,y value for drawing the text of the label being passed to the "high level" fl_draw() is consistent across pango vs non-pango, but that call takes an align value, so one has to go deeper to see how that affects the x,y value for drawing the actual text position.

The high level fl_draw() calls a lower level fl_draw() that handles the actual calculations for FL_ALIGN_XXX. In my test case, the align value ends up being 20 (decimal), or (FL_ALIGN_INSIDE | FL_ALIGN_LEFT).

This causes the following effective calculation to compute the actual Y value for drawing, the value in parens being the value of each part of the formula, where ypos ends up being the final Y position for drawing the text:

```
pango off: ypos(29) = y(10) + ( h(30) - lines(1) * fl_height(17) - imgh(0) ) / 2 + fl_height(17) - fl_descent(4)
pango on:  ypos(31) = y(10) + ( h(30) - lines(1) * fl_height(18) - imgh(0) ) / 2 + fl_height(18) - fl_descent(3)
```
Note the different values for fl_height() and fl_descent() when combined with that formula cause a +2 offset for the `pango on` scenario.

**Comment by erco77** [comment]
Attaching a small [showvals.zip](https://github.com/fltk/fltk/files/10147708/showvals.zip) program that just prints the values of `fl_height()` and `fl_descent()` and exits.

This makes it easy to see what the values are with different builds of FLTK. Right now I get this output:

```
pango off: fl_height()=17 fl_descent()=4
pango  on: fl_height()=18 fl_descent()=3
```
I suppose the goal would be to get those `pango on` values the same as `pango off`, so old programs have consistent results.

**Comment by ManoloFLTK** [comment]
> I suppose the goal would be to get those pango on values the same as pango off, so old programs have consistent results.

I would be wary of following this goal because height and descent values are given by the font metrics itself and these values apparently change with Pango versions as shown by @wcout 's comment above (the change between Pango 1.44 and 1.50 seems to be for the good). Furthermore, xft and Pango+Cairo are 2 different font mechanisms,

Height and descent values are computed in the constructor of `Fl_Cairo_Font_Descriptor` in `src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx`. The code therein merely follows the Pango API to get height and descent, supplemented with a small addition of mine where the FLTK fontsize is multiplied by 0.75 in order for the resulting font visible helght to match what is produced by Xft. Notice that height and descent values there are in Pango units, that need be divided by PANGO_SCALE (=1024) to obtain pixels. It's also possible to argue about how to convert height/float(PANGO_SCALE) to an integer value : FLTK presently rounds the result up with `ceil()`: see `Fl_Cairo_Graphics_Driver::height()` .

Pango font metrics are detailed [there](https://docs.gtk.org/Pango/struct.FontMetrics.html). The "Strikethrough position" mentionned therein, which is not handled by FLTK presently, may be of interest.

**Comment by ManoloFLTK** [comment]
With commit 1b938ab, fl_height() == fl_size() for all fonts and sizes. That might do good.

**Comment by wcout** [comment]
> With commit https://github.com/fltk/fltk/commit/1b938ab8b1ec3087366700a43110a8c6e58694fe, fl_height() == fl_size() for all fonts and sizes. That might do good.

Wow! Now the line distances are the same as with Xft. A pleasant side effect :+1: 

The y positioning in `radio` has also improved:
- With Ubuntu 20.04 **all** texts in the widget are y+1 (in resp. to Xft version)
- With Ubuntu 22.04 only the left side side button texts are y+1, the right side 'radio' text y are ok

Here my screenshots:

Ubuntu 20.04 Xft (the "should be" version):
![radio_2004_xft](https://user-images.githubusercontent.com/9895976/205490565-9ebb894d-7104-4734-ae86-752c25939669.png)

Ubuntu 20.04 Pango:
![radio_2004_pango](https://user-images.githubusercontent.com/9895976/205490583-7dd3379d-9a0e-40e3-bcd4-de0835dce79a.png)

Ubuntu 22.04 Pango:
![radio_2204_pango](https://user-images.githubusercontent.com/9895976/205490595-0a27b864-d413-4556-803b-917ba0ead88f.png)

**Comment by Albrecht-S** [comment]
Thanks, @ManoloFLTK, commit 1b938ab8b1ec3087366700a43110a8c6e58694fe looks good. I'd say that everything is resolved and I won't follow this issue anymore. Thanks to all participating devs and to @wcout for his tests and comments.

I agree to close this issue if @erco77 and @ManoloFLTK agree.

**Comment by erco77** [comment]
Seems the "label hopping" is affected by labelsize().

I noticed the radio app had the button(s) using an unusual size, labelsize(13), so I made a small app that just made buttons with different label sizes, 13 thru 16. Here's the results, pango vs no pango:

![fontsizes-pango-vs-nopango](https://user-images.githubusercontent.com/6484779/206046278-63feb622-d2f7-492d-8db4-e529111058fd.gif)

It's interesting how sizes 15 and 16 are locked into place, but 13 and 14 are down a pixel relative to xft. Probably a rounding thing, and is perhaps splitting hairs. I'll see if I can at least track it down.

**Comment by erco77** [comment]
FTR, more sizes..
![fontsizes-pango-vs-nopango](https://user-images.githubusercontent.com/6484779/206047956-4e459998-2d46-4880-9fde-6f2e81b655a3.gif)

**Comment by erco77** [comment]
So seems simple enough; at different labelsize() values, the fl_descent() and fl_height()
values disagree by +/-1, and that causes the "hopping". Made a table comparing the values.

If this isn't worth persuing, I'll close -- just wanted to figure out what was going on.
My guess is floating point rounding or similar differences in the font rendering.


            labelsize() vs. fl_descent() / fl_height()
            ==========================================

    Xft                              Pango
    ----------------------------     ----------------------------
    size  7: descent=2 height=9      size  7: descent=2 height=9
    size  8: descent=2 height=10     size  8: descent=2 height=10
    size  9: descent=3 height=12     size  9: descent=2 height=11
    size 10: descent=3 height=13     size 10: descent=2 height=12
    size 11: descent=3 height=14     size 11: descent=3 height=13
    size 12: descent=3 height=15     size 12: descent=3 height=14
    size 13: descent=4 height=17     size 13: descent=3 height=16
    size 14: descent=4 height=17     size 14: descent=3 height=17
    size 15: descent=4 height=18     size 15: descent=4 height=18
    size 16: descent=4 height=19     size 16: descent=4 height=19
    size 17: descent=5 height=21     size 17: descent=4 height=20
    size 18: descent=5 height=22     size 18: descent=4 height=21

**Comment by erco77** [comment]
Attaching the code for the buttons and printing the descent/height report.
[buttonsizes.zip](https://github.com/fltk/fltk/files/10171283/buttonsizes.zip)
Gonna stop here to see if it's worth further investigation or not.

**Comment by wcout** [comment]
So just to complete, I added the values of my Ubuntu 22.04 version (comparison marks are to Xft):

`````
                           labelsize() vs. fl_descent() / fl_height()
                           ==========================================

Xft                              Pango (Ubuntu 20-04)                  Pango (Ubuntu 22.04)
----------------------------     ----------------------------          ----------------------------
size  7: descent=2 height=9      size  7: descent=2 height=9           size  7: descent=2 height=9
size  8: descent=2 height=10     size  8: descent=2 height=10          size  8: descent=2 height=10
size  9: descent=3 height=12     size  9: descent=2 height=11   <--    size  9: descent=3 height=11  <---
size 10: descent=3 height=13     size 10: descent=2 height=12   <--    size 10: descent=3 height=12  <---
size 11: descent=3 height=14     size 11: descent=3 height=13   <--    size 11: descent=3 height=13  <---
size 12: descent=3 height=15     size 12: descent=3 height=14   <--    size 12: descent=3 height=14  <---
size 13: descent=4 height=17     size 13: descent=3 height=16   <--    size 13: descent=4 height=16  <---
size 14: descent=4 height=17     size 14: descent=3 height=17   <--    size 14: descent=4 height=17
size 15: descent=4 height=18     size 15: descent=4 height=18          size 15: descent=4 height=18         
size 16: descent=4 height=19     size 16: descent=4 height=19          size 16: descent=4 height=19
size 17: descent=5 height=21     size 17: descent=4 height=20   <--    size 17: descent=5 height=20  <---
size 18: descent=5 height=22     size 18: descent=4 height=21   <--    size 18: descent=5 height=21  <---
`````
The descent values are identical to Xft, but the height values are increasing very nicely.

**Comment by wcout** [comment]
Maybe of interest: When using the `line_height` computation for Pango version < 1.44, which is contained in `Fl_Cairo_Graphics_Driver.cxx` the results of Ubuntu 20.04 and Ubuntu 22.04 become identical.

For testing I changed:
````diff
diff --git a/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx b/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
index c05456861..060315541 100644
--- a/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
+++ b/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
@@ -1135,7 +1135,7 @@ Fl_Cairo_Font_Descriptor::Fl_Cairo_Font_Descriptor(const char* name, Fl_Fontsize
   PangoFontMetrics *metrics = pango_fontset_get_metrics(fontset);
   ascent = pango_font_metrics_get_ascent(metrics);
   descent = pango_font_metrics_get_descent(metrics);
-#if PANGO_VERSION_CHECK(1,44,0)
+#if PANGO_VERSION_CHECK(1,50,6)
   line_height = pango_font_metrics_get_height(metrics); // 1.44
 #else
   line_height = (pango_font_metrics_get_ascent(metrics) + pango_font_metrics_get_descent(metrics)) * 1.025 + 0.5;
````
Advantage of this change would be, that with the current git version under Ubuntu 20.04 the underscore characters `_` become visible again in the editor, which they are currently not, at least on my machine.

I also tested current FLTK with an "old" Ubuntu 18.04 (Cairo version definitely < 1.44) and the results are very good.
So I wonder if the old line_width method shouldn't be used always (With the change above the "new" method is used with Ubuntu 22.04, which has Pango version 1.50.6).

**Comment by Albrecht-S** [comment]
@wcout Thank you for further looking into this. Your suggestion seems sensible but I'm personally not going to investigate this further. I'm leaving the decision to others.

Note to all: I notice the issue with invisible underline characters also on my Linux Mint 20 (based on Ubuntu 20.04) in its editor `xed` and maybe other tools as well. Increasing the font size helps ... sometimes. This could indicate that this is also due to the used Pango version on Ubuntu 20.04. Maybe this was a regression and is fixed in a later Pango version (1.50.6 or whatever) and we can assume that older versions are broken and newer versions will hopefully not break it again.

**Comment by erco77** [comment]
@wcout -- Wow, yeah, on Ubuntu 20.04 I can confirm running `test/editor` with a default build and typing just underbar,
* nothing * shows up at all; it's like I was typing spaces.

Applying your fix solves that for me on this particular machine. FWIW, when I run `pango-view -version` I get `1.44.7`.

Underbars (_) and overlines (‾) and unicode box characters would surely be good thing to include in the unittests for all the multiline widgets to ensure they draw properly. I was happy to find that with the @wcout fix our test/editor demo can actually show unicode box drawing just fine -- check this out:

![image](https://user-images.githubusercontent.com/6484779/206822053-6be2ec47-7cae-4207-a51b-99ff08a34fe9.png)

I find it _super impressive_ there's no artifacts. Woohoo! For many years most browsers couldn't do that properly. For laughs, pasting here in github just to test our browsers:
```
◫◫◫◫◫◫◫◫▮▮▮▮▯▯▯▯
▯▯▯▯
╳ ╳ ╳ ╳ █ █ █ █ ▏▏▏▏  ◢◣  ┏━━┓  ╔══╗  ╔═╦═╗  ██████
╳ ╳ ╳ ╳ █ █ █ █ ▏▏▏▏  ◥◤  ┃  ┃  ║  ║  ╠═╬═╣  ██  ██
╳ ╳ ╳ ╳ █ █ █ █ ▏▏▏▏      ┗━━┛  ╚══╝  ╚═╩═╝  ██████

underbar: ______
 overbar: ‾‾‾‾‾‾

underbar/overbar alternate:

___‾‾‾___‾‾‾___‾‾‾___‾‾‾___
‾‾‾___‾‾‾___‾‾‾___‾‾‾___‾‾‾

```

In addition to boxdrawing chars in the unittests, perhaps also something like an animation that alternates between showing a fixed screenshot image (snapped from a known working system) that alternates showing in its place the actual widget, and having it flip back and forth as a comparision similar to the animations in this issue.

**Comment by Albrecht-S** [comment]
@erco77 Very impressive demo, thanks.
> FWIW, when I run pango-view --version I get 1.44.7.

Same here (Mint 20/Ubuntu 20.04).

Regarding the patch: If I understand correctly the only change would be that:
- we assume the first "correct" (good) Pango version is `1.50.6` rather than `1.44.0` and
- our fallback code is "better" than what we'd get with "broken" Pango version(s) before `1.50.6`

I don't think that this can be wrong, hence I'm also

+1 on @wcout's patch :+1:

**Comment by Albrecht-S** [comment]
@erco77 Regarding unittests: I'd say, feel free to add more tests or change existing tests to use more/different characters. Adding a slider to change the font size would also be good (IMHO).

I wouldn't want to add an image to flip image vs. text though. When I had a similar "problem" with the "Drawing Images" test (question: how should it look?) I decided to add the image to the docs (in chapter ["Example Applications"](https://www.fltk.org/doc-1.4/examples.html#examples_unittests_images)).

Reasoning: you can never make the images superimposable (correct word?) for an animation because of different pixel-wise layout, platform specific differences and **certainly** if you change font sizes. But a "correct" example image in the docs would be helpful for devs and users.

**Comment by ManoloFLTK** [comment]
Thanks to @wcout for the proposed change of use of function pango_font_metrics_get_height(). This is now committed (8dcd121).

@erco77 Please, consider to close the issue if you agree.

**Comment by erco77** [comment]
Yes, thanks Manolo + wcout -- this looks much better for the buttons too (screenshot below). The size=15 is a little off, but at that size it's not that noticeable.

Thanks everyone! Closing.

![wcout-fix-applied](https://user-images.githubusercontent.com/6484779/206870969-233bd972-7b7f-438a-850d-352b232234ad.gif)

**Comment by erco77** [comment]
@Albrecht-S I added a branch to master called "unittest-with-unicode" which has the new unittests feature called "Unicode boxes", which looks like this:

![image](https://user-images.githubusercontent.com/6484779/206880459-eb16a60f-1a56-4a94-8f4a-6fc2fff35ffd.png)

I'm not sure why, but on my system FLTK can't seem to show FL_COURIER as a courier font.. it apparently shows it in the same font as FL_SCREEN, which is a fixed width non-courier font (shrug), but it draws the boxes correctly. If that looks OK I'll merge it to master and delete the branch. (Hoping that's a good git development approach)

**Comment by Albrecht-S** [comment]
> I added a branch to master called "unittest-with-unicode" which has the new unittests feature ...
> ... (Hoping that's a good git development approach)

That's technically correct but for our project we try to avoid unfinished development branches in the main fltk/fltk repository. It's OK for now (no need to remove it), but please use your own fork for future additions. The reason is that FLTK **users** don't need to "pull" unfinished stuff which would otherwise happen (bandwith etc.). One branch may not be an issue, but many branches and maybe large images make a difference.

> ... If that looks OK I'll merge it to master and delete the branch.

Please take care not to "merge" it (literally). It should be squashed and rebased such that we get only one new commit at the tip of master. Otherwise (in a real "merge") every commit would be kept in the repository forever (see above, bandwidth...).

AFAICT it looks good. I have two minor comments though. I see (when applying your branch as a patch [1]):
```
$ git diff --check master
test/unittest_unicode_utf8.h:3: trailing whitespace.
+static const char *utf8_box_test = <<< trailing whitespace here
```
Please remove the trailing space. We shouldn't have trailing whitespace (I'm removing it from time to time with a script which adds otherwise unnecessary commits).

I suggest to make the title use "title spelling", i.e. "Unicode Boxes" (uppercase B) for consistency. All but one selections use this spelling ("Rendering **text**"). Please correct me if this is "wrong".

**Comment by erco77** [comment]
Sounds good to me.. I guess I'll fix "Rendering text" too, as that's what I went by.
I'll also include the README-unittests.txt that I posted in the fltk.coredev thread "Question about prefixes in unittests".
And with that we should be done here for this issue.

**Comment by Albrecht-S** [comment]
:+1: Looking forward to your "squashed and rebased" commit (and deletion of the branch). Thanks.

**Comment by erco77** [comment]
Done.

Those trailing spaces apparently get me because `gitk` doesn't highlight them, even though `git diff` does. I often use `gitk` just to stay on top of things, but that is one feature it seems to be lacking.

**Comment by Albrecht-S** [comment]
> I often use gitk just to stay on top of things, but that is one feature it seems to be lacking.

Yes, so do I, but before committing I recommend `git gui`. It flags trailing spaces and you can easily commit - only some files or only parts of files (replaces `git add` and `git commit` in a very useful GUI). You can really see **what** you are going to commit.
