### ISSUE TITLE
Build on FreeBSD fails: linux/input.h not found

### ISSUE THREAD

**Issue by ngortheone** [fltk/fltk#584]
Configuration succeeds with
```
 cmake -D 'OPTION_USE_WAYLAND=ON' -D 'OPTION_WAYLAND_ONLY=ON' ..
```

Then `make` fails with:
```
[ 33%] Building CXX object src/CMakeFiles/fltk.dir/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx.o
/home/ngor/tmp/fltk/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:35:10: fatal error: 'linux/input.h' file not found
#include <linux/input.h>
         ^~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /opt/ngor/tmp/fltk/build
*** Error code 1

Stop.
make[1]: stopped in /opt/ngor/tmp/fltk/build
*** Error code 1

Stop.
make: stopped in /opt/ngor/tmp/fltk/build
```

Expected result:
- build does not fail,
- or configuration fails if necessary library is missing.

**Comment by ngortheone** [comment]
Missing package was [devel/evdev-proto](http://www.freshports.org/devel/evdev-proto)

**Comment by Albrecht-S** [comment]
Thanks for the report and for the solution.

This requirement is documented in [README.Wayland.txt](https://github.com/fltk/fltk/blob/8dea6505e92a93156820ea24f1256f08cf2b9e8f/README.Wayland.txt#L232).

Is there anything else we can do? If not, please close the issue.

**Comment by ngortheone** [comment]
@Albrecht-S can CMake check if `linux/input.h` is present during configuration?

**Comment by Albrecht-S** [comment]
@ManoloFLTK The primary issue is resolved, but the OP @ngortheone asked after closing this issue:
> can CMake check if linux/input.h is present during configuration?

I see that this file is included in Wayland builds unconditionally but I don't know what we could do to help users if it's not installed. Under FreeBSD the required package was `devel/evdev-proto` which is documented. I believe that the build would fall back to X11 build if that file doesn't exist but if `OPTION_WAYLAND_ONLY=ON` is set it doesn't and fails consequently.

Maybe you, Manolo, have an idea what to check under which circumstances and which warning or error message to issue?

If not, please reply here and close the issue again. Thanks.

**Comment by ManoloFLTK** [comment]
@ngortheone  Could you, please, apply the attached small patch which should have CMake check for presence of `linux/input.h` and report if that works and is what you expected.


[freebsd.patch.txt](https://github.com/fltk/fltk/files/10205147/freebsd.patch.txt)

**Comment by ngortheone** [comment]
Sorry for late report. The issue is indeed fixed. Cmake reports the error now

```
-- Looking for linux/input.h - not found
CMake Error at CMake/options.cmake:273 (message):
  Required include file 'linux/input.h' is missing.  Please install package
  'evdev-proto'
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)

```

Thanks a lot!
