### ISSUE TITLE
[FEATURE] Wayland layer shell protocol support

### ISSUE THREAD

**Issue by ngortheone** [fltk/fltk#593]
Is it possible to use wayland's layer shell with fltk? Layer Shell is wlroots protocol that allows an application to occupy an exclusive area on the screen (overlay, anchored to screen anchors etc.). This is highly useful for building shell components like bars, panels, login screens, etc.

Protocol description
https://wayland.app/protocols/wlr-layer-shell-unstable-v1
https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/protocol/wlr-layer-shell-unstable-v1.xml

Demo of the protocol by Drew DeVault: https://www.youtube.com/watch?v=VuRXHJu5Kmg

Similar GTK project, that adds layer shell to gtk3
https://github.com/wmww/gtk-layer-shell

An example panel project that uses gtk-layer-shell
https://github.com/Alexays/Waybar

Theoretically this shouldn't be very difficult. An existing xdg-tooplevel window surface is upgraded to the new role - layer shell.
But I don't know fltk well enough if this is easily doable.

Thanks

**Comment by ManoloFLTK** [comment]
I don't think this request fits with FLTK's general aims because FLTK features must be expressible in Unix, Linux, Windows and macOS. Moreover, I read that the layer shell is not supported by the Mutter Wayland compositor. This feature appears therefore too specialized for FLTK.

**Comment by ngortheone** [comment]
@ManoloFLTK is it possible for fltk programmer to get a raw window handle (wayland surface in case of wayland driver) and to the wayland server instance/socket?

This could enable programmers to use layer-shell protocol without explicit support in fltk. Programmers could write their own code to change the role of the surface.

https://github.com/slint-ui/slint/discussions/1765

**Comment by MoAlyousef** [comment]
On wayland, FLTL exposes fl_wl_surface() and fl_wl_display(), maybe these can be used for layer shell support?

**Comment by ManoloFLTK** [comment]
As @MoAlyousef writes, FLTK gives public access to a few internal objects of its Wayland platform. 
Please, read [here](https://fltk.gitlab.io/fltk/wayland_8H.html) for a list of all functions with that purpose.

Function `fl_wl_surface()` gives access to the surface of a window FLTK has previously created. I suspect it might be too late to change its role. That's where function `fl_wl_compositor()` might be handy to construct a fresh wl_surface with
`struct wl_surface *my_wl_surface = wl_compositor_create_surface(fl_wl_compositor(());`
