### ISSUE TITLE
`Fl_Simple_Terminal` should not use `wrap()` mode, but instead wrap at a fixed boundary by inserting '\n'

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#595]
**Is your feature request related to a problem? Please describe.**
Fl_Text_Display, the base of Fl_Simple_Terminal, can become quite slow if wrap mode is activated. I am planning on improving that ASAP, but the basic problem will remain. Fl_Simple_Terminal can become relatively slow when large amounts of text (in particular, text without '\n' in them) are logged. This can be accelerated a lot if wrap() mode is disabled.

**I am using FLTK**
1.4.0

**Describe the solution you'd like**
 I suggest to wrap automatically at character 80, or at a user-settable character x position, because Fl_Simple_Terminal will likely use a fixed font and likely log output from other apps. It should still be possible to enable wrap mode if needed.

**Describe alternatives you've considered**
Qt, but FLTK is so much nicer. And smaller. And without license fees. And the developers are just awesome.

_[Edit by @Albrecht-S: fixed a few typos.]_

**Comment by Albrecht-S** [comment]
I'm not sure if I understand the request correctly. I would not want to **insert** `\n` in the actual data (FLTK should not change user data) but I agree that the **display** should (or could) wrap at a given position.

**Comment by erco77** [comment]
@MatthiasWM -1 for inserting \n's or in any way changing the user's text, aside from ansi() parsing and special character handling like backspace (I'm recently adding this btw).

I think it's important that long lines wrap for display purposes only, and unwrap when the widget is made larger, so long output can be read continuously. It'd be OK to have clipping be an option and a horizontal scrollbar appear only if anything clips. (Not sure if the base widget handles that well tho -- I seem to have memory of the horiz scrollbar appearing when it shouldn't under certain circumstances)

**Comment by erco77** [comment]
BTW, it appears I'll be modifying FST's ansi() parsing code quite a bit to support some new features that are needed (my recent comment sin issue #577), so if we're both working on that code, there might be conflicts.
