### ISSUE TITLE
Recent macos build issues

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#598]
**Describe the bug**
CI breakage on macos-latest with appleclang 13 (while it seems appleclang 14 accepts the code):
```
/Users/runner/work/fltk-rs/fltk-rs/fltk-sys/cfltk/fltk/src/Fl_Native_File_Chooser_MAC.mm:577:37: error: non-constant-expression cannot be narrowed from type 'int' to 'CGFloat' (aka 'double') in initializer list [-Wc++11-narrowing]
[452](https://github.com/fltk-rs/fltk-rs/actions/runs/3708314829/jobs/6285747669#step:6:453)
    NSRect hidden_files_rect = {{150, (filter ? 35 : 0)}, {80, 30}};
^~~~~~~~~~~~~~~~~
[454](https://github.com/fltk-rs/fltk-rs/actions/runs/3708314829/jobs/6285747669#step:6:455)
  /Users/runner/work/fltk-rs/fltk-rs/fltk-sys/cfltk/fltk/src/Fl_Native_File_Chooser_MAC.mm:577:37: note: insert an explicit cast to silence this issue
[455](https://github.com/fltk-rs/fltk-rs/actions/runs/3708314829/jobs/6285747669#step:6:456)
    NSRect hidden_files_rect = {{150, (filter ? 35 : 0)}, {80, 30}};
[456](https://github.com/fltk-rs/fltk-rs/actions/runs/3708314829/jobs/6285747669#step:6:457)
                                      ^~~~~~~~~~~~~~~~~
[457](https://github.com/fltk-rs/fltk-rs/actions/runs/3708314829/jobs/6285747669#step:6:458)
                                      static_cast<CGFloat>( )
```
According to clang docs, some Wc++11-narrowing diagnostics seem to be enabled by default. 

**To Reproduce**
Incidentally noticed when git pulling latest FLTK changes in fltk-rs

Build FLTK on macos-latest

**Expected behavior**
Successfull build

**Screenshots**
N/A

**FLTK Version**
 - Version: 1.4 (master)
 - Downloaded and self-built from:  Git as submodule
 
**FLTK Configure / Build Options**
The only difference seems to be in the compiler version, whereas appleclang 13 fails and appleclang 14 succeeds (as shown from FLTK’s github action logs)

**Operating System / Platform:**
Macos 12 intel x64.

**Comment by ManoloFLTK** [comment]
That should be fixed now. Please close this issue if you confirm.

**Comment by MoAlyousef** [comment]
All green. Thank you
