### ISSUE TITLE
Use screen DPI if Xft.dpi is unset.

### ISSUE THREAD

**Issue by nick87720z** [fltk/fltk#600]
Current fltk requires Xft.dpi for scaling. Screen resolution, autodetected by X, is collected, but unused.

**I am using FLTK**
 - Version 1.4.x (commit 64d8c913be441ae2d2179399a624e4279192ee7b)

**Describe the solution you'd like**
In case if Xft.dpi is not configured (not in `xrdb -query` output), `desktop_scale_factor()` driver method could use screen DPI for scaling. Optionally this value could be used for `current_xft_dpi`.

**Additional context**
I'm experimenting with virtual multiplied resolution for subpixel rendering, so trying to get as much as possible apps with as correct as possible DPI. Qt5 and gtk2 are other toolkits, using screen DPI if Xft.dpi is unconfigured (also there's patch for gtk3 to undo regressive commit, removing same functionality).

**Comment by ManoloFLTK** [comment]
Could you, please, provide a procedure to create a situation under Linux (Debian if possible) where Xft.dpi is undefined ? That will help us fixing this issue.

Do you suggest to use the dpi returned by function Fl::screen_dpi() when Xft.dpi is undefined?

**Comment by nick87720z** [comment]
> Do you suggest to use the dpi returned by function Fl::screen_dpi() when Xft.dpi is undefined?

Right.

Example situation: either custom xsession of just anything like fluxbox or so. Also, xfce4 allowes to use default font settings without modification (not saved to xfce4-settings database), which also means it could be not in `~/.Xresources`. Can't remember about other DE (KDE, mate).

**Comment by ManoloFLTK** [comment]
@nick87720z  Please, could you apply the attached small patch and report whether it does what you expect ?

[dpi.patch.txt](https://github.com/fltk/fltk/files/10309560/dpi.patch.txt)

**Comment by ManoloFLTK** [comment]
The tests I can run here are based on a Debian system inside a virtual machine with a HighDPI display. FLTK uses both XRandR and Xinerama to get the screen's pixel size and mm size. 
It obtains correct pixel sizes but wrong mm sizes. XRandR and Xinerama are equally wrong.

In that situation, and unless another source of information for the mm display size can be recruited, I believe FLTK will not be able to detect HighDPI displays without help from the Xft.dpi resource.

**Comment by nick87720z** [comment]
I checked two places to get screen size in mm: xrandr and xdpyinfo. Never used xinerama, because not using multi-monitor setups. I figured out - there are at least two versions for EDID standard. One allowes up to 10mm precision, other - 1mm.

E.g., my display size is 344x193mm. This seems to be highest precision, with which it may be configured. I wrote it to conf file in xorg.conf.d. And this is how xdpyinfo displays it.

xrandr displays only as 340mm x 190mm, even after `xrandr --fbmm 344x193`, which affects xdpyinfo output as well.

Though I can't be sure, my current setup is solid - I just looked to xorg log and noticed, that it still autodetects DPI 96, despite I removed that cli option from lightdm.conf.

(still need to look at that patch)

**Comment by nick87720z** [comment]
I think, patch is fine, but there may be problems, depenging on configuration and used backend (xrandr vs xinerama).

For context: I have configured xrandr scale 3..0 while doing own experiments with fullscreen antialiasing using picom shader (shader filters, while xrandr picks with nearest neighbor). However, I know, that using xrandr scales is usual way when using multiple monitors with different resolutions, combined with properly configured Xft.dpi, to make visually same text size across all monitors in setups.

There are results.
- Xrandr always reports physical size, somehow extracted from monitor itself, ignoring even own modification like `xrandr --fbmm 360x200`. Thus I have no idea, if xrandr really limited to 10mm precision from older EDID, or this is just wrong EDID (probably EDID, following older standard with that precision limit).  
However, pixel size seems to be from monitor itself as well, completely unaffected by own --scale option.
- Xinerama reports size with 1mm precision, honoring dpi modifications from xrandr. This size is affected by `X -dpi ...` option, as well as by drivers, which seem to ignore DisplaySize line from its `Section "Monitor"`. But at least it's configurable, unlike what xrandr returns.  
Pixel size from xinerama is also affected by xrandr scale, thus it reports size, into which applications render, rather than physical monitor size.

Perhaps, xrandr scale has to be fetched and applied manually when xrandr method is used. If I just type `xrandr` or `xrandr --listmonitors`, printed pixel size is scaled.

But still, error from incorrect EDID (if it's really reason for poor 10mm precision) makes notable difference - with 1mm size exact DPI is ~100.8 (xdpyinfo prints as 101), while with 10mm precision it's 102.04).
So I think, there have to be switch for screen DPI detection method, since both have drawbacks. Could be global FLTK option, configurable via fluid or just editing respective config file, or just evironment variable.

There's output with debug lines, size and dpy. I used monica for test.

With originally configured DPI (aas shown by xinerama);
```
xrandr-w: 340
xrandr-h: 190
dpi: 102.048233x102.669472
```
Same, but disabled one flat to unconditionally resort to xinerama.
```
xrandr-w: 340
xrandr-h: 190
xinerama-w: 344
xinerama-h: 193
dpi: 302.584869x303.220703
```
Intentionally misconfigured DPI with 10mm precision:
```
xrandr-w: 340
xrandr-h: 190
xinerama-w: 360
xinerama-h: 200
dpi: 289.136658x292.608002
```

Physical size is printed from `::init()` driver method, while dpi - from `screen_dpi()`.

**Comment by ManoloFLTK** [comment]
OK. My suggestion is that you use these FLTK APIs to scale each screen according to your needs

1) Get the number of screens with `Fl::screen_count()`. Each screen is numbered from 0 to this count -1. Screen 0 is the master screen.
2) Get the horizontal and vertical dpi of screen n with
`Fl::screen_dpi(float &h_dpi, float &v_dpi, int n)`
3) From this information, compute the scaling factor you want for each screen. That is typically `dpi/96`
4) Apply this factor to each screen before mapping the first window with
`Fl::screen_scale(int n, float scale)`

Consider also application test/fullscreen which shows in its bottom panel the pixel size, coordinates and dpi's of each screen.

I'm not in a position to test configurations with multiple displays with distinct dpi. If the dpi's returned by FLTK are not correct, announce that here, and I'll try to fix it.
