### ISSUE TITLE
Focus is lost leaving full screen on macOS 13

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#608]
**Describe the bug**
Upgrading macOS from 12 to 13 introduces a regression in FLTK where focus is lost whenever you leave full-screen mode.

**To Reproduce**
1. Start the `fullscreen` test application
2. Enable full screen
3. Disable full screen

**Expected behavior**
Focus should be retained on the window when toggling full screen.

**FLTK Version**
 - Downloaded and self-built from: GitHub
 - If from Git, branch: `master`
 - If from Git, commit: 004ea67203f6de695c3e1e246da28bf73d74ee83 (but also seen on 1.3 branch)

**FLTK Configure / Build Options**
 - `./configure --host x86_64-apple-darwin10`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: 13.1
 - Processor: Both x86_64 and M1

**Additional context**
This is caused by the call `orderOut:`, which from macOS 13 seems to drop focus. A backtrace for FLTK 1.3 can be found here:

https://bugzilla.cendio.com/show_bug.cgi?id=8049

Note that this was discussed for the 1.3 branch in #287. An alternative solution was proposed there that could be reconsidered. The sledgehammer approach is probably to switch `orderFront:` to `makeKeyAndOrderFront:`.

**Comment by ManoloFLTK** [comment]
Focus is also lost after turning fullscreen ON.
And it's also lost with fullscreen app under Linux+X11 when turning fullscreen ON or OFF.
I would believe it's best to have apps behave equally under macOS and X11.

**Comment by CendioOssman** [comment]
Hmm... I'm not seeing any focus loss in any of those three cases. Tested with macOS 13.1 and GNOME 42 on Fedora 36. Did you use a different commit?

I agree that it should behave the same everywhere, which is that focus is always retained. I hope you aren't suggesting that loss of focus is desirable?

**Comment by ManoloFLTK** [comment]
> Focus is also lost after turning fullscreen ON.
> And it's also lost with fullscreen app under Linux+X11 when turning fullscreen ON or OFF.

I confirm this in these setups:
FLTK head commit
macOS 13.1
Debian sid

I add that it's the same with Wayland as with X11.

I put the focus in the "Input" field of the fullscreen app to follow whether it stays or gets lost.

**Comment by CendioOssman** [comment]
I'm confused. How are you toggling full screen in that case? If you click the "FullScreen" button, then focus will be moved there (away from the input field).

The issue is that the window itself loses focus.

On every platform, except macOS 13, I can keep pressing space to toggle back and forth between full-screen and windowed mode.

More importantly, though, do you think you have time to find a fix for this?

**Comment by ManoloFLTK** [comment]
@CendioOssman Thanks for your clarification. That  issue should be fixed now. Please, close issue if you confirm.

**Comment by CendioOssman** [comment]
Seems to work well, thanks. Tested on both macOS 12 and 13.

Could this be applied to the 1.3 branch as well?

**Comment by ManoloFLTK** [comment]
> Could this be applied to the 1.3 branch as well?

Done.
