### ISSUE TITLE
[BUG] Fatal error while communicating with the Wayland server: Protocol error

### ISSUE THREAD

**Issue by ngortheone** [fltk/fltk#610]
OS: FreeBSD 14
Wayland: sway

while running examples I occasionally and randomly get this error and the app crashes

```
Fatal error while communicating with the Wayland server: Protocol error
``` 

I will try to observe more and figure out what exactly triggers the error.

**Comment by ngortheone** [comment]
while running `chart-simple` dropdown menu behaves strangely:
- when I move the mouse down the expanded list the list moves up as I move the mouse down
- once the mouse leaves the app window area and returns back to (app loses focus and gets it again) it the crash happens

**Comment by ManoloFLTK** [comment]
The commit mentionned above should fix "once the mouse leaves the app window area and returns back to (app loses focus and gets it again) it the crash happens".
It may also hopefully fix the rest of the errors "while running examples I occasionally and randomly get this error and the app crashes".

@ngortheone:  Please, pull from the git repo and report what you see.

**Comment by ngortheone** [comment]
The crash no longer happens. :tada: 

The drop down menu still moves as I navigate it with the mouse. But now this can be moved into a separate issue.

**Comment by ngortheone** [comment]
I moved the dropdown menu bug here https://github.com/fltk/fltk/issues/613

**Comment by ngortheone** [comment]
also `Platform:wayland` label is missing on this issue
