### ISSUE TITLE
Build failure case of FLTK with MSYS2+MinGW-W64

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#612]
I am not sure is it a bug, maybe failure by environment, but anyway it happended, so I report to here.
In case of auto configured with ./autogen.sh, fltk/fltk fails to bilbuild libfltk_png.a by libz reference of MinGW64.
```
Configuration Summary
-------------------------------------------------------------------------
    Directories: prefix=/mingw64
                 bindir=${exec_prefix}/bin
                 datadir=${datarootdir}
                 datarootdir=${prefix}/share
                 exec_prefix=${prefix}
                 includedir=${prefix}/include
                 libdir=${exec_prefix}/lib
                 mandir=${datarootdir}/man
                 MSys docpath=/local/share/doc/fltk
Cross-compiling: no
       Graphics: GDI+
Image Libraries: JPEG=System
                 PNG=Builtin
                 ZLIB=System
    Large Files: YES
         OpenGL: YES
        Threads: YES
configure: creating ./config.status
config.status: creating makeinclude
config.status: creating fltk.list
config.status: creating fltk-config
config.status: creating fltk.spec
config.status: creating FL/Makefile
config.status: creating config.h
config.status: creating FL/fl_config.h
```
And build stops as ...
```
=== making png ===
make[1]: Entering directory '/d/Projects/fltk-origin/png'
make[1]: warning: -j4 forced in submake: resetting jobserver mode.
Compiling png.c...
Compiling pngset.c...
Compiling pngget.c...
Compiling pngrutil.c...
In file included from pngrutil.c:17:
pngpriv.h:920:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the note
s in pngpriv.h"
  920 | #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
      |    ^~~~~
In file included from pngget.c:15:
pngpriv.h:920:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the note
s in pngpriv.h"
  920 | #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
      |    ^~~~~
In file included from png.c:14:
pngpriv.h:920:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the note
s in pngpriv.h"
  920 | #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
      |    ^~~~~
In file included from pngset.c:19:
pngpriv.h:920:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the note
s in pngpriv.h"
  920 | #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
      |    ^~~~~
make[1]: *** [../makeinclude:168: pngget.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [../makeinclude:168: pngset.o] Error 1
make[1]: *** [../makeinclude:168: png.o] Error 1
make[1]: *** [../makeinclude:168: pngrutil.o] Error 1
make[1]: Leaving directory '/d/Projects/fltk-origin/png'
make: *** [Makefile:22: all] Error 1
```
It is OK when configuration set to built local image libraries - `--enable-localjpeg --enable-localzlib --enable-localpng`.
I think it would be checked while configure to libz dependency with ZLIB_VERNUM and PNG_ZLIB_VERNUM exists.

**Comment by MatthiasWM** [comment]
Lib PNG must use the headers of zlib that match the binary of zlib. Maybe it is enough to make sure that png and zlib are both set to System or BuiltIn, and never to different options. So if zlib is found on the system, but png isn't, we still must use the builtin zlib.

**Comment by Albrecht-S** [comment]
@MatthiasWM wrote:
> ... if zlib is found on the system, but png isn't, we still must use the builtin zlib.

Yes, I believe that's something we have to do, both in `configure/make` and `CMake`. I always suspected that this could be an issue, and now we're seeing it in "real life".

Side note (related): on macOS the current default is to use the bundled libjpeg and libpng but the system zlib (if found).

We should probably set the **default** to use **_all three bundled libs_** on `Windows` and `macOS` and set the default to **_system libs_** on all other platforms. In a second stage we should decide to use the bundled `zlib` if we use the bundled `png` lib because they must be compatible (as @MatthiasWM wrote correctly).

This would need changes in both `configure` and `CMake`. I can take the `CMake` part but I'd like to leave the configure part to someone else, if possible.

**Comment by MatthiasWM** [comment]
Trying to fix that in #621 .

**Comment by MatthiasWM** [comment]
@rageworx Could you please test this with the newest master branch and let me know if this error is still happening? Thanks.

**Comment by rageworx** [comment]
Dear @MatthiasWM , @Albrecht-S 

Tested with `./configure --enable-localpng`.
It automatically enables local ZLIB as like this :
```
Configuration Summary
-------------------------------------------------------------------------
    Directories: prefix=/mingw64
                 bindir=${exec_prefix}/bin
                 datadir=${datarootdir}
                 datarootdir=${prefix}/share
                 exec_prefix=${prefix}
                 includedir=${prefix}/include
                 libdir=${exec_prefix}/lib
                 mandir=${datarootdir}/man
                 MSys docpath=/local/share/doc/fltk
Cross-compiling: no
       Graphics: GDI+
Image Libraries: JPEG=System
                 PNG=Builtin
                 ZLIB=Builtin
    Large Files: YES
         OpenGL: YES
        Threads: YES
```
So local PNG option successfully configures local ZLIB as well and build successfully completed as well.
Thanks !
