### ISSUE TITLE
Two compiler warnings on Windows with mingw-w64 (MSYS2), CMAKE_CXX_STANDARD=20

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#615]
**Describe the bug**
See compiler warnings below:
```
(1) Building CXX object src/CMakeFiles/fltk.dir/drivers/PostScript/Fl_PostScript.cxx.obj

[...]/src/drivers/PostScript/Fl_PostScript.cxx: In member function
'int Fl_PostScript_Graphics_Driver::start_postscript(int, Fl_Paged_Device::Page_Format, Fl_Paged_Device::Page_Layout)':
[...]/src/drivers/PostScript/Fl_PostScript.cxx:676:61: warning: bitwise operation between different enumeration types
'Fl_Paged_Device::Page_Format' and 'Fl_Paged_Device::Page_Layout' is deprecated [-Wdeprecated-enum-enum-conversion]
  676 |   page_format_ = (enum Fl_Paged_Device::Page_Format)(format | layout);
      |                                                      ~~~~~~~^~~~~~~~

(2) Building CXX object test/CMakeFiles/animated.dir/animated.cxx.obj

[...]/test/animated.cxx: In function 'void make_images()':
[...]/test/animated.cxx:90:33: warning: arithmetic between floating-point type 'const float' and
  enumeration type '<unnamed enum>' is deprecated [-Wdeprecated-enum-float-conversion]
   90 |     const int xoffset = int(pos * DIM);
      |                             ~~~~^~~~~
```

**To Reproduce**
This is a build issue with a recent `g++` compiler under Windows with mingw-w64 (MSYS2) and C++ standard "20".

1. Configure with CMake (see below), run build

**Expected behavior**
No warning.

**FLTK Version**
 - Version: 1.4.0 / git current, commit b26db74dd0be8e4f4728e976144cb15e64b677a5

**FLTK Configure / Build Options**
 - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20 ../..

**Operating System / Platform:**
 - OS: Windows 10
 - Build environment: MSYS2 (mingw-w64)

**Additional context**
The warnings are unrelated and don't appear w/o `CMAKE_CXX_STANDARD=20` but both warnings seem to be reasonable.

**Comment by Albrecht-S** [comment]
I consider these statements bugs but set priority "Low". I don't think that this is platform specific, it just happened to appear in my MSYS2 build on Windows when trying to use C++ standard '20' (2020) and g++ 12.2.

**Comment by ManoloFLTK** [comment]
I see these warnings present before and absent after commit 72b8054. So we should be good.
@Albrecht-S please close issue if you confirm.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Basically I see no problem with the fix in `test/animated.cxx` although the use of an `enum` for `DIM` and `FRAMES` is questionable in the first place. However, it's been this way since it was contributed.

I worked on a better fix that replaces the inappropriate enum with `const` values and I'm going to commit this later. Sorry for the duplicated work.

**Comment by Albrecht-S** [comment]
@ManoloFLTK The other part in the PostScript driver is trickier and the main reason why I didn't (try to) investigate this myself. Your fix does technically suppress the warning, but is it "correct"? Bitwise OR of enums is always an issue. Are these enums "compatible"?

Well, I looked at the code and I noticed that these enums have distinct values. So far, so good.

But the assignment in question still assigns an "undefined" value to an enum, i.e. a value that is not a member of the enum if `layout != 0`. This is questionable. At least the enums should be documented (for the reader) such that it is clear that they can be combined or whatever is intended. I can imagine to define a range of bits that's reserved for the `layout` part in the `format` enum. This would make the intention clear.

However, wouldn't it be better to define two distinct members in `Fl_PostScript_Graphics_Driver` for layout and format?
```
  enum Fl_Paged_Device::Page_Format page_format_;
  enum Fl_Paged_Device::Page_Format page_layout_; // add this and use it appropriately
```

I noticed also that a similar (but unchanged) assignment is done later in the same file. You fixed [the warning in line 676](https://github.com/fltk/fltk/blob/72b8054ecc4c53cb9a138266fd267f2334f32a37/src/drivers/PostScript/Fl_PostScript.cxx#L676) but [the unchanged line 1494](https://github.com/fltk/fltk/blob/72b8054ecc4c53cb9a138266fd267f2334f32a37/src/drivers/PostScript/Fl_PostScript.cxx#L1494) obviously has the same issue.

Finally, in [line 1653](https://github.com/fltk/fltk/blob/72b8054ecc4c53cb9a138266fd267f2334f32a37/src/drivers/PostScript/Fl_PostScript.cxx#L1653)
```
  ps->page(ps->page_format_);
```
is called. Looking further into [this function](https://github.com/fltk/fltk/blob/72b8054ecc4c53cb9a138266fd267f2334f32a37/src/drivers/PostScript/Fl_PostScript.cxx#L847), the `format` part is stripped off and the comment says "orientation only" (which is technically correct, but ...).

This looks (to me) like a minor redesign would be appropriate, maybe using two distinct members as I suggested above?

@ManoloFLTK Playing the ball back to you: can you please check the "other" assignment and (maybe) remove the "mixing" of two enums? I'd feel better if this could be cleared and this could be better for future maintenance but I'm leaving the final decision to you. Maybe I'm missing something...

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks for the new commit 31327cd649b8ad5a6271057d823abe59a5362c60.

Closing this issue now.
