### ISSUE TITLE
Commit 12da87b makes test/pixmap_browser crash with .svgz files

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#616]
**Describe the bug**
Commit 12da87b makes test/pixmap_browser crash with .svgz files

**To Reproduce**
1) get a .svgz file or construct one by applying gzip to a .svg (text) file. One such file is attached (strip the .ZIP suffix)
2) run test/pixmap_browser
3) open the .svgz file
---> program crashes
No crash with immediately preceding commit: 08f6741

**FLTK Version**

 - Version: 1.4.0
 - If from Git, branch:  master
 - If from Git, commit: 12da87b (17 december '22) and later

**Operating System / Platform:**

 - OS: Linux, macOS
 
**Additional context**
Under macOS, the crash needs
configure --enable-localzlib
which produces PNG: builtin and zlib: builtin

Unexpectedly, there's no crash under macOS with PNG: builtin and zlib: system

[bt-am-blue.svgz.ZIP](https://github.com/fltk/fltk/files/10315225/bt-am-blue.svgz.ZIP)

**Comment by MatthiasWM** [comment]
Thanks. There are issues with different versions of zlib. I will try to fix that asap.

**Comment by MatthiasWM** [comment]
Hmm, I can not duplicate that, neither on macOS nor Ubuntu 22.04 (ARM64). I tried Valgrind and it does not trigger. I assume you use an Intel machine? Or a different system version of zlib?

Here is my order of shell commands. 

```
git pull
git checkout master
autoconf
./configure --enable-localzlib
make
cp ~/Downloads/bt-am-blue.svgz.ZIP bt-am-blue.svgz.gz
gunzip bt-am-blue.svgz.gz 
test/pixmap_browser 
```

**Comment by ManoloFLTK** [comment]
@MatthiasWM  Don't gunzip! This decompresses the image into a text file which works OK.
The attached file is called .ZIP just because with extension .svgz it's not accepted as an attachment here. Just remove the .ZIP extension by a rename command. You get then a .svgz file and try and open it with pixmap_browser.

**Comment by ManoloFLTK** [comment]
To produce a .svgz file, you can also do, starting from the top of an fltk source tree:
```
cd test/pixmaps
gzip -c checker.svg > checker.svgz
../pixmap_browser &
```
and open the brand new file test/pixmaps/checker.svgz

**Comment by MatthiasWM** [comment]
Ah, got it. The svgz.ZIP was the compressed file. I fixed that in the master. I forgot to initialise a struct. Could you please verify? Thanks.

**Comment by ManoloFLTK** [comment]
@MatthiasWM It's all good now. Many thanks. I close the issue.
