### ISSUE TITLE
[BUG] test/mandelbrot crashes on rightclick [wayland]

### ISSUE THREAD

**Issue by ngortheone** [fltk/fltk#618]
OS: FreeBSD 14
wayland: sway 1.7

Very easy to reproduce:
1. Run `test/mandelbrot`
2. Right-click anywhere in the area with mandelbrot fractal image
3. Observe crash with error `Fatal error while communicating with the Wayland server: Protocol error`

**Comment by ManoloFLTK** [comment]
@ngortheone That should be fixed with commit mentionned above. Please, close issue if you confirm.

**Comment by ngortheone** [comment]
Looks fixed now!

Now right-click spawns a second windows with another image in it!
