### ISSUE TITLE
Fl_Native_File_Chooser_MAC.mm compilation warning

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#627]
Fl_Native_File_Chooser_MAC.mm occurs warning like this on macOS 12,
```
  if (filter) {
      ^~~~~~
Fl_Native_File_Chooser_MAC.mm:627:10: note: uninitialized use occurs here
  return popup;
         ^~~~~
Fl_Native_File_Chooser_MAC.mm:596:3: note: remove the 'if' if its condition is always true
  if (filter) {
  ^~~~~~~~~~~~
Fl_Native_File_Chooser_MAC.mm:572:23: note: initialize the variable 'popup' to silence this warning
  NSPopUpButton *popup;
                      ^
                       = nil
```
There's Apple llvm-gcc shows hint to solve this warning by ` NSPopUpButton *popup = nil;`.

So I did solve this warning as this commit on my fltk-clone repository (fltk-custom, 1.4.0-dev)
https://github.com/rageworx/fltk-custom/commit/efed680f570b4d841faf4305bba676d99c307eef

Hope this is little help to solve warning message on macOS 12 ( Apple clang version 14.0.0 (clang-1400.0.29.202) )

**Comment by ManoloFLTK** [comment]
@rageworx Thanks for this issue report. It's fixed in the commit mentionned above.
