### ISSUE TITLE
fluid: Input widget C++ properties missing FL_WHEN_ENTER_KEY_ALWAYS option

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#629]
**I am using FLTK**
 - Version 1.4.0

For New -> Text -> Input,  under Properties -> C++ -> When, the "When" chooser is missing FL_WHEN_ENTER_KEY_ALWAYS.

Example: if the input field contains a command, if the user goes into the input field and hits ENTER without typing anything else, the callback won't be invoked because nothing changed. With the 'when enter key always' flag is set, this works as expected.

**Comment by MatthiasWM** [comment]
Yeah, I changed the menu Ito a pulldown with check boxes because when() is actually a bitfield and `FL_WHEN_ENTER_KEY_ALWAYS` is simply `FL_WHEN_ENTER_KEY|FL_WHEN_NOT_CHANGED`. But I can see how this is not obvious, and I will add the missing menu items.

**Comment by MatthiasWM** [comment]
Ok, I added the missing menu items as part of PR #628 because that PR deals with when() handling.

**Comment by erco77** [comment]
Cool, Thanks!
I didn't check but I'm sure you did it so I'll close.
