### ISSUE TITLE
Make some private Fl_Tabs methods protected (STR 3314)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#630]
Moving [STR 3314](https://www.fltk.org/str.php?L3314) to GitHub Issues, closing STR 3314 now.

STR text from user `FlyingJester`, edited by me, and split in three points:

1. I would like if some of the `Fl_Tabs` methods were made protected in 1.4 (notably `draw_tab`, and `tab_height`). This would make it much easier to write derived versions of `Fl_Tabs`, which right now requires either editing the `Fl_Tabs` source to make these methods protected, or  reimplementing much of the tab positioning logic.
2. Ideally I would also like the tab positioning methods to be more extensible, but I know that would be more work.
3. I should add that I would also like those functions to be made virtual for this case, too.

I believe that points 1 and 3 above should be included in 1.4.0.

I'm not sure what would need to be done for point 2. This might require a separate issue.

**Comment by Albrecht-S** [comment]
I added labels "enhancement" and "Prio 3" because this would change the API and it should therefore be done in 1.4.0.

**Comment by MatthiasWM** [comment]
> 1. I would like if some of the `Fl_Tabs` methods were made protected in 1.4 

Done.

> 2. Ideally I would also like the tab positioning methods to be more extensible, but I know that would be more work.

Added three more methods to handle overflow. More can be added as everything is extensible and methods are virtual.

> 3. I should add that I would also like those functions to be made virtual for this case, too.

They are.
