### ISSUE TITLE
Fl_Native_File_Chooser_GTK not using dlclose() (STR 3510)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#632]
Moving [STR 3510](https://www.fltk.org/str.php?L3510) (see title) to GitHub issues and closing STR 3510.

STR text from user `dcjc` (I believe: GitHub user @darealshinji, please correct me if I'm wrong):
> Fl_Native_File_Chooser_GTK doesn't use dlclose() on the open library handlers. I don't know if it's really a problem when dlclose() isn't called. I've attached a patch that counts instances of Fl_Native_File_Chooser_GTK and dlclose()s the library handlers when the last instance was deleted.

FWIW: the patch (probably outdated) is [available here](https://www.fltk.org/strfiles/3510/free_gtk_libs.patch).

I'm not sure if we really need to do this because the file chooser might be called multiple times and the gtk libs wouldn't have to be reopened each time.

@ManoloFLTK Can you please check this and close this issue and [STR 3510](https://www.fltk.org/str.php?L3510) accordingly? Thanks.

**Comment by darealshinji** [comment]
Yes, that's me. I don't know how important it really is to call dlclose() or (FreeLibrary() on Windows), but that's what you normally do before closing the program. In this patch dlclose() is called in the class destructor, so if a compiled program doesn't call the d'tor each time the file chooser window is closed it shouldn't be an issue I guess? Maybe FLTK can check for the library handle somewhere else, at some code that is called when everything is about to close?

By the way now that I think about it I don't know how thread-safe the instance counting is.

**Comment by ManoloFLTK** [comment]
@darealshinji The FLTK code caches the result of the search for the gtk libs which is done only once. Furthermore, when a process completes, all its open file descriptors close and similarly for open shared libraries. So, there's no benefit in calling dlclose() just before the end of an FLTK program.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thank you for taking and closing this issue.

FTR: I closed [STR 3510](https://www.fltk.org/str.php?L3510) referring to this issue.
