### ISSUE TITLE
X11: Xrender blurs adjacent images with bilinear scaling + Fix

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#633]
**Describe the bug**
Currently adjacent images are "blurred" by Xrender's bilinear scaling filter. FLTK currently contains a "kludge" to prevent this for tiled images, but cannot fix other scenarios.

**To Reproduce**
Use the test program from #537.

Run the test program and notice the dark stripes between the "tiles"

**Expected behavior**
No blurring between the "tiles" even when scaled with Xrender's bilinear filter.

**Screenshots**
![xrender_bilinear_blur](https://user-images.githubusercontent.com/9895976/210762327-110a1935-1142-4e99-9e77-1413ead41c8d.png)

**FLTK Version**
Current Xft version with XRender support

**FLTK Configure / Build Options**
`--disable-wayland`

**Operating System / Platform:**
Linux: Ubuntu 20.04

**Linux/Unix Runtime, if applicable:**
 X11

**Proposed Fix:**
 ````diff
diff --git a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
index ba098c309..8b6074f60 100644
--- a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
+++ b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
@@ -51,7 +51,6 @@
 #  include <FL/fl_draw.H>
 #  include <FL/platform.H>
 #  include <FL/Fl_Image_Surface.H>
-#  include <FL/Fl_Tiled_Image.H>
 #  include "../../Fl_Screen_Driver.H"
 #  include "../../Fl_XColor.H"
 #  include "../../flstring.h"
@@ -806,8 +805,9 @@ int Fl_Xlib_Graphics_Driver::scale_and_render_pixmap(Fl_Offscreen pixmap, int de
   static XRenderPictFormat *fmt24 = XRenderFindStandardFormat(fl_display, PictStandardRGB24);
   static XRenderPictFormat *fmt32 = XRenderFindStandardFormat(fl_display, PictStandardARGB32);
   static XRenderPictFormat *dstfmt = XRenderFindVisualFormat(fl_display, fl_visual->visual);
-  Picture src = XRenderCreatePicture(fl_display, (Pixmap)pixmap, has_alpha ?fmt32:fmt24, 0, &srcattr);
-  Picture dst = XRenderCreatePicture(fl_display, fl_window, dstfmt, 0, &srcattr);
+  srcattr.repeat = 2; // RepeatPad
+  Picture src = XRenderCreatePicture(fl_display, (Pixmap)pixmap, has_alpha ?fmt32:fmt24, CPRepeat, &srcattr);
+  Picture dst = XRenderCreatePicture(fl_display, fl_window, dstfmt, 0, 0);
   if (!src || !dst) {
     fprintf(stderr, "Failed to create Render pictures (%lu %lu)\n", src, dst);
     return 0;
@@ -824,10 +824,7 @@ int Fl_Xlib_Graphics_Driver::scale_and_render_pixmap(Fl_Offscreen pixmap, int de
       { XDoubleToFixed( 0 ),       XDoubleToFixed( 0 ),       XDoubleToFixed( 1 ) }
     }};
     XRenderSetPictureTransform(fl_display, src, &mat);
-    if (Fl_Image::scaling_algorithm() == FL_RGB_SCALING_BILINEAR &&
-          !Fl_Tiled_Image::drawing_tiled_image()) {
-      // The filter is not used when drawing tiled images because drawn image edges
-      // become somewhat blurry.
+    if (Fl_Image::scaling_algorithm() == FL_RGB_SCALING_BILINEAR) {
       XRenderSetPictureFilter(fl_display, src, FilterBilinear, 0, 0);
       // A note at  https://www.talisman.org/~erlkonig/misc/x11-composite-tutorial/ :
       // "When you use a filter you'll probably want to use PictOpOver as the render op,
````

Edit: I had to update my change. Actually with `scrattr.repeat = 1 // RepeatNormal` I experienced an artefact on one of my images when scaled). Changed to `srcattr.repeat = 2 // RepeatPad`.

**Comment by ManoloFLTK** [comment]
Here is what I get here with the X11+Xrender FLTK platform under Debian sid :

<img width="215" alt="image" src="https://user-images.githubusercontent.com/41016272/210848369-cb1cd29a-aa9a-4d6d-8178-d88974f07f68.png">

That is with 170% scaling up. I see no dark strip at all scale values.

Did I miss something ?

**Comment by wcout** [comment]
Forgot to look how the scaling algorithm is set in that test program. You have to change it to bilinear.

**Comment by ManoloFLTK** [comment]
@wcout The commit mentionned above includes your proposed fix. Many thanks for it. Please, close issue if you agree.

**Comment by erco77** [comment]
@wcout I gotta ask, lol, how /did/ you track down the location of the code to make your patch? Did you just RTSL, or use a debugger to step your way down into the internals?

PS. I have no idea why a push on my fork created a reference to this issue.. yikes. I recently resynced my fork. Scares me to think that all issues from my sync did this to all issues related to the sync.

**Comment by Albrecht-S** [comment]
> I have no idea why a push on my fork (re)created a reference to this issue.. yikes. I recently resynced my fork. Scares me to think that all issues from my sync did this to all issues related to the sync. Is this visible to 'everyone', or just me because I own the fork?

What you see here is the reference in the main fltk/fltk repository, and yes, I see this as well.

From what I remember you **merged** the FLTK master into your fork which duplicated all commits of the master branch in your fork. This seems to be what causes the references from the commit messages to appear here. I'm not sure if this is intended by GitHub, but it seems to be another reason to avoid such "downstream merges" as you did. Not sure what exactly happened though.

Theory: syncing the fork alone (IIRC you did it via the GitHub `sync` button) shouldn't have this effect. But when (**if**) you then `git pull`ed or `git merge`d the upstream master branch into your own feature branch you created entirely new commits (new hashes etc.) with the same commit messages. And since the commit messages contained these references ('#'nnn) this might have caused these references here. Not sure, I may be wrong though.

**Comment by erco77** [comment]
This was a more recent sync where I wanted to bring in the recent mods to Fl_Rect.
IIRC: 1) On github synced my fork's master branch. 2) local repo, checked out master, git pull, checked out my branch and used 'git rebase master' locally. 3) Made some mods, 4) did a push, but it complained about my local branch being out of sync, so 5) did a 'git pull --rebase' followed by a 'git push'. Maybe it was the --rebase? Meh, so dang complicated. I need a script or something to do this right.

**Comment by ManoloFLTK** [comment]
@erco77: This is what I do, thanks to Albrecht, to synchronize my fork (myfork) and its own branch (mybranch) with progress in the main fltk repo:
```
git remote -v
    myfork   https://github.com/XXX/fltk.git (fetch)
    myfork    https://github.com/XXX/fltk.git (push)
    origin    https://github.com/fltk/fltk.git (fetch)
    origin    https://github.com/fltk/fltk.git (push)
git checkout master
git status
git fetch
git pull https://github.com/fltk/fltk.git
git push myfork master
git rebase master mybranch
as long as there are conflicts:
	edit conflict-containing files  
	git add <these files>
	git rebase --continue
git status
    On branch mybranch
git push -f myfork mybranch

```

**Comment by wcout** [comment]
> @wcout I gotta ask, lol, how /did/ you track down the location of the code to make your patch? Did you just RTSL, or use a debugger to step your way down into the internals?

I fear I cant' give you a spectacular answer to this:
That was mainly because I already had "contact" with this topic through https://github.com/fltk/fltk/issues/163.
The rest was research (just like finding out what RTSL stands for;), looking at the Xrender include file and educated guessing...

**Comment by wcout** [comment]
Works. Thank you.
