### ISSUE TITLE
Shift-Ctrl-C shortcut in fluid not working on newer linux OS's

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#637]
**Describe the bug**
I've been using fluid across different versions of linux, and have noticed the Ctrl-Shift-C shortcut (to 'Write code') is not working on some of the machines.

From what I can tell, it works fine on my Ubuntu 20.04,
but fails on Rocky9 or debian11.

This might be a wayland thing, and it might be specific to the Shift modifier.

**To Reproduce**
Go into fluid, create a simple project, then use Ctrl-Shift-C to try to trigger the "Write code".
On the affected systems, I have to use the menu to pick the option in order to get the confirmation dialog indicating the files have been written.

**FLTK Version**
This is 1.4.x current.

**FLTK Configure / Build Options**
Mmm, who knows, lol, different on each machine.
I'll see if I can build with different options (wayland vs X11 emulated wayland) to get some specifics.

**Comment by erco77** [comment]
Built on one of those machines with Wayland off, and now fluid's shortcut for Ctrl-Shift-C works.
The build that doesn't work was default, which is Wayland on.

So yeah, seems to be a wayland thing.

**Comment by erco77** [comment]
Another data point: running the test/keyboard program gives different results for chords like Ctrl-Shift-C.
- In the X11 version, doing Ctrl-Shift-C in that order, at the end shows all three keys down as it should
- In the wayland version, doing the same, hitting Ctrl shows that key down, hitting Shift causes Ctrl to show 'released' and Shift to be down, and similar for hitting 'C'.

So the Wayland version of the keyboard app seems to show only one key at a time as being down, even though it's a chord.

**Comment by ManoloFLTK** [comment]
> In the wayland version, doing the same, hitting Ctrl shows that key down, hitting Shift causes Ctrl to show as 'released' and Shift to be down, and similar for hitting 'C'.

That's not what I see with test/keyboard and Wayland : the "ctrl" Fl::event_state button remains yellow all along the key combination.

**Comment by ManoloFLTK** [comment]
OK.  Now I see the difference under test/keyboard: it's  not in Fl::event_state flags but in keyboard keys shown as pressed. Still, I would believe menu shortcuts is determined only by Fl::event_key() and Fl::event_state() which are both correct under Wayland.

**Comment by ManoloFLTK** [comment]
FYI: most of the times, it's not necessary to change OS nor to rebuild FLTK to determine whether a behaviour is Wayland-related or not: just running the same executable with `FLTK_BACKEND=x11` at the beginning of the command line will have it use X11. This way, all windowing and event-processing are exactly as what a non Wayland-enabled FLTK library does. This doesn't apply to behaviours determined by class Fl_Graphics_Driver because both legs of the hybrid Wayland+X11 platform use the same, Cairo-based graphics driver.

**Comment by erco77** [comment]
I'm still 1/2 asleep and goin back to bed, but doing a quick test, it seems the difference between the old and new machines is: when the Ctrl-Shift-C chord is hit, Fl::event_key() returns:

- 'c' on the old machines (lowercase 'c')
- 'C' on the new machines (uppercase 'C')

(I'm guessing uppercase is correct, since SHIFT is down during the chord)

Fluid defines the shortcut with a lowercase 'c', which is I assume why that's not working on the new machines:

```
 {"Write &Code...", FL_COMMAND+FL_SHIFT+'c', write_cb, 0},
```

With the attached program, [myshortcut.cxx.txt](https://github.com/fltk/fltk/files/10366147/myshortcut.cxx.txt), it defines a menubar and creates two items with shortcuts that trigger a callback:

- One with the ctrl|shift|c shortcut defined like fluid, with a lowercase 'c'
- One with the ctrl|shift|c shortcut defined with an UPPERcase 'C'

(It also defines a handle() method and tests in various ways and shows the value of Fl::event_key(), but I'd focus on the callback results)

What I see is:
- On old machines, only the LOWERcase 'c' shortcut is triggered
- On new machines, only the UPPERcase  'c' shortcut is triggered.

The Fl_Menu.cxx code seems to end up calling `Fl::test_shortcut()` to do the check, perhaps it needs a tolower() stuck in there somehow, so that both of these compositions work equally:

- (FL_COMMAND+FL_SHIFT+'c')
- (FL_COMMAND+FL_SHIFT+'C')

I've never been clear on this myself, and I think I saw mention of this in the last year or so as a conversation among devs to try to clear this up, but can't recall specifics.

I'm fading out, will check in later today..

**Comment by ManoloFLTK** [comment]
That should be fixed with the commit mentionned above. @erco77 Please close issue if you confirm.

**Comment by erco77** [comment]
Yep, that got it; closing.

That fixed fluid's Ctrl-Shift-C shortcut, and my test program now prints the same results on both old and new machines:

```
$ ./myshortcut 
APP: Fl::test_shortcut(cmd+shift+lowercase 'c')
APP: Fl::test_shortcut(cmd+shift+UPPERcase 'C')
APP: DETECT short cut: eventkey='c'   <-- lowecase now
MENU CALLBACK: Short cut [0x1]!       <-- lowercase shortcut (like fluid) is triggered
```
