### ISSUE TITLE
Fl_Spinner: look of widget has changed

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#638]
**Describe the bug**
The Fl_Spinner widget's input field has become a fixed height that is small, and thus doesn't change its size to match the size of the up/dn arrow buttons when resized.

**To Reproduce**
Go into fluid, create a window and a spinner, resize the spinner up, and it looks like this:
![image](https://user-images.githubusercontent.com/6484779/211126474-e826f81d-056f-443e-bbdb-ef52f7a3f832.png)

Should look like this instead:
![image](https://user-images.githubusercontent.com/6484779/211126396-087f6bb0-8cd0-4efc-9588-ad2f2d5516c3.png)

Note in the upper (wrong) screenshot, the height of the input field is small relative to the buttons, and the border box for the child Fl_Input isn't being drawn. Seems like the input field's "white area" isn't resizing vertically at all, staying locked at a fixed size.

I did a `git bisect` to figure this out, and found this commit to be the culprit:
```
$ ( cd .. ; git bisect good )
ecc47d0cc3e1784e17ac94829202f2bdbd38a682 is the first bad commit
commit ecc47d0cc3e1784e17ac94829202f2bdbd38a682
Author: Albrecht Schlosser <albrechts.fltk@online.de>
Date:   Sun Nov 22 19:19:19 2020 +0100

    Refactor and simplify "arrow drawing" in widgets
    
    "Arrows" in widgets are those GUI elements mostly represented by
    triangles pointing in a particular direction as in scrollbars,
    choice widgets, some menus, valuators and Fl_Counter widgets.
    
    The code has been simplified and standardized such that all these
    GUI elements are drawn identically per FLTK scheme.
    
    Widget authors no longer need to write code to calculate arrow sizes
    and draw polygons etc.
    
    Different schemes can and do implement different drawing functions.
    
    Todo: see comments "FIXME_ARROW" in src/Fl_Menu_Button.cxx and
          src/Fl_Menu.cxx
```

**Comment by erco77** [comment]
Looks like this one is you @Albrecht-S; I'm not clear on /why/ the input widget is drawing differently, but it seems to have something to do with the `((Fl_Widget&)input_).draw();` call that might be casting away some internal behavior. (shrug)

I also noticed in a working program with spinners, the cursor (vertical bar) would stay "stuck on" when you move focus to other widgets. So definitely the input widget was misbehaving somehow.

Albrecht, you might want to check for similar issues in the other widgets modified during this commit that use this same draw() technique.

Attaching a patch suggestion, [v1-patch.txt](https://github.com/fltk/fltk/files/10365344/v1-patch.txt), against 1.4.x master that appears to fix the issue. It simplifies the code a bit too, letting the whole group draw itself normally as it did before, and we just draw the arrows over the empty buttons. I didn't check the logic of the positioning, assuming it does what it did before.

**Comment by Albrecht-S** [comment]
Ok, thanks for debugging this. The only reason to add the draw() method was (IIRC) because I needed to draw the arrows explicitly rather than relying on the label drawing code with the `@ symbols`.

Your new code looks good and simplifies the draw() method. I didn't test it though, but it is closer to the original (before my commit) and still draws the arrows correctly. That's all I wanted, and if it also resolves another issue (cursor "stuck"), then it's even better.

Please go ahead and commit (and close this issue). TIA.

**Comment by erco77** [comment]
OK, will follow up and close.

Without the patch, you can see the "cursor stuck on" in the test/valuators app; click on the white input field in each of the two spinner widgets one at a time, and the "cursor bar" remains after focus moves away. Also the cursor can't be seen to move when the lt/rt arrow keys are used, but if you hold down SHIFT while using the arrows, you can see the cursor is indeed moving by the selection changing.
