### ISSUE TITLE
RFE: New Fl_Rect::inset(left,right,top,bot) method

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#640]
Would be good IMHO if `Fl_Rect` could be inset by left/right/top/bottom offsets, to allow for e.g. margins
that might be different than one standard offset. e.g.

```
void inset(int left, int right, int top, int bottom) {
  x_ += left;
  y_ += top;
  w_ -= right;
  h_ -= bottom;
}
```

**Comment by Albrecht-S** [comment]
FYI, we have already `void inset(Fl_Boxtype bt)` which insets according to a specific boxtype.

But if you really want asymmetric insetting, then I suggest the changed argument order similar to (x/left, y/top, w/right, h/bottom) as shown below and the modified (corrected) calculation:
```C
void inset(int left, int top, int right, int bottom) {
  x_ += left;
  y_ += top;
  w_ -= (left + right);
  h_ -= (top + bottom);
}
```

The calculation of `w_` and `h_` must adjust for both `left + right` and `top + bottom` resp..

**Comment by erco77** [comment]
Yep, right about the calculation.

For the word ordering, I take it you're recommending **left,top,right,bottom** perhaps for consistency with our `Fl_Printer::margins(int *left, int *top, int *right, int *bottom)` and new Fl_Flex, which is a good a reason for consistency.

FWIW, and the sake of lulz, and the utter confusion in the universe on this:
- **left,right,bottom,top** is opengl's [glOrtho()](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml), e.g. glOrtho( left, right, bottom, top, zNear, zFar )
- **left,top,right,bottom** is Qt's [QMargins](https://het.as.utexas.edu/HET/Software/html/qmargins.html#QMargins-2) class uses
- **left,right,top,bottom** is Qt's Rectangle and [anchor](https://doc.qt.io/qt-6/qtquick-positioning-anchors.html) classes use
- **top,right,bottom,left** is HTML/CSS's [margin](https://www.w3schools.com/css/css_margin.asp) command uses
- **left,right,top,bottom** is a common idiom, as that's the order one reads panels in a comic, or words on a page
- in FLTK and image libraries,  pixels are usually arranged primarily left-to-right, top-to-bottom

That all said, consistency is surely best, and if there's an existing precedent, we should follow it.

**Comment by erco77** [comment]
Suggested change; I can apply this and close:
```
  /** Move all edges in by \p left, \p top, \p right, \p bottom.

    Shrinks the rectangle on all sides keeping the center of the
    rectangle at the same spot.

    If any value is negative, the rectangle is enlarged.

    Values are not range checked; it is possible to create
    an invalid or empty rectangle.
  */
  void inset(int left, int top, int right, int bottom) {
    x_ += left;
    y_ += top;
    w_ -= (left + right);
    h_ -= (top + bottom);
  }
```
With those docs, the doxygen generated looks like this:
![image](https://user-images.githubusercontent.com/6484779/211175085-64bab27c-34ed-4b8d-baaf-78390d8c705c.png)

**Comment by Albrecht-S** [comment]
+1 :+1: Good to go from my side. Thanks.

Nice to see how different libs/tools use (order) the "same" arguments.

**Comment by MatthiasWM** [comment]
+1 from me.

**Comment by erco77** [comment]
Committed as 1324c623f, closing.
