### ISSUE TITLE
Fluid-generated code triggers compiler warning [-Wunused-variable]

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#643]
**Describe the bug**
The compiler warning is generated if
- an object is assigned a "Name" in the C++ tab and
- the variable name `o` is _"used"_ **inside a comment** in the "Extra Code" field

See screenshot of `test/tabs.fl` in `fluid` below.

**To Reproduce**
Compile current `master`with "-Wunused" and build target `tabs`.

Steps to reproduce the behavior with CMake:
1. `cd` to the build directory
2. build target `tabs` or the full library:
```
fltk/build/temp $ cmake -G Ninja -D CMAKE_CXX_FLAGS="-Wunused" ../..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
[...]
-- Generating done
-- Build files have been written to: /git/fltk/master/build/temp
fltk/build/temp $ ninja tabs
[240/241] Building CXX object test/CMakeFiles/tabs.dir/tabs.cxx.o
test/tabs.cxx: In function ‘int main(int, char**)’:
test/tabs.cxx:123:16: warning: unused variable ‘o’ [-Wunused-variable]
  123 |     { Fl_Tabs* o = tabs_group = new Fl_Tabs(10, 35, 315, 260);
      |                ^
[241/241] Linking CXX executable bin/test/tabs

```

**Expected behavior**
No compiler warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/26235500/211200352-e87fcdbb-5956-45ca-8bfc-7eb6e2140ad0.png)

**FLTK Version**
 - Version: 1.4.0
 - Git `master`, commit: 09db3a6dea4b6c6d23a81ba32c84e278c1964184

**FLTK Configure / Build Options**
See above.

**Operating System / Platform:**
 - OS: Linux Mint 20 (not relevant to the issue)

**Additional context**
ISTR that the `Extra Code` is scanned for the variable name `o` and if it is "found", fluid generates the variable `o` and assigns the value. The parser should test if the "variable name" is in a comment.

The assignment to `o` and thus the warning can be avoided by user code (in this case `tabs.fl`) if
- the string 'o' in the comment is changed to anything else, e.g. `x`
- the correct variable name (in this case `tabs_group`) is used, even in a comment

This is a minor issue and maybe we shouldn't care but I wanted to report it.

The code can be "fixed" on the user's side by not using `o` in the "Extra Code" field inside a comment.

**Comment by Albrecht-S** [comment]
@MatthiasWM If changing the parser of the "Extra Code" field would be too much work I wouldn't mind if this issue was closed and the "Extra Code" in `test/tabs.fl` was changed as suggested in the report. I could have done the latter myself but this would only hide the issue which can happen in other users' code.

**Comment by MatthiasWM** [comment]
All this minimal C++ "interpreter" does is check for the keyword 'o'. https://github.com/fltk/fltk/blob/9bdaf5a84d6243ab90584c2e0ee6125b0dc1f98c/fluid/Fl_Widget_Type.cxx#L2880

I could always add the line `(void)o;` right after its declaration to make the compiler shut up?! Writing a better interpreter is a bottomless pit inside Pandoras box.

**Comment by Albrecht-S** [comment]
@MatthiasWM OK, I'm fine with the statement above (Pandoras box).

Closing this issue.
