### ISSUE TITLE
undefined reference to png_init_filter_functions_vsx

### ISSUE THREAD

**Issue by cstkingkey** [fltk/fltk#652]
ppc64el target building fails with undefined reference to png_init_filter_functions_vsx

from https://github.com/godotengine/godot/issues/56448
need to set cfags with -DPNG_POWERPC_VSX_OPT=0 or use system png

**Comment by ManoloFLTK** [comment]
@cstkingkey Thanks for this report. I would hope the above-mentionned commit fixes the issue. Do you confirm that? If yes, please, close the issue.

**Comment by cstkingkey** [comment]
> @cstkingkey Thanks for this report. I would hope the above-mentionned commit fixes the issue. Do you confirm that? If yes, please, close the issue.

No. png/CMakeLists.txt is not updated.  so the new source fles are not built.

**Comment by ManoloFLTK** [comment]
@cstkingkey Sorry, I had forgotten about CMake-based building. That should be better with the commit mentionned above. Could you, please, explain a bit what are the connections between projects FLTK and Godot, if any ? TIA.

**Comment by cstkingkey** [comment]
> @cstkingkey Sorry, I had forgotten about CMake-based building. That should be better with the commit mentionned above. Could you, please, explain a bit what are the connections between projects FLTK and Godot, if any ? TIA.

just a search result of same issue. thanks for the quick fix.
