### ISSUE TITLE
[1.4.x] fluid file corruptions / odd behaviors

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#653]
**Describe the bug**
Platform is Linux, Ubuntu 20.x editing files on a local drive.

I've been working with fluid a bit lately, and noticing some odd behaviors I've not seen before:
- Sometimes hitting save (^S), the terminal I invoked fluid from spits out incomplete snippets of .fl file content.
- A few times the .fl file became corrupted in a way where extra lines were added to it. Had to xdiff to a previous and hand edit to restore.

There is no single reproduction I can think of; it comes after I edit functions it seems like.
FWIW, I use the 'external editor' feature, where it opens gvim to edit code.

When I've seen the behavior where the output goes to the screen, it seems to be the .fl output of the code block that was last selected in the fluid "tree", such as an existing "New -> Code -> Code.." block that had just been edited before doing the Save (^S).

I'm guessing that the code generator is somehow getting stdout as the output FILE* instead of the FILE* being saved.

**Comment by erco77** [comment]
This might be one for @MatthiasWM but since I worked on the external code editor stuff, might be my fault somehow too, lol, though I've not seen this before, and I think I've used fluid a lot since the external code editor stuff was added.

**Comment by erco77** [comment]
OK yeah, for sure when ^S saves out the .fl file and the code ends up on the terminal screen instead of in the file, the .fl file becomes corrupted.

Fortunately if I hit File -> Save as, and resave the file, that gets the file back to normal.

So yeah, somehow, perhaps after editing a code block, the output FILE* used during File -> Save becomes stdout somehow, perhaps redirecting what was meant for the .fl file to end up on the screen instead, causing a missing block from the .fl.

However I've also seen partial corruptions where an extra line or two ended up in the .fl file, i.e. a "repeated" few lines instead of a truncation as I just saw now. Very strange!

**Comment by erco77** [comment]
This is kinda hard to track down because there was a large commit in 2021 that moved stuff around.

I can only guess there might be a race happening with the external code editor, where a file is read into fluid before it's fully been written, even though all the editors are closed. It's possible after I save out of the editor, I'm too quick to hit ^S to save immediately after the editor closes its window, before fluid has time to fully catch the editor's modified content.

It doesn't explain the output to stdout, but it might explain a corruption. Trouble is the corruptions appear to be with the fluid syntax itself, not broken up code. For instance in the one case I saw a line of fluid's own bracketed code line (e.g. '} {}' with some "open" and "selected" commands mixed in) were duplicated in the .fl file, as if that one line was written twice. That was easily fixed by removing the extra line. But other corruptions were worse, with entire sections or an entire bottom half of the .fl file missing.

**Comment by MatthiasWM** [comment]
Thanks for looking at FLUID. This is really helpful for me. I am not too familiar with the external code editor, but I know that it uses a 2 second timer, so if your close/save combination happens to falls within those 2 seconds, you may very well have a disrupted file.

There is a second timer that updates the source code preview wind. Do you use that in auto-update mode?

Lastly, .fl file reading and writing uses variables local to the source file. It is absolutely possible that code may modify file pointers when reading or writing. Calling `open_write` with a NULL name opens a connection to stdout, for example. Closing the .fl file also reroutes following writes to stdout. The file descriptor for writing .fl files is `static FILE* fout` in `file.cxx`.

I will try to look at that in the next days.

**Comment by MatthiasWM** [comment]
Oh, there is one change that may contribute here. The source code preview window has a tab now to also preview the .fl file. Maybe the timer is triggering a preview whilw writing the actual file? That would require some obscure query to run system/timer event. Strange.

**Comment by erco77** [comment]
> ..if your close/save combination happens to falls within those 2 seconds,
> you may very well have a disrupted file.

But hmm, if anything would be corrupted there, it would just be the user's code block.

It's not uncommon for the user to have imperfect code inside the "code" block; I would still think whatever fluid loaded during those 2 sec updates would still end up saved into the .fl file enclosed in fluid braces correctly, no matter how mangled the user provided "code" block was.

Also, pretty sure the design of the external editor understands the asynchronous nature of the editor vs. fluid when it comes to editing code blocks. I believe the reason fluid has a timer that loads the user's editor every 2 secs is to allow multiple editors open on different parts of the fluid code (e.g. editing different function code blocks so one can paste between them, etc), and perhaps too so if one hits Save in the editor, fluid's modify flag updates quickly, so one can do a ^S or Alt-G while the editor is open to compile/run without having to close the editor, to see errors with what's been typed and be able to undo/redo in the editor.

Pretty sure no matter how mangled the external editor's code is, fluid wouldn't corrupt its own .fl syntax.

**Comment by erco77** [comment]
Pretty sure when fluid loads whatever editor files are open, it does so when it's not doing anything else. i.e. it shouldn't be servicing the timer (I hope) in the middle of a save operation. That is unless somehow during the save, an Fl::wait() is called, or some such, but I really can't imagine that, as saving also has to work headless.

Certainly is curious; I wish I could give you a precise trigger for this bad state; I've not been able to replicate it lately; been editing for many hours without seeing a repeat. But I may have tuned my editing habits to avoid e.g. doing a :wq in the editor followed by a quick ^S.

**Comment by MatthiasWM** [comment]
Investigating further, there are 9 locations that write .fl project files, including undo/redo, but generally, writing the file always happens in the main thread. The editors however run in their own thread, so they may in theory overwrite the code snippet while FLUID is reading it, but even if that were the case (I thought that the OS does not allow that), the resulting data block should simply be copied (possibly truncated at a `\0` character).

I will encapsulate project reading and writing into their own classes to minimise the chance of corrupted globals via double-use of the file writer.

**Comment by MatthiasWM** [comment]
Ok, I was able to duplicate the issue, and I found the bug, too. When an external editor saves a file, the change is discovered by FLUID within 2 seconds _or less_. If so, `Fl_Code_Type::name(...)` is called, which then calls `storestring()`, which calls `undo_checkpoint()`. A checkpoint is created by writing a .fl file into a temp directory.

Now if FLUID saves a file, it calls `write_file`, which calls `Fl_Code_Type::handle_editor_changes()` to capture external changes, just in case the 2 second timeout hasn't fired yet. And herein lies the problem: `handle_editor_changes` calls `name`, then `storestring`, then `undo_checkpoint`, which finally `write_file`. So the _undo_ file is written, and then the file descriptor is closed and reset to `stdout`. Now we continue to write our original file, also to `stdout`.

This bug is random, because we may be anywhere within the 2 second interval when saving our file. So any save-save sequence may or may not trigger the bug if it is shorter than two seconds.

The fix is very easy. When saving the .fl file, we must first suspend and the resume undo.

**Comment by MatthiasWM** [comment]
Fixed in 179771acd25ee5ff8e36a5fd192682d4d55c52af

**Comment by erco77** [comment]
That's great -- thanks for fixing that!
When writing large blocks of code in fluid, it really helps to use a familiar text editor for writing methods.

**Comment by MatthiasWM** [comment]
Yes, no doubt. I have a version where you can type the code right into the CodePreview window, and even though this is much better than the modal dialog, it's still far from using your own editor. Some kind of back-and-forth syncing between generated and edited code would be great, but I don't think that external apps allow that.

**Comment by Albrecht-S** [comment]
Note: I removed the label "Platform: X11" because the description of the solution sounds like this bug was not restricted to a platform. The "Platform: xxx" labels should only be set if the issue or bug is platform specific.

@MatthiasWM Thanks for fixing this, such random errors are hard to find. Great Job!
