### ISSUE TITLE
[1.4.x] fluid's New -> Code -> Comment needs syntax highlighting turned off

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#658]
**Describe the bug**
The New -> Code -> Comment text editor seems to treat the contents as code,
even though it's comment text, which makes for needlessly random colors
inside the code comment text.

**To Reproduce**
New->Code->Comment and start typing text. C++ keywords are highlighted,
and single quotes used for comment's punctuation makes the text change
colors needlessly.

**Expected behavior**
No syntax highlighting for comments.

**Screenshots**
![image](https://user-images.githubusercontent.com/6484779/213819887-8a3d7a3d-09ab-4b8c-9f2f-fb90bbe05bfe.png)

**Comment by MatthiasWM** [comment]
Fixed in master: 4c8927c08344f4275941c4367377f6ca60019648
