### ISSUE TITLE
Fl::get_font_name() regression or change?

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#66]
In older FLTK versions (1.3, 1.4 to some point) Fl::get_font_name() returns the name in eg. 'Arial bold', whereas the current version returns 'BArial' instead. This is on the same Linux machine (Ubuntu 16.04).

This can be seen with the 'fonts' program in the test folder.

Is this a regression or a deliberate change?

**Comment by ManoloFLTK** [comment]
That should now be fixed in the git repository.
The function was OK with Pango, but not without.

That said, I recommend using Pango which allows to draw any character
string with any font and any size. 
Just turn Pango option ON with configure or CMake.

**Comment by wcout** [comment]
I can confirm, that this it works now as expected.
Thank you very much for the quick fix.
