### ISSUE TITLE
New fltk-options app does not work

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#663]
**Describe the bug**
New  fltk-options app does not work

**To Reproduce**
Build and run fltk-options

1. Select 'Scaling factor options' and turn OPTION_SHOW_SCALING to OFF
2. Close fltk-options
3. Run fltk-options again, and select 'Scaling factor options': OPTION_SHOW_SCALING is OFF, that's good
4. Type ctrl+ : the transient, yellow 110% window appears

**Expected behavior**
No transient yellow window should appear, because that's what OPTION_SHOW_SCALING set to OFF means.

It's like that for all options: changes done in fltk-options are visible when fltk-options is re-run, but no option change has any effect on any FLTK app.
Option settings used to work before introduction of the fltk-options app.

**FLTK Version**

 - Version:  1.4.0
 - If from Git, branch:  master
 - If from Git, commit:  1fc269b and later

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS:  Linux
 - OS Version: Debian sid

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
@MatthiasWM : can you, please, look into this ?

**Comment by MatthiasWM** [comment]
Sigh. I tested the app in very respect, except to check if the options are indeed changed. Thanks for checking. This should be fixed now: e9e7be3ca10834d9e4566ea280bfae05668e5fcc
