### ISSUE TITLE
link failed

### ISSUE THREAD

**Issue by ys928** [fltk/fltk#667]
I have compiled the latest master branch's code, but it can't run.
the msvc report LNK2019 error
for example:
>error LNK2019  
>can't resolve the external symbol   __WSAFDIsSet,function "public: virtual double __cdecl >Fl_WinAPI_System_Driver::wait(double)" (?wait@Fl_WinAPI_System_Driver@@UEAANN@Z) referenced the symbol 
>Located in fltk.lib(Fl_win32.obj)

but I have linked all libs.

not only that,when i use the same code in fltk 1.3.8 ,It's normal.

**FLTK Version**
 - Version: 1.4.0
 - Installed as package from: github
 - Downloaded and self-built from: git
 - If from Git, branch:  master
 - If from Git, commit: 9bf2726bce637d

**FLTK Configure / Build Options**
 - cmake  -DCMAKE_INSTALL_PREFIX=\<projectPath\>  ../fltk
 - cmake --build . --config Release
 - cmake -P  cmake_install.cmake

The fltk folder and build folder  are at the same level

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Comment by Albrecht-S** [comment]
@ys928 Thanks for the report. I assume that this link failure happens after a successful build and installation of the FLTK library (i.e. the instructions you gave above are working well).

Is this true so far?

Further question: do you use any socket (winsock) functions in your own code?

One difference between FLTK 1.3.8 **may** be (I can't tell off the top of my head) that FLTK 1.4 requires you to link with the socket library explicitly while 1.3.8 did not.

Anyway, you need to link your application with ws2_32.lib explicitly, just add ws2_32.lib to your project.

If this fixes your problem, please close this issue. If not, please answer the questions above and provide more information.

That said, if my assumptions above are true and this does not fix your problem: this is not the right place to answer user ("build your own project") questions, please see below:

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by MatthiasWM** [comment]
FLTK depends on several libraries that come with msvc. FLTK comes with a litte tool named "fltk-config" that can be used from the command line and lists all the libraries and other resources that you need. 

For me on Windows11, fltk-config returns these flags for linking: `-L./lib -mwindows -lfltk -lgdiplus -lgdiplus -lole32 -luuid -lcomctl32 -lws2_32`

You must ink at least with gdiplus, ole32, uuid, comctl32, and ws2_32.

**Comment by Albrecht-S** [comment]
OK, this explains why 1.3.8 works and 1.4.0 not: using `gdiplus` was added as a new feature in 1.4.0 (it's optional, you can disable it).

**Comment by ys928** [comment]
Thank you for your answer!
