### ISSUE TITLE
Native file chooser on Linux returns wrong count when using BROWSE_MULTI_FILE

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#669]
This was reported in fltk-rs:
https://github.com/fltk-rs/fltk-rs/issues/1346
I'm guessing this is related to the Zenity file chooser.
Basically when using BROWSE_MULTI_FILE and choosing multiple files, the filechooser will return a count of 1, and filename(0) will return a `|` sepearted filename.

**To Reproduce**
```cpp
#include <FL/Fl.H>
#include <FL/Enumerations.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Native_File_Chooser.H>

void btn_cb(Fl_Widget *w, void *data) {
    Fl_Native_File_Chooser fnfc(Fl_Native_File_Chooser::BROWSE_MULTI_FILE);
    fnfc.show();
    printf("%d\n", fnfc.count());
    printf("%s\n", fnfc.filename(0));
    fflush(stdout);
}

int main(int argc, char **argv) {
    Fl_Window window(80, 80);
    Fl_Button btn(0, 0, 80, 80, "Browse");
    btn.callback(btn_cb);
    window.end();
    window.show();
    return Fl::run();
}
```

**Expected behavior**
For the file chooser to return the correct count. 

**Screenshots**
N/A

**FLTK Version**
Version 1.4 installed from git latest. Configured with CMake disabling wayland support, and enabling pango/cairo support.

**FLTK Configure / Build Options**
Configured with CMake disabling wayland support, and enabling pango/cairo support.

**Operating System / Platform:**
Triend on WSL linux ubuntu 18.04. With xserver via VcXsrv.

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by ManoloFLTK** [comment]
@MoAlyousef Good catch. The commit mentionned above should fix that. Please, close issue if you confirm.

**Comment by MoAlyousef** [comment]
Thanks @ManoloFLTK  
It works correctly
