### ISSUE TITLE
Can we remove the usage of __APPLE_QUARTZ__ ?

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#673]
**Is your feature request related to a problem? Please describe.**

Currently `__APPLE_QUARTZ__` is used in a single occurrence in operative code in [src/fl_overlay.cxx:102](https://github.com/fltk/fltk/blob/f1b2e92f077ca8de4b978e0e27e23f88749500af/src/fl_overlay.cxx#L102).

Can this be replaced with `__APPLE__` ?

`__APPLE_QUARTZ__` is currently defined in FLTK (not by the compiler) in `CMake` and in `configure.ac`. Note that macros with two leading underbars should be reserved to the compiler in C/C++ (AFAICT). If we could replace `__APPLE_QUARTZ__` with `__APPLE__` this would simplify our code as well (remove the definition from CMake and configure).

`__APPLE_QUARTZ__` doesn't seem to be documented anywhere (except in the CMP which is not the _user documentation_), hence we could remove it.

**I am using FLTK**
 - Version 1.4.0

**Describe the solution you'd like**
See problem description:
- replace `__APPLE_QUARTZ__` with `__APPLE__` in the code mentioned above
- remove its definition from configure and CMake

**Additional context**
Once it is removed we don't need to document it in the CMP (which is current work in progress).

**Comment by Albrecht-S** [comment]
@ManoloFLTK What do you think, and can you do this?

**Comment by ManoloFLTK** [comment]
I've removed all instances of __APPLE_QUARTZ__ that have lost any usefulness.

@Albrecht-S I would like to propose to also completely remove from `src/fl_overlay.cxx`
all its code under `#ifdef USE_XOR / #endif` . This code is supposed to implement xor-style drawing, but it's unused, not implemented for macOS, and I don't think FLTK would be improved by it. What do you think?

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks for removing `__APPLE_QUARTZ__` so quickly.

> XOR drawing ... This code is supposed to implement xor-style drawing, but it's unused, not implemented for macOS, and I don't think FLTK would be improved by it. What do you think?

I was aware of this code and thought some user **might** enable the `USE_XOR` macro which can be done by commandline option, as you know. I have no idea if it could improve FLTK in any way, or if users would use it at any time for any platform.

That said, I believe we can remove it and "wait for complaints". If there are any complaints we can add it back (it's in git anyway) and go ahead. Since this code wouldn't change any default FLTK build it doesn't affect the ABI and API, hence, yes, I believe we could remove it.

But maybe we should wait for a comment from @MatthiasWM: the code in question has obviously been disabled due to a bug reported in [STR 1438](https://www.fltk.org/str.php?L1438), git commit 32a8df787c76d7bd542b5903af86867d8704b8bb, more than 15 years ago in 2007. I believe that Matthias left the old code in the file in case it might be needed later.

@MatthiasWM, what do you think, can we remove this old, unused code?

**Comment by MatthiasWM** [comment]
The xor drawing came when the original SGI hardware overlay was not available on X11. It is limited to a single rectangle IIRC and was always a bad crutch. Today's computers should have no trouble using the simulated overlay from Fl_Overlay_Window.

**Comment by Albrecht-S** [comment]
@MatthiasWM I interpret this that you agree to remove the XOR drawing code, as Manolo suggested. Is this correct?

**Comment by ManoloFLTK** [comment]
Just FTR, file `fl_overlay.cxx` exists to support functions `fl_overlay_rect()` and `fl_overlay_clear()`. The current implementation works by reading on the display the state of the areas where the rectangle is going to be drawn, drawing a dotted rectangle, and writing back the contents of read areas to erase the rectangle. XOR would provide an alternative approach where an xor-drawn rectangle can be erased just by xor-drawing it again. The corresponding code is currently in place (but not used unless compiling FLTK with -DUSE_XOR) for X11 and Windows, but not for macOS or Wayland.

**Comment by MatthiasWM** [comment]
I have no PC access, but IIRC, the Mandelbrot demo uses the overlay rect. It should be possible to solve that better, but it is possible that this is used elsewhere. Fl_Overlay_Window is so much more versatile though. Not sure if is is buffering the main layer though.

**Comment by MatthiasWM** [comment]
Remove it. Please.

**Comment by Albrecht-S** [comment]
@MatthiasWM Thanks.

OK, who's going to remove it? @ManoloFLTK, would you like to do it? If not I can do it...

**Comment by ManoloFLTK** [comment]
The XOR-based code is now removed.

**Comment by Albrecht-S** [comment]
Another note: @MatthiasWM wrote:
> ... IIRC, the Mandelbrot demo uses the overlay rect. It should be possible to solve that better, ...

I checked that this is the only use of `fl_overlay_rect()` and `fl_overlay_clear()` in FLTK test programs, but of course these public functions can be used elsewhere in user programs.

FTR: I suggest to leave the Mandelbrot demo as is, because this is a good and our only test for this function.

@ManoloFLTK Thanks for removing the XOR code.
