### ISSUE TITLE
Move FLUID Shortcut_Button into fltk.lib as Fl_Shortcut_Button

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#677]
**Is your feature request related to a problem? Please describe.**
`Shortcut_Button` takes a users keystroke, converts it into an `Fl_Shortcut` type and displays the keystroke as a text. This button would be nice to have to allow users of the main library to write apps that allow custom shortcuts for menu items, for example. 

As this is already part of FLUID, there is no additional size in the source code if we move it to the main library. When linking the library statically, this code will be purged if not used, so no harm done either. It would add a kB or so to the shared library.

**I am using FLTK**
 - Version 1.4.0

**Describe the solution you'd like**
I'd like to move the code, rename the class, and add documentation.

**Describe alternatives you've considered**
Or we leave things the way they are, and potential users can copy the code from FLUID if they need this feature.

**Comment by Albrecht-S** [comment]
+1 :+1:

> or ... leave things the way they are, and potential users can copy the code from FLUID ...

Generally users can **use** code of the library in their applications, but **copying** code would at least require a compatible license which isn't always the case. Hence, if this is a common feature (and I see this in many apps), then it should be in a usable and subclassable widget.

**Comment by MatthiasWM** [comment]
See PR #680.
