### ISSUE TITLE
RFE: Add means to access previous value vs. current value in Fl_Choice (or Fl_Menu_)

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#685]
Please add a way to access the previous selection value (i.e., what the value was before the current selection value) as a convenient means for the user to figure out "from->to" transitions.

Or this could even be put into the parent class Fl_Menu_ for something even more useful.

As far as I am concerned, this could also only be valid / accessible while in the callback handling a value change.

Right now I have to implement my own code to remember and update the previous selection value. I could also put it in a derived class of course. But for those of us that need this, our efforts are redundant.

**Comment by Albrecht-S** [comment]
This sounds like a good idea, thanks for the request and description. I don't think that this would be too hard to implement.

I believe this could be done best by @MatthiasWM. Matthias, what do you think?

**Comment by MatthiasWM** [comment]
Add `const Fl_Menu_Item *Fl_Menu_::prev_mvalue();` to [144d7d3](https://github.com/fltk/fltk/commit/144d7d3529d00ef3fae3850f87c1cba4aadc59b9)
