### ISSUE TITLE
A different header order causes compilation errors in C++20.

### ISSUE THREAD

**Issue by yHan234** [fltk/fltk#686]
```
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Text_Editor.H>

int main(int argc, char **argv) {}
```

Using "-std=c++20" causes compilation errors:

```
Fl_Device.H
'HBITMAP' has not been declared

Fl_Pixmap.H
'UINT' does not name a type
```

Reverse the header order to compile successfully:

```
#include <FL/Fl.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Window.H>

int main(int argc, char **argv) {}
```

Removing "-std=c++20" also fixes the problem.

**FLTK Version**
 - Version: 1.3.8
 - Installed as package from: msys2
 - Downloaded and self-built from: msys2

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Comment by Albrecht-S** [comment]
OK, thanks for the report. This effect is weird, but it's not a bug. Let me explain:

First of all, I can reproduce the issue **_if and only if_** I compile the given program w/o defining `WIN32` on the commandline. However, this is required and [documented in FLTK 1.3.x](https://www.fltk.org/doc-1.3/basics.html#basics_visual_cpp) (but no longer in FLTK 1.4.x). Admitted, this requirement is pretty much hidden in the docs about Visual Studio, but it applies to all Windows build systems.

You don't seem to have defined `WIN32`, did you? Without doing this, the result is undefined. Just in case you did (which I doubt), please describe exactly how you build the demo program.

For your reference, building with MinGW (MSYS2) on my system:

Building w/o `-DWIN32`:
```
$ g++ --version
g++.exe (Rev6, Built by MSYS2 project) 12.2.0
...

$ g++ -std=c++20 -I. -mwindows -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o 'issue-686_header_order' 'issue-686_header_order.cxx' -mwindows ./lib/libfltk.a -lole32 -luuid -lcomctl32
In file included from ./FL/Fl_Device.H:32,
                 from ./FL/fl_draw.H:30,
                 from ./FL/Fl_Text_Display.H:27,
                 from ./FL/Fl_Text_Editor.H:28,
                 from issue-686_header_order.cxx:6:
./FL/Fl_Pixmap.H:66:3: error: 'UINT' does not name a type
   66 |   UINT pixmap_bg_color; // RGB color used for pixmap background
      |   ^~~~
./FL/Fl_Device.H:482:58: error: 'HBITMAP' has not been declared
  482 |   void copy_offscreen_with_alpha(int x,int y,int w,int h,HBITMAP bitmap,int srcx,int srcy);
```

Building with `-DWIN32`:
```
$ g++ -std=c++20 -DWIN32 -I. -mwindows -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o 'issue-686_header_order' 'issue-686_header_order.cxx' -mwindows ./lib/libfltk.a -lole32 -luuid -lcomctl32
```
(compiles and links w/o error).

**_Hint:_** FLTK provides you with a tiny tool called `fltk-config` which you can use to see which commandline switches you need. This can be used on all POSIX (like) systems, i.e. also on `MinGW/MSYS2`. Here's what I see (and where I started my tests from) if I use it on my build system:
```
$ ./fltk-config --compile issue-686_header_order.cxx
g++ -I. -mwindows -DWIN32 -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o 'issue-686_header_order' 'issue-686_header_order.cxx' -mwindows ./lib/libfltk.a -lole32 -luuid -lcomctl32
```
You can use this commandline and add `-std=C++20` and it will work. Note that `-DWIN32` is part of this commandline.

Before you ask: I don't know what `-std=C++` changes in this context, but the discussion would be moot anyway, for two reasons:
1. You need to define WIN32 in FLTK 1.3.x, and FLTK 1.3.x is no longer developed further.
2. In the current development version (1.4.x) this is no longer needed anyway.

I hope this helps. Please check your commandline and close this issue if it works for you with `-DWIN32` (or its equivalent in Visual Studio etc.).

**Comment by yHan234** [comment]
Thank you for your detailed answer!

**Comment by Albrecht-S** [comment]
Welcome.
