### ISSUE TITLE
fluid when certain changes are made, user can't use File -> Save

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#691]
**Describe the bug**
In certain cases making a change in fluid doesn't activate File -> Save, making it impossible to save the change unless you change something else.

In my case, changing the "Properties -> Attributes -> Divider" for an Fl_Choice menu item.

**To Reproduce**
1. Opened a fluid file (example attached as [simple_choice_fl.txt](https://github.com/fltk/fltk/files/10874069/simple_choice_fl.txt)) that contains an Fl_Choice with menu items.
2. Open Properties for one of the menu items, and enable the "Attributes -> Divider" toggle under the "GUI" tab.
3. Open the "File" menu and find "Save" is grayed out, and ^S does nothing.

This is bad/confusing especially if someone hits ^S then quits, never noticing that nothing was saved.

Perhaps as a precaution, hitting the ^S shortcut when Save is /deactivated/ should show a warning somehow, e.g.

    Nothing to save.
    Fluid thinks nothing has changed since your last save.

A click-away dialog might be too annoying, but maybe a borderless window inside the current window could appear briefly (for a second or two) and automatically clear away, similar to our Ctrl(+) and Ctrl(-) scaling feature that shows the current scale in a similar way.

**Additional context**
This is with a recent fltk 1.4.x,

**Comment by MatthiasWM** [comment]
This is inherited functionality and I find it very annoying. I can't count how many times I pressed F2 F3 to fake a change to activate the menu. Some months ago I added many "changed" conditions, but obviously I did not captcha them all. 

I can also simply disable the graying out, but I would also like to have the "changed" [*] indicates right.

**Comment by erco77** [comment]
Maybe File -> Save should never gray out, and anyone interested in seeing if something changed could depend on the "changed" [*] asterisk indicator.

At least any bug with that wouldn't cause the user data loss.

**Comment by MatthiasWM** [comment]
Fixed in #703
