### ISSUE TITLE
fltk-fltk-1.4.x-2023-03-05 -> pango-1.50.14

### ISSUE THREAD

**Issue by szukw000** [fltk/fltk#695]
The degree symbol e.g in '90°' triggers the following error message:

Invalid UTF-8 string passed to pango_layout_set_text()

What must I change? The error message seems to be new.

winfried

**Comment by erco77** [comment]
Be sure the symbol you're using is utf8 encoded. If it's encoded some other way, it won't work.

**Comment by MatthiasWM** [comment]
utf8 encoding of `°` is C2 B0, or `"\xC2\xB0"`

**Comment by szukw000** [comment]
The proposal of MathiasWM worked. But why? FLTK alsways translated from
ascii to utf8. But not now anymore.
winfried

**Comment by Albrecht-S** [comment]
> The proposal of MathiasWM worked. But why? FLTK alsways translated from
ascii to utf8. But not now anymore.

@szukw000 Winfried, ASCII is a part of UTF-8, but ASCII is **only the lower part (half)** of what Windows calls a "codepage", i.e. the characters from 0x00 to 0x7f (0-127 decimal). In the extended codepage used by Windows (aka `CP1252`) and e.g. in `ISO-8859-1` the `'°'` character is 0xb0 (176 decimal) which is not a legal character in UTF-8 encoding. Matthias posted its UTF-8 encoding which consists of two bytes.

To "fix" this you can set your editor to use UTF-8 encoding and then you can type the `'°'` character as usual and it will just work. Some editors can convert text files from ISO-8859-1 or Windows Codepage 1252 to UTF-8.

Note that there are some "tricks" in FLTK (for instance in test/editor) that try to convert such illegal UTF-8 sequences to UTF-8, assuming that they are encoded in either ISO-8859-1 or Windows Codepage 1252. The former is a subset of CP1252 as far as printable characters are concerned. You can view the character layout of [Codepage 1252](https://github.com/fltk/fltk/blob/master/misc/cp1252_utf-8.txt) and/or [ISO-8859-1](https://github.com/fltk/fltk/blob/master/misc/iso-8859-1_utf-8.txt) in our bundled character tables (links above go to the FLTK repo on GitHub).

That said, it can also make a difference if you use the default Pango setup on Linux or disable pango under Linux/X11 which doesn't show the error message you posted, but I don't know if it would "convert" non-UTF-8 characters...

**Comment by Albrecht-S** [comment]
Closing this issue now because it's fixed.
