### ISSUE TITLE
Shift-Tab not "reverse navigating" on some platforms

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#696]
**Describe the bug**
Shift-Tab for reverse keyboard navigation of input fields in programs like `test/input` seems to not work on some linux distros (in my case **debian11**), as if the sequence is ignored.

This doesn't seem to be a problem with the window manager shortcuts because Shift-Tab seems to work fine in other non-fltk applications (e.g. firefox) on the same machine.

**To Reproduce**
On the platforms that have this problem:

1. Run the test/input application
2. Hit Tab to navigate forward to the next field
3. Hit Shift-Tab to reverse-navigate to the previous field -- ** focus does not change **

**FLTK Version**
1.4.x current

**FLTK Configure / Build Options**
Default cmake build on this **debian11** test system, the results from cmake are:
```
-- Image Libraries: JPEG = Builtin
--                  PNG  = System
--                  ZLIB = System
-- Use Wayland:             Yes (when available at run-time)
-- All drawing uses Cairo:  Yes
-- Use Pango:               Yes
-- Fl_Cairo_Window support: No
```

**Comment by erco77** [comment]
This machine does have Xwayland, so I tried invoking the input program in these two ways:
```
FLTK_BACKEND=wayland ../build/bin/test/input
FLTK_BACKEND=x11 ../build/bin/test/input
```
Same results for both -- not sure if I'm doing that right.

**Comment by ManoloFLTK** [comment]
I confirm that shift-Tab doesn't work under Wayland with test/input as diagnostic app whereas it does work when the same app runs under X11.

**Comment by ManoloFLTK** [comment]
@erco77 This problem should be fixed with commit mentioned above. Please, close issue if you confirm.
