### ISSUE TITLE
IRC or Gitter Channel for immediate communication and queries on fltk

### ISSUE THREAD

**Issue by Thecarisma** [fltk/fltk#7]
I think it will be great if a gitter channel or IRC is created for fltk to help in facilitating communication.
Even though there exists a google group for fltk, the response there is slow and some time not up to date, with an IRC or gitter channel communication will be almost real time and small issues can be quickly discussed. 
I am open to managing the gitter channel.

**Comment by erco77** [comment]
IMHO I don't see a problem if it's a community managed thing (and not devs).
You can certainly set it up, make an article on the fltk.org site linking to it once it's setup; that way it will appear on the main page. We can also add a link to it on the community/forums page as a permanent link. IRC, slack, gitter.. or whatever works best.

**Comment by Thecarisma** [comment]
I ll setup the channels and prepare an article

**Comment by shlyakpavel** [comment]
@Thecarisma what do you think about Telegram? It is really convenient and popular

**Comment by Thecarisma** [comment]
Telegram would be a better option too but then gitter is more about developer communication and it allows integration of platforms and app. If github is integrated with a gitter channel all the issues and pr can be monitored from the channel..
Looking at the other communication channels of fltk It ll be easy to adopt and use.plus it super convenient to use.

**Comment by shlyakpavel** [comment]
@Thecarisma there are plenty of bots that bring GitHub into Telegram so it's no advantage

**Comment by Thecarisma** [comment]
I have never used telegram as a dev communication channel,  hence my choice for gitter.
Telegram is a proprietary thing that require people to install stuff in their phones. Who knows what sort of tracking they have and they share with governments. This project should use something more open IMO. Gitter is very friendly, can be used from a browser, allows anonymous access, but the better feature is that you can browse message logs! .
Gitter functions just like any other irc and with more advantages, there is no regretting the decision.

**Comment by Albrecht-S** [comment]
Gitter sounds interesting. I never used it but its integration with GitHub projects seems to be an advantage. Looking forward to your announcement, @Thecarisma

**Comment by Thecarisma** [comment]
whoops! 
I can't create a community for fltk as am not a member of the organization, one of the public member will have to do that on [https://gitter.im/](https://gitter.im/)

**Comment by Thecarisma** [comment]
Gitter Channel : 
https://gitter.im/fltklib/fltk

Article has been submitted at https://www.fltk.org/articles.php?L1622+P1
Article need review and approval.

**Comment by erco77** [comment]
> Article has been submitted at https://www.fltk.org/articles.php?L1622+P1
> Article need review and approval.
Approved -- it's on the front page now.

**Comment by Thecarisma** [comment]
Since this has been resolved it can be close now

**Comment by erco77** [comment]
Closed..

**Comment by erco77** [comment]
I've also updated the Forums (newsgroups) page on fltk.org with two references to the new channel.
OP, feel free to post on fltk.general (and fltk.coredev) about the new gitter channel, along with any details you think necessary.
BTW, I've contacted you by email regarding some additional questions.

**Comment by erco77** [comment]
Update: I've added "gitter" and "matrix/element" chat icon links to the FLTK main page (at the top right, next to the github and RSS feed icons).
