### ISSUE TITLE
Empty UI rendered when loading more than 1 FLTK UI instances

### ISSUE THREAD

**Issue by AnClark** [fltk/fltk#700]
**Describe the bug**
I'm using FLTK to implement music plugin editor UI for Windows. The plugin has VST2, VST3 and CLAP formats, via DISTRHO Plugin Framework. FLTK can only render UI when instantiating one plugin format in DAW.

At this time, if I replace the current instance with another format of the same plugin, it ends up with an empty UI.

To simplify, the UI only contains a FLTK native `Clock` widget. I removed any Cairo-related custom widgets, so issues about Cairo can be eliminated.

Related project: <https://github.com/anclark/infamousplugins/tree/test/fltk-simple-window>

**To Reproduce**
1. Build the project via `cmake -S . -B build -DCLASSIC=OFF -DDPF=ON -DPLUGINS_DPF=casynth`
2. Install built plugins (located in `build/bin`)
3. Open REAPER, create an empty project
4. Create an empty track, and load the VST2 format of plugin `VSTi: the infamous cellular automaton (Spencer Jackson, AnClark Liu)`
5. In FX Chain window, replace the plugin instance with the VST3 (or CLAP) version of the plugin (shows `VST3: the infamous cellular automaton (Spencer Jackson, AnClark Liu)`)

**Expected behavior**
The UI should be rendered like this, on Step 4:
![image](https://user-images.githubusercontent.com/12870704/225613750-483c3892-ba45-4e53-ad57-31323550dd97.png)

**Screenshots**
Problem occured, on Step 5, like this:
![image](https://user-images.githubusercontent.com/12870704/225613904-eae16701-00e9-4c52-ad9b-88d572e2f2a6.png)

**FLTK Version**
- Version: 1.4.0
- Installed as package from: Build from source
- Downloaded and self-built from: Git
- If from Git, branch: master
- If from Git, commit: af47890

**FLTK Configure / Build Options**

Build FLTK with these options tuned (FLTK source is added as a submodule of my project):

```cmake
set (FLTK_BUILD_EXAMPLES OFF CACHE BOOL "")
set (FLTK_BUILD_TEST OFF CACHE BOOL "")
set (FLTK_BUILD_FLTK_OPTIONS OFF CACHE BOOL "")
set (FLTK_BUILD_FLUID ON CACHE BOOL "")

set (FLTK_SRC_DIR ${PROJECT_SOURCE_DIR}/vendor/fltk)

set (OPTION_BUILD_HTML_DOCUMENTATION OFF CACHE BOOL "")
set (OPTION_BUILD_SHARED_LIBS OFF CACHE BOOL "")

set (OPTION_CAIRO ON CACHE BOOL "")
set (OPTION_CAIROEXT ON CACHE BOOL "")
set (OPTION_USE_GDIPLUS ON CACHE BOOL "")
set (OPTION_USE_SVG ON CACHE BOOL "")

set (OPTION_FILESYSTEM_SUPPORT ON CACHE BOOL "")

set (OPTION_USE_SYSTEM_LIBJPEG OFF CACHE BOOL "")
set (OPTION_USE_SYSTEM_LIBPNG OFF CACHE BOOL "")
set (OPTION_USE_SYSTEM_ZLIB OFF CACHE BOOL "")
```

**Operating System / Platform:**
- OS: Windows
- OS Version: Windows 10

**Dependencies (Msys2):**
All packages are in mingw64 variant.
- cairo: 1.17.6-3
- pixman: 0.42.2-1

**Comment by AnClark** [comment]
In addition:

Different plugin formats seem to be loaded isolated in my DAW. This means the same static variable has different instances among different formats, and each format an instance.

I know many FLTK states are defined as static variables. Now that they are isolated among plugin formats, the UIs should be loaded well. However, the result is:

<details><summary>The wrong behavior when loading VST2 and VST3 versions of my project, each format 3 instances respectively</summary>

![image](https://user-images.githubusercontent.com/12870704/226165117-acefe299-cf23-4526-910a-ae54c296c2e2.png)

</details>

**Comment by MatthiasWM** [comment]
From what I read on the DPF pages, DPF has its own UI framework with their own Widget implementations: https://distrho.github.io/DPF/classWidget.html . I don't think that DPF anticipated that user link with different UI libraries like FLTK, so what you are trying to may not work. But I do not know much about DPF to begin with. I recommend that you ask in their mailing list.

It is often not possible to mig GUI libraries via plugins, because every UI library must access the same stream of system events to figure out what the user of system wants. Those event streams are often impossible to share or separate in a meaningful way.

**Comment by MatthiasWM** [comment]
There is a list of audio apps for Linux that use FLTK, but I don't think that these are plugins in the classical sense. Again, I am not deep into this subject at all,. Maybe someone can correct me:

https://wiki.linuxaudio.org/apps/categories/fltk

**Comment by AnClark** [comment]
> I don't think that DPF anticipated that user link with different UI libraries like FLTK, so what you are trying to may not work.

@MatthiasWM I also participate in DPF development, for example, external UI support on CMake build system.

DPF itself has external UI support, which means developers can use 3rd-party UI framework, as long as you can load your UI, and embed it into the host (optional).

Qt, NTK, FLTK and other frameworks are supported.  FalkTX himself wrote Carla and Cardinal's plugin version in Qt, and helped porting ZynAddSubFX's FLTK and NTK UI to DPF.

**Comment by ManoloFLTK** [comment]
Is it possible that the 1st plugin closes the display connexion when it's unloaded, and that the 2nd plugin attempts to re-open the display connexion? That is something that FLTK does not support: any client program can only run without GUI after the FLTK library has closed its display connexion.

**Comment by MatthiasWM** [comment]
@AnClark Thanks for the clarification. I'll stop my wild guesses ;-)

**Comment by AnClark** [comment]
@ManoloFLTK My explanations has ambiguity. The "only one instance" means:

- Only one plugin format can show UI properly if you load it at first.
- When loading another format of the same plugin, its UI won't be shown.

Just as this screenshot describes. The 3 windows is the VST3 format's instances, while the 2 gray windows on the left is VST2 format's. I load VST3's first, so their FLTK UIs can be rendered properly.

![image](https://user-images.githubusercontent.com/12870704/226165117-acefe299-cf23-4526-910a-ae54c296c2e2.png)

**Comment by AnClark** [comment]
> In that case, each plugin was linking with FLTK in a way that generated a new UI loop for every plugin. This can not work, because event loops are fighting over the same event queue, stealing each others events.

No wonder why I encountered such an issue. Sounds that the event queue is only one no matter how much plugin instance it creates. Maybe on REAPER, the instances with same format does not conflict each other, but cross-format does (e.g. creating both VST3 and CLAP instances).

Is it possible to debug, and improve FLTK's event loop and event queue procedure?

---

> I came across a similar effect and was reminded of this issue.

BTW, what is the "effect" you mentioned? Is it another audio plugin?

**Comment by MatthiasWM** [comment]
> Is it possible to debug, and improve FLTK's event loop and event queue procedure?

It's not an issue with FLTK. Every process has just one event queue. VST as the main app must distribute events for you. Looking at some sample code, it seems you have to derive from the class LV2_External_UI_Widget and implement your own "run()" method. All that does is pretty much call Fl::check() which is telling FLTK to handle all events in the queue. All your widgets are the manage in callbacks. 

The main loop is inside the main app. Your plugin just gets a call when there is an event available for it. But I have no time to go much deeper into the VST API. I love to learn from working code, and I found this: https://github.com/Yoshimi/yoshimi , and it seems to be very readble.

> > I came across a similar effect and was reminded of this issue.
> 
> BTW, what is the "effect" you mentioned? Is it another audio plugin?

An app had linked different modules with different FLTK libraries, resulting in multipel event loops. Fixing the linking process fixed the issue. This here seems to be slightly different though, as described above.

**Comment by AnClark** [comment]
Thanks @MatthiasWM . As long as I reconfigure my Msys2 environment I can test again.

Are you familiar with LV2 SDK? I found that LV2 has an entry of `LV2_UI__idleInterface`. Some plugins, including [infamousPlugins](https://github.com/ssj71/infamousPlugins/tree/master/src/casynth) use this instead of `LV2_External_UI_Widget`'s `run()` method.

Here's the code section (including UI resize extention):

```c
static int
idle(LV2UI_Handle handle)
{
  CaSynthUI* self = (CaSynthUI*)handle;
  self->idle();
  
  return 0;
}

static int
resize_func(LV2UI_Feature_Handle handle, int w, int h)
{
  CaSynthUI* self = (CaSynthUI*)handle;
  if(self && w>0 && h>0)
      self->ui->size(w,h);
  
  return 0;
}

static const LV2UI_Idle_Interface idle_iface = { idle };
static const LV2UI_Resize resize_ui = { 0, resize_func };

static const void*
extension_data(const char* uri)
{
  if (!strcmp(uri, LV2_UI__idleInterface))
  {
    return &idle_iface;
  }
  if (!strcmp(uri, LV2_UI__resize))
  {
    return &resize_ui;
  }
  return NULL;
}
```

In DPF, it has an API called `DISTRHO::UI::uiIdle()`. This is invoked on `LV2_UI__idleInterface` call as well. I run `Fl::check()` there.

**Comment by MatthiasWM** [comment]
Hmm, no, I am not involved in lv2, but I am trying to gather what I can from the docs. I find links form 10 years ago with people using FLTK with lv2, but the current page doesn't mention it: https://lv2plug.in . Looking at what this guy does: http://mountainbikesandtrombones.blogspot.com/2014/08/making-lv2-plugin-gui-yes-in-inkscape.html , everything seems a bit patched together. I wish I could help you with this, but I am not sure how they got things to run. There are a few plugins on GitHub that seem to use FLTK. If you can test them, and they work with multiple instances, then maybe those make a good base structure for what you want to do.

**Comment by MatthiasWM** [comment]
I am closing this now. This can't be resolved without any of the core developers or the OP diving deep into this specific music software. I tried to describe what is needed (a single event loop), but I can't find any more examples besides those that I posted.

If the author of teh original software is interested in continuing support of FLTK, I will be happy to assist as much as possible.

**Comment by AnClark** [comment]
Still thanks a lot. 

Surely it needs a lot of work to improve FLTK to fit with what I need. I consider putting it aside as well, as I'm working on other projects. Migrating to other toolkits (e.g DPF's DGL) is also a good choice.
