### ISSUE TITLE
Wayland surfaces maybe not released

### ISSUE THREAD

**Issue by nahsheef** [fltk/fltk#702]
**Describe the bug**
Using Ctrl + and - to zoom in/out several times seems to allocate Wayland surfaces that are not released after restoring the zoom level. I'm using fltk-rs (Rust bindings) and opened a [discussion](https://github.com/fltk-rs/fltk-rs/discussions/1373) there, but asking here as well since I suspect it's likely a design behavior of the Wayland driver, or a limitation, maybe a bug. 

**To Reproduce**
 - `cargo new fltktest`
 - `cd fltktest`
 - `cargo add fltk@1.2.28 --features=use-wayland`
 - `rm src/main.rs`
 - `curl -o src/main.rs https://raw.githubusercontent.com/fltk-rs/fltk-rs/master/fltk/examples/hello_button.rs`
 - `cargo run`

**Expected behavior**
After returning to the initial zoom level, or time passing after the last several zoom levels, memory should return close to initial RSS value.

**Screenshots**

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: fltk-rs 1.3.28

**FLTK Configure / Build Options**
FLTK Rust bindings with `use-wayland` feature enabled.

**Operating System / Platform:**
 - OS: Arch Linux

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by Albrecht-S** [comment]
@nahsheef Thanks for the report. However, we need more details, for instance, how do you "measure" RSS? Are we talking about the same ["resident set size (RSS)"](https://en.wikipedia.org/wiki/Resident_set_size)?

I tried to figure out what you mean and used several variants of `ps`, and I can see that the value of 'RSS' seems to grow significantly when I use either `ctrl/+/-/0` or resize any FLTK window when using the Wayland backend. The same program running with the X11 backend grows much less (but it does, slowly). This effect may be explained by the memory buffers used by the Wayland backend.

I can't tell why the RSS doesn't decrease after some time. Would it really do this? On my system there's lots of free memory, hence I don't know when the system would trim the working set of a particular process...

That said, I don't know the Wayland internals. Maybe @ManoloFLTK can tell more, and maybe he can find where memory **should** be released. I just wanted to let you and him know that I can see the effect, but I don't know if this is really an issue.

@nahsheef Did you really notice an issue with this on a heavy loaded system where memory should be trimmed, or is this just an observation? And please tell us a "recipe" how you "measure" so we are on the same level. TIA.

**Comment by nahsheef** [comment]
As a "recipe" I was loosely tracking resident set size of a small tool I'm building with fltk-rs, watching `top`, because I was happy to see how little memory FLTK uses. It didn't impact overall system load, but I found it unexpected that memory seems to be retained. Maybe release is triggered after N redraw cycles or a comparable threshold which I haven't hit during my short experiment.

**Comment by nahsheef** [comment]
I assume the memory allocated internally is not marked as or of type that the kernel is allowed to free while the process is alive. Under high system load OOM would rather kill the process as a whole.

**Comment by erco77** [comment]
Just a side note: you probably won't often see applications decrease in memory size for this reason:
https://stackoverflow.com/questions/14023815/memory-stability-of-a-c-application-in-linux

Typically the heap is implemented with `brk(2)` only ever growing in size, due to how "memory holes" develop during an application's execution in real time, where the most recent mallocs that occur near the end of the heap can remain allocated while addresses below it get free()d. At best the application won't /grow/ when the app isn't allocating memory, but it probably won't shrink during free/delete. Memory free/delete'd will simply be reused, if possible.

**Comment by ManoloFLTK** [comment]
I believe all memory used to create, resize, and draw into Wayland windows is released after use by the FLTK library. The memory structure used by Wayland to hold the graphics data mapped on the display has type `struct wl_buffer` and is itself made using what Wayland calls "buffer factory" of type `struct wl_shm_pool`. This is memory shared between the client app and the Wayland compositor, created by the client app as an mmap'ed, in-memory anonymous file. The Wayland library guarantees that the mmap'ed memory will be ultimately released when it's no longer used : see the Wayland documentation of [wl_shm_pool::destroy](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_shm_pool).
How that is done exactly is internal to the Wayland system, that is, not directly under FLTK control. See [there](https://fltk.gitlab.io/fltk/wayland-devel.html#wayland-buffer-factory) for full details about how FLTK creates and uses its buffer factory.

**Comment by nohsheef** [comment]
Update: with fltk-rs 1.4.7 and the cfltk it relies on, this issue seems to be resolved. From what I can tell, while there is growth, it does settle and isn't growing indefinitely without a release.

**Comment by Albrecht-S** [comment]
@nohsheef Thanks for the feedback.
