### ISSUE TITLE
RFE: Add -I<directory> option flags to fltk-config 

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#705]
( Note the enhancements in #656 will solve this for me, but I wanted to enter this as a simpler RFE in case #656 is deferred, or maybe just as reinforcement. )

Please add `-I<directory>` option flags to fltk-config as a convenience for the user.

For example, if I have some header files in directory `/mydir` needed by `myprogram.cpp`, I would like to issue the command
```
fltk-config -I/mydir --compile myprogram.cpp
```
Note
```
fltk-config --includedir
```
gives an include for the FLTK header files installation path, e.g. `-I.../apps/usr/local/gcc-11.3/include`.

But
```
fltk-config -I/mydir --includedir
```
would add `-I/mydir` to it, thus:   `-I/mydir -I.../apps/usr/local/gcc-11.3/include`.

Opinion: fltk-config already recognizes -D flags, so to me, having it also recognize -I flags sort of completes the picture with respect to its use in compilation.

**Comment by Albrecht-S** [comment]
Thanks, all your arguments sound useful.

This will definitely be handled by the implementation of issues #656 and #647, respectively. The final solution will forward everything that's not recognized as a known switch to the compiler command line.

Note: this comment automatically adds a link (aka "mention") to these two issues. Therefore I'm closing this issue now as a duplicate.

**Comment by Albrecht-S** [comment]
Note: commit 877126e572c2d473cd80de7abaae6d0fadc5c142 fixes this issue. It allows more than one source file and additional compiler and linker switches. Please see #647 for details.
