### ISSUE TITLE
Wayland backend draws everything two or three times

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#708]
See attached test program [draw_box.cxx](https://github.com/fltk/fltk/files/11052725/draw_box.cxx.txt)

FLTK 1.4.0 current Git (aebf2fec39640e2151d818e96f182af1cb3a63b3)
Platform: Wayland is buggy as compared to others (tested so far on Linux/X11 and Windows)

Compare the output on X11 vs. Wayland:
```
$ ninja draw_box 
[2/2] Linking CXX executable bin/test/draw_box
$ 
$ FLTK_BACKEND=x11 bin/test/draw_box
my_box::draw[   1] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   2] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.10, damage = 0x80
my_box::draw[   3] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.20, damage = 0x80
my_box::draw[   4] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
$ 
$ FLTK_BACKEND=wayland bin/test/draw_box
my_box::draw[   1] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   2] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   3] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   4] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.10, damage = 0x80
my_box::draw[   5] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.10, damage = 0x80
my_box::draw[   6] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.20, damage = 0x80
my_box::draw[   7] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.20, damage = 0x80
my_box::draw[   8] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   9] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
```

**Test procedure:**
1. Build and run the demo program (use `fltk-config --compile` to build)
2. Type `ctrl/+/-/0 `and watch the output.
3. Note how the output value of "scale" changes once but `draw()` is called two or three times on Wayland [1].

FYI: `damage = 0x80` == `FL_DAMAGE_ALL`.

[1] `draw()` seems to be called **three times for the initial drawing** and **twice after scaling** the window. Manual resizing has the same effect.

**Expected behavior:**
`draw()` should be called only once on Wayland, as on the other platforms.

Although drawing under Wayland works on an internal buffer it can be expensive to do it, hence it shouldn't be done more often than necessary - even if the result wouldn't be transmitted to the Wayland compositor more than once.

I added the `damage()` flags to the output to show that even if the widget would use minimized drawing this wouldn't help because the flag is always `FL_DAMAGE_ALL`.

**Comment by wcout** [comment]
The second redraw after scaling seems to triggered by the appearance or dismissal of the "transient popup window" which displays the zoom factor. When disabling this popup using `fltk-options` there is no second redraw.

**Comment by ManoloFLTK** [comment]
Only 1 redraw for each scale value here (Debian + gnome) :

my_box::draw[   1] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   2] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   3] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.00, damage = 0x80
my_box::draw[   4] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.10, damage = 0x80
my_box::draw[   5] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.20, damage = 0x80
my_box::draw[   6] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.33, damage = 0x80
my_box::draw[   7] box = ( 10,  10, 120, 120), window = ( 300,  300), scale = 1.50, damage = 0x80

Moeover, Wayland does not allow to center a window on a display, contrarily to what is done under X11. Transient scale factor windows under Wayland are implemented as a transient subwindow of the front window. It's then a matter of the Wayland compositor to call or not for a redraw when a subwindow is removed. That's not under FLTK control.

For this reason, I propose to close this issue. 

@Albrecht-S Do you agree?

**Comment by wcout** [comment]
Another redraw is done whenever the window loses or gains focus, which is not the case under X11. Is this also a Wayland thing?

**Comment by Albrecht-S** [comment]
@ManoloFLTK OK, let's see...

- The inital draw() is repeated three times which can't be explained by the "scale window" (X11: only once).
- I wrote also that the same happens with manual resizing which also doesn't display another window. Just look at the window size values instead.
- To rule out the "scale window effect" I disabled the scale window (in fltk-options), and indeed I see only one draw() call.

I should also have mentioned that I built the demo program on my older Linux Mint 20 and copied the binary to my Debian Bookworm system (this is a pretty new system, not yet set up to build FLTK). Maybe this makes a difference, I don't know. I'll check this as soon as this system works for me.

Anyway, what we have now:

- Drawing twice when rescaling the display can obviously not be avoided. Unfortunately this was my primary test because it was so simple.
- Drawing twice when resizing manually is still an open issue. Can anybody please test this on your system?
- We could try resizing in a timer event which would be another point to check.

**Comment by Albrecht-S** [comment]
> We could try resizing in a timer event which would be another point to check.

Done this, and it's OK. draw() is called only once after setting the new size.

Manual resizing is different though:
- Clicking on the window border and releasing the mouse button w/o movement each draw twice (i.e. a total of four times). This **may** have to do with the focus loss mentioned by @wcout above. @ManoloFLTK, do you think that this could be the case? Are borders and title bars separate windows (from the composer's view)? ISTR something like that.
- Dragging the vertical border draws multiple times (at least twice) with the same window width, even if I try to drag very quickly.

I'm not sure if we can change this but maybe you, Manolo, have an idea. It would definitely be good to remove unnecessary draw() calls, if possible.

It's still noteworthy that all these unnecessary drawings are not seen on X11 which makes it look like a regression to users experiencing subjective slowness on Wayland.

Modified test program attached: [draw_box-2.cxx.txt](https://github.com/fltk/fltk/files/11055050/draw_box-2.cxx.txt)

**Comment by Albrecht-S** [comment]
@ManoloFLTK Yes, thank you very much, this commit fixes all issues I was seeing:
- initial draw done only once
- no draw when clicking and releasing on the border w/o dragging
- no draw on focus loss and regain
- only one draw when resizing manually (per different size)
- no draw when rescaling with scaling size display, even if the box is partially occluded by the window

That's awesome! Thank you.

Closing this issue now: fixed.
