### ISSUE TITLE
fltk-config --use-images --ldflags

### ISSUE THREAD

**Issue by geuzaine** [fltk/fltk#709]
I'm using cmake to configure FLTK. When `OPTION_USE_SYSTEM_LIBJPEG`, `OPTION_USE_SYSTEM_ZLIB` and `OPTION_USE_SYSTEM_LIBPNG` are set, the `fltk-config` script is always created with `IMAGELIBS=-ljpeg -lpng -lz` (the values are harcoded in `variables.cmake`). This does not work when the libraries are installed in a non-standard location (e.g. /opt/homebrew/lib).

The correct path to the libraries is actually found in `options.cmake`, but it is not used when creating the `fltk-config` script.

**Comment by Albrecht-S** [comment]
Thanks for the report, I'll check and fix this.

**Comment by Albrecht-S** [comment]
I believe this issue has been fixed by our move to "Modern CMake" in commit fd5cd809356dc73d2ede5bb2f0db25098771cb8e.

@geuzaine Please confirm and close the issue.

**Comment by Albrecht-S** [comment]
No reaction for 25 days, closing this issue now. Please open a new issue if this is still a problem.
