### ISSUE TITLE
Wayland regression: non-resizable windows are positioned in the wrong place

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#711]
**Describe the bug**
On my Linux Mint 20 system (based on Ubuntu 20.04 LTS) in a Gnome/Wayland session **non-resizable program windows** are positioned at the very top left position of the screen working area such that the title bar is hidden. These windows can't be moved by the user because the title bar is not accessible.

Resizable windows are positioned as expected.

The **identical binaries** work well on `Debian Bookworm` with recent updates, also in a `Gnome/Wayland` session (after copying the binaries to the other system).

This is a regression since Git commit e918d94b6791e81438233e7672ad0b2223c57dc8 for issue #708.

**To Reproduce**
Build current FLTK (since above mentioned commit) and run one of the non-resizable test programs, for instance `hello`, `arc`, `blocks`, `button`, `curve`, etc.. An exception from the rule seems to be `test/animated` which appears shortly in the top position and then quickly jumps to a "correct" position.

You can find test programs w/o an explicit `resizable()` statement with a bash shell command like this one:
```
for f in test/*.cxx;do echo "----  $f  ----"; grep resizable $f;done
```
Look for a source file name w/o an immediately following line with `resizable`.

**Expected behavior**
All windows should be positioned with an accessible title bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/26235500/228940089-de14bdda-57e7-4419-84c5-5caf699fc713.png)
This screenshot shows the top left corner of the Gnome/Wayland desktop where the title bar of test/hello seems to be hidden behind the Gnome bar.

**FLTK Version**
 - Version: 1.4.0 Git
 - Git branch: master, commit see above (introduces the regression)

**FLTK Configure / Build Options**
Default (hybrid) build with CMake (not tested with configure/make).

**Operating System / Platform:**
 - OS: Linux Mint 20 (based on Ubuntu 20.04 LTS)

**Linux/Unix Runtime:**
 - Wayland (Gnome/Wayland session)
 - works well if binary is copied to Debian 12/Bookworm (Gnome/Wayland)
 - note: I didn't have a chance yet to build FLTK apps directly on Debian Bookworm

**Comment by ManoloFLTK** [comment]
That should be fixed now.

**Comment by Albrecht-S** [comment]
Yep, works as expected again. Thanks.
