### ISSUE TITLE
Giant cursor on Wayland + fractional scaling

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#713]
**Describe the bug**
Running any FLTK app under Wayland with scaling = 1.25x will make cursor "giant".
Aparently this regression happened in commit eeb9267e6ea1a8481bef36186e36c02189924f3b. Downgrading to previous commit fixes it.

Here's the video:

https://user-images.githubusercontent.com/6562863/230622814-978a379f-b745-4031-a752-5eddb1444eb4.mp4

**To Reproduce**
1. Run GNOME-shell under Wayland
2. Enable fractional scaling: `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
3. Re-login, go to `Settings` -> `Displays` -> `<your display>` and set `Scale` to `125%`.
3. Build and run FLTK from master branch
4. Run any application, e.g. `fltk-options`

**Expected behavior**
Cursor size should be proportional to other controls, similarly to cursor size on titlebar rendered by GTK3.

**Screenshots**

![Screenshot from 2023-04-07 16-58-34](https://user-images.githubusercontent.com/6562863/230621741-7ab31f17-628e-40aa-8941-9c915a3f8fdd.png)

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 0691833375bd97004890d4bbdcf12d7e4c2040ab

**FLTK Configure / Build Options**
 - `cmake -DCMAKE_BUILD_TYPE=Debug -DOPTION_WAYLAND_ONLY=ON ..`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Fedora 37

**Linux/Unix Runtime, if applicable:**
 - Wayland / GNOME 43

**Comment by ManoloFLTK** [comment]
FLTK has not been tested with fractional scaling.

Is this experimental feature useful?
FLTK supports gnome's 100% and 200% scales and brings, in addition to that, its own fractional scaling with 2 channels:
- type ctrl/+/-/0/ to increase, decrease, reset scaling
or
- set the FLTK_SCALING_FACTOR environment variable to any value (e..g., 1.25, 1.5).

@polter-rnd What is in your view the utility of fractional scaling values?

**Comment by polter-rnd** [comment]
>  What is in your view the utility of fractional scaling values?

I'm using this feature for a long time, that was the main reason of switching to Wayland for me. The utility for me is that I having 2 screens, one is 15" laptop and another one is 23" monitor. They both are FullHD but are quite unusable together because of different DPI. Setting 125% scale for laptop monitor makes UI size quite the same on both of them.

> FLTK has not been tested with fractional scaling.
>  FLTK supports gnome's 100% and 200% scales and brings, in addition to that, its own fractional scaling with 2 channels

Actually this is something different, and It's not related to cursor size.

Fractional scaling in GNOME works in a different way: it renders the window at next integer scale first (so FLTK does not know about 1.25x, it is told to render on 2x) and then downsizes the image in the compositor to 1.25x.

The regression I mention in this topic is only for cursor size - before commit eeb9267e6ea1a8481bef36186e36c02189924f3b it was working as expected

**Comment by ManoloFLTK** [comment]
Many thanks for this explanation. I was not aware of how this experimental feature works.

FLTK now correctly sizes cursors at 100% and 200% without the experimental feature, whereas they appear too big for all but 100% when  the feature is activated.

Is the feature consistent in that the compositor downsizes window graphics and also cursor graphics?

**Comment by polter-rnd** [comment]
@ManoloFLTK  After some more testing it eventially turns out that this issue is not related to fractional scaling. I tried to set scale to `200%`  and cursor size renders at 4x scale :)

**Comment by ManoloFLTK** [comment]
> I tried to set scale to 200% and cursor size renders at 4x scale :) So it's always bigger than expected on every scale > 1.0.

That does not happen when the experimental feature is off: a cursor at 200% has twice the size of the same at 100% which keeps it in line with the rest of the GUI.

I'll see what I can do to support fractional scaling. But for now, it's not supported, and typing ctrl-+ on one display and not the other, you'll get essentially the same result since scaling is done separately for each display.

**Comment by ManoloFLTK** [comment]
This issue should be fixed with the above-mentionned commit. 
@polter-rnd Please, close issue if you confirm.

**Comment by polter-rnd** [comment]
Many thanks! It is fixed by https://github.com/fltk/fltk/commit/4c567
