### ISSUE TITLE
fltk-config error with CAIRO

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#714]
In latest (at this time) 1.4 commit 877126e572c2d473cd80de7abaae6d0fadc5c142, which I build configured with CAIRO + static libs on my Linux Mint machine, file `fltk-config.in` line 98 I think has a bug.
```
if test -n $CAIROFLAGS; then
```
ought to be
```
if test -n "$CAIROFLAGS"; then
```
where in my case CAIROFLAGS on line 41 is defined as
```
CAIROFLAGS="-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16"
```

I believe thanks to the missing quotes, when I do `fltk-config --cxxflags` I get this error:
```
.../apps/fltk/fltk-clone# fltk-config --cxxflags
.../bin/fltk-config: 98: test: -I/usr/include/cairo: unexpected operator

**Comment by Albrecht-S** [comment]
Thanks for the report, fixed in 100786222c12eef7c72643e6855cec11baa35678.

**Comment by Albrecht-S** [comment]
OK, I reopened the issue, and I'll fix this ASAP (maybe not today though). Sorry for the trouble.

**Comment by Albrecht-S** [comment]
I decided to fix this immediately because it's Thursday evening and the next snapshot will be packed tomorrow morning. This fix should really be included.

Thanks again for reporting the bug.
