### ISSUE TITLE
Fl_Table::find_cell doesn't appear to update when resizing the table

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#721]
**Describe the bug**
Fl_Table::find_cell doesn't appear to update when resizing the table

**To Reproduce**
```cpp
#include <FL/Fl_Double_Window.H>
#include <FL/Enumerations.H>
#include <FL/Fl_Table.H>
#include <FL/Fl.H>

class MyTable: public Fl_Table {
    public:
    MyTable(int x, int y, int w, int h, const char *label = 0): Fl_Table(x, y, w, h, label) {
        rows(4);
        cols(4);
        box(FL_BORDER_BOX);
        color(FL_RED);
    }
    void resize(int x, int y, int w, int h) override {
        Fl_Table::resize(x, y, w, h);
        printf("%d\n", w); // this is updated
        int cell_x, cell_y, cell_w, cell_h;
        find_cell(CONTEXT_CELL, 3, 3, cell_x, cell_y, cell_w, cell_h);
        printf("%d\n", cell_x); // this is not updated
        puts("");
    }
};

int main() {
    auto win = new Fl_Double_Window(800, 600);
    auto table = new MyTable(0, 0, 800, 600);
    win->end();
    win->resizable(win);
    win->show();
    Fl::add_timeout(0.2, [](void *w) {
        auto table = (MyTable *)w;
        table->resize(0, 0, 400, 600);
        Fl::redraw();
    }, table);
    return Fl::run();
}
```

If you build the attached program, you'll notice that the table resizes automatically after some timeout delay, the printed width from the overriden resize method is correct, however the printed cell_x from find_cell doesn't seem to be updated.
You can change the delay or even remove it, it's just for demonstration purposes.

**Expected behavior**
find_cell should take into account the new size of the table when it's resized.

**Screenshots**
N/A

**FLTK Version**
 - Version: 1.4 (built from master using cmake)

**FLTK Configure / Build Options**
`cmake -Bbin -GNinja -DFLTK_BUILD_TEST=OFF && cmake --build bin`

**Operating System / Platform:**
- Ubuntu 20.04 on wsl.

**Linux/Unix Runtime, if applicable:**
 - Hybrid

**Additional context**
N/A

**Comment by wcout** [comment]
I don't think this is a bug.
It is hard to see what happens in this example, because there is no table data displayed, but if you adapt the FLTK example `table-simple.cxx` you can see that is seems normal behaviour that table cells are not affected by resizing of the whole table, instead the table will show in a scroll area.
Or do I understand something wrong?

**Comment by MoAlyousef** [comment]
Thank you for the clarification. I guess that I was expecting that resize would readjust the size of the cells if the row height and column width aren't set. It seems this is intended behavior.
