### ISSUE TITLE
FLUID crashes when SHIFT key or Control + C keys are used in Settings > External Editor input field

### ISSUE THREAD

**Issue by udgigor** [fltk/fltk#722]
**Describe the bug**
FLUID crashes when SHIFT key or Control + C keys are used in Settings > external editor input field

**To Reproduce**
On Windows 10, Build Fluid.

1. Go to fltk/fluid/
2. open fluid.exe
3. Go to Edit menu 
4. Choose "Settings"
5. Click into "External Editor" input field
6. Hold Shift Key ****CRASH***
7. repeat steps 1 through 5
8. Press Control + C keys to pase  ****CRASH***

**Expected behavior**
should be able to set an external editor by name or path

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from:  Git, 
 - If from Git, branch: . master, branch-1.4.0
 - If from Git, commit: [e.g. 7d58e2385452]??? _ I dunno

**FLTK Configure / Build Options**
I just used MSYS2 MinGW 64 shell:
```
make config
make all
```

**Operating System / Platform:**
 - OS: Windows
 - OS Version: 10

**Comment by udgigor** [comment]
I don't know it very well either I just installed according to these instructions, part of building old FLTK 1.1.8 for MurgaLua

**Windows Setup instructions (x64)**

**Install MSYS2 with installer:**
https://www.msys2.org/

**Install MinGW 64-bit toolchain via MSYS2 UCRT64:**
`pacman -S mingw-w64-x86_64-toolchain`

Add _"C:\msys64\mingw64\bin"_ to the **PATH** system environment variable

Close MSYS2 UCRT64 and open MinGW64 shell that you just installed via pacman (MSYS2 MINGW64)

**Install git** (needed for fetching thirdparty repos), autotools (for make) and other required MSYS2 packages via MSYS2 MINGW64:

`pacman -S git`

`pacman -S mingw-w64-x86_64-autotools`

`pacman -S mingw-w64-x86_64-freealut`

`pacman -S mingw-w64-x86_64-openal`

`pacman -S mingw-w64-x86_64-libogg`

`pacman -S mingw-w64-x86_64-libvorbis`

`pacman -S mingw-w64-x86_64-curl`

Then in this instance cd'd to the FLTK folder:

`make config`

`make all`

And then tested FLUID and got that bug.

**Comment by MatthiasWM** [comment]
Ok, so I was able to install and build, and Fluid indeed crashes in `Fl_Menu_Item::test_shortcut() const`, but it is one of thise wonderful crash bugs that go away when compiling in debug mode, on a different OS, or even with small changes to the source code. 

I will try to find what's causing this, but phew, this may take a while.

**Comment by MatthiasWM** [comment]
Ok found the bug and fixed it in master 982d104adb5b5c73990c81b1cd53eb6e65f6fa1e . The problem was an oversight in static initialisation order, silly me.
