### ISSUE TITLE
fltk-1.4 wayland only build fails without dbus

### ISSUE THREAD

**Issue by juanitotc** [fltk/fltk#726]
I'm trying to build the smallest possible version of a wayland only fltk.

**FLTK Version**
 - Version: 1.4.0 weekly snapshot
 - Downloaded and self-built

**FLTK Configure / Build Options*
CC="gcc -flto -mtune=generic -Os -pipe" CXX="g++ -flto -mtune=generic -Os -pipe -fno-exceptions -fno-rtti" ./configure --prefix=/usr/local --localstatedir=/var --enable-shared --without-x --enable-wayland --disable-x11 --disable-gl --disable-pango --disable-cairo --disable-cairoext --disable-usecairo

configure: WARNING: These packages 'wayland-client>=1.18 wayland-protocols>=1.15 wayland-cursor xkbcommon dbus-1 pangocairo' are required to build FLTK for wayland.

Why is dbus required - Weston doesn't require it to run (I presume cairo/pango are absolutely necessary).

**Operating System / Platform:**
 - OS: Linux
 - OS Version: TinyCore CorePure64 14.0

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by Albrecht-S** [comment]
AFAICT you're correct that Pango and Cairo are required for Wayland because they are used internally to draw graphics and text.

I don't know why dbus is required though, but I'm pretty sure @ManoloFLTK can answer this question or even remove this requirement if possible.

**Comment by ManoloFLTK** [comment]
The requirement for dbus is inherited from the libdecor library bundled in FLTK and which has dbus as a recommended dependency "to query the current cursor theme".
I've just verified that FLTK runs also without dbus. Do do that, remove from file
libdecor/build/Makefile the string "-DHAS_DBUS `pkg-config --cflags dbus-1`"
and comment out line
        AS_IF([$PKGCONFIG --exists dbus-1],[],[missing="yes"])
in file configure.ac

Is it useful to modify FLTK to support running without dbus ?

**Comment by juanitotc** [comment]
thanks for the reply.

My aim is to get a workable wayland gui as small as possible, so having dbus as optional would be great.

**Comment by ManoloFLTK** [comment]
@juanitotc The commit mentionned above should allow you to build FLTK for Wayland without the dbus package (using configure and make). Please report here if you confirm.

**Comment by juanitotc** [comment]
I cloned fltk and built it using cmake without errors without dbus.

Most of the fltk apps I tried worked without problems, but the fluff file manager fails with:

```
fluff[2011]: segfault at 0 ip 00007f036e3a4717 sp 00007ffed3beaf90 error 4 in li
bwayland-cursor.so.0.22.0[7f036e3a4000+2000] likely on CPU 0 (core 0, socket 0)
```

Ref: http://tinycorelinux.net/12.x/x86_64/tcz/src/fluff/

**Comment by ManoloFLTK** [comment]
@juanitotc Please, post a stack dump with source line numbers (build FLTK with -DCMAKE_BUILD_TYPE=Debug) at the point of crash. TIA.

**Comment by ManoloFLTK** [comment]
@juanitotc With commit 0394a27, the crash with fluff may hopefully disappear.

**Comment by juanitotc** [comment]
That looks to have fixed things - thanks :)
