### ISSUE TITLE
fltk-1.4 wayland only - fltk applets give "xkbcommon error couldnt find a compose file for a locale mapped to c"

### ISSUE THREAD

**Issue by juanitotc** [fltk/fltk#727]
**Describe the bug**
When trying to run fltk applets on an fltk-1.4 wayland only system using weston, the applets fail to start with the error "xkbcommon error couldn't find a compose file for a locale mapped to c".

This can be cured by copying /usr/local/share/X11/locale from libX11.

I guess this is a libxkbcommon issue, but I added it here in case fltk wayland is doing something in an x11 way.

**FLTK Version**
 - Version: 1.4.0 weekly snapshot
 - Downloaded and self-built from: Snapshot

**Operating System / Platform:**
 - OS: Linux
 - OS Version: CorePure64 14.0

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
What is an fltk applet? How to reproduce the issue ?

**Comment by juanitotc** [comment]
Sorry - compiling these against fltk-1.4 and running them from weston.

https://github.com/tinycorelinux/fltk_projects

**Comment by ManoloFLTK** [comment]
The error message reported suggests it's related to the support of the compose key and character composition sequences. FLTK for Wayland does that using exclusively libxkbcommon and header files of the libxkbcommon-dev package. Therefore I believe, as you suggest too, this is an issue with the support of libxkbcommon in absence of any X11 software.

**Comment by juanitotc** [comment]
I will follow-up with libxkbcommon
