### ISSUE TITLE
Fl_Simple_Terminal::append(str, len) assumes a null terminated string in non-ansi mode

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#728]
**Is your feature request related to a problem? Please describe.**
Given the following program:
```cpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Simple_Terminal.H>

const char *MSG = "Hello World";

int main() {
    auto w = new Fl_Window(400, 300);
    auto t = new Fl_Simple_Terminal(0, 0, 400, 300);
    t->append(MSG, 5);
    w->end();
    w->show();
    return Fl::run();
}
```
in FLTK 1.4, the signature of append implies that when passed a length, the length will be adhered to.
However this will print the whole message (until null termination). Which I would say is unintuitive and might be a source of issues.

**I am using FLTK**
 - Version 1.4.0

**Describe the solution you'd like**
I would suggest that the append method adhere to the passed length in non-ansi mode. This will likely require an overloaded Fl_Text_Buffer::append(str, len) as well as an Fl_Text_Buffer::insert(pos, str, len).

**Describe alternatives you've considered**
The alternative would be to allocate new strings just to add null termination, which might be undesirable.

**Additional context**
N/A

**Comment by MatthiasWM** [comment]
Thank you. That is a bug. It works if ANSI is enabled, but was forgotten for regular text strings.

**Comment by ManoloFLTK** [comment]
That should be fixed with the commit mentionned above. @MoAlyousef Please, close issue if you agree.

**Comment by MoAlyousef** [comment]
Thanks Manolo. It works!
