### ISSUE TITLE
Huge memory leak under Wayland

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#730]
**Describe the bug**
Memory usage (both RSS and VIRT) increases dramatically during simple test under Wayland, memory is never getting freed.

**To Reproduce**
1. Run `FLTK_BACKEND=wayland bin/test/menubar` example under Wayland
2. Click on any menu in menubar and move the cursor to open different menus
3. Notice memory usage increases dramatically

This is not  happening with `FLTK_BACKEND=x11`.

**Expected behavior**
Constant memory usage

**Screenshots**

https://github.com/fltk/fltk/assets/6562863/4521dc44-ddf5-439c-8e76-9c3a6d30a641

**FLTK Version**
- Version: 1.4.0
- Downloaded and self-built from: Git
- If from Git, branch: master

**FLTK Configure / Build Options**
- `cmake ..`
- No extra build options.

**Operating System / Platform:**
- OS: Linux
- OS Version: Fedora 37

**Linux/Unix Runtime, if applicable:**
- Wayland / GNOME 43

**Additional context**

Looks like it is caused by leaking `memfd:libdecor`:

```
[polter@polter-home FLTK]$ grep libdecor /proc/44864/maps
7f8261050000-7f82619da000 rw-s 00000000 00:01 109287                     /memfd:libdecor (deleted)
7f82619da000-7f826209c000 rw-s 00000000 00:01 113421                     /memfd:libdecor (deleted)
7f826209c000-7f8262a26000 rw-s 00000000 00:01 114761                     /memfd:libdecor (deleted)
7f8262a26000-7f82633b0000 rw-s 00000000 00:01 111215                     /memfd:libdecor (deleted)
7f82633b0000-7f8263d3a000 rw-s 00000000 00:01 111211                     /memfd:libdecor (deleted)
7f8263d3a000-7f82646c4000 rw-s 00000000 00:01 109280                     /memfd:libdecor (deleted)
7f82646c4000-7f826504e000 rw-s 00000000 00:01 112353                     /memfd:libdecor (deleted)
7f826504e000-7f82659d8000 rw-s 00000000 00:01 109271                     /memfd:libdecor (deleted)
7f82659d8000-7f8266362000 rw-s 00000000 00:01 112334                     /memfd:libdecor (deleted)
7f8266362000-7f8266cec000 rw-s 00000000 00:01 111198                     /memfd:libdecor (deleted)
7f8266cec000-7f8267676000 rw-s 00000000 00:01 111196                     /memfd:libdecor (deleted)
7f8267676000-7f8268000000 rw-s 00000000 00:01 114752                     /memfd:libdecor (deleted)
7f82703d8000-7f8270d62000 rw-s 00000000 00:01 110400                     /memfd:libdecor (deleted)
7f8270d62000-7f82716ec000 rw-s 00000000 00:01 112325                     /memfd:libdecor (deleted)
7f82716ec000-7f8272076000 rw-s 00000000 00:01 112324                     /memfd:libdecor (deleted)
7f8272076000-7f8272a00000 rw-s 00000000 00:01 113400                     /memfd:libdecor (deleted)
7f82780c2000-7f8278a4c000 rw-s 00000000 00:01 113352                     /memfd:libdecor (deleted)
7f8278d27000-7f8278d69000 rw-s 00000000 00:01 113422                     /memfd:libdecor (deleted)
[polter@polter-home FLTK]$ grep libdecor /proc/44864/maps | wc -l
18
[polter@polter-home FLTK]$ grep libdecor /proc/44864/maps | wc -l
23
[polter@polter-home FLTK]$ grep libdecor /proc/44864/maps | wc -l
33
[polter@polter-home FLTK]$ grep libdecor /proc/44864/maps | wc -l
44
```

**Comment by ManoloFLTK** [comment]
Please, read very carefully [this description of how Wayland-style buffers are allocated and released](https://fltk.gitlab.io/fltk/wayland-devel.html#wayland-buffer-factory). It explains why memory use first increases when many windows are created and deleted, and how Wayland is expected to ultimately release large blocks of unused memory.

**Comment by ManoloFLTK** [comment]
@polter-rnd Good catch! A call to `munmap()` was indeed missing, causing the accumulation of mmap'ed objects you've detected.
It turns out that I had wrongly interpreted the Wayland documentation of function `wl_shm_pool_destroy()` that reads
>   The mmapped memory will be released when all
>   buffers that have been created from this pool
>   are gone.

I thought it meant the Wayland library does the `munmap()` call. Apparently, that's incorrect. The Wayland client program is expected to call `munmap()`. This requires to add a means to detect when all buffers from a pool are gone. That's hopefuly in place in the commit mentioned above.

Please, close issue if you confirm the memory leak is fixed.

**Comment by polter-rnd** [comment]
Thanks, it is fixed now
