### ISSUE TITLE
Cannot link if built with OPTION_PRINT_SUPPORT=OFF

### ISSUE THREAD

**Issue by darealshinji** [fltk/fltk#734]
**Describe the bug**
I'm getting linking errors when I had build libfltk with "cmake -DOPTION_PRINT_SUPPORT=OFF":
```
/usr/bin/ld: /home/[...]/usr/lib/libfltk.a(Fl_Printer.cxx.o):(.data.rel.ro._ZTV25Fl_PostScript_File_Device[_ZTV25Fl_PostScript_File_Device]+0x10): undefined reference to `Fl_PostScript_File_Device::end_current()'
/usr/bin/ld: /home/[...]/usr/lib/libfltk.a(Fl_Printer.cxx.o):(.data.rel.ro._ZTV25Fl_PostScript_File_Device[_ZTV25Fl_PostScript_File_Device]+0x18): undefined reference to `Fl_PostScript_File_Device::set_current()'
collect2: error: ld returned 1 exit status
```

**To Reproduce**
I need to build fluid first since it requires print support and OpenGL.
After that I can build FLTK with most features disabled.

**Expected behavior**
Make it possible to build with "-DOPTION_PRINT_SUPPORT=OFF", since that is an option in cmake.

**Screenshots**
\-

**FLTK Version**
1.4 master branch commit 7d7edcf50fc23ffac2c3abba66f981629b000150

**FLTK Configure / Build Options**
```
 CMAKE_BUILD_TYPE                 Release
 CMAKE_INSTALL_PREFIX             /home/[...]/usr
 FLTK_BUILD_EXAMPLES              OFF
 FLTK_BUILD_FLTK_OPTIONS          OFF
 FLTK_BUILD_FLUID                 OFF
 FLTK_BUILD_TEST                  OFF
FLUID_PATH                       /home/[...]/fluid
OPTION_ARCHFLAGS                 -O3
OPTION_BUILD_SHARED_LIBS         OFF
OPTION_CAIRO                     OFF
 OPTION_CAIROEXT                  OFF
 OPTION_CREATE_LINKS              OFF
 OPTION_FILESYSTEM_SUPPORT        OFF
 OPTION_LARGE_FILE                OFF
 OPTION_OPTIM                     -O3
 OPTION_PRINT_SUPPORT             OFF
 OPTION_USE_CAIRO                 OFF
 OPTION_USE_GL                    OFF
 OPTION_USE_KDIALOG               OFF
 OPTION_USE_PANGO                 OFF
 OPTION_USE_SVG                   OFF
 OPTION_USE_SYSTEM_LIBJPEG        ON
 OPTION_USE_SYSTEM_LIBPNG         ON
 OPTION_USE_SYSTEM_ZLIB           ON
 OPTION_USE_THREADS               ON
 OPTION_USE_XFT                   ON
 OPTION_USE_XRENDER               ON
```

**Operating System / Platform:**
Linux: Ubuntu 23.04

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**
\-

**Comment by Albrecht-S** [comment]
Confirmed: no matter whether I build with or without Wayland (note: Wayland-only **not** tested), the build fails when linking `fluid`, `fltk-options`, or any other test program. Example `CMake` and `configure` commands:
```
cmake -DOPTION_PRINT_SUPPORT=OFF ..
./configure --disable-print
```

Both fail with the same error message as reported by @darealshinji

@ManoloFLTK: can you please take a look? I'm not really familiar with this printing stuff and what to remove/disable (and what to keep) when print support is switched off. TIA.

**Comment by ManoloFLTK** [comment]
That should be fixed with the commit mentioned above. @darealshinji : Please, close issue if you confirm.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Great solution(s), I wouldn't have had an idea where to look. Thanks.
