### ISSUE TITLE
Using Fl_Gl_Window outputs `invalid context 0x0` errors on macOS

### ISSUE THREAD

**Issue by dcourtois** [fltk/fltk#738]
**Describe the bug**
Using a Fl_Gl_Window on macOS (Ventura 13.4.1) outputs the following error:
`CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.` when it's run through XCode, each time it's drawn.

Setting the env var doesn't give much info though: it's basically lots of "system" calls (calls from NSView, CA, etc.) ending like this:
```
  <CGBitmapContextCreateImage+132>     <-- This call in the drawRect method in Fl_Cocoa.mm
  <-[FLView drawRect:]+1012>
  <_NSViewDrawRect+124>
```

I'm using the latest dev version (69cb2744152c12dd084b438c593b53299714b4c8)

**To Reproduce**

Here is the source to repro:
```
#include <Fl/Fl_Gl_Window.H>
#include <Fl/gl.h>

struct GlWindow
    : public Fl_Gl_Window
{
    GlWindow(int w, int h)
        : Fl_Gl_Window(0, 0, w, h) {
    }

    virtual void draw(void) override {
        glClearColor(0.7f, 0.1f, 0.2f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
    }
};

int
main(int argc, char ** argv)
{
    GlWindow gl(500, 300);
    gl.end();
    gl.resizable(&gl);
    gl.show(argc, argv);
    return Fl::run();
}
```

Just running this example through XCode will log the aforementioned errors.

**FLTK Version**
commit 69cb2744152c12dd084b438c593b53299714b4c8, compiled locally with the default CMake options.

**Operating System / Platform:**
macOS Ventura (13.4.1) with a M2 Max

**Additional context**
I can "fix" this by just adding a ` if (aux_bitmap)` in the `drawRect` method, before calling CG methods, but I'm not sure if this is not just putting the dirt under the rug.
And also, in a more complex app, I have those kind of errors when I mix "normal" widgets with Fl_Gl_Window. And when resizing, the behavior is very weird with lots of flickering, and sometimes widgets not being drawn at all (all black) And I'm wondering if this is not related.
And from what I could see, this behavior seemd to begin with the introduction of this `aux_bitmap` thing.

**Comment by dcourtois** [comment]
Hi, thanks for taking the time to check. Yep I noticed the include typo :)
As for mixing 1.4 and 1.3.x, I'm 100% sure it's not the case.
Just to be sure: did you run the program via XCode? Because those errors do not show when run from a terminal (even when redericted stderr for some reasons) They only show up in the output panel of XCode (or the debug console of Visual Studio Code if you have it installed)
Also, is your laptop an Apple Silicon (M1/M2) one? And if so, did you build natively (e.g. arm64)? (just trying to check what might be the difference between your config and mine :p)

**Comment by ManoloFLTK** [comment]
Yes, I have been using arm64 code on an M1 MacBook Pro and Xcode.

**Comment by dcourtois** [comment]
Ok, thanks for your time.
