### ISSUE TITLE
Fluid "Extra Code" generation emitted too early

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#739]
**Describe the bug**
Currently code added to a widget (window, in this case) in the "Extra Code" section is put in the source file before other static attributes like `size_range()` and `resizable().` This is unexpected and can have unwanted side effects. In the demo fluid code posted below the unexpected result is that the window is not resizable on the Windows platform.

**To Reproduce**
Please use the self-contained fluid file, compile, build, and run on Windows. The example works well on Linux (X11 and Wayland), not tested on macOS. This is due to platform specific behavior on Windows where `size_range()` etc. must be set before the window is shown.

1. Run `fluid -c` to generate code
2. Build the program, e.g. with `fltk-config --compile` (using MinGW or MSYS)
3. Execute the program and try to resize the window

I didn't bother to try this with VS but the result is very likely the same.

**Expected behavior**
The program window should be resizable.

**FLTK Version**
 - Version: 1.4.0, Git master, commit 66bf6ea34

**FLTK Configure / Build Options**
Default build, no options required.

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 10 / 11

**Additional context**
The following simple fluid file shows the issue:
```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {.h}
code_name {.cxx}
snap {
  ver 1
  current_suite FLTK
  current_preset 0
}
Function {make_window()} {open
} {
  Fl_Window win {
    label {Button in Window} open selected
    xywh {33 56 300 220} type Double resizable
    code0 {win->show(); // this is in "Extra Code"} size_range {100 100 0 0} visible
  } {
    Fl_Button bt {
      label Button
      xywh {55 140 210 50} down_box DOWN_BOX color 189
    }
  }
}

Function {} {
  comment {main program} open return_type int
} {
  code {make_window();} {}
}
```
Code generated by `fluid -c` is as follows:
```
// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "CodeView.h"

Fl_Double_Window *win=(Fl_Double_Window *)0;

Fl_Button *bt=(Fl_Button *)0;

Fl_Double_Window* make_window() {
  { win = new Fl_Double_Window(300, 220, "Button in Window");
    { bt = new Fl_Button(55, 140, 210, 50, "Button");
      bt->down_box(FL_DOWN_BOX);
      bt->color((Fl_Color)189);
    } // Fl_Button* bt
    win->show(); // this is in "Extra Code"
    win->size_range(100, 100);
    win->end();
    win->resizable(win);
  } // Fl_Double_Window* win
  return win;
}

int main(int argc, char **argv) {
  make_window();
  return Fl::run();
}
```

Notes:
- if `win->show()` is moved down below `win->resizable(win);` the resulting program works as expected.
- I found a similar example in "real user code" in a more complicated context where something like an "app" class was defined and `show()` was called in the constructor.
- IMHO this is legit fluid code.
- I know that I can work around the issue by calling show() elsewhere (later in main()) but IMHO it should work as well if called in the "Extra Code" section.
- Possible solution: generate the "Extra Code" after **all** static attributes that are defined by the widget in fluid.

**Comment by Albrecht-S** [comment]
Note: I added documentation that the behavior of size_range() can be platform specific and that show() must be called after size_range() - and not vice versa - in a recent commit (66bf6ea34605227b38b141ad360b2f887fc39571) - which did not yet make it to the official online docs.

Although it would be "nice" to unify the platform specific behavior I'm not sure that this is possible. Therefore I suggest to update fluid to "do the right thing" and issue the "Extra Code" after all other widget attributes.

BTW, I checked that this issue is not a regression: branch-1.3 shows the same (IMHO wrong) code generation.

**Comment by MatthiasWM** [comment]
Yes, it makes sense to add the user code late (or last) for a widget. I will dig into this and check in which order everything is generated, and if that makes sense.

**Comment by Albrecht-S** [comment]
I also suggest to output `size_range()` after `resizable()` to ensure the resizable widget is set before `size_range()` gets calculated. Just to be sure. Something like:
```
    win->resizable(win);
    win->end();
    win->size_range(100, 100);
    win->show(); // this is in "Extra Code"
```
In my own code I call `size_range()` always directly before `show()` after everything else is set.

**Comment by MatthiasWM** [comment]
This should work now in 6fbc7ad86eadeb1b5405e322553bff4b7aeb0775

**Comment by Albrecht-S** [comment]
OK, thanks, this works now as expected. It's OK that this issue is closed.

**Comment by Albrecht-S** [comment]
@MatthiasWM This is, strictly spoken, OT here, but anyway:

There's another issue which is in the realm of "undefined behavior" or "unexpected side effect". The point is that the "extra code" is generated before the window's `end()` is output to the source file. A side effect of `Fl_Window::show(...);` is that `Fl_Group::current(0);` is called somewhere deep inside `show(...)` to "get rid of very common user bug: forgot end()". [1]

Executing the "extra code" before calling "end()" has advantages and disadvantages:
1. PRO: the user can add child widgets in the extra code section
2. CON: if the user calls `show()` then this will likely leave the flow of code in an unexpected state.

What I want to say is: we should somehow/somewhere (where?) document the fact that the extra code is generated after all other static code but before `end()` if the widget is derived from `Fl_Group` so users know that they can add child widgets in the extra code section -- if that would be useful inside fluid code at all.

The fact that `show()` calls `Fl_Group::current(0);` is documented, but I would really, really like to remove this in the future because it can have very ugly, unexpected side effects.

[1] Permanent links to current code and documentation:
https://github.com/fltk/fltk/blob/6fbc7ad86eadeb1b5405e322553bff4b7aeb0775/FL/Fl_Window.H#L417
https://github.com/fltk/fltk/blob/6fbc7ad86eadeb1b5405e322553bff4b7aeb0775/src/Fl_win32.cxx#L1943
https://github.com/fltk/fltk/blob/6fbc7ad86eadeb1b5405e322553bff4b7aeb0775/src/Fl_x.cxx#L2345

**Comment by MatthiasWM** [comment]
Yes, I was aware of that when I made the changes. I left the `end()` command as the last command so that existing code should still work the same. I assume that extra code that calls `show()` will not start adding widgets right after showing the window. Calling `end()` after `Fl_Group::current(0)` is harmless.
