### ISSUE TITLE
Question: preferred issue reporting system?

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#74]
Here or http://www.fltk.org/str.php ?

**Comment by Albrecht-S** [comment]
There's not a preferred issue reporting system, we're (still) accepting issues or STR's, resp., on both systems. This may change in the future, but then we'll likely close the STR system for new issues.

That said, if you're not absolutely sure that you found a real bug you should ask in our mailing list (aka forum) [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral) first, which is also the right place for user questions on how to **use** the software, i.e. asking for help.

If you want to discuss _development of the library itself_ there is also [fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev) which is a Google group as well.

**Comment by fire-eggs** [comment]
Thank you for the quick response!  I will check out the mailing lists.

I have real issues to report, and am more comfortable with Github. Figured I'd check tho since the docs still point to STR.

**Comment by Albrecht-S** [comment]
Yes, the docs have not been upgraded yet, and the main cause is (very likely) that we're in a very slow transition to GitHub. We're still learning and we'll decide how to proceed when we need to.

Did this answer your question? If yes please close the issue. TIA

**Comment by fire-eggs** [comment]
Yes, thanks!
