### ISSUE TITLE
FLUID: Request for checking widgets inside groups and windows

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#745]
Currently, FLUID makes it very easy to create groups or widgets whose bounding box lie outside the window.  This is particularly problematic on macOS and OpenGL subwindows as they can create refresh issues (flashing redraws when resizing for example).
Also, FLUID's undo is known to be buggy and create groups that are offset.  Cuting and Pasting is another way of creating issues.

I am using FLTK 1.4.0.

**Describe the solution you'd like**

I would like a menu entry in FLUID that checks that all widgets are inside their groups and inside their window containers.  Widgets that are not behaving properly, would get selected, so that they can be manually inspected.

**Describe alternatives you've considered**
I thought of doing a ruby or python script for this, but parsing the fluid files is way too dificult.

**Comment by MatthiasWM** [comment]
I could make a visual feedback, maybe diagonal hatched red lines where widgets overlap that should not. It would make those error visible right away during the design process. Is that a good solution?

**Comment by ggarra13** [comment]
Sounds great by me!  Thanks Matthias!

**Comment by MatthiasWM** [comment]
I think I implemented most of this in the current master. It check for widgets that are out of bound of their parent group, and for widgets in the same group that are overlapping. 2e9c1a5097c0e5bcc94528a056dcc561621d137b

**Comment by ggarra13** [comment]
I get a compiler error on Linux:

FAILED: fluid/CMakeFiles/fluid-lib.dir/Fd_Snap_Action.cxx.o 
/usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK-build -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/install/include/freetype2 -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/zlib -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/jpeg -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/png -I/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/install/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/libpng16 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -O3 -DNDEBUG -MD -MT fluid/CMakeFiles/fluid-lib.dir/Fd_Snap_Action.cxx.o -MF fluid/CMakeFiles/fluid-lib.dir/Fd_Snap_Action.cxx.o.d -o fluid/CMakeFiles/fluid-lib.dir/Fd_Snap_Action.cxx.o -c /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fd_Snap_Action.cxx
In file included from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/FL/fl_types.h:24,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/FL/fl_utf8.h:31,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/FL/Fl.H:33,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/FL/Fl_Widget.H:25,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fl_Type.h:20,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fl_Widget_Type.h:24,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fl_Window_Type.h:24,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fd_Snap_Action.h:20,
                 from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fd_Snap_Action.cxx:17:
/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/FL/fl_attr.h:129:21: error: expected ‘;’ at end of member declaration
  129 | #define FL_OVERRIDE override
      |                     ^~~~~~~~
/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fl_Group_Type.h:167:19: note: in expansion of macro ‘FL_OVERRIDE’
  167 |   int is_scroll() FL_OVERRIDE const { return 1; }
      |                   ^~~~~~~~~~~
In file included from /home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fd_Snap_Action.cxx:19:
/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fl_Group_Type.h:167:37: error: expected unqualified-id before ‘{’ token
  167 |   int is_scroll() FL_OVERRIDE const { return 1; }
      |                                     ^
/home/gga/code/develop/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK/fluid/Fl_Group_Type.h:167:7: error: ‘int Fl_Scroll_Type::is_scroll()’ marked ‘override’, but does not override
  167 |   int is_scroll() FL_OVERRIDE const { return 1; }
      |       ^~~~~~~~~

**Comment by MatthiasWM** [comment]
Yes, sorry, it's fixed. You were simply too fast ;-)

**Comment by ggarra13** [comment]
It seems like it isn't working quite right.  See the picture (and I attach the .fl file too).  It marks the Edit button but its hatches go outside the button (and afaict the button is right in its groups):

![mrViewer](https://github.com/fltk/fltk/assets/6072843/8289e31c-4cb8-4406-8b84-48097442476d)

[mrViewer.fl.txt](https://github.com/fltk/fltk/files/12021743/mrViewer.fl.txt)

**Comment by ggarra13** [comment]
Never mind me.  It is working just fine, but the hatching is drawn outside the button.

**Comment by MatthiasWM** [comment]
Hmm, no clue why "Edit" is hatched. The rest is hatched correctly AFAICT. There is a little red hatched area in PixelToolBarClass on the right, indicating that the child group is too far left (x=-2). So that part seems to work too.

The hatched area is 4 pixels larger, or you would not see single pixel overlaps, or out of bounds at window edges. Let me know if you have a better idea.

**Comment by ggarra13** [comment]
Everything is fine.  I found out why Edit is hatched and it is correct.  I thought it was wrong due to the hatching being too big, but what you did makes sense.  I am closing the issue.
