### ISSUE TITLE
Disable file chooser at build time

### ISSUE THREAD

**Issue by nohsheef** [fltk/fltk#746]
**Is your feature request related to a problem? Please describe.**
Possibility to disable file selector at build time and that way drop GTK dependency.

**I am using FLTK**
 - fltk-rs 1.4.7

**Describe the solution you'd like**
`./autogen.sh --without-file-chooser`.

**Additional context**
I did check existing cmake and autoconf options and hopefully didn't miss the obvious.

**Comment by ManoloFLTK** [comment]
FLTK does not depend on GTK. By default, under Linux, FLTK uses the shared GTK library to show file dialogs and printer chooser dialogs. If no shared GTK library is found on the running system, FLTK uses its own file and printer dialogs. All that is done entirely at run time. The app needs not be linked to GTK. If the app finds the shared GTK library at run-time, it uses it; if it doesn't the app is happy too.

Furthermore, it's possible with the FLTK option mechanism (with the `fltk-options` app) to turn **off** `OPTION_FNFC_USES_GTK`. In that case, FLTK apps will not look for the GTK shared library and will always use FLTK file and printer dialogs. It's enough to run the `fltk-options` app once to have effects on all FLTK apps without any re-build of these apps. 

An entirely different situation exists under Wayland and with CSD compositors such as Mutter: FLTK can draw window titlebars either GTK-styled or in a GTK-free way (FLTK uses Cairo in that case). This choice is done at  build time. If package libgtk-3-dev is found on the build system, libfltk is configured to draw GTK-styled titlebars and all FLTK apps link against libgtk*.so. If that package is not found, FLTK apps don't use any GTK code.

@nohsheef If that information solves your problem, please close this issue. If it doesn't, please post here your remaining questions.

**Comment by ManoloFLTK** [comment]
Furthermore, it's possible to prevent libfltk from using GTK under Wayland to draw window titlebars even if package `libgtk-3-dev` is present on the build system with :
`cmake  -DOPTION_ALLOW_GTK_PLUGIN=OFF`

**Comment by nohsheef** [comment]
Thanks. I'll see that OPTION_ALLOW_GTK_PLUGIN option is exposed in fltk-rs.

**Comment by nohsheef** [comment]
To be precise, would OPTION_ALLOW_GTK_PLUGIN disable any and all GTK linking, not just CSD with --enable-wayland?

**Comment by ManoloFLTK** [comment]
1) the 2 possible uses of GTK by FLTK, for dialogs and for drawing window title bars under Wayland are completely independent.
2) for dialogs, FLTK never links with GTK. It merely calls functions found in the shared GTK lib at run time, and that can be prevented with OPTION_FNFC_USES_GTK for file dialogs and by OPTION_PRINTER_USES_GTK for print dialogs.
3) under Wayland and for window titlebars, FLTK will link to GTK by default if package libgtk-3-dev is present in the system at FLTK configure time, and that can be prevented using cmake OPTION_ALLOW_GTK_PLUGIN. So, yes, with `cmake  -DOPTION_ALLOW_GTK_PLUGIN=OFF` FLTK apps are not linked to GTK.

I also add that there's an API to set OPTION_FNFC_USES_GTK and OPTION_PRINTER_USES_GTK  for an app independently from using the fltk-options app. That is obtained with these statements :
```
  Fl::option(Fl::OPTION_FNFC_USES_GTK, false);
  Fl::option(Fl::OPTION_PRINTER_USES_GTK, false);
```

**Comment by nohsheef** [comment]
2. via `dlopen` and thus no `-lgtk..` at build time?

**Comment by Albrecht-S** [comment]
> via dlopen and thus no -lgtk.. at build time?

Yes.
