### ISSUE TITLE
Fl_Valuator or Fl_Color_Chooser bug, out-ranged value

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#749]
## Phenomenon
I found a strange issue on trying to pick a color with Fl_Color_Chooser,

- Testing Project = https://github.com/rageworx/fltk-cpp-barcode/commit/3e62ad67e0438308fc344df918581cd16ef77df6
- Issue track = https://github.com/rageworx/fltk-custom/issues/57

Fl_Color_Chooser set right value range(), it is Ok.
But looks Fl_Valuator not handles right value range, please refer to my Issue track.

## Idea,
- Maybe `Fl_Valuator::value()` need be set to clamped value when it called in `Fl_Color_Chooser`.
- But `softclamp()` and `clamp()` is not working as designed -> input allowed out-ranged.
- Or wrong usage ?

## Some captures
![image](https://github.com/fltk/fltk/assets/6948225/7bb465da-37ba-4701-a3f2-a5d69c0c0f88)

![image](https://github.com/fltk/fltk/assets/6948225/276f8fcc-3d25-4da0-9f93-8e0e5f123e8d)
- softclamp allows out-ranged value.

**Comment by rageworx** [comment]
Plus, I think changing Fl_Valuator::value() is not a right way as written in comment.

**Comment by rageworx** [comment]
I am not sure what is wrong for now, but I can type out ranged value for any type for RGB/HSV.
Is it a bug for Fl_Valuator() ? Or , need to range check on Fl_Color_Chooser? Not sure.

**Comment by rageworx** [comment]
I am not sure what is wrong for now, but I can type out ranged value for any type for RGB/HSV.
Is it a bug for Fl_Valuator() ? Or , need to range check on Fl_Color_Chooser?

**Comment by rageworx** [comment]
Testing for clamping is working or not,
![image](https://github.com/fltk/fltk/assets/6948225/79b10772-dfcb-4f26-912a-1a706b4568cf)

clamping is not works at internal value,
![image](https://github.com/fltk/fltk/assets/6948225/20711c65-3d45-40f5-9394-d1adc27198f9)

**Comment by rageworx** [comment]
Input 500 on Red,
![image](https://github.com/fltk/fltk/assets/6948225/809d8bc4-0060-4863-b46a-76ffaa13ecc8)
clamp value is 1.96 for RED !

**Comment by rageworx** [comment]
Changing sequence, to be applied right range...
![image](https://github.com/fltk/fltk/assets/6948225/db8098fa-a541-4115-a32d-89d5cee1e11d)

Same,
![image](https://github.com/fltk/fltk/assets/6948225/a30305e4-68da-4caf-aeff-fe80bf74b802)

Fl_Value_Input need to prevent out-ranged value from typing.

**Comment by rageworx** [comment]
## Question
- `Fl_Value` set rage by 1 to 100.
- `Fl_Value.clamp()` able to return out-ranged ?
- Am I doing wrong ?

**Comment by rageworx** [comment]
## Some testing 
![image](https://github.com/fltk/fltk/assets/6948225/5be5f030-82b5-4a8b-b6f2-c36efac10f59)

1. I input 600 on RED, 
2. Fl_Valuator::clamp() got 600, But returns 255 as well.
3. But in time while type 600, there's out-ranged image occurs,
![image](https://github.com/fltk/fltk/assets/6948225/ea54e891-d79b-45e5-b8e3-bb1f0cad3bd6)
4. Maybe a event timing or sequence issue ?

**Comment by rageworx** [comment]
## It was timing issue, maybe.
![image](https://github.com/fltk/fltk/assets/6948225/b8ef5434-1a25-4465-a3ac-e5009f9c1b60)
1. Tried to type 600 on RED.
2. `rgb_cb()` call before processing clamping.

**Comment by rageworx** [comment]
## My thought
![image](https://github.com/fltk/fltk/assets/6948225/ab19455c-d7f7-4d43-bb65-2fbe1067b016)
1. Clamping on `Fl_Color_Chooser::set_valuators()` may not a good choice.
2. Doing clamping on `Fl_Color_Chooser::rgb_cb()` may better.

**Comment by rageworx** [comment]
I was committed this issue for my repo (fltk-custom/1.4.0-dev).
https://github.com/rageworx/fltk-custom/commit/01672827f07e9216970a165a4d0c2b05e38ce006

**Comment by Albrecht-S** [comment]
Thanks @rageworx for this report and the fix. I can reproduce the weird color effects.

I used your fix in commit 580a531ef511c1b80c30fa61b27e0209ff693f96 added a little more to update the input values in the case they were clamped. Otherwise you could enter for instance RGB (byte mode) values like 255678 (interpreted as 255).

Please close the issue if this commit fixes it for you.

PS: Please use our bug report template [1] and provide the requested info (system, FLTK version etc.) for future bug reports. This helps us to reproduce the issue and to fix it.
[1] Click on "New issue", then select "Bug report --> Get started". TIA.
