### ISSUE TITLE
Fl_Help_View: enable copying text selection in subclass

### ISSUE THREAD

**Issue by darealshinji** [fltk/fltk#75]
I made a subclass of `Fl_Help_View()` and added a context menu with the option to copy the currently selected text:
``` C++
class MyHelpView : public Fl_Help_View
{
private:
  Fl_Menu_Item *_menu;

public:
  MyHelpView(int X, int Y, int W, int H);
  void menu(Fl_Menu_Item *m) { _menu = m; }
  int is_selected() { return selected; }
  Fl_Help_View *has_current_view() { return current_view; }
  void copy_selection() { end_selection(1); }

protected:
  int handle(int event);
};

int MyHelpView::handle(int event)
{
  if (event == FL_PUSH && Fl::event_button() == FL_RIGHT_MOUSE) {
    _menu[0].flags = (is_selected() && has_current_view() == this) ? FL_MENU_DIVIDER : FL_MENU_INACTIVE|FL_MENU_DIVIDER;

    const Fl_Menu_Item *m = _menu->popup(Fl::event_x(), Fl::event_y());
    if (m) {
      m->do_callback(NULL);
      return 1;
    }
  }
  return Fl_Help_View::handle(event);
}

static void copy_html_selection_cb(Fl_Widget *, void *) {
  html->copy_selection();
}

static void do_nothing_cb(Fl_Widget *, void *) {
}

Fl_Menu_Item html_menu[] = {
  { " Copy selection  ", 0, copy_html_selection_cb, NULL, FL_MENU_DIVIDER },
  { " Dismiss  ", 0, do_nothing_cb },
  {0}
};

html = new MyHelpView(10, 10, 780, 580);
html->menu(html_menu);
```

But in order to do that I had to edit the `Fl_Help_View.H` header file:
``` diff
--- a/FL/Fl_Help_View.H
+++ b/FL/Fl_Help_View.H
@@ -240,12 +240,16 @@ class FL_EXPORT Fl_Help_View : public Fl_Group {	// Help viewer widget
   static int    selection_push_last;
   static int    selection_drag_first;
   static int    selection_drag_last;
+protected:
   static int    selected;
+private:
   static int    draw_mode;
   static int    mouse_x;
   static int    mouse_y;
   static int    current_pos;
+protected:
   static Fl_Help_View *current_view;
+private:
   static Fl_Color hv_selection_color;
   static Fl_Color hv_selection_text_color;
 
@@ -286,7 +290,9 @@ private:
   void          hv_draw(const char *t, int x, int y, int entity_extra_length = 0);
   char          begin_selection();
   char          extend_selection();
+protected:
   void          end_selection(int c=0);
+private:
   void          clear_global_selection();
   Fl_Help_Link  *find_link(int, int);
   void          follow_link(Fl_Help_Link*);
```

To achieve the same on `Fl_Text_Display()` I don't need to patch anything.

**Comment by erco77** [comment]
Indeed, seems like Fl_Help_View is missing public selection methods that both set and get the primary + secondary selections, as well as trigger a 'copy' operation.

The existing private methods are probably not good names for public facing api.
I'd suggest looking to other widgets for consistency with one of them.

Fl_Input uses methods `position(), mark(), and copy()`.
Fl_Text_Editor/Buffer provides `selectXXX()` methods and ` kf_copy()`.

Not sure which is best. Would be nice if there was consistency across all the text widgets for this.

**Comment by Albrecht-S** [comment]
`position()` is probably a bad choice since it would shadow `Fl_Widget::position()` -- see #69. I also don't like method names `kf_*()` because they're not FLTK-alike.

I agree that we should strive for consistency with sensible method names. I don't have a proposal right now though...

**Comment by erco77** [comment]
As much as we shouldn't use issues as a discussion forum, I find things fall apart when moved, so let's see if we can just figure this out here..  shouldn't be hard.

Suggestion "A":

    void select(int start, int end);       // sets selection. select(val,-1) sets start only
                                           // select(-1,val) sets end only (extend or shorten right edge)
                                           // select(-1,-1) clears selection (extend or shorten left edge)
    int select_start();                    // get, returns -1 if no selection
    int select_end();                      // get, returns -1 if no selection
    void selection_fg_color(Fl_Color val); // sets selection text color
    void selection_bg_color(Fl_Color val); // sets selection background color
    Fl_Color selection_fg_color(void);     // get selection text color
    Fl_Color selection_bg_color(void);     // get selection background color

If others have more, offer Suggestion B, C, etc.

**Comment by zcream** [comment]
Instead of changing Fl_Help_View, a second widget called Fl_Html_Editor() can be created. This would be an alternative to Fl_Text_Editor()

**Comment by darealshinji** [comment]
Any new ideas for this? I really hate to patch the sources...

**Comment by MatthiasWM** [comment]
"good things come to those who wait"

Sorry about the delay. I implemented the Copy pulldown mennu and added two public methods.
