### ISSUE TITLE
Give the option to disable the static library

### ISSUE THREAD

**Issue by rempas** [fltk/fltk#753]
**Is your feature request related to a problem? Please describe.**
Having to build the static library that I never use.

**I am using FLTK**
 - 1.4.0

**Describe the solution you'd like**
I would like to have on option on CMAKE to disable the static library and only build the shared one. There is that option for the shared library (as it should) for people that would only use the static one. I just don't understand why there isn't one for the static one as well.

**Describe alternatives you've considered**
I suppose that I can remove it manually from the Make file but that's not a proper way of doing it and it doesn't make sense...

**Additional context**
I do understand and respect the idea of FLTK been small enough to be statically linked but some people would still want to use the shared library anyways. So I don't see why having to build it anyways. Thank you for your time reviewing that!

**Comment by rageworx** [comment]
Dear @rempas ,
I like to ask you about why need to disable static library ?
As I know, CMAKE provides an option for SHARED_LIBRARY.
![image](https://github.com/fltk/fltk/assets/6948225/0b428236-e741-4673-9fb2-576290426502)

FLTK is builds static library as default, and shared is an option, then you can use only shared library.
Is it something different ?

**Comment by rempas** [comment]
> Dear @rempas , I like to ask you about why need to disable static library ? As I know, CMAKE provides an option for SHARED_LIBRARY. ![image](https://user-images.githubusercontent.com/6948225/254182026-0b428236-e741-4673-9fb2-576290426502.png)
> 
> FLTK is builds static library as default, and shared is an option, then you can use only shared library. Is it something different ?

I think that it would be nice if it was more configurable and flexible. Like I said, not everyone (I mean, I don't think I'm not the only one in the whole world... right?) would want to use the static library so I think that there is no point and having to build it (hence wait for it to compile) and then install it and have it in your system.

Again, nothing to big, the compile times aren't so long (unless you have an older system) and the size of the library isn't so big but again, it's just for a better feel and image for the library.

**Comment by Albrecht-S** [comment]
@rempas Thank you for the request. I can see why someone may want this, one reason is to enable only shared FLTK library builds of FLTK projects - besides the compilation time.

@rageworx OPTION_BUILD_SHARED_LIBS only **adds** the shared FLTK libs but does not disable building the static libs.

FWIW: CMake has an own variable named `BUILD_SHARED_LIBS` for users to configure **either** building shared **or** static libs, but this option is not used by the FLTK build system. FLTK currently builds always static libs and optionally shared libs.

**Comment by rageworx** [comment]
> > Dear @rempas , I like to ask you about why need to disable static library ? As I know, CMAKE provides an option for SHARED_LIBRARY. ![image](https://user-images.githubusercontent.com/6948225/254182026-0b428236-e741-4673-9fb2-576290426502.png)
> > FLTK is builds static library as default, and shared is an option, then you can use only shared library. Is it something different ?
> 
> I think that it would be nice if it was more configurable and flexible. Like I said, not everyone (I mean, I don't think I'm not the only one in the whole world... right?) would want to use the static library so I think that there is no point and having to build it (hence wait for it to compile) and then install it and have it in your system.
> 
> Again, nothing to big, the compile times aren't so long (unless you have an older system) and the size of the library isn't so big but again, it's just for a better feel and image for the library.

> OPTION_BUILD_SHARED_LIBS only adds the shared FLTK libs but does not disable building the static libs.

Dear @Albrecht-S , @rempas 
Now I understood why dynamic "ONLY" build request.
I never imagine building shared object since I used FLTK, hmmm ... I always loved FLTK to build GUI static to publish by less dependency.
Thanks for all :)

**Comment by rempas** [comment]
> > > Dear @rempas , I like to ask you about why need to disable static library ? As I know, CMAKE provides an option for SHARED_LIBRARY. ![image](https://user-images.githubusercontent.com/6948225/254182026-0b428236-e741-4673-9fb2-576290426502.png)
> > > FLTK is builds static library as default, and shared is an option, then you can use only shared library. Is it something different ?
> > 
> > 
> > I think that it would be nice if it was more configurable and flexible. Like I said, not everyone (I mean, I don't think I'm not the only one in the whole world... right?) would want to use the static library so I think that there is no point and having to build it (hence wait for it to compile) and then install it and have it in your system.
> > Again, nothing to big, the compile times aren't so long (unless you have an older system) and the size of the library isn't so big but again, it's just for a better feel and image for the library.
> 
> > OPTION_BUILD_SHARED_LIBS only adds the shared FLTK libs but does not disable building the static libs.
> 
> Dear @Albrecht-S , @rempas Now I understood why dynamic "ONLY" build request. I never imagine building shared object since I used FLTK, hmmm ... I always loved FLTK to build GUI static to publish by less dependency. Thanks for all :)

It's ok! It will make sense for most people to use the static library like I said but, there will still be people that will want to use the shared one.

**Comment by Albrecht-S** [comment]
Progress report:
- positive: I could add an option to disable building the static libs
- negative: fluid, fltk-options, and all test programs link against the static libs.

What this means: I can build the shared libs only (without above mentioned progs) but making this feature complete would require more changes.

Still working on it but please don't hold your breath...

**Comment by rempas** [comment]
> Progress report:
> 
>     * positive: I could add an option to disable building the static libs
> 
>     * negative: fluid, fltk-options, and all test programs link against the static libs.
> 
> 
> What this means: I can build the shared libs only (without above mentioned progs) but making this feature complete would require more changes.
> 
> Still working on it but please don't hold your breath...

Cool! It's mostly a "quality of life" update so it's fine if it takes more time or even if it doesn't get implemented at all. If at some point you feel like giving up, just close the issue.

I'm more impressed by the fact that FLTK seems to be one of the most active projects I know! You are just amazing! All of you!

**Comment by Albrecht-S** [comment]
You're welcome. Well, we are a very small team and progress is sometimes slowly but we try to be responsive on issues and PR's. Sometimes we're quick, sometimes it can take a while.

> If at some point you feel like giving up, just close the issue.

Yes, I would have done this if necessary but I believe it can be implemented.

Since we have options to exclude `fluid` and `fltk-options` from the build to save compilation time, we should IMHO also have the option to disable the entire static library which takes much longer to build.

That doesn't necessarily mean that it **will** be implemented but I'm confident that it can be done.

**Comment by rempas** [comment]
> You're welcome. Well, we are a very small team and progress is sometimes slow but we try to be responsive on issues and PR's. Sometimes we're quick, sometimes it can take a while.
> 
> > If at some point you feel like giving up, just close the issue.
> 
> Yes, I would have done this if necessary but I believe it can be implemented.
> 
> Since we have options to exclude `fluid` and `fltk-options` from the build to save compilation time, we should IMHO also have the option to disable the entire static library which takes much longer to build.
> 
> That doesn't necessarily mean that it **will** be implemented but I'm confident that it can be done.

I understand. People should not "demand" a feature, unless they want to contribute or at least, partly help at some point. I don't know and like C++ so, I do not demand anything.

I'm very grateful that you are willing to try and in general for all the help I had got with the issues I had.

And of course, I cannot ignore and don't mention that FLTK tops both GTK and QT! Not only it is more lightweight and fast but the API is more stable as well! You guys **ROCK!**

**Comment by nohsheef** [comment]
> And of course, I cannot ignore and don't mention that FLTK tops both GTK and QT! Not only it is more lightweight and fast but the API is more stable as well! You guys ROCK!

This is true, and I apologize for the off-topic comment.

I've been comparing various Rust gui crates and fltk exhibits the least overhead when resizing, moving, entering/exiting a window on Wayland. It behaves more efficiently than GTK4 and GTK3, which I would expect to be thoroughly optimized. The difference with Qt6 is smaller but still measurable. So whatever FLTK computes less to achieve a usable GUI, maybe partly by me using a GlutWindow to draw widgets, is working surprisingly well.

What I measured is odd and not a common test case, but I have over decades noticed that some toolkits waste resources when redrawing, and this is one of the first things I try when checking out a library. I haven't tested the Vulkan renderer of Qt6 or GTK4. Rust's Iced gui crate is as bad as GTK4 at this.

**Comment by MatthiasWM** [comment]
> People should not "demand" a feature, unless they want to contribute or at least, partly help at some point. I don't know and like C++ so, I do not demand anything.

Nah, don't worry. But we take language bindings as contributions, too ;-) .

**Comment by rempas** [comment]
> Nah, don't worry. But we take language bindings as contributions, too ;-) .

I will have to decide if I will create my language or if I'll stick with D or if I'm gonna discover another language...

After than, you're gonna get the bindings, I promise!

**Comment by rempas** [comment]
> > And of course, I cannot ignore and don't mention that FLTK tops both GTK and QT! Not only it is more lightweight and fast but the API is more stable as well! You guys ROCK!
> 
> This is true, and I apologize for the off-topic comment to praise FLTK.
> 
> I've been comparing various Rust gui crates and fltk exhibits the least overhead when resizing, moving, entering/exiting a window on Wayland. It behaves more efficiently than GTK4 and GTK3, which I would expect to be thoroughly optimized. The difference with Qt6 is smaller but still measurable. So whatever FLTK computes less to achieve a usable GUI, maybe partly by me using a GlutWindow to draw widgets, is working surprisingly well.
> 
> What I measured is odd and not a common test case, but I have over decades noticed that some toolkits waste resources when redrawing, and this is one of the first things I try when checking out a library. I haven't tested the Vulkan renderer of Qt6 or GTK4. Rust's Iced gui crate is as bad as GTK4 at this.

Now that you mention it, I do wonder why FLTK doesn't support Vulkan (or does it and I live under a rock)?

@MatthiasWM @Albrecht-S If I don't bother you, could I get more info on that decision because I was always curious since I discovered FLTK!

**Comment by MatthiasWM** [comment]
> @rempas I will have to decide if I will create my language or if I'll stick with D

This is not the forum here because the entire conversation will vanish into obscurity when Issue is marked closed. A better place would be in the Google groups: https://groups.google.com/g/fltkgeneral

Anyway, I still have a partial FLTK D port from very early days of D development.

As for Vulcan, it's not available on macOS. So at least for me, I won't put any effort into it.

**Comment by rempas** [comment]
> > @rempas I will have to decide if I will create my language or if I'll stick with D
> 
> This is not the forum here because the entire conversation will vanish into obscurity when Issue is marked closed. A better place would be in the Google groups: https://groups.google.com/g/fltkgeneral
> 
> Anyway, I still have a partial FLTK D port from very early days of D development.
> 
> As for Vulcan, it's not available on macOS. So at least for me, I won't put any effort into it.

Vulkan is not available on MacOS? Bro, I had the impression it was...

Anyways, I do understand! Have a nice day/night everyone!

**Comment by erco77** [comment]
I believe Vulkan supports Mac, but Apple doesn't itself release or support Vulkan; Apple's putting all their effort into "Metal", which is Apple's core graphics API to replace opengl.
I think Vulkan support for mac is implemented over Metal.

**Comment by rempas** [comment]
> I believe [Vulkan supports Mac](https://vulkan.lunarg.com/doc/sdk/1.3.250.1/mac/getting_started.html), but Apple doesn't itself release or support Vulkan; Apple's putting all their effort into "Metal", which is Apple's core graphics API to replace opengl. I think Vulkan support for mac is implemented over Metal.

Whatever they want I guess...

**Comment by Albrecht-S** [comment]
OK, guys, this issue has run very much off-topic. I'm ignoring all "discussion" items - please do as @MatthiasWM suggested: 
> A better place would be in the Google groups: https://groups.google.com/g/fltkgeneral

Please open a new thread with any topic that needs discussion there.

**Comment by Albrecht-S** [comment]
Coming back to the subject of this issue: I'm sorry to say that the OP's request is not doable with acceptable efforts. The (main) reason is that fluid, fltk-options, and all test and demo programs are linked to the static libs and changing this would be too much work. It would also very likely confuse users that expect particular library names (CMake target names) for the libraries. This and the docs are already complicated enough.

The OP @rempas wrote above:
> It's mostly a "quality of life" update so it's fine if it takes more time or even if it doesn't get implemented at all. If at some point you feel like giving up, just close the issue.

That point has come, I'm giving up. Not because it's not doable at all (if you want to build only the library itself) but because it would affect the entire (CMake) build system.

So yes, this RFE will not be considered further. Hence I'm closing this issue now. Sorry.

Maybe we can reconsider this decision for the next minor release after 1.4.x (1.5.0) but I'm closing the issue anyway.
