### ISSUE TITLE
A little bit of feedback 

### ISSUE THREAD

**Issue by zxpyld3x** [fltk/fltk#755]
I like the old-fashioned UI interface:

A little bit of feedback (personal preference), the cursor should be thinner and can blink

thanks

**Comment by MatthiasWM** [comment]
Thanks. You can set the schemes to make it look more modern, too.

You can change the cursor of Fl_Text_Editor/Fl_Text_Display by calling cursor_style(DIM_CURSOR) etc. https://fltk.gitlab.io/fltk/classFl__Text__Display.html#a9bfe2e5350be0232e0115a1003ceaa32a44c221fb4a13dda486e5d94279f7933c
