### ISSUE TITLE
`Fl_Screen_Driver::transient_scale_display()` need to follow `Fl_Tooltip::textcolor()`

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#756]
**Describe the bug**
I found some strange scale% display when I have testing DPI scaling up/down by pressing Ctrl+'+'/'-'.

![image](https://github.com/fltk/fltk/assets/6948225/fbd35a35-0aaf-45a7-b9cd-957648ee2033)

In case of mine, I have changed `Fl_Tooltip` colors for darker.
And found scale% displaying window text color not follow Fl_Tooltip::textcolor() in `Fl_Screen_Driver::transient_scale_display()`.

**To Reproduce**
I have set colors like this
```
    Fl_Tooltip::color( 0x15151500 ); // was fl_darker( FL_DARK3 )
    Fl_Tooltip::textcolor( 0xFF663300 );
    Fl_Tooltip::size( 12 );
    Fl_Tooltip::font( fl_message_font_ );
    Fl_Tooltip::enable( 1 );
```
And made my app here (Make Image'O HDR)
https://bitbucket.org/rageworx/make_img_o_hdr/src/master/
You can jsut download prebuilt images in download section.
And presss Ctrl+'+'/'-'/'0' ... you can see a black window as I captured.

**Expected behavior**
I think scale% window Fl_Box text label should follow Fl_Tooltip::textcolor().
So I had a commit for this on my forked fltk-custom repo.
https://github.com/rageworx/fltk-custom/commit/b7ad102bb24a677fe97a03972bd28bca8eb88710

**Screenshots**
current issue, fixed text color to FL_BLACK
![image](https://github.com/fltk/fltk/assets/6948225/fbd35a35-0aaf-45a7-b9cd-957648ee2033)

when follow textcolor(),
![image](https://github.com/fltk/fltk/assets/6948225/61925e9c-b16b-46c9-8bfd-c4f73dd5f9d5)

**FLTK Version**
1.4.0 (current)

**FLTK Configure / Build Options**
EFLAGS="--enable-localjpeg --enable-localzlib --enable-localpng"
BSYS="--build=x86_64-w64-mingw32"
./configure ${BSYS} ${EFLAGS}

**Operating System / Platform:**
 - OS: Windows10
 - OS Microsoft Windows [Version 10.0.19042.1706]
 - Processor if relevant : Intel i7-7700 

**Additional context**
Nope !

**Comment by Albrecht-S** [comment]
Thanks for the report.

I agree because the transient scale display sets its background color to `color(Fl_Tooltip::color());`. Therefore it's consistent to set the text color as `labelcolor(Fl_Tooltip::textcolor());`.

Fixed in commit 9ee8cdc727e7c510c28b51318b953d82aa1dd936.

Note: tested in one of the test and demo programs by setting
```
  Fl_Tooltip::color(FL_GREEN);
  Fl_Tooltip::textcolor(FL_RED);
```
in main before `Fl::run()`. Bad color choice, I know, but this was for testing. ;-)
