### ISSUE TITLE
Fluid reports "Unknown property" on existing fluid files

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#759]
**Describe the bug**
See below from [CI build](https://github.com/fltk/fltk/actions/runs/5598708885/jobs/10238715665). The link may not be publicly viewable but FLTK maintainers can open it. 
```
/home/runner/work/fltk/fltk/test/mandelbrot_ui.fl:49: Unknown property "slider_size"
/home/runner/work/fltk/fltk/test/mandelbrot_ui.fl:49: Unknown property "0.1"
/home/runner/work/fltk/fltk/test/mandelbrot_ui.fl:63: Unknown property "slider_size"
/home/runner/work/fltk/fltk/test/mandelbrot_ui.fl:63: Unknown property "0.1"
```

**_Important note:_** if you **update** the .fl file the property "slider_size 0.1" will be removed!

**To Reproduce**
Build FLTK with test programs in a fresh (or cleaned) build directory.

**Expected behavior**
Fluid should "compile" the existing .fl files without warnings.

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0, git master
 - commit: 1e890ea4e4ba00a66743cc97b89dfd4991167ce1

**FLTK Configure / Build Options**
All default options, building the test programs is required.

**Operating System / Platform:**
not relevant

**Additional context**
This seems to be a regression since recent (massive) FLUID changes.

IMPORTANT: since most of the existing fluid (.fl) files have been updated recently I suggest to check if this or similar issues have been undetected and removed this or similar properties from other .fl files.

Hint: `fluid -u` can be used to update (upgrade) fluid (.fl) files.

@MatthiasWM After these massive fluid changes I suggest to do something like:
```bash
for f in *.fl; do /path/to/new/fluid -u $f; done
```
in all source directories where fluid files can be found (src, fluid, test, examples).

**Comment by MatthiasWM** [comment]
The massive FLUID changes are not done yet, but are important to make the code readable and maintainable. I am trying to avoid regressions as best as I can, but sometimes something slips, so thank you very much for the error report.

**Comment by Albrecht-S** [comment]
Thanks, the commit apparently fixes the issue but there's a new compiler warning.
```
[47/593] Building CXX object fluid/CMakeFiles/fluid-lib.dir/Fl_Widget_Type.cxx.o
/git/fltk/master/fluid/Fl_Widget_Type.cxx: In member function ‘virtual void Fl_Widget_Type::read_property(Fd_Project_Reader&, const char*)’:
/git/fltk/master/fluid/Fl_Widget_Type.cxx:3415:9: warning: unused variable ‘x’ [-Wunused-variable]
 3415 |     int x = is_a(ID_Slider);
      |         ^
```
Reopening the issue for simplicity although the new warning is not directly related.

**Comment by MatthiasWM** [comment]
Saw that already, will be fixed in a few minutes.

**Comment by MatthiasWM** [comment]
Obsolete test removed in [f8a3278](https://github.com/fltk/fltk/commit/f8a327877699a8565d36b2f0b1cbe074f224fba4)
