### ISSUE TITLE
XWayland and Wayland using Mesa drivers when Wayland is used instead of NVidia drivers

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#760]
**Describe the bug**
There appears to have been a change in compatibility of XWayland and Wayland with NVidia drivers (among others).  When I log onto Ubuntu 22.04 LTS with Wayland, the reported driver used is Mesa.
With Rocky Linux 8.8 I don't even get that chance.  Once the Nvidia driver is installed, login to Wayland becomes restricted (no Wayland options on the main log in screen).
On Ubuntu, it leads to offscreen GL contexts to not work under XWayland (but they work fine in X11 with the same code) and native Wayland (might be wrong code, but I think they used to work).
Under XWayland, the error is "no visinfo" for:
```
            XVisualInfo* visInfo = glXGetVisualFromFBConfig(p.dpy, glxfbCfg[0]);            
            if (!visInfo)
            {
                LOG_ERROR("no visinfo");
                return;
            }
```
Under Wayland, the error is:
            "choose config failed
            EGL_SUCCESS"

for:
```
            if ((eglChooseConfig(
                     p.egl_display, fbAttribs, &egl_config, 1, &numConfigs) !=
                 EGL_TRUE) ||
                (numConfigs != 1))
            {
                LOG_ERROR("choose config failed");
                LOG_ERROR(eglGetErrorString(eglGetError()));
                return;
            }
```

**To Reproduce**
No simple example, unfortunately.  I am attaching the gl offscreen context class, just in case it becomes obvious what's wrong.  For a full application, go to: www.github.com/ggarra13/mrv2 and compile or download a binary.

**Expected behavior**

Under XWayland, the behavior of offscreen GL contexts should work identically to X11 without any code change.
Under Wayland itself, the code in my provided class *should* work, from what I gather online, but I might be wrong.

I could have sworn that this used to work in previous versions of FLTK/Wayland with my NVidia card.  With XWayland, the only problem that used to happen was that the MultilineInput text widget would lag behind.  Now that is fixed, but the offscreen gl context is not.

**FLTK Version**
1.4.0 - master

**FLTK Configure / Build Options**

include( ExternalProject )

set( FLTK_TAG c2cce9cba86dcc208c9396af994010cd49484988 )
#set( FLTK_TAG master )

set( build_type ${CMAKE_BUILD_TYPE} )
set( patch_cmd )

if (APPLE OR WIN32)
    set( wayland OFF )
    set( pango   OFF )
else()
    set( wayland  ON )
    set( pango    ON )
endif()

ExternalProject_Add(
    FLTK
    GIT_REPOSITORY "https://github.com/fltk/fltk.git"
    GIT_TAG ${FLTK_TAG}
    PATCH_COMMAND ${patch_cmd}
    CMAKE_ARGS
    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHIECTURES}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
    -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${build_type}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
    -DFLTK_BUILD_EXAMPLES=OFF
    -DFLTK_BUILD_TEST=OFF
    -DOPTION_BUILD_SHARED_LIBS=0
    -DOPTION_USE_SYSTEM_ZLIB=0
    -DOPTION_USE_SYSTEM_LIBJPEG=0
    -DOPTION_USE_SYSTEM_LIBPNG=0
    -DOPTION_USE_PANGO=${pango}
    -DOPTION_USE_WAYLAND=${wayland}
    )

**Operating System / Platform:**
Linux:  Ubuntu 22.04.2 LTS and Rocky Linux 8.8 

**Linux/Unix Runtime, if applicable:**
- XWayland (does not work)
- Wayland (does not work)
- X11  (works)

**Additional context**
Attaching the offscreen gl context class here.
[offscreen_glcontext.zip](https://github.com/fltk/fltk/files/12189284/offscreen_glcontext.zip)

**Comment by ManoloFLTK** [comment]
> Once the Nvidia driver is installed, login to Wayland becomes restricted (no Wayland options on the main log in screen).

That doesn't look like a bug in FLTK.

**Comment by ManoloFLTK** [comment]
I don't have access to hardware using the NVidia drivers, so won't be able to help.

**Comment by ggarra13** [comment]
> > Once the Nvidia driver is installed, login to Wayland becomes restricted (no Wayland options on the main log in screen).
> 
> That doesn't look like a bug in FLTK.

Sorry, yes.  It seems like it is a feature in Rocky Linux 8.  I rebooted again today and the Wayland options were back there, but they just don't allow you to log-in.

**Comment by ggarra13** [comment]
Ok.  I fixed the class for Wayland with help of https://github.com/svenpilz/egl_offscreen_opengl.  It seems pbuffers don't work reliably on Wayland, but you can achieve the same by using EGL_NO_SURFACE.

Still, the issue with my X11 code working on native X11 and not working under XWayland remains.

**Comment by Albrecht-S** [comment]
@ggarra13 You wrote previously:
> ... Under XWayland, the error is "no visinfo" for:
> `XVisualInfo* visInfo = glXGetVisualFromFBConfig(p.dpy, glxfbCfg[0]);`
> ... and ...
> the issue with my X11 code working on native X11 and not working under XWayland remains

This seems to be pure X11 code from your own class which has nothing to do with FLTK itself. I'm sorry that we can't help. 

I suggest that you try to make a small test case to ask this question somewhere else, for instance in an XWayland support channel.

@ggarra13 Can we close the issue? Please close the issue if you agree.

**Comment by ggarra13** [comment]
I fixed it both for Wayland and XWayland.  Thanks.  I am closing the issue.

**Comment by Albrecht-S** [comment]
@ggarra13 Thanks for closing the issue. I added platform X11/Wayland just for reference and "no user support" because it turned out not to be an FLTK issue. This is just for our internal info.
