### ISSUE TITLE
FLTK 1.38 resizebox.cxx Compile Error under VS2019 Error with "Winnt.h"

### ISSUE THREAD

**Issue by ausir2016** [fltk/fltk#763]
//     http://www.fltk.org/str.php
// resizebox.cxx

//This will cause error. and should be moved after #include <....>
//#define W1 (big ? 60 : 40)
//#define B 0
//#define W3 (5*W1+6*B)

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Radio_Button.H>
#include <FL/fl_draw.H>
#include <FL/fl_message.H>

// New location.
#define W1 (big ? 60 : 40)
#define B 0
#define W3 (5*W1+6*B)

**Comment by MatthiasWM** [comment]
Yes, this is fixed in newer versions of FLTK.

**Comment by MatthiasWM** [comment]
Ok, I checked and the bug is fixed in the latest 1.3.8 release on GitHub as well as in the master/1.4.0. There is nothing more I can do.
