### ISSUE TITLE
Fluid compiler warnings (Windows, Visual Studio)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#765]
**Describe the bug**
Compilation warnings in Visual Studio:
```
Compiling...
  shell_command.cxx
...\fluid\shell_command.cxx(313,30): warning C4129: 'e': unrecognized character escape sequence [...\fltk\build\fluid\fluid-lib.vcxproj]
...\fluid\shell_command.cxx(317,32): warning C4129: 'e': unrecognized character escape sequence [...\fltk\build\fluid\fluid-lib.vcxproj]
```

It looks like we need double backslashes in these two lines. I assume the output should contain `'\e'` (`Escape` character) and therefore we need `'\\e'` in multiple places in
https://github.com/fltk/fltk/blob/76fb2d5b79cb69782998bf6cf71c2c61fb712d69/fluid/shell_command.cxx#L313
and https://github.com/fltk/fltk/blob/76fb2d5b79cb69782998bf6cf71c2c61fb712d69/fluid/shell_command.cxx#L317

**To Reproduce**
Build current Git master (76fb2d5b79cb69782998bf6cf71c2c61fb712d69) in Visual Studio.

**Expected behavior**
No warnings.

**FLTK Version**
 - Downloaded and self-built from: Git
 - branch: master
 - commit 76fb2d5b79cb69782998bf6cf71c2c61fb712d69.

**FLTK Configure / Build Options**
Default CMake build for Visual Studio 2019.

**Operating System / Platform:**
 - OS: Windows 10
 - Visual Studio 2019

**Comment by MatthiasWM** [comment]
\e is some GNU extension. \033 is the correct ESC character code.
