### ISSUE TITLE
Fl_Tabs should respond to FL_MOUSEWHEEL events when in overflow-drag mode

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#766]
- [X] Use event_dx() to drag overflowing tabs left and right [5e48452](https://github.com/fltk/fltk/commit/5e484524c8713697182cf50e303ecc4305f60bd4)
 - [ ] Menu windows should react to scrolling up and down.
 - [ ] Also, check all the Fl_Value_ widgets that may benefit from this event.

**Comment by Albrecht-S** [comment]
Sorry, this is off-topic, but a thought: while you're at modifying menu windows and scrolling, it would be really cool if large menus would fit in a smaller window (not larger than the screen height, originating window height, or some other related value like two thirds of screen/window height) and we could scroll the contents of the window (i.e. the menu items) inside the menu window.

Then there should be a visible "overflow" indication like a small arrow (triangle) so the user knows that there are more menu items than currently visible.

This would help with large menus under Wayland and would lead to a much better user interface of menus.

**Comment by ManoloFLTK** [comment]
> This would help with large menus under Wayland …

To clarify: large menus are currently supported and functional under Wayland. But, putting them in a scrolling smaller window would considerably simplify the Wayland code, provided the new functionality is platform-independent.

Please, let's not further delay the release of FLTK 1.4 by adding new requirements.

**Comment by MatthiasWM** [comment]
Ok, I promise to rewrite the popup menu code( #768). I did dig into it so many times, only to find out that I have to relearn what the heck is going on every time. Let me finish the multitouch stuff first, and then I should get to it.

**Comment by MatthiasWM** [comment]
Tabs feature implemented, popup menu stuff in new Issue, valuator stuff not high in priority at all. closing.
