### ISSUE TITLE
Concept: FLTK as a backend for proton-/react-native like system

### ISSUE THREAD

**Issue by IngwiePhoenix** [fltk/fltk#77]
Rapid application development - or at least the idea of creating a prototype - has become very important over the last few years. Especially when considering to build an application across platforms, options like Electron with React Native or Proton Native and friends have been used to build those. The problem: They all require _so much_ memory. Even without names, it's easy to just peek into Windows Task Manager or macOS Activity Monitor and immediately spot which applications are Electron based. Kind of insane, if you ask me.

I have been out of developing anything UI related for ages now and surely enough, things have changed. A lot, too. So I wanted to see how long it took to make an Electron app and read up a few tutorials and looked at basic examples and boilerplates - to see what the structure would be like and how things would work out. While reading those, I became curious about one thing in particular: Since most of the code defines components based on existing objects (i.e. HTML elements) and what would happen, if that base was simply changed from a WebView perspective to a native perspective?

Proton Native does that by using Qt or wxWidgets, which is very interesting. But both those libraries are quite big while FLTK is not (my last memories of FLTK are from 1.3.x mostly). So I looked at what would be needed to make this work; using FLTK as a backend for this kind of approach, using something like JerryScript (or any other basic but good library) as the JS engine and NodeJS as a toolset to handle the transpiling of JSX/TSX to plain JS.

Thus, I have a few questions: 

* The first, most obvious thing, is FLTK's event loop. What is it based on? Is it different per platform? And can it be used to handle something like a reimplementation of `EventEmitter` if need be?
* How far can a component (window, button, textbox, checkbox, radio, progress bar) be styled?
* From what I last remember, there was not a lot of flow-options for components. Each one needed to be given coordinates. Do newer versions of FLTK implement a way to automatically flow components within a container?
* I remember that each instance of `FL_Window` has a `end()` method. Is my memory right, that any statement following `start()` up untill `end()` is meant for those to happen "in the context" of that window? As in adding components like buttons? If so, the HTML-ish idea of something like `<FLWindow> <FLButton>text</FLButton> </FLWindow>` would be easy to implement - easier than I had expected, actually.
* Wasn't there a FLTK UI designer - FLUID? To what format does it actually output?

My C/C++ toolchain is kind of broken right now (i messed it up by accident...) and because of how Windows decided to prioritize my virtual network devices over my actual, real device, I probably have to re-install and start over. To be fair, I was a macOS user for the better part of my life and have to get used to a few of the more lower-y levels of how Windows does things...

This probably isn't a great place to post these questions, let alone the basic idea of what I would like to do in the long run, however seeing as this repo is now the main place for the FLTK code, I figured it might just work. :) Sorry if there was a more suitable place!

Kind regards,
Ingwie

**Comment by Albrecht-S** [comment]
Hi Ingwie, your assumption that this is not the right/best place to ask such questions (about the _development of the FLTK library_). Please post your question to our [fltk.coredev forum/mailing list](https://groups.google.com/forum/#!forum/fltkcoredev). Thanks.

Note: I added the 'invalid' and 'wontfix' labels since this is OT here.

**Comment by Albrecht-S** [comment]
Addition: just in case I misunderstood the gist of this issue: if it is aimed at the basic question "how to **use** FLTK to do this ..." then the best place to ask such a question would likely be our user forum [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral).
