### ISSUE TITLE
Special (UTF-8) characters in PDF docs maybe not rendered correctly

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#772]
**Describe the bug**
I found at least one issue where a special character (UTF-8 : '⌘') is not rendered in our PDF docs which leads to incomplete docs:

"Under macOS, the corresponding GUI scaling shortcuts are **_/+/-/0/_**."
Should read: "⌘/+/-/0/".
Text copied from PDF docs, section "1.8.2 What Drawing Units Do FLTK Drawing Functions Use?" from the paragraph beginning with "At application start time ...".

**To Reproduce**
Build PDF docs, use PDF viewer to view fltk.pdf.

**Expected behavior**
Documentation should be correct with all intended characters rendered correctly.

**Screenshots**
![image](https://github.com/fltk/fltk/assets/26235500/7feec112-1cf1-4ddd-8cee-e4cb3a71aaa0)

See the last line for the missing '⌘' character.

**FLTK Version**
 - Version: 1.4.0
 - Git, branch: master
 - Commit: be657471e761462d91c62e8cd00519e5dbda82a0

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Debian 12 / Bookworm

**Additional context**

I'm not sure if other special (non-ASCII or non-Latin1) characters in the docs (expressed in UTF-8 encoding in our sources) are rendered properly. This should be investigated but I can't do this right now.

My intention is to document the issue so it is not forgotten.

**Comment by MatthiasWM** [comment]
What happens if you use `&#8984;` in the Doxygen code, or `\char"2318` or `\unichar{#2318)` after `\latexonly`? Docs also mention `\usepackage[T1]{fontenc} \usepackage[utf8]{inputenc}`. Just for giggles, the German word for the character is Schleifenquadrat.

**Comment by MatthiasWM** [comment]
Oh, and Doxyfile.in has an entry `EXTRA_PACKAGES` in the Latex/Pdf section.

**Comment by ManoloFLTK** [comment]
I propose to replace the single occurrence of ⌘ by "cmd" because that's the way it's called quite a few times elsewhere in the pdf document.

More generally, it does seem that our Doxygen-to-PDF procedure has a hard time with non ASCII characters. A place with several such characters is a table in the [detailed description of class Fl_PostScript_File_Device](https://fltk.gitlab.io/fltk/classFl__PostScript__File__Device.html#details) where benign characters such as ≤ and ≥ don't appear in PDF. Others (‰, €) appear correctly.

**Comment by Albrecht-S** [comment]
> What happens if you use `&#8984;` in the Doxygen code, or \char"2318 or \unichar{#2318) after \latexonly?

Doesn't work. I also tried `unichar{#2318}` instead of `unichar{#2318)` (closing bracket/brace typo?) but none worked.

> Docs also mention `\usepackage[T1]{fontenc} \usepackage[utf8]{inputenc}`.

Which docs? LaTeX docs or ... ? I don't feel comfortable with such approaches because I have no knowledge about these tools.

> I propose to replace the single occurrence of ⌘ by "cmd" because that's the way it's called quite a few times elsewhere ...

Sure, that will fix this single issue. I can do this.

> More generally, it does seem that our Doxygen-to-PDF procedure has a hard time with non ASCII characters ...

From some earlier experience with PDF generation ISTR that PDF (or was it PS?) has a limited character set and that Latin1 (or ISO-8859-1) is included. I tested the entire Latin1 character table and this worked well.

I conclude that we are safe if we limit our "special characters" to the Latin1 / ISO-8859-1 character set and a few more like '€' and other chars that are **_known to work_**.

To all devs: please test the PDF generation when introducing new "special" characters literally in the docs. Using special (e.g. html entity or numerical Unicode) "encodings" would not help if the target character can't be represented in the generated PDF docs.

> A place with several such characters is a table in the [detailed description of class Fl_PostScript_File_Device](https://fltk.gitlab.io/fltk/classFl__PostScript__File__Device.html#details) where ...

Hmm, I wonder why some of these characters appear in the PDF file correctly and others don't. If the text is correct, then all characters of that table should be rendered correctly in PostScript - but maybe not in PDF?

There are two intermediate "actors" (Doxygen and LaTeX) and the final PDF creation. I don't know where to look further.

- I tried to find a clue in the documentation of Doxygen but couldn't find anything except the mention of "character encoding UTF-8" in several places (input and output encoding etc.). However, there's no mention of the supported **_character set_**.
- I have absolutely no idea about the capabilities of LaTeX to encode any chars outside the Latin1 range to PS or PDF.

Is here anybody who knows more about LaTeX to PDF conversion and can shed some light on this general problem?

Maybe it would be helpful to ask the Doxygen guys. I'll try to do this and report back here...

**Comment by MatthiasWM** [comment]
> Doesn't work. I also tried `unichar{#2318}` instead of `unichar{#2318)` (closing bracket/brace typo?)

Fully intentional of course. Who in their right mind would start *and * end with curlies? 😄 

Anyway, LaTex seems to be the issue here. It's originally 7 bit and can deal with 8 bit characters, but not with inline utf8. Doxygen has a list of supported characters for HTML, and maybe those work for LaTex as well (https://www.doxygen.nl/manual/htmlcmds.html#htmlentities). I haven't tried it though, and besides what doxygen provides, we can not expect a specific LaTex interpreter or pdflatex app, I guess.

Using `Cmd` in that specific case is great. Do we really *need* any special characters in the docs? Worst case, we can reference a picture of a character if it *must* be LaTex/PDF compatible.

**Comment by Albrecht-S** [comment]
I created a minimal test case: [cloverleaf.zip](https://github.com/fltk/fltk/files/12479129/cloverleaf.zip).

1. Extract the zip file in an empty folder
2. Change dir to that folder
3. Run `doxygen`
4. Change dir to subdir `latex`
5. Run `make` (outputs log and error message)
6. Enter 'H' + \<Return\>

You should see something similar to the error messages in file `error.txt` (included in the zip file).

Excerpt from error messages:
```
! LaTeX Error: Unicode character ⌘ (U+2318)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
... Using special char 'cloverleaf': ⌘}}
... You may provide a definition with
\DeclareUnicodeCharacter
```

That's it. I'm lost at that point.

If anybody knows how to "provide a definition with \DeclareUnicodeCharacter" please feel free to help.

Note: this is only a test to see what happens, not because I insist on using the `cloverleaf` character in particular. The same would likely happen with all other unknown characters (in fact I saw similar errors when I tested with the PostScript table mentioned above by @ManoloFLTK) .

**Comment by Albrecht-S** [comment]
> Do we really need any special characters in the docs? Worst case, we can reference a picture of a character if it must be LaTex/PDF compatible.

I believe showing a picture would be a good choice for the special character table mentioned by Manolo. We can render the table using the HTML output (using `\htmlonly`), take a screenshot, and put the latter under `\latexonly` guards.

I hope we don't need images for single characters though.

**Comment by MatthiasWM** [comment]
> ... You may provide a definition with
> \DeclareUnicodeCharacter

You write something like `\DeclareUnicodeCharacter{2318}{\cloverleaf}` and from then on, writing `\cloverleaf` should output the character, but only with certain versions of LaTex and depending on some ominous packages.

**Comment by ManoloFLTK** [comment]
> I wonder if it would be possible to fix this and similar issues by using doxygen's \htmlonly and \latexonly statements using different sources

I volunteer to do that for the table at class `Fl_PostScript_File_Device`.

**Comment by Albrecht-S** [comment]
> I volunteer to do that for the table at class Fl_PostScript_File_Device.

Yes, please, go ahead. Just a quick question: do you intend to use an image (screenshot) for the '\latexonly` part or is there a better way?

While you're at it, could you please also commit the replacement of the '⌘' character with 'Cmd' as discussed above?

**Comment by ManoloFLTK** [comment]
Done, using an image, under the opinion that handling properly Unicode under latex is difficult.

**Comment by Albrecht-S** [comment]
> Done, using an image, under the opinion that handling properly Unicode under latex is difficult.

Thanks, and yes, I wouldn't like to open another can of worms and maybe introduce more dependencies that make PDF generation harder for us (devs) and end users. Let's keep it simple (KISS).

I believe we can close this issue although there may be other issues, unless someone knows of more such issues. Searching more than 1000 pages of PDF docs would be tedious, but I ask all devs to keep an eye on special (non-ASCII, non-Latin1) characters in the docs. TIA.
