### ISSUE TITLE
Feature requested to disabling scale up/down temporary.

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#773]
**I am using FLTK**
 - Version 1.4.0 ( and also 1.4.0.10-custom on my repo )

**Describe the solution you'd like**
Ctrl/Cmd + "+/-/0" key scaling up or down anytime.
But sometimes, I need to disable this feature for temporary as like timered animation loop, like resizing Fl_Widget.

**Describe alternatives you've considered**
While timer event to adjusting Fl_Widget width and height, or position, FLTK rescaling by user key hitting goes widget sizing strange.
So I think it will be better FLTK can give option to disable/enable scaling by key hitting.

**Additional context**
I think FLTK can make `bool Fl_Screen_Driver::scale_active;` to check in Fl_Screen_Driver.cxx:457~458 by `if ( !scale_active ) return;`.

**Comment by ManoloFLTK** [comment]
Put this function definition somewhere in your code
```
int my_scale_handler(int event)
{
  if ( event != FL_SHORTCUT || (!Fl::event_command()) ) return 0;
  int key = Fl::event_key() & ~(FL_SHIFT+FL_COMMAND);
  if (key == '=' || key == '-' || key == '+' || key == '0' || key == 0xE0/* for '0' on Fr keyboard */) {
    return 1;
  }
  return 0;
}
```
and then, turn scaling OFF with
`  Fl::add_handler(my_scale_handler);`
and turn it back ON with
`  Fl::remove_handler(my_scale_handler);`

**Comment by rageworx** [comment]
Dear @ManoloFLTK ,

I have tested with your add/remove handler when animation timer enabled/disabled.
But seems to strange widget sizing issue is not an answer for this way.

Thank you for your help !

And one more question, 
When timer event, my app is resizing Fl_Box.
While sizing Fl_Box, scaling called by hitting Ctrl/Cmd +/-/0, widget size goes minimal size or maximum size before timer event.
Do you have any idea to handle sizing Fl_Box while timer and prevent to scale mechanism ?
Disabling handling while sizing with timer seems not an answer to me, and it feels strange issue.

Regards, Raph.

**Comment by ManoloFLTK** [comment]
@rageworx I would believe a small example code showing your issue is necessary to understand the issue and, hopefully, its cause.

**Comment by rageworx** [comment]
> @rageworx I would believe a small example code showing your issue is necessary to understand the issue and, hopefully, its cause.

Okay, I will.
But currently project has a commercial issue, so I need remove some images and words to explain strange working.
I will be back with some video and codes.

**Comment by ManoloFLTK** [comment]
This discussion describes how to disable and then enable on demand the processing of Ctrl/+/-/0/ keys for rescaling the GUI.

I'm therefore marking this issue as fixed and closing it.

The OP may have another problem/question in mind. If that's confirmed, the OP should create another issue for it.

**Comment by rageworx** [comment]
I was busy for a while, Sorry for late.
I will be back with captured video, or image for explaining this issue.
Thank you !
