### ISSUE TITLE
Fluid regression(s)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#777]
**Describe the bug**
Current fluid has a severe regression: under certain circumstances it writes an absolute path of a header file to the `.cxx` file where it previously correctly wrote a relative path. This is obviously a problem if the generated `.cxx` file is to be distributed (stored in the git repository). FLTK has such files in the 'src' directory (for instance `src/Fl_Help_Dialog.fl`) but users would have the same problem. The problem manifests if there is a (relative) path to the header file, e.g.
```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {../FL/Fl_Help_Dialog.H}      ###  relative path here ###
code_name {.cxx}
...
```

**To Reproduce**
Use current fluid to "write files" of file `src/Fl_Help_Dialog.fl` and compare the output to the previous file contents. For instance, after building the latest fluid (assuming: configure/make):
```diff
$ cd /path/to/fltk/src
$ ../fluid/fluid -c Fl_Help_Dialog.fl
$ git diff -U0 -- Fl_Help_Dialog.cxx
diff --git a/src/Fl_Help_Dialog.cxx b/src/Fl_Help_Dialog.cxx
index 3cdba7097..ca8a43724 100644
--- a/src/Fl_Help_Dialog.cxx
+++ b/src/Fl_Help_Dialog.cxx
@@ -26 +26 @@
-#include "../FL/Fl_Help_Dialog.H"
+#include "/data/git/fltk/master/FL/Fl_Help_Dialog.H"
```

The last two lines show the diff with the absolute path on **my** system!

See the following tiny example file. It should be used in the FLTK `src` folder with current fluid.
[regression.fl](https://github.com/fltk/fltk/files/12675643/regression.fl.txt)

**Expected behavior**
The old behavior exporting the **_relative path as given in the `.fl` file_** would be correct.

**FLTK Version**
- Git master
 - commit fd2741e031c45d645d99f5579cb2eccf22e0e606

**FLTK Configure / Build Options**
Build with default options, either with configure/make or CMake. Instructions above are for configure builds in the FLTK source tree.

**Operating System / Platform:**
Debian 12 (Bookworm), but the platform shouldn't matter.

**Comment by Albrecht-S** [comment]
**Note:** I assigned @MatthiasWM (hope you don't mind) and set labels `bug` and `Prio 4 - High` because (re)generating the source and header files in the `src` directory would create wrong source files - but the bug would not be noticed on the current build system because the (absolute) path would be "correct" **_on the author's system_**.

**Comment by Albrecht-S** [comment]
Another minor related issue: the first part is not a regression but it confused me when I tried to locate the issue. It is also not obvious to the "normal" user what really happens:

First I had a hard time to find out why that particular header file (`FL/Fl_Help_Dialog.H`) is written to that directory. I saw it in the `.fl` file (line 3, see above), but when I used Fluid I couldn't find where it was set. The problem is that it is **NOT** properly set up in the GUI after reading the .fl file: menu `Edit / Settings / Project` doesn't show the path under "Header File:" - there's the default '.h' value. If I'm not completely wrong the according variable should be set when reading the .fl file.

No matter if you enter the path in this field (or not) it works and writes the file to the given (but hidden) relative path. The "old" fluid **correctly reports** in a popup "Wrote Fl_Help_Dialog.cxx and ../FL/Fl_Help_Dialog.H", however:

This is another regression: the "new" fluid does NOT report the relative path, it just says "Wrote Fl_Help_Dialog.cxx and Fl_Help_Dialog.H" which is **not correct** because it seems to have written to the current directory.

**Comment by Albrecht-S** [comment]
And while we're at it: here's another issue, probably caused by recent commits (sorry, I don't have the time to bisect).
```diff
$ git diff .
diff --git a/fluid/sourceview_panel.cxx b/fluid/sourceview_panel.cxx
index 2cd008f85..e064a7dfe 100644
--- a/fluid/sourceview_panel.cxx
+++ b/fluid/sourceview_panel.cxx
@@ -116,6 +116,8 @@ void update_sourceview_cb(class Fl_Button*, void*) {
       sv_strings->buffer()->loadfile(fn);
       sv_strings->scroll(top, 0);
     } else if (sv_source->visible_r() || sv_header->visible_r()) {
+      // *FIXME* g_project.basename = fl_filename_name(sv_source_filename);
+      // *FIXME* g_project.basename = fl_filename_setext(g_project.basename, "");
       Fl_String code_file_name_bak = g_project.code_file_name;
       g_project.code_file_name = sv_source_filename;
       Fl_String header_file_name_bak = g_project.header_file_name;
diff --git a/fluid/sourceview_panel.fl b/fluid/sourceview_panel.fl
index 37c38d2fb..744dec05c 100644
--- a/fluid/sourceview_panel.fl
+++ b/fluid/sourceview_panel.fl
@@ -136,8 +136,8 @@ and load those into the Code Viewer widgets.} open return_type void
     sv_strings->buffer()->loadfile(fn);
     sv_strings->scroll(top, 0);
   } else if (sv_source->visible_r() || sv_header->visible_r()) {
-    g_project.basename = fl_filename_name(sv_source_filename);
-    g_project.basename = fl_filename_setext(g_project.basename, "");
+    // *FIXME* g_project.basename = fl_filename_name(sv_source_filename);
+    // *FIXME* g_project.basename = fl_filename_setext(g_project.basename, "");
     Fl_String code_file_name_bak = g_project.code_file_name;
     g_project.code_file_name = sv_source_filename;
     Fl_String header_file_name_bak = g_project.header_file_name;
```

The patch above ~fixes~ works around another issue. Running `./fluid -c sourceview_panel.fl` creates a file that can't be compiled. I commented out two lines of the .fl file (and added `*FIXME*`). These lines were not in the committed .cxx file, maybe manually edited or whatever. I didn't want to remove them silently from the .fl file because I don't know why they were left there. Please feel free to **remove** these two lines entirely or do whatever is needed so we can recreate the sources from the .fl file again. TIA.

**Comment by Albrecht-S** [comment]
> On a side note, Fluid uses different paths when run from the command line vs. when in interactive mode.

I didn't notice a difference in the behavior of this particular case. The output file is always written to the "correct" directory, no matter if I used interactive or batch mode - always using the directory of the `.fl` file as the current working directory. I can't tell if there would be a difference if I opened the .fl file "from" another working directory, e.g.
```
$ cd /path/to/fltk-1.4
$ fluid/fluid [ -c ] src/Fl_Help_Dialog.fl
```
Would be interesting to see what this would do in both interactive or batch mode. But I'm leaving this to you...

**Comment by MatthiasWM** [comment]
> First I had a hard time to find out why that particular header file (`FL/Fl_Help_Dialog.H`) is written to that directory. I saw it in the `.fl` file (line 3, see above), but when I used Fluid I couldn't find where it was set. The problem is that it is **NOT** properly set up in the GUI after reading the .fl file: menu `Edit / Settings / Project` doesn't show the path under "Header File:" - there's the default '.h' value. If I'm not completely wrong the according variable should be set when reading the .fl file.

I can't replicate that. I tried launching FLUID from the IDE and from the command line, with Fl_File_Chooser.fl as an argument, or by loading it later, or through the "previous" function, but in all cases, the `Header File:` text field is set correctly to `../FL/Fl_File_Chooser.H`. Do you have a way to repeat the issue?

**Comment by MatthiasWM** [comment]
If I counted right, this commit [0a2f05a](https://github.com/fltk/fltk/commit/0a2f05a2fe2898ee1407319a6764018fdf54e562) should fix all issues mentioned. Tested on all .fl files in test, src, and fluid.

**Comment by MatthiasWM** [comment]
> > On a side note, Fluid uses different paths when run from the command line vs. when in interactive mode.
> 
> I didn't notice a difference in the behavior of this particular case. The output file is always written to the "correct" directory, no matter if I used interactive or batch mode - always using the directory of the `.fl` file as the current working directory. I can't tell if there would be a difference if I opened the .fl file "from" another working directory, e.g.
> 
> ```
> $ cd /path/to/fltk-1.4
> $ fluid/fluid [ -c ] src/Fl_Help_Dialog.fl
> ```
> 
> Would be interesting to see what this would do in both interactive or batch mode. But I'm leaving this to you...

Yes, `fluid -c test/inactive.fl` writes `./inactive.cxx` and not `test/inactive.cxx`. In interactive mode, it always writes relative to the directory with the `.fl` file.

**Comment by MatthiasWM** [comment]
I leave this open for now because it seems to fix the issue at hand, but I want to test some additional cases.

**Comment by erco77** [comment]
I've just been casually watching this thread, esp. regarding absolute vs. relative paths.

One thing I've certainly noticed, in general file browsers can sometimes convert relative paths into absolute, particularly the native file choosers.  They'll do things like unwind symbolic links, rewrite volume names, and a host of other weird and annoying things.

So this is a long way of saying watch out for which file browsers you use and have enabled (assuming there's an option), as some might be causing this.

Also, I think we have some code somewhere that converts e.g. absolute paths to relative that might be "problematic". I've run into that code before, and found it was a deep cave in unix in particular. There was a long thread or issue or STR/bug where I went into some detail about how to go about, I think, fixing some function we had that did this to try to improve it. Not sure if I actually applied that fix or if it's still open or some such. I do remember diving into the C library itself to pull out code that was in newer OS's but absent in older ones. If I find that bug/issue/whatever, I'll include it here as it might be relevant.

**Comment by erco77** [comment]
Ah, here it is: https://www.fltk.org/str.php?L3441
That's also mentioned in this issue: https://github.com/fltk/fltk/issues/141

Again, not sure if it's related or not, other than by the relative vs. absolute path aspect of things.

**Comment by MatthiasWM** [comment]
@erco77 thanks for looking that up. fl_filename_relative and ..._absolute are quite minimal. I believe that they are still good enough to solve what I try to achieve here. The file chooser path has not been a problem as of yet, but it's great to know that there could be, and I should verify that FLUID does the right thing.

Admittedly, I threw myself into refactoring hell, and I am not happy with my code, especially if major regressions like this appear.

**Comment by Albrecht-S** [comment]
@MatthiasWM Regarding not properly initialized GUI (field "Header File") after fluid initialization, you wrote:
> I can't replicate that. I tried launching FLUID from the IDE and from the command line, with Fl_File_Chooser.fl as an argument, ... Do you have a way to repeat the issue?

Yes, please see this screenshot. I marked the relevant pieces with red ellipses:

![fluid](https://github.com/fltk/fltk/assets/26235500/a613e4d7-c92c-465e-8259-53e1769b2449)

Current branch is 'master', latest commit as of today. To reproduce:
- build FLTK (in my case with configure/make but this doesn't matter)
- execute `../fluid/fluid Fl_Help_Dialog.fl` in fltk/src (i.e. the new fluid executable)
- open the preferences / project dialog
- type ctrl/shift/c to write the output file(s).

The last point verifies that the output of the written files is now correctly reflecting the directory of the written header file, but the dialog still shows only `.h` as the header file destination - although it must have been loaded correctly (only not shown in the GUI). This is benign but it confuses the user (me).

Note that I tested to edit the field and verified that my edits were used when writing the output files, hence this is the relevant field. I'm not sure what would happen if I edited it to contain just ".h" (as it is preset). Would it still remember the correct setting with the relative path?

PS: I ran out of time for further tests, will continue later...

**Comment by MatthiasWM** [comment]
Thanks, it's fixed. The difference actually *is* building with `autoconf` instead of `cmake`. Cmake generates `fluid.app` on macOS which takes a different path when loading the initial project than just `fluid` as generated by autoconf

**Comment by Albrecht-S** [comment]
OK, I tested my example case (`src/Fl_Help_Dialog.fl`) and I confirm that the reported bug is fixed. Thanks.

I also ran `fluid -c <file>` on all relevant fluid source files in the FLTK distro (i.e. in `src` and `fluid` folders) and the result was the same as in the git repo - which is what it should be.
