### ISSUE TITLE
Fl_File_Icon::load_system_icons() doesn't seem to work on KDE desktops

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#780]
**Describe the bug**
Fl_File_Icon::load_system_icons() doesn't seem to work on KDE desktops.

**To Reproduce**
```cpp
#include <FL/Fl.H>
#include <FL/Fl_File_Icon.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_Double_Window.H>

int main() {
    Fl_File_Icon::load_system_icons();
    auto win = new Fl_Double_Window(400, 300);
    auto fbr = new Fl_File_Browser(0, 0, 400, 300);
    fbr->load("../red");
    win->end();
    win->show();
    return Fl::run();
}
```

1- build the program
2- Start the executable

**Expected behavior**
- Icons should be showing next to the browser items

**Screenshots**
![image](https://github.com/fltk-rs/fl2rust/assets/37966791/98ca9c1a-06f0-4b3f-832e-4d020d411278)

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4
 - Downloaded and self-built from: Git
 - If from Git, branch: master

**FLTK Configure / Build Options**
 - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF 

**Operating System / Platform:**
 - OS: Ubuntu 20.04.6 LTS
 - Shell: KDE Plasma
 - Processor: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**
Running the same program on Linux running in WSL works correctly. On WSL I use an Xsrv 3rd party installed X server.

**Comment by ManoloFLTK** [comment]
It works here with KDE Plasma version 5.27.8
<img width="205" alt="image" src="https://github.com/fltk/fltk/assets/41016272/c39dddb4-b126-45b4-8728-b125f33ddbf3">

**Comment by ManoloFLTK** [comment]
@MoAlyousef Could you, please, try to define env variable KDEDIR to some non-existant directory and run again your test program.
