### ISSUE TITLE
Long standing bug in fl_filename_relative()

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#781]
Moving [STR 3441](https://www.fltk.org/str.php?L3441) ("fl_filename_relative returns a wrong path)" to GitHub Issue.
Simple test case:
```C++
#include <stdio.h>
#include <FL/filename.H>
int main(int argc, char **argv) {
  char from[] = "/test/path/folder/file";
  char base[] = "/test/path_suffix/folder";
  char to[256] = "";
  fl_filename_relative(to, 256, from, base);
  printf("%s\n", to);
  return 0;
}
```

Save this program as `test1.cxx`, compile and run it, e.g. using `fltk-config`:
```
$ ./fltk-config --compile test1.cxx && ./test1
[... output from fltk-config elided]
../../folder/file
```

The correct output would be `../../path/folder/file`. I copied the demo code from STR 3441 (thanks to `nakane`).

This long standing bug can be seen in Git branch-1.3 (7fb3ca2c3ae83bb7b42f64f4ef5f92ba3558fe63) as well as in master (bb7c68a4777fa9d30165ba201dc8dcf3ce92a5f3).

There has been a lot of work put into a solution by different people (@wcout, @erco77, maybe @MatthiasWM and others) and I would really appreciate if **someone** (not me) could get this to a successful solution. Any volunteers?

Note: STR 3441 is from Dec 12, 2017. I strongly believe that this STR could and **should** be fixed at least in FLTK 1.4 (if possible also in 1.3.9, but not necessarily).

Any volunteers? Thanks in advance.

Links:
- File 1: Patch by Chris (@wcout), probably outdated: https://www.fltk.org/strfiles/3441/STR-3441.diff
- File 2: Test suite by Chris: https://www.fltk.org/strfiles/3441/fl_filename_relative_testsuite.cxx
- File 3: Implementation and test program by Greg (@erco77), maybe incomplete: https://www.fltk.org/strfiles/3441/fl_filename_relative--v1.cxx

**Comment by MatthiasWM** [comment]
PR is in #787

**Comment by MatthiasWM** [comment]
Applied PR
