### ISSUE TITLE
new fluid usability suggestions

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#784]
Neat looking things in the new fluid!

But some things that affect usability in the new main menu "Shell > Customize" dialog:

1. The new Shell -> Customize dialog window needs to be **resizable**.
    Esp. to allow the Shell Script window to be made larger so one can see long commands.
    For instance I might use:
```
        /usr/local/src/fltk-1.4.x.git/build/fltk-config --compile foo-ui.cxx 2>&1 || exit
       ./foo-ui
```
2. All buttons + fields should have **tooltips** indicating what they are.
    For instance in the "Shell command list", I'm not really sure I know what "+" vs "++" is,
    or what the "down-arrow" is for, or what the difference is between "Name:" and "Label:"

3. The '-' key is too easy to hit and loose work. Should be protected by a **warning dialog**.
    I've hit it once already and lost all my shell commands and couldn't get them back.
    
4. The "Shell script:" input field has two buttons to the right that **appear to be grayed out**.
    I was surprised they did anything when I clicked them just to see what they did.
    Perhaps the icons can be darker? (black)
    
5. "Name" and "Label" seem redundant with the same contents.. can there just be one?
    Shell commands setup should probably be simple with as few fields as possible.

**Comment by MatthiasWM** [comment]
Thanks for your suggestions.

> 1. The new Shell -> Customize dialog window needs to be **resizable**.

Yes, Albrecht also suggested that, and I will implement this next. There is a "zoom" button to the right of the text field that gives you access to a much bigger text editor, but (see below).

>  2. All buttons + fields should have **tooltips** indicating what they are.

Yes, I have not done that yet. Thanks for the reminder.

> 3. The '-' key is too easy to hit and loose work. Should be protected by a **warning dialog**.

Yeah, you are right. I will add a confirmation dialog. The first version could only delete a single entry, so having a popup dialog at every delete would have been annoying but with the ability to select multiple scripts comes a higher risk of destroying work.

> 4. The "Shell script:" input field has two buttons to the right that **appear to be grayed out**.

Yeah, I see how that is confusing. I was trying to get a "hollow" rectangle as a label. Don;t know why the down arrow is grey. I will check that.

> 5. "Name" and "Label" seem redundant with the same contents.. can there just be one?

My thought was that the name can be a bit more descriptive while the label is used in the pulldown menu. So you can create, for example, two scripts labeled "Build...", one for MSWindows, named "Win: Build", and one for Linux/MacOS named "UX: Build" in the list of scripts. Not sure if this is really useful or if I am overthinking things.

**Comment by MatthiasWM** [comment]
The current master branch now contains tooltips. The icon colors are a tiny bit better. The down arrow is being fixed in another Github Issue. The warning dialog was added.

**Comment by MatthiasWM** [comment]
e2c2ba777362f9d231e8b7281c764132038b8d61 ahs a better icon to indicate that a text field can be zoomed

**Comment by MatthiasWM** [comment]
Only issue left: make Settings Dialog resizable

**Comment by MatthiasWM** [comment]
d93b991e5c8c5322839def653c042f27aff3d500 makes the settings panel resizable
