### ISSUE TITLE
inconsistent color source for fl_draw_arrow

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#786]
**Describe the bug**
Arrows use different ways to calculate their color.

**To Reproduce**
Fl_Choice, Fl_Counter, Fl_Input_Choice, Fl_Scrollbar uses labelcolor(), 
Fl_Spinner uses labelcolor() but does not deactivate,
Fl_Menu_Button uses FL_DARK3
Fl_Tabs use fl_contrast(FL_BLACK, color())
and Fl_Adjuster uses selection_color()

**Expected behavior**
All widgets should use lablecolor() to draw their arrows. I want to fix Spinner, Menu_Button and Tabs. Not sure about Adjuster. Maybe the selection color should default to FL_FOREGROUND_COLOR? Probably will just leave that one alone.

**FLTK Version**
 - Version: 1.4.0 master

**Comment by Albrecht-S** [comment]
I appreciate this. I put a lot of work on making the arrows consistent by introducing `fl_draw_arrow()` so we don't need to calculate widths and offsets in all widgets and write code for drawing an "arrow" (just calculate the bounding box). I noticed at that time that all the widgets used their own approach to use arrow colors but I didn't want to touch this at that time. I'm glad I got the arrow drawing code centralized. [OT: In the future this should be part of the FLTK scheme.]

One big issue I saw in this context was that the GTK+ scheme uses its own colors, supposedly to be compatible with the GTK look and feel. However, this is a big issue concerning contrast if the user chose a particular background color that conflicts with the GTK colors (low contrast).

My general "philosophy" on widget drawing is that the FLTK scheme should neither change the layout (important) nor change essential colors. Therefore I wouldn't mind if you would also remove some of these `Fl::is_scheme("gtk+")` exceptions. OTOH it might be necessary to use fl_contrast() in more places than now. But that's maybe another story...

That said, take care, this is like opening another can of worms, but it would be great to make this more consistent. Thanks in advance.
