### ISSUE TITLE
Fltk doesn't respect XDG Base Directory standard

### ISSUE THREAD

**Issue by rhysday** [fltk/fltk#79]
I would like to move .fltk out of my $HOME directory and into $XDG_CONFIG_HOME

**Comment by Albrecht-S** [comment]
Thanks for this suggestion, this is a legitimate and sensible request.

I'm thinking of the FLTK _preference files_ which are usually stored in `~/.fltk` on Linux systems. Is there anything else you're concerned about? Maybe other platforms than Unix/Linux?

**Comment by Albrecht-S** [comment]
FTR: XDG_CONFIG_HOME and other related directories are specified in "[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)" (freedesktop.org).

**Comment by luxintra** [comment]
Just concerned about Linux, thanks.

**Comment by Albrecht-S** [comment]
See more info and discussion on [STR 3370](https://www.fltk.org/str.php?L3370).

**Comment by MatthiasWM** [comment]
Fixed
