### ISSUE TITLE
FLTK cmake issue: HAVE_GL_GLU_H incorrectly set to 0 in generated config.h on Linux Mint 21 ( Vanessa)

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#793]
Basics:

I have an Intel desktop with Linux Mint 21. I have used apt to install packages for GL and GLU etc. including what I believe are the "dev" packages. There is a glu.h in /usr/include/GL along with the other OpenGL header files like gl.h, glut.h, etc.

My cmake version is 3.22.1.

Problem:

When I do FLTK cmake configure/generate (actually I use cmake-gui), it does not seem to detect the GLU installation (although it indicates it finds the libglu library). Namely, in the generated config.h file, HAVE_GL_GLU_H is defined to 0, even though HAVE_GL_H is defined to 1.

This causes GLU-dependent tests like `fractals` not to work. It compiles OK during the FLTK build, but emits an error message about "This demo does not work without GL and GLU" when executed.

Workaround:

If I add the entry 'HAVE_GL_GLU_H' (type bool, selected) to my FLTK cmake config, then the generated config.h file indeed has HAVE_GL_GLU_H defined to 1. Rebuilding everything then seems to make things like `fractals` work fine.

I do not know if I have not installed the needed package(s) for FLTK's cmake to detect GLU, but I know they (installed packages) are sufficient for other applications I use to build (i.e., via my own make files) and work OK.

Naturally, I would be happy to supply more details about my platform if you need them.

**Comment by MatthiasWM** [comment]
Which version of FLTK are you using?

**Comment by Albrecht-S** [comment]
@pdhahn Please use our bug report template for future bug report or issues (New issue - Bug report --> Get started) and fill in all relevant informations. This will help us to help you.

As @MatthiasWM asked we need the FLTK version, and please be precise (Git branch and revision, snapshot version, or exact release version).

You wrote:
> I have used apt to install packages for GL and GLU etc. including what I believe are the "dev" packages.

That's not very helpful. Can you tell us which exact packages you installed? Note that `apt list --installed | grep gl` can help you to find out, but please don't post the entire list, tell us only which GL related packages you installed.

Then - assuming you are using FLTK 1.4 - please edit or patch file CMake/resources.cmake:
```diff
diff --git a/CMake/resources.cmake b/CMake/resources.cmake
index aa17f73b3..0d57ed66e 100644
--- a/CMake/resources.cmake
+++ b/CMake/resources.cmake
@@ -31,7 +31,7 @@ include (CheckIncludeFiles)
 macro (fl_find_header VAR HEADER)
   check_include_files ("${HEADER}" ${VAR})
-  if (NOT CMAKE_REQUIRED_QUIET)
+  ## if (NOT CMAKE_REQUIRED_QUIET)
     fl_debug_var (${VAR})
-  endif (NOT CMAKE_REQUIRED_QUIET)
+  ## endif (NOT CMAKE_REQUIRED_QUIET)
 endmacro (fl_find_header)
 
```
The two lines with '##' are commented out so you get all find_header results logged.

Now please run cmake (or cmake-gui) on a fresh install or delete the cache (CMakeCache.txt) in your build directory. If you're using cmake-gui you can use the menu `File/Delete Cache` to do this. Then execute `Configure`, copy the entire output and post it here. If you changed any of the CMake variables or used the command line, then please post also the entire command line or whatever variables you changed.

Note that CMake caches the search results and searches only if the cache variable is "not found" or similar. Therefore it is essential to clean the cache or start with a fresh download.

**Comment by pdhahn** [comment]
I was using FLTK 1.4 `b1321bb97` when I reported the problem.

I just did a git pull and now have `01038e832`.

Well, hmmm... now, after the pull and deleting the cmake cache as specified by @Albrecht-S, and cleaning out my build area, then doing configure / generate and full rebuild all over again, it appears the problem has been solved somehow. Good enough for me. Thank you.

**Comment by Albrecht-S** [comment]
Thanks for the feedback. I didn't see an issue after some test, which was why I recommended to clean the cache. Maybe something was stuck in the cache.
