### ISSUE TITLE
Log messages when running FLUID in Xcode.

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#795]
**Describe the bug**
I have two log messages when running FLUID from within Xcode. They appeared with the last update to macOS 14.0 Sonoma and Xcode 15.0.

The first message is 5 repeats of `Metal failed to load render pipeline: pipeline=..., Failed to find reflection in binary archives`. The solution that worked for me was adding Metal to the linker options in CMake/setup.cmake:104
```
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework Cocoa -framework Metal")
    set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -framework Cocoa -framework Metal")
```
This seems weird because we are not using Metal explicitly, but it seems that calling Cocoa now also implies that we call Metal. It's noteworthy that test/hello does not show this message, so maybe it is related to a specific feature? Maybe image drawing?

Does anyone have a little more insight here?

The second log message is `No error handler for XPC error: Connection invalid` and seems to be harmless according to [StackOverflow](https://stackoverflow.com/questions/75763933/how-to-solve-no-error-handler-for-xpc-error-connection-invalid-when-i-want-te).

**To Reproduce**
launch FLUID master from within Xcode.

**FLTK Version**
Git master

**FLTK Configure / Build Options**
 - cmake -G Xcode -B build

**Operating System / Platform:**
macOS Sonoma 14.0
Xcode 15.0

**Comment by ManoloFLTK** [comment]
These are the messages I get when running fluid within Xcode15 on Sonoma here:
> Unable to open mach-O at path: default.metallib  Error:2
> No error handler for XPC error: Connection invalid
> Program ended with exit code: 0

They appear when I open a .fl file within fluid.

**Comment by MatthiasWM** [comment]
@ManoloFLTK that sounds like a somewhat similar message, maybe with an older binary format? Does fluid still open the .fl file correctly for you? Have you tried adding metal.framework as I described above? When I do that and rebuild from scratch (run CMake -B again), my Metal warning goes away.

**Comment by ManoloFLTK** [comment]
I was just pointing out that I don't see the same messages as you get. All of that seems benign to me. Yes, fluid opens the .fl file and runs correctly.

**Comment by MatthiasWM** [comment]
Ah, ok. Understood.
