### ISSUE TITLE
Minimum size for tiles in an Fl_Tile (STR 2791)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#797]
**Description**
This is a follow-up to [STR 2791](https://www.fltk.org/str.php?L2791) from Robert Strickland who wrote:
[Note: incomplete citation, for more see [STR 2791](https://www.fltk.org/str.php?L2791):]
> Create an additional parameter to the Fl_Tile constructor and modify functionality to establish a minimum size for tiles. Default could be twice the width of a DOWN_FRAME border (plus perhaps a pixel or two).
>
> The behavior I would like is for each box in the tile to have some minimum size. Currently, when I drag the border to one side or the other, one or more tiles completely disappears. If the user is unfamiliar with the layout, there is absolutely no visible cue that there is a hidden tile lurking against one edge or corner of the drawn border. The poor user has to randomly try to drag borders until the hidden tile appears.

**This applies to FLTK**
 - Version 1.4.0

**Describe the solution you'd like**
Robert Strickland (RWS) provided code for a new widget that partially resolves the issue. This new widget was only created See more below.

**Possible Alternatives**
- incorporate this feature in `Fl_Tile` (my preferred solution)
- subclass `Fl_Tile`, for instance as `Fl_TileM` (name to be decided) - see code below
- we might also consider setting per-widget sizes (not yet done).

**Additional context**
RWS also cited @MatthiasWM (supposedly from a discussion on fltk.general):
> Fl_Tile has no function to set a minimum tile size. However, I strongly believe that there should be one for exactly the reason you state. Using DOWN_FRAMEs for the tiles give a nice visible and draggable border, so defaulting the minimal tile size to twice the width of the border would keep the visual cue and would make it possible to reconstruct all tiles.

I agree with the fact that a minimal tile size would be useful. IMHO that size should also be user-settable.

I worked on RWS's proposal and I'll post a stripped-down version of his code below. To make this work I already committed changes to `Fl_Tile` to make subclassing possible (commit 6ba7b49baf11e526d1ed19aef491db2cd120e55e).

**Comment by MatthiasWM** [comment]
Thanks for posting this. I have put some thought into this issue already, so I will likely assign it to me when I find the time.

**Comment by ggarra13** [comment]
Fl_Tile *has* a way to set a minimum size.  If you add a hidden group as the first element of the tile, this sets the minimum size.

**Comment by MatthiasWM** [comment]
@ggarra13 yes, thank you for the reminder. I think that this is more for a minimum width and height that children themselves can have. In a tile with more than two widgets vertically (or horizontally) that would give some kind of stacking effect. Not sure yet if that makes sense.

**Comment by Albrecht-S** [comment]
@ggarra13 This is about a minimum size of each tile such that no tile can be squeezed to zero width or zero height. Basically, at least the border of a tile should always be visible. If you look at the test/tile demo you can see that some of the tiles can be squeezed to zero width or height which should be prevented. Please see the original post and [STR 2791](https://www.fltk.org/str.php?L2791) for further details.

**Comment by ggarra13** [comment]
@Albrecht-S Yes, I __think__ I undertstand the issue.  But that's just what an invisible group (with resizable set to on), solves.  For each tile, your first element should be a group with the minimum size that you want on each edge and with resizable set to on so that if you scale the Fl_Tile, the limiting borders also scale.  The test/tile demo is, IMHO, incomplete.

Here's a sample file from my mrv2 viewer.  The "uiLimitingTileGroup" limits how the tile can be resized, in my case the uiView goes to about 20 pixels on height on the border at the top, while the uiTimelineGroup goes to about 30 pixels on the border at the bottom, leaving room for the timeline in my case.  Neither edge shrinks to 0.

[mrViewer.fl.txt](https://github.com/fltk/fltk/files/13273564/mrViewer.fl.txt)

The good thing about using a group instead of an actual number is that it handles resizes automatically.

**Comment by Albrecht-S** [comment]
@ggarra13 Thank you very much for your comments and for your fluid file. Unfortunately I couldn't use it directly - I had to change your private classes to `Fl_Group`'s to see what it does and how it works. The result can be seen in a single file [mrViewer1.cxx](https://github.com/fltk/fltk/files/13282602/mrViewer1.cxx.txt) that can be built using e.g. `fltk-config`.

I'm trying to understand what you mean...

Your example `Fl_Tile` has exactly three children:
- `uiLimitingTileGroup`: an invisible box (or group)
- `uiView`: the main "view"
- `uiTimelineGroup`: the group containing the timeline and a placeholder.

I colorized the different groups for better visibility because there's no other visible content. Since your `Fl_Tile` has only two _real children_ besides the invisible `resizable()` there is no way to squeeze any of these children to zero size. This is the "normal" behavior as it is designed and works well. However, this is not what this issue is about.

You wrote:
>  The test/tile demo is, IMHO, incomplete.

I tried to work around the issue in `test/tile.cxx` by making some of the children `Fl_Group`'s and adding resizable boxes etc.. I couldn't find a way to do what this issue suggests: prevent "squeezing" any of the children of the `Fl_Tile` to zero width or height. I'd be glad if this worked (as you seem to suggest) but I couldn't find it.

In `test/tile.cxx` there are two tiles that can be shrunk to zero width or height:
- 2b: to zero width
- 3a: to zero height

All the other tiles are protected by the hidden box. In fact, all tiles that touch one edge can't be resized to zero width **_OR_** height but tiles that have two neighbors in one direction **_can_** be shrunk to zero size.

Maybe I didn't understand what you mean. I'd appreciate if you could "make `test/tile.cxx` complete" by showing us code such that at least one of these boxes can not be shrunk to zero width/height (as an example). I don't think that this can be done with current FLTK 1.3 or 1.4 (git) but maybe I'm missing something?

Thanks in advance.

Note that `test/tile.cxx` in 1.3 and 1.4 are functionally equivalent, both have the resizable box in `Fl_Tile`.

**Comment by ggarra13** [comment]
Here you go. 

[tile.cxx.txt](https://github.com/fltk/fltk/files/13283430/tile.cxx.txt)

**Comment by Albrecht-S** [comment]
@ggarra13 I tested your new example and I'm sorry to say that it doesn't work as intended. There are two important points that don't help with this issue:
1. Your example nests `Fl_Tile` widgets inside the main `Fl_Tile`. Although this may work in some cases this is not what we want to achieve here. It should really be as simple as setting a minimum width and height of the tiles of **one** `Fl_Tile` widget. Nesting `Fl_Tile`s does not behave in the same way as having one `Fl_Tile` with `n` tiles.
2. You can still shrink some tiles to zero size. I came to an irrecoverable state where tiles 2a and 3a are "lost" forever. See also the broken bottom line below tiles 0 and 1.

![image](https://github.com/fltk/fltk/assets/26235500/910bce76-427a-4385-b8f8-646a3d6f9054)

Note that the screenshot is from a slightly modified version of your program but I believe that your original code works similar. I just tested it again and can see that I can shrink tiles 2a and 2b to zero size.

But anyway, thanks for trying it.

**Comment by ggarra13** [comment]
@Albrecht-S Yes, you are correct.  I did some more testing of my simple example and it behaves incorrectly.  The problem seems to be the main Fl_Tile that has many children.  I apologize for making you waste your precious time.  Also, I apologize for giving you the incomplete mrViewer.fl file.

**Comment by Albrecht-S** [comment]
@ggarra13 No problem, I always try to learn from such examples. Complete (compileable) examples would be helpful though. ;-)
In this case I learned that nesting `Fl_Tile`'s can lead to unexpected results. Maybe using `Fl_Group`'s as children of the main `Fl_Tile` and then putting another `Fl_Tile` into that child group (not necessarily in full group size) would be suitable for some problems.

**Comment by MatthiasWM** [comment]
Initial commit in 81e26b9089f83a608768fdb39aa63f33ce169521 . `test/tile` has a minimum child size set to 30x30 pixels. Minimum size can also be set per child. 

This is not the final version yet. The math behind this is not robust yet. resize() does not work perfectly yet. 0 size children can lead to endless loops. Maximum size API is available, but values are currently ignored. Documentation is not complete yet.

**Comment by Albrecht-S** [comment]
Great that you are working on this. Please see my comment to commit 81e26b9089f83a608768fdb39aa63f33ce169521.

Note that I was just curious and looked at the commit. I didn't review the calculation at all (too much stuff).

**Comment by MatthiasWM** [comment]
> I didn't review the calculation at all (too much stuff).

Yeah, it took me a while. Basically, I tell the children that are touching the moved intersection to resize. If they hit their limit, they ask their neighbors to resize, all the way to the edge of the Tile. The recursion returns the maximum movement possible. It then calls the recursion again, but now with the verified valid new position and a pointer that indicates that the child must actually resize (so down the recursion again, and up again). We do that again in all three other directions, either growing or shrinking neighbors.

It would be good if devs could test this beyond my own test cases. The no-space children-must-touch rule is essential here too.

**Comment by ggarra13** [comment]
I am re-opening this.  @MatthiasWM Have you tried this new widget with mrViewer1.cxx listed above?  I haven't yet, but when I tried it on my own application that is more complex I got two issues (at least on Linux): the tile would not move and the cursor would not change shape to indicate the tile behavior.

**Comment by Albrecht-S** [comment]
@MatthiasWM OK, I tested again and I believe it's OK as long as the **window's** `size_range()` is large enough that the `Fl_Tile` widget can't get smaller than the width and height sums of its children (as you wrote).

Please feel free to close again unless @ggarra13 chimes in with real issues and descriptions how to reproduce.

**Comment by ggarra13** [comment]
@MatthiasWM @Albrecht-S Feel free to close the issue.

**Comment by Albrecht-S** [comment]
@MatthiasWM Is there anything more we (or you) can or need to do to close this issue? If yes it should be done before 1.4.0 gets released.

**Comment by MatthiasWM** [comment]
The tile resize should now be fixed. I am closing this after trying a bunch of test cases worked great.
