### ISSUE TITLE
Crashes and warnings when Fl_Double_Window is smaller than 1x1 (STR 2797)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#798]
**Bug description**
We experience crashes on Wayland or notice X11 related warnings when the window size of an `Fl_Double_Window` gets smaller than 1x1 pixels. This has been reported in [STR 2797](https://www.fltk.org/str.php?L2797) related to `Fl_Tile` when a subwindow is reduced to zero size in any dimension but it is a general issue.

**To Reproduce**
Please apply patch [double_window_bug.diff](https://github.com/fltk/fltk/files/12918103/double_window_bug.diff.txt) in the FLTK root folder. This patches test/hello.cxx (I was too lazy) as a simple test case and test/tile.cxx.
1. test/hello.cxx creates a resizable window with a tiny (3x3 px) yellow subwindow in the center of the main window. Resize the window (make it smaller) to see the effect when the subwindow becomes too small.
2. The patch also removes the `resizable()` box widget from `test/tile.cxx` so the subwindow can be reduced to zero height at least. The same effect applies.
3. `src/Fl_Double_Window.cxx` was patched to issue diagnostics when the window size becomes smaller than 1x1.
4. In `src/Fl_Double_Window.cxx` you can also change macro `TRY_FIX_SIZE` to 1 to work around too small windows. This is definitely not meant as a solution.

Run one of the above mentioned programs after the patch, resize either the entire window or the top right area of the Fl_Tile demo to zero size.

**Expected behavior**
1. Do not crash the application with weird error messages (Wayland) or issue warnings on the console (X11)
2. It would IMHO be acceptable to issue a qualified error message and terminate the program if necessary.
3. As can be seen in the modified `test/hello.cxx` program, the behavior of the program after the workaround (`TRY_FIX_SIZE`) can be undefined, i.e. in this example we can see even negative window sizes after applying the workaround. A qualified error message and termination of the app might be better.
4. If possible, another more graceful fix would be to fix the underlying double window issues and keep working but this would need verification that it doesn't have bad consequences elsewhere.
5. See also the long discussion on STR 2797 for more info about possible solutions.

**Screenshots**
I'll post some log messages in a follow-up comment.

**FLTK Version**
Almost current FLTK 1.4 (git) as of today (commit 6ba7b49baf11e526d1ed19aef491db2cd120e55e).

**FLTK Configure / Build Options**
Default build with CMake or configure/make.

**Operating System / Platform:**
 - OS: Linux Debian 12/Bookworm

**Linux/Unix Runtime, if applicable:**
 - Wayland
 - X11

**Additional context**
- Not tested on Windows nor macOS (yet).
- The example program is contrived but such things can happen in user code and have also happened in our test/tile demo before the resizable widget was added (probably still visible in 1.3.x).
- Although creating or resizing windows with zero or negative sizes is a user error, FLTK should behave gently and not crash in internal functions.
- The STR 2797 mentions explicitly that these X11 warning (on 1.3.x) happen only when XDBE is disabled. This is now always the case in 1.4.x
- it seems that allocating the back buffer for Fl_Double_Window's causes the issue but a good fix is not obvious.

I assume this is something for @ManoloFLTK who knows the details best.

**Comment by ManoloFLTK** [comment]
The commit mentionned above removes the Wayland error and the X11 warning. Tests with macOS and Windows 11 show no more code change is needed.
The fix silently enforces a minimum size of 1x1 for subwindows under Wayland and X11 (even for Double subwindows only under X11).
