### ISSUE TITLE
launching a binary from the command line hangs on macOS Sonoma

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#799]
**Describe the bug**
Since macOS Sonoma, launching a binary from the command line hangs before the first window can open, but only if that binary is located inside a bundle.

**To Reproduce**
Build `test/hello` withcamke/Xcode under Sonoma. Launching `hello` from Xcode should work just fine. Now open a shell and launch `[cmake build path]/bin/test/Debug/hello` (which in turn just launches `[cmake build path]/bin/test/Debug/hello.app/Contents/MacOS/hello`), and the window will not open until clicking the icon in the task bar.

**Expected behavior**
Apps should launch from both the shell and the Finder.

**FLTK Version**
1.4.0 master

**FLTK Configure / Build Options**
cmake -G Xcode -DCMAKE_BUILD_TYPE=Debug -B build/Xcode

**Operating System / Platform:**
macOS Sonoma 14.0, Xcode 15.0, M1

**Additional context**
@ManoloFLTK 
The app hangs in `Fl_Cocoa_Screen_Driver::open_display_platform()` while calling `[NSApp run];`. I assume it took a wrong turn when calling `is_bundled()`. Forcing `is_bundled()` to return 0 make the app behave well when launched from the shell, but not from Finder, and forcing it to return 1 (which it does in the case above) makes the shell launch hang.

**Comment by ManoloFLTK** [comment]
That should be fixed with the last commit.

Running an unbundled app seems impossible under Sonoma: even `main()` doesn't start.

The fix requires to act differently if the app is started under Xcode or not. That's very hacky, but I didn't find a way out. With FLTK, we don't use macOS's interface builder, so we are kind of away from what Apple expects from a well behaved app.

**Comment by ManoloFLTK** [comment]
This further commit is quite better and should allow us to close the issue.

**Comment by revisionfx** [comment]
Thanks Matthias (like 30 installers redo in progress here :( )

**Comment by MatthiasWM** [comment]
@revisionfx did Manolo's fix from commit [c62501c](https://github.com/fltk/fltk/commit/c62501c93a802a9853a9f44fc9e79b294a4be81c) work for you? Happy rebuilding.

**Comment by ManoloFLTK** [comment]
@revisionfx Please, try with commit c27009e rather than the previous one. Does it fix the issue?

**Comment by revisionfx** [comment]
Just to be clear, we hard coded fix to src/Fl_cocoa.mm here to ship, we downloaded your commit, compiled it and plan to test and confirm it all works hopefully this week -  note if it makes you feel better, it also broke GlobalSign we used for windows and linux installer signature (running all the installer building on a Mac, notarize at Apple etc).  

Pierre

**Comment by MatthiasWM** [comment]
@revisionfx Thanks for the confirmation. I am kind of glad to hear that we are not the only ones with issues. 

@ManoloFLTK @Albrecht-S Since this is such a disabling bug for macOS, do you think we could/should move the fix to 1.3 as well and make a new release?

**Comment by ManoloFLTK** [comment]
@Albrecht-S I intend to backport the fix to `branch-1.3` after confirmation by @revisionfx is received.

**Comment by revisionfx** [comment]
I am being told, all good - works

Pierre

**Comment by ManoloFLTK** [comment]
The fixes reported here to support macOS Sonoma 14 have also been committed to branch-1.3.

**Comment by MatthiasWM** [comment]
Thanks so much Manolo for fixing this so quickly!
