### ISSUE TITLE
Fluid: can't specify FL_OVERRIDE in derived class

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#801]
**Describe the bug**
Specifying FL_OVERRIDE in a subclass doesn't seem to work. See example below for a test case in a simple .fl file.
But maybe I'm doing something wrong.

**To Reproduce**
See this complete fluid (.fl) file:
```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
utf8_in_src
header_name {.h}
code_name {.cxx}
decl {\#include <FL/Fl_Group.H>} {public global
}

class MyGroup {open : {public Fl_Group}
} {
  Function {MyClass(int X,int Y,int W,int H, const char *L=0):Fl_Group(X,Y,W,H,L)} {
    comment CTOR open
  } {}
  Function {handle(int e) /* FL_OVERRIDE */} {open return_type int
  } {
    code {return Fl_Group::handle(e);} {}
  }
}
```

1. Build current FLTK with configure/make for following instructions to apply literally
2. save above sample file as 'override.fl' in FLTK root folder
3. run the following commands (using g++, YMMV), see compiler warning below
```
$ fluid -c override.fl 
$ fluid/fluid -c override.fl
$ g++ -c -o override.o override.cxx `./fltk-config --cxxflags` -Wsuggest-override
In file included from override.cxx:3:
override.h:11:7: warning: ‘virtual int MyGroup::handle(int)’ can be marked override [-Wsuggest-override]
   11 |   int handle(int e) /* FL_OVERRIDE */;
      |       ^~~~~~
```

If I uncomment `FL_OVERRIDE` (or use `override` directly) the corresponding signature is used in both the header and the source file which is OK for such attributes like `const` but not for `override`:
```
$ cat override.fl
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
utf8_in_src
header_name {.h}
code_name {.cxx}
decl {\#include <FL/Fl_Group.H>} {public global
}

class MyGroup {open : {public Fl_Group}
} {
  Function {MyClass(int X,int Y,int W,int H, const char *L=0):Fl_Group(X,Y,W,H,L)} {
    comment CTOR open
  } {}
  Function {handle(int e) FL_OVERRIDE} {open return_type int
  } {
    code {return Fl_Group::handle(e);} {}
  }
}
$ fluid/fluid -c override.fl
$ g++ -c -o override.o override.cxx `./fltk-config --cxxflags` -Wsuggest-override
In file included from ./FL/fl_types.h:24,
                 from ./FL/fl_utf8.h:31,
                 from ./FL/Fl.H:33,
                 from override.h:5,
                 from override.cxx:3:
./FL/fl_attr.h:129:21: error: virt-specifiers in ‘handle’ not allowed outside a class definition
  129 | #define FL_OVERRIDE override
      |                     ^~~~~~~~
override.cxx:5:28: note: in expansion of macro ‘FL_OVERRIDE’
    5 | int MyGroup::handle(int e) FL_OVERRIDE {
      |                            ^~~~~~~~~~~
```

**Expected behavior**
We need a way to specify FL_OVERRIDE in a derived class in fluid so we can compile with `-Wsuggest-override`. I can imagine either a check mark "use FL_OVERRIDE" (which would in future versions be just "use 'override'" or fluid would have to "filter" `FL_OVERRIDE` or `override` when generating the C++ source file.

**FLTK Version**
1.4.0, Git master, commit 27a779b2357fb27ae834e8921323f09fd3288940

**FLTK Configure / Build Options**
Default build with configure/make but building with CMake has the same issue.

**Operating System / Platform:**
Debian 12/Bookworm, but shouldn't matter.
Other platforms may need different compiler switches.

**Additional context**
I found this when testing Greg's new Fl_Terminal branch (PR #800) because I always compile with `-Wsuggest-override`. I couldn't manage to add `override` or `FL_OVERRIDE` to silence the compiler warning.

**Comment by MatthiasWM** [comment]
Thank you. There is no code that handles `override` or `FL_OVERRIDE`. FLUID assumes that user use the old `virtual void something()` signature, or no `virtual` keyword at all. I will add this feature.

**Comment by MatthiasWM** [comment]
Should be fixed in https://github.com/fltk/fltk/commit/ca7844cf94ad5ba892fe8b162a86b25c9ba6a172

**Comment by Albrecht-S** [comment]
Thanks, it works now.

However, I found a minor issue when testing this with `Fluid`s shell commands: the shell output window obviously doesn't show `stderr`, hence I couldn't see the expected error messages which surprised me in the first place. I wonder if this is intentional and/or if it should be documented. Or maybe add a check button "show stderr" or similar.

An easy workaround was to add `2>&1` to the shell command so fluid would display the error messages I expected (e.g. for syntax errors and other compiler warnings).

@MatthiasWM Please feel free to close this issue, I just wanted to mention this. If this needed further attention I could open another issue (or you could just take care of it...).

**Comment by erco77** [comment]
I've always had to add 2>&1 to my fluid build commands; works in both unix and windows.
If you use popen() you really have to, as popen() doesn't support stderr.

We could roll our own; on unix with fork()/exec() you can redirect stdout and stderr together much the way 2>&1 does, and in windows you can do the same (it's a little harder) setting up pipes for the STDHANDLES before the CreateProcess() call. But just adding 2>&1 seems the easier thing to do. Perhaps we should append it if the user didn't specify it.

**Comment by Albrecht-S** [comment]
> just adding 2>&1 seems the easier thing to do. Perhaps we should append it if the user didn't specify it.

@erco77 OK, after reading your comment I think we should leave it as it is. Rolling our own pipe stuff seems to be too much in this case.

We should however document it somehow so users (like me) know what they need to do to see error messages in the fluid shell window. I discovered the error messages on the terminal window I started fluid from, but on Windows that wouldn't work. Somehow we should help users to avoid having to learn this the hard way.

**Comment by erco77** [comment]
Yeah, there's a bit of busy work you have to do in WIN32 that isn't so bad in unix.
For the record, here's a comparison of the unix pipe/fork/exec approach vs the hunk of WIN32 code.
One nice thing about rolling your own is you can easily support a "Cancel" button in the FLTK UI that can just killpg() the process group. popen() doesn't provide a PID, but doing it yourself will, and you can set it up so that killing the child kills the child's entire process hierarchy as well (sh/make/g++), (cmd/nmake/cl.exe) so that no weirdness is left behind. It's tricky but works fine if 'done right'.
![pipe-process-unix-vs-win32](https://github.com/fltk/fltk/assets/6484779/b8f95b42-ac37-4c6b-856f-c7927f1df917)

**Comment by MatthiasWM** [comment]
Yes, this was the intention of #678: roll an Fl_Process class that can do all these additional things and link seamlessly with Fl_Terminal. Especially the kill feature is really needed, but some other convenience stuff as well, for example, send command output into a string, get stdout and stderr while still being able to send via stdin, etc.

**Comment by MatthiasWM** [comment]
See #803 and #678.
