### ISSUE TITLE
Fluid shortcut Ctrl+0 should perhaps not be used

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#802]
Fluid uses the shortcut Ctrl+0 to load the last used .fl-file.
This collides with the Ctrl+0 zoom event (reset scale to 100%).

It is unexpected when zooming via Ctrl+ and Ctrl- and then trying to reset the scale with Ctrl+0, that this does not work, but instead opens a fluid file.

**Comment by MatthiasWM** [comment]
Ah, thanks. I will change that to a different shortcut. Shortcuts in general are not too intuitive. Maybe I make them configurable at some point...

**Comment by MatthiasWM** [comment]
Fixed in [ab6ef9d](https://github.com/fltk/fltk/commit/ab6ef9d52f60ac991baafc7af33775e34484f358) . Ctrl-1 now loads the latest file in history instead of Ctrl-0.
