### ISSUE TITLE
fluid 1.4.x: New shell command stuff

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#803]
The new shell stuff is cool, I'm getting used to it.

I realize it's probably still in progress, but thought I'd mention some things I keep tripping on:

- When a fluid file has multiple build commands configured in "Shell -> Customize..", it should remember which one was last selected when you Save, Exit, and re-open fluid. As it is, if you open a .fl file and hit Alt-G, it still runs the Sample Shell Command, instead of the last selected one.

- Creating new shell commands are not appearing under the "Shell" submenu. I imagine too it would show the user-configured shortcuts for each different shell command (e.g. Alt-G, etc). I suppose if no shortcuts are configured by the user, Alt-G would run the "currently selected" one from the "Shell command list", and that would show in the Shell submenu as the shortcut for just that command, and the others would have blank shortcuts. (I figure this is a WIP, but thought I'd mention it..)

- RFE: In the new "Shell" tab, please add a radio button (down with the others) that disables the confirmation dialog for saving the .cxx/.h files. I see it's in "General -> Show Completion Dialogs", but it'd sure be nice if it also appeared in the "Shell" dialog, as a user looking to turn that off wouldn't necessarily know where to look for that.

**Comment by erco77** [comment]
To clarify the bit about Alt-G and the Shell submenu, I currently have several commands in my "Shell command list":

         ___________________________
        | Sample Shell Command      |
        | My Unix Build Command     |
        | My Windows Build Command  |  <-- selected
        | My Regression Tests       |             
        |___________________________|

Since I'm currently working on windows, I have "My Windows Build Command" selected, and Alt-G runs that command.

So if I exit out of fluid, I kinda expect that item to still be selected, and when I hit "Alt-G", it would run that command, and not any of the others.

Since I haven't defined separate shortcuts for each item, it seems intuitive to assume Alt-G is the shortcut for the /currently selected item/. If other shortcuts are defined, those would take precedence I suppose, but perhaps Alt-G would just ALWAYS be the "currently selected item"?

Anyway, in the fluid "Shell" submenu (off the main menubar), I'd expect to see this in the submenu:

    Customize..                  Alt+X
    ----------------------------------
    My Unix Build Command
    My Windows Build Command     Alt+G    <-- shortcut always the "selected item"
    My Regression Tests

**Comment by MatthiasWM** [comment]
> The new shell stuff is cool, I'm getting used to it.
> I realize it's probably still in progress, but thought I'd mention some things I keep tripping on:

Thanks for taking the time to look into the new features. I love to get feedback. Ideally, I would love to stand behind every user for a while and watch how they use FLUID, so I can react and make things easier.  I loved that when working at DD. I could just go to the artists and look over their shoulder while they were using Nuke. A million times better than any bug report ;-)

> * When a fluid file has multiple build commands configured in "Shell -> Customize..", it should remember which one was last selected when you Save, Exit, and re-open fluid. As it is, if you open a .fl file and hit Alt-G, it still runs the Sample Shell Command, instead of the last selected one.

I remove the concept of "run again". I assumed that users will define shell commands for "Build and run..." for example, and assign "F5" as a shortcut, or whatever they are used to. In the settings panel, you can make shell commands conditional, so you can run different scripts on Windows vs. Linux vs. macOS. They can all have the same "F5" shortcut key, but call different scripts on different host OS's. So you can configure "F5" to always build and run, no matter what platform. If you need to different things based on the hostname, you can make that part of the script itself.

![Screenshot 2023-10-22 at 11 57 15](https://github.com/fltk/fltk/assets/653993/9285a396-e59a-4b57-8eab-8b69fa8a7992)

> * Creating new shell commands are not appearing under the "Shell" submenu. I imagine too it would show the user-configured shortcuts for each different shell command (e.g. Alt-G, etc). I suppose if no shortcuts are configured by the user, Alt-G would run the "currently selected" one from the "Shell command list", and that would show in the Shell submenu as the shortcut for just that command, and the others would have blank shortcuts. (I figure this is a WIP, but thought I'd mention it..)

In the "Shell" menu, the last item is always "Customize..." which opens the Shell tab in the settings menu. Clicking "+" will create a new shell command. In the lower half of the tab, you can configure the selected shell command for any shortcut you like and make it conditional to a host OS. You can also remove the sample shell command by selecting it in the list (upper half of Shell tab in settings) and clicking DEL, or simply change or remove the shortcut of the sample item.

> * RFE: In the new "Shell" tab, please add a radio button (down with the others) that disables the confirmation dialog for saving the .cxx/.h files. I see it's in "General -> Show Completion Dialogs", but it'd sure be nice if it also appeared in the "Shell" dialog, as a user looking to turn that off wouldn't necessarily know where to look for that.

LOL, yes. I think I can turn that off by default anyway. I did not realize this "feature" until I *enabled* completion dialogs accidentally.

**Comment by MatthiasWM** [comment]
PS: the main menu pulldown will always update. So if you define shortcuts per script, they will all be listed there. If you have conditional scripts, only the one for your current platform will show. There is not really a concept of a "current" script. But you can assign "F7" to build, "F5" to run, etc. etc. , and have single keystroke access to everything.

**Comment by erco77** [comment]
> In the "Shell" menu, the last item is always "Customize..." which opens the Shell tab in the settings menu. Clicking "+" will create a new shell command...

Ya I understand, but in my case the Shell main menu pulldown only ever has "Customize..", and doesn't seem to ever get populated with the new shell commands I created:

![screenshot](https://github.com/fltk/fltk/assets/6484779/fe5db81c-7d2a-48ef-840c-a19e0cf0b759)

I pulled the latest 1.4.x and rebuilt just to be sure before making this STR (oops, issue) just to be sure I had the latest.

**Comment by MatthiasWM** [comment]
Oh! I will look into that.

**Comment by MatthiasWM** [comment]
Hmm, I can't replicate that (6cc3eb32db192e5a0c2453cf0ea261e042dbf818). Can you give me a step-by-step? I am using VisualC as the IDE (Windows 11, ARM64, Parallels virtual machine). 

![Screenshot 2023-10-22 at 23 17 55](https://github.com/fltk/fltk/assets/653993/f648d183-53c9-4616-9a97-97fef64dd0fe)

This code decides what goes into the menu: https://github.com/fltk/fltk/blob/6cc3eb32db192e5a0c2453cf0ea261e042dbf818/fluid/shell_command.cxx#L543 , but it seems that even scripts marked "all platforms" are not showing.

**Comment by erco77** [comment]
Hmm, I'll attach my .fl file, which I think is supposed to have all my shell functions in it, because I have "Project File" checked:
[for-matt.zip](https://github.com/fltk/fltk/files/13064826/for-matt.zip)
When I open that file with fluid, the customize menu is empty (as shown in my screenshot), but the shell commands are there.

I'm not sure what steps I took to get there honestly; I did use + to make the first, then ++ to duplicate that to make the second and changed the command for MS windows.

**Comment by MatthiasWM** [comment]
I tested your .fl file and it works as expected for me on Windows and macOS. It seems that the whole shell menu never gets initialized, so I made a few changes to always read the user settings and update the menu before the main window is even shown. I am not sure how that would help, but I have no other idea (667d5b9b72ca1c22b0ca63bd8c4cf0725a19e4a2).

How did you build the Windows version? I am using VisualC, but maybe Cygwin or whoever has different flags or macros when compiling?

**Comment by MatthiasWM** [comment]
One option came to mind. If you use File/Merge to load a project instead of File/Load, the shell scripts are not loaded. Same with copy/paste: even if al nodes are selected, the project settings are not copied.

**Comment by erco77** [comment]
Oh, sorry for slow reply -- I must've missed the email reminder on this.

Your question about how do I build on Windows: I use a win10pro with VS 2019, and use cmake, having it generate nmake files, as per my one contribution to the README.CMake.txt which I use a lot:
```
cmake -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /Ob2 /D NDEBUG" -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /Ob2 /D NDEBUG" ..
```
I use that because I like to never have to open that fat monster of an IDE. :^P

I never use cygwin for any serious work; that /c/pathname stuff it seems to have built in causes me all kinds of woes; not a fan of that stuff.

**Comment by erco77** [comment]
BTW, I think you may have fixed the first two out of three items I reported in the OP.
For the third item, a radio flag, I'm fine with the default being to show a dialog when the .cxx/.h files are saved; I think that's useful for new users wondering if anything happened. But it would be nice to turn that off once familiar with the tool. Another useful place for such a radio button is in the dialog itself. Many "annoying dialogs" usually have a "Don't show this again" radio button in them, which is a nice way to let the user turn that stuff off.

**Comment by erco77** [comment]
Oops, closed by accident -- reopening unless you're ready to close.

**Comment by MatthiasWM** [comment]
> BTW, I think you may have fixed the first two out of three items I reported in the OP.

Oh, good! ;-)

> For the third item, a radio flag, I'm fine with the default being to show a dialog when the .cxx/.h files are saved. (...) Many "annoying dialogs" usually have a "Don't show this again" radio button in them, which is a nice way to let the user turn that stuff off.

Well, it no longer show the completion dialog if using a shell command, no matter how the user setting is. Popping up the shell dialog is feedback enough. And thanks for the "Don't show this agin" idea. That's easy and makes sense.

**Comment by Albrecht-S** [comment]
> ... thanks for the "Don't show this again" idea. That's easy and makes sense.

For me (as a user) I'm always worried how I can reset this particular "Don't show **_this_** again" flag if I ever need or want it. Maybe this would need to be a hint in the dialog, like "you can turn this on again in menu x/y/z/...".

@erco77 wrote:
> that'd be a great built-in dialog for fl_ask.h, as I imagine it'd be a common thing. I'd use it myself, ...

Hmm, how should this be implemented? Just an additional "Don't show this again" (variable) label with a checkmark? Then the value of the check mark would be accessible by the user program, and that's it? From the point of `FLTK's fl_ask()` of `fl_message()` dialog, of course. Would this be something usable?

PS: before we "abuse" this **_closed_** issue, please open another one for this specific topic if you're interested in a general solution. TIA.

**Comment by Albrecht-S** [comment]
Note: @MatthiasWM opened issue #831 for this topic.
