### ISSUE TITLE
Fluid RFE: add find function

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#804]
**Desription**
When I'm working with fluid file(s) I often don't know which item to open in the fluid GUI, even if I know the (code) statement I want to change or view for some reason, e.g. in fluid's own `*.fl` files. Of course this can also happen with one's own project, particularly if it is large or after a long time not working on it or both.

**I am using FLTK**
 - Version 1.4.0

**Describe the solution you'd like**
Any help to find the item in the fluid GUI if I know its code or a part of it would be helpful. Currently I'm often opening the source view, then click on any GUI item and watch where in the source view its code becomes highlighted (which is very helpful, BTW). Eventually I'll find the item I want to change or view. Possible better solutions:
1. Add a `find` menu to the fluid GUI view. It should find GUI items that contain the requested string, open their tree, and select the item. `find next` would find the next item.
2. Add a 'find' menu to the `source view` window. Although this doesn't directly help to find fluid's GUI item it would still be very helpful, maybe for other reasons.
3. Add "line number comments" to the source view window with the number representing the GUI item number or the line number of the project's `.fl` file. It would be enough to do this in the source view (not the written source and header files) but having it in the written code (.cxx and .h) would maybe not be bad as well. Such comments might look like `// terminal.fl:1234`.
 
**Describe alternatives you've considered**
See above. Maybe there are even better alternatives.

**Additional context**
See also @erco77's [test/terminal.fl](https://raw.githubusercontent.com/erco77/fltk/Fl_Terminal_squash/test/terminal.fl) in his branch which has almost 2000 lines (not yet in master). Note that this link may become outdated after the branch is merged/deleted).

There's probably not much more to say to it. Someone knows **what** to change but can't find it easily in the fluid GUI. Of course it's possible to edit the project file directly but that's error prone.

This RFE has low priority. It would be great if @MatthiasWM would consider it but it shouldn't block release 1.4.0.

**Comment by MatthiasWM** [comment]
That should not be very difficult to implement. I will take a look at that since I have to revise some source code stuff anyway.

**Comment by MatthiasWM** [comment]
I added a find bar to the bottom of the SourceView window. Select the source, header, or .fl project file tab, enter a search term, and click "Reveal" and the widget browser will show the node that contains that piece of code. You can also just click into the text window, and Reveal will find the node that generated the code at the cursor position. Also, double clicking Reveal will open the editor for the node.

**Comment by Albrecht-S** [comment]
Awesome, will look into it (i.e. test) and report my results.

**Comment by Albrecht-S** [comment]
:+1: **THIS NEW FEATURE IS AWESOME !** :+1: 

@MatthiasWM I love it. It's such a big help if you need to find something in a fluid project you don't know well, or if it's just too big to "click everywhere".

I used Greg's [terminal.fl](https://raw.githubusercontent.com/erco77/fltk/Fl_Terminal_squash/test/terminal.fl) and looked for the `handle()` method that issued a compiler warning (suggest-override). You can't find and fix such a bug or warning quicker!

I found one minor issue, although I don't know if it is really one. When I search and click "reveal" in the **header view** on a method declaration **inside a class** then the entire class instead of that particular method is selected in the tree view. Revealing the same method **_in the source view works as expected_**.

As I said, not a big thing, please feel free to close the issue as fixed if it would be too much work to improve this.

**Comment by MatthiasWM** [comment]
> 👍 **THIS NEW FEATURE IS AWESOME !** 👍

Thanks 😁!

> I found one minor issue, although I don't know if it is really one. When I search and click "reveal" in the **header view** on a method declaration **inside a class** then the entire class instead of that particular method is selected in the tree view. 

Ah, yes. I did not think that header files can have hierarchies, but class declarations obviously are. It's easy to add. I will do that tomorrow.

**Comment by MatthiasWM** [comment]
Header file issue fixed in b270e1409caa23f8333c3eafb48534cb42957f12
