### ISSUE TITLE
Wayland: Overlay windows look blurred

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#808]
**Describe the bug**
Under Wayland all Fl_Overlay_Window's have a very blurred "look".
This can be seen with `test/overlay`.
But even better with Fluid, which is using an Fl_Overlay_Window for the widget previews.
Here is `valuators.fl` viewed with Fluid under Wayland.
![valuators_fluid_preview_wayland](https://github.com/fltk/fltk/assets/9895976/628ae406-58da-4d12-ad34-8c8aa9c5e726)
Also (can not be seen here) the top pixelrow and the left pixelcolum have the background (desktop) shine through.

**FLTK Version**
1.4 git

**Operating System / Platform:**
Ubuntu 20.04 (also 23.04) with Wayland

**Comment by ManoloFLTK** [comment]
Strange. It's not blurred here:
<img width="583" alt="image" src="https://github.com/fltk/fltk/assets/41016272/cf8b24e0-4052-4eb8-9195-dc5c1dd0fd41">

FLTK Version
1.4 git

Operating System / Platform:
Debian testing inside VM on MacBook Pro with Wayland (HighRes screen)

**Comment by wcout** [comment]
> Does your system use a scaling factor other than 1.0 or 2.0?

No, it is a plain 1980x1200 display and scaling is at 100%. I do get it on the real hardware and in a VM on this machine running Ubuntu 23.04 too.

**Comment by erco77** [comment]
Am I right in thinking cairo is behind all rendering on Wayland now, and if so, perhaps see if the cairo test tools (minus FLTK) do the same thing on the OP's system?

**Comment by wcout** [comment]
And it is not machine specific!
I do have the same blurry image on another notebook with different (graphics) hardware.
Also a standard (not hires) screen.

**Comment by ManoloFLTK** [comment]
Got it. it's blurred on non-HighRes displays.

**Comment by ManoloFLTK** [comment]
@wcout It's hopefully fixed with the last commit.

**Comment by wcout** [comment]
This fixes it - awesome!
