### ISSUE TITLE
fluid 1.4.x: problems when using flex within fluid

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#809]
**Describe the bug**
There's some weird behaviors that happen while trying to use New -> Group -> Flex interactively within fluid. I don't think the problems are with flex so much as how fluid handles the interaction with the widget during the manual interactive layout/positioning process.

_(I'd earlier made an issue I had to delete because I was mixing up flex/grid terminology.. trying again)_

There's a few different problems I seem to have:

**To Reproduce**

Problem # 1: Copy/pasting existing widgets into flex, flex doesn't always put the new widget "into" it. (My understanding is flex immediately takes control of the xywh of the widget, depending on the flex's VERTICAL|HORIZONTAL setting, and optionally the child widget's Size: and "Fixed" radio button)

1) Create a new function and a New>Group>Window around 500x400 in size
2) Create a New>Buttons>Button in the window, and position it near the left edge of the window
3) Create a New>Group>Flex, and move it away from the button, near the right edge of the window. Change the property of the flex to C++ > Subtype > VERTICAL
4) Click inside the button's area to select it, and hit ^C to copy
5) Click inside the flex's area to select it, and hit ^V to paste a copy of the button into the flex widget
6) PROBLEM # 1: I expect the new copy to appear inside the flex, but it appears outside it and hashed out.
7) I can drag the button copy inside the flex's area, and then flex seems to take control of its xywh, so that's fine, just unexpected.
8) Click the original button again to select it, and hit ^C to copy
9) Click the flex widget in the fluid tree (because it's hard to select the flex once it has children unless there's a gap) and hit ^V to paste
10) The new button copy again appears near the original and is hashed out.
11) This time, instead of moving the new copy inside the flex area, move it just a little bit, so that it's still outside the flex's area, just moved a little bit
12) PROBLEM # 2: Instead of being moved inside the grid, the flex widget re-sizes and re-positions itself to engulf the new button copy's position. This is unexpected.

There's a few other problems I noticed when resizing/repositioning the grid that causes the children to get 'lost' outside the widget, and other strange behavior when using the keyboard up/down keys to move it, depending on the VERTICAL/HORIZONTAL type for the flex.

**Comment by erco77** [comment]
Also, I received this comment you left in the issue I deleted:

> Ah, ok., but you are still not wrong at all. FLUID can't really handle Groups inside Flex or Grid (or any other widget that repositions children). I will need a flag for that ;-)

Ah, interesting, but just to be clear I'm not putting groups inside flex (and I haven't used grid yet). My issues are just with putting two or three buttons inside flex, and letting flex manage them.

In my actual app I'm using the Gap/Size and using both HORIZONTAL and VERTICAL options too, and as long as I get the layout right it works fine in the compiled app. It's just some weird interactive behavior in fluid I'm seeing.

**Comment by MatthiasWM** [comment]
6. That's simply a refresh issue. Fl_Flex does not update, which would reposition the Button before it is actually rendered. I *does* get added to the Flex, but I need to add the code to refresh the Flex.

12. This is based on the same issue, mixed with FLUID's attempt to enlarge groups when any of their children are moved out of bounds. I will try to fix that soon. Fl_Grid added some virtual functions that are needed to achieve this. SO it *is* related in some silly way.

**Comment by erco77** [comment]
OK -- what I can do is let you close this when the refresh issue is solved, and I'll make a separate issue for the other issues I've seen, because those are unrelated.

I just ran into these issues doing the replication steps for a different problem I was having involving moving the flex around with children already inside it nicely, and decided to report these first.

I'm pretty sure the repositioning issue is something unrelated to refresh, as the children really do get mangled in weird ways during movement/position changes of the flex that were probably just some simple xywh transpositions with the math.

**Comment by MatthiasWM** [comment]
4b5985eb49e057aa69b8ba4e91d0ad11e1cc87ff should catch most cases in 6, and 12 is probably just a result of 6 not giving the correct visual indication.

I will close this one for now. The bigger issue will be to fix widget layout when moving a group with children into the Flex. But that for another #issue.
