### ISSUE TITLE
Widgets nested inside groups that are inside a scroll group randomly lose the ability to receive events when you scroll

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#811]
**Describe the bug**
Hello
This was reported on the fltk-rs bug tracker here:
https://github.com/fltk-rs/fltk-rs/issues/1471
From the description there:
When you have groups nested in groups inside a scroll group, scroll causes seemingly random controls within the groups to stop responding.

**To Reproduce**
I was able to reproduce in C++:
```cpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Flex.H>
#include <FL/Enumerations.H>
#include <FL/Fl_Button.H>

#include <string>

static int COUNT = 0;

void row_btn_cb(Fl_Widget *w) {
    puts(w->label());
}

void btn_cb(Fl_Widget *w, void *arg) {
    COUNT += 1;
    auto scroll = (Fl_Scroll*)arg;
    scroll->clear();
    scroll->begin();
    for (int i = 0; i < COUNT; i++) {
        auto row = new Fl_Flex(0, 50 * i, 100, 50);
        row->type(Fl_Flex::ROW);
        auto b = new Fl_Button(0, 0, 0, 0);
        b->copy_label(std::to_string(i).c_str());
        b->callback(row_btn_cb);
        row->end();
    }
    scroll->end();
    scroll->redraw();

}

int main() {
    auto win = new Fl_Double_Window(100, 100, 400, 300, "Hello");
    auto col = new Fl_Flex(0, 0, 400, 300);
    col->type(Fl_Flex::COLUMN);
    auto scroll = new Fl_Scroll(0, 0, 0, 0);
    scroll->box(FL_FLAT_BOX);
    scroll->color(FL_GREEN);
    scroll->end();
    auto btn = new Fl_Button(0, 0, 0, 0, "add");
    btn->callback(btn_cb, scroll);
    col->fixed(btn, 50);
    col->end();
    win->end();
    win->resizable(win);
    win->show();
    return Fl::run();
}
```
And I think I was able to pinpoint the commit that added the behavior:
Commit b2a41e08c3b9b5fbbd0c899537611b8e28e5993d

1. Build the repro
2. Click on the Add button until the scrollbars appear
3. Scroll down
4. Try to click the row buttons

**Expected behavior**
The row buttons should be clickable

**Screenshots**
N/A

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Git, commit: b2a41e08c3b9b5fbbd0c899537611b8e28e5993d or later

**FLTK Configure / Build Options**
 - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DOPTION_USE_WAYLAND=OFF -DFLTK_BUILD_TEST=OFF

**Operating System / Platform:**
- Linux running Kubuntu 20.04

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by Albrecht-S** [comment]
Thanks for the report and for the C++ reproducer. If you really found the correct commit (mentioned above) I have an idea where to look and how potentially to fix it.

I'll look into it.

**Comment by Albrecht-S** [comment]
commit a710d700f3e82a744245817932c942b85022e327 fixes the issue for me in FLTK (C++).

Please confirm that it also fixes the fltk-rs issue. Thanks.

**Comment by MoAlyousef** [comment]
Hi @Albrecht-S 
It also fixes it for me in C++ and Rust.
Thank you

**Comment by Albrecht-S** [comment]
Thanks for confirmation and closing the issue.
