### ISSUE TITLE
Blend2D support?

### ISSUE THREAD

**Issue by rempas** [fltk/fltk#812]
Have you heard about [Blend2D](https://github.com/blend2d/blend2d)? It's a software renderer that uses a JIT compiler and [brags](https://blend2d.com/performance.html) to be faster than AGG, Cairo, QT6 and even Skia! And it brags to do that in most cases (which is very suspicious, as it sounds too good to be true).

If you have heard and tried it, how does it compare with FLTK's built-in renderer, and would you consider adding support for it in FLTK? The project seems very interesting, and I thought of sharing it and I thought that if it's faster than FLTK's built-in render (which I know nothing about), It may be worth supporting as from what I've seen, [there are no plans to support Vulkan](https://github.com/fltk/fltk/issues/753#issuecomment-1646205128), at least not from Matthias.

I opened this as a feature suggestion issue and didn't make a question in the forums because in case someone is interested to look at it and work on it, the issue can be used to track and report progress about it (and, of course, make further suggestions and questions).

**Comment by MatthiasWM** [comment]
As a GUI library, FLTK renders pretty much everything directly to the screen. We optimize greatly using clipping regions, which keeps pixels that are actually changed to a minimum. Blend2D is more of a compositing library for vector drawing and not a perfect fit for FLTK.

It's not impossible to write a Blend2D backend, but I don't see it as a priority. If you like to contribute a Blend2D backend to FLTK, I am sure that we will consider it as an addition or external library.

**Comment by ManoloFLTK** [comment]
I've just tried blend2d under macOS. I see it runs under macOS, Windows and Linux/Unix. One could therefore imagine replacing the various OS-specific graphics drivers FLTK presently use by a single blend2fd-based driver. However, text support is crucial for FLTK, and my impression is that blend2d does not provide transparent support of all scripts in all fonts, that is, what coretext does under macOS, GDI does under Windows, and Pango+Cairo do under Linux/Unix.

**Comment by rempas** [comment]
> As a GUI library, FLTK renders pretty much everything directly to the screen. We optimize greatly using clipping regions, which keeps pixels that are actually changed to a minimum. Blend2D is more of a compositing library for vector drawing and not a perfect fit for FLTK.
> 
> It's not impossible to write a Blend2D backend, but I don't see it as a priority. If you like to contribute a Blend2D backend to FLTK, I am sure that we will consider it as an addition or external library.

Oh! So it doesn't support bitmaps (if that's how they are called) and only vectors is what you are saying, right? In that case, yeah, I can see why it's not worth the effort to give support to it. Maybe it would be worth it if someone wanted to create a vector manipulation program, but still, it's too much wok for just a theoretical usage.

**Comment by rempas** [comment]
> I've just tried blend2d under macOS. I see it runs under macOS, Windows and Linux/Unix. One could therefore imagine replacing the various OS-specific graphics drivers FLTK presently uses by a single blend2d-based driver. However, text support is crucial for FLTK, and my impression is that blend2d does not provide transparent support of all scripts in all fonts, that is, what coretext does under macOS, GDI does under Windows, and Pango+Cairo do under Linux/Unix.

That's interesting. Could FLTK using the mentioned for transparent script support and use Blend2D for others? That would be interesting. But like said, Blend2D probably doesn't worth the effort to port to FLTK in general...

**Comment by MatthiasWM** [comment]
> > It's not impossible to write a Blend2D backend, but I don't see it as a priority. If you like to contribute a Blend2D backend to FLTK, I am sure that we will consider it as an addition or external library.
> 
> Oh! So it doesn't support bitmaps (if that's how they are called) and only vectors is what you are saying, right? 

That's not what I said. You can use Blend2D, but from what I read in their API documentation, it would not be my preferred choice. I have not checked for bitmaps support for rendering, and I know that it can write to the screen. It would need a better clipping engine to run as a backend for FLTK.

I did not mean that in any negative way: FLTK is open source. We create the graphics driver system so that users can add their own graphics backend, and if you see a need for Blend2D, by all means, write I, and we consider it if it makes FLTK better.

**Comment by rempas** [comment]
> That's not what I said. You can use Blend2D, but from what I read in their API documentation, it would not be my preferred choice. I have not checked for bitmaps support for rendering, and I know that it can write to the screen. It would need a better clipping engine to run as a backend for FLTK.

Thank you for the clarification! Personally, I only have some very basic knowledge of graphics and how they work, so I'm sorry that I got that wrong.

> I did not mean that in any negative way: FLTK is open source. We create the graphics driver system so that users can add their own graphics backend, and if you see a need for Blend2D, by all means, write I, and we consider it if it makes FLTK better.

Yeah, I am glad for that! I have talked about some things, and you guys seem to be very open about things in general. And I do understand and fully respect your choices, as a good project needs to have a good management that has priorities.
