### ISSUE TITLE
Commit 81615bb causes GL window to blink when resizing on macOS

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#813]
**Describe the bug**
Since 81615bbe0b96dc8640cee453b86bf8b4363b175a, the OpenGL window blinks between content and black during every resize operation.

**To Reproduce**
Launch test/cubs, resize, both GL areas blink. This is the same for CubeView and others.

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 81615bbe0b96dc8640cee453b86bf8b4363b175a introduces this regression

**FLTK Configure / Build Options**
 - cmake -G Xcode 

**Operating System / Platform:**
 - macOS Sonoma 14.0 (23A344)
 - Xcode 15.0 (15A240d)
 - MacBook Pro M1 CPU

**Comment by ManoloFLTK** [comment]
@MatthiasWM Please, close issue if you agree it's fixed after commit above.

**Comment by MatthiasWM** [comment]
Record time! Thank you very much!
