### ISSUE TITLE
overlay dotted line rendering problem (1.4.x-current + x11 (on a wayland system) + ubuntu 22.04.3 LTS)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#816]
**Describe the bug**
I noticed this dotted line rendering artifact while using fluid, but it's probably something more low level:
![fluid-dotted](https://github.com/fltk/fltk/assets/6484779/a3652045-5774-4a20-b620-bea841f95701)

As far as I know I don't have any special screen scaling or resolution; under the Desktop's right click -> "Displays" menu:

- **Resolution: 1920x1080**
- **Scale 100%**
- **Fractional Scaling: off**

**To Reproduce**
In my case, built fltk-1.4.x current with default cmake on Ubuntu 22.04.3 [EDIT: with Wayland on the system, but building with X11 support in FLTK only], and then:
1. Open fluid
2. Create a New -> Code -> Function/Method
3. Create a New -> Group -> Window
4. Create a New -> Group -> Group
5. Give the new group a label, e.g. "foo" <-- this is important to create the bug
6. The dotted line around the label is broken (as shown above)

**Comment by erco77** [comment]
This artifact reminds me a lot of that weird bug in X11's linux specific default drivers that had a hard time with line drawing patterns, which made focus boxes draw funny.. but in this case here it's Wayland, not X11, and this /seems/ to be exclusively with overlays (at least I think that's what fluid is using, not sure).

Focus box dotted lines seem to be drawing OK here.

**Comment by ManoloFLTK** [comment]
No such problem here:
<img width="283" alt="image" src="https://github.com/fltk/fltk/assets/41016272/13ebdf51-66c3-4e04-8267-c3b119f18415">

That's with Ubuntu 23.10 and both LowRes and HighRes displays.

**Comment by erco77** [comment]
@ManoloFLTK Any ideas what I should be checking; is this perhaps a cairo version thing? I assume cairo is behind /all/ drawing, but maybe not certain things?

**Comment by ManoloFLTK** [comment]
Make sure you don't have scaling in action (via environment variables you can get it). test/fullscreen will tell you.

Cairo is behind ALL graphics.

I tried with Ubuntu 22.04 and see the same correct dotted lines.

**Comment by erco77** [comment]
Hmm, while fltk built by default successfully, it didn't seem to build bin/test/fullscreen.
It is in the test source code directory, it just didn't build.. hmm.

Looking closely at the cmake output, seems like my build of fltk didn't pick up wayland after all, and is using x11:
```
..
-- Checking for module 'wayland-protocols>=1.15'
--   Found wayland-protocols, version 1.25
-- Checking for module 'xkbcommon'
--   No package 'xkbcommon' found
-- Not all software modules 'wayland-client>=1.18 wayland-cursor wayland-protocols>=1.15 xkbcommon' are present
-- Consequently, OPTION_USE_WAYLAND is set to OFF.
..
```

..so this might be an X11 issue after all; if so I'll tweak the title of this issue.

For sure the system is using wayland, as I can't do normal things in gimp like make screenshots. (Need special tools under wayland for this)

Seems xkbd in some form or another is needed for wayland builds, and the dev stuff must be missing on my system, which seems to be why it's not picking up.

**Comment by erco77** [comment]
OK, after installing about 10 packages, mostly x11 stuff oddly, fltk now builds with wayland, **and the reported problem goes away.**

So then this is **X11 specific** - if I build with Wayland turned off on this same system, e.g.
```
$ cmake -DOPTION_USE_GL=off -DOPTION_USE_WAYLAND=OFF ..
$ make -j 10
```
..then the problem returns. So I've tweaked the title of the issue.

_As a side note: I'm still not getting a **test/fullscreen** executable when fltk builds successfully, wayland or X11 style build. Is there something I need to enable that binary to build?_

**Comment by ManoloFLTK** [comment]
No such problem here with FLTK's X11 platform, nor with the hybrid Wayland/X11 platform run with FLTK_BACKEND=x11.

Is it a display driver bug?

GL is required to build test/fullscreen.

**Comment by erco77** [comment]
Ah, I have opengl disabled (see cmake command above) because I don't use/need it, so I guess that'd be why no test/fullscreen.

_Normally when our test apps depend on an external package that isn't present, (e.g. test/cube), the app builds and posts a dialog when run that says "This demo does not work without GL", which might be a good idea for test/fullscreen. The reasoning is similar to graying out menu items when they're not available instead of hiding them._

I don't know what's up with the X11 showing dots.. could be a driver issue, similar to that old focus box bug thing. Perhaps it's the same thing actually -- I can't remember if we accepted a patch that hides the issue for focus box (@Albrecht-S ?), in which case this may need a similar fix..?

**Comment by erco77** [comment]
Installed opengl + rebuilt fltk, test/fullscreen reports scale=1.00

I built fltk with ```cmake -DOPTION_USE_GL=ON -DOPTION_USE_WAYLAND=OFF ..``` with artifact results, and also setting the env variable `( export FLTK_BACKEND=x11 ; bin/fluid )` with same results.

Must be a driver problem -- might be 'that' default X11 driver problem, where it only works if you update to the actual driver for the graphics chip manufacturer, to avoid the x11 "default driver". If that's the case, leaving this open in case it makes sense to implement the same focusbox workaround we have for that, or something else.

**Comment by ManoloFLTK** [comment]
@erco77 Let's try and have fluid draw this particular dotted rectangle with the same code as what gets used to draw focus rectangles: apply small attached patch.
Please report what you get.

[issue816.patch](https://github.com/fltk/fltk/files/13248288/issue816.patch)

**Comment by ManoloFLTK** [comment]
About `test/fullscreen` without GL: neither `cmake -DOPTION_USE_GL=0` nor `configure --disable-gl` produce a `test/fullscreen` executable (or any GL-using test app). To see these executables in non-GL mode, it's necessary to configure FLTK **with** GL, then edit `config.h`, set `HAVE_GL` to 0 therein, and rebuild fullscreen. Its GUI becomes:

<img width="462" alt="image" src="https://github.com/fltk/fltk/assets/41016272/391a3c6c-152e-48c5-9cc9-722a2dd8ef27">

**Comment by Albrecht-S** [comment]
> Normally when our test apps depend on an external package that isn't present, (e.g. test/cube), the app builds and posts a dialog when run that says "This demo does not work without GL", which might be a good idea for test/fullscreen.

FYI: I'm working on changing `test/CMakeLists.txt` so we can use at least `CMake` to build `test/fullscreen` w/o having GL.

@erco77 When this is done your CMake build with `cmake -DOPTION_USE_GL=off -DOPTION_USE_WAYLAND=OFF ..` should build a working fullscreen demo program w/o GL.

This is not possible for all our demo programs that use GL though, at least not now. I'm investigating...
Will report here when done.

**Comment by Albrecht-S** [comment]
Done: Git commit d9798d2840ec55e2b45a6e53d8b9b3a118732a7f standardizes parts of `test/CMakeLists.txt` so we can easier build e.g. OpenGL demo programs that can also be built w/o OpenGL like fullscreen, handle_events, and unittests.

`cmake -DOPTION_USE_GL=off -DOPTION_USE_WAYLAND=OFF ..` can now be used to build fullscreen w/o OpenGL.

**_Note:_** I will definitely not change `test/Makefile` to do something similar.
`./configure --disable-wayland --disable-gl` **_DOES NOT_** build `test/fullscreen` …

… and this is OK for me. **_There must be a reason for users to move to CMake !  ;-)_**

**Comment by ManoloFLTK** [comment]
@erco77 I need you to know the effect of `issue816.patch` posted above because I can't replicate here this issue which is driver-specific.

**Comment by erco77** [comment]
Ah, OK, will try the patch in just a bit.. I kinda lost track of this issue, been busy on a large hardware/software project.

**Comment by erco77** [comment]
Added the patch -- looks good to me!
![fluid-with-patch](https://github.com/fltk/fltk/assets/6484779/559c533e-a665-4b13-9df7-2ea08a5ade27)
