### ISSUE TITLE
adding a widget_type_name() method

### ISSUE THREAD

**Issue by bstarynk** [fltk/fltk#82]
FLTK 1.4 (git commit a432db8ca3300666bf3f37 ..) has in its [`FL_Widget.H` file](https://github.com/fltk/fltk/blob/master/FL/Fl_Widget.H) a `virtual int type() const` virtual method returning some integer in all even indirect subclasses of `Fl_Widget`.  

It would be quite nice to add a new convention: Every widget class would have a `virtual std::string widget_type_name() const;`  method. The default implementation could be

     virtual std::string widget_type_name(void) const {
        char namebuf[32];
        memset (nambuf, 0, sizeof(nambuf));
        snprintf(nambuf, sizeof(nambuf), "fltk-type#%u", type());
        return std::string(nambuf);
    }

But every usual class of FLTK would reimplement the above, e.g. `Fl_Pack` would provide

    std::string Fl_Pack::widget_type_name(void) const { return std::string("Fl_Pack"); };

and so on for other standard FLTK widgets.

Such a change is less intrusive and lighter that depending upon C++ RTTI. It would help a lot those debugging FLTK applications with code like 

    Fl_Widget* widget = some_widget_returning_function();
     std::clog << "widget@" << (void*)widget 
                   << ":" << (widget?widget->widget_type_name():"*null*") << std::endl;

Basile Starynkevitch - near Paris, France ; 
I am using FLTK in the http://refpersys.org/ GPLv3+ project [branch `fltk-branch`](https://gitlab.com/bstarynk/refpersys/-/commits/fltk-branch)
<basile@starynkevitch.net> - http://starynkevitch.net/Basile/index_en.html

**Comment by Albrecht-S** [comment]
Thanks for the proposal - however I'm not sure if this is going to be implemented. The issue system is not the best place to discuss such questions, you should better ask this in our developers forum/Google Group [fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev).

That said, as you may have noticed already, the `type()` method is not a general type information about a widget type or class. It's more something to distinguish similar widget classes like different Fl_Button types or such (with some restrictions that Fl_Window derived classes have values > some min value etc.).

And you should also know that we don't use `std::string`, neither internally, nor in our public interfaces. However, that would be a minor issue, you could replace `std::string` with `const char *`.

I suggest that you start a thread in [fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev) and close this issue. TIA.

**Comment by Albrecht-S** [comment]
Please feel free to post your issue/question in [fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev) as suggested above.
