### ISSUE TITLE
maximize method for Fl_Window

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#820]
**Is your feature request related to a problem? Please describe.**
There is no function to maximize windows, only for fullscreen, but that's different. There is iconize though, so maximize only makes sense.

**Describe the solution you'd like**
There should be an API on all platform that we can forward to in the drivers.

**Describe alternatives you've considered**
fullscreen() is different...

**Additional context**
Forwarded from a Google Groups request by Will B. Original text here:
https://groups.google.com/g/fltkgeneral/c/zpsg4QkW94s/m/R5S1FJJfBwAJ

**Comment by ManoloFLTK** [comment]
see Pull request #823 that implements what is requested here.

**Comment by ManoloFLTK** [comment]
The requested enhancement is now in the git repo at 0ae927a.

**Comment by willbprog127** [comment]
Thank you so much! :+1:
