### ISSUE TITLE
fluid / fltk 1.4.x: disappearing text in code editor when moving between windows + linux

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#824]
**Describe the bug**
It seems that moving between windows and linux, ^M's are getting into the fluid system, causing various problems in the default code editor, such as making code "invisible" or drawn one line down from where it actually is, making editing impossible.

This MIGHT be related to a bug in Cairo that me and Manolo figured out in a different STR, but I'm not sure.
The problem manifests differently in the X version of fluid, where the ^Ms show up as little "boxes".

On Windows I'm using Win 10 Pro with Visual Studio 2019, and fltk 1.4.x current + cmake to create NMake files to build fltk.
On Linux I'm using Ubuntu 22.04.3 LTS with the default Gnome desktop + Wayland, fltk.1.4.x current + cmake default.

**To Reproduce**
1. On windows, open fluid
2. New > Code > Function
3. New > Code > Code
4. In the Code Properties, paste these 6 lines (blank lines important):
```
int x = 0;

// This is a comment
hello();

return(0);
```
5. Save the .fl file
6. *Move to a linux machine*, open the .fl file in fluid
7. Open the "Code"
8. Click on the blank line below the first line, and try to type anything. For me the text is "invisible"

At step# 8, the entered text is "invisible". You can hit Enter after what you type, and keep typing, new lines of text still invisible.

This behavior is with the Wayland version of fluid. If I use the X version, little 'box' characters show at the end of lines that have the ^Ms from windows.

Workaround is to edit the .fl file in e.g. VI (which clearly shows the trailing ^M's), remove the trailing ^M's, save, then reopen in fluid and all is well again.

We should probably be careful on windows with the whole \r\n vs \n thing. I'm not sure how it worked before, but I'm guessing fluid first "normalized" the text, probably into unix format before saving the .fl, and perhaps would remove them if found on load (in case someone used a windows based text editor to tweak the .fl file)

I think I've also seen where the ^Ms can get elsewhere in the .fl files, and cause errors on loading on linux that show up in the terminal window as weird .fl parsing errors.

**Comment by erco77** [comment]
If you don't have access to a windows machine, I'm attaching a [foo.zip file](https://github.com/fltk/fltk/files/13262407/foo.zip) which let's you skip steps 1-5 above. Just unzip the attached file and continue with step 6.

**Comment by erco77** [comment]
While I'm here, when I edit a fluid file, the titlebar of fluid shows a trailing ".cxx". I'm not sure what causes that, but I see it on linux and windows, e.g.
![image](https://github.com/fltk/fltk/assets/6484779/655df638-d410-4072-9c44-ee68b638fcbe)

**Comment by MatthiasWM** [comment]
> While I'm here, when I edit a fluid file, the titlebar of fluid shows a trailing ".cxx".

This is a feature. Just like the asterisk after coo.fl would indicate that the .fl file has changed and needs to be saved, the asterisk after .cxx indicates that the code file is out of sync with the project. I will put that in the docs.

**Comment by MatthiasWM** [comment]
Ok, so Windows *does* introduce `\r` characters before every `\n`, which by itself is no surprise. However it should obviously not do that in `.fl` project files, but it seems it always did (I can follow it back until before 2010)? I will fix this in the next hours, making sure that .fl files are always written with LF and no CRLF, and that all CRLF are filtered out on read.

That leaves me with many questions: what changed? why did we never see this before? Is really nobody out there but you using Fluid? Why can't Fl_Text_Editor handle CRLF? 

And one decision: I know it's better to write the project files with LF only, but for source code on MSWindows, do we really need to write CRLF? Ah, heck, I will write LF everywhere and try to filter out incoming CR wherever I can.

**Comment by MatthiasWM** [comment]
Ok, so I changed FLUID to always write LF in project, code, and strings files, and to ignore any CR it reads in project files. All other file readers (Data type for external image, external text) read and use the input verbatim, as they always did.

**Comment by MatthiasWM** [comment]
No worries about any text within fltk. Fltk expects only a \n, and that's still generated by typing ^J in the text field (which I like to do for toots as well).
