### ISSUE TITLE
1.4.x: Fl_Simple_Terminal ignores textsize() setting if ansi(true)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#827]
**Describe the bug**
When `Fl_Simple_Terminal::ansi(true)` is set, the `Fl_Simple_Terminal::textsize()` setting is ignored.

This is probably because when `ansi()` is enabled, a style table is defined to support colors, and I think style table's font size specifications override the `textsize()`.

If that's the case, changes to `Fl_Simple_Terminal::textsize()` should change the style buffer font sizes, assuming the default is specified (so as not to try to redefine a user defined style buffer).

_This of course would be moot if the `Fl_Terminal` project (PR #800) is merged, but I thought it's worth noting._

I'd also suggest the `Fl_Text_*` widget docs should warn that e.g. `textsize(), textcolor(), textfont()` etc. will be overridden when a style buffer is defined.. AFAICT this is not mentioned (e.g. [Fl_Text_Display::textsize()](https://www.fltk.org/doc-1.4/classFl__Text__Display.html#ad92e726e57de12916b1493ed2370177b) doesn't mention it).

**Comment by Albrecht-S** [comment]
@erco77 In the text above you mention right at the beginning twice `Fl_Terminal::…`. I assume this should read `Fl_Simple_Terminal` ?

**Comment by erco77** [comment]
Ah, yep -- muscle memory. I'll edit it.

**Comment by erco77** [comment]
Fl_Simple_Terminal is now made obsolete by Fl_Terminal, which is now in the master branch.
So "use Fl_Terminal" would be the recommendation here.
