### ISSUE TITLE
How to get the wayland windows handle?

### ISSUE THREAD

**Issue by chad-cao** [fltk/fltk#829]
Dear sir,
Now I need to combine the gstreamer's overlay to the window.
Gstreamer offers a function named "gst_video_overlay_set_window_handle(GstVideoOverlay * overlay, guintptr handle)". 
For the second parameters, I need the value of os_id() in Fl_Window class. But for wayland, it returns 0.
Is there any other ways to get this value?
Thanks
Chad

**Comment by ManoloFLTK** [comment]
To answer you, we should now what exactly is the argument `guintptr handle` of function `gst_video_overlay_set_window_handle()`. If it is an object of type `struct wl_surface*`which is the name Wayland gives to windows, you can do this :
```
#include <FL/platform.H>

  Fl_Window *window = ……
  window->show();  
  struct wld_window *xid = fl_wl_xid(window);
  struct wl_surface *surf = fl_wl_surface(xid);
  printf("surf=%p\n",surf);
```

**Comment by chad-cao** [comment]
Dear ManoloFLTK,
For the guintptr handle, it should be the value of Fl_Window::os_id()，but for wayland, it returns 0.
At the beginning, I also think it should be wl_surface, I tested, but it does not work. So if you also think it should be wl_surface, I think the problem should be with Gstreamer.
In a word, I will keep trying until I have a result, I will update here and close the issue。
Thanks
Chad

**Comment by chad-cao** [comment]
Hi @ManoloFLTK ，
I checked the source code of gstreamer, yes, you are right. For the handle, it is wl_surface.
About the failing, the gstreamer need its own display. So when I tried to send the handle from FLTK, it will return fail due to unrecoginzed. But if I use the gstreamer's display, I think FLTK also will not recoginze.
Maybe I have to use 2 surfaces, and set the FLTK window's alpha to 0, and place the gstreamer behind it.
Thanks
Chad

**Comment by ManoloFLTK** [comment]
> the gstreamer need its own display.

I don't understand what does this mean. Is display the same as window?

You may want also to consider function [fl_wl_compositor()](https://fltk.gitlab.io/fltk/wayland_8H.html#af64ed05f0b7da0063d7ed411eefcf2ff) that allows to create a wl_surface object independently from an Fl_Window.

**Comment by chad-cao** [comment]
@ManoloFLTK  I am not familiar with wayland. Just recently started learning how it works。
According to the source code of gstreamer:
if (G_UNLIKELY (sink->display->own_display)) {
        GST_ELEMENT_ERROR (sink, RESOURCE, OPEN_READ_WRITE,
            ("Application did not provide a wayland display handle"),
            ("waylandsink cannot use an externally-supplied surface without "
                "an externally-supplied display handle. Consider providing a "
                "display handle from your application with GstContext"));

Maybe I'm still doing something wrong, and I'm keeping learn.
Thanks
Chad

**Comment by ManoloFLTK** [comment]
We are good because FLTK does provide a wayland display handle: the return value of function `fl_wl_display()` declared in `FL/platform.H`.

**Comment by chad-cao** [comment]
@ManoloFLTK Haha，I really appreciate your confidence.
According to my understanding, fltk is also a client of wayland, which has its own memory and window list, etc, . When I only passed the fltk_surface from FLTK to gstreamer, gstreamer still couldn't use the associated memory, etc., so gstreamer had to have its own client as well. This is the reason of failing.
Or if I get a wl_surface or wl_display from gstreamer, it is possible to put the FLTK's buttons or other widget into them?
Thanks
Chad

**Comment by ManoloFLTK** [comment]
> Or if I get a wl_surface or wl_display from gstreamer, it is possible to put the FLTK's buttons or other widget into them?

No.
