### ISSUE TITLE
Fl_Text_Display: Old (minor) bug with linenumbers and word wrap

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#830]
The display of line numbers when word wrap is on can be wrong.

**To Reproduce**
Use `test/editor`

 - run `editor editor.cxx`
 - Turn on "Word wrap"
 - Scroll down with slider to bottom
 - Turn on line numbers

There are negative line numbers displayed:
![editor_wrap_lineno](https://github.com/fltk/fltk/assets/9895976/568cf5c3-8e4b-4fb7-8cdd-92c1527af19c)

**Comment by MatthiasWM** [comment]
Fixed: 214b133298f4a1b31e9b6ab89392fcd574fa6691
