### ISSUE TITLE
1.4.x fluid: tree view should show function names in bold? (and code in de-emphasized normal or italic font)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#832]
**Describe the bug**
Not a regression but an RFE: The fluid tree seems to always show functions in normal text, and the first line of "Code" blocks in Bold, as shown in this screenshot:

![image](https://github.com/fltk/fltk/assets/6484779/5e5e1876-3341-463f-b396-df8ab9d69dc4)

Note the bold text is the /least/ interesting thing to see.

I'm usually scanning the fluid tree for function names, but my eye is drawn to the bold code lines instead, which are usually uninteresting bits of code like random variable declarations or unrelated comments. It's hard to 'squint away' the bold code to see the more-important function names.

Switching those around seems to make _so much more_ sense to me, which I've mocked up just to demonstrate what I'd prefer:

![image](https://github.com/fltk/fltk/assets/6484779/ea042460-2c8b-4f5a-9ce4-8dd0947ad6df)

Assuming there's a reason for why it is the way it is, can there maybe be a *project* Preference for this to swap that behavior, so people used to the old behavior can still access it?

I think if one were to be successful with the current behavior, you'd have to go out of your way to make the first line of code a *comment* that reflects what your eye wants to see, which is a per-project thing, and while I've considered doing that, in my mind this is redundant, just duplicating what the function name should already do. And if I change a function name, I'd have to change these duplicate comments too; it just makes little sense to me. :^/

Please note, the current behavior *is* the old behavior, so this is not a regression but an RFE.

**Comment by MatthiasWM** [comment]
Hmm, yeah, I can see why this is annoying. I subconsciously  always keep function names "closed", so I don't see the first line of the code block. It's quite easy to make this into a *user* setting. I think that making this into a project setting would not be helpful.

**Comment by erco77** [comment]
Here's why I /think/ it's appropriate as a project setting:

_The fluid file might be /designed/ to show the comments in bold (like some of my old projects, where I try to leverage the first line as a useful comment), whereas a different project, like the one I'm working on now, is designed to emphasize the functions, because I don't have time to go back and make meaningful first line comments in the code; it'd just duplicate my function comments (a new feature in fluid IIRC)._

So if I designed the fluid file a certain way to be viewed, I'd want other users to see it the same way I do when I created/maintained it.

So even though I'm a single user, I might work on differently designed projects. I see this like using 4 space indent vs. 8 thing; it's per project, based on how the project is designed.

>  I subconsciously always keep function names "closed", so I don't see the first line of the code block. 

Ya, I just find it hard to do that.

What I often have done is try to stow all the functions once I'm done with the project, to make it "readable". But when the functions are stowed, one can't view/edit the code easily, so I have to go unstowing everything, which is kinda a pain (I don't think we have a 'stow all' and 'unstow all')


I think with the newer format, I'd just leave things "unstowed", as I wouldn't feel I have to stow everything for readability, and leaving it all open makes it easy to jump into the code quickly.

I'm maybe one of few people that works with really large fluid files, lol, so I might be the only one running into this enough to mention it.

**Comment by Albrecht-S** [comment]
**Just my 2 ct:** although I understand Greg's point that different projects may be designed differently I wouldn't like the idea to make such layout decisions project settings or user settings at all. It would make things more complicated (in fluid) and users might be confused (why is this project displayed this way and another one differently?).

But what do I know? I'm not a regular fluid user, please feel free to ignore my comment.

**Comment by erco77** [comment]
I'm fine with no option if that'd keep us from having "creeping featurism", but I do think switching things would be better generally.

I think if I ever got around to making an "advanced fluid" video showing how to make classes that derive from windows, people might use fluid for larger programs, as that allows one to create multiple windows + dialogs all within one fluid application. It would also let people develop separate fluid files per dialog (which is arguably better) so that each is its own class that can then be used/instanced within a hand written application.

**Comment by erco77** [comment]
Perhaps instead of making the Function/Methods bold, the Code could be NOT bold? Perhaps even a light gray/normal weight.

The code tree just gives too much emphasis to the first line of Code, which is truly unimportant information, making it _harder_ to  find the important things: functions/method names.

**Comment by MatthiasWM** [comment]
Also changed defaults

![Screenshot 2023-12-16 at 14 01 58](https://github.com/fltk/fltk/assets/653993/1a3740e5-da97-4176-8a05-6ca6dc72ad6c)

**Comment by erco77** [comment]
**Nice solution!** Woo hoo!

Some small things I noticed:

- Changing color for "Code" also affects New>Code>Comments (red)
- New>Code>Code lines are showing text beyond first line(orange).
  _Old fluid only showed first line (no \n's) which is better._
- Color picker pallet appears at the top/left of the root window.
  _This is on my wayland linux system, perhaps inherent to Wayland's window placement?_

![image](https://github.com/fltk/fltk/assets/6484779/15b378b0-65de-4063-92bf-620113ec4e60)

**Comment by Albrecht-S** [comment]
> Color picker pallet always appears at the top/left of root window.
This is on my wayland system, perhaps inherent to its window placement limitations

Pretty sure this is Wayland specific. Manolo is looking into a way to open dialog windows relative to the main window (similar to menus) on Wayland. Maybe this can be fixed with whatever he finds out.
See fltk.coredev thread "about fl_message_position(Fl_Widget*)":
https://groups.google.com/g/fltkcoredev/c/azVbctc_uT0/m/fZFfOxIRAwAJ
Looking forward to his solution...

**Comment by erco77** [comment]
Yes, I noticed that post too.
I noticed that, for instance, `test/color_picker` has this problem on wayland too.

**Comment by erco77** [comment]
Attaching a patch suggestion to truncate the \n's for comments + code:
[trunc_lf_patch_sugg.txt](https://github.com/fltk/fltk/files/13693210/trunc_lf_patch_sugg.txt)

Result:
![image](https://github.com/fltk/fltk/assets/6484779/1ff4b6a4-2750-4552-804e-937e4d8ded0f)

I didn't think it was necessary to add the "..." when truncating at \n's because it should be a clean break.

**Comment by MatthiasWM** [comment]
@ManoloFLTK  @erco77 @Albrecht-S As for where the picker palette appears, I can't fix that ATM, but I presume that we need to put those standard pickers into the same kind of popup window type that we use for popup menus. Not sure how that reflects in Wayland world. Maybe we need a more refined Fl_Popup_Window type?

The other two points should be fixed.

**Comment by erco77** [comment]
All good -- thanks!

**Comment by Albrecht-S** [comment]
> I can't fix that ATM, but I presume that we need to put those standard pickers into the same kind of popup window type that we use for popup menus. Not sure how that reflects in Wayland world. Maybe we need a more refined Fl_Popup_Window type?

I was thinking about an extended `Fl_Window::show()` method. It could be called `Fl_Window::show_relative()` and have an additional `Fl_Widget` and positioning parameters, or something like that. But let's wait until Manolo has something we can use for either popup windows or maybe just "other" windows like the "wingman" window described in a recent thread in fltk.general.
