### ISSUE TITLE
Potential dereference thru NULL pointer in Fl_Image_Surface::Fl_Image_Surface()

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#834]
A vulnerability for dereference thru NULL pointer exists in constructor `Fl_Image_Surface` in **Fl_Image_Surface.cxx**. I suppose this is not encountered in real life on FLTK supported platforms so far, but is theoretically a bug w.r.t bulletproofing, especially in a a sub-class scenario. 

This is in FLTK version 1.4 commit ff134f008.

The issue is at line 40.

A diff for an obvious patch fix is as follows:
```c++
diff src/Fl_Image_Surface.cxx ../fixes/src/
40,41c40,43
<   platform_surface->image_surface_ = this;
<   if (platform_surface) driver(platform_surface->driver());
---
>   if (platform_surface) {
>     platform_surface->image_surface_ = this;
>     driver(platform_surface->driver());
>   }
```

**Comment by ManoloFLTK** [comment]
Thanks.

**Comment by pdhahn** [comment]
I see you changed the code to eliminate the `if (platofrm_surface)...` check in the  `Fl_Image_Surface` constructor, instead of moving the vulnerable assignment statement under it. Note this same check exists in various other methods in the `Fl_Image_Surface` class, so perhaps whoever wrote it was anticipating (as bulletproofing, it seems) that `platform_surface` could be NULL. In any case, it looks a little strange to see the check in various other methods, but not the constructor.

Also, since (for example) I am considering subclassing `Fl_Image_Surface` based on some new driver classes I would also create, and others one day might do the same, wouldn't it be best to retain the bulletproofing check in the constructor?

**Comment by pdhahn** [comment]
(I deleted my previous post after further consideration of the code. If you see it, please ignore!)

I would just point out FYI that the `if (platform_surface)...` check still exists in a few other methods in `Fl_Image_Surface`. Yet other methods do not check for `platform_surface` being NULL, so that does look a bit inconsistent.

Anyway, I hope it's really true that the bulletproofing is not needed because it is safe to assume `Fl_Image_Surface_Driver::newImageSurfaceDriver(w, h,...)` always returns a non-NULL pointer (e.g., for all w, h).
