### ISSUE TITLE
Can the post-cmake report show if fltk is being built in debug vs. release mode

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#838]
It would be good if the report that's shown immediately after cmake completes shows if the build will be debug or not. (e.g. Release vs Debug)

It's easy to miss under automation when one's setting lots of flags.

**Comment by Albrecht-S** [comment]
Please provide more info about how you run CMake. The question is mainly how you specify the build type, and note that there is no single build type for multi-config builds like Visual Studio (although I assume that `nmake` is a single-config build). Anyway, more info would be helpful.

**Comment by erco77** [comment]
I'm using what's recommended in the README.CMake for building in debug mode:
```
cd build
cmake -D FLTK_BUILD_EXAMPLES=on -D CMAKE_BUILD_TYPE=Debug ..
```
AFAICT the build type is not reported in the post-cmake report.

It seems an important enough flag to report the state of.

I'm on linux at the moment, but I imagine it's the same flag for VS. A msg in the report like:
```
    Build type: Debug
-or-
    Build type: Release
..etc.
```
..would help give some reassurance the build style is what we think it should be.

**Comment by Albrecht-S** [comment]
Done in d446059766f9560a34735cd04beac319d1fb0858.

I called it "Build configuration" rather than "type". Looks like this:
```
-- ...
-- Example programs will not be built (set FLTK_BUILD_EXAMPLES=ON to build)
-- 
-- Build configuration     : Debug
-- 
-- Image Libraries         : JPEG = System
-- ...
```

**Comment by Albrecht-S** [comment]
> I'm on linux at the moment, but I imagine it's the same flag for VS.

VS is one of these "multi-config" build systems, i.e. the IDE project files are **_generated_** for more than one configuration and the build configuration is decided only when you actually **_build_** the project.

OTOH if you generate `nmake` files it's likely a "single-config" build system, I don't know. I guess you know that better than me.

**Comment by erco77** [comment]
Ya, I'm pretty sure that's how the nmake stuff works; very similar to the unix builds.

I haven't dug into the generated nmake files to see if they offer alternative targets other than `clean`. I think I looked at them once, and they were pretty ugly to read, and some had literally thousands of lines, and lots and lots of absolute (instead of relative) paths, which makes the lines realllllly long.

The nmake builds do honor the Debug flag, and create lib files with the "d" suffix, e.g.
```
Z:\tmp\fltk-1.4.x.git\build-win10pro-debug>dir /b lib
fltk_formsd.lib
fltk_gld.lib
fltk_imagesd.lib
fltk_jpegd.lib
fltk_pngd.lib
fltk_zd.lib
fltkd.lib
```
