### ISSUE TITLE
It seems like https://fltk.gitlab.io/fltk/ is not updating daily

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#843]
According to the [fltk docs page](https://www.fltk.org/documentation.php), this [gitlab page](https://fltk.gitlab.io/fltk/) shown in the title should be updating the 1.4.x docs daily.

But I've checked in some doc changes to Fl_Terminal to the master branch a few days ago that seem not to be reflected.

Albrecht, is there a way to check if this is stalled? I don't know how to check this, actually. I assume it has something to do with the [.gitlab-ci.yml](https://github.com/fltk/fltk/blob/master/.gitlab-ci.yml) file, but I'm not sure where it logs attempts, or how to check if the automated thing is actually "on".

**Comment by Albrecht-S** [comment]
@erco77 There's a simple check to see if the docs are up-to-date on the main page of the docs. Both the HTML and the PDF versions contain the generation date and the git revision at the bottom of the main page.

Looking at the GitLab mirror this seems to be all fine as of today: "_Generated on Nov 22, 2023 from Git revision 9383f172a8 by Doxygen 1.9.4_". **_Maybe you need to reload the page or clean your browser cache to get the latest updates in your browser._**

For GitLab CI builds (which generate the docs daily) you can view our GitLab mirror at https://gitlab.com/fltk/fltk:

![image](https://github.com/fltk/fltk/assets/26235500/b275bc9d-69f2-430b-8a4f-6a4828c12718)

If there is the green check mark (with tooltip "Passed" as shown in the screenshot) the CI build worked and the docs should be up-to-date. You can also click on the check mark (or the red cross if it failed) to see the build logs.

If anything fails I should also get a mail so I can look at it - but you can always drop a note in fltk.coredev if anything is missing.

Please close this issue if there are no further questions.

**Comment by erco77** [comment]
Ah, I think I see what's messing me up: it must be the different versions of doxygen.

On my system **any methods showing in black means there's no doxygen docs for those methods**, but on the gitlab apparently methods can show in black if the docs _are only one line long_, e.g.

![image](https://github.com/fltk/fltk/assets/6484779/6aa4d76d-f8fc-4c54-903a-a8ddd04251c9)

 And since I've been trying to make sure all the methods are doc'ed, that was throwing me off.

I guess I'm used to the old behavior, which I kinda prefer because I can also easily grab a link to any method, whereas with the new behavior, it's not as easy to access the link to methods that have only single line docs; you have to find it in the index.

Perhaps there's an option to control this in the newer doxygen config file, and the default is "off"?

**Comment by erco77** [comment]
Also thanks for the info on how to check the gitlab stuff. I didn't realize gitlab.com/fltk/fltk accesses the mirror; I'd only been using the fltk.gitlab.io link with the single /fltk argument.

**Comment by Albrecht-S** [comment]
> Perhaps there's an option to control this in the newer doxygen config file, and the default is "off"?

Perhaps this has been a bug fix. Where would a link point to when there is no more docs than this one line?

To answer that question myself: I checked it with an older doxygen version (1.8.14) and found that it points at itself. You are right that this makes it easier to copy the link.

If you're still looking for undocumented methods I believe the "List all members" link at the top of the class reference can be helpful. BTW, there seem to be only two _protected_ methods left: `handle_cr()` and `handle_lf()`. Well done.

**Comment by erco77** [comment]
I did a pass thru the modern doxygen config file docs and didn't right away see anything that preserved the old behavior when it comes to links for brief methods, but I'll bet it's in there somewhere. Pretty sure doxygen tries to provide ways to preserve old behavior when it's unclear which is the better one. I can kinda see why links vs. no links would be both good and bad; bad for consistency, but good for some kind of clarity on when to not expect more than just a brief.

I guess I'll close this.

> BTW, there seem to be only two protected methods left: handle_cr() and handle_lf(). Well done.

Thanks!

Regarding handle_cr/lf, I've been on the fence about making those private or not. The cursor movement methods need to be provided, since `ansi(false)` disables all the esc codes, but CR and LF still work with that off, so why provide them. :^/

> I found some more undocumented protected methods in the current GitLab docs, e.g. cursor_tab_left() and cursor_tab_right().

Hmm, those are documented on my local, so they must've been pushed after the gitlab generated.

**Comment by erco77** [comment]
> If you're still looking for undocumented methods I believe the "List all members" link at the top of the class reference can be helpful. 

Thanks -- that is useful, and I never noticed that stuff hiding up there at the top right.

Yeez, they sure hide that well. Those links should really be below the heading..!
