### ISSUE TITLE
Fl_Terminal has strange resize behaviour

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#844]
**Describe the bug**
When resizing a terminal when there is no/not enough history the result is somewhat unexpected.

**To Reproduce**
Minimal program:
````cxx
#include <FL/Fl_Terminal.H>
#include <FL/Fl_Window.H>
#include <FL/Fl.H>

int main()
{
	Fl_Window win(400, 300, "term");
	Fl_Terminal t(0, 0, win.w(), win.h());
	win.resizable(t);
	win.show();
	t.printf("Welcome!\n");
	return Fl::run();
}

````

**Steps to reproduce the behavior:**
After resizing the window a bit larger and then smaller one can easily end up with this screen:
![testterm_resized](https://github.com/fltk/fltk/assets/9895976/3364f095-2399-47c0-8b19-52dcdaebeb2e)

There are blank lines above the message and blank lines between the message and the cursor.

**Expected behavior**
The message should stay on top and the cursor be after it.

**FLTK Version**
 Version: 1.4.0 git

**Comment by erco77** [comment]
Ya, I know there is "something" odd after a resize().. I need to figure that out.
The correct behavior should be whatever xterm does, which is to keep line 1 at the top if there's no history, and enlarge into the history if there is history, and extend below the cursor if the window becomes larger than the history.

**Comment by erco77** [comment]
More details on what I think the goal for resize behavior should be, based on studying xterm's behavior:
```
Fl_Terminal enlarge:

    1. Enlarge display by revealing lines from scrollback history (if there is any) into top of display

    2. If there's no scrollback history to reveal from above the top of the screen,
       add blank rows to bottom of display (below cursor).

Fl_Terminal shrink:

    1. If shrinking the window hasn't yet reached the cursor position (C),
       erase lines from below the cursor (even if they have content!), e.g.:

           ------------------         ------------------
          |                  |       |                  |
          |                  |       |                  |
          | C                |       | C                |
          | 5                |        ------------------
          | 6                |         5  \
          | 7                |         6   >-- erased!
           ------------------          7  /



    2. If the bottom of the display reaches the cursor, move the cursor
       and content up to follow the bottom edge, and move lines above
       the cursor up into the scrollback history, e.g.:
       
                                       1
                                       2
                                       3
           ------------------         -------------------
          | 1                |       | C                 |
          | 2                |        -------------------
          | 3                |
          | C                |
           ------------------
```

**Comment by erco77** [comment]
This should be fixed in d3914ef.
(The commit's comment was unfortunately mislabeled, and I can't 'git amend' it)

Can you give it a try and see if this works for you? It should follow the resizing behavior of xterm(1).

**Comment by wcout** [comment]
It works pretty good now. Awesome!

**Comment by erco77** [comment]
Great! Closing.
