### ISSUE TITLE
Internal: Adding OpenGL swap_interval (STR 1373)

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#849]
https://www.fltk.org/str.php?L1373

Since this issue has boom much bigger that a classic STR (what in the world were they thinking when they implemented four different and mutually exclusive ways to do this in X/Wayland?), I decided to file a report and continue development in my own branch to not annoy with too many commits. I'll make this into a PR eventually.

**Comment by ManoloFLTK** [comment]
@MatthiasWM Please, see these comments about a putative [Wayland implementation](https://github.com/fltk/fltk/commit/f3348e81204a4758b0c7dc231607196b790128f1#comments).

**Comment by MatthiasWM** [comment]
Thanks, Manolo. I added your code and rebuilt the X11 code to catch all cases I found online. My emulator supports none of these extensions, so I can't test things. It does work on macOS for swap_intervals 0 and 1. MSWindows version still missing, but I am on it.

**Comment by MatthiasWM** [comment]
It's implemented on all platforms. I hope it helps someone. 49af3d88e39713c00d74eb15f5ca42f438c185e9

**Comment by Albrecht-S** [comment]
```
Building CXX object src/CMakeFiles/fltk_gl.dir/drivers/X11/Fl_X11_Gl_Window_Driver.cxx.o
/git/fltk/master/src/drivers/X11/Fl_X11_Gl_Window_Driver.cxx:412:48: warning: non-static data member initializers only available with ‘-std=c++11’ or ‘-std=gnu++11’ [-Wc++11-extensions]
  412 |   GLX_Set_Swap_Iterval_Proc glXSwapIntervalEXT = NULL;
      |                                                ^
```

@MatthiasWM Compiler warning (using C++98): should be easy to fix. TIA.

**Comment by MatthiasWM** [comment]
[a69fc0c](https://github.com/fltk/fltk/commit/a69fc0c9e5e561b2b5135a3e7d7faacd2e6666aa) hopefully fixes that.
