### ISSUE TITLE
FLTK wont run

### ISSUE THREAD

**Issue by Dogeislove** [fltk/fltk#85]
It doesn't run. 
code : 
//
// "$Id$"
//
// Button/callback test program for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

#include <stdlib.h>
#include <stdio.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/fl_ask.H>

void beepcb(Fl_Widget*, void*) {
	fl_beep();
	fflush(stdout);
}

void exitcb(Fl_Widget*, void*) {
	exit(0);
}

#if 0
// test Fl::add_fd()...
void stdin_cb(int, void*) {
	char buf[1000];
	fgets(buf, sizeof(buf), stdin);
	printf("stdin callback\n");
}
#endif

int main(int argc, char** argv) {
	Fl_Window* window = new Fl_Window(320, 65);
	Fl_Button* b1 = new Fl_Button(20, 20, 80, 25, "&Beep");
	b1->callback(beepcb, 0);
	/*Fl_Button *b2 =*/ new Fl_Button(120, 20, 80, 25, "&no op");
	Fl_Button* b3 = new Fl_Button(220, 20, 80, 25, "E&xit");
	b3->callback(exitcb, 0);
	window->end();
	window->show(argc, argv);
#if 0
	Fl::add_fd(0, stdin_cb);
#endif
	return Fl::run();
}

//
// End of "$Id$".
//
error log: 

1>Source.obj : error LNK2001: unresolved external symbol "public: void __thiscall Fl_Window::show(int,char * *)" (?show@Fl_Window@@QAEXHPAPAD@Z)
1>Source.obj : error LNK2001: unresolved external symbol "public: __thiscall Fl_Window::Fl_Window(int,int,char const *)" (??0Fl_Window@@QAE@HHPBD@Z)
1>Source.obj : error LNK2001: unresolved external symbol "public: static int __cdecl Fl::run(void)" (?run@Fl@@SAHXZ)
1>Source.obj : error LNK2001: unresolved external symbol "void __cdecl fl_beep(int)" (?fl_beep@@YAXH@Z)
1>Source.obj : error LNK2001: unresolved external symbol "public: void __thiscall Fl_Group::end(void)" (?end@Fl_Group@@QAEXXZ)
1>Source.obj : error LNK2001: unresolved external symbol "public: __thiscall Fl_Button::Fl_Button(int,int,int,int,char const *)" (??0Fl_Button@@QAE@HHHHPBD@Z)LNK1120: 6 unresolved externals

**Comment by Albrecht-S** [comment]
We need more information (platform, compiler, commands used to build, etc.).

Sorry, this is the wrong place to ask user questions. Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Thanks.

Please provide the platform (Windows, Linux, macOS), the build system, compiler, and the error messages in text form (copy and paste preferred). TIA.
