### ISSUE TITLE
Fl_Terminal needs public access to scrollbar; currently private

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#853]
**Describe the bug**
Fl_Terminal should make its scrollbar public, like Fl_Browser, so the app can change the scrollbar's color (for instance).

**Comment by Albrecht-S** [comment]
Thanks, commit 38aff7d9b4bfb5865406ab93a7118710e74d8dbe looks fine. It's of course OK to make the pointer public rather than adding a function as I wrote above. Sorry for potential confusion.

**Comment by erco77** [comment]
Fixed in 38aff7d9b4b.
_(Thought this would auto-close; forgot to specify the pound sign in the "solves" message of my commit)_
