### ISSUE TITLE
Fl_File_Chooser docs for the type() enum needs better docs

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#856]
**Describe the bug**
The class's public type() enum (SINGLE/MULTI/etc) shows up without docs, e.g.

![image](https://github.com/fltk/fltk/assets/6484779/3bd549a8-bd98-46ae-9581-084ff422590a)

Apparently this is an anonymous enum, so doxygen won't show docs for it unless we also give the enum a name.

Attaching a patch proposal [Fl_File_Chooser-docs-v1.txt](https://github.com/fltk/fltk/files/13532007/Fl_File_Chooser-docs-v1.txt) that does just that, giving it the name "Type" so the results end up looking like:

![image](https://github.com/fltk/fltk/assets/6484779/8867cb83-50af-46b7-b4e8-e43e74b4fbee)

The proposal also includes a few other doc fixes for that class; proper indenting for a multiline code example, and improved formatting for the constructor's parameters, e.g.

![image](https://github.com/fltk/fltk/assets/6484779/b7228521-f4aa-40ab-8627-f5a58fe9e29b)

If this looks OK, I'll commit. Asking because I had to change an anonymous enum -> named enum, which affects the API a bit, but in a backwards compatible way (I think).

**Comment by ManoloFLTK** [comment]
Apparently, it's possible to convince Doxygen to document an anonymous enum as follows:
```
class FL_EXPORT Fl_File_Chooser {
public:
  /** Determines the type of file chooser presented to the user. */
  enum
  {
     SINGLE    = 0, ///< Select a single, existing file.
     MULTI     = 1, ///< Select one or more existing files.
     CREATE    = 2, ///< Select a single, existing file or specify a new filename.
     DIRECTORY = 4  ///< Select a single, existing directory.
   };
……
```
This has the advantage of not changing the API.
Here is the resulting HML:
<img width="483" alt="image" src="https://github.com/fltk/fltk/assets/41016272/960bfe84-cd29-475e-bd3a-e8230da1d03c">
and
<img width="480" alt="image" src="https://github.com/fltk/fltk/assets/41016272/05e229a9-0424-48ab-b7ef-3d33ce23a190">

**Comment by ManoloFLTK** [comment]
I also wonder whether the constructor documentation misses an important thing: the enum contains values 0,1,2,4 rather than 0,1,2,3 to allow for combinations of values, e.g. CREATE | DIRECTORY. Shouldn't that be documented too?

**Comment by MatthiasWM** [comment]
> I also wonder whether the constructor documentation misses an important thing: the enum contains values 0,1,2,4 rather than 0,1,2,3 to allow for combinations of values, e.g. CREATE | DIRECTORY. Shouldn't that be documented too?

Yes, that would be very important, or maybe even create enums for all useful and supported combinations (CREATE_FILE vs. CREATE_DIRECTORY, etc.). Then again, it should not be an anonymous enum to begin with. Enums are not bitmasks unless you implement the '|' operator.

**Comment by erco77** [comment]
> [Manolo's enum Option example]

Ya, and we seem to logically OR those enums in our code without trouble:

est/clipboard.cxx:    fnfc.options(Fl_Native_File_Chooser::SAVEAS_CONFIRM | Fl_Native_File_Chooser::USE_FILTER_EXT);

I think the reason it works is when the enums are used in an integer context, they convert to ints and can then be combined with logical operators without tripping errors.

**Comment by MatthiasWM** [comment]
Yes, we do that all the time, and we may have to keep doing it for back compatibility. It's not bad per se, but it would be nice if the compiler did flag `myWidget->color(Fl_File_Chooser::CREATE);` as wrong. C++11 enum classes fix (some of) that.

**Comment by Albrecht-S** [comment]
I wrote:
> As @MatthiasWM mentioned, enums can't be used with bitwise OR as in CREATE|DIRECTORY, at least not with some compilers and enabled warnings of some kind. We should not do this as it violates C++ rules.

Sorry, I believe my statement was wrong. I remembered an issue in a such a context but I couldn't find anything related to that.

 It seems that you can use enums with bitwise OR and AND in C and C++ w/o issues. I checked https://en.cppreference.com/w/cpp/language/enum and there are some examples using bitwise OR and bitwise AND.

**Comment by MatthiasWM** [comment]
Sorry, a little rant. Please skip if not in the mood.

Yes, you can combine enums with OR, but the result is an int, so the original type is lost. You can write `Fl_File_Chooser::type(FL_GREEN|FL_FLAT_BOX)` and you won't even get a warning. Anonymous enums are especially bad because their type is never checked. C++11 has addressed this, and I believe the code there would look something line this:
```
class Fl_File_Chooser {
  enum class Type_Map { MULTI_BIT=1, CREATE_BIT=2, DIRECTORY_BIT=4 };
  void type(Type_Map t);
};
```
Now you can only feed exactly one of the enum values, but no integer, no FL_RED, or whatever users may type:
```
myFileChooser->type(Fl_File_Chooser::Type_Map::CREATE_BIT);
```
Since these are supposed to be OR'd together, we need to the tell the compiler:
```
Fl_File_Chooser::Type_Map operator|(Fl_File_Chooser::Type_Map lis, Fl_File_Chooser::Type_Map rhs) {
  ...
}
```
But we are on C++98, so this is all void. My confusion comes from having 0, 1, 2, and 4 as values, and it is not immediately obvious to me if someone just forgot the 3 in the list of types, or if this is a bitmap and I am supposed to use the 0 value in the logical "or". Again, we do that all the time in FLTK. This is only a proxy sample.

So my suggestion would be to name the enum, even if we can't use the name in `type()` for back compatibility reasons, and then provide values for all supported and useful combinations, which I think is limited to OPEN_SINGLE_FILE, OPEN_MULTIPLE_FILES, OPEN_DIRECTORY, CREATE_FILE, CREATE_DIRECTORY. Am I missing one? OPEN_MULTIPLE_DIRECTORIES? Of course, the old names have to remain for back compatibility.

**Comment by MatthiasWM** [comment]
For `CREATE` if states "Select a single, existing file or specify a new filename." . This does not work on macOS. If `CREATE` is set, you can *only create a new file, but not choose an existing one.

**Comment by MatthiasWM** [comment]
PS: this is absolutely no rant about programming skills or type. I hope it did not appear like that. This is more a rant on C++ not having a bitmap type even though it is a huge part of language use.

**Comment by erco77** [comment]
So is the suggestion to go with the patch, which names the enum Type but does not use it in the API (this is on purpose to allow logical flags), and just add an extra bit of docs for CREATE|DIRECTORY?

**Comment by ManoloFLTK** [comment]
> So is the suggestion to go with the patch, which names the enum Type but does not use it in the API (this is on purpose to allow logical flags), and just add an extra bit of docs for CREATE|DIRECTORY.

Yes, that's what I would support too.

**Comment by erco77** [comment]
OK, thanks for everyone's input!
Committed in b9ac6bd, closing.

**Comment by erco77** [comment]
Ah, looks like Manolo noticed a problem with my patch, and fixed it in b9ac6bd.

**Comment by Albrecht-S** [comment]
@erco77: Yes, Manolo (@ManoloFLTK) noticed the problem and commented on your commit (with some suggestions) but there is no commit that fixes this yet. commit b9ac6bd728659a7780d7cde024f34607601e8a7f is your own commit.

Greg, since you are our "Fluid user guru" ;-) I suggest that you copy your changes to the .fl file and regenerate the header and the source file. If you never did the latter in this special case, here's how to do it:
```
$ cd src
$ /path-to-fluid/fluid -c Fl_File_Chooser.fl
```
This should write the `.H` file to the `FL/` directory. Of course you can also do it in interactive mode. Then commit all three files if they were changed.

**Comment by erco77** [comment]
Ya, I caught that actually, and am kinda unsure at the moment IF fluid can even do this.. I'm not sure it can in its current state. I need a way to do New>Code>Code without associating it with a function/method, which is currently not possible. All the other Code options (Declaration, Declartion Block, etc) don't seem to work for this either. Might need a new feature or tweak to fluid to provide this.

**Comment by Albrecht-S** [comment]
... or add the documentation elsewhere in another source file. It might be possible in doxygen syntax to add documentation to arbitrary things elsewhere like this (not tested, not really a fitting example, just kinda pseudo doxygen syntax):
/**
  \function ...
*/

I don't know if this would be useful here but I don't think we need to [try to] put everything we can into fluid files.

Honestly, **_I can't "read" fluid files_**, and every source code created using large fluid files tends to become unmaintainable (for me at least). Don't understand me wrong, I appreciate fluid's capability to define the layout of such dialogs (here: `Fl_File_Chooser`) but I'm not a fan of putting lots of code and documentation into fluid files.

**Comment by ManoloFLTK** [comment]
@erco77 
I believe you can do like that with fluid:
<img width="874" alt="image" src="https://github.com/fltk/fltk/assets/41016272/cc949fb5-e02e-40c3-83ad-51fe887afc3e">

Only the first two enum values are commented, just to show the principle.

**Comment by ManoloFLTK** [comment]
The best approach is, I believe now, to do as Albrecht suggested: move Doxygen comments out of the .fl file, as follows
- Don't put any Doxygen comment in the enum declaration present in the .fl file
- Add this to Fl_File_Chooser2.cxx at lines 152 _ff_
```
/** \enum Fl_File_Chooser::Type
 Determines the type of file chooser presented to the user.
 */
/** \var Fl_File_Chooser::Type Fl_File_Chooser::SINGLE
  Select a single, existing file.
 */
/** \var Fl_File_Chooser::Type Fl_File_Chooser::MULTI
 Select a multiple files.
*/
/** \var Fl_File_Chooser::Type Fl_File_Chooser::CREATE
When used alone, select a single, existing file or specify a new filename.
Can be combined with DIRECTORY (e.g. CREATE|DIRECTORY) to have the same effect for directories.
*/
/** \var Fl_File_Chooser::Type Fl_File_Chooser::DIRECTORY
 Select a single, existing directory. Can be combined with CREATE.
 */
```

**Comment by MatthiasWM** [comment]
> Matt: Are you sure about the OS specific behavior on Macs? I might expect OS-specific stuff with the **native** chooser, but I'd like to think our own Fl_File_Chooser widget is consistent across all platforms.

@erco77 yes, you are right, I removed my comment.

@Albrecht-S yes, commenting in another file (or in the same file in a different comment block) is probably the best thing to do here, since Declarations are limited to one line of input. I should probably allow multiple input lines here, but as you said, it's often not helpful to have tons of code in FLUID besides the widget layout. FLUID is no IDE.

**Comment by ManoloFLTK** [comment]
@erco77 I would like to make sure you read the recent posts at issue #856.

Furthermore, the second point I had made in my comment to git commit b9ac6bd can be accounted for changing line 69 of file `Fl_File_Chooser.fl` to:
`Function {Fl_File_Chooser(const char *pathname, const char *pattern, int type, const char *title)} {open`

**Comment by erco77** [comment]
My goal was to try to follow the rule of keeping the comment near the implementation, so the two aren't separated from each other. This helps for easy maintenance, e.g. when new enums are added.

I think perhaps the best thing might be to add a New>Code>Comment in fluid for the class that uses the doxygen technique for documenting the enum away from the current declaration, but still within the fluid file. This avoids needing a separate file in the code base, while still keeping the docs near the implementation. Otherwise, second best might be to create a src/Fl_File_Chooser.dox file just for this.

But I would think, hopefully, there would be a way to do this type of thing within fluid in the future; fluid already has many features along these lines, e.g. declaring custom classes, so public class enums kinda go with that. I would think declaring New>Code>Code could be allowed without attaching it to a function/method? This way the enum could be declared just like normal code, and the dox comments included with it.

Regarding some of the ideas suggested so far:

- Redesigning Fl_File_Chooser so that the GUI layout is separate from the main class would have been good in the initial design, but it seems wrong to try to pry that apart now, esp. just to work around a missing docs feature.
- A separate file for the doxygen docs seems bad, as it splits the docs from the implementation, which should be avoided whenever possible IMHO
- Manolo's first suggestion for trying to put all the enum docs on a single line; I did already try that and ruled it out because it isn't readable or easily maintainable unless the comments are /really/ short.
- Can't break the enum into separate Declaration lines because fluid unconditionally adds ';'s at the end of each statement, preventing that from working.

Might not be able to revisit this until Wednesday; the power company here is installing new utility poles, so power will be on/off.

**Comment by MatthiasWM** [comment]
I will add multiline declarations later today. You can add the comments there easily. This will be backward compatible and easy to edit from then on. Probably in four or five hours from now.

**Comment by Albrecht-S** [comment]
@erco77 wrote:
> keeping it within the fluid file instead of in a separate dox file or separate Fl_File_Chooser2 file. This avoids needing a separate file in the code base, ...

This separate file (`src/Fl_File_Chooser2.cxx`) exists already, has lots of code and docs (1.651 lines!) and even the class documentation:
```
/** \class Fl_File_Chooser
  The Fl_File_Chooser widget displays a standard file selection
  dialog that supports various selection modes.
  ...
```
> ... while still keeping the docs near the implementation.

Well, this is a valid point.

> Redesigning Fl_File_Chooser so that the GUI layout is separate from the main class would have been good in the initial design, but it seems wrong to try to pry that apart now, esp. just to work around a missing docs feature.

IMHO it's not only to "work around a missing docs feature" in fluid. I wrote before why I believe that it would be better to separate widget design and code, particularly if the code is "hidden" in a big fluid file and maintainers like me have a hard time to find out how to change something they need to change. Separating design and code is generally a good principle and would be an investigation in the future and in better maintainability.

That said, we don't need to do this right now if it's not necessary, but we should IMHO try to do this in the future at least with our dialogs used in the library (two `.fl` files in `src/`).
```
$ wc -l src/*.fl
  533 src/Fl_File_Chooser.fl
  265 src/Fl_Help_Dialog.fl
  798 total
```

The fluid dialogs are even larger (7 files, 5.429 lines) but I wouldn't want to touch those, particularly not now, short before a release. Never touch a ~running~ working system.

**Comment by erco77** [comment]
> This separate file (src/Fl_File_Chooser2.cxx) exists already, has lots of code and docs (1.651 lines!) and even the class documentation ..

I haven't looked into it, but are you thinking we can move the enum declaration into Fl_File_Chooser2.H? If so that'd be a neat solution. (Oops, no, there isn't a 2.H, there's only a 2.cxx..)

I'll wait and see what Matt comes up with; sounds like he might have a solution that would work and keep things in the .fl which is how it was designed, so it seems best to keep with the flow of the existing code.

Agree separating the GUI from the class might be a good idea, but perhaps this was a test case for the (relatively new) fluid features that allow a GUI widget class to be completely designed within fluid. (New>Code>Class and New>Code>Widget Class). It's probably a good thing that this made us realize a missing feature to flesh that out.

I know you mentioned you have a hard time reading large-ish fluid files.. I think it's something one gets used to when using fluid a lot. I've been using it constantly, as one of my main commercial GUI applications, the most complicated one, makes use of this. It's surprisingly manageable, though in my case I did move some of the stuff into a separate .cxx/.h file, splitting off the GUI-centric methods from the backend stuff. Still, the gui centric code is quite significant, and uses messaging to do a lot of the inter-widget communications.

Going offline now for the day - power issues here. Be back on line later tonight/tomorrow.

**Comment by MatthiasWM** [comment]
> This should write the `.H` file to the `FL/` directory. Of course you can also do it in interactive mode. It's a little tricky to get the directories right because fluid does this different in batch and interactive mode.

It should be just fine in interactive mode.

OK, I updated the dialog box and the entry itself. There is still the issue of FLUID adding a rather random `;` at the end of the first or second line, which I will hopefully be able to fix. The current fix is yet another special car if the line starts with `enum`. Either way, we are fine now, I think.

**Comment by Albrecht-S** [comment]
@erco77:
> ... are you thinking we can move the enum declaration into Fl_File_Chooser2.H? If so that'd be a neat solution. (Oops, no, there isn't a 2.H, there's only a 2.cxx..)

Only the documentation could be moved to `src/Fl_File_Chooser2.cxx`, the declaration needs to remain in the class, i.e. in the fluid file AFAICT. This way we'd have the docs far away from the declaration which would be bad.

> Agree separating the GUI from the class might be a good idea, but perhaps this was a test case for the (relatively new) fluid features that allow a GUI widget class to be completely designed within fluid.

I didn't check when/if the mentioned feature has been added to fluid, but the two fluid files in the `src/` folder exist since september 2001. I'm not going to investigate this further.

> I know you mentioned you have a hard time reading large-ish fluid files.. I think it's something one gets used to when using fluid a lot.

**_This will never happen._** I'm not using fluid in my own FLTK projects at all, hence I need it only for FLTK maintenance. And this is really a burden when it comes to changing fluid files for some (maybe minor) code changes.

> I'll wait and see what Matt comes up with; sounds like he might have a solution ...

If there is a solution I won't object, but I'd still prefer to have less operational code in fluid files, if possible. But that's now OT here, we may discuss this separately later (I'm too busy with releasing 1.3.9 and preparing 1.4.0 for release anyway).

**Comment by erco77** [comment]
@MatthiasWM Great! Yeah, that's a good solution, and easy to see/maintain:

![image](https://github.com/fltk/fltk/assets/6484779/6fda2025-af77-49ce-8c37-f1b28ca9dca6)

I'll also implement @ManoloFLTK 's recommendations to change the type names and such, and close this as solved.

**Comment by MatthiasWM** [comment]
It always generates a Doxygen comment, but I should probably add a way to change it to a regular or a // comment.
