### ISSUE TITLE
fluid: unicode text in New>Code>Comments doesn't seem to work

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#858]
**Describe the bug**
I'm not sure how or why, but utf-8 isn't showing correctly in fluid's New>Code>Comments, e.g. the box characters '▒' pasted into the code comments shows up in fluid as:

![image](https://github.com/fltk/fltk/assets/6484779/b02f62bd-42dc-4122-babd-0c7d713789bb)

..whereas the same character in the New>Code>Comments dialog looks as expected:

![image](https://github.com/fltk/fltk/assets/6484779/12bcba92-e41d-47e3-af0e-adac21f4bfbd)

I thought utf-8 support is underneath all our text drawing stuff, so this seems like an odd exception..

**Comment by MatthiasWM** [comment]
> I thought utf-8 support is underneath all our text drawing stuff, so this seems like an odd exception..

I thought so too, but who know if we missed something somewhere. I'll check that out. I am so happy that you're testing FLUID so much. It really helps finding all the nasty bugs.

**Comment by erco77** [comment]
Ya, I've been designing a medium sized application from scratch using the new fluid. It's been generally smooth lately, no crashes or hangs, and have been able to keep rolling forward - it's been great! Love the new features.

I've been mostly developing on linux/wayland, but the target is windows. So at some point I'll be jumping onto windows to do touchups using fluid there too.

**Comment by erco77** [comment]
Reopening -- it seems the truncation thing fluid does that lops off the comment and adds "..." will truncate in the middle of multibyte utf-8..

**Comment by Albrecht-S** [comment]
> Will see if I can fix that.

FWIW, I think `fl_utf8back()` and maybe `fl_utf8fwd()` might be helpful to find the beginning of the previous or next character, respectively. There is very likely also a function that returns the size (number of bytes) starting at a particular byte in the string so one can make sure to always include a full UTF-8 character.

**Comment by erco77** [comment]
Attaching a patch suggestion [fluid_issue_858_patch.txt](https://github.com/fltk/fltk/files/13540667/fluid_issue_858_patch.txt) that fixes the problem by simply removing code.

As far as I can tell this works, letting truncation occur during item_draw(), and I don' t think Fl_Comment_Type even needs the title() overload (hence my removing it and the title_buf[] variable, which was wrongly sized for utf-8 strings anyway)

**Comment by Albrecht-S** [comment]
Fixing an issue by removing code. That looks promising. ;-)

Let's see what @MatthiasWM says, likely tomorrow (later today for us in Europe, it's now almost 2am here).

**Comment by MatthiasWM** [comment]
Oh, great find. And thanks for the patch.

**Comment by erco77** [comment]
Seems to work! Closing.
