### ISSUE TITLE
fluid: New>Code>Comments and New>Code>Declaration appear at wrong position in source code

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#859]
**Describe the bug**
I'm using New>Code>Comments to document like-methods in a class together, e.g.

![image](https://github.com/fltk/fltk/assets/6484779/e7c0f375-3a72-4e37-ab99-529df63502be)

..but in the generated source code, all these comments end up grouped together at the bottom of the class, all next to each other, and not above the methods they document, e.g.

![image](https://github.com/fltk/fltk/assets/6484779/e5fe35a2-d118-4537-ae70-cf65130d23b8)

This might be a problem limited to using these comments within the definition of a class, or how the scoping pulldown affects things.. I'm not sure.

I'll follow up with a .fl file to demonstrate the problem.

**Comment by erco77** [comment]
Attaching [test-fluid-v1.zip](https://github.com/fltk/fltk/files/13537106/test-fluid-v1.zip) that demonstrates the problem where e.g. the comments "SOME METHODS" and "OTHER METHODS" (created with New>Code>Comments) which are defined among the class's methods appear in the source code at the bottom of the class's constructor, instead of in with the method definitions.

I could see where perhaps I'm using comments in an unintended or unsupported way, though I suppose I'm not sure then how to use them.

**Comment by erco77** [comment]
Thanks -- definitely better!

There's still a few odd things, e.g. the ordering of these comments switches around -- where the red lines cross (green circle) shows where the comment ordering swaps around.. and some comments are still ending up in the middle of the ctor for some reason, seems to be between the user code (above comment) and auto-generated code (resizable/end below comment):

![image](https://github.com/fltk/fltk/assets/6484779/61fe75b6-ca69-43af-b357-e5fbb9c0842e)

**Comment by MatthiasWM** [comment]
Haha, yes, you immediately found the bug that I mentioned in the dos. If a comment follows a comment, this doesn't work. I can add that though...

**Comment by MatthiasWM** [comment]
Ok, I added a nice recursion, so you can have multipel comments in a row.
