### ISSUE TITLE
"fluid shell" output window needs larger scrollback history size (easily filled by compiler output)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#860]
**Describe the bug**
I have builds where the compiler output is much longer than fluid's 120 line shell history, preventing me from seeing the first error, which is often the most important.

The screen history size should probably be more like 1000 lines, possibly configurable in the Fluid Settings -> Shell screen.

**Comment by erco77** [comment]
Attaching a patch suggestion [fluid_history_1000_patch_v1.txt](https://github.com/fltk/fltk/files/13551941/fluid_history_1000_patch_v1.txt) that increases the history size to 1000.
- Patch also fixes a mismatch between the .fl and .cxx file with the escape sequence stuff (\e vs \033)
- I noticed when fluid loads the alignment_panel.fl in master, it prints this warning: 
  `alignment_panel.fl:1581: Unknown word ""`
  ..which seems to be some imbalanced braces in fluid's syntax.

**Comment by MatthiasWM** [comment]
Done.

**Comment by erco77** [comment]
Confirmed, closing.
