### ISSUE TITLE
Fluid: hitting ^O clears the current fluid file unconditionally (even if you hit Cancel)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#862]
**Describe the bug**
I was trying to set a shortcut for my app's File -> Open menu item by clicking the little shortcut circular arrow icon and hitting ^O, but fluid intercepted it as its own File -> Open.

**This effectively cleared away my app**, renamed it Untitled, and popped up a file browser in that order.
Hitting Cancel returns me to an empty fluid window, my app gone.. yikes.

There was _no data loss_ because the file had already been saved, but still it's disconcerting/scary to have the app get cleared before actually picking a file to open; hitting Cancel in the file chooser should have left me back where I was, as the ^O was accidental in this case.

So there's I think two problems here:

1. Fluid's own File -> Open should probably not clear the current app unless the user successfully picks a file

2. There might be a focus problem with the Properties -> Shortcut that I guess I don't remember encountering before; apparently it's not keeping focus, and lets the shortcut key leak out for fluid to handle as a shortcut.

**Comment by erco77** [comment]
Regarding item 2 above:

Apparently clicking the little circular arrow is the one thing you should NOT click when making a shortcut.

Clicking the white bar to the left creates the shortcut, putting the widget into "take focus" mode and turns the widget blue.
But if you click the circular arrow that's at the far right, it seems to be a dead zone, and doesn't trigger this mode, so it does nothing, even though it's inside the white bar.

As a user, it's kinda unclear how this widget works, actually, and what the circular arrow does.

I think the intention is the white field is to look like a "text input" field, and when you click it, it prompts in blue for the shortcut keys to press. That's fine I suppose. Perhaps if it said "Type the keys for your shortcut" when nothing is set yet, that'd help people know what to do.

But the circular arrow.. I'm assuming it's an Undo button to clear whatever shortcut is set (similar to hitting Backspace)?
If so, it should really be a separate button to the right of the field, with its own tooltip that says what it does. Or maybe instead a button that says "Clear"?

**Comment by MatthiasWM** [comment]
@erco77 Oh! It took me a while, but now I get it. You pressed Ctrl-O while the shortcut widget was till white. Yeah, my previous fix does not take that into account. I'll have to rethink the interface, maybe even put the reset option into a pulldown menu... .

**Comment by erco77** [comment]
Yes, right in your last comment.

The focus thing works fine, I was clicking the arrow which doesn't switch the widget around, but since I wasn't familiar with what it did when it worked correctly, I didn't know what wasn't working at first.

So yeah, I think the widget interface could be a bit clearer (see my suggs=suggestions), and as far as the ^O clearing the user's application, that's probably just a matter of doing the clear AFTER it's confirmed the user picked a file successfully, and didn't "Cancel".

**Comment by erco77** [comment]
I wanted to look into this a bit.

Apparently the UI issue in question is **Fl_Shortcut_Button**, an FLTK button class I guess I've never run into myself. It's not in the demos or examples, so perhaps it's new.

The icon symbol "↶" that I was hitting is a "return to default shortcut" icon, where I think if a default is set, then this button is drawn, and will actually be triggered if one clicks on it.. a button-in-a-button? 

I'd offer this could maybe be reimplemented as a group that contains two buttons, similar to the Fl_Input_Choice widget:

![image](https://github.com/fltk/fltk/assets/6484779/ba924ca1-0534-40b4-8195-db58b0b4c913)

- The left side of the group would be the white input field/button that turns blue when clicked to grab the shortcut, as it does now (No undo icon within that area)
- The right side of the group would be a regular button with the Undo icon in it, that when hit, restores the shortcut to a default. This button would push down like a regular button (so it's clear it's a button), could be deactivated by default, activated only when the user created a new shortcut different from the default. The activation state would clearly indicate there's something to "undo". This button could also have its own tooltip indicating what it does.

**Comment by MatthiasWM** [comment]
@erco77 Thanks for looking into this. The Fl_Shortcut_Button was in FLUID for a long time. I decided to move it into the core library, hoping that we will get a nice interface for people who like to offer custom menu shortcuts. 

The addition to offer restoring the previous/original/whatever shortcut was a bit of an enthusiastic spur-of-the-moment thing. Seeing that it leads to confusion, I think I overloaded this simple widget with too much functionality. I do not want to create a composite widget for such a minor feature, because composites come with a whole new list of issues. Instead, I will remove this functionality for 1.4.0 . 

We will have to talk about composite widgets for 1.5 anyway... .

**Comment by Albrecht-S** [comment]
I agree that it is probably useful to remove the undo/reset feature from the widget that is now in the core. You could still implement the extra reset button as Greg suggested.

> We will have to talk about composite widgets for 1.5 anyway... .

OT here, but yes, absolutely! There are so many issues...

**Comment by erco77** [comment]
Wait - the bug with ^O still exists (clears the UI even if user hits cancel in file browser)

**Comment by MatthiasWM** [comment]
Yes, I accidentally closed the issue. I am working on the Ctrl-O issue right now.

**Comment by MatthiasWM** [comment]
This should fix it. Sorry of the typos in the log message.

**Comment by erco77** [comment]
Confirmed your fix!

_I wasn't sure if you were gonna address it today, so I was gonna offer [fluid_ctrl-o-fix.diff.txt](https://github.com/fltk/fltk/files/13663339/fluid_ctrl-o-fix.diff.txt), but I see you addressed it already. Posting my patch here just for fun to see how different our mods were :^D_
