### ISSUE TITLE
--prefix with autoconf or CMAKE_INSTALL_PREFIX with cmake not honored

### ISSUE THREAD

**Issue by w5pny** [fltk/fltk#864]
When building the 1.3.9 release using either --prefix with autoconf or CMAKE_INSTALL_PREFIX with cmake 
things are put into /usr/local no matter what install directory is specified.

**Comment by Albrecht-S** [comment]
Thank you for your report. I have two questions though (I hope you can answer these):

1. Is this a regression, i.e. did (does) it work with the previous release (1.3.8)?
2. Can you tell if the same issue is in 1.4.0 (Git master branch)?

I'll try to reproduce the issue myself but if you could answer the questions above this would be helpful and very much appreciated. Thanks

**Comment by Albrecht-S** [comment]
Hmm, I tested this right now on Linux with configure and CMake and both work as expected, i.e. I can't confirm your issue. Are you sure you used a fresh install?

1. `./configure --prefix=/usr/local/fltk/branch-1.3-configure; make; (sudo) make install` works and installs correctly
2. `cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local/fltk/branch-1.3-cmake ../..; make; (sudo) make install` works as well.

If you double check and still have the issue, please report your full configure + build commands and - if applicable - any error messages.

Another question: is it possible that you have the environment variable `DESTDIR` set to `/usr/local`? What does `echo $DESTDIR` output?

Executing `DESTDIR=/usr/local make install` I can see that CMake would correctly install in `/usr/local` and configure/make would try to install in `/usr/local/usr/local` which is not correct but another issue than you reported. This needs further investigation.

**Comment by Albrecht-S** [comment]
Correction: I noticed now that both configure/make and CMake/make do the same thing: if I set DESTDIR this is used as and additional prefix before the given install prefix - which seems correct. I'm not really familiar with the DESTDIR semantics. Sorry for the confusion.

**Comment by w5pny** [comment]
DESTDIR is NOT set ...

After using autoconf the first time, I then tried using cmake
with the following build script:

#!/bin/bash
export CMAKE_INSTALL_PREFIX=/opt/fltk
export OPTION_BUILD_SHARED_LIBS=yes
mkdir build
cd build
script -c "cmake .." conf.log
script -c make make.log
script -c "sudo make install" install.log

That failed the same way.

So I just tried autoconf again, but I used the
autogen.sh script in the 1.3.9 directory.
That worked -- which means I must have only used autoconf
on my first attempt. 

Please go ahead and close this issue...

**Comment by Albrecht-S** [comment]
@w5pny I tried your script and it doesn't work like you tried it. Setting environment variables like `export CMAKE_INSTALL_PREFIX=/opt/fltk` and `export OPTION_BUILD_SHARED_LIBS=yes` doesn't work with our CMake files. Honestly, I never tried this. CMake is able to read env vars but this is not recommended. The right way to set CMake (cache) variables is to use the commandline with `-D CMAKE_INSTALL_PREFIX=/opt/fltk -D OPTION_BUILD_SHARED_LIBS=yes`. This is what I did after I read your first post, and it works as expected.

Please read `README.CMake.txt` for further advice on using CMake with FLTK. This is the recommended way to build. autoconf/configure/make is still supported in the upcoming release 1.4.0 but will be removed in 1.5.0.

That said, building with configure/make is not really well (and somewhat outdated) described in our online docs and in README.Unix.txt. If you want to use a standard build - using the official release tarball - you can either use
```
./configure --options...
make
```
or just run `make` w/o the configure step. FLTK supports configure to set a lot of options (see `./configure --help`) but you don't need to use it nor do you need to use autogen.sh explicitly (even if it is mentioned in the docs, it's optional).

I'm closing this now as requested.
