### ISSUE TITLE
Fl_Terminal::selection_text() sometimes hangs

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#866]
**Describe the bug**
Fl_Terminal::selection_text() is a protected method, but if you derive Fl_Terminal and just create a getter, it would sometimes hang. It seems to be occuring in Fl_Terminal::walk_selection().

**To Reproduce**
Build the following program with a FLTK master, then run.
```cpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Terminal.H>

struct Term: public Fl_Terminal {
    Term(int x, int y, int w, int h): Fl_Terminal(x, y, w, h, 0) {}
    const char *selection_text() const {
        return Fl_Terminal::selection_text();
    }
};

void cb(void *arg) {
    auto t = (Term *)arg;
    auto text = t->selection_text(); 
    if (text) puts(text);
    Fl::repeat_timeout(1.0, cb, t);
}

int main() {
    auto w = new Fl_Window(400, 300);
    auto t = new Term(0, 0, 400, 300);
    t->append("Hello world");
    w->end();
    w->show();
    Fl::add_timeout(1.0, cb, t); 
    return Fl::run();
}
```

The program will start printing the selected text to the console. Try modifying the selection a few times, it might print the selected text or it might hang.

**Expected behavior**
The program shouldn't hang.

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0 master
 - Downloaded and self-built from: git
 
**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
 - cmake -G"..." -DCMAKE_BUILD_TYPE=Debug -DFLTK_USE_WAYLAND=OFF -DFLTK_USE_PANGO=ON -DFLTK_USE_CAIRO=ON

**Operating System / Platform:**
Ubuntu 20.04 on WSL.

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by Albrecht-S** [comment]
I can confirm the issue and I also found the culprit. The bug happens when the selection has been made backwards (right to left or bottom to top).
I added some `::printf()` statements, and I got for a "backward selection" (see comments below):
```
1. Fl_Terminal::walk_selection(u8c:(nil), row:4353708, col:32767)
2. [1826] (u8c:0x59ce78, row:0, col:9, erow:0, ecol:3)
3. Fl_Terminal::walk_selection(u8c:0x59cf08, row:0, col:9)
4. Fl_Terminal::walk_selection(u8c:0x59cf18, row:0, col:10)
```

1. So far OK, starting walk_selection(), u8c is NULL, row/col undefined.
2. After about line https://github.com/fltk/fltk/blob/a20bace4e101d6e54bb190fa1ac55a8483f152e7/src/Fl_Terminal.cxx#L1820 I read and logged `erow` and `ecol` and it's obvious that `ecol < col`.
3. walking forward and
4. walking forward will loop infinitely.

@erco77 It would likely help to swap row/erow and col/ecol to walk forwards and terminate correctly or to walk backwards - I'm leaving a correct solution to you.

**Comment by erco77** [comment]
Thanks for the report.
Try the fix in current, 817966f.

**Comment by Albrecht-S** [comment]
@erco77 The fix works fine for me (I also checked the returned `erow` and `ecol` values.

@MoAlyousef Just for completeness (not for the actual demo program but for a "real" program): note that the caller must free the text returned from `selection_text()`. With that added to the demo program ASAN (address sanitizer) doesn't emit warnings.

Looks like we can close the issue?

**Comment by erco77** [comment]
Awaiting the OP to follow up + close, as he has an unusual use case (rust).

**Comment by MoAlyousef** [comment]
Thank you. It no longer hangs, but the selected text sometimes only shows only the first character of the selection.

**Comment by erco77** [comment]
Ah, checking the selection while it's in progress, good point.
OK, eedc5bdc0 should fix that.

**Comment by MoAlyousef** [comment]
Thank you. Works with both C++ and Rust :)
