### ISSUE TITLE
Memory leak in FL_Terminal?

### ISSUE THREAD

**Issue by F7F** [fltk/fltk#867]
Now that I'm using FL_Terminal with 1.4, I'm noting a memory leak with valgrind. On line 3150 of FL_Terminal.cxx the variable _current_style_ is created with **new** in init_(), but I don't see it being deleted in the destructor. It's only 40 bytes per terminal so not a big issue, but FYI.

**Comment by Albrecht-S** [comment]
Thank you for the report. Bug confirmed and fixed.
