### ISSUE TITLE
Compilation warnings (Fl_Shortcut_Button)

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#868]
Git current:
```
In file included from /Users/runner/work/fltk/fltk/src/Fl_Shortcut_Button.cxx:17:
/Users/runner/work/fltk/fltk/FL/Fl_Shortcut_Button.H:24:24: warning: private field 'default_set_' is not used [-Wunused-private-field]
  bool hot_, pre_hot_, default_set_, handle_default_button_;
                       ^
/Users/runner/work/fltk/fltk/FL/Fl_Shortcut_Button.H:26:15: warning: private field 'default_shortcut_' is not used [-Wunused-private-field]
  Fl_Shortcut default_shortcut_;
              ^
2 warnings generated.
```

@MatthiasWM ISTR that you commented out most of the default_shortcut stuff, hence I didn't want to **remove** these variables. Please check what to do.

**Comment by Albrecht-S** [comment]
Note: warning issued by CI build on macOS:
https://github.com/fltk/fltk/actions/runs/7228534279/job/19698129872

**Comment by MatthiasWM** [comment]
Yes, I kept these in the class, because I may want to add the functionality again later without changing the ABI. I'll check if initializing those variables will shut up the compiler.

**Comment by Albrecht-S** [comment]
Thanks, the fix is IMHO good, I'm not complaining ;-)

Just a note: the comment in the code says:
```
  // suppress warning on unused private members. I keep these around in case
  // we decide to activate this API again without changing the ABI.
```

Please keep in mind that we **can** change the ABI if we use the `FL_ABI_VERSION` macro to add new variables. It may turn out that we never add this feature again or that we need some other variables in the future, hence it is IMHO always questionable to add variables that **might** be used in the future.
