### ISSUE TITLE
#96bacd3 may crash on X11

### ISSUE THREAD

**Issue by tanxn5** [fltk/fltk#873]
96bacd3f9dff5b428a7826bbd507b1c02b2bcbba may lead to a crash if **USE_COLORMAP == 0**

function ```Fl_X11_Screen_Driver::open_display_platform()``` invoke ```open_display_i()``` cause reentrant.

 - OS: [Ubuntu 22.04]
 - X11

**Comment by Albrecht-S** [comment]
Thanks for the report. I can confirm the issue if I edit `config.h` like this after creation: `#define USE_COLORMAP 0`.

@tanxn5 I have two questions:
1. How do **you** achieve `USE_COLORMAP == 0` as you wrote above?
2. Just for my own curiosity: **why** do you do this?

**Comment by Albrecht-S** [comment]
@ManoloFLTK Here is an arbitrary excerpt of a backtrace after the crash (using 96bacd3f9dff5b428a7826bbd507b1c02b2bcbba):
```
#56273 0x000000000044f203 in Fl_X11_Screen_Driver::open_display_platform (this=0x523fa0) at /git/fltk/master/src/Fl_x.cxx:549
#56274 0x0000000000420502 in Fl_Screen_Driver::open_display (this=0x523fa0) at /git/fltk/master/src/Fl_Screen_Driver.cxx:551
#56275 0x000000000044801d in Fl_X11_Screen_Driver::visual (this=0x523fa0, flags=0) at /git/fltk/master/src/drivers/X11/Fl_X11_Screen_Driver.cxx:164
#56276 0x00000000004683e2 in Fl::visual (flags=0) at /git/fltk/master/src/Fl_visual.cxx:51
#56277 0x000000000044f924 in open_display_i (d=0x5332d0) at /git/fltk/master/src/Fl_x.cxx:621
#56278 0x000000000044f203 in Fl_X11_Screen_Driver::open_display_platform (this=0x523fa0) at /git/fltk/master/src/Fl_x.cxx:549
```

As you can see the frame numbers are greater than 50000.

**Comment by tanxn5** [comment]
> Thanks for the report. I can confirm the issue if I edit `config.h` like this after creation: `#define USE_COLORMAP 0`.
> 
> @tanxn5 I have two questions:
> 
> 1. How do **you** achieve `USE_COLORMAP == 0` as you wrote above?
> 2. Just for my own curiosity: **why** do you do this?

Oh, I modify configh.cmake.in for change USE_COLORMAP. Change that because FLTK app doesn't display my all Fl_PNG_Image draw in Windows Remote Desktop Client Screen. USE_COLORMAP = 1 could fix that.

**Comment by Albrecht-S** [comment]
@tanxn5 Thanks for the feedback. We always try to learn how our users use FLTK.

**Comment by ManoloFLTK** [comment]
This should be fixed with the commit mentioned above. @tanxn5 Please, close issue if you confirm.

**Comment by tanxn5** [comment]
It's OK.
