### ISSUE TITLE
Fl_Input pop menu customize doesn't work

### ISSUE THREAD

**Issue by tanxn5** [fltk/fltk#874]
after 7bef4ebf78061035540071ad1659d94e00ebfca9 Fl_Input has pop menu
Menu item text cannot change at run-time because rmb_menu is static. ```rmb_menu```  string pointers static.
```
/** [this text may be customized at run-time] */
const char *Fl_Input::cut_menu_text = "Cut";
/** [this text may be customized at run-time] */
const char *Fl_Input::copy_menu_text = "Copy";
/** [this text may be customized at run-time] */
const char *Fl_Input::paste_menu_text = "Paste";

static Fl_Menu_Item rmb_menu[] = {
  { Fl_Input::cut_menu_text,    0, NULL, (void*)1 },
  { Fl_Input::copy_menu_text,   0, NULL, (void*)2 },
  { Fl_Input::paste_menu_text,  0, NULL, (void*)3 },
  { NULL }
};
```

**Comment by ManoloFLTK** [comment]
@tanxn5 The commit mentioned above should fix this issue. Please, close issue if you confirm.

@MatthiasWM Do you agree with the above changes? Don't hesitate to proceed differently if you prefer.

**Comment by tanxn5** [comment]
@ManoloFLTK it works.  But a little problem:

according e466fe20c84ae17facd62c71de767603705be424 ```rmb_menu``` cannot update text after it init at Fl_Input ctor.  I think make ```rmb_menu``` as Fl_Input's public static member could be better. Thanks. Issue closed.

**Comment by MatthiasWM** [comment]
I am sorry that I can't reply very well ATM because I am traveling. I probably won't be able to look at the source code for a few days, but if there is an issue with this widget here, a similar issue should exists with Fl_Text_Display. They are very different widgets with the same feature, so code is duplicated there.
