### ISSUE TITLE
Wayland + full-size subwindow resizing issue

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#878]
**Description**
Under Wayland window resizing by border dragging doesn't work smoothly if an OpenGL subwindow fills the main window entirely.

_**EDIT:** as Manolo found out the issue is caused by a subwindow occluding the full size of the main window, no matter if it's a GL window or not._

It works well if either the subwindow's width or height (or both) are less than the main window's width or height, respectively.

**To Reproduce**
See attached demo program [opengl-resize.cxx](https://github.com/fltk/fltk/files/13779029/opengl-resize.cxx.txt). Build instructions are included (`fltk-config --use-gl --compile ...`).

1. Run program with "empty" commandline under Wayland
2. Drag border to resize
3. Window size does not follow the mouse pointer (after an initial small "jump")
4. Release the mouse button
5. Window resizes instantaneously to where the mouse was dragged.

The demo program supports two optional commandline arguments `dx` and `dy` to reduce the width and height of the subwindow, respectively. See below for usage.

**Expected behavior**
Window should resize smoothly while dragging the mouse as it does when using X11.

**FLTK Version**
 - Version: 1.4.0
 - Git master, commit 73bd4a53dd54c300ffa539f23a521083172d6253

**FLTK Configure / Build Options**
Default build with either CMake or configure/make.

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Debian 12 Stable (Bookworm)

**Linux/Unix Runtime, if applicable:**
 - Wayland
 - Desktop Gnome/Wayland
 - Mutter 43.6

**Additional context**
Use commandline arguments to set optional args:
1. dx > 0
2. dy > 0

It's sufficient to run with one argument set to '1' to see how resizing works smoothly.

Resizing works smoothly with full-size subwindow (dx=dy=0) with the X11 backend.

**Comment by Albrecht-S** [comment]
@ManoloFLTK I assigned this issue to you because it's a Wayland issue. I hope you don't mind.

I also noticed another tiny issue with this demo program (again under Wayland and not under X11): when the window is closed by clicking the close button the background shortly flashes in green which is the background color of the main window. This is unexpected and could be annoying on slow(er) systems and it seems to indicate that the main window is unnecessarily drawn after the subwindow has been unmapped, or something like this. While this is benign it would be good if we could avoid that extra drawing when closing the window.

Thanks in advance for looking into it.

**Comment by ManoloFLTK** [comment]
It's not GL-related: same problem with Fl_Window instead of Fl_Gl_Window.

**Comment by ManoloFLTK** [comment]
A Mutter bug? No problem resizing under KWin and under Weston (with or without GL subwindow).

**Comment by ManoloFLTK** [comment]
@Albrecht-S I believe this is a Mutter bug for the reason explained in the commit description. This commit adds an extra operation to each window resize under the Mutter Wayland compositor to protect the client app from the compositor bug. Please, report here whether you see the bug fixed.

I didn't yet look into the "other tiny issue".

**Comment by ManoloFLTK** [comment]
@Albrecht-S I believe the "other tiny issue" was also caused by the Mutter bug and disappears with the fix. Is that what you see too?

**Comment by Albrecht-S** [comment]
> Please, report here whether you see the bug fixed.

Yep, the main bug is fixed, thank you. Resizing is smooth even with the full-size subwindow. I didn't test with a normal Fl_Window but according to your commit description it's plausible that it doesn't make a difference. I just noticed the bug with the full size GL subwindow when trying a test program I "found" somewhere on my computer.

FTR: I'm currently using mutter 43.6 but my system offers 43.8 as "upgradable" version. I'll upgrade later, perhaps tomorrow, and I'll check 43.8 - with our previous FLTK version - to test if the bug persists in 43.8.

> I believe the "other tiny issue" was also caused by the Mutter bug and disappears with the fix. Is that what you see too?

No, unfortunately not. The "green flash" showing the main window's background is still visible when the window is closed. Do you have an idea to fix this as well? If not we could close the issue because it's not a real problem (just a tiny annoyance). I'll test this as well after upgrade to mutter 43.8, of course but we know that some of our users use even older mutter versions.

**Comment by ManoloFLTK** [comment]
I'm using here Debian testing with gnome-shell version 44.7, so I would believe 43.8 not to make a difference with 43.6.

**Comment by ManoloFLTK** [comment]
> I also noticed another tiny issue with this demo program (again under Wayland and not under X11): when the window is closed by clicking the close button the background shortly flashes in green which is the background color of the main window. This is unexpected and could be annoying on slow(er) systems and it seems to indicate that the main window is unnecessarily drawn after the subwindow has been unmapped, or something like this. While this is benign it would be good if we could avoid that extra drawing when closing the window.

This issue is not present with gnome 44.7, but I do see it with gnome 43.6. I monitored redraws of the main window adding a puts() when it occurs, and I saw the window closing adds no redraw operation. The green flash therefore is the main window's content showing after the subwindow is closed and before the main one is also closed. I don't think important to try and change that, all the more because it's fixed in recent Mutter versions.

**Comment by Albrecht-S** [comment]
OK, then let's close this issue. I'm not going to test anything more. Thanks.
