### ISSUE TITLE
When zooming window, the window size range must be adjusted

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#880]
**Describe the bug**
If a window has a size range (minimum size, maximum size), and the user zooms into the window using Ctrl-Shift-"+", the size range stays in host coordinates, but it should be adjusted to the zoom factor.

**To Reproduce**
Launch test/tile, resize to minimal size, zoom to 150%. We can make the window even smaller now, causing overlapping.

**Expected behavior**
The size range should adapt to the zoom factor.

**FLTK Version**
 - Version: 1.4.0
 - If from Git, branch: master

**Operating System / Platform:**
 - macOS Sonoma 14.2.1, Xcode 15.1

**Comment by Albrecht-S** [comment]
> the size range stays in host coordinates, but it should be adjusted to the zoom factor.

Good point. To clarify: the size range values stored in `Fl_Window` must not be changed but the size range values known to the OS or window manager must be modified and communicated to the OS or WM. The latter is obviously platform specific but very likely needed on all four current platforms (counting X11 + Wayland as two distinct platforms).

Issue confirmed on Linux.

**Comment by ManoloFLTK** [comment]
@MatthiasWM Please, close issue if you confirm it's fixed.

**Comment by MatthiasWM** [comment]
Perfect. Thank you!
