### ISSUE TITLE
Text selection with keyboard in Fl_Text_Editor stops working when left clicking inside selection 

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#885]
**Describe the bug**
Text selection with keyboard in Fl_Text_Editor stops working when left clicking inside selection 

**To Reproduce**
./editor editor.cxx
select text with keyboard or mouse
click inside selection and keyboard selection does not work until next selection with mouse
click outside selection and keyboard selection does work

**FLTK Version**
1.4.0 08e64283aacf0c26453c1be956bf15569b6d3585

**FLTK Configure / Build Options**
./configure --enable-use_std

**Operating System / Platform:**
Xubuntu 23.10

**Comment by MatthiasWM** [comment]
Great find. Thank you. I should be able to fix this tomorrow.

**Comment by MatthiasWM** [comment]
Should be fixed. We forgot to reset a flag. Please verify.

**Comment by erco77** [comment]
Super glad the OP identified the cause -- I kept running into this with the code editor in fluid (which is Fl_Text_Editor based), but never reported the bug officially 'cause I couldn't figure out how to replicate; it seemed to happen randomly, lol.

Thanks for the fix Matt.

**Comment by gnuwimp** [comment]
👍
