### ISSUE TITLE
Fl_Button.cxx::handle() has no explicit return for switch case FL_KEYUP

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#889]
A warning from build of Fl_Button.cxx in e0a334840d106bc1b569d3c85da5d623e66ef024:

```
.../apps/fltk/fltk-clone/src/Fl_Button.cxx: In member function ‘virtual int Fl_Button::handle(int)’:
.../apps/fltk/fltk-clone/src/Fl_Button.cxx:211:1: warning: control reaches end of non-void function [-Wreturn-type]
  211 | }
      | ^
```
This is a concern at least for switch case FL_KEYUP -- I think there is no explicit return in the code path for that case.

Linux Mint 21, g++ 11.4.0.

**Comment by MatthiasWM** [comment]
Thanks, missed that one.
