### ISSUE TITLE
Invisible mouse cursor when activating menu with the keyboard

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#890]
**Describe the bug**
If current mouse cursor is the insert cursor and you activate the menu with the keyboard (alt+key), the cursor is invisible.
If you press only the alt key the cursor will be shown.
Sometimes if you keep the alt key pressed the cursor will disappear.
Occasionally I have also managed to show the insert cursor in the menu.

**To Reproduce**
Tried in editor.exe and in menubar.exe.
Added one input widget to menubar.

```
  G_tty = new Fl_Terminal(0,400,WIDTH,TERMINAL_HEIGHT);
  new Fl_Input(0,300,WIDTH, 24);
```

**Expected behavior**
Normal mouse cursor should be visible in the menu area.

**FLTK Version**
1.4.0 31daa83f2b507e287725a7cf648ae5b51effbabf

**Operating System / Platform:**
Windows 10

![screenshot 21](https://github.com/fltk/fltk/assets/18072526/c031bf6b-64a6-4004-9f65-c628cd83d3f9)
![screenshot 22](https://github.com/fltk/fltk/assets/18072526/9743a935-8139-4de7-8abb-55daac3f8a9d)

**Comment by Albrecht-S** [comment]
@gnuwimp Thank you for the report, this is very much appreciated!

@MatthiasWM This is likely one for you?

**Comment by MatthiasWM** [comment]
Sorry, typo in the commit message. Too used to my old style.
