### ISSUE TITLE
Wayland: crash with set_menu_window()

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#892]
**Describe the bug**
Setting a window as "menu window" causes a crash with Wayland when the window is shown.

Note: How useful that is, is another topic, but on X11 this can be utilized to **not** show the minimize control in the titlebar.

**To Reproduce**
````cxx
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

int main()
{
	Fl_Window w(100, 100, 300, 200, "menu_window");
	Fl_Box b(0,0, w.w(), w.h());
	b.label("menu");
	w.set_non_modal();
	w.set_menu_window(); // crash with Wayland
	w.show();
	return Fl::run();
}
````

**Expected behavior**
Application should not crash.

**FLTK Version**
1.4 git current

**Linux/Unix Runtime, if applicable:**
- Ubuntu 20.04
 - Wayland

**Comment by ManoloFLTK** [comment]
That is fixed with commit ab8c844.

@Albrecht-S Please, close issue if you agree.

**Comment by wcout** [comment]
Initial crash is fixed.
But I get another crash if I use a tooltip in the window, when the tooltip is displayed.

e.g. in above program:

```cxx
b->tooltip("This a tooltip");
````

**Comment by ManoloFLTK** [comment]
@wcout Do you want to add a tooltip to a "pseudo" tooltip window created by calling `Fl_Window::set_tooltip_window()` that's documented as
> This is intended for internal use, but it can also be used if you write your own tooltip handling. However, this is not recommended.

? "Regular" tooltip windows do work OK. If you have a crash with them, please, clean and rebuild FLTK.

**Comment by wcout** [comment]
@ManoloFLTK I don't understand what you ask.
I just want to add a tooltip to a widget.
But it seems when the window where the widget is in is marked as menu_window(), then the display of the tooltip crashes.
I did a clean rebuild.

**Comment by ManoloFLTK** [comment]
> But I get another crash if I use a tooltip in the window, when the tooltip is displayed.

That should be fixed with commit above.

**Comment by wcout** [comment]
It is fixed! Thanks.
