### ISSUE TITLE
Wrong tooltip position on Wayland with secondary monitor

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#894]
**Describe the bug**
With 2-screen configuration, on the rightmost screen, tooltips are shifted to the right. On the leftmost screen tooltips position are correct.

**To Reproduce**
Launch `bin/test/tree` demo under Wayland and 2 screens, move the window to the rightmost screen, then hover mouse on the tree item. Tooltip will be shown shifted very much to the right (see screenshot).

**Expected behavior**
Tooptip shown under mouse cursor

**Screenshots**
![image](https://github.com/fltk/fltk/assets/6562863/8bbd6ecf-d176-469a-910b-4c4932ab3401)

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0 (latest master)
 - Downloaded and self-built from: master branch (commit `5cc5a60e096f96924e1409bb410a978db025876a`)

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Fedora 39

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by Albrecht-S** [comment]
@polter-rnd Thanks for the report.

Just for clarification: do you have any (system) screen scaling factors other than 1.0, and maybe also relevant: what are the screen coordinates and sizes of both screens? If you don't know, `test/fullscreen` may help...

@ManoloFLTK ?

**Comment by polter-rnd** [comment]
Thanks for quick reply. It is reproducible without any scaling. My screen configuration:

```
Screen 0: 1920x1080@0,0 DPI:96.0x96.0 scale:1.00
Work area 0: 1920x1080@0,0
Screen 1: 1920x1080@1920,0 DPI:96.0x96.0 scale:1.00
Work area 1: 1920x1080@1920,0
```

**Comment by ManoloFLTK** [comment]
@polter-rnd This should be repaired with the commit mentioned above. Please, close issue if you confirm.

**Comment by polter-rnd** [comment]
@ManoloFLTK Now X position is correct, but Y is wrong - the tooltip is shifted to the bottom, as on screenshot below 
![image](https://github.com/fltk/fltk/assets/6562863/a06ee0a7-72ca-45c9-86f2-5a020ffe1be4)

**Comment by ManoloFLTK** [comment]
Right. Commit 8a4aa61 should correct the Y position.

**Comment by polter-rnd** [comment]
Thanks, now it's correct!
