### ISSUE TITLE
Some missing cursors on wayland

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#895]
**Describe the bug**
Some FL_CURSOR_* cursors appear to be missing in wayland. Namely the cross, move, NS, WE cursors.
I'm not sure if it's an issue with my system (WSLg running ubuntu), the same program shows the correct cursors with FLTK_BACKEND=x11.

**To Reproduce**
Build the following program:
```cpp
#include <FL/Fl.H>
#include <FL/Enumerations.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>

void choice_cb(Fl_Widget *w, void *data) {
    auto *choice = (Fl_Choice *)w;
    auto *win = (Fl_Double_Window *)data;
    switch (choice->value()) {
        case 0: win->cursor(FL_CURSOR_DEFAULT); return; 
        case 1: win->cursor(FL_CURSOR_ARROW  ); return; 
        case 2: win->cursor(FL_CURSOR_CROSS  ); return; 
        case 3: win->cursor(FL_CURSOR_WAIT   ); return; 
        case 4: win->cursor(FL_CURSOR_INSERT ); return; 
        case 5: win->cursor(FL_CURSOR_HAND   ); return; 
        case 6: win->cursor(FL_CURSOR_HELP   ); return; 
        case 7: win->cursor(FL_CURSOR_MOVE   ); return; 
        case 8: win->cursor(FL_CURSOR_NS     ); return; 
        case 9: win->cursor(FL_CURSOR_WE     ); return; 
        case 10: win->cursor(FL_CURSOR_NWSE  ); return; 
        case 11: win->cursor(FL_CURSOR_NESW  ); return; 
        case 12: win->cursor(FL_CURSOR_N     ); return; 
        case 13: win->cursor(FL_CURSOR_NE    ); return; 
        case 14: win->cursor(FL_CURSOR_E     ); return; 
        case 15: win->cursor(FL_CURSOR_SE    ); return; 
        case 16: win->cursor(FL_CURSOR_S     ); return; 
        case 17: win->cursor(FL_CURSOR_SW    ); return; 
        case 18: win->cursor(FL_CURSOR_W     ); return; 
        case 19: win->cursor(FL_CURSOR_NW    ); return; 
    }
}

int main() {
    auto *win = new Fl_Double_Window(400, 300);
    auto *choice = new Fl_Choice(5, 5, 160, 30);
    choice->add("DEFAULT|ARROW|CROSS|WAIT|INSERT|HAND|HELP|MOVE|NS|WE|NWSE|NESW|N|NE|E|SE|S|SW|W|NW");
    win->end();
    win->show();

    choice->callback(choice_cb, win);
    return Fl::run();
}
```
Run the built app and change the cursor in the Fl_Choice widget.

**Expected behavior**
The wayland and xwayland cursor should be the same, all cursors should show correctly.

**Screenshots**

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed
by using CMake GUI tools (if any).
 - cmake -Bbin -GNinja -DCMAKE_BUILD_TYPE=Debug -DFLTK_BUILD_TEST=OFF && cmake --build bin && sudo cmake --install bin
 - fltk-config --compile main.cpp

**Operating System / Platform:**
 - OS: Ubuntu  22.04 running on WSLg on Windows 11

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by Albrecht-S** [comment]
Sorry for the short reply: what about the test/cursors.cxx program?

**Comment by MoAlyousef** [comment]
Hi @Albrecht-S 
I rebuilt FLTK with tests enabled, ran test/cursor and it's the same behavior.

**Comment by Albrecht-S** [comment]
I did a quick test and found that all cursors you mention explicitly are working well on my Debian/Gnome/Wayland system.

![image](https://github.com/fltk/fltk/assets/26235500/b747882a-8ea0-46c5-a96c-62d72e1cfc5e)

This screenshot shows the `WE` cursor. The NS and WE cursors differ from other cursors in that they have arrows with a green circle - which **might** indicate that they are theme specific. But this is only guessing, I'm just testing here.

Maybe @ManoloFLTK can tell more about which cursors are taken from what source or whatever...

**Comment by MoAlyousef** [comment]
I've created a video and sank into the rabbit hole trying to convert it to a gif with a reasonable file size. I'll just post the video:

https://github.com/fltk/fltk/assets/37966791/e163fa48-d4fc-438e-832f-b2eae395538d

**Comment by MoAlyousef** [comment]
I went thru the wayland driver code and it seems to look for a /usr/share/icons/XXXX/cursors/ dir:
https://github.com/fltk/fltk/blob/8a4aa619e418fb0d3804c335bd7a05e86280e9a5/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx#L1567

Apparently WSLg's ubuntu distro uses adwaita as a default theme, however it seems to lack such a directory. Installing the adwaita-icon-theme-full package via apt effectively populates the cursors dir and fixes the issue.

**Comment by ManoloFLTK** [comment]
FLTK constructs its Wayland cursors from the files of directory /usr/share/icons/XXXX/cursors/ where XXXX is the 'gnome cursor theme' (default= Adwaita). For example, what FLTK calls FL_CURSOR_INSERT corresponds to file xterm therein. The full correspondance between Fl_Cursor values and names of files therein is found in function Fl_Wayland_Window_Driver::set_cursor(Fl_Cursor).

The gnome-tweaks app allows to change the 'gnome cursor theme'.

When installing the gnome desktop under Ubuntu or Debian, package gnome-core installs many things among which adwaita-icon-theme-full.

@MoAlyousef I would believe this issue to be fixed and closable.

**Comment by MoAlyousef** [comment]
Yes. Thank you
