### ISSUE TITLE
Fltk rs cannot adjust window size after compilation in Windows and does not have a maximize button

### ISSUE THREAD

**Issue by li-yun-xian** [fltk/fltk#896]
But when compiled on the Linux platform, everything runs normally

**Comment by ManoloFLTK** [comment]
FLTK needs a top-level window to be assigned a resizable widget with function `Fl_Group::resizable(Fl_Widget*)` to get a maximize button and to be resizable. Once that is done, the window is resizable and has a maximize button both under Windows and Linux.

I don't know what happens in [FLTK-rs](https://github.com/fltk-rs/fltk-rs). You may want to open an issue there.
