### ISSUE TITLE
Constructing Fl_Anim_GIF_Image from memory returns invalid format

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#897]
**Describe the bug**
Fl_GIF_Image can be constructed from memory, however Fl_Anim_GIF_Image apparently returns `invalid format`. Using the other constructor which takes a filename works correctly.

**To Reproduce**
A minimal repro:
Build the following program:
```cpp
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Anim_GIF_Image.H>
#include <FL/Fl_GIF_Image.H>

int main() {
    auto *f = fopen("an-example.gif", "rb");
    fseek(f, 0, SEEK_END);
    auto sz = ftell(f);
    fseek(f, 0, SEEK_SET);

    auto *bytes = new unsigned char[sz];
    fread(bytes, sz, 1, f);
    fclose(f);
    auto *win = new Fl_Double_Window(400, 300);
    auto *box = new Fl_Box(0, 0, 400, 300);
    win->end();
    win->show();

    auto *i = new Fl_Anim_GIF_Image(NULL, bytes, sz);
    box->image(i);

    auto ret = Fl::run();
    delete[] bytes;
    return ret;
}
```

Copy a gif image to your pwd, rename it to an-example.gif. Run the program, it should print:
```
Fl_Anim_GIF_Image: (null) has invalid format.
```
And show nothing.

If you change Fl_Anim_GIF_Image to Fl_GIF_Image, it would work.
Also if you try `auto *i = new Fl_Anim_GIF_Image("an-example.gif");` it would work.

**Expected behavior**
Loading Fl_Anim_GIF_Image from memory should work.

**Screenshots**
N/A

**FLTK Version**
 - Version: 1.4
 - Downloaded and self-built from: Git
 - If from Git, branch: master

**FLTK Configure / Build Options**
 - cmake -Bbin -GNinja -DCMAKE_BUILD_TYPE=Debug && cmake --build bin

**Operating System / Platform:**
 - OS: WSLg running Ubuntu 22.04

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by erco77** [comment]
I found I could make the replication program work by making this small change:

```diff
-    auto *i = new Fl_Anim_GIF_Image(NULL, bytes, sz, box);
+    auto *i = new Fl_Anim_GIF_Image("xxx", bytes, sz, box);
```

Perhaps the internals need a name of some kind to associate with the bytes[] array.
In which case only the docs need to be changed or at least clarified, as currently the docs say the `imagename` can be NULL, presumably the only case that makes sense is when bytes is non-NULL.

**Comment by MatthiasWM** [comment]
Thanks @erco77 for checking this. I'll be happy to take a look at that tomorrow if the bug is not obvious.

**Comment by MoAlyousef** [comment]
Looking at the code, it seems Fl_Anim_GIF_Image::FrameInfo::load when given data, will just call Fl_GIF_Image::load (maybe repeatedly). And that uses the stored imagename which is attached to the data. Commenting out the check for name_, would only load a single frame.
So it seems Fl_Anim_GIF_Image imagename can't be NULL.

I'm not sure whether generating an automatic (arbitrary) name would be worth the changes or not. Maybe the docs just need updating to state the imagename can't be NULL.

**Comment by ImUrX** [comment]
just gonna say that its awesome the development is in here, i didnt expect this to be solved so quick :pleading_face:

**Comment by wcout** [comment]
This is easy to fix:

```diff
diff --git a/src/Fl_Anim_GIF_Image.cxx b/src/Fl_Anim_GIF_Image.cxx
index 155ec4ca2..281e4ef38 100644
--- a/src/Fl_Anim_GIF_Image.cxx
+++ b/src/Fl_Anim_GIF_Image.cxx
@@ -266,6 +266,7 @@ void Fl_Anim_GIF_Image::FrameInfo::dispose(int frame) {
 bool Fl_Anim_GIF_Image::FrameInfo::load(const char *name, const unsigned char *data, size_t length) {
   // decode using FLTK
   valid = false;
+  anim->ld(0);
   if (data) {
     anim->Fl_GIF_Image::load(name, data, length, true); // calls on_frame_data() for each frame
   } else {
@@ -1040,8 +1041,10 @@ bool Fl_GIF_Image::is_animated(const char *name) {
 bool Fl_Anim_GIF_Image::load(const char *name, const unsigned char *imgdata /* =NULL */, size_t imglength /* =0 */) {
   DEBUG(("\nFl_Anim_GIF_Image::load '%s'\n", name));
   clear_frames();
-  free(name_);
-  name_ = name ? fl_strdup(name) : 0;
+  if (name_ != name) {
+    free(name_);
+    name_ = name ? strdup(name) : 0;
+  }
 
   // as load() can be called multiple times
   // we have to replicate the actions of the pixmap destructor here
@@ -1054,7 +1057,7 @@ bool Fl_Anim_GIF_Image::load(const char *name, const unsigned char *imgdata /* =
   w(0);
   h(0);
 
-  if (name_) {
+  if (name_ || imgdata) {
     fi_->load(name, imgdata, imglength);
   }

```

The relevant change for this issue is only the last one (`if (name_ || imgdata)`), but if you are on it you could also add the other minor changes, which fix the special case that `load()` is called multiple times on the same object.

**Comment by wcout** [comment]
@erco77 
> I'm not myself familiar with this widget, but it really could use some example code, and perhaps even a fully working test/ or examples/ demo.

There are 4 programs in `examples/ ` that exercise various aspects of the widget:
```
animgifimage.cxx
animgifimage-simple.cxx
animgifimage-play.cxx
animgifimage-resize.cxx
```

**Comment by MoAlyousef** [comment]
The ability to pass NULL for imagename would be great.

**Comment by MatthiasWM** [comment]
Thanks for the patch @wcout . This should be fixed now.

**Comment by wcout** [comment]
@MatthiasWM 
Did you miss this diff?
```diff
 bool Fl_Anim_GIF_Image::FrameInfo::load(const char *name, const unsigned char *data, size_t length) {
   // decode using FLTK
   valid = false;
+  anim->ld(0);
   if (data) {
     anim->Fl_GIF_Image::load(name, data, length, true); // calls on_frame_data() for each frame
   } else {
````
What is it good for: If loading from the same `Fl_Anim_GIF_Image` object multiple times. If you encounter a bad image, which sets  `ld(ERR_FORMAT)`, subsequent `load()`'s will fail too otherwise.

**Comment by MatthiasWM** [comment]
Ah, makes sense now.
