### ISSUE TITLE
Problem with Fl_Window::default_size_range() + Fl_Widget::position()

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#901]
**Describe the bug**
If a window is assigned itself as resizable widget and is positioned in the display by a call to Fl_Widget::position(), its minimum width and height are computed erroneously by Fl_Window::default_size_range().

**To Reproduce**
1) Modify demo program hello.cxx, adding
  ```
window->resizable(window);
  window->position(100,100);
```
just after
`   window->end();`
 2. Run the modified hello program and attempt to resize the window: its height cannot be decreased.

**Expected behavior**
The minimal width and height of the window should be 100.

**FLTK Version**

 - Version: 1.4.0
 - If from Git, branch: master
 - If from Git, commit: most recent

**Operating System / Platform:**
The bug is cross platform

**Additional context**
The attached small patch is a proposed fix of the issue.
[default_size_range.patch](https://github.com/fltk/fltk/files/14192468/default_size_range.patch)

**Comment by Albrecht-S** [comment]
Thanks for the report and the patch.
... checking ...
Done, fixed in 1cf6fdfa8562fafa0566e1008f74ea94f71356e4.
