### ISSUE TITLE
Problems with rotated text and FL_COURIER

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#903]
**Describe the bug**
When I change the font to FL_COURIER, the text rotates weirdly.
I might be using this in a wrong way but I'm quite sure it used to work.
It does work with all FL_HELVETICA* and FL_TIMES* fonts.

**To Reproduce**
Labelfont changed in rotated_text.cxx.

```
  text= new Rotated_Label_Box(100,75,200,100,"Widget with rotated text");
  text->box(FL_FRAME_BOX);
  text->align(FL_ALIGN_BOTTOM);
  text->labelfont(FL_COURIER);

```

**Screenshots**
![rotated_text](https://github.com/fltk/fltk/assets/18072526/62c28660-051b-4661-b7c3-9d02f73c8094)

**FLTK Version**
Version 1.4.0 c83164fbcc7330ae7e2a8b6d1e5b4d32023109c7

**Operating System / Platform:**
Xubuntu 23.10

**Linux/Unix Runtime, if applicable:**
X11

**Comment by gnuwimp** [comment]
It does work properly in Windows so it is a X11 problem.

**Comment by Albrecht-S** [comment]
Thanks for the report, but I'm afraid I can't reproduce the effect. I also tried the modification posted by you above but this didn't show the effect.

We need more info from you.

- Which build system do you use (configure/make or CMake)?
- Please make sure that you build in a fresh build directory, particularly if you use configure/make and updated from Git
- if you use configure, please run `make distclean` and `make`
- Please post your `configure` or `CMake` command and the full configure log. We don't need the compilation    output, just the configure part.

Can you also produce the issue with the unmodified `test/rotated_text.cxx` ? Note that `FL_COURIER == 4` and the `Font` slider allows you to change the font interactively (move it to '4' to see FL_COURIER).

**Comment by gnuwimp** [comment]
I pulled a fresh version.
Ouch I didn't see the font slider but yes the bug is still there with the unmodified rotate.
I have uninstalled some packages with fonts so I might have a problem with my Ubuntu...

./configure --enable-use_std
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for pkg-config... /usr/bin/pkg-config
checking for a BSD-compatible install... /usr/bin/install -c
checking for nroff... /usr/bin/nroff
checking for doxygen... no
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking for windres... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking whether byte ordering is bigendian... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for sys/select.h... yes
checking for sys/stdtypes.h... no
checking whether we have the POSIX compatible scandir() prototype... yes
checking for vsnprintf... yes
checking for snprintf... yes
checking for strings.h... (cached) yes
checking for strcasecmp... yes
checking for strlcat... yes
checking for strlcpy... yes
checking for locale.h... yes
checking for localeconv... yes
checking for library containing pow... -lm
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for long long int... yes
checking for library containing dlsym... none required
checking for dlfcn.h... yes
checking for alsa/asoundlib.h... no
checking for jpeg_CreateCompress in -ljpeg... no
checking for gzgets in -lz... yes
checking for zlib.h... yes
checking for png_read_info in -lpng... yes
checking for png.h... yes
checking for libpng/png.h... yes
checking for png_get_valid in -lpng... yes
checking for png_set_tRNS_to_alpha in -lpng... yes
checking for pthread.h... yes
checking for pthread_create using -lpthreads... no
checking for pthread_create using -lpthread... yes
checking for pthread_create using -pthread... yes
checking whether we have PTHREAD_MUTEX_RECURSIVE... yes
checking how to run the C preprocessor... gcc -E
checking for X... libraries , headers 
configure: WARNING: These packages 'wayland-client>=1.18 wayland-protocols>=1.15 wayland-cursor xkbcommon  pangocairo' are required to build FLTK for wayland.
configure: WARNING: At least one of them is missing.
configure: WARNING: Continuing with --disable-wayland
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... no
checking for library containing dlopen... none required
checking for GL/gl.h... yes
checking for glXMakeCurrent in -lGL... yes
checking for glXGetProcAddressARB in -lGL... yes
checking for GL/glu.h... yes
checking for XineramaIsActive in -lXinerama... no
checking for FcPatternCreate in -lfontconfig... yes
checking for X11/Xft/Xft.h... yes
checking for XftDrawCreate in -lXft... yes
checking for X11/extensions/Xfixes.h... no
checking for X11/Xcursor/Xcursor.h... no
checking for X11/extensions/Xrender.h... yes
checking for XRenderQueryVersion in -lXrender... yes
checking for X11/Xregion.h... yes
checking if GCC supports -fno-exceptions... yes
checking if GCC supports -fno-strict-aliasing... yes
checking if ld supports -no-undefined... yes
checking if ld supports -Bsymbolic-functions... yes
checking if toolchain supports sections... yes

Configuration Summary
-------------------------------------------------------------------------
    Directories: prefix=/usr/local
                 bindir=${exec_prefix}/bin
                 datadir=${datarootdir}
                 datarootdir=${prefix}/share
                 exec_prefix=${prefix}
                 includedir=${prefix}/include
                 libdir=${exec_prefix}/lib
                 mandir=${datarootdir}/man
    Build fluid: YES
Cross-compiling: NO
       Graphics: X11 + Xft + Xrender
Image Libraries: JPEG=Builtin
                 PNG=System
                 ZLIB=System
Forms library:   YES
    Large Files: YES
         OpenGL: YES
        Threads: YES
   Allow std:: : YES
configure: creating ./config.status
config.status: creating makeinclude
config.status: creating fltk.list
config.status: creating fltk-config
config.status: creating fltk.spec
config.status: creating FL/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: creating FL/fl_config.h

**Comment by Albrecht-S** [comment]
@gnuwimp OK, thanks for the log. I don't see anything wrong with it except that you are missing some of the optional Xlib packages:
```
- libxcursor-dev   recommended, needed to display some cursor
- libxext-dev      recommended
- libxinerama-dev  optional, used for multi-screen displays
```

> I have uninstalled some packages with fonts so I might have a problem with my Ubuntu...

That may explain it. Or not, I don't know. You could try other FLTK programs, e.g. `test/utf8.cxx` and `test/fonts.cxx` but I don't know if this could help.

AFAICT FLTK chooses a replacement font if the named font can't be found but I'm not familiar with this font  stuff. Maybe someone else can help. @ManoloFLTK, @MatthiasWM ?

**Comment by MatthiasWM** [comment]
Hmm, xft does the rotation. If for some reason you are not using xft, or your font is not recognized as xft compatible, fltk falls back to x11. The easiest would be to set breakpoints in `void Fl_Xlib_Graphics_Driver::draw_unscaled(int angle, const char *str, int n, int x, int y)` and `void Fl_Xlib_Graphics_Driver::draw_unscaled(int angle, const char *str, int n, int x, int y)` and trace where the code goes. Maybe it's an xft thing for weird font formats?

I saw that in `XftFont* fontopen(const char* name, /*Fl_Fontsize*/double size, bool core, int angle)`, fonts that are specified with the XLFD format (-*-*-*...), there seems to be code missing to rotate the font!? https://github.com/fltk/fltk/blob/a7bc26e12a43cbf01ec56e90bc6a3f9e3da9d724/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_font_xft.cxx#L643

**Comment by gnuwimp** [comment]
I tried the same code on my laptop with Xubuntu 22.04 and that worked as it should.
Then I added the missing libraries (libcursor, libxext, libxinerama) to my Xubuntu 23.10 computer but that did not help.

When I looked through some code in the driver section, which I dont understand at all, I did see there were two version of draw_unscaled(). One was for pango so I turned on pango and that did work. Although pango dependency are quite heavy. And slow for text rendering.

So either has ubuntu changed its libraries or I have mismanaged my machine somehow. But it is only 2 months to next major version so no worries. 

If you cant reproduce the bug, then please close it.

**Comment by MatthiasWM** [comment]
I can't run Xubuntu here on my ARM machine. It still feels like we are finding a bad font, so the rotation center is off. You could try to replace the Courier font by another, similar font with Fl::set_font(); https://www.fltk.org/doc-1.4/group__fl__attributes.html#ga15dee80a622a9ab2798acfdc0aabcd95

**Comment by Albrecht-S** [comment]
@MatthiasWM The OP's screenshot shows that the font appears to be not only misplaced but **_also mirrored_**. The latter would be weird by itself, no matter which font was used. I'm not going to investigate further because I assume that the OP assumes correctly that they misconfigured their OS (fonts). Whatever it was that causes such issues.

**Comment by gnuwimp** [comment]
Yeah I'm not sure my X11 is feeling ok.
I tried several mono fonts, all failed but one "Fira Code". Although does look like a mono font it has a spacing called "Dual Width". Other fonts have either "Proportional" or "Monospace" (using Font Manager).
I have to do a reinstall some day so I'm closing this issue for now.
