### ISSUE TITLE
Desktop keyboard shortcuts stop working after displaying a menu in a FLTK app

### ISSUE THREAD

**Issue by abau** [fltk/fltk#904]
**Describe the bug**

I defined several keyboard shortcuts in my KDE desktop environment, e.g., Meta+Shift+C for closing or Meta+Enter for maximizing the active window. When running a FLTK application, they work as expected until a menu is displayed anywhere within the running application. After that, pressing any of these shortcuts does not trigger an action anymore.

**To Reproduce**

0. Define some desktop-wide keyboard shortcut for closing the active window
1. Check out current `master` branch
2. Build FLTK
3. Run `test/menubar`
4. Click on any item in the top menubar so that the respective menu opens
5. Close the open menu by clicking anywhere within the application
6. Try closing the application using your desktop-wide keyboard shortcut defined above

**Expected behavior**

Desktop-wide shortcuts should always work.

**FLTK Version**

Git-commit `809ceea075d0636263de2db7e35735555c151d67` on `master` branch.

**FLTK Configure / Build Options**

No build options were set, I just ran `make`.

**Operating System / Platform:**

 - OS: Arch Linux on `6.7.3-arch1-2` kernel
 - Desktop environment: KDE Plasma Desktop 5.27.10-1 using X11

**Comment by ManoloFLTK** [comment]
OK. I can reproduce the issue, namely with KDE's default close window shortcut Alt-F4.

FYI: the problem does not occur with KDE+Wayland.

**Comment by ManoloFLTK** [comment]
@abau The commit mentioned above should fix this issue. Please, close issue if you confirm.

**Comment by abau** [comment]
Works fine. Thanks!
