### ISSUE TITLE
Menu popup floats above other wayland windows on xwayland

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#907]
**Describe the bug**
This is in relation to the fltk-rs issue:
https://github.com/fltk-rs/fltk-rs/issues/1517
and the following discussion in fltk-general:
https://groups.google.com/g/fltkgeneral/c/hEoiB93usnM

Where if you run an FLTK application built for X11 on a wayland system, i.e. using FLTK_BACKEND_X11 which fltk-rs does by default unless wayland support is explicitly passed via a feature flag, the menu popup floats above other wayland-native windows.

**To Reproduce**
I'm guessing building any app with a menubar like the examples menubar-add.cxx will exhibit the issue.

Open the menu then drag an native wayland window and the menu popup will float above it.

**Expected behavior**
The menu popup should disappear once another window is clicked.

**Screenshots**
A video can be seen here:
https://github.com/fltk-rs/fltk-rs/issues/1517

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master

**FLTK Configure / Build Options**
 - cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Debug -DFLTK_BACKEND_X11=ON

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: Linux
 - OS Version: Ubuntu 22

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
I believe that's the way the gnome Wayland desktop supports X11 client apps. FLTK does nothing special for menu windows, it's an X11 client as any other. An example:
- run Synaptic, the well known package manager GUI app; it's still built as an X11 client app; and it's not an FLTK app;
- open its "Help" menu
- drag a terminal window, which is a Wayland client, above your Synaptic window: it will slip between the Synaptic and its menu windows.

@MoAlyousef Why not having fltk-rs run as a Wayland client by default, just like FLTK does starting with version 1.4 ? A switch could allow to turn to X11 mode if strictly necessary for a specific app.

**Comment by MoAlyousef** [comment]
@ManoloFLTK:
Not necessarily. It’s just more difficult using the Rust build system to declare optional dependencies. Technically it’s still possible to shell out to pkg-config and the likes, but Cargo build scripts don’t offer things like CMake’s find_package(). It’s also more difficult to pass those as defines to Rust source files. 
It’s currently possible to build fltk-rs using an fltk-config feature which will shell out to fltk-config and determine the FLTK needed libraries. I plan to make fltk-rs build hybrid apps by default once FLTK releases 1.4, regardless of availability on linux distros. This should make default builds and builds using fltk-config similar and would simplify the build process.

**Comment by ManoloFLTK** [comment]
@MoAlyousef I'm not familiar with what Cargo is and does. Anyway, for this issue, I believe nothing can be done within FLTK to change how gnome processes X11 popup windows mixed with Wayland windows. Since you write "I plan to make fltk-rs build hybrid apps by default once FLTK releases 1.4, regardless of availability on linux distros.", that means the issue will disappear as soon as FLTK 1.4 is released.  If you agree, I would believe you could close the issue.

**Comment by MoAlyousef** [comment]
Thank you for confirming it’s an issue with X11 popus running on wayland.
