### ISSUE TITLE
Who is responsible for deleting an Fl_Widget image/deimage ?

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#91]
When an image/deimage has been applied to a Fl_Widget label, who is responsible for deleting that image?

I don't see any explicit cleanup of images in any of the examples, and I don't see any cleanup of the `label_.image` / `label_.deimage` in the `Fl_Widget` dtor.

Using FLTK 1.4-20200612-e43dee9d, Windows 10 x64, Visual Studio 2019.

**Comment by Albrecht-S** [comment]
Standard answer:

This is the wrong place to ask questions about building or running programs built with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by Albrecht-S** [comment]
That said, your program is responsible, there is no transfer of ownership. FLTK mostly stores just pointers, and this is documented, it's basically the same as with label() and copy_label().

There is PR #3 though that requests a `copy_image()` and `copy_deimage()` method. The prerequisites mentioned in https://github.com/fltk/fltk/pull/3#issuecomment-451755987 are now fulfilled in master and I intend to work on this PR soon.

WRT the demo programs: there's typically no need to destroy images on exit, but it may be useful if you create and destroy widgets often during the execution of a program. But I know you know that. :-)

**Comment by fire-eggs** [comment]
Sorry for posting here, but I consider this a bug - either in the code, the samples, or the documentation.

In the case of an image, on the Windows platform, FLTK does not store "just a pointer". An HBITMAP GDI resource is created to cache the image. Unless the image is explicitly deleted, this HBITMAP resource is not deleted, resulting in a GDI resource leak.

Since the documentation doesn't state so, and the samples do not illustrate so, I believe a  neophyte user is not going to be aware of this situation on Windows.

But I will move to fltk.general.

**Comment by Albrecht-S** [comment]
> In the case of an image, on the Windows platform, FLTK does not store "just a pointer". An HBITMAP GDI resource is created to cache the image. Unless the image is explicitly deleted, this HBITMAP resource is not deleted, resulting in a GDI resource leak.

This (i.e. the question about a GDI resource leak) is really interesting. Please move this to fltk.general as well - or maybe this is a question for fltk.coredev ?

WRT "just a pointer": what I meant was that FLTK stores only a pointer to the `Fl_Image` **object**, it does not aquire ownership and does not take responsibility for deleting the image object. Technically this does not mean that FLTK does not use internal caches for drawing the image (or not) ...
