### ISSUE TITLE
Should Fl_Terminal::clear() turn off attributes?

### ISSUE THREAD

**Issue by jgriffitts** [fltk/fltk#911]
**Describe the bug**
If `Fl_Terminal_clear()` is called when attributes are on (bold, dim, underline), they are left on in the cleared background screen.

**To Reproduce**
```
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Terminal.H>

Fl_Double_Window* win = 0;
Fl_Terminal* term = 0;

int main(int argc, char** argv) {
    win = new Fl_Double_Window(900, 320, "App");
    win->begin();
    term = new Fl_Terminal(0, 0, win->w(), win->h());
    win->end();
    win->resizable(win);
    win->show(argc, argv);

    term->textbgcolor_xterm(0);
    term->textattrib(Fl_Terminal::BOLD);
    term->append("Bold text that will immediately be erased.\n");

    term->clear();
    term->textattrib(Fl_Terminal::NORMAL);
    term->append("Non-bold text");
    return Fl::run();
}
```
**Expected behavior**
Expect a black background through the entire terminal. Instead, in this test case, the background is light gray because it is being "bolded". If UNDERLINE had been on before the clear(), it would be on throughout the empty parts of the terminal.

**Screenshots**
![image](https://github.com/fltk/fltk/assets/246411/fc0c8ee4-6f0c-49c5-95c5-f651322a2f3b)

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0, pulled from github.com/fltk/fltk, commit 00cdb17
 - Compiled using VS 2022 on Windows 10 Pro using cmake, default x64-Debug config
 - Run on Windows 10 Pro build 19045
 - Intel Core i5-7500 CPU

-----
_** Side note: **_
The doc for `Fl_Terminal::textcolor()` states:

>   Colors set this way will NOT be influenced by the xterm Dim/Bold color intensity attributes.
>  For that, use textcolor_xterm() instead.

**_As far as I can tell, there is no `textcolor_xterm()` function._**

**Comment by erco77** [comment]
Addressed the screen clear issue in eb4916344.

Will deal with the new textcolor_xterm() reference in the docs separately; not sure if that's a doc error and should be textfgcolor_xterm(), or if I need to create a new method that sets both the textfgcolor and the defaultcolor. Probably the latter, but wanna think about that one.
