### ISSUE TITLE
`fl_height(int, int)` decreases the font size after each call

### ISSUE THREAD

**Issue by KyrietS** [fltk/fltk#915]
**Describe the bug**
On WIndows when scaling is set to 125% the call to [`fl_height(int, int)`](https://www.fltk.org/doc-1.4/group__fl__attributes.html#ga0196d8e99a0dced827edf1ef569ee2fe) decreases the size of a current font.

**To Reproduce**
I've made a minimal example with reproduction: https://github.com/KyrietS/fltk-bug

IMPORTANT: I reproduced this bug on Windows (GDI driver) with 125% scaling. With scaling 100% or 150% this bug is not visible.

```cpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/fl_draw.H>
#include <iostream>

struct MyWidget : Fl_Widget
{
    MyWidget(int x, int y, int w, int h, const char* label) : Fl_Widget(x, y, w, h, label) {}
    virtual ~MyWidget() = default;

    void draw() override
    {
        fl_rectf( x(), y(), w(), h(), FL_BACKGROUND_COLOR );
        fl_color( FL_FOREGROUND_COLOR );
        fl_font( FL_HELVETICA, FL_NORMAL_SIZE );


        const char firstLine[] = "First line";
        const char secondLine[] = "Second line";

        fl_draw( firstLine, 50, 100 );
        fl_draw( secondLine, 50, 100 + fl_height());

        fl_draw( firstLine, 130, 100 );

        // The font becomes smaller after each call to fl_height
        std::cout << fl_size() << ", " << fl_height() << std::endl; // prints: 13, 15
        fl_height( FL_HELVETICA , FL_NORMAL_SIZE );
        std::cout << fl_size() << ", " << fl_height() << std::endl; // prints: 12, 14
        fl_height( FL_HELVETICA , FL_NORMAL_SIZE );
        std::cout << fl_size() << ", " << fl_height() << std::endl; // prints: 12, 13
        fl_height( FL_HELVETICA , FL_NORMAL_SIZE );
        std::cout << fl_size() << ", " << fl_height() << std::endl; // prints: 12, 13
        fl_height( FL_HELVETICA , FL_NORMAL_SIZE );
        std::cout << fl_size() << ", " << fl_height() << std::endl; // prints: 12, 13

        fl_draw(secondLine, 130, 100 + fl_height());
	}
};

int main()
{
    auto* window = new Fl_Window( 300, 300 );

    auto* myWidget = new MyWidget(25, 25, 50, 50, "mywidget");

    window->show();

    return Fl::run();
}
```

**Expected behavior**

The `firstLine` and `secondLine` should be drawn with the same size.

**Screenshots**
![image](https://github.com/fltk/fltk/assets/19170699/186359bd-7519-42a1-8f44-80dc2ecc0f32)

**FLTK Version**
master branch

**FLTK Configure / Build Options**
See CMakeLists.txt in my reproduction repo: https://github.com/KyrietS/fltk-bug

**Operating System / Platform:**
Windows 10 / Window 11 with: Display settings -> Scale and layout -> 125%

**Additional context**
The documentation of [`fl_height()`](https://www.fltk.org/doc-1.4/group__fl__attributes.html#gac4acb828270adf35bf1d8fc06051f938) says:

> You can also use the value of size passed to [fl_font()](https://www.fltk.org/doc-1.4/group__fl__attributes.html#gad234d90fe63191609ec196e1b8041d1a).

I don't understand why this statement is there. The size passed to `fl_font(face,fsize)` is not the same thing as a font height returned by `fl_height()`. Just call `fl_font( FL_HELVETICA, 14);` and then print the value of `fl_size()` and `fl_height()`. On my PC I get `14` and `16` printed. It depends on the scaling settings. I thing the statement from the docs above is very misleading.

**Comment by ManoloFLTK** [comment]
@KyrietS Thanks for this finding. The issue should be fixed with the commit mentioned above. Please, close issue if you confirm it's fixed.

**Comment by KyrietS** [comment]
Thank you for fixing it so fast! I can confirm that it works as expected now 👍
