### ISSUE TITLE
[Bug] FLTK 1.4 FL_MENU_TOGGLE and FL_MENU_RADIO items do not update in sys menu bar on Mac via shortcut

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#916]
**Describe the bug**
On Mac, FL_MENU_TOGGLE and FL_MENU_RADIO menu items in the sys menu bar do not have their checkmark updated when the menu option is triggered via keyboard shortcut. The parent menu also does not "flicker". The menu item's callback is invoked and its internal state (`value()`) is updated, but the menu item's appearance in the sys menu bar is not updated. This worked correctly in FLTK 1.3.9.

**To Reproduce**
Apply this diff to test/menubar.cxx and `make`:

```diff
diff --git a/test/menubar.cxx b/test/menubar.cxx
index e46a60be0..402a26fdf 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -108,10 +108,10 @@ Fl_Menu_Item menutable[] = {
     {"Size",        0,           0},
     {0},
   {"&Checkbox",FL_F+3,0,0,FL_SUBMENU},
-    {"&Alpha",  FL_F+2, 0, (void *)1, FL_MENU_TOGGLE},
-    {"&Beta",   0,      0, (void *)2, FL_MENU_TOGGLE},
-    {"&Gamma",  0,      0, (void *)3, FL_MENU_TOGGLE},
-    {"&Delta",  0,      0, (void *)4, FL_MENU_TOGGLE|FL_MENU_VALUE},
+    {"&Alpha",  FL_COMMAND+'a', 0, (void *)1, FL_MENU_TOGGLE},
+    {"&Beta",   FL_COMMAND+'s',      0, (void *)2, FL_MENU_TOGGLE},
+    {"&Gamma",  FL_COMMAND+'d',      0, (void *)3, FL_MENU_TOGGLE},
+    {"&Delta",  FL_COMMAND+'f',      0, (void *)4, FL_MENU_TOGGLE|FL_MENU_VALUE},
     {"&Epsilon",0,      0, (void *)5, FL_MENU_TOGGLE},
     {"&Pi",     0,      0, (void *)6, FL_MENU_TOGGLE},
     {"&Mu",     0,      0, (void *)7, FL_MENU_TOGGLE|FL_MENU_DIVIDER},
@@ -121,10 +121,10 @@ Fl_Menu_Item menutable[] = {
     {"000",     0,      0, (void *)1, FL_MENU_TOGGLE},
     {0},
   {"&Radio",0,0,0,FL_SUBMENU},
-    {"&Alpha",  0,      0, (void *)1, FL_MENU_RADIO},
-    {"&Beta",   0,      0, (void *)2, FL_MENU_RADIO},
-    {"&Gamma",  0,      0, (void *)3, FL_MENU_RADIO},
-    {"&Delta",  0,      0, (void *)4, FL_MENU_RADIO|FL_MENU_VALUE},
+    {"&Alpha",  FL_COMMAND+'A',      0, (void *)1, FL_MENU_RADIO},
+    {"&Beta",   FL_COMMAND+'S',      0, (void *)2, FL_MENU_RADIO},
+    {"&Gamma",  FL_COMMAND+'D',      0, (void *)3, FL_MENU_RADIO},
+    {"&Delta",  FL_COMMAND+'F',      0, (void *)4, FL_MENU_RADIO|FL_MENU_VALUE},
     {"&Epsilon",0,      0, (void *)5, FL_MENU_RADIO},
     {"&Pi",     0,      0, (void *)6, FL_MENU_RADIO},
     {"&Mu",     0,      0, (void *)7, FL_MENU_RADIO|FL_MENU_DIVIDER},
@@ -251,9 +251,9 @@ int main(int argc, char **argv) {
   menus[2] = &ch;
   Fl_Menu_Button mb(0,0,WIDTH,400,"&popup");
   mb.type(Fl_Menu_Button::POPUP3);
-  mb.menu(menutable);
-  mb.remove(1); // delete the "File" submenu
-  mb.callback(test_cb);
+  //mb.menu(menutable);
+  //mb.remove(1); // delete the "File" submenu
+  //mb.callback(test_cb);
   menus[3] = &mb;
   Fl_Box b(200,200,200,100,"Press right button\nfor a pop-up menu");
   window.resizable(&mb);
```

This adds some typical shortcuts to the checkbox menu items and radio menu items, and removes the right-click popup menu (so that it does not hog keyboard shortcut events).

1. Apply the above diff and `make`
2. Run `./test/menubar`
3. Use shortcuts, like CMD+A, SHIFT+CMD+A, etc.
4. Click on the "Checkbox" or "Radio" menus and see that the checkmarks to the left of the labels have not updated, despite the terminal reporting that the shortcuts have been detected.

**Expected behavior**
The "Checkbox" and "Radio" menus should "flicker" and their menu item checkmarks should update when the menu items are triggered by their shortcut.

**Video**

The first half of this video shows this behavior working _correctly_ on FLTK 1.3.9 (same patch from above applied).

The second half of this video shows the bugs present in FLTK 1.4.0.

https://github.com/fltk/fltk/assets/5231310/080eee9d-9b7f-4a03-b079-c2da0dd8e498

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 2f343ad

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed
by using CMake GUI tools (if any).
 - `./autogen.sh && make`

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: maxOS
 - OS Version: macOS 11.4
 - Processor if relevant: Intel

**Comment by ManoloFLTK** [comment]
@dannye  That should be fixed with the commit mentioned above. Please, close issue if you confirm.

**Comment by dannye** [comment]
Yes, looks good now, thank you very much.
