### ISSUE TITLE
Compilation error due to comparing -1 with unsigned integer

### ISSUE THREAD

**Issue by jputcu** [fltk/fltk#92]
With the latest gcc-10.1 compiler on Windows 10 in MSYS2 environment, using the 1.3.5 tag, I get a compilation error:
`error: narrowing conversion of '-1' from 'int' to 'long unsigned int' [-Wnarrowing]` on following locations:
* `fluid\ExternalCodeEditor_WIN32.cxx:141:13`
* `fluid\ExternalCodeEditor_WIN32.cxx:512:15`
Indeed, the member function in the switch returns a DWORD (unsigned int) and is compared to a **-1**.

**Comment by erco77** [comment]
Thanks -- I'll investigate; that's my code.
*Sigh* too bad MS didn't call it UDWORD, lol.

**Comment by erco77** [comment]
OP, will you be available to test?
I only have Visual Studio available at this time; want to make sure it compiles OK on MSYS.
Fix will take some time, as I also have to make symmetrical changes to the unix code, and then test on all three platforms with external editors. Might not be until later today..

**Comment by jputcu** [comment]
Sure

**Comment by erco77** [comment]
When you get a chance: clone 1.4.x and see if you can build it up to that same point of failure. (I just want to be sure you can actually build 1.4.x)
I'll then give you a commit# for 1.4.x that should fix the unsigned issue.
Once that works, I'll back port the mods to 1.3.x for you, so you can have it in 1.3.x.

**Comment by erco77** [comment]
I committed to a branch called "issue92" in fltk 1.4.x
So check that out and give it a try. Should solve the error. I was able to test with VS2017 + Unix, and was able to install msys2 + gcc 10.1 and do a build/run test using cmake.

**Comment by jputcu** [comment]
Using the `issue92` branch I was able to build without errors. I only had some undefined references in my example application which is missing some libraries, probably due to the switch from 1.3 to 1.4.
Thanks for the quick fixing.

**Comment by erco77** [comment]
Fixed in commit db07cea7580fbe6a92a62c9045e8877827d73d61

**Comment by erco77** [comment]
(BTW, this fix has now been backported to branch-1.3, commit a0caebb66353f5a2fbee0a2b70a770e51c2aac11)
