### ISSUE TITLE
Fl_Window::fullscreen() does not work correctly on Mac

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#920]
**Describe the bug**
This issue is not new to FLTK 1.4. It is present in FLTK 1.3 as well.

There are 2 major issues:

1. When Fl_Window::fullscreen() is used on Mac, pressing the mouse cursor against the top edge of the screen does not pull down the system menu bar. This makes accessing the menu impossible until full screen mode is exited.
2. If native OS full screen is already active (the green button in the window title bar), and then Fl_Window::fullscreen() is called, the application crashes.

**To Reproduce**
The issues can be observed in the default test/fullscreen program.

1. Compile the default test programs
2. Run test/fullscreen
3. Click the "FullScreen" button to enter fake full screen mode
4. Notice that pressing the cursor against the top edge of the screen does not pull down the menu bar
5. Click the "FullScreen" button to exit fake full screen mode
6. Click the green button in the window title bar to enter real full screen mode
7. Notice that pressing the cursor against the top edge of the screen does correctly pull down the menu bar
8. Click the "FullScreen" button to enter fake full screen mode while in real full screen mode
9. Notice the application has crashed

**Expected behavior**
Fl_Window::fullscreen() and Fl_Window::fullscreen_off() should function identically to the green full screen button in the window title bar, ie. it should call [toggleFullScreen](https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen) or similar.

**Video**

https://github.com/fltk/fltk/assets/5231310/c6466f4c-45a1-4c6c-9598-bee39db8f2ed

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: f288aea

**FLTK Configure / Build Options**
 - `make`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: macOS 11.4
 - Processor if relevant: Intel

**Comment by ManoloFLTK** [comment]
@dannye Please, close issue if you see it fixed with commit mentioned above.
