### ISSUE TITLE
FLTK 1.3: missing FL_EXPORT in x.H

### ISSUE THREAD

**Issue by oikumene** [fltk/fltk#922]
In branch-1.3, there is no FL_EXPORT for the class Fl_XFont_On_Demand in FL/x.H, which makes python's FLTK wrapper module fail on import.

I built python's FLTK wrapper library against FLTK 1.3.9 with Clang 17.0.6 on FreeBSD stable/14 (amd64) and got:

```
>>> import fltk

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/fltk/__init__.py", line 9, in <module>
    from .fltk import *
  File "/usr/local/lib/python3.9/site-packages/fltk/fltk.py", line 17, in <module>
    from . import _fltk
ImportError: /usr/local/lib/python3.9/site-packages/fltk/_fltk.cpython-39.so: Undefined symbol "_ZN18Fl_XFont_On_Demand5valueEv"
```

On the master branch, the class Fl_XFont_On_Demand is labelled FL_EXPORT in FL/x11.H. It should be the same on branch-1.3.

Thank you in advance.

**Comment by Albrecht-S** [comment]
Thanks for the report, I'm going to fix this.

**Comment by Albrecht-S** [comment]
Note that there's currently no schedule for the next 1.3 release but this fix will be in 1.3.10.

@oikumene Please pull from Git and confirm that this fixes your issue. Thanks in advance.

**Comment by oikumene** [comment]
Confirmed. Thank you.

**Comment by Albrecht-S** [comment]
Thanks for confirmation.
