### ISSUE TITLE
FLTK 1.4 Bug on Linux: Window scaling makes window lose resizable status if resizable_ is NULL

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#923]
**Describe the bug**
If a window is resizable (has a min and max size which are not equal to each other) but has a NULL resizable_ (has no stretchy children widgets), then rescaling the window causes the window to lose its resizable status (cannot be resized nor maximized).

**To Reproduce**
Apply this patch to test/fullscreen.cxx:

```diff
diff --git a/test/fullscreen.cxx b/test/fullscreen.cxx
index 780eae32d..146957f03 100644
--- a/test/fullscreen.cxx
+++ b/test/fullscreen.cxx
@@ -298,6 +298,7 @@ int main(int argc, char **argv) {
     Fl::fatal("Options are:\n -2 = 2 windows\n -f = startup fullscreen\n%s",Fl::help);
 
   fullscreen_window window(460,400+30*NUMB); window.end();
+  window.size_range(200, 200, 2000, 2000);
 
   shape_window sw(10,10,window.w()-20,window.h()-30*NUMB-120);
   sw.set_visible(); // necessary because sw is not a child of window
@@ -314,7 +315,7 @@ int main(int argc, char **argv) {
     sw.show();
   } else {              // otherwise make a subwindow
     window.add(sw);
-    window.resizable(&sw);
+    //window.resizable(&sw);
     w = &window;
   }
```

1. Apply the above patch to test/fullscreen.cxx
2. `make`
3. Run ./test/fullscreen
4. See that the window is both resizable and maximizable
5. Scale the window up or down
6. See that the window is neither resizable nor maximizable

**Expected behavior**
The window should remain resizable and maximizable after scaling.

**Video**

https://github.com/fltk/fltk/assets/5231310/d375b10b-1c3d-47e6-99ea-86f26f4e714f

Please observe the bug specifically at the 16 second mark. The window title bar loses the Maximize button and the edges of the window are no longer resizable.

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 2e315e5

**FLTK Configure / Build Options**
 - `make`

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: Linux
 - OS Version: PeppermintOS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by ManoloFLTK** [comment]
@dannye  That should be fixed with commit mentioned above. Please, close issue if you confirm.

**Comment by dannye** [comment]
Yes, fixed now, thank you very much.
