### ISSUE TITLE
FLTK 1.4 Mac Bug: Fullscreen window loses sys menu bar and (un)fullscreen button if 2nd window is opened

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#924]
**Describe the bug**
If a window is made fullscreen, it will have the sys menu bar above it (pulled down by pressing the mouse cursor against the top) and it will have a green button in the title bar to un-fullscreen.

If a secondary window is opened (such as the About window) then the primary fullscreen window loses the sys menu bar (it is still pulled down but the menu is missing/transparent) and the green un-fullscreen button becomes disabled.

**To Reproduce**
1. Run test/fullscreen
2. Fullscreen the window
3. See the functional sys menu bar and un-fullscreen button
4. Open the About window, and then either close it or click back into the fullscreen window to give it focus
5. See the non-functional sys menu bar and un-fullscreen button

**Note:** Clicking the "FullScreen" light button in test/fullscreen while in this state causes a crash with the message:

> "*** Terminating app due to uncaught exception 'NSGenericException', reason: 'NSWindowStyleMaskFullScreen cleared on a window outside of a full screen transition."

**Expected behavior**
The sys menu bar and un-fullscreen button should stay functional when secondary windows are opened.

**Video**

https://github.com/fltk/fltk/assets/5231310/57bb3581-1ba5-4bc1-a88c-5b2e6f612db9

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5ba756e

**FLTK Configure / Build Options**
 - `make`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: macOS 11.4
 - Processor if relevant: Intel

**Comment by dannye** [comment]
Hm, this does not appear fixed. The only affect I can see is that now the About window cannot be opened while the main window is fullscreen, which does not seem desirable to me.

The bug can still be encountered by opening the About window first:

https://github.com/fltk/fltk/assets/5231310/b1fcce70-d9be-44aa-8131-2ef2964db419

Steps:

1. Run test/fullscreen
2. Open the About window
3. Make the main window fullscreen
4. See that the menu bar and title bar look OK
5. Go back to the desktop (4 finger gesture) and give the About window focus again
6. Close the About window if you want (not required)
7. Go back to the fullscreen window (4 finger gesture again)
8. See that the menu bar and title bar are wrong again

Also note that the About window was just an example. I believe any secondary window will do for this bug.

**Comment by dannye** [comment]
Also try the original steps from the OP but with using test/tree and the tree's "Load Database..." modal window instead of the About window:

<img width="1280" alt="Screen Shot 2024-03-04 at 1 32 16 PM" src="https://github.com/fltk/fltk/assets/5231310/dc308542-6d8a-49dd-832a-4ca8c3f6aa62">

**Comment by ManoloFLTK** [comment]
The issue should be fixed with commit 483729f.

**Comment by dannye** [comment]
Yes, works fantastic now! Thank you so much.
