### ISSUE TITLE
FLTK 1.4 Mac Bug: Scaling window up/down also scales X/Y position on secondary displays only

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#925]
**Describe the bug**
If Cmd+ or Cmd- are used to scale a window up or down, the top-left corner of the window is also proportionally scaled, but seemingly only if the window is not on the primary display.

**To Reproduce**
1. Run any application, such as test/fullscreen
2. Move the window to a secondary display
3. Scale the window up or down
4. See that the X/Y position of the window is also scaled

**Expected behavior**
The top-left corner of the window should stay roughly stationary when the window is scaled, just like it does on the primary display and on other OSes.

**Video**

https://github.com/fltk/fltk/assets/5231310/d53180b6-d508-4bb6-9d39-de6126ea1b7c

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5ba756e

**FLTK Configure / Build Options**
 - `make`

**Operating System / Platform:**
 - OS: macOS
 - OS Version: macOS 11.4
 - Processor if relevant: Intel

**Comment by ManoloFLTK** [comment]
That should be fixed with commit above.
