### ISSUE TITLE
Filechooser preview of XML file shows it as a corrupt image

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#926]
**Describe the bug**
Filechooser preview nor recognizing XML files as text file.

**To Reproduce**
- Use the `filechooser` test program to select a file
-  Select `All files (*)'
-  Point to an XML file
- The preview shows a big 'X'

**Expected behavior**
The preview should show the content of the XML file

**FLTK Version**
1.4 git

**Additional context**
Obviously the XML is treated as an image type, which is corrupt. FLTK 1.3 correctly shows the content of the XML.
Reason is the new SVG image type, which is tested for in `fl_images_core.cxx`. It treats the file as SVG image as soon as `<?xml` is found in the begin.

**Comment by ManoloFLTK** [comment]
This issue should be fixed with commit mentioned above. Please, close issue if you confirm.

**Comment by wcout** [comment]
Though there is no guarantee that the <svg> tag is among the first 300 bytes, it probably is in 99%.
But you should also increase the buffer for the uncompressed SVG's. And maybe check the `count` as in all other occasions.  

````diff
--- a/src/Fl_Shared_Image.cxx
+++ b/src/Fl_Shared_Image.cxx
@@ -279,7 +279,7 @@ void Fl_Shared_Image::reload() {
   int           i;              // Looping var
   int           count = 0;      // number of bytes read from image header
   FILE          *fp;            // File pointer
-  uchar         header[64];     // Buffer for auto-detecting files
+  uchar         header[300];    // Buffer for auto-detecting files
   Fl_Image      *img;           // New image
 
   if (!name_) return;
diff --git a/src/fl_images_core.cxx b/src/fl_images_core.cxx
index 45835fa20..efb676daa 100644
--- a/src/fl_images_core.cxx
+++ b/src/fl_images_core.cxx
@@ -126,7 +126,7 @@ fl_check_images(const char *name,               // I - Filename
   // SVG or SVGZ (gzip'ed SVG)
 
 #ifdef FLTK_USE_SVG
-  uchar header2[300];      // buffer for decompression
+  uchar header2[300];     // buffer for decompression
   uchar *buf = header;    // original header data
   int count = headerlen;  // original header data size
 
@@ -160,8 +160,8 @@ fl_check_images(const char *name,               // I - Filename
 
   // Check svg or xml signature
   bool found_svg = false;
-  if (memcmp(buf, "<svg", 4) == 0) found_svg = true;
-  else if (memcmp(buf, "<?xml", 5) == 0) {
+  if (count >= 4 && memcmp(buf, "<svg", 4) == 0) found_svg = true;
+  else if (count >= 5 && memcmp(buf, "<?xml", 5) == 0) {
     uchar *p = buf;
     do {
       if (memcmp(p, "<svg", 4) == 0) {
````

**Comment by ManoloFLTK** [comment]
Now it should be OK.

**Comment by wcout** [comment]
From looking at the commit only, I think there might be a problem with uncompressed SVG's with a BOM now, not being recognized always correctly, because the might not be read in before with 300 bytes.

Further I notice something is wrong: FLTK does not load SVG-Images that do not start with `<?xml' or `<svg`.
e.g. if you have anSVG looking like:

````
<!--- some comment -->
<svg>
</svg>
````
it is not recognized as a valid SVG and not loaded as Fl_Shared_Image.

I have no time time to investigate further now.

**Comment by wcout** [comment]
What do you think about this simple solution?

[926_v1.diff.txt](https://github.com/fltk/fltk/files/14545255/926_v1.diff.txt)

It in effects reverts `fl_images_core.cxx` to the state before the changes for this issue, removes leading spaces, adds a check for xml comment  and uses nanosvg to decide if this was an SVG image.

**Comment by ManoloFLTK** [comment]
@wcout: very good suggestion. I've committed it with a minor change to make the test for leading whitespace effective.

**Comment by wcout** [comment]
Thanks for fixing! Closing.
