### ISSUE TITLE
FLTK on NetBSD very slow on X11 with Unicode locale

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#935]
This is the transposition of  [STR#2961](https://www.fltk.org/str.php?L2961)  to a github issue.
The overall message from that STR is that the call to XOpenIM() performed each time a window gets closed renders FLTK very slow under NetBSD with Unicode locale. The effect is particularly noticeable when using a menubar where each time the mouse changes toplevel menu a window is closed.

**To Reproduce**
Run test/editor under NetBSD with Unicode locale.
Open a menu and move the mouse left or right to change menu.

**Expected behavior**
Menu changes should be swift but they are very slow.

**FLTK Version**
 - Version: 1.3.x or 1.4 : same cause, same effect
 
**Operating System / Platform:**
 - OS: NetBSD
 -  With Debian, no slowdown but the frequent calls to XOpenIM() do occur

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by ManoloFLTK** [comment]
To Michael Bäuerle: please apply the attached patch to the current version of FLTK 1.4 and report here whether the slowdown disappears under NetBSD and a Unicode locale. I would really expect it does.
If so, I will commit that change. I could also apply it to branch 1.3 if you need to keep using 1.3.

[issue935.patch](https://github.com/fltk/fltk/files/14627486/issue935.patch)

**Comment by michaelbaeuerle** [comment]
Yes, with this patch there is no delay anymore.
Thank you for looking at this problem!

**Comment by Albrecht-S** [comment]
:+1: @ManoloFLTK Awesome, thank you very much for fixing this long-standing issue!

Manolo wrote:
> I could also apply it to branch 1.3 if you need to keep using 1.3.

@michaelbaeuerle What about your further usage of 1.3?

@ManoloFLTK Would you like to add this to 1.3 as well? I'm planning to release 1.3.10 soon (either before 1.4.0 or shortly after 1.4.0).

**Comment by ManoloFLTK** [comment]
@Albrecht-S I've also committed to branch 1.3 (807d205) the fix for this issue.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks.
