### ISSUE TITLE
Memory leak in Fl_Xlib_Graphics_Driver_font_xft.cxx

### ISSUE THREAD

**Issue by tanxn5** [fltk/fltk#938]
This minor issue is `fl_xft_font()` alloc new `Fl_Xlib_Font_Descriptor` to `fl_fonts`(static pointer)
and `Fl_Xlib_Font_Descriptor` open a `XftFont` as its member.

I' try to call `fl_close_display()` before program exit. `fl_close_display()` invoke `XftFontManageMemory`(libxft.so) to release all unref XftFont, but `Fl_Xlib_Font_Descriptor` doesn't close its font member to unref correct.

```cpp
// Practice
int main(int argc, char *argv[]) {

    // create window

    win->show(argc, argv);
    win->set_visible_focus();
    while (!Fl::program_should_quit())
        Fl::wait(1e20);
    delete win;

    fl_close_display();         // <-- XftFonts still keep by fl_fonts
}
```

build conf

```cmake
set(FLTK_USE_PANGO OFF)
set(FLTK_BACKEND_WAYLAND OFF)
set(FLTK_GRAPHICS_CAIRO OFF)
set(FLTK_OPTION_CAIRO_WINDOW OFF)
set(FLTK_OPTION_CAIRO_EXT OFF)
```

**Comment by tanxn5** [comment]
Thanks for reply. I know some memory allocated reachable after all, but valgrind report **definitely lost** for which XftFont opened by Fl_Xlib_Font_Descriptor. I try find a way to may valgrind happy. I mean definitely lost nothing.

**Comment by ManoloFLTK** [comment]
@tanxn5 I am afraid you will not be able to get rid of all memory allocations reported as definitely lost by valgrind after a call to fl_close_display(). FLTK has not been conceived to allow that. You may consider to run your FLTK apps as Wayland clients. The Wayland FLTK backend does a lot more memory deallocations when fl_close_display() runs.

**Comment by Albrecht-S** [comment]
> I try to find a way to may valgrind happy. If I close display after delete Fl_Xlib_Font_Descriptor, Valgrind will reports 0 definitely lost.

@tanxn5 It's a common misconception to (try to) release all allocated memory before program exit. Don't try to "make valgrind happy" but think about what that memory is good for. Imagine a program that allocates thousands of small pieces of memory. This memory is needed until the program exits but it will definitely be released (given back to the system memory pool) when the program exits. However, if you tried to release all memory you'd have to make thousands of deallocations for ... nothing. This would only waste time and we had user reports that such releasing of memory at program exit would take multiple seconds which is nothing you would want your users to suffer from.

The only reason you'd want to release memory at program exit would be to test if your program keeps some hidden memory that might accumulate during program runtime. If memory is **_accumulated during the runtime_** of the program although it should be released at some time, then that can be called a "real leak" and that should be tested, found, and fixed.

Memory allocated by the font structures is usually not of that type of a "real leak".

Hint: I'm using valgrind **and** ASAN (address sanitizer) for FLTK development. The latter allows me to suppress some functions from flagging memory issues (valgrind may allow that too but I don't know how). My ASAN "suppressions" file reads:
```
leak:libfontconfig.so
leak:XCreateFontSet
leak:System_Driver::putenv
leak:UnitTest::create()
leak:libEGL_mesa.so
leak:/usr/lib/x86_64-linux-gnu/dri/iris_dri.so
leak:XGetVisualInfo
leak:XListPixmapFormats
```

As you can see there's a lot of font related stuff but also `UnitTest::create()` which loads tests as plugins but doesn't release the plugins at exit which would just be wasting CPU cycles and time. The `System_Driver::putenv` suppression is a known issue that's not worth fixing and `fl_putenv()` should not be called too often during runtime.

**Comment by tanxn5** [comment]
> @tanxn5 I am afraid you will not be able to get rid of all memory allocations reported as definitely lost by valgrind after a call to fl_close_display(). FLTK has not been conceived to allow that. You may consider to run your FLTK apps as Wayland clients. The Wayland FLTK backend does a lot more memory deallocations when fl_close_display() runs.
Thanks.But I can’t use Wayland for a hardware reason, and pango slower than xftfont in my test.

**Comment by tanxn5** [comment]
> > I try to find a way to may valgrind happy. If I close display after delete Fl_Xlib_Font_Descriptor, Valgrind will reports 0 definitely lost.
> 
> @tanxn5 It's a common misconception to (try to) release all allocated memory before program exit. Don't try to "make valgrind happy" but think about what that memory is good for. Imagine a program that allocates thousands of small pieces of memory. This memory is needed until the program exits but it will definitely be released (given back to the system memory pool) when the program exits. However, if you tried to release all memory you'd have to make thousands of deallocations for ... nothing. This would only waste time and we had user reports that such releasing of memory at program exit would take multiple seconds which is nothing you would want your users to suffer from.
> 
> The only reason you'd want to release memory at program exit would be to test if your program keeps some hidden memory that might accumulate during program runtime. If memory is **_accumulated during the runtime_** of the program although it should be released at some time, then that can be called a "real leak" and that should be tested, found, and fixed.
> 
> Memory allocated by the font structures is usually not of that type of a "real leak".
> 
> Hint: I'm using valgrind **and** ASAN (address sanitizer) for FLTK development. The latter allows me to suppress some functions from flagging memory issues (valgrind may allow that too but I don't know how). My ASAN "suppressions" file reads:
> 
> ```
> leak:libfontconfig.so
> leak:XCreateFontSet
> leak:System_Driver::putenv
> leak:UnitTest::create()
> leak:libEGL_mesa.so
> leak:/usr/lib/x86_64-linux-gnu/dri/iris_dri.so
> leak:XGetVisualInfo
> leak:XListPixmapFormats
> ```
> 
> As you can see there's a lot of font related stuff but also `UnitTest::create()` which loads tests as plugins but doesn't release the plugins at exit which would just be wasting CPU cycles and time. The `System_Driver::putenv` suppression is a known issue that's not worth fixing and `fl_putenv()` should not be called too often during runtime.

I’ve fixed putenv string copy leak, close xftfont for release them to libxft management’s and rebuild libfontconfig for suppress all valgrind errors. You are right, the one slot memory remains is not a problem.
Thanks.
