### ISSUE TITLE
Support for NetBSD

### ISSUE THREAD

**Issue by michaelbaeuerle** [fltk/fltk#944]
Tested on NetBSD 2.0 (version 1.x used GCC 2) with FLTK 1.4 git revision b3b051240ecf3ab562e73d3d5674d05aff261fc4.
Compiler: GCC 3.3 (supports C99, but the system libc only has partial support).

The macro "FL_DEPRECATED" does not work.
Because there was no problem on AIX with GCC 3.4, I changed a threshold with this patch:
[patch_FL_fl_attr.h.txt](https://github.com/fltk/fltk/files/14742586/patch_FL_fl_attr.h.txt)

The Fl_Terminal widget has a problem with "putchar()".
Looks like some header indirectly includes "stdio.h", which defines "putchar()" as a macro on this system.
POSIX defines "putchar()" as equivalent to "putc()":
https://pubs.opengroup.org/onlinepubs/9699919799/functions/putchar.html
And "putc()" is allowed to be implemented as macro:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/putc.html
The FLTK code seems to ask for "Fl_Terminal::putchar()" only.
This patch explicitly undefines the macro "putchar()":
[patch_src_Fl_Terminal.H.txt](https://github.com/fltk/fltk/files/14742729/patch_src_Fl_Terminal.H.txt)

In Fl_Timeout the function "trunc()" is missing.
This patch emulates it with "floor()" and "ceil()":
[patch_src_Fl_Timeout.cxx.txt](https://github.com/fltk/fltk/files/14742736/patch_src_Fl_Timeout.cxx.txt)

In Fl_Unix_Screen_Driver the function "select()" is not found.
NetBSD 2 declares this function in "unistd.h":
https://man.netbsd.org/NetBSD-2.1/select.2
Patch:
[patch_src_driver_Unix_Fl_Unix_Screen_Driver.H.txt](https://github.com/fltk/fltk/files/14742793/patch_src_driver_Unix_Fl_Unix_Screen_Driver.H.txt)

---------------------------------------

Tested on NetBSD 9.3 (current stable version) with FLTK 1.4 git revision 4742d830beb17bd92fed83eb58cede09bfddd576.
Compiler: GCC 7.5 (system libc should be POSIX.1-2001 conformant, POSIX.1-2008 still not supported).

Can be compiled, but needs the patch from #942 too. Otherwise the mount point list in the file browser does not work.

**Comment by Albrecht-S** [comment]
@michaelbaeuerle Thanks again for yet another platform patch.

> This patch explicitly undefines the macro "putchar()":

Did you forget to upload this patch?

**Comment by Albrecht-S** [comment]
> ... needs the patch from https://github.com/fltk/fltk/issues/942 too. Otherwise the mount point list in the file browser does not work.

Done, this part has been committed in 5666ec0ff06bb339923a8b39d771886935bca9a1.

**Comment by Albrecht-S** [comment]
Regarding `Fl_Terminal::putchar()`: I don't think that the proposed patch is a good solution because user code would still be affected by this issue if putchar was defined as a macro. I suggest to rename the method(s) in Fl_Terminal.

I opened a thread in fltk.coredev: ["RFC: Fl_Terminal::putchar() in public API"](https://groups.google.com/g/fltkcoredev/c/mAjbOSJ91Aw/m/iXdNLrC_AAAJ). Please read and add your comments there before we patch the sources.

**Comment by Albrecht-S** [comment]
Regarding missing `trunc()`: I would prefer a `configure` + `CMake` test whether `trunc()` is available rather than system macros to decide if we need a replacement function. It may turn out that other systems lack this function as well and a `configure`/`CMake` test would catch all of them.

I apologize because I'm a bit late with this aspect, however this is not only true for this patch but for all other missing functions we have encountered so far or may find in the future. Looking at this particular patch made me think: "_this is too complicated, it can't be right!_".

I admit that I accepted platform tests like `#ifdef __hpux` before (and in some cases this may be OK) but we should "think" more in "feature tests" rather than "guessing" (depending on platform macros).

**Comment by michaelbaeuerle** [comment]
No problem. Second attempt for a cleaner solution.

Use "HAVE_TRUNC" to enable or disable the replacement function:
[patch-src_Fl__Timeout.cxx.txt](https://github.com/fltk/fltk/files/14772200/patch-src_Fl__Timeout.cxx.txt)

Patches for autoconf:
[patch-configh.in.txt](https://github.com/fltk/fltk/files/14772156/patch-configh.in.txt)
[patch-configure.ac.txt](https://github.com/fltk/fltk/files/14772158/patch-configure.ac.txt)

Patches for CMake:
[patch-configh.cmake.in.txt](https://github.com/fltk/fltk/files/14772161/patch-configh.cmake.in.txt)
[patch-CMake_resources.cmake.txt](https://github.com/fltk/fltk/files/14772163/patch-CMake_resources.cmake.txt)

**Comment by Albrecht-S** [comment]
Working ...

**Comment by Albrecht-S** [comment]
... done. I hope I fixed everything (applied all patches) except:
> This patch explicitly undefines the macro "putchar()":
[patch_src_Fl_Terminal.H.txt](https://github.com/fltk/fltk/files/14742729/patch_src_Fl_Terminal.H.txt)

The `Fl_Terminal` / `putchar()` stuff is still being discussed in `fltk.coredev` and should be resolved soon by renaming `Fl_Terminal::putchar()` - presumably to `Fl_Terminal::put()`.

See discussion in fltk.coredev:
- https://groups.google.com/g/fltkcoredev/c/mAjbOSJ91Aw/m/iXdNLrC_AAAJ
- https://groups.google.com/g/fltkcoredev/c/mAjbOSJ91Aw/m/qOerkC_tAwAJ

**Comment by erco77** [comment]
The `putchar()` change has been made in 31170c4, new name is `plot_char()`.

**Comment by Albrecht-S** [comment]
@erco77  Thanks for the commit and the update here.

@michaelbaeuerle Please confirm that this issue is resolved, i.e. you can build FLTK on your NetBSD system w/o further patches. TIA.

**Comment by michaelbaeuerle** [comment]
> Please confirm that this issue is resolved, i.e. you can build FLTK on your NetBSD system w/o further patches. TIA.

NetBSD 10 was released two weeks ago.
I have tested this version first with git revision 05a95e146b2429154b360030d098f0dae5555706 and FLTK worked as expected.

I need some more time for the older versions.
Hopefully I can test them again tomorrow.

**Comment by michaelbaeuerle** [comment]
More tests with git revision 05a95e146b2429154b360030d098f0dae5555706:
- NetBSD 9: OK
- NetBSD 2: OK with additional "return" statement in the replacement function for `trunc()`, see below.

[patch-src_Fl__Timeout.cxx.txt](https://github.com/fltk/fltk/files/14956735/patch-src_Fl__Timeout.cxx.txt)

**Comment by Albrecht-S** [comment]
@michaelbaeuerle Thanks for the update, and thanks for all your help with your old systems.

This issue has been closed by commit 5de880ae810f7790d888d52a1accbafb0607bf0f.
