### ISSUE TITLE
Please clean up some annoying build warnings emanating from FLTK 1.4

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#946]
**Describe the bug**
For quite a while now, I have been getting the following warnings during compilation of my code that includes FLTK (1.4) headers. I have finally decided to request that you please consider doing something about this annoyance, ideally before releasing 1.4.

```c++
In file included from /vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl_Widget.H:25,
                 from /vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl_Image.H:24,
                 from /vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl_Graphics_Driver.H:32,
                 from /vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/fl_draw.H:26,
                 from fwt3dapi_plot3d.h:76,
                 from Cfwt3dAPI.h:69,
                 from Cfwt3dDrawable.h:64,
                 from Cfwt3dColorLegend.h:64,
                 from Cfwt3dColorLegend.cpp:65:
/vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl.H: In static member function ‘static void Fl::cairo_flush(cairo_t*)’:
/vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl.H:1494:36: warning: unused parameter ‘c’ [-Wunused-parameter]
 1494 |   static void cairo_flush(cairo_t *c) {
```
and
```c++
/vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl_Menu_Item.H: In member function ‘void Fl_Menu_Item::callback(void (*)(Fl_Widget*, long int), long int)’:
/vol1/athabasca/apps/usr/local/gcc-11.4/include/FL/Fl_Menu_Item.H:329:54: warning: cast between incompatible function types from ‘void (*)(Fl_Widget*, long int)’ to ‘void (*)(Fl_Widget*, void*)’ [-Wcast-function-type]
  329 |   void callback(Fl_Callback1*c, long p=0) {callback_=(Fl_Callback*)c; user_data_=(void*)(fl_intptr_t)p;}
```

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from: github
 - If from Git, branch: master
 - If from Git, commit: latest all the time

**FLTK Configure / Build Options**
I enable CAIRO in my FLTK cmake configuration.

**Operating System / Platform:**
 - OS: Linux Mint
 - OS Version: 21 (Vanessa)
 - Compiler: g++ 11.4.0

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**
This is not harmful but clutters my build with warnings that I have to double check every time.

Just today I finally decided to use pragmas to disable the warnings around the include of relevant FLTK headers, at least until you might address the issue.

**Comment by Albrecht-S** [comment]
@pdhahn Please elaborate: do these warnings appear when you build FLTK or when you build your own application?

If it's your own application, please tell use which compiler warnings you are enabling in your application.

**Comment by pdhahn** [comment]
It is when building my own application code, not FLTK. The warnings emanate from the FLTK headers that my code includes.

To configure FLTK, I use `cmake-gui` not `cmake` from command line. I have attached my generated `CMakeCache.txt` file in case that helps. Otherwise, I can try to do a screen capture from the `cmake-gui` display if you like.
[CMakeCache.txt](https://github.com/fltk/fltk/files/14877349/CMakeCache.txt)

**Comment by Albrecht-S** [comment]
Thanks, the CMakeCache.txt file is sufficient. However, I don't see that any unusual compiler warnings are enabled in this file (looking for `CMAKE_CXX_FLAGS*`). This is surprising. Maybe your gcc/g++ compiler (11.4.0) is pickier than mine (12.2.0) which would be unusual (newer versions tend to become pickier). I have no idea what can cause this.

What happens when you build FLTK itself? Do you also see lots of warnings? As I wrote before, we usually don't see warnings with default compiler setups, and I enable some more warnings than the default for my build anyway.

Side note: if I enable both your warnings explicitly in my build of FLTK (`-Wunused-parameter` and `-Wunused-parameter`) I get lots of warnings. These warnings are benign and we don't check for these warnings in our default builds.

Anyway, commit 9d9646fb124aee9255a6bc11a7af65bc54e94fb6 should fix the 2nd warning as well.

Can you comfirm, please?

I'll reply to your compiler setup in my next comment...

**Comment by Albrecht-S** [comment]
Warning `-pedantic` makes the compiler ... guess, what? ... **_pedantic_**. You should IMHO enable this warning only if you really, really want to make sure that your code is kinda "perfect". It may help to find some issues but it's definitely not "compatible" with FLTK code (we use some necessarily "incompatible" casts etc.).

That said, I believe that I "fixed" the two warnings you mentioned above but I can't guarantee that there won't other warnings appear if you include other FLTK headers.

Please close this issue if your current issues are resolved. In the future - if you want to report further warnings - please give all relevant informations about your compiler switches and configurations (and of course, whether the warnings appear when you compile FLTK or your own application) to help us find or reproduce the issue. Thanks.

**Comment by pdhahn** [comment]
Yes I just updated FLTK and your changes appear to work.

W.r.t. `pedantic`, kinda "perfect" is indeed my goal, although as I mentioned, I think `std=c++14` following `-pedantic` may effectuate some modifications, especially overriding `-ansi`. I have a very large number of lines of C++ code in my application(s), and I use quite a few 3rd party libraries other than FLTK of course, so it behooves me to utilize compiler assistance as best I can. :-)

But I hear you about "perfect" when it comes to FLTK, so I'll take that as good advisement moving forward.

Thanks for taking time to help me.
