### ISSUE TITLE
Fl_Gl_Window glViewport() clips drawing on Windows/Mingw64

### ISSUE THREAD

**Issue by ptepa** [fltk/fltk#951]
**Describe the bug**
On Windows 11 / Mingw64 g++ 8.1.0, FLTK 1.4.x Fl_Gl_Window glViewport() does not draw
in the right and top portion of the window.

**To Reproduce**
/*
bug.C - Demsontrate bug on Windows/Mingw64 FLTK 1.4.x Fl_Gl_Window:
square glViewport() has right and top areas where nothing is drawn.
2024-04-09 ptepa

Works correctly on Mac (draws diagonal lines corner to corner):
g++ -m64 -DGL_SILENCE_DEPRECATION -Wall -g -I../../../include -o bug bug.C \
-L../../../lib/Darwin.x86_64 -lFLTK -lm -lpthread \
-framework AGL -framework Cocoa -framework OpenGL -framework ApplicationServices
./bug

On Windows, diagonal lines are clipped (not drawn) on the right and top areas:
PATH="/c/Users/ptepa/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin:/c/Users/ptepa/MinGW/msys/1.0/bin:/c/Users/ptepa/MinGW/bin:/c/WINDOWS/System32:/c/WINDOWS"

g++ -m64 -mwindows -static -Wall -g -DUSE_OPENGL32 -o bug bug.C \
  -I../../../include -L../../../lib/Win64 -lFLTK \
  -lglu32 -lopengl32 -lgdiplus -lole32 -luuid -lcomctl32 -lws2_32
bug.exe
*/

#include <stdio.h> // For printf(), snprintf().
#include <FL/Fl.H>           // For Fl::run().
#include <FL/Fl_Gl_Window.H> // For Fl_Gl_Window.
#include <FL/gl.h>           // For gl*() OpenGL routines.

class View : public Fl_Gl_Window {
private:
  int size; // Current size of square View window (in screen pixels).
  double west; // Lon/lat bounds of viewport.
  double east;
  double south;
  double north;
  View( const View& other ); // Not allowed.
  View& operator=( const View& other ); // Not allowed.
  void resizeViewport( int width, int height );
public:
  virtual ~View() {};
  View();
  virtual void resize( int x, int y, int w, int h );
  virtual void draw();
};

View::View() : Fl_Gl_Window( 355, 35, 730, 730, "bug" ) {
  size = 730;
  west = -88.0;
  east = -63.0;
  south = 24.0;
  east = 49.0;
  resizable( this );
  size_range( 100, 100, 2000, 2000, 1, 1, 1 ); // Enforce square window.
  end();
  show();
}

void View::resizeViewport( int width, int height ) {
  printf( "View::resizeViewport( width = %d, height = %d )\n",
           width, height );
  printf( "  size = %d\n", size );

  if ( width != size || height != size ) {
    size = width < height ? width : height;
  }

  glLoadIdentity();
  printf( "calling glViewport( 0, 0, %d, %d )\n", size, size );
  glViewport( 0, 0, size, size );
  printf( "calling glOrtho( %f, %f, %f, %f, -1.0, 1.0 )\n",
           west, east, south, north );
  glOrtho( west, east, south, north, -1.0, 1.0 );
}

void View::resize( int x, int y, int w, int h ) {
  printf( "View::resize( %d, %d, %d, %d )\n", x, y, w, h );
  size = w < h ? w : h; // New size will be minimum of width or height.
  size -= size % 2; // Ensure size is even.
  char label[ 64 ] = "";
  memset( label, 0, sizeof label );
  snprintf( label, sizeof label / sizeof *label, "View %d", size );
  this->label( label );
  Fl_Gl_Window::resize( x, y, size, size );
  resizeViewport( size, size );
  redraw(); // Causes FLTK to call draw().
}

void View::draw() {
  static bool initialized = false;
  printf( "View::draw() initialized = %d\n", initialized );

  if ( ! initialized ) {
    initialized = true;
    glEnable( GL_TEXTURE_2D );
    glClearDepth( 1.0 );
    glDepthFunc( GL_LESS );
    glDisable( GL_DEPTH_TEST );
    glShadeModel( GL_SMOOTH );
    glDisable( GL_LIGHTING );
    glBlendFunc( GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA );
  }

  if ( ! valid() ) { // If first time or resized window:
    valid( 1 );
    printf( "  View::draw() calling resizeViewport( %d, %d )\n", size, size );
    resizeViewport( size, size );
  }

  // Draw white diagonal lines connecting opposite corners:

  glClearColor( 0.0, 0.0, 0.0, 1.0 );
  glClear( GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT );
  glColor4f( 1.0, 1.0, 1.0, 1.0 );
  glLineWidth( 1.0 );
  glBegin( GL_LINES );
  glVertex2f( west, south );
  glVertex2f( east, north );
  glEnd();
  glBegin( GL_LINES );
  glVertex2f( east, south );
  glVertex2f( west, north );
  glEnd();
}

int main() {
  View view; // Create View window.
  Fl::run(); // Loop on events until user quits.
  return 0;
}

g++ -m64 -mwindows -static -Wall -g -DUSE_OPENGL32 -o bug bug.C \
  -I../../../include -L../../../lib/Win64 -lFLTK \
  -lglu32 -lopengl32 -lgdiplus -lole32 -luuid -lcomctl32 -lws2_32
bug.exe

**Expected behavior**
The drawn white "X" diagonal lines should reach all four corners of the square window.
Instead, the lines are clipped (not drawn) in the right and top regions thus not reaching the SE, NE, NW corners.

**Screenshots**

**FLTK Version**
fltk-1.4.x-20240405-9d9646fb
 - Downloaded and self-built from: fltk.org
 
**FLTK Configure / Build Options**
./configure --enable-debug --enable-localjpeg --enable-localpng --enable-localzlib
make

**Operating System / Platform:**
Windows 11, Intel iCore processor, mingw64, g++ 8.1.0

**Additional context**
The program displays correctly on my Mac 10.13.6, x86_64, g++ = Apple LLVM version 9.0.0 (clang-900.0.39.2)

**Comment by MatthiasWM** [comment]
Assigned to myself for OpenGL knowledge, but not so much for Windows, and much less mingw.
At the top right, is the white line missing a lot, or just one pixel?

**Comment by MatthiasWM** [comment]
Line 30: east is initialized twice, but north is never initialized. Checking further.

**Comment by MatthiasWM** [comment]
Or is your cross only half the size it should be? Then you probably have a HiDPI screen and one FLTK pixel is actually two screen pixels wide. glViewport must be called with the physical number of pixels which you get via `Fl_GL_Window::pixel_w()` and `pixel_h()`, or in your case by writing `glViewport(0, 0, size*pixels_per_unit(), size*pixels_per_unit());`

https://www.fltk.org/doc-1.4/classFl__Gl__Window.html#a080d304174ec7658ea82328044ce20ce
https://www.fltk.org/doc-1.4/classFl__Gl__Window.html#a233531b1ca75ad7ebade4889118d7cf9
