### ISSUE TITLE
Naseem

### ISSUE THREAD

**Issue by fakawenaseem** [fltk/fltk#955]
**Please do not use GitHub Issues for FLTK user questions**

This is the wrong place to ask questions about building FLTK or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.

Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (e.g. Windows, macOS, Linux/X11 or Linux/Wayland), the build system (e.g. Visual Studio, CMake, Ninja), compiler (gcc, clang, ...), compiler version and build error messages in text form (copy and paste preferred). Thank you.

Note that FLTK user questions here (in GitHub Issues) **must** be closed immediately by a maintainer with label `no user support`.

**Comment by fakawenaseem** [comment]
Naseem

**Comment by Albrecht-S** [comment]
Hi Naseem, please do not post such messages in our GitHub issues. If you had read what you posted you should have known what to do. I take it that you did this accidentally and I'm closing this issue now.
