### ISSUE TITLE
Wayland use of alpha in glClearColor/glClear() -- bug or misfeature?

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#957]
**Describe the bug**
Wayland treats alpha channel differently than X11.  When clearing the screen to 
0, 0.8, 0.8, 0 (ie. cyan with no alpha), X11 would respect that color and alpha.
Wayland, at least under FLTK, does not.  It treats 0.f alpha as transparent.
The behavior of X11  is desired as it allows then reading back the colors properly with transparency (with, say, glReadPixels), which are lost in Wayland. 
It isn't clear to me if this is another *mis-feature* of Wayland or an actual bug in FLTK.

**To Reproduce**
Find attached a self compiled .zip, a README.txt and with a CMakeLists.txt file and a runme.sh script for easy compiling if you have FLTK already installed.

See the README.txt.

**Expected behavior**
Wayland should respect the alpha channel and treat the unrendered areas as black.  Optionally, this should be an option in the mode() creation of the GL window.

**Screenshots**
Not possible, as capturing makes the window behave properly.

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4
 - Downloaded and self-built from: git master

**FLTK Configure / Build Options**
cmake .. 

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS:Linux
 - OS Version: Ubuntu 22.04.4 LTS
 - Processor if relevant [e.g. on macOS: M1, Intel]

**Linux/Unix Runtime, if applicable:**
 - Wayland 
 - X11
 
 Both.  Each show different behavior.

**Additional context**

[fltk_wayland_alpha.zip](https://github.com/fltk/fltk/files/15049146/fltk_wayland_alpha.zip)

**Comment by ManoloFLTK** [comment]
@ggarra13 Would the attach patch fix the issue?

[issue957.patch](https://github.com/fltk/fltk/files/15052490/issue957.patch)

**Comment by Albrecht-S** [comment]
@ManoloFLTK I'm not a friend of such C comments as used in the old code and the resulting new code after the patch. Such /* ... comments ... */ that span several lines of _otherwise valid code_ are confusing, and at any time a dev adds a new comment inside that sequence of lines the new `*/` would terminate the previous comment etc. etc..

In such cases I suggest to use either C++ comments `//` on all commented-out lines or `#if (0) ... #endif` or similar to make clear what code part is commented out and which part is valid code.

Thanks for taking this into account if you apply the patch.

I can't say anything to the issue at hand or the patch though.

**Comment by ggarra13** [comment]
> @ggarra13 Would the attach patch fix the issue?
> 
> [issue957.patch](https://github.com/fltk/fltk/files/15052490/issue957.patch)

No, I'm afraid it would not.  That sets the clear color to an alpha of 1.
The code you has two issues.  In OpenGL, that color is not applied with that instruction, but only when you do:

glClear(GL_COLOR_BUFFER_BIT);

Even if you add that to your patch, the whole idea is to leave the alpha at 0, like the original code:

glClearColor(0.0, 0.0, 0.0, 0.0);
glClear(GL_COLOR_BUFFER_BIT);

Imagine a PNG drawing of a ball with an alpha channel of 1 where the ball is 1 and 0 where the ball is not present.  You want that image to not change when you: 1) load it, 2) display or 3) save it back again after, say, changing its color.  For 3) to happen, you need the alpha channel to remain the same all through out.  That way you can change the background at any time by doing a "composite".  If you are new to compositing, google for it for some samples.

If you call:

glClearColor(0.0, 0.0, 0.0, 1.0);
glClear(GL_COLOR_BUFFER_BIT);

the ball _and_ the background would have an alpha of 1.0, and you would no longer be able to composite the ball on a different background anymore (it would have black hard-coded).

The code we are looking for is *NOT* OpenGL code, but something in Wayland that clears the window to 0,0,0,0 when it is created, without letting the Desktop background through.

**Comment by ggarra13** [comment]
I asked Gemini who had this to say about Wayland:





















Achieving a fully transparent background with no desktop peeking through in Wayland using OpenGL requires a two-pronged approach:

Clearing the Color Buffer with Alpha:

Within your OpenGL rendering code, use the glClearColor function to set the clear color to (0.0f, 0.0f, 0.0f, 0.0f). This sets the red, green, and blue components to black (0.0f) and the alpha component to fully transparent (0.0f).

Before drawing any objects, call glClear to clear the color buffer with the previously set color. This ensures newly drawn objects are rendered on a completely transparent background.  *** WE HAVE THIS IN MY SAMPLE CODE ***

Disabling Window Background:

Unfortunately, Wayland doesn't offer a direct OpenGL function to control window background behavior. However, you can leverage compositor-specific extensions to achieve this:

Identify your compositor: Use libraries like wlr-client to query the running Wayland compositor. This will tell you which compositor you're using (e.g., GNOME Shell's Mutter, KDE Plasma's KWin).

Check for compositor extensions: Some compositors provide extensions to control window transparency. Consult the specific compositor's documentation to see if it offers an extension for disabling the window background. GNOME Shell, for example, offers the wlr-transparent-v1 extension.  *** THIS IS WHAT WE NEED EXPOSED IN WAYLAND ***

Enable the extension (if available): If your compositor supports a relevant extension, use the appropriate library functions to enable it within your application. This allows you to control window transparency behavior.

Disable window background (extension specific): Once enabled, the extension will likely provide functions to set the window background behavior. Look for functions related to disabling the window background or setting opacity to 0. This prevents the desktop from showing through the transparent parts of your application window.

Important Note: Not all Wayland compositors offer extensions for controlling window transparency. If your compositor doesn't have such an extension, achieving a fully transparent background with a completely invisible desktop might not be possible.

**Comment by ManoloFLTK** [comment]
OK. I think I got it with this other patch:

[issue957-V2.patch](https://github.com/fltk/fltk/files/15058737/issue957-V2.patch)

**Comment by ggarra13** [comment]
I think we are almost there.  The window is now indeed not transparent anymore.  And the alpha seems to remain at 0 on OpenGL.  I say it seems because I could not verify it.
When I try to read back the values of the GL_FRONT frame buffer of the OpenGL window (to verify the image has indeed kept its alpha), I get a completely empty image.
I'll see if I can create a simple main.cpp program with the test of creating a circle like the test now but saving the image to a .png file.  Also to make sure it is not a bug in my viewer.

**Comment by ggarra13** [comment]
No.  It is still broken.  I tried patch v2 and v3.

On Wayland, the background is dark gray instead of being black, as if some gain is being applied.  On XWayland, it *is* black as it should be.
When saving on my program the image captured from OpenGL on Wayland, I get a fully transparent image (no spheres or anything).  On XWayland, I get a fully opaque alpha. 
Anyway, I'll do the little test program and we can then add it to FLTK's test suite.

**Comment by ggarra13** [comment]
Ok.  My program is buggy.  With this sample code your fix is almost perfect.

I am attaching a simple program that creates a shape (triangle) and saves it to a png with and without alpha in /tmp.  You will need to view it with a program that shows the alpha channel.  If you don't have anything, you can use my own (github.com/ggarra13/mrv2).

The background is set to pure black with no alpha channel.  The problem, under Wayland, is that it does not set the background to black but to the color of the Window (border?).
XWayland shows it properly.

I'm using this command-line to test quickly the code:

cd fltk_build
ninja && bin/test/shape && mrv2 /tmp/triangle*.png

**Comment by ManoloFLTK** [comment]
The mechanism at work under Wayland with the V3 patch is as follows: a GL window which is now fully transparent is composited above its parent, non-GL window which is fully opaque. What is not colored by GL therefore lets what is behind it appear. Overall, the background color of the parent window is visible in the non-colored parts of the GL scene. That explains why "the background is dark gray instead of being black": that's because the parent window has FLTK's default background color, grey. To get it black, just add a solid black FL_FLAT_BOX Fl_Box to the parent window where the GL subwindow is placed.

I've run your modified shape program and see that the output png-with-transparency file is correct.

In my view, this issue is solved with the one-line V3 patch. It's just necessary, when creating an FL_ALPHA GL scene in an Fl_Gl_Window subwindow to take care of the color of the parent window of this subwindow.

**Comment by ManoloFLTK** [comment]
@ggarra13 If you agree that the commit mentioned above fixes the issue, please close it.

**Comment by ggarra13** [comment]
I don't see how I can get to the parent window.  I've tried from my OpenGL window's draw code:

  // window()->box(FL_FLAT_BOX);
  // window()->color(0x00000000);
  parent()->box(FL_FLAT_BOX);
  parent()->color(0x00000000);

**Comment by ggarra13** [comment]
I added a new group and that solved it.  I am closing the issue now.

**Comment by ManoloFLTK** [comment]
```
#include <config.h>
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Hor_Slider.H>
#include <FL/math.h>

#include <FL/gl.h>
#include <FL/Fl_Gl_Window.H>

class shape_window : public Fl_Gl_Window {
  void draw() FL_OVERRIDE;
public:
  int sides;
  shape_window(int x,int y,int w,int h,const char *l=0);
};

shape_window::shape_window(int x,int y,int w,int h,const char *l) :
Fl_Gl_Window(x,y,w,h,l) {
  sides = 3;
  mode(FL_ALPHA);
}

void shape_window::draw() {
// the valid() property may be used to avoid reinitializing your
// GL transformation for each redraw:
  if (!valid()) {
    valid(1);
    glLoadIdentity();
    glViewport(0, 0, pixel_w(), pixel_h());
  }
// draw an amazing graphic:
  glClear(GL_COLOR_BUFFER_BIT);
  glClearColor(.0f, .0f, .0f, .0);
  glColor3f(.5f, .6f, .7f);
  glBegin(GL_POLYGON);
  for (int j=0; j<sides; j++) {
    double ang = j*2*M_PI/sides;
    glVertex3f((GLfloat)cos(ang), (GLfloat)sin(ang), 0);
  }
  glEnd();
}

// when you change the data, as in this callback, you must call redraw():
void sides_cb(Fl_Widget *o, void *p) {
  shape_window *sw = (shape_window *)p;
  sw->sides = int(((Fl_Slider *)o)->value());
  sw->redraw();
}

int main(int argc, char **argv) {

  Fl::use_high_res_GL(1);
  Fl_Window window(300, 330);
  Fl_Box bg(FL_FLAT_BOX, 10, 10, 280, 280, 0);
  bg.color(FL_BLACK);
// the shape window could be it's own window, but here we make it
// a child window:
  shape_window sw(10, 10, 280, 280);
// make it resize:
  window.resizable(&sw);
  //  window.size_range(300,330,0,0,1,1,1);
// add a knob to control it:
  Fl_Hor_Slider slider(50, 295, window.w()-60, 30, "Sides:");
  slider.align(FL_ALIGN_LEFT);
  slider.callback(sides_cb,&sw);
  slider.value(sw.sides);
  slider.step(1);
  slider.bounds(3,40);

  window.end();
  window.show(argc,argv);

  return Fl::run();
}
```
