### ISSUE TITLE
Fluid/MSVC compilation warnings

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#966]
**Describe the bug**
Compilation warnings under Windows/MSVC 2019:
```
fluid\autodoc.cxx(123,13): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data
fluid\autodoc.cxx(148,13): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data
fluid\autodoc.cxx(173,13): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data
fluid\autodoc.cxx(198,13): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data
fluid\autodoc.cxx(308,81): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
fluid\autodoc.cxx(308,65): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
```

**To Reproduce**
Build FLTK including FLUID using Visual Studio.

**Expected behavior**
No compilation warnings.

**FLTK Version**
 - Version: 1.4.0 (Git master)
 - Commit: f194d8596f4a9761fa180ae5cc49b0f9d421bfb5

**Operating System / Platform:**
 - OS: Windows 10
 - Visual Studio 2019

**Additional context**
1. The first four warnings are all similar, like `float a = 255/max_x;`. I don't know the intention but I assume that it was intended to be `float a = 255.0f/max_x;` or something like this (floating point division). Since using integer division would yield a totally different value I don't know the correct (intended) solution.
2. The other two warnings (same line) are "the opposite": `img->w()*scale, img->h()*scale`. I guess that a simple cast to int (truncation) would be appropriate, unless rounding is preferred (intended).

I'm classifying the first four "warnings" as bugs because the result is very likely not as intended.

@MatthiasWM Should be easy to fix for you.

**Comment by MatthiasWM** [comment]
Fixed in 132e7d4e32836bba9d840c177baac02b7e441a40
