### ISSUE TITLE
FLTK hangs when a GL visible subwindow goes partially below the screen on Wayland-Gnome

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#967]
**Describe the bug**
In my application, I can have three GL windows.  One is the main viewport, one is the main timeline and one is an (optional) floating window.  Neither the main viewport nor the floating window hang.  However the timeline, if it is dragged below the bottom of the screen partially stops FLTK's timeouts (refreshing of playback) while still moving it and completely hangs FLTK (timeouts - see playback in the attached movie) when the window is released with the timeline outside (at the bottom) of the desktop.
 XWayland is fine.  Moving any window to the left or to the right is also fine (does not hang).
Hiding the timeline is also fine.  But leaving it visible and dragging outside the desktop is not.  My guess is that it may be a polll issue that is making FLTK hang.

**To Reproduce**
Working on it.  For now, check the attached movie and fluid screenshot.

**Expected behavior**
Wayland should not hang when the window goes to the bottom of the screen.

**Screenshots**
See the linked movie.  Note how the timeouts (refreshing of the view window) stop while dragging outside the desktop.
Note the hang when the window is finally released.

https://mega.nz/file/DT51CISD#_0Bw98XiLWic53eGZYt_Ap2AanL4mA6ypbh02irc6QI

I am also attaching a picture of my fluid layout for the viewer (uiTimeline is the OpenGL viewer window with the issue which is expanded to show thumbnails in the movie, albeit that is irrelevant):

![Captura desde 2024-05-03 12-18-19](https://github.com/fltk/fltk/assets/6072843/40878672-7705-4da9-8168-a6c99b55bc0f)

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0 master

**FLTK Configure / Build Options**
Same as usual, with X11 and Wayland support.

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: Linux
 - OS Version: Ubuntu 22.04.4 LTS
 - Graphics driver: any (Mesa and NVidia drivers exhibit the behavior)

**Linux/Unix Runtime, if applicable:**
 - Wayland (Ubuntu-wayland)

**Additional context**

**Comment by ManoloFLTK** [comment]
I can reproduce the problem with Debian + gnome and I see that the same executable run under the KDE/plasma desktop shows no problem when the GL window is entirely out from the display. This looks like a bug in Mutter, gnome's wayland compositor. Wayland hides the position of a window in the display, so I don't see how to detect when a subwindow becomes out from the display area.

**Comment by ggarra13** [comment]
Could you file a bug report with them as you are likely more saavy?  Did you get a simple reproduceable example?
On the meantime, isn't there any other Wayland compositor that is not as heavy as KDE that works too (Kwin, Weston, other...)?

**Comment by ManoloFLTK** [comment]
@ggarra13 The commit mentioned above should hopefully fix this issue. Is that what you observe?

**Comment by ggarra13** [comment]
@ManoloFLTK I confirm that: a) KDE/Plasma and Weston did not suffer from this.  b) The attached patch fixes it for Gnome's Mutter.

Thanks a lot!

**Comment by ggarra13** [comment]
@ManoloFLTK I am reopening the issue.  Albeit the proposed patch got rid of the hanging when dragging the subwindow out of the screen, it has introduced a random freezing of the UI (FLTK timeouts not getting called) when the subwindow (the timeline is visible).  Moving the mouse on the main view will unfreeze the UI.
If the timeline is hidden (ie. not visible), no freezing of the video happens.

**Comment by ManoloFLTK** [comment]
> it has introduced a random freezing of the UI -video playback- (FLTK timeouts not getting called) when the subwindow (the timeline is visible). 

Doesn't this sentence lack its end?

Please describe the problem in detail. Providing a small test program would be very useful.

**Comment by ManoloFLTK** [comment]
Gonzalo: could you, please, apply this patch to FLTK and then try again with your program? Report here what you get.

[issue967.patch](https://github.com/fltk/fltk/files/15209496/issue967.patch)

**Comment by ManoloFLTK** [comment]
@ggarra13 I attach a modified version of `examples/OpenGL3test.cxx` I use here to try and reproduce the issue. I would expect `issue967.patch` given above to fix the issue. Report here, please, what you get.

[OpenGL3test.cxx.txt](https://github.com/fltk/fltk/files/15212035/OpenGL3test.cxx.txt)

**Comment by ggarra13** [comment]
Sorry for not getting back to you sooner.  I was compiling several versions of my program from scratch and when I did, it got rid of the video playback stopping.  I could no longer reproduce it, so I could not check your patch.  The only main thing I changed on my side (besides recompiling everything) was to not load pyFLTK at startup, albeit I don't think that would be the culprit.
I'll try your OpenGL3test.cxx to see what happens with it and provide further input in an hour or so.

**Comment by ManoloFLTK** [comment]
I could reproduce here quite clearly with my test program the first issue, about moving a GL window below the screen bottom. I also see that when I move the window to the left, GL stops redrawing when about half of the GL scenes is outside the screen. Do you get that too with your app?

Commit b726211 fixes this problem in my tests. 

But I could not reproduce here the second issue about GL freezing. I didn't really understand how it occurs. If you confirm that there's no more GL freezing, then `issue967.patch` is no longer needed/useful.

**Comment by ggarra13** [comment]
Okay.  Here's what I got:

Without patch:

- I tried OpenGL3test.cxx and, the first time I tried it, it stopped refreshing after right after starting it (when the mouse was away from the window.  Moving the mouse fixed it).  I tried it several times again and I could not reproduce it another time.
- My application, as mentioned, does not seem to exhibit the issue anymore, so I no longer know how to test it (previously it was not refreshing the view window usually between 10 or 40 seconds of playing the video).  Yesterday, I left it running for three hours and it did not had refresh issues.

With the patch:

It is worse.

- OpenGL3test.cxx did not show any improvement or problem.  Could not reproduce the issue.
- My program, however, did not refresh the view window at opening the window with a movie (right at start up).  I am attaching a picture of it:

![Captura desde 2024-05-05 05-48-28](https://github.com/fltk/fltk/assets/6072843/577809b7-577b-4b58-a381-786d4676a32f)


Two more things that happen at start up on my program which may effect the last patch.  I resize the window as soon as a movie is loaded.  Also, I hide one of the bars (the pixel bar), which is in a Fl_Flex widget, so that the interface rearranges itself.  I call Fl::flush every time I update either the hiding of the pixel bar or resizing of the window.

**Comment by ManoloFLTK** [comment]
OK. So I would believe we are good with FLTK in its present state and without further patch. Do we agree?

**Comment by ggarra13** [comment]
Yes, it seems to be the best thing so far.  I'll keep an eye if I can see freezing again.

**Comment by ManoloFLTK** [comment]
I added a small further commit for a detail that should not have visible effect. Close issue if you agree.
