### ISSUE TITLE
Wayland: subwindow redraw issues from timeouts with NVidia driver

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#973]
**Describe the bug**
I believe the current Wayland FLTK implementation may have a **VERY** subtle and hard to reproduce bug.  I had some time to dig into it and I **think** I know what triggers it, but not yet how to reproduce it in a simple example.
Currently I have a subwindow on a Fl_Flex (where my viewer's opengl timeline and frame counter live --an fltk widget).
I have two timeouts.  One, that receives the picture for display and also updates the frame counter and timeline.  That works fine.
However, I also have another timeout on the timeline that checks on user interaction on the timeline viewport, to allow for, for example, dragging clips around for editing, even when the picture timeout's callback/redraw is not called.  Sometimes both timeouts may call redraw() on the same OpenGL timeline.

The picture/frame counter timeout has a:
        const double kTimeout = 0.005;

The timeline UI interaction timeout has a:
        const double kTimeout = 0.008; // approx. 120 fps
  
On all platforms but Wayland, calling uiTimeline->redraw() from two different timeouts does not seem to have any side effects, even if they have different speeds.
However, on Wayland, calling the two timeouts can lead to no redraws.  I am still not sure if it is because the two timeouts coincide in time, or on the contrary, because they diverge.

**To Reproduce**
Good luck with this one, @ggarra13 !!!!

**Expected behavior**
I would expect the multiple redraws from the timeouts to not stop the redraws from happening.

**Screenshots**

**FLTK Version**
 - Version: 1.4.0 master

**FLTK Configure / Build Options**
N/A  happens on both debug and release builds.

**Operating System / Platform:**
Linux

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
It's difficult to follow the bug description. Is the bug this?
> calling the two timeouts can lead to no redraws

"No redraws" of what? Is the GUI completely frozen?

**Comment by ManoloFLTK** [comment]
@ggarra13 Could you, please, apply the attached patch and report here whether it solves the issue?

[issue973.patch](https://github.com/fltk/fltk/files/15289697/issue973.patch)

**Comment by ggarra13** [comment]
> @ggarra13 Could you, please, apply the attached patch and report here whether it solves the issue?
> 
> [issue973.patch](https://github.com/fltk/fltk/files/15289697/issue973.patch)

No changes seem appararent.  Still freezes randomly.

**Comment by ggarra13** [comment]
Actually with issue973.patch it is worse. I get bad redraws on the timeline when dragging the dragbar of the Fl_Tile where the windows are.

**Comment by ggarra13** [comment]
Note that freezing goes away as soon as I enter the main window of my viewer.  The event does not seems to have to be inside one of the OpenGL windows.

**Comment by ManoloFLTK** [comment]
Then, there's nothing I can do without being able to reproduce the problem here with a simple app.

**Comment by ggarra13** [comment]
> Then, there's nothing I can do without being able to reproduce the problem here with a simple app.

I understand.  Let me help you out.  I think it is not an OpenGL issue but and EGL issue.  It may be an NVidia problem or a problem in FLTK interacting with EFL.

With Mesa, that is **without** the Ubuntu package:

libnvidia-egl-wayland1

I get the following EGL warning on Mesa on any FLTK GL demos (or my program):

libEGL warning: egl: failed to create dri2 screen

With NVidia, that is **with** the Ubuntu package, I get no warnings on the FLTK GL demos.  Let's see if we can get rid of that warning first on Mesa, as it may point to a bug.  Do you also see that warning with the FLTK demo programs on your side?

So far, I cannot get my program to hang with the Mesa drivers.
That may indicate an EGL issue (either on FLTK's code -- the Mesa warning) or in the NVidia driver.

**Comment by ManoloFLTK** [comment]
> I get the following EGL warning on Mesa on any FLTK GL demos (or my program):
libEGL warning: egl: failed to create dri2 screen
With NVidia, that is with the Ubuntu package, I get no warnings on the FLTK GL demos. Let's see if we can get rid of that warning first on Mesa, as it may point to a bug. Do you also see that warning with the FLTK demo programs on your side?

Yes, I also always see this warning here where I always use MESA because I run Wayland+EGL inside a VM.

> So far, I cannot get my program to hang with the Mesa drivers.

That would suggest the error is in the NVidia driver (or in FLTK handling of it). At any rate, nothing you report suggests FLTK doesn't interact correctly with EGL under MESA.

That also suggests I won't be able to reproduce the issue here.

**Comment by ManoloFLTK** [comment]
>  libEGL warning: egl: failed to create dri2 screen

This warning is not created by FLTK per se because I see exactly the same warning when running the GL-using demo app of the libdecor package (https://gitlab.freedesktop.org/libdecor/libdecor) which uses no FLTK whatsoever.

**Comment by ggarra13** [comment]
> > libEGL warning: egl: failed to create dri2 screen
> 
> This warning is not created by FLTK per se because I see exactly the same warning when running the GL-using demo app of the libdecor package (https://gitlab.freedesktop.org/libdecor/libdecor) which uses no FLTK whatsoever.

Yes, I asked Gemini.  And it said it comes from EGL itself and indicates there's no HW acceleration.  Oh well...

**Comment by ggarra13** [comment]
@ManoloFLTK I am going to start reading your documentation on how Wayland works to see if I can find the issue on my Ubuntu box with Nvidia.  Do you have a list of potential functions (FLTK's or Wayland's EGL) that could potentially stall FLTK?

**Comment by ManoloFLTK** [comment]
It would be firstly very useful to know the debug mode backtrace of your app when it blocks.
The block occurred in function eglSwapBuffers() during the previous issue about GL subwindows moved below the screen bottom. It's also necessary to describe the condition of the block much more clearly. Just reading this issue and without having the blocking app at hands, I can't understand exactly when the blocking happens.

The key Wayland feature I suspect to be involved is what Wayland calls "frame throttlling": a mechanism that Wayland suggests client apps to use to know when the compositor is ready to map a new content of a window. It's explained in subsection "Throttling redraw operations" of the "Wayland buffers" section of my document about [how FLTK implements Wayland](https://fltk.gitlab.io/fltk/wayland-devel.html).

The fix of the 'below screen bottom' issue was to implement this throttling mechanism also for GL subwindows (previously it was implemented only for non-GL windows and for resize operations of toplevel windows, GL or non-GL). The document mentioned above describes this mechanism only for non-GL windows because it's not clear in my mind whether and if yes how exactly EGL is involved in this mechanism.

**Comment by ggarra13** [comment]
Ok.  You ask for it, you have it.  Here's the stack trace of my program when it stalls:

0x558ce0ea8423 printStackTrace()
 (/home/gga/code/applications/mrv2/mrv2/lib/mrvCore/Linux/mrvStackTrace.cpp:46)
0x558ce0ea8001 mrv::callback(int)
 (/home/gga/code/applications/mrv2/mrv2/lib/mrvCore/Linux/mrvSignalHandler.cpp:32)
0x7f05cb318bcf __GI___poll
 (../sysdeps/unix/sysv/linux/poll.c:29)
0x7f05e1183aab wayland_socket_callback
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:1330)
0x7f05e117f59e Fl_Unix_Screen_Driver::poll_or_select_with_delay(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Unix/Fl_Unix_Screen_Driver.cxx:75)
0x7f05e11858b3 Fl_Wayland_Screen_Driver::poll_or_select_with_delay(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:1910)
0x7f05e11902f3 Fl_Unix_System_Driver::wait(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Unix/Fl_Unix_System_Driver.cxx:810)
0x7f05e10b3b02 Fl::wait(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/Fl.cxx:585)
0x7f05e10b3b2a Fl::run()
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/Fl.cxx:605)
0x558ce07b77ad mrv::App::run()
 (/home/gga/code/applications/mrv2/mrv2/lib/mrvApp/mrvApp.cpp:1011)
0x558ce0610e3d main
 (/home/gga/code/applications/mrv2/mrv2/src/main.cpp:70)
0x7f05cb229d8f __libc_start_call_main
 (../sysdeps/nptl/libc_start_call_main.h:58)
0x7f05cb229e3f __libc_start_main_impl
 (../csu/libc-start.c:392)

**Comment by ManoloFLTK** [comment]
@ggarra13 Could you, please, apply this patch and report here what you see? TIA.

[issue973.patch](https://github.com/fltk/fltk/files/15351611/issue973.patch)

**Comment by ggarra13** [comment]
The stall is still there.  And the window could be resized out of bounds (behind/below the Ubuntu Taskbar at the bottom).

**Comment by ggarra13** [comment]
Actually, I just realized the Window could be resized out of bounds without the patch too.

**Comment by ggarra13** [comment]
The stack trace now **is** different thou:

0x5561c492c7f7 printStackTrace()
 (/home/gga/code/applications/mrv2/mrv2/lib/mrvCore/Linux/mrvStackTrace.cpp:46)
0x5561c492c394 signal_callback
 (/home/gga/code/applications/mrv2/mrv2/lib/mrvCore/Linux/mrvSignalHandler.cpp:21)
0x7f473c51b63d __GI___select
 (../sysdeps/unix/sysv/linux/select.c:69)
0x7f475217f39e Fl_Unix_Screen_Driver::poll_or_select_with_delay(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Unix/Fl_Unix_Screen_Driver.cxx:53)
0x7f47521858b3 Fl_Wayland_Screen_Driver::poll_or_select_with_delay(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:1910)
0x7f47521902f3 Fl_Unix_System_Driver::wait(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/drivers/Unix/Fl_Unix_System_Driver.cxx:810)
0x7f47520b3b02 Fl::wait(double)
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/Fl.cxx:585)
0x7f47520b3b2a Fl::run()
 (/home/gga/code/applications/mrv2/BUILD-Linux-amd64/Debug/FLTK-prefix/src/FLTK/src/Fl.cxx:605)
0x5561c423b7ad mrv::App::run()
 (/home/gga/code/applications/mrv2/mrv2/lib/mrvApp/mrvApp.cpp:1011)
0x5561c4094e3d main
 (/home/gga/code/applications/mrv2/mrv2/src/main.cpp:70)
0x7f473c429d8f __libc_start_call_main
 (../sysdeps/nptl/libc_start_call_main.h:58)
0x7f473c429e3f __libc_start_main_impl
 (../csu/libc-start.c:392)

**Comment by ManoloFLTK** [comment]
@ggarra13 I think you mentioned somewhere you're using Ubuntu 22.04 LTS Jammy.
There, package libnvidia-egl-wayland1 has version 1.1.9 whereas it's at version 1.1.13 in the all new Ubuntu LTS 24.04 Noble. Could you report here if this version difference in the Nvidia package makes any difference?

**Comment by ggarra13** [comment]
The stalls seem to be gone!!!!  However they still have bugs.  When going to main->fullscreen(), the title bar is sometimes not getting hidden.  Also, when maximizing with the button at the top right corner, the window would be too wide and go out of the desktop a tad.
Anyway, I don't think it is an FLTK bug.  Let's keep this issue open until Noble is released.

**Comment by ManoloFLTK** [comment]
Ubuntu LTS 24.04 Noble is released already!

**Comment by ggarra13** [comment]
@ManoloFLTK According to Gemini and Ubuntu 22.04.4 LTS Software Update for LTS it isn't.

**Comment by Albrecht-S** [comment]
@ggarra13 Why don't you "ask" Ubuntu directly? https://wiki.ubuntu.com/Releases
Release date is [April 25, 2024](https://lists.ubuntu.com/archives/ubuntu-announce/2024-April/000301.html).

**Comment by ggarra13** [comment]
@Albrecht-S Wow!  So why is the auto updating not notifying me of it?  I'll upgrade this afternoon with the CLI.

**Comment by Albrecht-S** [comment]
FYI: From the release announcement: _"Users of 22.04 LTS will be offered the automatic upgrade when 24.04.1
LTS is released, which is scheduled for the 15th of August."_

**Comment by ManoloFLTK** [comment]
@ggarra13  My understanding of the situation is that this issue is caused by the NVidia driver and is fixed in the last version of that driver. If that's true, I would believe the issue should be closed.

**Comment by ggarra13** [comment]
@ManoloFLTK Indeed.  It seems the problem is with the NVidia drivers.
