### ISSUE TITLE
needing the set of C++ root or top classes of FLTK 1.4

### ISSUE THREAD

**Issue by bstarynk** [fltk/fltk#975]
**Describe the bug**
There is no easy and reliable way to find the complete set of C++ classes of FLTK 1.4 (on Linux) which are not inheriting from another FLTK C++ class.

An error prone way to find them would be to run (in the `fltk/FL` source code directory)  some command similar to 

`grep 'class *FL_EXPORT *Fl_' *H|grep -v ' : '`

(which gives bad results needing human inspection of the FLTK C++ code)

**Context**

The [RefPerSys](http://refpersys.org/)  open source inference engine on https://github.com/RefPerSys/RefPerSys/ (its commit  9dfc915ac93 of may 17, 2024)

RefPerSys is a GPLv3+ software project which *generates* some (and hopefully more and more) of its C++ code at runtime, that generated C++ code is (at least conceptually) compiled as a C++ plugin to be `dlopen`-ed by RefPerSys linux process. Our goal is to generate a lot of the FLTK code needed on Linux to RefPerSys from a higher level formalism (see ideas from https://arxiv.org/abs/1109.0779 ...)

RefPerSys can be run without any graphical interface (e.g. in some `crontab` script). It is essential for us to be able to link the FLTK library and run RefPerSys without any X11 or Wayland display server. Documenting how this can be done with FLTK 1.4 should be useful to many people. On Linux the GNU emacs program can be run without any display server, so this is doable.

For the purpose of this discussion, consider RefPerSys to be some extensible interpreter (like the [fish](https://fishshell.com) is...).

**Expected behavior**
A documented way to get some machine readable format giving the set of toplevel FLTK C++ classes, or perhaps the entire inheritance graph of the full FLTK library.

(a possibility could be for the FLTK team to maintain some GCC plugin analyzing all the FLTK source code. On Linux, consider adapting and maintaining [bismon](https://github.com/bstarynk/bismon) which I don't maintain any more and needs improvement)

**FLTK Version**
 - Version: 1.4.0
 - - Operating System: Debian/x86-64 Trixie (testing)
 - Downloaded and self-built from: FLTK git commit 9df6dc2aeb37682a2ef1906e04b9e0436e63a6ba
 - - compiled with GCC 13.2.0 Debian
 -  FLTK was configured with 

```
 './configure'  'CFLAGS=-O2 -fPIC -g -Wall -Wextra' 'CXXFLAGS=-O2 -g -fPIC -Wall -Wextra'  \
      '--disable-static'      '--enable-shared' '--enable-debug' '--with-abiversion'   \ 
    '--with-optim=-g -O2 -fPIC' '--sysconfdir=/etc/local/' 
``` 

**Operating System / Platform:**
. "Linux: Debian Trixie on x86-64"
 - Processor AMD Ryzen Threadripper 2970WX 24-Core Processor
 - 32Gbyte RAM
 - 
**Proposed solutions**

Adopt more coding conventions

Define some Xmacro in your `FL/Fl.H` or other file  (see `Fl-toplevel.H` proposal below)

Provide a new file which listing in some documented format (GNU m4, or JSON)  the set of top level FLTK C++ classes and 
the entire C++ inheritance graph.

Perhaps a new file `FL/Fl-toplevel.H` with

```
// proposed FL/Fl-toplevel.H file listing FLTK toplevel C++ classes
#ifndef FLTK_TOPLEVEL_CLASS
#error FLTK_TOPLEVEL_CLASS needs to be defined
FLTK_TOPLEVEL_CLASS(Fl_Cairo_State)
FLTK_TOPLEVEL_CLASS(Fl_Surface_Device)
FLTK_TOPLEVEL_CLASS(Fl_File_Chooser)
/// etc...
```

Other possibility, have the `fltk-config`utility accept a new option: `--list-toplevel-classes` whcih would output such a file 

Regards from near Paris in France.
 
Basile Starynkevitch             <basile@starynkevitch.net>
(only mine opinions / les opinions sont miennes uniquement)
8 rue de la Faïencerie, 92340 Bourg-la-Reine, France
web page: starynkevitch.net/Basile/
See/voir:   https://github.com/RefPerSys/RefPerSys

**Comment by RokerHRO** [comment]
You might look at tools like doxygen that can parse C++ sources and their header and generate an inheritance graph in different output formats.

So that is not an FLTK question, I'd say.

**Comment by ManoloFLTK** [comment]
Pursuing with what @RokerHRO suggested, may be you could generate the Doxygen documentation of FLTK using
`make html`
and then parse file `<build directory>/documentation/html/hierarchy.html` (see https://fltk.gitlab.io/fltk/hierarchy.html) that presents the full class hierarchy of FLTK.

**Comment by MatthiasWM** [comment]
Doxygen can generate tag files that contain that information, as far as I can remember. SWIG is another tool that interprets the C++ header files to generate language bindings. pyFLTK uses it to bind FLTK to Python.

As for X11/Wayland. As long as you don;t open a display connection, FLTK will not try to connect to X11 or Wayland. This is how FLUID can be used as a pure command line tool on headless machines. Don't call `show()` on a window or `Fl::run()` and you are mostly fine. `Fl::args()` also opens the display connection to find default desktop colors.

**Comment by Albrecht-S** [comment]
OK, I believe the discussion showed that this is not a FLTK issue, i.e. not one we can solve by providing a list or anything else like the requested output. I tend to close this issue with label "wontfix".

@bstarynk If you agree, please close the issue. If not, please tell us why your request should be implemented nevertheless.
