### ISSUE TITLE
fltk.org is down

### ISSUE THREAD

**Issue by palfrey** [fltk/fltk#976]
https://downforeveryoneorjustme.com/fltk.org?proto=https&www=1

**Comment by erco77** [comment]
Yeah, something's beating up on the server and causing really heavy cpu + memory use. I'm already getting overage messages from the service provider.
Investigating.

**Comment by erco77** [comment]
Mmm, seems to be a very wide attack from a large swath of amazon aws cloud servers in the southeast. Some kind of spider that's gone bananas. It's beating up mysql and the web interface to the forum.

**Comment by erco77** [comment]
So I've punched up fail2ban a bit to try to mitigate this, as this could have financial repercussions from our provided if the cpu load gets too high again; we're only in the middle of the month here and already at a 90% watermark.
If need be I may have to switch fltk.org over to a low bandwidth set of pages if this continues.

**Comment by erco77** [comment]
Things have settled a bit now that I've got the server banning the access signatures.

![image](https://github.com/fltk/fltk/assets/6484779/4f60f64a-c382-40a3-8e87-5b161bf8c78f)

 Sheesh, 4 hours of sustained 120% cpu is bad news.
 
 Closing this; please reopen if there's more weirdness.
