### ISSUE TITLE
Fl_Window::get_size_range()

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#981]
Currently, you can set the size_range for an FLTK window.  But there's no programmatic way to retrieve those values.

**I am using FLTK**
 - v1.4.0

**Describe the solution you'd like**
A get_size_range() function that returns the values set by set by size_range().  At least the minimum values, which are the most important ones.
The values seem like they are stored internally in variables in Fl_Window.

**Describe alternatives you've considered**
Patching my own FLTK.

**Comment by MatthiasWM** [comment]
Added the method as proposed.
