### ISSUE TITLE
Wayland sends wrong events after an FL_DRAG of a top window.

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#983]
**Describe the bug**
Wayland top windows supposedly cannot be repositioned.  However, the code attached allows them to be repositioned.
However, FLTK will create only one FL_DRAG event and when released, it will turn FL_MOVE events into FL_DRAG ones.

**To Reproduce**
[fltk_wayland_handle_bug.zip](https://github.com/fltk/fltk/files/15462439/fltk_wayland_handle_bug.zip)

1. Run ./runme.sh script
2. It will build FLTK and the bug demo and run it.
3. Try it first under Wayland or XWayland to see how it is supposed to work.  It is a panel that can be docked and undocked.
4. Drag the blue floating window to the red panel.  It will turn on/off when it can be dropped.
5. Try it next under XWayland.
6. It won't work.  However...
7. Pay attention to the events that are sent to the drag bar (mrvDragButton.cpp).
8. See how the top window can be moved in Wayland and how it sends FL_DRAG events to mrvDragButton.cpp *AFTER* the mouse button is released (ie. when it should be sending FL_MOVE events).

**Expected behavior**
Ideally, I would like to have the top window reposition and dock on the dock area.
If the top window cannot be repositioned like this as documented, there still should not be FL_DRAG events sent instead of FL_MOVE ones.

**Screenshots**

**FLTK Version**
1.4.0 master

**FLTK Configure / Build Options**
See runme.sh script for cmake and SuperBuild/cmake/Build/BuildFLTK.cmake for FLTK build options.

**Operating System / Platform:**
Linux

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
Although Wayland doesn't allow to control where on screen will the compositor put a non-popup toplevel window, it allows to drag such a mapped window around with the mouse. That's shown by the `bin/examples/shapedwindow` demo of the FLTK source code. 

This issue shows a trail of FL_DRAG events remain after the end of the mouse drag procedure. I will look into this.

**Comment by Albrecht-S** [comment]
@ggarra13 Thank you for the report and for the demo program.

The following is a general advice (request), not related to the reported FLTK issue:

Gonzalo, please don't send such "complicated" demo build systems that pull FLTK from external sources (GitHub) in issue reports. You may ask: "why not"?

You address **_FLTK developers_** with your report and
- we certainly know how to build FLTK itself
- we always have a working build directory for tests or we can create one w/o downloading the entire FLTK repo
- it doesn't make sense to pull a particular git revision for testing because ...
- once we make changes (and before we push them to the official repo) we can't test changes if your build process requires to download FLTK from GitHub
- personally I never rely on executable code or scripts (`runme.sh`) w/o verifying that they are harmless (extra work to be done)
- your "superbuild" system makes it harder to decide what to do
- many source files like in this case make the devs' job harder, a **_simple example_** should consist of max. 1 or 2 source files and a top level `CMakeLists.txt` to build the demo program, nothing else.

I assume that your build instructions (_"See runme.sh script for cmake and SuperBuild/cmake/Build/BuildFLTK.cmake for FLTK build options"_) are meant to **_simplify_** testing but in fact such a build system is not helpful for FLTK devs. It is certainly useful for end users to build a project but that's another target.

Thanks in advance for simpler demo projects in future reports. We appreciate all reports!

**Comment by ManoloFLTK** [comment]
With the commit mentioned above, FL_DRAG events should no longer be sent after the end of the window drag operation with the mouse.

The question of how to detect that the dragged window has been moved above another window remains open. I don't see right now how to do that under Wayland.

**Comment by ggarra13** [comment]
I understand now clearly.  I will try to make my top windows child windows parented to the main ui and report back of my findings.

**Comment by ggarra13** [comment]
I am reopening the issue as I have now modified my sample test program to work with child windows.  I've still kept the superbuild, but you can easily compile it without it, by just running cmake on the main Makefile.

[wayland_child_window_bug.zip](https://github.com/fltk/fltk/files/15476790/wayland_child_window_bug.zip)

See the README.txt for more info.  Summary:

The behavior under X11 or XWayland with top windows works as desired.
The behavior under X11 or XWayland with child windows works but clips the subwindows at the edges of the main window.
The behavior under Wayland is broken.  Coordinates are all wrong as can be seen in the printouts of Debug builds.

**Comment by ManoloFLTK** [comment]
OK. I had checked that a subwindow can be fully non intersecting with its parent, and it works OK. But, when the subwindow partially intersects its parent, a feature previously asked clips the subwindow to its intersection with its parent. That has been done for Wayland (and also for macOS) to make these platforms behave as X11 and Windows do, that is where a subwindow doesn't extend beyond the limits of its parent. I'm reluctant to remove that feature that was asked in other contexts.

My feeling at this point is that Wayland doesn't offer yet a solution to dock a window.

**Comment by ggarra13** [comment]
@ManoloFLTK Two things:

1) Did you fix the values that Fl::event_x_root() and Fl::event_y_root() were returning.  I was getting negative values for Y.

> OK. I had checked that a subwindow can be fully non intersecting with its parent, and it works OK.

2) Could that be made a toggle?  By default have it behave like X11 or Windows, but if turned off, allow non-clipping windows?  Animators and compositors in VFX will really need that feature.

**Comment by ManoloFLTK** [comment]
> Did you fix the values that Fl::event_x_root() and Fl::event_y_root() were returning. I was getting negative values for Y.

Negative values are correct. Wayland completely hides the position of a toplevel window in its display. Fl::event_x_root() cannot return the position of the event relatively to the screen. It returns it relatively to the  toplevel window's top left. If the subwindow is to the left of its parent, Fl::event_x_root() is negative.

> Could that be made a toggle? 

That's a problem because that would be a platform-specific feature to undo a platform-independent feature.

**Comment by ggarra13** [comment]
> It returns it relatively to the toplevel window's top left.

No, I think it is currently broken.  See this picture:

![Captura desde 2024-05-29 09-27-16](https://github.com/fltk/fltk/assets/6072843/871b13e1-6083-4533-a217-92a82192408c)

I am positioning my subwindow with Fl::event_x(), which returns 948, which looks correct to me.  However, Fl::event_x_root() returns incorrectly 1919 (the edge of my screen) and clamps it there (I cannot move it further). 

By using the 'yellow button' and clamping the subwindow to x/y/w/h of the main drop window, I am able to get a work-around.
Working with Fl::event_x()/y() I am able to move the subwindow past the boundary of the main ui, albeit it flickers and gets clamped.

If I use Fl::event_x_root() to position it, I get values like -15405050 or something like that.

I am attaching a new version of my demo program for you to test:
[wayland_child_window_bug_v2.zip](https://github.com/fltk/fltk/files/15484318/wayland_child_window_bug.zip)

I consolidated all the querying of position routines in mrv::DragButton::get_global_coords().

**Comment by ggarra13** [comment]
Okay.  You make me work hard.  Here's a working version (sans clipping solution):

[wayland_child_window_solved.zip](https://github.com/fltk/fltk/files/15486674/wayland_child_window_bug.zip)

**Comment by ManoloFLTK** [comment]
Excellent!

**Comment by ManoloFLTK** [comment]
It seems the clipping of the subwindow is effective with resize operations but not when the subwindow is just moved inside its parent. So the docking works. Very good.

@ggarra13  I would believe the issue may be closed again.

**Comment by ggarra13** [comment]
@ManoloFLTK I believe clipping is still a big issue for Wayland subwindows and a limitation of FLTK for something not present in Wayland.  I've had to go through a lot of hoops in my code to try to avoid it.  So I may close this issue and open another one specific to the clipping problem, which I sustain should be modified as Wayland is here to stay it seems.

**Comment by ggarra13** [comment]
I'm attaching the latest version of my test, which adds more Wayland work-arounds.  I have added an avoid_clipping function to the PanelGroup to shift and worse case scenario, resize the windows when they are created or undocked.  I have to do that as I rescale the windows based on content (ie. when I load the first video of different size than the main window).

[wayland_child_window_bug.zip](https://github.com/user-attachments/files/15519455/wayland_child_window_bug.zip)

@ManoloFLTK There's another issue under Wayland with subwindows is that these will scale with the main window even if resizable for them is 0.  You can see the problem if you put the "Drag1 me!" window outside the main window (say to the right) and scale the main window.  Is that a bug or a "feature"?

**Comment by ggarra13** [comment]
> [](https://github.com/user-attachments/files/15519482/wayland_child_window_bug.zip)
> 
> @ManoloFLTK There's another issue under Wayland with subwindows is that these will scale with the main window even if resizable for them is 0. You can see the problem if you put the "Drag1 me!" window outside the main window (say to the right) and scale the main window. Is that a bug or a "feature"?

Solved it.  I am closing this issue and will open a new issue about removing clipping from Wayland.
