### ISSUE TITLE
Problems when using PNG images compiling on a Mac with STANDARD ARCHITECTURE (Apple Silicon + Intel)

### ISSUE THREAD

**Issue by robbwheel** [fltk/fltk#984]
Problems when using PNG images compiling on a Mac with STANDARD ARCHITECTURE (Apple Silicon, Intel)

I got some undefined symbol errors when compiling for both architectures (Apple silicon + intel)  on an Intel Mac:

Undefined symbol: _png_do_expand_palette_rgb8_neon

Undefined symbol: _png_do_expand_palette_rgba8_neon

Undefined symbol: _png_init_filter_functions_neon

Undefined symbol: _png_riffle_palette_neon

It seems the libraries are not compiled correctly for Apple Silicon ARM  even when compiling the libraries using STANDARD ARCHITECTURE (Apple Silicon, Intel). The universal format libraries generated miss some ARM functions

It has something to do do detect the correct architecture to build, the point is that arch must be compiled also when using an Intel Mac if selecting the STANDARD ARCHITECTURE (Apple Silicon, Intel)

When compiling for intel only all are fine.

Any additional #define to be used to compile the libfltk_png.lib? (I see there are a lot of #ifdef in the code .. in the png lib code)

**Comment by ManoloFLTK** [comment]
Please, describe in a bit more detail how you make this failing build. Here, I build successfully FLTK and libfltk_png for 4 architectures (ppc, i386, x86_64, arm64) with CMake with these commands for the last 2 architectures :
```
set TARGETS="-target arm64-apple-macos11.0 -target x86_64-apple-macos10.9"
/Applications/CMake.app/Contents/bin/cmake -S $source -B $build \
-DFLTK_BUILD_GL=0 -DFLTK_BUILD_HTML_DOCS=0 -DFLTK_BUILD_FLUID=0 \
-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
-DFLTK_ARCHFLAGS="$TARGETS" 

cd $build
make -j6 fltk_images device
```

**Comment by robbwheel** [comment]
I can build them too! ..  but not all the calls are implemented
I correctly created the libraries too with Xcode 
The problem were when I embedded a png in fluid and went to access it , the necessary calls were missing from the libfltk_png.a  library 

You need even to try returning the image with 'return image_App1281()->copy();'
I tried in the same code still leaving all the code in place and it works till I don't call the 'return image_App1281()->copy();'  returning another pic in SVG works perfectly, returning a JPEG works fine too with the built libs

This is the code for returning the PNG (pic data omitted use your own pic):

--------------------------------------------------------

static const unsigned char idata_App1281[] =
{ /* ... 20531 bytes of binary data... */ };
static Fl_Image *image_App1281() {
  static Fl_Image *image = NULL;
  if (!image)
    image = new Fl_PNG_Image("App128.png", idata_App1281, 20531);
  return image;
}





Fl_Double_Window* AppImages::make_window() {
  { noUsedWindow = new Fl_Double_Window(900, 829);
    noUsedWindow->user_data((void*)(this));
    { appIcon128 = new Fl_Box(195, 513, 128, 128);
      appIcon128->image( image_App128() );
      appIcon128->align(Fl_Align(FL_ALIGN_WRAP));
      Fl_Group::current()->resizable(appIcon128);
    } // Fl_Box* appIcon128
    { Fl_Box* o = new Fl_Box(25, 25, 100, 100, "pngTest");
      o->image( image_App1281() );
      o->labelsize(10);
    } // Fl_Box* o
    noUsedWindow->end();
  } // Fl_Double_Window* noUsedWindow
  return noUsedWindow;
}

Fl_Image* AppImages::getAppIcon128() {
  return image_App1281()->copy();
}


these are the resulting error using this libfltk_png.a library that was built perfectly and till I tried to use it I was think could work perfectly:


Undefined symbol: _png_do_expand_palette_rgb8_neon

Undefined symbol: _png_do_expand_palette_rgba8_neon

Undefined symbol: _png_init_filter_functions_neon

Undefined symbol: _png_riffle_palette_neon

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by ManoloFLTK** [comment]
I build and run here for STANDARD ARCHITERCTURE with Xcode 15.4 this program and get no error. The resulting app can be run on my M1 MacBook Pro both as an arm binary or as an x86_64 binary with Rosetta.

```
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_PNG_Image.H>
#include <stdio.h>

static Fl_Image *image_App1281() {
  static Fl_Image *image = NULL;
  if (!image) {
    FILE *in = fopen("<path/to/ftlk/source>/misc/lorem_ipsum.png", "r");
    fseek(in, 0, SEEK_END);
    int s = ftell(in);
    rewind(in);
    unsigned char *data = new unsigned char[s];
    fread(data, s, 1, in);
    fclose(in);
    image = new Fl_PNG_Image(NULL, data, s);
  }
  return image;
}

Fl_Window* make_window() {
   Fl_Window *noUsedWindow = new Fl_Window(900, 829);
    { Fl_Box *appIcon128 = new Fl_Box(195, 513, 200, 200);
      appIcon128->image( image_App1281() );
      appIcon128->align(Fl_Align(FL_ALIGN_WRAP));
      Fl_Group::current()->resizable(appIcon128);
    } // Fl_Box* appIcon128
    { Fl_Box* o = new Fl_Box(25, 25, 200, 200, "pngTest");
      o->image( image_App1281() );
      o->labelsize(10);
      o->image()->scale(300,300);
    } // Fl_Box* o
    noUsedWindow->end();
  return noUsedWindow;
}

Fl_Image* getAppIcon128() {
  return image_App1281()->copy();
}

int main(int argc, char ** argv) {
  Fl_Window * w2 = make_window();
  w2->show(argc, argv);
  Fl::run();
  return 0;
}
```

**Comment by Albrecht-S** [comment]
I can't help directly, but here are three points I noticed:
1. I don't see that the undefined symbols are prefixed with `'fltk_'` in our build process of libpng. If they are used, then they should also be prefixed.
2. There's a preprocessor macro `PNG_ARM_NEON_IMPLEMENTATION` that may need to be defined (1 or 2) to compile the relevant code.
3. There may be a compiler switch needed to compile the specific "neon" code (whatever this is).
See
```
png/arm/filter_neon_intrinsics.c-18-/* This code requires -mfpu=neon on the command line: */
png/arm/filter_neon_intrinsics.c:19:#if PNG_ARM_NEON_IMPLEMENTATION == 1 /* intrinsics code from pngpriv.h */
png/arm/filter_neon_intrinsics.c-20-
```

Just my 2 ct in the hope that it may help.

**Comment by ManoloFLTK** [comment]
All `png_*_neon` symbols are private, internal to libpng, so it's nominal they aren't redefined with the fltk_ prefix. FLTK uses none of these symbols.

File pngpriv.h contains this:
```
    * It is possible to set PNG_ARM_NEON_IMPLEMENTATION in CPPFLAGS, however
    * this is *NOT* supported and may cease to work even after a minor revision
    * to libpng. 
``` 
To me, this means the user needs not fiddle with how PNG_ARM_NEON_IMPLEMENTATION is or isn't defined. It's all done inside libpng at build time.

**Comment by ManoloFLTK** [comment]
>  I tried in the same code still leaving all the code in place and it works till I don't call the 'return image_App1281()->copy();' 

This is bizarre because the `copy() `member function for an Fl_PNG_Image object uses zero symbol of libpng.  The copying operation processes the Fl_PNG_Image as an Fl_RGB_Image, that is, as an array of RGB(A) bytes. libpng isn't needed to copy that.

**Comment by robbwheel** [comment]
I suppose the problem is present ONLY on intel compiling for AppleSilicon
Maybe there is a macro activated _only_ when on AppleSilicon so the compilation on intel for apple silicon generates a lib with non all the code inside the functions (maybe it checks the running platform and not the requested architecture) ?

**Comment by ManoloFLTK** [comment]
I'll be able to do the compiling, building and running on an x86_64 MacBook Pro, so we'll know.

**Comment by robbwheel** [comment]
I started from scratch and investigated a bit more
inside a fresh flak download:

I built all and
On an Intel Mac _using_ the $(ARCHS_STANDARD) the libfltk_png.a is not built at all, while the other libraries are built correctly
I went for a check inside the jpeg folder, I typed make and yes it is built (just to test)
then
I went inside the png folder and typed 'make' and bum:
This is what happens on an Intel Mac (Mac mini i7 2018) both selecting or not : FLTK_USE_SYSTEM_LIBPNG
```
Last login: Fri May 31 11:42:08 on ttys001
roberto@MacMini png % make
Compiling png.c...
In file included from png.c:14:
./pngpriv.h:945:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM       "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
make: *** [png.o] Error 1
roberto@MacMini png % 
```

I think this could help

**Comment by robbwheel** [comment]
Ok I think I realized where the problem is:
If you compile on Mac in the usual way on Xcode indicating a minimum SDK  (as you  usually do in Xcode) the PNG compilation will fail for the arm part (if you provided a target less then macOS 11)
You need to indicate a different target system for the arm64-apple and x86_64-apple, otherwise you will get big trouble
That can be an error that many macOS developers can do because usually Xcode solves it.

So in same way to do not make a mess with libraries you need to generate with different macOS target for the 2 different platform
as example using:
set TARGETS="-target arm64-apple-macos11.0 -target x86_64-apple-macos10.13"
a thing that usually in macOS programming you don't do because Xcode solves it by itself, I even think you can't differentiate the target os for platform in the same build object (not sure)

In that case you need
Also using the app CMake, if you insert for example 10.13 it will not work and it will fail, but it will fail not for all, if you generate with Xcode as example it doesn't fail for libfltk.a  but it generates a libfltk_png.a working only for intel

Better to inform the Mac users so on how to proceed
I'm not sure if insite the Cmake graphical app can be inserted the different targets for the different platforms
I will check. 
For sure  manoloFLTK knows

**Comment by robbwheel** [comment]
So problem solved, (see above).
Thank you to Manolo for the right script that let me understand where the trouble was using Xcode to compile (apparently it was ok, but it was not)

**Comment by ManoloFLTK** [comment]
> I even think you can't differentiate in Xcode the target os for the 2 different platforms in the same build object (not sure)

Xcode's build settings allow to control the deployment target per architecture as shown here:
<img width="550" alt="image" src="https://github.com/fltk/fltk/assets/41016272/f87888af-aa20-44bd-939d-c8976125f1d6">
