### ISSUE TITLE
Zero-sized borderless window causes high cpu usage on windows

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#985]
**Describe the bug**
A Zero-sized borderless window causes high cpu usage on windows.
This was reported here:
https://github.com/fltk-rs/fltk-rs/issues/1555

**To Reproduce**
Build the following program on windows and run it. Observe high cpu usage vs giving the window any size.
```c++
#include <FL/Fl_Double_Window.H>
#include <FL/Fl.H>

int main() {
    auto *win = new Fl_Double_Window(0, 0, 0, 0);
    win->border(false);
    win->end();
    win->show();
    return Fl::run();
}
```

You can check the high usage in the task manager for example.

**Expected behavior**
A borderless zero-sized window shouldn't consume much resources.

**FLTK Version**
 - Version: 1.4
 - If from Git, branch: ,master

**FLTK Configure / Build Options**
 - cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Debug ...
I was also able to observe the same behavior on older versions of FLTK, the one downloadable on msys2 for example: mingw64/mingw-w64-x86_64-fltk 1.3.8-1

**Operating System / Platform:**
Windows 11 x64bit, with both msvc and mingw targets.

**Comment by ManoloFLTK** [comment]
I get 0% cpu usage here under Windows 11 inside a VM on my MacBook Pro. I see a window reduced to its titlebar.

**Comment by ManoloFLTK** [comment]
Sorry, I had used a window with a border. Adding `window->border(0);` I do see the high cpu usage.

**Comment by ManoloFLTK** [comment]
That should be fixed with the commit mentioned above.

**Comment by MoAlyousef** [comment]
Thanks @ManoloFLTK 

I no longer see the high cpu usage.
