### ISSUE TITLE
Changing FLTK's default color pallete effects how widgets and opengl child drawings are composited on Wayland

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#989]
**Describe the bug**
In my application, I allow customization of colors by calling Fl::set_color(x, r, g, b) and reading the colors from a file (in a format Greg Ercolano invented).  The color customization works fine under Wayland (the colors change the UI correctly).
However, opengl1 drawings or FLTK child widgets drawn in an OpenGL window with:

        Fl_Gl_Window::draw_begin(); // Set up 1:1 projection
        Fl_Window::draw(); // Draw FLTK widget's children
        glViewport(0, 0, viewportSize.w, viewportSize.h);
        _drawGL1TextShapes();
        Fl_Gl_Window::draw_end(); // Restore GL state
        
results in items composited as if they had 0.5 alpha.

The problem happens on Wayland only.  macOS, Windows and X11 are fine.

**To Reproduce**
[color_scheme.zip](https://github.com/user-attachments/files/15741225/color_scheme.zip)

1. Compile using cmake, to locate GLEW and FLTK, like:
```
     mkdir build
     cd build
     cmake .. -D CMAKE_PREFIX_PATH=<FLTK_INSTALLED_LOCATION>
     make
```
2.  Run the program:

      main
      
3.   Click on "Color Change" button.
4.   Type on the second box (an Fl_Multiline_Input).
5.   See how the Fl_Multiline_Input draws its text with opacity.

**Expected behavior**

**Screenshots**

Here's with FLTK's default color pallette (compositing works fine):
![Normal_Pallette](https://github.com/fltk/fltk/assets/6072843/538d573e-2b81-4e84-9a40-97eac1ef42c0)

Here's with modified FLTK's color pallete (compositing looks semi-transparent):
![Black_Pallette](https://github.com/fltk/fltk/assets/6072843/d62e7d79-8eaf-4192-a72b-9251c5fb7469)

**FLTK Version**
1.4 Master

**FLTK Configure / Build Options**

**Operating System / Platform:**
OS: Linux
OS Version: Ubuntu 22.04.4 LTS

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ggarra13** [comment]
@ManoloFLTK I submited a small compilable example.  Were you able to reproduce the issue with the Mesa drivers or is it an NVidia issue?

**Comment by ManoloFLTK** [comment]
Here is what I get here with the mesa driver on Ubuntu 24.04. The red text doesn't seem to be drawn partly transparent:
<img width="803" alt="image" src="https://github.com/fltk/fltk/assets/41016272/489e9477-e6d2-4bf7-9864-d1001444e58b">

**Comment by ggarra13** [comment]
It seems you don't have applied the color pallette.  Here's what the image should look like (the color scheme in the panel to the right should have changed):

![Wayland](https://github.com/fltk/fltk/assets/6072843/1d107be8-405d-4ce7-8501-2edc4461f2d2)

The letters may not look red (I believe the color scheme turns them into dark red), like XWayland:

![XWayland](https://github.com/fltk/fltk/assets/6072843/2a39ef36-5df0-412d-9b55-caea1e845b32)

**Comment by ggarra13** [comment]
If you compiled the test with fltk-config or did not use an installed version of FLTK, you might not have gotten the path to the mrv2.colors file (I used a relative path to it, based on my instructions)

**Comment by ManoloFLTK** [comment]
Here is what I get here with the mesa driver on Ubuntu 24.04 with the changed color scheme. The red text doesn't seem to be drawn partly transparent:

<img width="805" alt="image" src="https://github.com/fltk/fltk/assets/41016272/8309cf6f-a18a-4814-a119-ea8c1dc1a268">

**Comment by ManoloFLTK** [comment]
The commit mentioned above hopefully fixes the issue.

**Comment by ggarra13** [comment]
I confirm it fixes the issue.
