### ISSUE TITLE
Fl_Pack should override clear() to set resizable(0)

### ISSUE THREAD

**Issue by flpack** [fltk/fltk#993]
Fl_Pack's default resizable() is 0, this is set in constructor and is different from Fl_Group, for which it is **this**.
But when one calls clear(), resizable() gets set to **this** because it is Fl_Group::clear() which is called. Need to override clear() and set resizable(0) there. Thanks.

The issue is present in latest git master.

**Comment by ManoloFLTK** [comment]
@flpack This issue should be fixed with the commit mentioned above. Please, close issue if you confirm.

**Comment by ManoloFLTK** [comment]
Closing this for lack of feedback from OP.
