### ISSUE TITLE
Allow replacing an element of an Fl_Group (without deleting it)

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#994]
I have been playing with pyFLTK and have been enjoying it.  However, I run into what appears a limitation in its interaction with FLTK's API that would effect probably any other language binding too.

I am trying to change the order of the Fl_Widgets in an Fl_Group, similar to what it is done in Fl_Scroll:

```
void Fl_Scroll::fix_scrollbar_order() {
  Fl_Widget** a = (Fl_Widget**)array();
  if (children() > 1 &&
      (a[children()-2] != &scrollbar ||
       a[children()-1] != &hscrollbar)) {
    int i, j;
    for (i = j = 0; j < children(); j++) {
      if (a[j] != &hscrollbar && a[j] != &scrollbar)
        a[i++] = a[j];
    }
    a[i++] = &scrollbar;
    a[i++] = &hscrollbar;
  }
}
```

On Python, there's no way to deal with the pointers directly, afaik.  And doing something, like:

```
      # store widgets
      widgets = []
      for x in range(self.children()):
            widgets.append(self.child(x))
       
       # Sort them     
       widgets = sort_by_some_method(widgets)
      
       self.clear()          # undefined behavior, as FLTK will call "delete" on all the pointers
       for widget in widgets:
              self.add(widgets)
```

I would like to do:

```
      widgets = []
      for x in range(self.children()):
            widgets.append(self.child(x))
            
     # Sort them     
      widgets = sort_by_some_method(widgets)
            
       # Replace them, without deleting the original ones
       for index, widget in enumerate(widgets):
              self.replace(idex, widget, delete=False)
```

**I am using FLTK**
 - 1.4.0 master

**Describe the solution you'd like**
Either one of two things (whatever is easier):
   1) Add a flag to Fl_Group to have clear() and remove() not call "delete widget" on its children.
   2) Add a Fl_Group::replace(idx, Fl_Widget& w) to replace the widget at index idx (no bound checking, etc) and, optionally, without deleting the original pointer.

**Describe alternatives you've considered**
Create my own derived C++ Fl_Group and expose it in pyFLTK.

**Comment by Albrecht-S** [comment]
This is a question you should probably ask in pyFLTK support/forum/group/whatever.

As far as FLTK is concerned, did you consider using `Fl_Group::remove(child)` which removes the child widget w/o deleting it? This should be supported by pyFLTK as well (is it?), and if it is you could do something as in your first example, replacing `self.clear()` with a loop that removes all children.

_Disclaimer:_ I don't know how pyFLTK (i.e. python itself) operates (WRT memory management) but I believe it uses some kind of garbage collection. Thus, as long as you store all the widgets in the array `widgets[]` they should be "safe" from deletion while you `remove()` them from their parent group. Please correct me if that's not true.

Another approach would be to use the FLTK equivalent of [`Fl_Group::insert()`](https://www.fltk.org/doc-1.4/classFl__Group.html#a837959459836c8dfc3e734d51bb2607f) after sorting your widgets in pyFLTK. Insert them in the new order, one by one, at position 1, 2, 3, ...
See the docs linked above, particularly the sentence _"This can also be used to rearrange the widgets inside a group"_. While doing this, all widgets are removed and re-inserted at the requested position.

**Comment by Albrecht-S** [comment]
I just noticed that you wrote:
> Add a flag to Fl_Group to have clear() and remove() not call "delete widget" on its children.

Your implied assumption in this statement is incorrect: [Fl_Group::remove()](https://www.fltk.org/doc-1.4/classFl__Group.html#a7f79b03771b0f4c508e11c5f427ec85a) does **_NOT_** delete the child widget - as I wrote above (see the linked docs).

**Comment by ggarra13** [comment]
> Your implied assumption in this statement is incorrect: [Fl_Group::remove()](https://www.fltk.org/doc-1.4/classFl__Group.html#a7f79b03771b0f4c508e11c5f427ec85a) does **_NOT_** delete the child widget - as I wrote above (see the linked docs).

Indeed.  I had missed that detail and both Robert Arkiletian (of pyFLTK) and yourself pointed me in the right direction.  I am closing the issue.  I apologize.
