### ISSUE TITLE
Wayland hang with a subwindow inside Fl_Flex

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#996]
**Describe the bug**
While modifying the subwindowV2.cxx of Manolo to debug it to see where it was failing I run into a hanging bug on my Ubuntu 24.04.4 LTS box when I changed one Fl_Group to an Fl_Double_Window.

**To Reproduce**
[manolo_subwindowV5.cxx.txt](https://github.com/user-attachments/files/16036935/manolo_subwindowV5.cxx.txt)

1. Compile with fltk-config --compile
2. Run it under Wayland (hangs on me without opening any window -- just icon on the dock)
3. Run it under XWayland or X11 (works fine)
4. Comment out the #define WAYLAND_HANGS line to use an Fl_Group instead of a Fl_Double_Window.
5. With the Fl_Group, Wayland does not hang. 

**Expected behavior**
Not hang in any of the cases.

**Screenshots**
N/A

**FLTK Version**
 - Version: 1.4.0 master

**FLTK Configure / Build Options**
cmake defaults.

**Operating System / Platform:**
Linux

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Comment by ManoloFLTK** [comment]
I had seen that too, and its fix is the purpose of commit 55daede.
